### ISSUE TITLE
Rename or recreate the repo

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#1]
Please at least rename this repo to "aries-cloudagent-python" in preparation for transferring it to Hyperledger.  Alternatively create a new repo by that name.  Either way, please make sure that the standard BC Gov files are put into the repo - licence, contributions, etc.  All repos should always have that, and Shea mentioned there might be a tool for doing that.

@nrempel - should we just create a new repo, or use this one?  Remember that we want the commit history on the files.

Thanks!

**Comment by WadeBarnes** [comment]
All issues have been transferred to the new repo, and the `indycat-agent` has been deleted.
