### ISSUE TITLE
Error in presentation proof verification when trinsic wallet is used as a client/holder

### ISSUE THREAD

**Issue by konsmosc** [hyperledger/aries-cloudagent-python#1002]
This issue happens only when I am using trinsic wallet.
I have configure the von_network and the indy_tails_server and I am running an aca-py instance version 0.6.0 with the following starting params:
--inbound-transport http 0.0.0.0 8050 
--outbound-transport http --admin 0.0.0.0 8051 
--admin-insecure-mode 
--public-invites 
--endpoint http://{ip}:8050 
--genesis-url http://{ip}:8000/genesis 
--label "Issuer Agent" 
--auto-ping-connection 
--auto-accept-requests 
--auto-respond-credential-proposal 
--auto-respond-credential-request 
--auto-verify-presentation 
--seed 000000000000000000000000000Agent 
--tails-server-base-url http://{ip}:6543 
--wallet-key issuer 
--wallet-name issuer_agent 
--wallet-type indy 
--auto-provision

After the creation of a schema and a credential definition, I have manage to make a connection with the trinsic wallet, to issue-credentials and when I send a request for proof, if the credential is non-revoked, everything is fine. But, when I revoke the credentials and then ask again for a proof request, I get a **"verified":"true"** field into the present-proof record.

I use the **POST /present-proof/send-request** service from the aca-py using as body:
{
    "connection_id": "<Enter a valid Connection ID>",
    "proof_request": {
        "name": "<Proof of Request name>",
        "version": "1.0",
        "requested_attributes": {
            "0_<attribute name>_uuid": {
                "name": "<attribute name>",
                "non_revoked": {
                    "to": <current timestamp in seconds>
                },
                "restrictions": [
                    {
                        "cred_def_id": "<Enter a valid Credential Definition ID>"
                    }
                ]
            }
        },
        "requested_predicates": {}
    }
}

Expected behaviour:
The field **"verified"** should have the value **false**

I share with you the responses of the /present-proof/records/{pres_ex_id} for both presentation exchange records (before and after the revocation of the credentials) into the txt.
[responses.txt](https://github.com/hyperledger/aries-cloudagent-python/files/6049331/responses.txt)

**Comment by sklump** [comment]
The presentation request does not specify a non-revocation interval, so it does not care about revocation status. See https://github.com/sklump/aries-rfcs/tree/441-present-proof-best-practices/concepts/0441-present-proof-best-practices#presentation-requests-and-non-revocation-intervals
