### ISSUE TITLE
Aries OpenAPI Demo Errors 

### ISSUE THREAD

**Issue by mobinauten** [hyperledger/aries-cloudagent-python#1005]
Following the Demo Script I have following issues:

1. Issuing a credential I receive the following error - "Error: agent Faber.Agent has no method handle_issue_credential to handle webhook on topic issue_credential"
2. Trying to find the Public DID on the ledger http://dev.greenlight.bcovrin.vonx.io. returns Null 

Thanks 
Olli

**Comment by mobinauten** [comment]
This is Alice side's Error: agent Alice.Agent has no method handle_issue_credential to handle webhook on topic issue_credential

**Comment by sklump** [comment]
The code now uses v2 of these protocols: I will update the docs accordingly
