### ISSUE TITLE
Running Acapy agent always requires registering a public DID regardless of whether its role will be an issuer or not

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#1007]
Whenever running a new Acapy agent, it always requires a public DID to be registered in an Indy ledger network (e.g. von) regardless of if the agent will be used as an issuer. The error returned from the agent is shown below:
`aries_cloudagent.config.base.ConfigError: Ledger rejected transaction request: client request invalid: could not authenticate, verkey for VV9pK5ZrLPRwYmotgACPkC cannot be found.`

Expected result: 
Theoretically, only an agent that is going to be an issuer should need a public DID. So an agent that is NOT going to be an issuer shouldn't need a public DID registered on an Indy ledger network.

**Comment by TimoGlastra** [comment]
I think `--wallet-local-did` should do the trick:

> If this parameter is set, provisions the wallet with a local DID from the '--seed' parameter, instead of a public DID to use with a Hyperledger Indy ledger.

**Comment by yunxi-zhang** [comment]
Thanks @TimoGlastra , also figured out without having a --seed parameter could make acapy agent run. Will close this ticket.

**Comment by yunxi-zhang** [comment]
see last comment.
