### ISSUE TITLE
Alice demo: Type Error: expected str, bytes or os.PathLike object, not int 

### ISSUE THREAD

**Issue by GuilhermeMenezes** [hyperledger/aries-cloudagent-python#1008]
Hi,

I'm trying to run the Aries demos... but I'm getting an error when I run Alice.

I'm using Ubuntu 20.04.1  and when I run faber everything works well, it expects a connection...
command used:
LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo faber

But when I run Alice I get this error:
![runningAliceTypeError](https://user-images.githubusercontent.com/11176973/109968381-8a55c380-7cea-11eb-92e2-ca2f0d91c465.JPG)
command used:
LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo alice

I can't seem to find a solution or a cause of this problem... Have anyone seen this before?
Thanks in advance.

**Comment by swcurran** [comment]
I'm running on Ubuntu 18.04 and everything worked fine.  I notice that some of the messages from the script I'm running are different from yours -- notably:

```
~/repos/aries-cloudagent-python/demo [main] 09:32 $ LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo alice
Preparing agent image...
sha256:8c1508e46dc1a6dca8dd634dc49bca3e588c19966d858a55fbec18f0a9a50f4b
Trying to detect ngrok service endpoint
ngrok not detected for agent endpoint
172.17.0.1
Starting [alice] agent with args [--port 8030]

#7 Provision an agent and wallet, get back configuration details
Alice      | ['/home/indy/.pyenv/versions/3.6.13/bin/python', '-m', ...
```

Is it possible you aren't up to date on the code?  Even then, I wouldn't expect a problem.

I'm running the same python 3.6.9, so it's not that.

@ianco -- any ideas on what might be wrong?

**Comment by ianco** [comment]
> @ianco -- any ideas on what might be wrong?

No, it's odd that faber works but alice doesn't, they both use the same common code to start up the agent

**Comment by GuilhermeMenezes** [comment]
I figured it out, I was giving it a specific seed instead of a random one. My fault, thanks for your reply though! On 5 Mar 2021 17:41, Ian Costanzo <notifications@github.com> wrote:

@ianco -- any ideas on what might be wrong?

No, it's odd that faber works but alice doesn't, they both use the same common code to start up the agent
