### ISSUE TITLE
Possible Error in demo multi-tenancy

### ISSUE THREAD

**Issue by JulianNicholls** [hyperledger/aries-cloudagent-python#1011]
This may be a total lack of understanding on my part, but I think that there is a problem with the DemoAgent in multi-tenancy mode.

I am running Alice as multitenant and Faber as single.

I make the initial connection to 'Alice.initial' wallet by accepting an invitation from Faber.

I then create a new wallet 'Julian' and create an invitation from Faber and accept it to this wallet.

Then, I switch back to 'Alice.initial' and create an invitation from Faber and accept it. Alice.initial should now have two connections. I can see that the call to /receive-invitation is made with the authorization token of 'Julian', this is presumably the problem.

If I check connections by GET /connections with the 'Alice.initial' authorization token, I see one connection, not the two I expect. 
Getting the connections with the 'Julian' authorization token, I see two connections, rather than one.

I can see that self.managed_wallet_params is only updated when a wallet is created, not when a wallet is re-opened. This leaves self.managed_wallet_params["token"] holding the token of the last wallet created, rather than the token of the last wallet opened.
It seems to me that the previous contents of self.managed_wallet_params are lost when creating a new wallet, and are therefore not available to go back to when re-opening a previous wallet.

**Comment by TimoGlastra** [comment]
Thanks for opening this issue @JulianNicholls!

Seems like we'd need to either store all of the wallet tokens, or we can call the `/multitenancy/wallet/{wallet_id}/token/` endpoint to retrieve the token. I think I'd prefer the latter.

Do you want to take a shot at this yourself @JulianNicholls?

**Comment by JulianNicholls** [comment]
I'm glad that I have understood correctly.

I agree that calling the `/multitenancy/wallet/{wallet_id}/token/` endpoint is a better way of fixing it.

I would like to have a go at fixing it, during w/c 08-Mar, and I will submit a pull request when it's ready.

**Comment by JulianNicholls** [comment]
I have submitted pull-request #1017 to fix this. It's my first pull-request to this project, so I'm not 100% sure if I've done it right.
