### ISSUE TITLE
Calling API for sending a presentation returns an error showing no revocation registry id is found even though i've set up a revocation registry

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#1012]
I have run two agents, one as **Issuer(Verifier)** and the other as **Holder.**  I've set up a revocation registry by calling below apis In the **Issuer** agent step by step: 
1. /revocation/create-registry (POST), 
` API Response: Result:   "revoc_reg_id": "VV9pK5ZrLPRwYmotgACPkC:4:VV9pK5ZrLPRwYmotgACPkC:3:CL:8:esg:CL_ACCUM:fd8d371a-b345-4867-ad01-591647a6f862", omitting other response`
2. /revocation/registry/{id} (PATCH) 
3. /revocation/registry/{id}/definition (POST) and 
4. revocation/registry/{id}/tails-file(PUT).

The issuer has successfully issued a credential to the Holder and the credential can be found in the Holder's agent. After the Issuer(Verifier) sends a request proof request to the Holder, and calling the api: /present-proof/records/{pres_ex_id}/send-presentation, I've got the below error:

`400: Error when constructing proof: Error: Invalid structure. Caused by: RevocationState not found by id: RevocationRegistryId("VV9pK5ZrLPRwYmotgACPkC:4:VV9pK5ZrLPRwYmotgACPkC:3:CL:8:esg:CL_ACCUM:b4ddc084-690a-4dc0-86d0-978b51ff359a"). CommonInvalidStructure.`

When I checked the the Revocation registry Id shown in the error, it is a different ID as the one generated in the api call at step 1 as shown above. Mainly the last string (i.e. after "CL_ACCUM") in the two responses are different.

Also, when calling the send presentation api, there is no value I can set in the JSON body to tell the api which revocation registry id it should look at. 

What's wrong in my process?

**Comment by swcurran** [comment]
I think you are making it too hard on yourself.

When we first implemented revocation, we added the endpoints that you are using.  And it was difficult for a controller to have to manage everything.  We then went back and hid all the complexity of revocation, so that the only things you need to do are:

- when creating a cred-def, flagging that you want to use revocation, how big a registry (default 1000).  It handles everything to do with the revregs on the ledger (it creates two at this time) and the tails file.  I think there is a startup param for the tails server URL.
- when issuing credentials -- track the info needed for revocation.  ACA-Py figures if the active revreg is full, and if so, switches over to the next one and triggers the creation of another one.
- use an endpoint to revoke a credential, optionally publishing it
- use an endpoint to publish any revoked credentials not yet published (e.g. a batching capability)

That should be all you need to do.  Suggest you look at the "--revocation" option in the demos to see how the APIs work.

**Comment by yunxi-zhang** [comment]
Thanks for your answer @swcurran. I've retried the process by skipping the four steps I put in my ticket and by only flagging using the revocation + its size when creating a new cred-def, and then checked the api for the registry as per your point 1, I can now see two registries ids are available, which looks good. However, I still got the same error when calling the api for sending a presentation. In my case, I don't think I need to revoke the credential following your points 3 and 4 here, right? As the purpose here is to let the holder to share a no-revoked presentation of its credential with the verifier. 

Also, could you point me to url for the docs showing the right demos regarding how revocation works ?

**Comment by swcurran** [comment]
@ianco -- can you help with this?  I'm not really hands on enough on this.

**Comment by yunxi-zhang** [comment]
@ianco , please let me know if you need more info from me regarding how I run my Aries agent by using v6. Stuck with this problem at the moment. Thanks!

**Comment by ianco** [comment]
Hi @yunxi-zhang revocation is enabled in the alice/faber demo here:  https://github.com/hyperledger/aries-cloudagent-python/tree/main/demo.

You startup faber with an additional parameter `./run_demo faber --revocation` , and depending on where you have your tails server setup, you need to pass in the url of your tails server.

In the demo, you just use options `3` and `4` (I think?) to revoke a credential.  Alice will try to use a revoked credential in a proof, so if you issue one credential from faber -> alice, and then revoke it, then when you ask for a proof alice will provide the revoked credential and the proof won't verify.

There's also a description here specifically issuing to a mobile app and then revoking:  https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AliceGetsAPhone.md

As Stephen says, it's a pretty complicated process.  If you can get the alice/faber demo running, then you should be able to walk through the code and see exactly which api's are getting called and what payloads are provided, and then you can compare against what you are doing manually.

**Comment by yunxi-zhang** [comment]
Thanks for the information, I've figured out the reason for the issue. It's simply because I put unnecessary information for some fields in the JSON body when calling the send presentation api. Removing them made me pass this issue. Will close this ticket.
