### ISSUE TITLE
Error message is not helpful to tell what's the root cause 

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#1014]
When calling the api for a holder to present a proof, below error info will be shown if the JSON body message is not constructed properly. However, the error message is not helpful to tell what's the root cause.

`400: Error when constructing proof: Error: Invalid structure. Caused by: RevocationState not found by id: RevocationRegistryId("VV9pK5ZrLPRwYmotgACPkC:4:VV9pK5ZrLPRwYmotgACPkC:3:CL:8:esg:CL_ACCUM:b4ddc084-690a-4dc0-86d0-978b51ff359a"). CommonInvalidStructure.`

Expected result: 
The error message should show more meaningful message such as invalid structure in the request JSON body with what messages are expected in the JSON body.

**Comment by swcurran** [comment]
Totally agree, but unfortunately right now there is not a lot we can do in ACA-Py.  Where it makes sense we have added checks on data structures, but ultimately this is an issue in Indy, and until Indy improves the error handling as they occur, there is little we can do.
