### ISSUE TITLE
Credential offer through out-of-band protocol is not supported yet

### ISSUE THREAD

**Issue by konsmosc** [hyperledger/aries-cloudagent-python#1019]
When I want to _offer-credentials_ using the out-of-band protocol, I call the **/out-of-band/create-invitation** endpoint with an attachment from the issuer point of view. 

But when I call the **/out-of-band/receive-invitation** endpoint, using as body the invitation object created from the above request, from the holder point of view, **the following error appears --> "Unsupported request~attach type, only request-presentation is supported"**. 

From the code point of view this seems correct, since the **receive_invitation** function of the _**out-of-band manager (in aries_cloudagent/protocols/out_of_band/v1_0/manager.py, line 531)**_ checks **only** if the request_attach[@type] is request-presentation and if not the above error occurs. 

Is this functionality not yet implemented or am I doing something wrong??

**Comment by swcurran** [comment]
Connection-less Issue is not supported with OOB.  We haven't had the need for the functionality as we think that it is much better to establish a connection with an entity to whom a credential is issued for followup communications.  We also would prefer that verification done before issuing a credential should use the same channel as the issue, to ensure the issuance is to the right entity.

That lecture over with :-), this functionality could be added.  We just haven't included it in our work.

**Comment by konsmosc** [comment]
Hi Stephen, thanks for the clarification about connection-less issuance of credentials. 

Basically, I have tried this because, from the Open-API it seems that you are allowed to have as attachments either credential-offer or present-proof to create an invitation with OOB. So by using the /out-of-band/create-invitation you can sucessfully create an invitation using a credential-offer as an attachment. But after your comment, if I am get it right, you can not then use the OOB(from holder point of view) to receive this offer, because it is much better to first establish a connection with the entity to whom a credential is issued.

So you would prefer for example to use OOB to establish the connection and then use this connection and the issue-credential protocol to send the credential?? Am I get it right??

**Comment by swcurran** [comment]
Yes.  There is nothing to technically to stop someone from building a connection-less issue in ACA-Py.  We haven't because we are concerned about the data model -- issuing on a channel where you don't really know to whom you are connected.

We've implemented it on the proof request side because you are just doing a receipt of data from a holder, not issuing them something.

**Comment by sklump** [comment]
At least the API shouldn't propose offer-credential as an option then. I can take that out in minutes.

**Comment by sklump** [comment]
Should I remove support for credential-offer attachments on out-of-band invitation creation then? It does seem like a three-card-monte.

**Comment by swcurran** [comment]
I'd say yes.  If/when someone wants to add full support, this is the least of their worries.

**Comment by konsmosc** [comment]
Thank you very much for your clarifications guys!!
