### ISSUE TITLE
Possible WQL queries

### ISSUE THREAD

**Issue by james-cohen** [hyperledger/aries-cloudagent-python#1021]
I've been trying to perform some WQL queries for searching credentials following the guide at https://readthedocs.org/projects/indy-hipe/downloads/pdf/latest/ but not all seem compatible with use via the Aries REST API.

Given the structure of an example GET Credentials response:
```
{
  "results": [
    {
      "referent": "test_credential",
      "attrs": {
        "BrandNewAttribute": "test 1",
        "Another_New_Name_Test": "first test",
        "Another_test_attribute": "second test"
      },
      "schema_id": "7y89bapMsGn13s37E8G1uZ:2:test:3.0",
      "cred_def_id": "7y89bapMsGn13s37E8G1uZ:3:CL:default",
      "rev_reg_id": null,
      "cred_rev_id": null
    },
    {
      "referent": "another_test_credential",
      "attrs": {
        "BrandNewAttribute": "test",
        "Another_test_attribute": "2nd test",
        "Another_New_Name_Test": "3rd test"
      },
      "schema_id": "7y89bapMsGn13s37E8G1uZ:2:test:3.0",
      "cred_def_id": "7y89bapMsGn13s37E8G1uZ:3:CL:default",
      "rev_reg_id": null,
      "cred_rev_id": null
    }
  ]
}
```

What queries are possible to perform here? The following both work:
```
{"schema_id": {"$in": ["7y89bapMsGn13s37E8G1uZ:2:test:3.0"]}}
{"cred_def_id": {"$in": ["7y89bapMsGn13s37E8G1uZ:3:CL:default"]}}
```

But querying the referent always returns an empty array. There is also mention of querying by encrypted and unencrypted tags but this doesn't seem to be an available option to set up via Aries, is this referring to attribute names and values?

**Comment by sklump** [comment]
WQL queries can operate on:
- "schema_id"
- "cred_def_id"
- "rev_reg_id"
- "attr::<attr-name>::value"
- "attr::<attr-name>::marker": "1"
It's not up to us: it's the underlying indy toolkit.

**Comment by james-cohen** [comment]
Got it, I figured that would be a factor. Thanks for your help
