### ISSUE TITLE
Alias ignored when creating OOB invitation

### ISSUE THREAD

**Issue by rpobulic** [hyperledger/aries-cloudagent-python#1025]
If I specify an alias in /out-of-band/create-invitation, it is ignored and no alias is visible in /connections. Specifying alias in /out-of-band/receive-invitation works as expected. Currently, when using /out-of-band/create-invitation, the only way to identify the connection for later reference is the invi_msg_id, but it cannot be used as a query parameter for /connections, so a full scan of all connections is needed to find the corresponding connection_id.
Is there any other way of efficiently correlating the invitation and the resulting connection_id in the controller?

POST /out-of-band/create-invitation
body:
{
  "alias": "Test",
  "handshake_protocols": ["https://didcomm.org/didexchange/1.0"],
  "my_label": "test label"
}
response:
{
  "invitation": {
    "@type": "https://didcomm.org/out-of-band/1.0/invitation",
    "@id": "401bcdd3-100f-4245-bb5b-1a99ce3f8b86",
    "handshake_protocols": [
      "https://didcomm.org/didexchange/1.0"
    ],
    "label": "VDEL",
    "service": [
      {
        "id": "#inline",
        "type": "did-communication",
        "recipientKeys": [
          "did:key:z6MktQzJoQuSYKQBrpweohWpPWqruFJSiy1aHtwG3pmMLXcU"
        ],
        "serviceEndpoint": "http://130.61.17.227:8020"
      }
    ]
  },
  "invitation_url": "http://130.61.17.227:8020?oob=eyJAdHlwZSI6ICJodHRwczovL2RpZGNvbW0ub3JnL291dC1vZi1iYW5kLzEuMC9pbnZpdGF0aW9uIiwgIkBpZCI6ICI0MDFiY2RkMy0xMDBmLTQyNDUtYmI1Yi0xYTk5Y2UzZjhiODYiLCAiaGFuZHNoYWtlX3Byb3RvY29scyI6IFsiaHR0cHM6Ly9kaWRjb21tLm9yZy9kaWRleGNoYW5nZS8xLjAiXSwgImxhYmVsIjogIlZERUwiLCAic2VydmljZSI6IFt7ImlkIjogIiNpbmxpbmUiLCAidHlwZSI6ICJkaWQtY29tbXVuaWNhdGlvbiIsICJyZWNpcGllbnRLZXlzIjogWyJkaWQ6a2V5Ono2TWt0UXpKb1F1U1lLUUJycHdlb2hXcFBXcXJ1RkpTaXkxYUh0d0czcG1NTFhjVSJdLCAic2VydmljZUVuZHBvaW50IjogImh0dHA6Ly8xMzAuNjEuMTcuMjI3OjgwMjAifV19",
  "invi_msg_id": "401bcdd3-100f-4245-bb5b-1a99ce3f8b86",
  "state": "initial",
  "trace": false
}

GET /connections
response:
{
  "results": [
    {
      "their_did": "5Qr9rDTJUxy2FErWJaYry5",
      "connection_id": "eebe7877-a2d4-4e5e-ac9d-7c21b49afe83",
      "updated_at": "2021-03-14 14:25:19.907382Z",
      "routing_state": "none",
      "state": "active",
      "rfc23_state": "completed",
      "invitation_key": "ExjGDAf1CmuikL6x88YyYRHs5g2bK5mDbt2LDYoLRJq6",
      "invitation_msg_id": "401bcdd3-100f-4245-bb5b-1a99ce3f8b86",
      "created_at": "2021-03-14 14:23:58.901870Z",
      "their_label": "Rade Pobulic",
      "my_did": "Wm4jKCtZJdYPyBsMTaL4qZ",
      "request_id": "a805b114-3f8d-4f81-b315-e738b646bafd",
      "accept": "auto",
      "their_role": "invitee",
      "invitation_mode": "once"
    }
  ]
}

**Comment by swcurran** [comment]
@shaangill025 -- could you take a peek?  Probably for after your presentation exchange work.

**Comment by shaangill025** [comment]
I have found the bug. I will create a PR to fix this. 

`alias = request.query.get("alias") ` needs to be updated to `alias = body.get("alias")`. The same issue needs to be fixed with `my_label`. 

https://github.com/hyperledger/aries-cloudagent-python/blob/ab72c90c9dba013181c524d5ea85c04c44a8a6fb/aries_cloudagent/protocols/out_of_band/v1_0/routes.py#L163

**Comment by Ennovate-com** [comment]
@andrewwhitehead - comment on March 14, 2021 > The same issue needs to be fixed with `my_label`.

Has this been fixed for `my_label`? Or at least an issue created for it? I am still seeing the `default_label` "Aries Cloud Agent".
