### ISSUE TITLE
--arg-file config YAML is never found

### ISSUE THREAD

**Issue by james-cohen** [hyperledger/aries-cloudagent-python#1027]
I'm attempting to put all of my environment variables in a YAML as described in the --help section of ACA-Py:

```
Args that start with '--' (eg. --admin) can also be set in a config file
(specified via --arg-file). The config file uses YAML syntax and must
represent a YAML 'mapping' (for details, see
http://learn.getgrav.org/advanced/yaml). If an arg is specified in more than
one place, then commandline values override environment variables which
override config file values which override defaults.

```

I have a config.yaml with parameters like so:
```
ACAPY_WALLET_SEED: Seed000000000000000000000000000
ACAPY_WALLET_TYPE: indy
ACAPY_WALLET_STORAGE_TYPE: postgres_storage
ACAPY_WALLET_STORAGE_CONFIG: '{"url":"172.17.0.1:5432","wallet_scheme":"DatabasePerWallet"}'
ACAPY_WALLET_STORAGE_CREDS: '{"account":"postgres","password":"mysecretpassword","admin_account":"postgres","admin_password":"mysecretpassword"}'
ACAPY_WALLET_NAME: verses_wallet
ACAPY_WALLET_KEY: abcd1234
ACAPY_GENESIS_URL: http://dev.greenlight.bcovrin.vonx.io/genesis
ACAPY_INBOUND_TRANSPORT: 0.0.0.0 8020
ACAPY_OUTBOUND_TRANSPORT: http
ACAPY_ADMIN: 0.0.0.0 8021
ACAPY_ENDPOINT: http://172.17.0.1:8020
ACAPY_ADMIN_INSECURE_MODE: true
ACAPY_LABEL: BaseAgent
ACAPY_PUBLIC_INVITES: true
ACAPY_MULTITENANT: true
ACAPY_MULTITENANT_ADMIN: true
ACAPY_JWT_SECRET: abcd1234
```

I keep the config file at the root level and run the start script:
```
 ./scripts/run_docker start --arg-file ./config.yaml
```

But no matter where I put it I always get the error:
```
aca-py start: error: File not found: ./config.yaml
```

I've tried pretty much every variation of path I can think of, ranging from just ```config.yaml``` to ```../../../../config.yaml``` and putting it in various folders, including the Docker folder, the aries_cloudagent/config folder and anywhere else sensible, but it is never able to locate it.

Is there a specific location or argument that's required?

**Comment by futureman2007** [comment]
I assume you run aca-py inside docker right?
I had a similar issue providing the genesis-transaction-file.

When you use the docker Container, you start a new and clean ubuntu machine. Therefore your file is not inside the container.
To put it inside, you need to edit the Dockerfile which ./scripts/run_docker is starting.
there you need to Add your file.

Are you familiar with this? If not i will post an example of how to do that

**Comment by james-cohen** [comment]
That makes a lot of sense. If you would't mind posting an example snippet that I can adapt and add to the Dockerfile I would greatly appreciate it

**Comment by futureman2007** [comment]
Sure.

Inside your run_docker you have the line: 
`$CONTAINER_RUNTIME build -t aries-cloudagent-run -f ../docker/Dockerfile.run ..`
This means, your Dockerfile to be used is inside docker/Dockerfile.run.

Opening it (e.g. with vi, vim or any other texteditor):
FROM bcgovimages/von-image:py36-1.15-1

ENV ENABLE_PTVSD 0

ADD requirements*.txt ./

RUN pip3 install --no-cache-dir -r requirements.txt -r requirements.dev.txt

```
ADD aries_cloudagent ./aries_cloudagent
ADD bin ./bin
ADD README.md ./
ADD setup.py ./

RUN pip3 install --no-cache-dir -e .

RUN mkdir logs && chown -R indy:indy logs && chmod -R ug+rw logs

ENTRYPOINT ["/bin/bash", "-c", "aca-py \"$@\"", "--"]

```


Here you need to add your file like so:
ADD <Path-to-File> <Path-inside-container>

for example:
ADD myYamlFile ./

To check, if all worked and if your file is inside the container, execute this command after your container has started (after you have run run_docker)

docker exec <name-of-container> ls
docker exec <name-of-container> cat <yourFilename>

I hope this was helpfull

**Comment by james-cohen** [comment]
That now works perfectly, thank you so much.

However, now that it works it's uncovered some issues about the argument parsing itself:

1) Formatting the variables as the help section suggests e.g. ACAPY_SEED instead of --seed does not work, as it seems like the program is trying to interpret them as normal anyway:
```
aca-py start: error: unrecognized arguments: --ACAPY_WALLET_SEED=Seed0000000000000000000000000000
```
The variables only work if you present them in the normal format, so:
```
seed: Seed0000000000000000000000000000
wallet-type: indy
wallet-storage-type: postgres_storage
wallet-storage-config: '{"url":"172.17.0.1:5432","wallet_scheme":"DatabasePerWallet"}'
wallet-storage-creds: '{"account":"postgres","password":"mysecretpassword","admin_account":"postgres","admin_password":"mysecretpassword"}'
wallet-name: verses_wallet
wallet-key: abcd1234
genesis-url: http://dev.greenlight.bcovrin.vonx.io/genesis
inbound-transport:
  - [http, 0.0.0.0, 8020]
outbound-transport: http
admin: [0.0.0.0, 8021]
endpoint: http://172.17.0.1:8020
admin-insecure-mode: true
label: BaseAgent
public-invites: true
multitenant: true
multitenant-admin: true
jwt-secret: abcd1234
```

Note that inbound-transport in particular has to be formatted in this specific way, or you get the error message:
```
aca-py start: error: argument -it/--inbound-transport: expected 3 arguments
```

I was only able to get it to work by copying the formatting found in the demo-args.yaml file found in /demo

I think that the args YAML instructions need to be updated to reflect what's required

**Comment by ianco** [comment]
> 1. Formatting the variables as the help section suggests e.g. ACAPY_SEED instead of --seed does not work, as it seems like the program is trying to interpret them as normal anyway:
> 
> ```
> aca-py start: error: unrecognized arguments: --ACAPY_WALLET_SEED=Seed0000000000000000000000000000
> ```

This is the name of the environment variable, not command-line input, so:

ACAPY_WALLET_SEED=Seed0000000000000000000000000000 ./scripts/rn_docker start ... etc
> 
> The variables only work if you present them in the normal format, so:
> 
> ```
> seed: Seed0000000000000000000000000000
> wallet-type: indy
> wallet-storage-type: postgres_storage
> wallet-storage-config: '{"url":"172.17.0.1:5432","wallet_scheme":"DatabasePerWallet"}'
> wallet-storage-creds: '{"account":"postgres","password":"mysecretpassword","admin_account":"postgres","admin_password":"mysecretpassword"}'
> wallet-name: verses_wallet
> wallet-key: abcd1234
> genesis-url: http://dev.greenlight.bcovrin.vonx.io/genesis
> inbound-transport:
>   - [http, 0.0.0.0, 8020]
> outbound-transport: http
> admin: [0.0.0.0, 8021]
> endpoint: http://172.17.0.1:8020
> admin-insecure-mode: true
> label: BaseAgent
> public-invites: true
> multitenant: true
> multitenant-admin: true
> jwt-secret: abcd1234
> ```
> 
> Note that inbound-transport in particular has to be formatted in this specific way, or you get the error message:
> 
> ```
> aca-py start: error: argument -it/--inbound-transport: expected 3 arguments
> ```
> 
> I was only able to get it to work by copying the formatting found in the demo-args.yaml file found in /demo.
> I think that the args YAML instructions need to be updated to reflect what's required
> 
> 1. Every time the YAML is updated (even changing a single character), the entire image is rebuilt from scratch. Is there any way of putting in an ignore statement that doesn't rebuild just because the YAML changed? (Apologies if this isn't feasible, I'm far from a Docker expert)

**Comment by james-cohen** [comment]
Ok finally almost there, my final issue is that whilst trying to use environment variables, the formatting for multi argument variables is unclear, specifically for ACAPY_ADMIN and ACAPY_INBOUND_TRANSPORT

None of the following variants are accepted:
```
ACAPY_INBOUND_TRANSPORT: http 0.0.0.0 8020
ACAPY_INBOUND_TRANSPORT: http, 0.0.0.0, 8020
ACAPY_INBOUND_TRANSPORT: [http, 0.0.0.0, 8020]
ACAPY_INBOUND_TRANSPORT: 'http 0.0.0.0 8020'
ACAPY_INBOUND_TRANSPORT: http 0.0.0.0 8020
ACAPY_INBOUND_TRANSPORT:
  - http
  - 0.0.0.0
  - 8020
 ACAPY_INBOUND_TRANSPORT:
  - module: http
  - host: 0.0.0.0
  - port: 8020
```

All are rejected with errors such as:
```
services.versesagent.environment.ACAPY_INBOUND_TRANSPORT contains ["http", "0.0.0.0", 8020], which is an invalid type, it should be a string, number, or a null
```
```
aca-py start: error: argument -it/--inbound-transport: expected 3 arguments
```

How should these multi-argument variables be formatted?

**Comment by ianco** [comment]
Hi @james-cohen , FYI we use configargparse (https://pypi.org/project/ConfigArgParse/) to handle these parameters.

I'm not sure offhand how to handle multi-value parameters in environment variables, but I can say from experience that these are not 100% supported.

We've typically used environment variables for parameters that we don't want to record anywhere (such as passwords and DID seeds) and for the rest we use either the aca-py command-line arguements or yml config files.

**Comment by james-cohen** [comment]
Good idea, I basically got a bit too obsessive with trying to make everything need and tidy but for those multi-parameter, non-secret ones I'll just pass as command line variables instead. Thanks!
