### ISSUE TITLE
[Endorser Protocol] Connection/transaction settings

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#1028]
Add the Endorser DID to the connection meta-data (it is required when creating the initial schema or cred def transaction)

Add an Endorser Name to the meta-data (or else ensure that an Alias is set for the connection)

Remove the DID parameter from the Create Schema and Create Cred Def operations; select the desired Endorser instead (based on connection alias?)

Rename the endpoint from "transaction-jobs" to "endorser-role" (Author or Endorser)

For the Create Schema and Cred Def, change "auto-endorse" (default true) to "create-transaction-for-endorser" (default false), so the default behaviour is the same (@andrewwhitehead ?)

**Comment by HarshMultani-AyanWorks** [comment]
Hi @ianco , If we remove the endorser did parameter during create schema or create cred def, then how should we select the desired endorser? Can you elaborate on it.
Are you referring to the case where we first set endorser did in connection meta-data and when we create the transaction records at that time take the endorser did from connection meta-data (This way the agent would need to pass the connection id).

**Comment by ianco** [comment]
Yes, I was thinking they would need to select the endorser (or connection id) when they created the schema or cred def.
