### ISSUE TITLE
No wallet database exists

### ISSUE THREAD

**Issue by ytebboune** [hyperledger/aries-cloudagent-python#1036]
Hello,

I got an issue when I launch agents using this project, and the error is the following : 

> prover_1      | 2021-03-18 08:44:39,640 aries_cloudagent.commands.start ERROR Exception during startup:
> prover_1      | Traceback (most recent call last):
> prover_1      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/wallet_setup.py", line 169, in open_wallet
> prover_1      |     credentials=json.dumps(self.wallet_access),
> prover_1      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/wallet.py", line 127, in open_wallet
> prover_1      |     open_wallet.cb)
> prover_1      | indy.error.WalletNotFoundError
> prover_1      |
> prover_1      | The above exception was the direct cause of the following exception:
> prover_1      |
> prover_1      | Traceback (most recent call last):
> prover_1      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 72, in init
> prover_1      |     await startup
> prover_1      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 28, in start_app
> prover_1      |     await conductor.setup()
> prover_1      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 91, in setup
> prover_1      |     self.root_profile, self.setup_public_did = await wallet_config(context)
> prover_1      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/config/wallet.py", line 40, in wallet_config
> prover_1      |     profile = await mgr.open(context, profile_cfg)
> prover_1      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/profile.py", line 161, in open
> prover_1      |     opened = await indy_config.open_wallet()
> prover_1      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/wallet_setup.py", line 182, in open_wallet
> prover_1      |     ) from x_indy
> prover_1      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/wallet_setup.py", line 169, in open_wallet
> prover_1      |     credentials=json.dumps(self.wallet_access),
> prover_1      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/wallet.py", line 127, in open_wallet
> prover_1      |     open_wallet.cb)
> prover_1      | aries_cloudagent.core.error.ProfileNotFoundError: Wallet 'Prover' not found: Error: Wallet not found
> prover_1      |   Caused by: No wallet database exists

I tried multiple things and the problem doesn't come from Docker, ports aren't used. I guess it may be a set up problem.
Any idea ?

Thanks for your help,

**Comment by ianco** [comment]
Can you provide some information on how you are starting the agents?

**Comment by ytebboune** [comment]
I'm using docker commands to start the agents -> 
docker-compose build
docker-compose up

**Comment by ianco** [comment]
Can you provide your docker-compose.yml file?

**Comment by ytebboune** [comment]
[docker-compose.zip](https://github.com/hyperledger/aries-cloudagent-python/files/6164682/docker-compose.zip)
The file is this one.
Just to precise a little bit : the project is working for all the others one that used it. I am the only one in this case.
I tried to disable my firewall and my antivirus in order to try if that's because of this, but it didn't changed anything.

**Comment by ianco** [comment]
Thanks can you also share the startup command for the agent (with all the parameters)?

**Comment by ytebboune** [comment]
> FROM bcgovimages/von-image:py36-1.14-1
> 
> ARG PROVER_SEED
> ARG PROVER_AGENT_ENDPOINT
> ARG PROVER_WALLET_KEY
> ARG PROVER_ADMIN_API_KEY
> ARG GENESIS_URL
> ARG INBOUND_PORT
> ARG API_PORT
> 
> ENV SEED=$PROVER_SEED
> ENV AGENT_ENDPOINT=$PROVER_AGENT_ENDPOINT
> ENV WALLET_KEY=$PROVER_WALLET_KEY
> ENV ADMIN_API_KEY=$PROVER_ADMIN_API_KEY
> ENV GENESIS=$GENESIS_URL
> ENV AGENT_INBOUND_PORT=$INBOUND_PORT
> ENV ADMIN_API_PORT=$API_PORT
> 
> RUN pip install aries-cloudagent
> 
> ENTRYPOINT ["/bin/bash", "-c", "aca-py start  --inbound-transport http 0.0.0.0 $AGENT_INBOUND_PORT \
>     --outbound-transport http \
>     --admin 0.0.0.0 $ADMIN_API_PORT \
>     --seed $SEED \
>     --endpoint $AGENT_ENDPOINT \
>     --wallet-key $WALLET_KEY \
>     --wallet-name Prover \
>     --wallet-type indy \
>     --label CertPROVER \
>     --admin-api-key $ADMIN_API_KEY \
>     --auto-accept-invites \
>     --auto-accept-requests \
>     --auto-respond-messages \
>     --auto-respond-credential-proposal \
>     --auto-respond-credential-offer \
>     --auto-respond-credential-request \
>     --auto-respond-presentation-proposal \
>     --auto-respond-presentation-request \
>     --auto-store-credential \
>     --enable-undelivered-queue \
>     --genesis-url $GENESIS", "--"]

Is that what you were looking for?
Another precision, is that the same error shows up for the others agents that you can see in the docker-compose file (issuer, verifier).

**Comment by ianco** [comment]
Hi @ytebboune when you "pip install aries-cloudagent" you get the latest published version. aca-py version 0.6.0 was released recently, so I suspect what's happening is that previously people were getting aca-py 0.5.6 and now you're running with 0.6.0

You need to add an additional parameter `--auto-provision` to tell the agent to create its wallet if it doesn't already exist.

Alternately you can run `aca-py provision ...` which will do any necessary wallet setup, and then `aca-py start ...`

(The changes in 0.6.0 are to make wallet creation always explicit)

**Comment by ytebboune** [comment]
That's it !
Thanks a lot, really. I spent days on it.
