### ISSUE TITLE
Turning on "--recreate-wallet" flag when running Acapy v0.6.0, old data in the storage are not auto removed

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#1039]
I run Acapy agent v0.6.0 that connects to my AWS PostgreSQL as my physical wallet storage. For the 1st time run, I've also turned on the multi-tenancy feature, so I can successfully create two sub wallets for this agent (see below figure for using an pgadmin tool).

![image](https://user-images.githubusercontent.com/16185797/111782513-fe7a9480-88b0-11eb-8393-6e71022e5b98.png)

When rerun the acapy agent by turning on the flag "--recreate-wallet" for the 2nd time, I still see the two wallets data in the "items" table.

**Expected result**: All the old data in the tables should be auto removed, the tables should be reinitialised.

**Comment by swcurran** [comment]
Closing as being obsolete. Please reopen with notes if this is still a relevant issue.
