### ISSUE TITLE
Send problem-report when webhook fails to reach controller

### ISSUE THREAD

**Issue by nrempel** [hyperledger/aries-cloudagent-python#104]
The agent retries webhooks if a request fails to reach the controller or the controller does not respond with a 2** response.

In the case of failure and the agent stops sending retries, should the agent send a problem report back to the initiating agent?

@andrewwhitehead what do you think about this? I think there could be arguments in both directions.

cc: @swcurran @ianco

**Comment by andrewwhitehead** [comment]
@nrempel Do we still think this would be useful? I think it would depend entirely on what protocol is being used and would probably be more like timeout on pending requests.

**Comment by swcurran** [comment]
I'm guessing that we can close this.  @andrewwhitehead - can you please confirm?

**Comment by ianco** [comment]
Yes ...  if the credential exchange protocol (or proof request) cannot complete for whatever reason the initiating agent needs to receive a problem report.

**Comment by swcurran** [comment]
Closing...
