### ISSUE TITLE
use did-communication service type in DID Exchange

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-cloudagent-python#1043]
The service type should be `did-communication` rather than `IndyAgent` in DID Exchange.

**Comment by swcurran** [comment]
@sklump -- can you please take this?  For 0160, it can remain as it was, but for DID Exchange, it should be this new format.  Not sure if this data lies in the shared "connection object", which makes it more fun...

**Comment by domwoe** [comment]
Related to this: https://github.com/decentralized-identity/didcomm-messaging/issues/179

**Comment by andrewwhitehead** [comment]
This is covered in my draft PR here, where we leave it as IndyAgent for the connections protocol for compatibility with current .NET agents: https://github.com/hyperledger/aries-cloudagent-python/pull/1056

**Comment by swcurran** [comment]
Closing this is being addressed in the PR for updating Unqualified DIDs to DID Peer.
