### ISSUE TITLE
use and accept updated media types

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-cloudagent-python#1044]
AcaPy should be using the Aries RFC media types rather than `application/ssi-agent-wire`.

**Comment by swcurran** [comment]
Agreed, and I believe we've added that.  But for backwards compatibility, both need to be accepted.

@andrewwhitehead can you provide a status on this?

**Comment by swcurran** [comment]
A priority for accomplishing AIP 2.0 Interop with Aries Framework Go.

**Comment by andrewwhitehead** [comment]
At the moment we don't support this, but for testing it could be enabled under the same flag that turns on the new message types for outgoing requests.

**Comment by swcurran** [comment]
What is the work and who should do it?  Is this something you should do, or perhaps @shaangill025 ?

Presumably, in receiving messages, we could handle 0 or more values.  We can also send them out, but I'm guessing we don't know what those receiving our messages would do.  Correct?

**Comment by andrewwhitehead** [comment]
On receiving we don't enforce the media type. I can do a quick pass today along with the did:peer changes for testing.

**Comment by swcurran** [comment]
Completed
