### ISSUE TITLE
Create DID docs with `peer` DID method in did exchange

### ISSUE THREAD

**Issue by Moopli** [hyperledger/aries-cloudagent-python#1048]
When creating a peer DID doc for DID exchange, it should have the `peer` DID method.

**Comment by swcurran** [comment]
@andrewwhitehead -- how do we get this one done?   Is this an AIP 2 change and we have to do a compatibility flag on it?  I'm guessing we have to, since this is working with our existing interop partners.

Also, we will be able to use git blame to find out where this came from???   :-)

**Comment by troyronda** [comment]
@swcurran @andrewwhitehead do you have any updates on this topic?

**Comment by esune** [comment]
@shaangill025 please connect with @andrewwhitehead as he has already done work on this and you may be able to inherit his work/branch to get started.

**Comment by swcurran** [comment]
This is being addressed by Issue #2156 . Closing this issue as #2156 has more detail about how we are doing this.
