### ISSUE TITLE
generating DID docs with verificationMethod rather than publicKey

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-cloudagent-python#1050]
[DID-Core v1](https://w3c.github.io/did-core/#verification-methods) now uses `verificationMethod` rather than the `publicKey` property. When generating DID documents, the `verificationMethod` property should be used.

The [did:peer spec](https://identity.foundation/peer-did-method-spec/#verificationmethod) has now also been updated to use `verificationMethod`.

**Comment by victormartinez-work** [comment]
this is been address in this PR.  
https://github.com/hyperledger/aries-cloudagent-python/pull/1033

**Comment by swcurran** [comment]
Addressed in replacement PR to 1033 — #1070
