### ISSUE TITLE
How to handle json-ld contexts

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1062]
I'd like some feedback from other ACA-Py users / developers on the best approach for handling json-ld contexts in ACA-Py.

AFAIK you shouldn't just download JSON-LD contexts whenever you encounter them. And you should definitely cache them if you do. Should we:

- Have some essential local contexts
- allow to download new contexts
- Cache downloaded contexts
- disallow to download contexts
- Allow to specify a list of trusted contexts that may be downloaded (at startup?).
- ....

I'm trying to find a sweet spot between just downloading every document every time and creating a full-featured context management system in ACA-Py. Any thoughts on this, especially w.r.t. security?

@swcurran @andrewwhitehead @sklump @ianco

**Comment by swcurran** [comment]
Not much of an answer.  As I've heard repeatedly say by the people that created JSON-LD -- never dynamically download a JSON-LD context.  You should only pre-configure contexts you expect to see.  I don't know how that would work.

Closing this as an ACA-Py issue as I think this is more a JSON-LD tooling issue. If/When we get serious about JSON-LD in ACA-Py, we'll no doubt hit this again.
