### ISSUE TITLE
consistency in key identifier for did:sov?

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1075]
The new did resolver returns `keys-1` for the key identifier. Uniresolver returns `key-1`.

If we now create a jsonld credential in ACA-Py the verification method will be something like: `did:sov:xxx#keys-1`. If we then verify this somewhere else that uses uniresolver the key will be undefined.

I'm not sure if there is a standard for this, but maybe we can use the uniresolver format for now.

@dbluhm

**Comment by dbluhm** [comment]
We should have this better formalized once the Indy DID Method @swcurran and co have been working on is ready but until we have that, I agree that sticking to the uniresolver format is a good idea.
