### ISSUE TITLE
Match returned did:sov doc with uniresolver

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1081]
Currently the did:sov diddocs assembled in ACA-Py don't include the `assertionMethod` for the key. This means we can't use it for the default VC proof purpose `assertionMethod` and thus we get an error:

"Verification method did:sov:DViYrCMPWfuLiY7LLs8giB#key-1 not authorized by controller for proof purpose assertionMethod"

Uniresolver does include the key in `assertionMethod` so I think we should also do that in ACA-Py. I've modified it in my local branch, but just wanted to check if this is intentional.

@dbluhm

**Comment by dbluhm** [comment]
No particular reason this is missing in the current implementation other than we were focused on representing info needed for DIDComm and overlooked this. Thanks for pointing it out!

**Comment by TimoGlastra** [comment]
Cool, openend #1082 to fix
