### ISSUE TITLE
Running agent locally

### ISSUE THREAD

**Issue by juvebogdan** [hyperledger/aries-cloudagent-python#1083]
Hello,

I want to run agent locally so i can start making a controller. But for some reason I am unable to follow guides from readme. First I went to http://dev.greenlight.bcovrin.vonx.io/ and created public DID from seed then I ran this command:

 ./scripts/run_docker start --genesis-url http://dev.greenlight.bcovrin.vonx.io/genesis --inbound-transport http 0.0.0.0 8020 --outbound-transport http --admin-insecure-mode -e http://0.0.0.0:8020 --admin 0.0.0.0 8021 --seed ztVe8GJtMPiC1RBFjxL56Rf0uj4IURAi

This finishes but I can not access http://localhost:8021 or http://localhost:8020 in my browser. Am I missing something here?

Thank you in advance

**Comment by sklump** [comment]
`PORTS="8020 8021" ./scripts/run_docker start --genesis-url http://dev.greenlight.bcovrin.vonx.io/genesis --inbound-transport http 0.0.0.0 8020 --outbound-transport http --admin-insecure-mode -e http://192.168.56.133:8020 --admin 0.0.0.0 8021 --seed ztVe8GJtMPiC1RBFjxL56Rf0uj4IURAi`

**Comment by srbms23** [comment]
Hi @sklump ,

I hope you can help me with my issue as well.
What is the endpoint when I want to run Agent on my mac locally? Could you take a look at my commands below and tell me if there is something wrong?

After I had registered public did on ledger, I tried to do run Agent locally with commands below but I got `403 Error: No ledger available` in Swagger.

`PORTS="8020 11000" aca-py start --label Alice --inbound-transport http 0.0.0.0 8020 --outbound-transport http --admin 0.0.0.0 11000 --admin-insecure-mode --genesis-url http://dev.greenlight.bcovrin.vonx.io/genesis --seed Alice000000000000000000000000001 --endpoint http://localhost:8020 --debug-connections --auto-provision`


Thanks a lot!
