### ISSUE TITLE
Issue Credential protocol cannot handle unknown credential formats

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1084]
The issue credential `V20CredFormat` does not allow unknown format identifiers to be present. As the format is used in all the credential exchange messages this means message validation will fail if we receive an unrecognized format.

The way I currently handle it is that we only process the formats that we recognize. If that means no formats are processed, we throw an error. This allows a flow where we receive two formats, one of which we recognize and can respond to.

I already modified the cred v2 manager in our branch to check we at least recognize a single format. So I think we should only loosen up the higher level validation a bit such as:

- Update V20CredFormatSchema to allow any string identifier
- Update the `validate_fields` methods in the cred ex messages to check if the format is found before calling `validate_fields`
- Maybe others??

BTW -- This is the same for present proof

**Comment by TimoGlastra** [comment]
@sklump Could you maybe pick this up? 🙂

**Comment by sklump** [comment]
I can look into it starting tomorrow
