### ISSUE TITLE
"./run_demo faber --revocation" fails

### ISSUE THREAD

**Issue by edbkei** [hyperledger/aries-cloudagent-python#1094]
ubu20w@DESKTOP-CT0HBV1:~/aries-cloudagent-python/demo$ ./run_demo faber --revocation
Preparing agent image...
sha256:439695f8bcf199a6952e310a9138f52e692095c5ff5d7c1d84f518db925308e4
Trying to detect ngrok service endpoint
jq not found
172.29.38.172
Starting [faber] agent with args [--port 8020 --revocation]

#1 Provision an agent and wallet, get back configuration details
Faber      | Registering faber.agent ...
Faber      | nym_info: {'did': 'CoyHqJEZdS7UeKkVz42cMw', 'seed': 'd_000000000000000000000000827879', 'verkey': '7SLGaGjzrDTwyuR9fi76yN2BLgHp8ZVErgXEmDvrS4Du'}
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
Schema ID: CoyHqJEZdS7UeKkVz42cMw:2:degree schema:57.74.8
Faber      | Revocation registry: (undetermined) state: init
Faber      | Revocation registry: CoyHqJEZdS7UeKkVz42cMw:4:CoyHqJEZdS7UeKkVz42cMw:3:CL:24:faber.agent.degree_schema:CL_ACCUM:54f10cf7-a9d6-4c14-a15e-c6a8fd6ca156 state: generated
Faber      | Revocation registry: CoyHqJEZdS7UeKkVz42cMw:4:CoyHqJEZdS7UeKkVz42cMw:3:CL:24:faber.agent.degree_schema:CL_ACCUM:54f10cf7-a9d6-4c14-a15e-c6a8fd6ca156 state: posted
Faber      | Revocation registry: CoyHqJEZdS7UeKkVz42cMw:4:CoyHqJEZdS7UeKkVz42cMw:3:CL:24:faber.agent.degree_schema:CL_ACCUM:54f10cf7-a9d6-4c14-a15e-c6a8fd6ca156 state: active
Faber      | Revocation registry: (undetermined) state: init
Faber      | Revocation registry: CoyHqJEZdS7UeKkVz42cMw:4:CoyHqJEZdS7UeKkVz42cMw:3:CL:24:faber.agent.degree_schema:CL_ACCUM:d14ca843-db5e-4094-8157-4dd11cbd6768 state: generated
Faber      | Revocation registry: CoyHqJEZdS7UeKkVz42cMw:4:CoyHqJEZdS7UeKkVz42cMw:3:CL:24:faber.agent.degree_schema:CL_ACCUM:d14ca843-db5e-4094-8157-4dd11cbd6768 state: posted
Faber      | 2021-04-17 19:56:36,410 aries_cloudagent.admin.server ERROR Handler error with exception: Tails file for rev reg CoyHqJEZdS7UeKkVz42cMw:4:CoyHqJEZdS7UeKkVz42cMw:3:CL:24:faber.agent.degree_schema:CL_ACCUM:54f10cf7-a9d6-4c14-a15e-c6a8fd6ca156 failed to upload: Exceeded maximum put attempts
Faber      |
Faber      | =================
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 182, in ready_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 219, in debug_middleware
Shutting down agent ...
Faber      |     return await handler(request)
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 381, in setup_context
Faber      |     return await task
Faber      |   File "/home/indy/aries_cloudagent/messaging/credential_definitions/routes.py", line 253, in credential_definitions_send_credential_definition
Faber      |     f"Tails file for rev reg {registry_record.revoc_reg_id} "
Faber      | aiohttp.web_exceptions.HTTPInternalServerError: Tails file for rev reg CoyHqJEZdS7UeKkVz42cMw:4:CoyHqJEZdS7UeKkVz42cMw:3:CL:24:faber.agent.degree_schema:CL_ACCUM:54f10cf7-a9d6-4c14-a15e-c6a8fd6ca156 failed to upload: Exceeded maximum put attempts
Faber      |
Faber      | Shutting down
Faber      | Exited with return code 0
Traceback (most recent call last):
  File "/home/indy/demo/runners/support/agent.py", line 624, in admin_request
    resp.raise_for_status()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 500, message='Tails file for rev reg CoyHqJEZdS7UeKkVz42cMw:4:CoyHqJEZdS7UeKkVz42cMw:3:CL:24:faber.agent.degree_schema:CL_ACCUM:54f10cf7-a9d6-4c14-a15e-c6a8fd6ca156 failed to upload: Exceeded maximum put attempts', url=URL('http://172.29.38.172:8021/credential-definitions')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/indy/demo/runners/faber.py", line 430, in <module>
    asyncio.get_event_loop().run_until_complete(main(args))
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/home/indy/demo/runners/faber.py", line 173, in main
    schema_attrs=faber_schema_attrs,
  File "/home/indy/demo/runners/agent_container.py", line 422, in initialize
    schema_name, schema_attrs
  File "/home/indy/demo/runners/agent_container.py", line 434, in create_schema_and_cred_def
    schema_name, schema_attrs, self.revocation, version=version
  File "/home/indy/demo/runners/agent_container.py", line 309, in create_schema_and_cred_def
    revocation_registry_size=TAILS_FILE_COUNT if revocation else None,
  File "/home/indy/demo/runners/support/agent.py", line 243, in register_schema_and_creddef
    "/credential-definitions", credential_definition_body
  File "/home/indy/demo/runners/support/agent.py", line 725, in admin_POST
    "POST", path, data, text, params, headers=headers
  File "/home/indy/demo/runners/support/agent.py", line 627, in admin_request
    raise Exception(f"Error: {resp_text}") from e
Exception: Error: 500: Tails file for rev reg CoyHqJEZdS7UeKkVz42cMw:4:CoyHqJEZdS7UeKkVz42cMw:3:CL:24:faber.agent.degree_schema:CL_ACCUM:54f10cf7-a9d6-4c14-a15e-c6a8fd6ca156 failed to upload: Exceeded maximum put attempts

**Comment by ianco** [comment]
I just tested this and it looks like it's working.  I suspect it's an issue with ngrok (by default the agent connects to your tails server using the ngrok endpoint.)  Try shutting everything down and (`./manage rm` in your tails server and von-network shells), then restart everything and see if you still get the issue

**Comment by safwanAhman** [comment]
hey im getting the same issue, i was wondering if you have resolved this?

**Comment by edbkei** [comment]
it´s the same status as before, with refreshed machine. But apparently, it went a little further.

ubu20w@DESKTOP-CT0HBV1:~/aries-cloudagent-python/demo$ ./run_demo faber --revocation
Preparing agent image...
sha256:726309c7c1a6b362ea4e6dfbdb84d23bdae232ecf2d048f6678e66ffbc70fc08
Trying to detect ngrok service endpoint
ngrok not detected for agent endpoint
172.28.56.26
Starting [faber] agent with args [--port 8020 --revocation]

#1 Provision an agent and wallet, get back configuration details
Faber      | Registering faber.agent ...
Faber      | nym_info: {'did': 'DM4dgtMn1q2oWBRc1RgyYJ', 'seed': 'd_000000000000000000000000483872', 'verkey': '7jH9nDsjDduTMHeKjjTVKAeYDNKZxfb4hGsz51zSmd5X'}
Faber      | Registered DID: DM4dgtMn1q2oWBRc1RgyYJ
Faber      | ['/home/indy/.pyenv/versions/3.6.13/bin/python', '-m', 'aries_cloudagent', 'start', '--endpoint', 'http://172.28.56.26:8020', '--label', 'faber.agent', '--auto-ping-connection', '--auto-respond-messages', '--inbound-transport', 'http', '0.0.0.0', '8020', '--outbound-transport', 'http', '--admin', '0.0.0.0', '8021', '--admin-insecure-mode', '--wallet-type', 'indy', '--wallet-name', 'faber.agent483872', '--wallet-key', 'faber.agent483872', '--preserve-exchange-records', '--auto-provision', '--genesis-transactions', '{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node1","blskey":"4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSEimFF6nsQ6M41QvhM2Z33nves5vfSn9n1UwNFJBYtWVnHYMATn76vLuL3zU88KyeAYcHfsih3He6UHcXDxcaecHVz6jhCYz1P2UZn2bDVruL5wXpehgBfBaLKm3Ba","blskey_pop":"RahHYiCvoNCtPTrVtP7nMC5eTYrsUA8WjXbdhNc8debh1agE9bGiJxWBXYNFbnJXoXhWFMvyqhqhRoq737YQemH5ik9oL7R4NTTCz2LEZhkgLJzB3QRQqJyBNyv7acbdHrAT8nQ9UkLbaVL9NBpnWXBTw4LEMePaSHEw66RzPNdAX1","client_ip":"172.28.56.26","client_port":9702,"node_ip":"172.28.56.26","node_port":9701,"services":["VALIDATOR"]},"dest":"Gw6pDLhcBcoQesN72qfotTgFa7cbuqZpkX3Xo6pLhPhv"},"metadata":{"from":"Th7MpTaRZVRYnPiabds81Y"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"fea82e10e894419fe2bea7d96296a6d46f50f93f9eeda954ec461b2ed2950b62"},"ver":"1"}\n{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node2","blskey":"37rAPpXVoxzKhz7d9gkUe52XuXryuLXoM6P6LbWDB7LSbG62Lsb33sfG7zqS8TK1MXwuCHj1FKNzVpsnafmqLG1vXN88rt38mNFs9TENzm4QHdBzsvCuoBnPH7rpYYDo9DZNJePaDvRvqJKByCabubJz3XXKbEeshzpz4Ma5QYpJqjk","blskey_pop":"Qr658mWZ2YC8JXGXwMDQTzuZCWF7NK9EwxphGmcBvCh6ybUuLxbG65nsX4JvD4SPNtkJ2w9ug1yLTj6fgmuDg41TgECXjLCij3RMsV8CwewBVgVN67wsA45DFWvqvLtu4rjNnE9JbdFTc1Z4WCPA3Xan44K1HoHAq9EVeaRYs8zoF5","client_ip":"172.28.56.26","client_port":9704,"node_ip":"172.28.56.26","node_port":9703,"services":["VALIDATOR"]},"dest":"8ECVSk179mjsjKRLWiQtssMLgp6EPhWXtaYyStWPSGAb"},"metadata":{"from":"EbP4aYNeTHL6q385GuVpRV"},"type":"0"},"txnMetadata":{"seqNo":2,"txnId":"1ac8aece2a18ced660fef8694b61aac3af08ba875ce3026a160acbc3a3af35fc"},"ver":"1"}\n{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node3","blskey":"3WFpdbg7C5cnLYZwFZevJqhubkFALBfCBBok15GdrKMUhUjGsk3jV6QKj6MZgEubF7oqCafxNdkm7eswgA4sdKTRc82tLGzZBd6vNqU8dupzup6uYUf32KTHTPQbuUM8Yk4QFXjEf2Usu2TJcNkdgpyeUSX42u5LqdDDpNSWUK5deC5","blskey_pop":"QwDeb2CkNSx6r8QC8vGQK3GRv7Yndn84TGNijX8YXHPiagXajyfTjoR87rXUu4G4QLk2cF8NNyqWiYMus1623dELWwx57rLCFqGh7N4ZRbGDRP4fnVcaKg1BcUxQ866Ven4gw8y4N56S5HzxXNBZtLYmhGHvDtk6PFkFwCvxYrNYjh","client_ip":"172.28.56.26","client_port":9706,"node_ip":"172.28.56.26","node_port":9705,"services":["VALIDATOR"]},"dest":"DKVxG2fXXTU8yT5N7hGEbXB3dfdAnYv1JczDUHpmDxya"},"metadata":{"from":"4cU41vWW82ArfxJxHkzXPG"},"type":"0"},"txnMetadata":{"seqNo":3,"txnId":"7e9f355dffa78ed24668f0e0e369fd8c224076571c51e2ea8be5f26479edebe4"},"ver":"1"}\n{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node4","blskey":"2zN3bHM1m4rLz54MJHYSwvqzPchYp8jkHswveCLAEJVcX6Mm1wHQD1SkPYMzUDTZvWvhuE6VNAkK3KxVeEmsanSmvjVkReDeBEMxeDaayjcZjFGPydyey1qxBHmTvAnBKoPydvuTAqx5f7YNNRAdeLmUi99gERUU7TD8KfAa6MpQ9bw","blskey_pop":"RPLagxaR5xdimFzwmzYnz4ZhWtYQEj8iR5ZU53T2gitPCyCHQneUn2Huc4oeLd2B2HzkGnjAff4hWTJT6C7qHYB1Mv2wU5iHHGFWkhnTX9WsEAbunJCV2qcaXScKj4tTfvdDKfLiVuU2av6hbsMztirRze7LvYBkRHV3tGwyCptsrP","client_ip":"172.28.56.26","client_port":9708,"node_ip":"172.28.56.26","node_port":9707,"services":["VALIDATOR"]},"dest":"4PS3EDQ3dW1tci1Bp6543CfuuebjFrg36kLAUcskGfaA"},"metadata":{"from":"TWwCRQRZ2ZHMJFn9TzLp7W"},"type":"0"},"txnMetadata":{"seqNo":4,"txnId":"aa5e817d7cc626170eca175822029339a444eb0ee8f0bd20d3b0b76e566fb008"},"ver":"1"}\n', '--seed', 'd_000000000000000000000000483872', '--webhook-url', 'http://172.28.56.26:8022/webhooks', '--tails-server-base-url', 'http://172.28.56.26:6543', '--auto-accept-invites', '--auto-accept-requests', '--auto-store-credential']
Faber      |
Faber      | ::::::::::::::::::::::::::::::::::::::::::::::
Faber      | :: faber.agent                              ::
Faber      | ::                                          ::
Faber      | ::                                          ::
Faber      | :: Inbound Transports:                      ::
Faber      | ::                                          ::
Faber      | ::   - http://0.0.0.0:8020                  ::
Faber      | ::                                          ::
Faber      | :: Outbound Transports:                     ::
Faber      | ::                                          ::
Faber      | ::   - http                                 ::
Faber      | ::   - https                                ::
Faber      | ::                                          ::
Faber      | :: Public DID Information:                  ::
Faber      | ::                                          ::
Faber      | ::   - DID: DM4dgtMn1q2oWBRc1RgyYJ          ::
Faber      | ::                                          ::
Faber      | :: Administration API:                      ::
Faber      | ::                                          ::
Faber      | ::   - http://0.0.0.0:8021                  ::
Faber      | ::                                          ::
Faber      | ::                               ver: 0.6.0 ::
Faber      | ::::::::::::::::::::::::::::::::::::::::::::::
Faber      |
Faber      | Listening...
Faber      |
Startup duration: 7.06s
Admin URL is at: http://172.28.56.26:8021
Endpoint URL is at: http://172.28.56.26:8020

#3/4 Create a new schema/cred def on the ledger
Schema:
  {
    "sent": {
      "schema_id": "DM4dgtMn1q2oWBRc1RgyYJ:2:degree schema:79.79.96",
      "schema": {
        "ver": "1.0",
        "id": "DM4dgtMn1q2oWBRc1RgyYJ:2:degree schema:79.79.96",
        "name": "degree schema",
        "version": "79.79.96",
        "attrNames": [
          "name",
          "age",
          "timestamp",
          "date",
          "degree"
        ],
        "seqNo": 8
      }
    }
  }

Schema ID: DM4dgtMn1q2oWBRc1RgyYJ:2:degree schema:79.79.96
Faber      | Revocation registry: (undetermined) state: init
Faber      | Revocation registry: DM4dgtMn1q2oWBRc1RgyYJ:4:DM4dgtMn1q2oWBRc1RgyYJ:3:CL:8:faber.agent.degree_schema:CL_ACCUM:87ecdc1d-7631-43fd-a93d-b340f322bd08 state: generated
Faber      | Revocation registry: DM4dgtMn1q2oWBRc1RgyYJ:4:DM4dgtMn1q2oWBRc1RgyYJ:3:CL:8:faber.agent.degree_schema:CL_ACCUM:87ecdc1d-7631-43fd-a93d-b340f322bd08 state: posted
Faber      | Revocation registry: DM4dgtMn1q2oWBRc1RgyYJ:4:DM4dgtMn1q2oWBRc1RgyYJ:3:CL:8:faber.agent.degree_schema:CL_ACCUM:87ecdc1d-7631-43fd-a93d-b340f322bd08 state: active
Faber      | Revocation registry: (undetermined) state: init
Faber      | Revocation registry: DM4dgtMn1q2oWBRc1RgyYJ:4:DM4dgtMn1q2oWBRc1RgyYJ:3:CL:8:faber.agent.degree_schema:CL_ACCUM:0a8c9fb4-768a-4ccb-a91f-76bca130b312 state: generated
Faber      | Revocation registry: DM4dgtMn1q2oWBRc1RgyYJ:4:DM4dgtMn1q2oWBRc1RgyYJ:3:CL:8:faber.agent.degree_schema:CL_ACCUM:0a8c9fb4-768a-4ccb-a91f-76bca130b312 state: posted
Faber      | 2021-09-03 11:47:07,427 aries_cloudagent.admin.server ERROR Handler error with exception: Tails file for rev reg DM4dgtMn1q2oWBRc1RgyYJ:4:DM4dgtMn1q2oWBRc1RgyYJ:3:CL:8:faber.agent.degree_schema:CL_ACCUM:87ecdc1d-7631-43fd-a93d-b340f322bd08 failed to upload: Exceeded maximum put attempts
Faber      |
Faber      | =================
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 182, in ready_middleware
Shutting down agent ...
Faber      |     return await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 219, in debug_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 381, in setup_context
Faber      |     return await task
Faber      |   File "/home/indy/aries_cloudagent/messaging/credential_definitions/routes.py", line 253, in credential_definitions_send_credential_definition
Faber      |     f"Tails file for rev reg {registry_record.revoc_reg_id} "
Faber      | aiohttp.web_exceptions.HTTPInternalServerError: Tails file for rev reg DM4dgtMn1q2oWBRc1RgyYJ:4:DM4dgtMn1q2oWBRc1RgyYJ:3:CL:8:faber.agent.degree_schema:CL_ACCUM:87ecdc1d-7631-43fd-a93d-b340f322bd08 failed to upload: Exceeded maximum put attempts
Faber      |
Faber      | Shutting down
Faber      | Exited with return code 0
Traceback (most recent call last):
  File "/home/indy/demo/runners/support/agent.py", line 624, in admin_request
    resp.raise_for_status()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 500, message='Tails file for rev reg DM4dgtMn1q2oWBRc1RgyYJ:4:DM4dgtMn1q2oWBRc1RgyYJ:3:CL:8:faber.agent.degree_schema:CL_ACCUM:87ecdc1d-7631-43fd-a93d-b340f322bd08 failed to upload: Exceeded maximum put attempts', url=URL('http://172.28.56.26:8021/credential-definitions')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/indy/demo/runners/faber.py", line 430, in <module>
    asyncio.get_event_loop().run_until_complete(main(args))
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/home/indy/demo/runners/faber.py", line 173, in main
    schema_attrs=faber_schema_attrs,
  File "/home/indy/demo/runners/agent_container.py", line 422, in initialize
    schema_name, schema_attrs
  File "/home/indy/demo/runners/agent_container.py", line 434, in create_schema_and_cred_def
    schema_name, schema_attrs, self.revocation, version=version
  File "/home/indy/demo/runners/agent_container.py", line 309, in create_schema_and_cred_def
    revocation_registry_size=TAILS_FILE_COUNT if revocation else None,
  File "/home/indy/demo/runners/support/agent.py", line 243, in register_schema_and_creddef
    "/credential-definitions", credential_definition_body
  File "/home/indy/demo/runners/support/agent.py", line 725, in admin_POST
    "POST", path, data, text, params, headers=headers
  File "/home/indy/demo/runners/support/agent.py", line 627, in admin_request
    raise Exception(f"Error: {resp_text}") from e
Exception: Error: 500: Tails file for rev reg DM4dgtMn1q2oWBRc1RgyYJ:4:DM4dgtMn1q2oWBRc1RgyYJ:3:CL:8:faber.agent.degree_schema:CL_ACCUM:87ecdc1d-7631-43fd-a93d-b340f322bd08 failed to upload: Exceeded maximum put attempts
ubu20w@DESKTOP-CT0HBV1:~/aries-cloudagent-python/demo$

**Comment by ianco** [comment]
How are you running the indy ledger and revocation registry?

(It looks like the agent is failing to upload the tails file to the revocation registry)'

**Comment by edbkei** [comment]
cd von-network
./manage up

**Comment by ianco** [comment]
Are you running a revocation registry (tails server)?

https://github.com/hyperledger/aries-cloudagent-python/tree/main/demo#revocation

https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AliceGetsAPhone.md#run-an-instance-of-indy-tails-server

**Comment by edbkei** [comment]
No, I was not running it. I really missed that.

It´s OK  now.

Sorry for any inconvenience.

Thanks.

**Comment by edbkei** [comment]
git clone https://github.com/bcgov/indy-tails-server.git
ubu20w@DESKTOP-CT0HBV1:~$ cd indy-tails-server
ubu20w@DESKTOP-CT0HBV1:~/indy-tails-server$ cd docker
ubu20w@DESKTOP-CT0HBV1:~/indy-tails-server/docker$ ./manage build
ubu20w@DESKTOP-CT0HBV1:~/indy-tails-server/docker$ ./manage start
ubu20w@DESKTOP-CT0HBV1:~$ cd von-network
ubu20w@DESKTOP-CT0HBV1:~/von-network$ ./manage up
Creating von_node2_1     ... done
Creating von_webserver_1 ... done
Creating von_node4_1     ... done
Creating von_node3_1     ... done
Creating von_node1_1     ... done
ubu20w@DESKTOP-CT0HBV1:~/von-network$ cd
ubu20w@DESKTOP-CT0HBV1:~$ cd aries-cloudagent-python/demo
ubu20w@DESKTOP-CT0HBV1:~/aries-cloudagent-python/demo$ ./run_demo faber --revocation
::::::::::::::
Waiting for connection...
Faber      | Revocation registry: XKpAmSE5op1XcmD2W5grr9:4:XKpAmSE5op1XcmD2W5grr9:3:CL:8:faber.agent.degree_schema:CL_ACCUM:7ceb6839-62aa-4d01-b831-f6ab370c83f3 state: posted
Faber      | Revocation registry: XKpAmSE5op1XcmD2W5grr9:4:XKpAmSE5op1XcmD2W5grr9:3:CL:8:faber.agent.degree_schema:CL_ACCUM:7ceb6839-62aa-4d01-b831-f6ab370c83f3 state: active

**Comment by darapich92** [comment]
Hello everyone, I would like to ask how can I edit the schema structure when I run ./run_demo faber?
