### ISSUE TITLE
IP address of an Agent (running locally)

### ISSUE THREAD

**Issue by srbms23** [hyperledger/aries-cloudagent-python#1097]
I installed Agent locally on my computer. However, after start of an Agent, I am not able to establish connection with public ledger. After I tried to send Schema, got error in Swagger saying `No ledger available`. 

The same error appears when I start agent with docker and type wrong endpoint so I think the problem might be in endpoint. (I can start agent with docker. In that case IP address is familiar and everything works.) 
When I want to start an agent locally, I am using local IP address of my computer or `http://192.168.2.10:8020` as endpoint, is that correct?

Is there something else that I forgot? Are there any additional steps that are needed to make agent visible on an IP address or that works automatically?

I saw somewhere that `export LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io` might be necessary, tried, but still does not change anything...

**Comment by ianco** [comment]
Can you provide the command you are running to start the agent locally?

(You are correct that you use your local IP as the agent endpoint.  You can also run von-network to listen on your local IP by providing it as a startup parameter - start von-network with something like `./manage start <your_ip> --logs`.  Or else if you export `LEDGER_URL` as you suggest, that should also work.)

**Comment by esune** [comment]
Likely related to #1152, see [this comment](https://github.com/hyperledger/aries-cloudagent-python/issues/1152#issuecomment-854866562).
