### ISSUE TITLE
Credential attributes naming inconsistency

### ISSUE THREAD

**Issue by mat-work** [hyperledger/aries-cloudagent-python#1098]
https://github.com/hyperledger/aries-cloudagent-python/blob/73361c60ed2db15c6ed9fdc173fe91ece9f7c15c/aries_cloudagent/messaging/util.py#L139-L152

For verifications, credential attributes are converted to lowercase, and spaces are removed.
On the other hand, a credential Schema can be defined without any restrictions.

The outcome is that verifications do not work when the attribute name, previously defined in the schema, contains upper case or spaces characters.

**Comment by swcurran** [comment]
hmm...changing the schema attribute names would seem to be bad thing.  Am I missing something?

**Comment by mat-work** [comment]
I am not sure why attribute names are "canonicalized for indy proofs and credential offers". That leads to a problem if the schema was not created with lowercase attribute names.

**Comment by dbluhm** [comment]
To reiterate, it's the asymmetry that is the problem; before writing the schema, the input attribute names are not canonized, allowing us to write schemas with attributes like `FirstName`, `Age`, etc. Likewise, on issuance, the attribute names remain capitalized (they'd have to match the schema exactly for the signature, right?). But when fetching credentials for a presentation request, attribute names are canonized so even though a request might have `FirstName` and `Age`, it checks for credentials with attributes `firstname` and `age` and fails to return the relevant credentials.

**Comment by sklump** [comment]
Also, indy canonicalizes in primary proofs, in proof revealed attribute groups but not revealed attributes, ... it's a dog's breakfast and it's painful for everyone. Welcome to the machine.

**Comment by swcurran** [comment]
I'm not sure what to do about this, so am going to close.  Please re-open if it should be re-opened.

Thanks
