### ISSUE TITLE
Send Credential Offer should allow Issuer to edit Credential terms, if responding to a Proposal

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#1103]
In the current API, when an Issuer is responding to a Credential Proposal there is no way for them to edit the content of the proposed Credential.

Expected behaviour - the Issuer should be able to set the content of the Credential they are offering, without having to start a new proposal.  The "send-offer" API should accept an optional Credential Preview (which may be different than the Proposal).

If an updated Credential preview is not provided then the original Proposal will be used.

**Comment by sklump** [comment]
You can send a free offer on the same connection id, but that orphans the old cred ex record. A text body for the bound offer API would be the way in. There might be some cred ex record state gotchas.

**Comment by sklump** [comment]
Note that this approach only allows the issuer to modify attribute values in the negotiation. To change the schema/cred def, the issuer would need to start a new offer: these are in the proposal, not the preview. I'll flesh it out as specified and we can quibble over the PR.

@ianco
