### ISSUE TITLE
did doc - referenced verification methods should be plain strings

### ISSUE THREAD

**Issue by Moopli** [hyperledger/aries-cloudagent-python#1104]
Verification method references in the did doc implementation are currently [objects](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/connections/models/diddoc/diddoc.py#L137) with a `type` member and a `publicKey` member (a did url), whereas in the spec a verification method reference is a [string](https://www.w3.org/TR/did-core/#referring-to-verification-methods) (a url, usually a did url).

**Comment by swcurran** [comment]
@shaangill025 - another one for you. 

Likely needs handling similiar to #1106?

**Comment by domwoe** [comment]
This bugs me as well. 
I'm trying to create a DID Exchange request with my public DID to establish a connection between to public DIDs.
According to to RFC 0023 I just include my public DID in the request and do not attach a DIDdoc.

On the recipient side I use the resolver interface to get the DID doc which is a pyDID DID Document. This is currently not compatible with the [did doc model] (https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/connections/models/diddoc/diddoc.py)

What's the plan here?
- Change the model to comply with the did spec?
- Don't use this model in the DIDX manager and instead use pyDID?

**Comment by domwoe** [comment]
Also related:  #1050
