### ISSUE TITLE
AriesOpenAPIDemo not working with von-network

### ISSUE THREAD

**Issue by jordanmmck** [hyperledger/aries-cloudagent-python#111]
The OpenAPI demo is failing for me. I'm up to date on `aries-cloudagent-python` and `von-network`. Also just updated Docker. Using Docker desktop 2.1.0.0 on Mac 10.14.6 Mojave.

I found exactly where it's failing, and got it working by making basically one change (see below), but I don't how to solve the problem properly so not confident creating a PR.

Steps taken:

1. Clone the `aries-cloudagent-python` repo and the `von-network` repo.
2. `cd von-network`, `./manage build`, `./manage start`
3. `cd aries-cloudagent-python/demo`, `./run_demo faber`

The faber agent waits for a long time, then fails:

![Screen Shot 2019-07-31 at 4 36 56 PM](https://user-images.githubusercontent.com/16055268/62255308-71b85580-b3b1-11e9-88c9-4edc957fefb0.png)

I tracked the problem down to line 27/28 in `demo/runners/support/agent.py`. These are the lines:

```
    DEFAULT_INTERNAL_HOST = os.getenv("DOCKERHOST") or "host.docker.internal"
    DEFAULT_EXTERNAL_HOST = DEFAULT_INTERNAL_HOST
```

When this code runs `DOCKERHOST` is `192.168.65.3`. When `DEFAULT_INTERNAL_HOST` has this value it fails grabbing the swagger json in `faber.py`. Everything works perfectly if I change these lines to:

```
    DEFAULT_EXTERNAL_HOST = os.getenv("DOCKERHOST") or "host.docker.internal"
    DEFAULT_INTERNAL_HOST = 'localhost'
```

So `DEFAULT_EXTERNAL_HOST` should be `192.168.65.3` for me, but `DEFAULT_INTERNAL_HOST` must be `localhost` or `127.0.0.1` or `0.0.0.0`.

**Comment by swcurran** [comment]
Thanks - we'll take a look at this. Weird that this has worked many times before - not sure what is different from a setup we've seen before and this. That said - if we have two variables, why are we setting them to the same thing?  We should be looking at where those two variables are used.

I wonder if both were set to 'localhost' would the demo start up properly?

**Comment by jordanmmck** [comment]
> I wonder if both were set to 'localhost' would the demo start up properly?

I tried that and it failed for me. `DEFAULT_EXTERNAL_HOST` needs to be set to that `DOCKERHOST` env var, and `DEFAULT_INTERNAL_HOST` needs to be some variation of `localhost`.

**Comment by swcurran** [comment]
@jordanmmck - a user on rocketchat reported the same stack trace and a timeout change was made to the code and recently merged.   Could you please retry and report back the results?  If all good, please close this error.

If it works, I think it can be put down to timing, and not the adjustment you made above.

Thanks!

**Comment by jordanmmck** [comment]
Pulled latest changes, and it all seems to be working fine now. Thanks @swcurran, closing now.
