### ISSUE TITLE
Problem reports in credential issuance and presenting proof

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#1122]
[Aries RFC 36](https://github.com/hyperledger/aries-rfcs/blob/master/features/0036-issue-credential/README.md) describes the problem report message as being [adopted](https://github.com/hyperledger/aries-rfcs/blob/master/features/0036-issue-credential/README.md#messages) into the issuance protocol. Similar language is used in [RFC 37 for presentations](https://github.com/hyperledger/aries-rfcs/blob/master/features/0037-present-proof/README.md#tutorial). The problem report message is significant in both of these exchanges as it enables the credential recipient or prover to explicitly reject a credential offer or presentation request. In the 2.0 versions of both of these protocols in ACA-Py, we now have the ability to send a problem report message from the Admin API. However, in both the 1.0 and 2.0 versions, there is no [adopted](https://github.com/hyperledger/aries-rfcs/blob/master/0000-template-protocol.md#adopted-messages) problem-report message and just the base problem-report type is used.

From my reading, this isn't consistent with the RFCs. Additionally, this requires the controller to handle presentation or credential issuance rejection by handling problem reports, relayed via webhook, and attempting to correlate a problem report to a specific exchange record in order to perform clean up and not leave dangling exchange records behind. If we had explicitly adopted problem report messages, separate handlers could be defined that better supported the controllers ability to follow up on the rejection by cleaning up or taking another action; or, the separate handlers could automatically perform clean up of these exchange records.

Fully recognizing that there's a good chance I'm missing context, is there something informing the usage of the base problem report message in these protocols instead of adopted problem report messages?

**Comment by dbluhm** [comment]
cc @farskipper

**Comment by sklump** [comment]
I'll take a look tomorrow.

**Comment by dbluhm** [comment]
We discussed this during the ACA-PUG meeting this week. @andrewwhitehead brought up that this gets into some changes from an old PR of his (https://github.com/hyperledger/aries-cloudagent-python/pull/285/files) when it comes to the problem report message and ensuring that it does not create loops on processing errors. Additionally, since adopting problem report messages into protocols is a common practice in DIDComm protocols, it was pointed out that it would be nice to be able to not have to redefine ProblemReports in each protocol but still be able to have specific handlers for each protocol.
