### ISSUE TITLE
Can't emit webhooks for stateless records anymore

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1123]
The event bus PR that was merged yesterday made a change that now won't allow you to emit events for stateless records anymore. Is this intended?

PR: #1063
Blame: https://github.com/hyperledger/aries-cloudagent-python/pull/1063/files#diff-fe738d195b46caab22aaa9e802de272264dc1f986e589aad2a2bd0965f98ac14R382

@farskipper @dbluhm

**Comment by dbluhm** [comment]
Not intentional -- I'll take a look

**Comment by TimoGlastra** [comment]
Verified that #1124 fixed the issue
