### ISSUE TITLE
OOB InvitationReceiveRequest model

### ISSUE THREAD

**Issue by domwoe** [hyperledger/aries-cloudagent-python#1138]
The model specifies `service_dids` and `services`, but the example value in the Open API definition only specifies `service_dids`.
I guess `service_dids` is deprecated. I can't find anything about it in the OOB RFC and ACA-Py will return an error when `services` is not specified. `Services` should either accept a (fully-qualified) DID or a DIDcomm service object.

**Comment by swcurran** [comment]
@shaangill025 -- can you look at this when you get a chance?  At least take a look and comment on the effort.

**Comment by shaangill025** [comment]
> The model specifies `service_dids` and `services`, but the example value in the Open API definition only specifies `service_dids`.
> I guess `service_dids` is deprecated. I can't find anything about it in the OOB RFC and ACA-Py will return an error when `services` is not specified. `Services` should either accept a (fully-qualified) DID or a DIDcomm service object.
This is what is happening, services accept a `DID` that is resolved to retrieve it's DIDDoc service block or a `DIDComm Service` object.
https://github.com/hyperledger/aries-cloudagent-python/blob/a322a8650a94b0488bd288a14fc59a2792f90fd3/aries_cloudagent/protocols/out_of_band/v1_0/messages/invitation.py#L135
