### ISSUE TITLE
Issue running tests

### ISSUE THREAD

**Issue by domwoe** [hyperledger/aries-cloudagent-python#1142]
When running `./scripts/run_test` I get the following error:

```
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
#9 22.37     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
while installing `multidict`

The error can be fixed by adding `gcc` and `python3-dev` instead of `python3` to the dependencies in `Dockerfile.test`.

**Comment by TimoGlastra** [comment]
Seems related to this PR that just got merged: https://github.com/hyperledger/aries-cloudagent-python/pull/1132

Does that solve your issue?

**Comment by domwoe** [comment]
@TimoGlastra  ha, indeed. I've tried to run tests before rebasing on the current main. Thanks!
