### ISSUE TITLE
[Endorser Protocol] Call to ​/transactions​/{conn_id}​/set-endorser-info fails if other agent has not already set their role

### ISSUE THREAD

**Issue by esune** [hyperledger/aries-cloudagent-python#1146]
When setting up a connection between an author and an endorser, it is a pre-requisites to prepare metadata about the connection with the endorser.

The calls MUST happen in the following order:
  -  `/transactions/{conn_id}/set-endorser-role` 
  - `​/transactions​/{conn_id}​/set-endorser-info`

When calling the second endpoint, the request will fail if the other agent has not yet set their role on the connection using the `/transactions/{conn_id}/set-endorser-role`: it appears that validation in the request handler (see [here](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/protocols/endorse_transaction/v1_0/routes.py#L674)) is expecting both roles to be set and raising an exception if they are not, making this process synchronous. 

The expected result would be that the process of setting endorser metadata on the connection is asynchronous.

**Comment by esune** [comment]
This could be closed as #1153 was merged - unless we need to do further tweaking @ianco

**Comment by esune** [comment]
It actually looks like there still is something lingering: it is now possible to complete the sequence of API calls correctly on the `author` side, however on the `endorser` side the following error will be thrown when the author calls `/transactions​/{conn_id}​/set-endorser-info`:
```
ndorser_1                 | 2021-05-06 21:51:27,633 aries_cloudagent.core.conductor ERROR Exception in message handler:
endorser_1                 | Traceback (most recent call last):
endorser_1                 |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/endorse_transaction/v1_0/manager.py", line 531, in set_transaction_their_job
endorser_1                 |     self._session, receipt.sender_did, receipt.recipient_did
endorser_1                 |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/connections/models/conn_record.py", line 271, in retrieve_by_did
endorser_1                 |     return await cls.retrieve_by_tag_filter(session, tag_filter, post_filter)
endorser_1                 |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/messaging/models/base_record.py", line 250, in retrieve_by_tag_filter
endorser_1                 |     cls.__name__, tag_filter, f", {post_filter}" if post_filter else ""
endorser_1                 | aries_cloudagent.storage.error.StorageNotFoundError: ConnRecord record not found for {'my_did': 'wRYyL8WjnVyrHEcpWdpSg'}
endorser_1                 |
endorser_1                 | The above exception was the direct cause of the following exception:
endorser_1                 |
endorser_1                 | Traceback (most recent call last):
endorser_1                 |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/dispatcher.py", line 195, in handle_message
endorser_1                 |     await handler(context, responder)
endorser_1                 |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/endorse_transaction/v1_0/handlers/transaction_job_to_send_handler.py", line 36, in handle
endorser_1                 |     context.message, context.message_receipt
endorser_1                 |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/endorse_transaction/v1_0/manager.py", line 534, in set_transaction_their_job
endorser_1                 |     raise web.HTTPNotFound(reason=err.roll_up) from err
endorser_1                 | aiohttp.web_exceptions.HTTPNotFound: ConnRecord record not found for {'my_did': 'wRYyL8WjnVyrHEcpWdpSg'}.
endorser_1                 | 2021-05-06 21:51:27,643 aries_cloudagent.core.conductor ERROR DON'T shutdown on HTTPNotFound ConnRecord record not found for {'my_did': 'wRYyL8WjnVyrHEcpWdpSg'}.
```

This does not appear to be causing issues - the endorser is able to carry on, set its own role in the connection metadata and endorse transactions correctly. It is however causing noise in the logs that can be misleading.

**Comment by HarshMultani-AyanWorks** [comment]
> When setting up a connection between an author and an endorser, it is a pre-requisites to prepare metadata about the connection with the endorser.
> 
> The calls MUST happen in the following order:
> 
> * `/transactions/{conn_id}/set-endorser-role`
> * `​/transactions​/{conn_id}​/set-endorser-info`
> 
> When calling the second endpoint, the request will fail if the other agent has not yet set their role on the connection using the `/transactions/{conn_id}/set-endorser-role`: it appears that validation in the request handler (see [here](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/protocols/endorse_transaction/v1_0/routes.py#L674)) is expecting both roles to be set and raising an exception if they are not, making this process synchronous.
> 
> The expected result would be that the process of setting endorser metadata on the connection is asynchronous.

Hi @esune,

When we set the endorser-info we attach the public did of the endorser to that particular connection metadata.
So, I was thinking that when the author's agent is setting up this endorser-info, it should know that the did that he/she is setting is of the agent who has a role of TRANSACTION_ENDORSER for this particular transaction / connection record. Therefore, I am thinking that this check should be there.

**Comment by HarshMultani-AyanWorks** [comment]
> It actually looks like there still is something lingering: it is now possible to complete the sequence of API calls correctly on the `author` side, however on the `endorser` side the following error will be thrown when the author calls `/transactions​/{conn_id}​/set-endorser-info`:
> 
> ```
> ndorser_1                 | 2021-05-06 21:51:27,633 aries_cloudagent.core.conductor ERROR Exception in message handler:
> endorser_1                 | Traceback (most recent call last):
> endorser_1                 |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/endorse_transaction/v1_0/manager.py", line 531, in set_transaction_their_job
> endorser_1                 |     self._session, receipt.sender_did, receipt.recipient_did
> endorser_1                 |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/connections/models/conn_record.py", line 271, in retrieve_by_did
> endorser_1                 |     return await cls.retrieve_by_tag_filter(session, tag_filter, post_filter)
> endorser_1                 |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/messaging/models/base_record.py", line 250, in retrieve_by_tag_filter
> endorser_1                 |     cls.__name__, tag_filter, f", {post_filter}" if post_filter else ""
> endorser_1                 | aries_cloudagent.storage.error.StorageNotFoundError: ConnRecord record not found for {'my_did': 'wRYyL8WjnVyrHEcpWdpSg'}
> endorser_1                 |
> endorser_1                 | The above exception was the direct cause of the following exception:
> endorser_1                 |
> endorser_1                 | Traceback (most recent call last):
> endorser_1                 |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/dispatcher.py", line 195, in handle_message
> endorser_1                 |     await handler(context, responder)
> endorser_1                 |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/endorse_transaction/v1_0/handlers/transaction_job_to_send_handler.py", line 36, in handle
> endorser_1                 |     context.message, context.message_receipt
> endorser_1                 |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/endorse_transaction/v1_0/manager.py", line 534, in set_transaction_their_job
> endorser_1                 |     raise web.HTTPNotFound(reason=err.roll_up) from err
> endorser_1                 | aiohttp.web_exceptions.HTTPNotFound: ConnRecord record not found for {'my_did': 'wRYyL8WjnVyrHEcpWdpSg'}.
> endorser_1                 | 2021-05-06 21:51:27,643 aries_cloudagent.core.conductor ERROR DON'T shutdown on HTTPNotFound ConnRecord record not found for {'my_did': 'wRYyL8WjnVyrHEcpWdpSg'}.
> ```
> 
> This does not appear to be causing issues - the endorser is able to carry on, set its own role in the connection metadata and endorse transactions correctly. It is however causing noise in the logs that can be misleading.

Hi @esune,

As of what I know, nothing goes on the endorser's side when the author sets the endorser-info as there is no outbound call.
Can you  tell the steps you carried out which led to this error?

**Comment by esune** [comment]
> 
> Hi @esune,
> 
> When we set the endorser-info we attach the public did of the endorser to that particular connection metadata.
> So, I was thinking that when the author's agent is setting up this endorser-info, it should know that the did that he/she is setting is of the agent who has a role of TRANSACTION_ENDORSER for this particular transaction / connection record. Therefore, I am thinking that this check should be there.

Hi @HarshMultani-AyanWorks ,

the issue here (fixed by #1153 ) was that the `TRANSACTION_AUTHOR` would not be able to successfully call `/transactions​/{conn_id}​/set-endorser-info` unless the `TRANSACTION_ENDORSER` had already set the metadata on their end. This step is going to be asynchronous in most scenarios where the author/endorser setup is automated (see https://github.com/bcgov/aries-vcr-issuer-agency as an example), o having a strict requirement about having things happen in a specific order seems too restrictve.

If the metadata is not set correctly and an endorsement request is fired, then the transaction will likely fail - I think this is acceptable.

**Comment by esune** [comment]
> 
> Hi @esune,
> 
> As of what I know, nothing goes on the endorser's side when the author sets the endorser-info as there is no outbound call.
> Can you tell the steps you carried out which led to this error?

1. Stand up an agent as `endorer` and one as `author`. I am using multitenancy for the author, but I don;t think this would make a difference (it shouldn't)
2. Create a connection/OOB invitation on the `endorer` side, and accept it on the `author`
3. Call `/transactions/{conn_id}/set-endorser-role` on the `author`
4. Call `​/transactions​/{conn_id}​/set-endorser-info`

At this point you should see the stack trace on the `endorser`.

This *might* be a red herring, however that stack trace seems to be happening every time when the above procedure is completed so I think it might be possibly related to validation of the connection metadata on the endorser end.

**Comment by HarshMultani-AyanWorks** [comment]
> > Hi @esune,
> > As of what I know, nothing goes on the endorser's side when the author sets the endorser-info as there is no outbound call.
> > Can you tell the steps you carried out which led to this error?
> 
> 1. Stand up an agent as `endorer` and one as `author`. I am using multitenancy for the author, but I don't think this would make a difference (it shouldn't)
> 2. Create a connection/OOB invitation on the `endorer` side, and accept it on the `author`
> 3. Call `/transactions/{conn_id}/set-endorser-role` on the `author`
> 4. Call `​/transactions​/{conn_id}​/set-endorser-info`
> 
> At this point you should see the stack trace on the `endorser`.
> 
> This _might_ be a red herring, however that stack trace seems to be happening every time when the above procedure is completed so I think it might be possibly related to validation of the connection metadata on the endorser end.



> > Hi @esune,
> > As of what I know, nothing goes on the endorser's side when the author sets the endorser-info as there is no outbound call.
> > Can you tell the steps you carried out which led to this error?
> 
> 1. Stand up an agent as `endorer` and one as `author`. I am using multitenancy for the author, but I don't think this would make a difference (it shouldn't)
> 2. Create a connection/OOB invitation on the `endorer` side, and accept it on the `author`
> 3. Call `/transactions/{conn_id}/set-endorser-role` on the `author`
> 4. Call `​/transactions​/{conn_id}​/set-endorser-info`
> 
> At this point you should see the stack trace on the `endorser`.
> 
> This _might_ be a red herring, however that stack trace seems to be happening every time when the above procedure is completed so I think it might be possibly related to validation of the connection metadata on the endorser end.


I checked this. I am not using multitenancy and followed the same steps, and nothing came on the endorser side for me.

**Comment by HarshMultani-AyanWorks** [comment]
> > Hi @esune,
> > When we set the endorser-info we attach the public did of the endorser to that particular connection metadata.
> > So, I was thinking that when the author's agent is setting up this endorser-info, it should know that the did that he/she is setting is of the agent who has a role of TRANSACTION_ENDORSER for this particular transaction / connection record. Therefore, I am thinking that this check should be there.
> 
> Hi @HarshMultani-AyanWorks ,
> 
> the issue here (fixed by #1153 ) was that the `TRANSACTION_AUTHOR` would not be able to successfully call `/transactions​/{conn_id}​/set-endorser-info` unless the `TRANSACTION_ENDORSER` had already set the metadata on their end. This step is going to be asynchronous in most scenarios where the author/endorser setup is automated (see https://github.com/bcgov/aries-vcr-issuer-agency as an example), o having a strict requirement about having things happen in a specific order seems too restrictve.
> 
> If the metadata is not set correctly and an endorsement request is fired, then the transaction will likely fail - I think this is acceptable.

Understood

**Comment by esune** [comment]
>
> 
> I checked this. I am not using multitenancy and followed the same steps, and nothing came on the endorser side for me.

I will check again whn I have a minute, it might be something that got cleaned up by a new commit maybe? It wasn't a breaking issue anyway, mostly trying to get rid of log noise (e.g.: stack traces even when the agent is actually working fine).

**Comment by swcurran** [comment]
Closing this issue.
