### ISSUE TITLE
`aca-py start` not working? 

### ISSUE THREAD

**Issue by jordanmmck** [hyperledger/aries-cloudagent-python#115]
Apologies if I'm missing something obvious, but it seems like `aca-py start` is not recognized? 

Steps I took:

```
pip3 install aries-cloudagent
```

Trying to run `aca-py` was producing complaints about `libsodium` missing, so I did `brew install libsodium` and all seemed good...

If I run the example commands from the [dev readme](https://github.com/hyperledger/aries-cloudagent-python/blob/master/DevReadMe.md#running), however, I get `unrecognized arguments: start`. 

```
$ aca-py start  --inbound-transport http 0.0.0.0 8000 --outbound-transport http
usage: aca-py [-h] -it <module> <host> <port> -ot <module>
              [--log-config <path-to-config>] [--log-level <log-level>]
              [-e <endpoint>] [-l <label>] [--seed <wallet-seed>]
              [--storage-type <storage-type>] [--wallet-key <wallet-key>]
              [--wallet-name <wallet-name>] [--wallet-type <wallet-type>]
              [--wallet-storage-type <storage-type>]
              [--wallet-storage-config <storage-config>]
              [--wallet-storage-creds <storage-creds>]
              [--pool-name <pool-name>]
              [--genesis-transactions <genesis-transactions>]
              [--genesis-url <genesis-url>] [--admin <host> <port>]
              [--admin-api-key <api-key>] [--admin-insecure-mode] [--debug]
              [--debug-seed <debug-did-seed>] [--debug-connections]
              [--accept-invites] [--accept-requests] [--auto-ping-connection]
              [--auto-respond-messages] [--auto-respond-credential-offer]
              [--auto-respond-presentation-request]
              [--auto-verify-presentation] [--no-receive-invites]
              [--help-link <help-url>] [--invite] [--timing]
              [--protocol <module>] [--webhook-url <url>]
aca-py: error: unrecognized arguments: start
```

Screenshot:

![Screen Shot 2019-08-02 at 10 25 45 AM](https://user-images.githubusercontent.com/16055268/62387610-ea352880-b50f-11e9-9e78-50935760a991.png)

System: macOS 10.14.6 Mojave

**Comment by jordanmmck** [comment]
Looking into the `aries_cloudagent` directory in my Python3 site-packages, I see that the `commands` directory is not there, while it is present in the `aries_cloudagent` dir in the repo project.

![Screen Shot 2019-08-02 at 10 47 58 AM](https://user-images.githubusercontent.com/16055268/62388791-156d4700-b513-11e9-8a2f-96e1d4183c5b.png)

**Comment by brianorwhatever** [comment]
interesting.. @nrempel and @andrewwhitehead do you have any ideas why the pypi package might be missing the commands?

**Comment by andrewwhitehead** [comment]
Leave out the ‘start’ for aries_cloudagent before 0.3.0, which hasn’t been packaged yet.

**Comment by swcurran** [comment]
Sorry for the confusion.  We're working on a better way to tag documentation to releases so this confusion won't arise.  Plan is to get ReadTheDocs going that is based on the latest released code so the documentation is tied to the release.

**Comment by brianorwhatever** [comment]
Great to hear @swcurran! Can @jordanmmck and I assist in anyway with that work?
