### ISSUE TITLE
Return id of the new ledger object on endorsed transaction write

### ISSUE THREAD

**Issue by esune** [hyperledger/aries-cloudagent-python#1159]
When a transaction `author` writes a correctly-endorsed transaction on the ledger, the response returned when calling `/transactions/{tran_id}/write` does not contain the `id` of the object that was just written (e.g.: schema definition, credential definition).

It would be nice to be able to obtain the id of the new object (corresponding to the indy `txnId`) in the result of the `write`, rather than having to make an additional call to either the schemas or credential definition endpoints to verify the object was written correctly.

This would also be consistent with non-endorsed writes, which return the id of the object that was created as part of the payload.

**Comment by esune** [comment]
Relates to #1026 and #1238

**Comment by swcurran** [comment]
@ianco -- given the new endorser handling that removes the controller from a lot of the work -- do we still need this feature?  If not, please close.

**Comment by ianco** [comment]
I think this would be a useful feature.  The processing *can* be automated, but some implementations may want to keep control in their controller.

**Comment by swcurran** [comment]
@ianco -- is this still an issue or has it been resolved in the endorser updates?

**Comment by ianco** [comment]
This one is fixed AFAIK, the cred_def_id was added to the response recently (i.e. in one of the `0.7.4-rcx` releases)
