### ISSUE TITLE
Error 400: Presentation exchange xxx in request_sent state (must be presentation_received)

### ISSUE THREAD

**Issue by RomainMercier1975** [hyperledger/aries-cloudagent-python#1163]
Hello, 
when I try to verifiy a proof, I have this message (400: Presentation exchange xxx in request_sent state (must be presentation_received))
It seems that when verifier get All Proof Requests, my request is not good. Maybe a step is missing.

-------------------------------------------------------------
1 : When I send this proof request (without predicates) :
-------------------------------------------------------------
```
{
  "connection_id": "{{VERIFIER_CONNECTION_ID}}",
  "proof_request": {
    "name": "ProofVaccination",
    "version": "1.0",
    "requested_attributes": {
      "a_lname": {
          "name": "lastname",
          "restrictions": [
          {
            "attr::doc_id::value": "1122"
          }
          ]         
      },
      "a_dose": {
          "name": "dose",
          "restrictions": [
          {
            "attr::doc_id::value": "1122"
          }
          ]         
      }
    },
    "requested_predicates": {}
  }
}
```
------------------------------------------------------------
After that prover accepts, I can get this proof Request :
-------------------------------------------------------------
```
        {
            "state": "verified",
            "updated_at": "2021-05-10 14:44:55.587962Z",
            "auto_present": false,
            "created_at": "2021-05-10 14:42:46.876413Z",
            "verified": "false",
            "connection_id": "8486a2ac-6b09-4f04-ae77-be08cd61ddcb",
            "presentation": {
                "proof": {
[...]
                },
                "requested_proof": {
[...]
                },
                "identifiers": [
                    {
                        "schema_id": "4kfmXB6jB2jB5Knt7uskb6:2:ROM_DEMO_01:0.1",
                        "cred_def_id": "4kfmXB6jB2jB5Knt7uskb6:3:CL:8218:ROMS35",
                        "rev_reg_id": null,
                        "timestamp": null
                    }
                ]
            },
            "initiator": "self",
            "thread_id": "6f40ebfd-3f9a-4075-9e22-2d62bef2f531",
            "presentation_request": {
[...]
            },
            "presentation_request_dict": {
                "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/present-proof/1.0/request-presentation",
                "@id": "6f40ebfd-3f9a-4075-9e22-2d62bef2f531",
[...]
            },
            "presentation_exchange_id": "48545f65-e6aa-445d-8ed6-73b937705006",
            "trace": false,
            "role": "verifier"
        },
```

Then, when verifier verify this Proof (with exchange id = "48545f65-e6aa-445d-8ed6-73b937705006")
Everything is OK.

---------------------------------------------------------
2 : But when I add a predicate to my proof request :
---------------------------------------------------------
```
{
  "connection_id": "{{VERIFIER_CONNECTION_ID}}",
  "proof_request": {
    "name": "ProofVaccination",
    "version": "1.0",
    "requested_attributes": {
      "a_lname": {
          "name": "lastname",
          "restrictions": [
          {
            "attr::doc_id::value": "1122"
          }
          ]         
      },
      "a_dose": {
          "name": "dose",
          "restrictions": [
          {
            "attr::doc_id::value": "1122"
          }
          ]         
      }
    },
    "requested_predicates": {
      "a_dose": {
        "name": "dose",
        "p_type": "<",
        "p_value": 10,
        "restrictions": [
          {
            "attr::doc_id::value": "1122"
          }
        ]
      }
    }
  }
}
```
(I try with and without the bloc "a_dose" in my "requested attributes")

--------------------------------------------------------
After that prover accepts, I get this proof Request :
--------------------------------------------------------
```
    {
            "state": "request_sent",
            "updated_at": "2021-05-10 15:14:26.827236Z",
            "auto_present": false,
            "created_at": "2021-05-10 15:14:26.827236Z",
            "connection_id": "8486a2ac-6b09-4f04-ae77-be08cd61ddcb",
            "initiator": "self",
            "thread_id": "88731c38-e9c7-4a6e-b22a-28fa281ac890",
            "presentation_request": {
[...]
            },
            "presentation_request_dict": {
                "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/present-proof/1.0/request-presentation",
                "@id": "88731c38-e9c7-4a6e-b22a-28fa281ac890",
[...]
            },
            "presentation_exchange_id": "f3544145-8ec8-4ee6-a8d1-4d3c9032b2a3",
            "trace": false,
            "role": "verifier"
        }
```
Then, when verifier verify this Proof (with exchange id = "f3544145-8ec8-4ee6-a8d1-4d3c9032b2a3")
I have the error :

_**400: Presentation exchange f3544145-8ec8-4ee6-a8d1-4d3c9032b2a3 in request_sent state (must be presentation_received)**_

We can see that my "state" is "request_sent" in that case, whereas in my first exemple, "state" is "verified"...
Do you know what's wrong ?

If you need more information, ask me.
Thank You.
Romain

**Comment by RomainMercier1975** [comment]
It dosen't work, it's the same.

When I "Get All Proof Requests for a Wallet, my result is in state "request_received" instead of being in "presentation_sent"
After when "Verifier Get All Proof Requests" my state is "request_sent" instead of being "presentation_received"...

It's what I can see after more analysis.

**Comment by sklump** [comment]
Also, a proof request cannot use an attribute in the requested predicates that it asks to reveal in the requested attributes.

**Comment by sklump** [comment]
I can't reproduce it, unless I repeat an attribute in requested_attribute and requested_predicates

**Comment by sklump** [comment]
![1163 1](https://user-images.githubusercontent.com/9336556/117866268-f01f7800-b264-11eb-95a5-abd3a4435c55.png)

produces

![1163 2](https://user-images.githubusercontent.com/9336556/117866291-f6adef80-b264-11eb-95e3-7daa57734e93.png)

**Comment by sklump** [comment]
my first guess is that doc_id ought not be in the restriction for lastname

**Comment by sklump** [comment]
Here's the input you want:
```
{
  "connection_id": "739a349a-4001-4acc-83dd-fbefd9fb6cd6",
  "proof_request": {
    "name": "ProofVaccination",
    "version": "1.0",
    "requested_attributes": {
      "a_lname": {
        "name": "lastname",
        "restrictions": [
          {
            "schema_name": "z"
          }
        ]         
      },
      "a_doc_id": {
        "name": "doc_id",
        "restrictions": [
          {
            "schema_name": "z",
            "attr::doc_id::value": "1200"
          }
        ]         
      }
    },
    "requested_predicates": {
      "p_dose": {
        "name": "dose",
        "p_type": "<",
        "p_value": 10,
        "restrictions": [
          {
            "schema_name": "z"
          }
        ]         
       }
    }
  }
}
```
To restrict an attribute to a value, request its revelation subject to its value restriction.

Also, note that the proof request always has to have at least one restriction per requested attribute/predicate, or else the holder will self-assert the value - which complies with that proof request. That's what appeared to happen in your case - since the dose predicate had no restriction, it self-asserted the dose instead of providing proof on its predicate. Indeed verifier logs state:
```
aries_cloudagent.indy.sdk.verifier ERROR Presentation on nonce=575121269548308614631215 cannot be validated: Presentation predicates mismatch requested predicate a_dose
```

**Comment by sklump** [comment]
If an attribute restriction requires a value for a different attribute, the prover can create the proof but indy rejects it on at the verifier. Note that value restriction was a late bolt-on well into the dereliction stage of indy development.

**Comment by RomainMercier1975** [comment]
When I try this request it works...
```
{
  "connection_id": "{{VERIFIER_CONNECTION_ID}}",
  "proof_request": {
    "name": "ProofVaccination",
    "version": "1.0",
    "requested_attributes": {
      "0_lastname_uuid": {
          "name": "lastname",
          "restrictions": [
              {
                  "schema_name": "ROM_DEMO_01"
              }
          ]
      },
      "0_doc_id_uuid": {
          "name": "doc_id",
          "restrictions": [
              {
                  "schema_name": "ROM_DEMO_01",
                  "attr::doc_id::value": "1122"
              }
          ]
      }
    },
    "requested_predicates": {
        "0_dose_GE_uuid": {
        "name": "dose",
        "p_type": ">",
        "p_value": 13,
        "restrictions": [
          {
            "schema_name": "ROM_DEMO_01"
          }
        ]         
       }
    }
  }
}
```
But I've the same result when I ask dose>13 and dose<13, as if my predicate wasn't consider.

**Comment by swcurran** [comment]
What is the data in the verifiable credential that you are verifying.  Notably, is "dose" an integer or a string?  For predicates to work, the value must be an integer.

That will adjust whether it will work in general. However, the fact that the predicate works for "<" and ">" is very weird.

Note that these things are all part of the Indy SDK and Indy AnonCreds functionality, not ACA-Py.  ACA-Py is just calling Indy to process the credential.  Not that it matters in getting the use case right, but just wanted to point that out.  If you are looking deeper into this, using the test cases within the Indy SDK to experiment with credentials and proofs might be a good way to dig into this.

**Comment by ianco** [comment]
> You can't put `"attr::doc_id::value": "1122"` into a predicate restriction, only an attribute restriction.

You *can* put this into a predicate restriction, however you *also* have to put the "doc_id" into a revealed attribute (so the proof verification can verify the restriction).  (Note this is with indy sdk 1.16.0 and above)

**Comment by ianco** [comment]
> > You can't put `"attr::doc_id::value": "1122"` into a predicate restriction, only an attribute restriction.
> 
> You _can_ put this into a predicate restriction, however you _also_ have to put the "doc_id" into a revealed attribute (so the proof verification can verify the restriction). (Note this is with indy sdk 1.16.0 and above)

I should clarify, indy-sdk (1.16.0) will accept this but aca-py won't, due to some aggressive validations that aca-py does when it receives a presentation.  I'll open a separate ticket with the details.

**Comment by RomainMercier1975** [comment]
Hello, i've some news :
This is the verifier request to get a proof.

```
{
  "connection_id": "{{VERIFIER_CONNECTION_ID}}",
  "proof_request": {
    "name": "ProofVaccination",
    "version": "1.0",
    "requested_attributes": {
      "0_lastname_uuid": {
          "name": "lastname",
          "restrictions": [
              {
                "cred_def_id": "4kfmXB6jB2jB5Knt7uskb6:3:CL:8286:ROMS41"
              }
          ]
      },
      "0_doc_id_uuid": {
          "name": "doc_id",
          "restrictions": [
              {
                  "cred_def_id": "4kfmXB6jB2jB5Knt7uskb6:3:CL:8286:ROMS41"
              }
          ]
      }
    },
    "requested_predicates": {
        "0_dose_GE_uuid": {
        "name": "dose",
        "p_type": "<",
        "p_value": 13,
        "restrictions": [
          {
            "cred_def_id": "4kfmXB6jB2jB5Knt7uskb6:3:CL:8286:ROMS41"
          }
        ]         
       }
    }
  }
}
```
As a prover, I try to send a proof to the verifier with the request "/present-proof/records"

- When the predicate is verified, the state of my request become "presentation_sent", and the verifier get the proof and the state is "presentation_received". 
At the end, the verifier can validate the proof with the request "/present-proof/records/{exchange_id}/verify-presentation".

- When the predicate isn't verified, the state of my request remaind "request_sent", and the verifier get a result with the same state ("request_sent").
At the end, the verifier try yto validate with the request "/present-proof/records/{exchange_id}/verify-presentation", and get my initial message : Error 400: Presentation exchange xxx in request_sent state (must be presentation_received).

I don't know if it's a normal behaviour. I'm using ACA-Py.

**Comment by ianco** [comment]
Hi @RomainMercier1975 , I'm not sure if you're calling the correct endpoints to send the presentation to the verifier.

There is some documentation here (relating to the demo, but it lists all the relevant api's):  https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AriesOpenAPIDemo.md#requestingpresenting-a-proof

Basically:

- The verifier sends a proof using `POST /present-proof-2.0/send-request`
- The holder/prover can get a list of *available* credentials using `GET /present-proof-2.0/records/{pres_ex_id}/credentials`
- The holder prover then has to create a presentation and send it using `POST /present-proof-2.0/records/{pres_ex_id}/send-presentation`
- When the verifier receives the proof they verify it using `POST /present-proof-2.0/records/{pres_ex_id}/verify-presentation`

At each stage the agent will receive notifications via webhooks.

If you set the appropriate "auto" flags the agent will execute the steps automatically.

(Because your presentation state is still `request_sent`, it means the agent hasn't received a proof from the holder/prover.)

**Comment by RomainMercier1975** [comment]
I will describe what happen when I do like that :

- Issuer issue credentials to Prover 
```
POST {{ISSUER_HOST_URL}}/issue-credential/send
{
  "connection_id": "{{ISSUER_CONNECTION_ID}}",
  "cred_def_id": "{{CRED_DEF_ID}}",
  "credential_proposal": {
    "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/1.0/credential-preview",
    "attributes": [
      {
        "name": "dose",
        "value": "18"
      },
      {
        "name": "lastname",
        "value": "Mercier17"
      },
      {
        "name": "doc_id",
        "value": "1122"
      }
    ]
  }
}
```
(we have "credential_exchange_id": "297ecc1f-f0c9-4218-88c8-843bfc4f765f")

- Prover get the credentials
```
GET {{AGENCY_URL}}/credentials
{
    "results": [
        {
            "referent": "63edae81-e564-4218-b32e-6fb0fed08693",
            "attrs": {
                "lastname": "Mercier17",
                "doc_id": "1122",
                "dose": "18"
            },
            "schema_id": "4kfmXB6jB2jB5Knt7uskb6:2:ROM_DEMO_04:0.1",
            "cred_def_id": "4kfmXB6jB2jB5Knt7uskb6:3:CL:8286:ROMS45",
            "rev_reg_id": null,
            "cred_rev_id": null
        }
    ]
}
```
- Verifier send a proof request
```
POST {{VERIFIER_HOST_URL}}/present-proof/send-request
{
  "connection_id": "{{VERIFIER_CONNECTION_ID}}",
  "proof_request": {
    "name": "ProofVaccination",
    "version": "1.0",
    "requested_attributes": {
      "0_lastname_uuid": {
          "name": "lastname",
          "restrictions": [
              {
                "cred_def_id": "4kfmXB6jB2jB5Knt7uskb6:3:CL:8286:ROMS45"
              }
          ]
      },
      "0_doc_id_uuid": {
          "name": "doc_id",
          "restrictions": [
              {
                  "cred_def_id": "4kfmXB6jB2jB5Knt7uskb6:3:CL:8286:ROMS45"
              }
          ]
      }
    },
    "requested_predicates": {
        "0_dose_GE_uuid": {
        "name": "dose",
        "p_type": ">",
        "p_value": 13,
        "restrictions": [
          {
            "cred_def_id": "4kfmXB6jB2jB5Knt7uskb6:3:CL:8286:ROMS45"
          }
        ]         
       }
    }
  }
}
```
(we have "presentation_exchange_id": "0f1454e4-7b5d-43f5-a1c1-5a6212db32d6")

- At this step when Prover play this request as you purpose :
`{{AGENCY_URL}}/present-proof/records/0f1454e4-7b5d-43f5-a1c1-5a6212db32d6/credentials`
I've this error :
`404: presentation_exchange_v10 record not found: 0f1454e4-7b5d-43f5-a1c1-5a6212db32d6. WalletItemNotFound.`

- So I tried to play ythis request as a Prover :
`GET  {{AGENCY_URL}}/present-proof/records`
And I have :
```
{
    "results": [
        {
            "trace": false,
            "auto_present": true,
            "role": "prover",
            "created_at": "2021-05-21 09:26:13.359955Z",
            "initiator": "external",
            "connection_id": "efe87070-aa9d-4df1-8bfe-31bcadf12582",
            "state": "presentation_sent",
            "updated_at": "2021-05-21 09:26:14.416724Z",
            "presentation_request": {
                "name": "ProofVaccination",
                "version": "1.0",
                "requested_attributes": {
                    "0_lastname_uuid": {
                        "name": "lastname",
                        "restrictions": [
                            {
                                "cred_def_id": "4kfmXB6jB2jB5Knt7uskb6:3:CL:8286:ROMS45"
                            }
                        ]
                    },
                    "0_doc_id_uuid": {
                        "name": "doc_id",
                        "restrictions": [
                            {
                                "cred_def_id": "4kfmXB6jB2jB5Knt7uskb6:3:CL:8286:ROMS45"
                            }
                        ]
                    }
                },
                "requested_predicates": {
                    "0_dose_GE_uuid": {
                        "name": "dose",
                        "p_type": ">",
                        "p_value": 13,
                        "restrictions": [
                            {
                                "cred_def_id": "4kfmXB6jB2jB5Knt7uskb6:3:CL:8286:ROMS45"
                            }
                        ]
                    }
                },
                "nonce": "664642976270086205801657"
            },
            "thread_id": "40a4df5c-afd6-4552-8db9-f469d63ae642",
            "presentation_exchange_id": "9bf3518a-b5f0-4a03-b165-7bd4b39377de",
            "presentation": {
             [...]
                },
                "requested_proof": {
                    "revealed_attrs": {
                        "0_lastname_uuid": {
                            "sub_proof_index": 0,
                            "raw": "Mercier17",
                            "encoded": "84093693795360725518821596369345420528421837193702943113843727237597984246644"
                        },
                        "0_doc_id_uuid": {
                            "sub_proof_index": 0,
                            "raw": "1122",
                            "encoded": "1122"
                        }
                    },
                    "self_attested_attrs": {},
                    "unrevealed_attrs": {},
                    "predicates": {
                        "0_dose_GE_uuid": {
                            "sub_proof_index": 0
                        }
                    }
                },
                "identifiers": [
                    {
                        "schema_id": "4kfmXB6jB2jB5Knt7uskb6:2:ROM_DEMO_04:0.1",
                        "cred_def_id": "4kfmXB6jB2jB5Knt7uskb6:3:CL:8286:ROMS45",
                        "rev_reg_id": null,
                        "timestamp": null
                    }
                ]
            }
        }
    ]
}
```
Now I have a new "presentation_exchange_id" : "9bf3518a-b5f0-4a03-b165-7bd4b39377de"

- Prover can play 
`{{AGENCY_URL}}/present-proof/records/9bf3518a-b5f0-4a03-b165-7bd4b39377de/credentials`
with the result 
```
[
    {
        "cred_info": {
            "referent": "63edae81-e564-4218-b32e-6fb0fed08693",
            "attrs": {
                "lastname": "Mercier17",
                "dose": "18",
                "doc_id": "1122"
            },
            "schema_id": "4kfmXB6jB2jB5Knt7uskb6:2:ROM_DEMO_04:0.1",
            "cred_def_id": "4kfmXB6jB2jB5Knt7uskb6:3:CL:8286:ROMS45",
            "rev_reg_id": null,
            "cred_rev_id": null
        },
        "interval": null,
        "presentation_referents": [
            "0_lastname_uuid",
            "0_doc_id_uuid",
            "0_dose_GE_uuid"
        ]
    }
]
```
- Then Prover send is presentation to Verifier
`POST {{AGENCY_URL}}/present-proof/records/9bf3518a-b5f0-4a03-b165-7bd4b39377de/send-presentation`
Unfortunately I've a bad result
```
{
    "requested_predicates": [
        "Missing data for required field."
    ],
    "self_attested_attributes": [
        "Missing data for required field."
    ],
    "requested_attributes": [
        "Missing data for required field."
    ]
}
```

**Comment by sklump** [comment]
Note that the connection id has to be from the correct side of the relationship: if the prover uses the verifier's, or vice versa, he will get Wallet Item Not Found.

I'm trying to reproduce these results.

**Comment by sklump** [comment]
4: Prover sends proof, note form fill:
![4-prover-sends-proof](https://user-images.githubusercontent.com/9336556/119990060-e5b7ea80-bf95-11eb-94e1-305555d0b923.png)

![5-prover-sent-proof](https://user-images.githubusercontent.com/9336556/119990103-f23c4300-bf95-11eb-8470-9548019bb830.png)

6: Verifier receives and verifies proof:
![6-verifier-received-and-verified-proof](https://user-images.githubusercontent.com/9336556/119990148-fec09b80-bf95-11eb-8876-ed9188c41e34.png)
