### ISSUE TITLE
Minor Bug: Issuer Send Credential comment argument gets overwritten.

### ISSUE THREAD

**Issue by wip-abramson** [hyperledger/aries-cloudagent-python#1167]
Even though the API allows an issuer to define a comment, it never get's received by the Holder if using the send credential function.

I believe it is this line that overwrites it - https://github.com/hyperledger/aries-cloudagent-python/blob/6292b5913605ff3cfe245093b7ce68b705e9b262/aries_cloudagent/protocols/issue_credential/v1_0/manager.py#L113

The comment that I input seems to get set on the CredentialProposal object instead.

**Comment by swcurran** [comment]
@sklump -- I think this one is for you?

**Comment by sklump** [comment]
I'll prioritize it accordingly

**Comment by swcurran** [comment]
Closing with #1171 -- please reopen as needed.
