### ISSUE TITLE
No match between credential proposal Records and credential sent records in an issuer agent 

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#1170]
In an issuer agent, when calling this api: `issue-credential-2.0/records`, i'm able to see JSON records related to record 1 - credential proposal sent from a holder with a "status" field showing "proposal-received" and record 2 - "offer-sent" indicating an new credential is issued and sent to the holder. My question is which field in both JSON records can tell the two records map to each other, if i consider record 2 (issue a credential) is a response to record 1 (request a credential)?

This could causes an issue when an issuer receives many credential proposals from the same holder and has issued more than two credentials for the holder, but the issuer can't tell which credential proposal has been processed.

**Comment by sklump** [comment]
This set up is labouring under a few misunderstandings.

1: An offer is not a credential. An offer is an abstract demonstrating that the issuer controls the credential definition.

2: Each credential exchange record is a record of a distinct credential exchange, by definition. An issuer can counter a proposal in the same exchange with the counter-preview in a bound offer:

![counter](https://user-images.githubusercontent.com/9336556/118120544-0e4cbb80-b3be-11eb-9f1e-e3f6399e5eb6.png)

**Comment by yunxi-zhang** [comment]
@sklump , you are right, I misunderstood it, it's a different api for issuing a credential, but this problem still exists. Let me give a process related to credential request, issuance I want to use in my case. I have an issuer agent and a holder agent.   
**Step 1**: The holder sends a credential proposal to the issuer. In practice, holder calls this api: `issue-credential-2.0/send-proposal`.
**Step 2**: The issuer checks the proposal and agrees with the proposal, then sends an agree message to the holder. In practice, issuer calls this api:` /issue-credential-2.0/send-offer `
**Step 3**: The holder is happy the issuer will issue a credential when receiving this offer message, then holder sends a credential request to the issuer. In practice, holder call this api: `/issue-credential-2.0/records/{cred_ex_id}/send-request `.
**Step 4**: The issuer issues a new credential and sends it to holder. In practice, holder calls this api: `issue-credential-2.0/records/{cred_ex_id}/issue`
**Step 5**. The holder stores this newly issued credential to its wallet. In practice, holder calls this api: /issue-credential-2.0/records/{cred_ex_id}/store

From my experimentations, Steps 2-5, the "state" related to a credential will auto updated for two agents. E.g. for the issuer, from "request-received" to "offer-sent" to "credential-issued", for the holder, from "request-sent" to "offer-received" to "credential-received". However, the record generated at step 1 always shows there as an isolated record. Imagine the issuer will receive many proposals from the holder, how can the issuer tell which proposals have been processed or not?

**Comment by sklump** [comment]
In your step 2, you are sending a free offer. To bind an offer to an existing credential exchange, the issuer should send a bound offer; i.e., `/issue-credential-2.0/records/{cred_ex_id}/send-offer`.
By sending a free offer, the issuer chooses create a new exchange not bound to an existing one. The fact that the preview in the free offer exactly matches an existing one does not change the fact that it is a new exchange.

**Comment by yunxi-zhang** [comment]
Thanks for helping me find this missing puzzle, @sklump, it resolves my query now.
