### ISSUE TITLE
500 Internal server error while receiving an OOB invitation which includes attachments

### ISSUE THREAD

**Issue by DaevMithran** [hyperledger/aries-cloudagent-python#1177]
The **out-of-band/receive-invitation** protocol is throwing an _500 internal server error_, while receiving an OOB invitation including attachments.

Credential Offer attachment

1. Created a credential offer using **POST issue-credential/create** protocol
2. Included the cred_ex_id of the credential offer in **out-of-band/create-invitation**
    ```
    {
          "alias": "Martini",
          "attachments": [
            {
              "id": "3032152c-40ba-4251-8978-373946027faa",
              "type": "credential-offer"
            }
          ],
          "handshake_protocols": [
            "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/didexchange/1.0"
          ],
          "my_label": "Issue credential to Martini",
          "use_public_did": false
      }
  `
3. Copied the invitation json and received the invitation using **out-of-band/receive-invitation** in an another agent (_I reduced the base64 to shorten the json, and removed the service endpoint for privacy in the below json_)
   
 ```
      {
        "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/out-of-band/1.0/invitation",
        "@id": "cc2529ed-02d9-469b-bdd5-6a9f6dc8d3f9",
        "requests~attach": [
          {
            "@id": "request-0",
            "mime-type": "application/json",
            "data": {
              "json": {
                "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/1.0/offer-credential",
                "@id": "250cbca0-0093-4ca8-b3da-5eb84ce92dd1",
                "~thread": {},
                "credential_preview": {
                  "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/1.0/credential-preview",
                  "attributes": [
                    {
                      "name": "Name",
                      "value": "martini"
                    },
                    {
                      "name": "Age",
                      "value": "12"
                    }]},
                "comment": "create automated credential exchange",
                "offers~attach": [
                  {
                    "@id": "libindy-cred-offer-0",
                    "mime-type": "application/json",
                    "data": {
                      "base64": "eyzYifQ=="
                    }}]}}}
        ],
        "handshake_protocols": [
          "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/didexchange/1.0"
        ],
        "label": "Issue credential to Martini",
        "services": [
          {
            "id": "#inline",
            "type": "did-communication",
            "recipientKeys": [
              "did:key:z6MkkPydCiyZzxg6EFb12ivCHcqzZRPo8gjPU9o4ksNe7V4J"
            ],
            "serviceEndpoint": ""
          }]}
```
4. Receiving an  _500 internal server error_
5. The **connection is successfully created** but the **credential offer is not being sent**.

**Comment by swcurran** [comment]
@shaangill025 , can you please take a look at this?

**Comment by swcurran** [comment]
Per comment on Rocketchat -- closing this issue.  @shaangill025 -- nevermind :-)

**Comment by DaevMithran** [comment]
@swcurran @shaangill025 , the **credential-offer** attachment type is not supported yet in out of band protocol. You can look it [here](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/protocols/out_of_band/v1_0/manager.py#L551).
