### ISSUE TITLE
Performance problems with Docker aca-py with thousands of items in the database

### ISSUE THREAD

**Issue by icc-vela** [hyperledger/aries-cloudagent-python#1192]
Hi,

We run aca-py using the docker image aries-cloudagent:py36-1.15-0_0.5.2 (no cpu or memory restrictions on Docker) using the Postgresql connector (no SQLite). We use a separate database for each aca-py. We run thousands of aca-py, most of them are for users, and some of them are the credential issuers. The user aca-py are shutdown after X time to avoid memory exhaustion.

We have reached about 100000 rows in the items table for one of our aca-py that is issuing credentials to other agents. Right now we are not using out-of-band, we create a connection for each agent and the we issue credentials. 

ACA-py started to behave really slow. Most of the tasks were failing. The status command showed us that we had 50 simultaneous tasks running at any given point, and most of them were failing and giving timeous. Operations like /wallet/did/public were taking 1 minute to complete. Establishing a connection was almost impossible, invitation creation was 15 seconds, but when the the other aca-py was accepting the connecting and sending the response via the transport port the connection was never ready. We tried to upgrade to bcgovimages/aries-cloudagent:py36-1.15-1_0.6.0 but the problem persisted.  We verified that the Postgres indexes were correctly created and that in fact, the database performance was good (10-100 millisecond answer for any query). Logging all the queries in Postgres we spotted that for a lot of actions aca-py issues thousands of SELECT statements. Not a single SELECT statement but thousands of them, usually like this one:

SELECT id, value, key FROM items where type = $1 AND name = $2

I see in this issue that people has already tested using hundreds of thousands of credentials: https://github.com/hyperledger/aries-cloudagent-python/issues/947

We have read that the recommended method is to use out-of-band messages without stablishing new connections for everything but  currently that would imply a lot of changes in the project.

I have several questions:

1. Why aca-py issues so many SELECT statements that seem to be tied to the number of the items in the database? It is fixed in any version?
2. We never passed the 50 concurrent tasks. The CPU usage never went up of 20%. There is a hard limit configured in the Docker image? Are the Docker images are production ready?
4. Old connections can be removed using  aca-py, but for what I see DID entries are impossible to delete. There is any way to do cleanups without removing by hand entries in the database?

 Regards.

**Comment by swcurran** [comment]
Thanks for the details -- good to hear this.  I'm not sure if you can share the test case you are using, but it might allow us to help with the analysis.

@andrewwhitehead has the most information on this and should be the one to reply.

I know that the selects are from the indy-wallet code, and has to do with the very simple data model being used -- basically, just two tables of name/value pairs -- items and tags.

Our team (mostly @andrewwhitehead) has also been working on a non-indy sdk version of the secure storage and indy interactions.  That work is close to being available, and it might be easy enough to try your test case with that, and see the impacts.

**Comment by icc-vela** [comment]
Hi Stephen,

The data is production data so I cannot share full details but I can replicate any command/test you need and provide the results in the form of numbers of SQL statements, etc. That is not a problem.

I have ran one of the examples that were causing more problems, connection creation and I have enabled postgres query log
[postgresql-2021-05-24_080439.log](https://github.com/hyperledger/aries-cloudagent-python/files/6530299/postgresql-2021-05-24_080439.log)
. 

In this example we create a connection invitation with the path /connections/create-invitation, then we accept the invitation in the destination agent with /connections/receive-invitation and finally we do periodic /connections/{connection_id}/send-ping from the origin agent until the connection is ready. In the log I am attaching, origin_agent is the agent that has the performance problem (more than 100000 items) and the destination_agent is a normal user_agent. You can see the high number of selects we have for  single operation (39524 SELECT statements for a single connection).

**Comment by andrewwhitehead** [comment]
So I think a large part of the performance issue here is probably coming from the DIDs associated with these connections, and the current overhead of `get_public_did` (which is used in many places in the system). There's more discussion on [this issue](https://github.com/hyperledger/aries-cloudagent-python/issues/753) but it hasn't been resolved yet. I should be able to look at improving that this week.

Even so, I have trouble understanding how quite so many SELECTs are being performed, so there might be additional overhead somewhere due to the handling of the connection records. It's not easy to debug this at the database level due to all the records being encrypted, so tracing would likely need to be added elsewhere to determine where the queries are originating.

Using Askar for storage will likely be faster in this case due to the speed of the record scans in postgres, but fast enough if it's still doing 30K queries. :)

**Comment by icc-vela** [comment]
Hi Andrew,

Thanks for the feedback. Reading the issue you shared, either fetching all records and scan them in memory or having a single record for the public did should do it. I would like to add that maybe it is not only a performance because of the DIDs, but also because of the number of connections, although in my tests I deleted all the connections by hand in the database and it was still really slow.

About the number of selects, that might be because in this example after the connection creation we issue each 5 seconds a  /connections/{connection_id}/send-ping which might be increasing the number of selects a lot if each of them.

**Comment by ducadellaforcoletta** [comment]
Hi icc-vela, another point of performance improvement found during the investigation of the issue linked by Andrew was at https://github.com/hyperledger/aries-cloudagent-python/blob/278c8ce0e85b403f8dd4cd83fb0bdc81f7e5dd54/aries_cloudagent/protocols/connections/v1_0/manager.py#L781

In that point, in our case, there was a useless search starting from a signkey generated instead of a verkey. A pre check in order to verify if it was a signkey in order to avoid the useless read has increased the performance of our process.

**Comment by swcurran** [comment]
FYI -- some fixes were done ACA-Py to address this issue.  Are you able to run this scenario again to see if the issue has been addressed? PR was #1249 

@icc-vela

**Comment by icc-vela** [comment]
Hi Stephen

Can I use some pre-existing Docker image that already ahs the fix or do I need to build my own using the main branch where the fix was merged?

Regards.

**Comment by swcurran** [comment]
I think we have built some images, but not certain where -- @esune @ianco ?  Last one on bcgovimages is from 18 days ago, I think.

**Comment by ianco** [comment]
We should have the `0.7.0-RC1` out soon.  I haven't published any images, just built and tested locally.

**Comment by esune** [comment]
> 
> 
> I think we have built some images, but not certain where -- @esune @ianco ? Last one on bcgovimages is from 18 days ago, I think.

The `pre` images I have been pushing to Docker Hub do not have that fix, once we are good to create an RC1 I can build it and push it

**Comment by swcurran** [comment]
FYI -- RC0 is out, so please go ahead with the images.  Let's get people pushing on this new release!

**Comment by esune** [comment]
The new image is now in Docker Hub: `bcgovimages/aries-cloudagent:py36-1.16-1_0.7.0rc0`

**Comment by icc-vela** [comment]
Dear @swcurran @esune 

Apologies for the lateness, I have been on holidays. I have tested the new image (not the RC but the final version as I saw it was already out) with the current database and the common tasks have dramatically improved:

bcgovimages/aries-cloudagent:py36-1.15-0_0.5.2
```
Initialization of agent:
90 seconds

Public DID (/wallet/did/public )
90 seconds

Accept invitation + ping (/connections/{connection_id}/send-ping"):
70 seconds
```

bcgovimages/aries-cloudagent:py36-1.16-1_0.7.0
```
Initialization of agent:
1 second

Public DID (/wallet/did/public )
less than 1 second

Accept invitation + ping (/connections/{connection_id}/send-ping"):
5 seconds
```

I am closing the issue as with this new image the problems I was having are gone.

Regards.

**Comment by swcurran** [comment]
Excellent!  Thanks for the follow up.

Well done, @andrewwhitehead !!
