### ISSUE TITLE
Remove invalid/corrupted tails files

### ISSUE THREAD

**Issue by c2bo** [hyperledger/aries-cloudagent-python#1196]
When acapy attempts to download a tails file (e.g. for revoking/issuing a credential), it will attempt to download the file from the public URI. If this process fails, (e.g. the tails server is temporarily unavailable and answers with an error code), then acapy will download the file, check for a valid hash (this check fails) and does not remove the tails file if an invalid hash value is detected.

The next time the tails file is required, acapy will use the invalid file in the filesystem (resulting in errors in indy-sdk/ursa) instead of attempting a redownload.

**Comment by sklump** [comment]
I can take a look early next week

**Comment by c2bo** [comment]
I did some manual tests and think I figured out where the problem is coming from (verified with a bit of manual testing). The biggest question for me would be the desired behavior, especially regarding allowed status codes of the tails server response (should only 200 be allowed or should we check at all - we are checking for hash validity anyway?).
