### ISSUE TITLE
Attributes with real values are not shown when verifier fetches present proof records

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#1201]
When my verifier agent sends a presentation request, I put below information asking for an attribute named "issuedTo" with a value "MyCompany".
![image](https://user-images.githubusercontent.com/16185797/119329007-a7ac8500-bc7c-11eb-88ce-ba681c268a81.png)

When the holder sends a credential claim and the verifier tries to get the claim records by calling the api:`/present-proof/records,` the value of "issuedTo" is not a plaintext value. 
![image](https://user-images.githubusercontent.com/16185797/119329228-e8a49980-bc7c-11eb-951e-030d0807b936.png)

![image](https://user-images.githubusercontent.com/16185797/119329260-f0643e00-bc7c-11eb-8e04-aaaca5de88af.png)

I wonder how the verifier can see the real value of this attribute in a claim? Is this the right api to find the plaintext of the submitted claim for the verifier?

**Comment by ianco** [comment]
Plaintext values should be available in the `"requested_proof"` block of the proof exchange object, for example see the `"raw"` values in the example below:

```
"requested_proof": {
  "revealed_attrs": {
    "0_degree_uuid": {
      "sub_proof_index": 0,
      "raw": "Maths",
      "encoded": "460273229220408542178729328948548235132905393400001582342944147813984660772"
    },
    "0_date_uuid": {
      "sub_proof_index": 0,
      "raw": "2018-05-28",
      "encoded": "23402637423876324098256519317695433196813217785795317220680415812348801086586"
    },
    "0_name_uuid": {
      "sub_proof_index": 0,
      "raw": "Alice Smith",
      "encoded": "62816810226936654797779705000772968058283780124309077049681734835796332704413"
    }
  },
  "self_attested_attrs": {},
  "unrevealed_attrs": {},
  "predicates": {
    "0_age_GE_uuid": {
      "sub_proof_index": 0
    }
  }
}
```

**Comment by domwoe** [comment]
If there is no plaintext (I haven't checked myself) I would argue it's by design. 

You know the value anyways because you ask the prover to prove `issuedTo == myCompany`. So  if the proof is valid you know that `issuedTo == myCompany` and if it is invalid you should not be able to infer the value of issuedTo, because this would be more information than you have asked for.

**Comment by sklump** [comment]
Ultimately this is indy. Do experiment with the indy-sdk wrapper tests and capture the output of various operations. Navigating these data structures without indy knowledge is navigating by bat sonar.

**Comment by yunxi-zhang** [comment]
thanks @ianco, i've found the right value in my tests.
