### ISSUE TITLE
connection error when using public did invitation

### ISSUE THREAD

**Issue by baegjae** [hyperledger/aries-cloudagent-python#1203]
We used public did invitation well.
But, recent changes occur connection error.

```
  File "/Users/baegjae/src/aries-cloudagent-python/aries_cloudagent/protocols/connections/v1_0/manager.py", line 1103, in get_connection_targets
    targets = await self.fetch_connection_targets(connection)
  File "/Users/baegjae/src/aries-cloudagent-python/aries_cloudagent/connections/base_manager.py", line 340, in fetch_connection_targets
    label=invitation.label if invitation else None,
UnboundLocalError: local variable 'endpoint' referenced before assignment
```
Above is part of the error log.

I debugged and I found that below line makes error when using public did invitation.
https://github.com/hyperledger/aries-cloudagent-python/blob/3751b61d6774185bec42315ddb084ec44c219fd3/aries_cloudagent/connections/base_manager.py#L290

In here, `connection.invitation_msg_id` and `connection.invitation_key` were `None` when using public did invitation.
Therefore, `if invitation.did:` code not worked.

Thanks!

**Comment by swcurran** [comment]
I think this one is for you @shaangill025

**Comment by baegjae** [comment]
It works well now. Thanks!
