### ISSUE TITLE
[Postgres] Placeholder, ensure updated Indy postgres plugin is supported

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#1214]
There have been some issues reported deploying aca-py to AWS and Azure due to limitations of the postgres plug-in.

Some items have been summarized here:  https://github.com/hyperledger/indy-sdk/issues/2396

This ticket is to ensure that aca-py supports/works with any required updates.

**Comment by swcurran** [comment]
Closing this issue.
