### ISSUE TITLE
ACA-Python version 1.16_0.6.0 Revocation registry error

### ISSUE THREAD

**Issue by Rounak210** [hyperledger/aries-cloudagent-python#1219]
![image](https://user-images.githubusercontent.com/85231262/120474247-97f01780-c3c5-11eb-9865-89ebb1b75cda.png)
Is there any way I can solve this error?. I have already set up VON tails server.

**Comment by domwoe** [comment]
The error seems not be related to the VON trails server, but the server you registered to receive webhooks, i.e. `http://dev-proof-.`. Is this server availabl?

**Comment by Rounak210** [comment]
@domwoe , the server is available at dev.thrift.identity.ky

**Comment by domwoe** [comment]
Then you have to set ACA-Py's webhook target (`--webhook-url` start parameter) to this url.

**Comment by Rounak210** [comment]
![Screenshot from 2021-06-02 20-31-45](https://user-images.githubusercontent.com/85231262/120504406-bbc15680-c3e1-11eb-8aa6-b9cc46242e35.png)
 @domwoe , I have already added --webhook-url while starting aca py

**Comment by Rounak210** [comment]
@domwoe , @esune  , can you please help, on to this issue. 
![image](https://user-images.githubusercontent.com/85231262/120665988-dc54e380-c4a9-11eb-85a0-31b5d6921f93.png)

getting this error, while running aca-py version 0.6.0

**Comment by esune** [comment]
> 
> 
> @domwoe , @esune , can you please help, on to this issue.
> ![image](https://user-images.githubusercontent.com/85231262/120665988-dc54e380-c4a9-11eb-85a0-31b5d6921f93.png)
> 
> getting this error, while running aca-py version 0.6.0

Is this a new schema/creddef or an old/existing one? I had this issue in the past when trying to start an agent with a known creddef while the tails server URL had changed (e.g.: created creddef to pint to `tails-old.mydomain.com` and now the tails server url is `tails-new.mydomain.com`).

**Comment by Rounak210** [comment]
It is the old one before setting up tails server. Okay, I am creating a new schema and credential_def_id, and will update if it resolves the issue. Thanks for the suggestion

**Comment by Rounak210** [comment]
@esune, thanks, after updating the credential_def_id, the issue is resolved, and now credentials could be issued, also can you guide me on why I am getting this error.?
![image](https://user-images.githubusercontent.com/85231262/120685373-622e5a00-c4bd-11eb-9780-44739ad17da2.png)

**Comment by esune** [comment]
Posting to the webhooks endpoint failed, check the controller logs and there will likely be an http 500 error there telling you why that happened.

**Comment by Rounak210** [comment]
![image](https://user-images.githubusercontent.com/85231262/120794034-4b3b4680-c555-11eb-8919-ce0ce377b73c.png)
@esune, I got this error while checking the logs. Do you have any suggestions?

**Comment by esune** [comment]
Something is mismatched in your configs - I think. I have not seen this issue before though.

I would recommend you start over with a clean state so that you will not be dragging along old configurations/settings.

**Comment by Rounak210** [comment]
@esune, Actually, We already have a genesis file using ACA-PY version 0.4.3, and details of all the nodes are present and all our existing service is using it. However, I wanted to test the revocation registry for one service, that should use ACA-PY version 0.6.0. We only have one genesis file. Is there any way, I can test the new configuration with a separate genesis file?.

**Comment by esune** [comment]
If you are starting a new agent to test things, make sure you start from scratch and do not have a previously saved wallet for that agent. I am unsure what else to recommend as this seems to be related to your specific configuration.

You also mention aca-py `0.4.3`: any reason not to upgrade your agents to a later, more up-to-date version? That release is over 1 year old now...

**Comment by Rounak210** [comment]
@esune We are updating the current ACA-Py version from 0.4.3 to 0.6.0, as prior to this we did not need the requirement to implement a revocation registry. Before I make changes on other services, I need to make sure that it works on a development server.

Also, as you said, I had started building the server and implementing ACA-PY 0.6.0 from scratch, however, I am currently getting 

![image](https://user-images.githubusercontent.com/85231262/121194920-c91c8c00-c88c-11eb-8626-0ad94e0811fb.png)
. Do you have any suggestions for this error?. Thanks!!

**Comment by esune** [comment]
Can you check the tails file hosted on the tails server and the one that was downloaded by the agent match.
It looks like they may not be the same file, as the error states. Not sure why that would be though.

**Comment by esune** [comment]
Closing as there has not been activity, please reopen if necessary.
