### ISSUE TITLE
Feature: Add aca-py command line option --genesis-file  

### ISSUE THREAD

**Issue by SmithSamuelM** [hyperledger/aries-cloudagent-python#122]
The current aca-py has two methods for injecting the genesis transactions. 
1) --genesis-transactions
2) --genesis-url

The first is not a great user experience. The genesis transactions are a newline separated list of JSON data structures; not event a JSON list. This requires escaping to get the transactions to correctly input from a command line shell.  A minimal four node set of genesis transactions are still almost 3K Characters.So this is not a reasonable option.

The second option genesis url requires some web server that provides the genesis transactions. This is a reasonable approach from a user experience but does have a hard dependency on a web server.

A practical alternative that has both decent user experience and no external dependencies is to allow a local file path input to provide the genesis transactions.

**Comment by swcurran** [comment]
Agree that is a reasonable approach - I thought that was an option.

Can this be used as a temporary workaround?  `--genesis-transactions "$(cat <genesis-file>)"`

**Comment by SmithSamuelM** [comment]
I can't find it as an option anywhere so it would be good to add. Thanks. Also good suggestion for workaround.

**Comment by andrewwhitehead** [comment]
Resolved via PR #127
