### ISSUE TITLE
Bug: ACAPY_MEDIATION_OPEN env var not working as expected

### ISSUE THREAD

**Issue by wip-abramson** [hyperledger/aries-cloudagent-python#1221]
I have moved to passing all agent configuration in through an .env file. However, when trying to set mediation using this argument, which does seem to be correct from the [argparse file](https://github.com/hyperledger/aries-cloudagent-python/blob/1c7bc86b91cd10d472ad15cb52c09b9424e8175c/aries_cloudagent/config/argparse.py#L1116) in acapy mediation requests are not being automatically granted.

I have changed to use the --open-mediation flag in a startup script instead. 

I had a little dig into the ACA-Py code but couldn't spot anything obvious. 

It is possible this is an issue on my end still, but I am setting all other args on agent the same way so seems unlikely.

**Comment by dbluhm** [comment]
I believe there was a bug where the env_var `ACAPY_MEDIATION_OPEN` was erroneously used in more than one argument. This has since been fixed.
