### ISSUE TITLE
Sending image as part of credential

### ISSUE THREAD

**Issue by juvebogdan** [hyperledger/aries-cloudagent-python#1222]
Hello,

I am trying to issue a credential that has image/jpeg as a field. I am using also mobile agent and mediator. but whenever i try to issue offer i get this error:

aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://192.168.65.3:8022/webhooks/topic/issue_credential/; Error: (<class 'aries_cloudagent.transport.outbound.base.OutboundTransportError'>, OutboundTranspo
rtError('Unexpected response status 413, caused by: Request Entity Too Large',), <traceback object at 0x7f907d3e05c8>); Re-queue failed message ...

My image is 460Kb

Is it possible to change this?

I tried to change default value of --max-message-size in argparse.py but that did nothing

**Comment by ducadellaforcoletta** [comment]
Hi, 
i found the same problem in the past at the following code line,
 https://github.com/hyperledger/aries-cloudagent-python/blob/653a4c2c4d19e1e3a0b6b89467affcea81827434/aries_cloudagent/admin/server.py#L288

The default client size is used, it can be customized passing the size as here app = web.Application(middlewares=middlewares, client_max_size=2048**2)

@andrewwhitehead  Maybe an args params could be usefull for the scope?

**Comment by juvebogdan** [comment]
Hi,

I dont see that line in that file. Is that the latest code?

**Comment by ducadellaforcoletta** [comment]
Sorry, I sent an old link. Looking at the actual code it looks like it is already managed with the "admin.admin_client_max_request_size" parameter. Default 1 mb. It can be customized using this parameter.

**Comment by juvebogdan** [comment]
I saw that but whatever i put there i get the same error. There is no way i am sending more then 20MB

**Comment by juvebogdan** [comment]
Maybe its because i am running faber demo? How can i add that option in that demo?

**Comment by swcurran** [comment]
Closing this issue because it is old, but am open to having it re-opened, especially if you could provide a more complete example of the problem -- the steps you used to create the problem using the Alice/Faber demo.  We'd just need what you did differently from the doc, and an example image you are using.
