### ISSUE TITLE
did:web resolver: DIDWeb.PATTERN too permissive

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#1228]
The regular expression used for `DIDWeb.PATTERN` is currently too permissive causing other DIDs (such as `did:github:dbluhm`) to be pushed to the `did:web` resolver for handling.

The current value used is: `^(did:web:)?([a-zA-Z0-9%._-]*:)*[a-zA-Z0-9%._-]+$`

I'm not sure how this is used elsewhere but at least for resolver selection, I think the `?` on `(did:web:)` is the part causing us trouble. If the `did:web` part is intended to be optional for other uses, we might need to use a different regex for resolver selection. The resolver selection regex is really used only to sort out whether it should handle a given DID and does not need to be exhaustive. Further validation can be performed by the resolver itself after selection. `^did:web:.*$` would likely be sufficient.

@domwoe

**Comment by dbluhm** [comment]
@Luis-GA same problem we were seeing for the Uniresolver plugin

**Comment by domwoe** [comment]
ah, sorry! Will fix this later today.
