### ISSUE TITLE
[Endorser Protocol] Add auto flags and default endorsement settings

### ISSUE THREAD

**Issue by esune** [hyperledger/aries-cloudagent-python#1238]
When running an instance of ACA-Py with `AUTHOR` only privileges (no permission to write to the ledger), the agent needs to explicitly request endorsement to an authorized agent when performing any action that requires writing a new transaction to the ledger. Some of these transactions are:
- creating a schema
- creating a credential definition
- creating a revocation registry
- publishing a revocation registry entry

To facilitate the endorsement pattern, it would be nice to have new global settings and `auto` flags that will:
- allow the `endorser` to automatically endorse all received endorsement requests endorsement
- allow the `author` to automatically submit endorsement requests for all relevant objects
- allow both agents to automatically setup the required metadata on the connection records

As part of implementing the above functionality, it may be required to add:
- an `--agent-role` setting/startup parameter to determine what the agent capabilities are when interacting with the ledger, and what role is held when completing a transaction
- an `--auto-endorse-transactions` setting/startup parameter to tell the endorser to automatically process incoming endorsement requests
- a setting to identify which connection corresponds to the endorser agent on the `author` (maybe by label or public did?)

c.c.: @ianco

**Comment by esune** [comment]
A couple of other thoughts about the above changes:
- the scope of refactoring will likely bleed into `revocation`, as it is another fairly complicated set tasks to orchestrate
- ideally, both endorsement and revocation are "transparent" to the user: this means that there should be no need to keep track of the sequence of steps required to endorse a transaction, or to keep a revocation registry active. Everything should be taken care of by aca-py, transparently to the user.
- some of the endorsemement/revocation endpoints might need to be turned to "read only mode" when appropriate (i.e.: auto flags set) in order to prevent erroneous calls to interfere with the state of the objects in aca-py (mostly thinking about revocation registries here)

**Comment by esune** [comment]
High level design document with proposed changes/approach can be found [here](https://hackmd.io/@esune/Hk1wCXz3d).

**Comment by swcurran** [comment]
Reviewed and added one comment.  Looks great to me!  Let's go for it.

**Comment by esune** [comment]
Perfect, I'll setup a meeting with @ianco next week to plan the work then!

**Comment by ianco** [comment]
Updated the high-level design to include a section describing how the event bus will be used:

https://hackmd.io/51flx8CVS1ypyOjEqVl1tg?view#Implementation-Details

**Comment by swcurran** [comment]
Closing this as I think the feature is done. If not, please add new issues left to be completed.
