### ISSUE TITLE
[Proposal/Question] Verify correctness of own Verifiable Credentials, using the Signature and Raw Data

### ISSUE THREAD

**Issue by futureman2007** [hyperledger/aries-cloudagent-python#1239]
As of this closed Issue: https://github.com/hyperledger/aries-cloudagent-python/issues/1217
A Credential Holder verifies a new VC, if the signature matches the Raw Data before storing it in the wallet.
But then a verifier is needed to check if the VC (matching Raw data with the Signature) was not altered.

What is the proposal?
A new Feature for e.g. the Wallet endpoint to check all or a single credential, if there are still not revoked and that the raw Data was not altered (Matchin Signature with Raw Data)

What are the Use-Cases?
A Device can check by itslef, if its Wallet VC data was altered after reboot/recovery/owner transfer/... 
It refuses any operations based on a VC, when
a) it was altered
b) it was revoked
(opt) c) it can not verify its credential(s) (no connection to the ledger) if the VCs are still valid (not revoked, not altered).

What do you think about It?
Is there something in Plan?

**Comment by swcurran** [comment]
A reasonable request, but unlikely to be needed in the near future. As noted in #1217 -- the verification is done before storage.

Closing, but happy for others to reopen if they want to move this forward.
