### ISSUE TITLE
DIF PE handler should not determine whether "schema.uri" is type or context based on "#"

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1240]
As I already mentioned in https://github.com/hyperledger/aries-cloudagent-python/pull/1125#discussion_r630778201 it is wrong to assume the `schema.uri` in PE is an `@type` if it contains a `#`.

Take a look at this playground: https://tinyurl.com/ye9whcca 

the expanded types result in:
```json
    "@type": [
  	  "https://www.w3.org/2018/credentials#VerifiableCredential",
      "http://schema.org/Person"
    ]
```

https://github.com/hyperledger/aries-cloudagent-python/blob/319a2ff30d9ddd4a9fdb4b3ab69d1946c110c21b/aries_cloudagent/protocols/present_proof/v2_0/formats/dif/handler.py#L201-L204

@shaangill025

**Comment by TimoGlastra** [comment]
I thought maybe we can use some of the advanced WQL syntax to include an OR statement:

https://hyperledger-indy.readthedocs.io/projects/sdk/en/latest/docs/design/011-wallet-query-language/README.html

According to the docs something like this should be possible:

```
{
 $or: [
	  {
	     "type:https://example.com#Something": "1"
	  }, 
	  {
	  	"schm://example.com#Something": "1"
	  }
 ]
}

@andrewwhitehead does Askar provide the same WQL as indy?

**Comment by shaangill025** [comment]
Ok, `search_credentials` in `storage.vc_holder.in_memory` has a `tag_query` parameter [tag filter cluase], I am not sure if this can be used for passing WQL query dict.

**Comment by andrewwhitehead** [comment]
Yes, Askar supports the same WQL as well as `"$exist": ["key1", "key2"]`
