### ISSUE TITLE
 RuntimeError: cannot reuse already awaited coroutine

### ISSUE THREAD

**Issue by et-taousy** [hyperledger/aries-cloudagent-python#1241]
When i run ./run_demo faber the container shutdown with the error below:

`Shutting down agent ...

Faber      | 

Faber      | Shutting down

Faber      | 2021-06-14 14:33:23,208 aries_cloudagent.commands.start ERROR Exception during startup:

Faber      | Traceback (most recent call last):

Faber      |   File "/home/indy/aries_cloudagent/commands/start.py", line 72, in init

Faber      |     await startup

Faber      |   File "/home/indy/aries_cloudagent/commands/start.py", line 28, in start_app

Faber      |     await conductor.setup()

Faber      |   File "/home/indy/aries_cloudagent/core/conductor.py", line 101, in setup

Faber      |     self.root_profile, self.setup_public_did and self.setup_public_did.did

Faber      |   File "/home/indy/aries_cloudagent/config/ledger.py", line 71, in ledger_config

Faber      |     async with ledger:

Faber      |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 272, in __aenter__

Faber      |     await self.pool.context_open()

Faber      |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 205, in context_open

Faber      |     await self.open()

Faber      |   File "/home/indy/aries_cloudagent/ledger/indy.py", line 170, in open

Faber      |     self.handle = await indy.pool.open_pool_ledger(self.name, "{}")

Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger

Faber      |     open_pool_ledger.cb)

Faber      | concurrent.futures._base.CancelledError

Faber      | 2021-06-14 14:33:23,213 asyncio ERROR Task exception was never retrieved

Faber      | future: <Task finished coro=<run_loop.<locals>.done() done, defined at /home/indy/aries_cloudagent/commands/start.py:77> exception=RuntimeError('cannot reuse already awaited coroutine',)>

Faber      | RuntimeError: cannot reuse already awaited coroutine

Faber      | Exited with return code 0

`

**Comment by ianco** [comment]
It looks like an error connecting to the ledger, are you running von-network locally?

Can you share more info about your setup?

**Comment by et-taousy** [comment]
Its not a connection error, i got that when i wasn't running an Indy-node locally( [Connect call failed ('10.0.2.15', 9000)]).
i didn't get that now i don't what happened.
