### ISSUE TITLE
DIF PE handler throws error when the only "schema.uri" is VC

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1242]
Is there a specific reason the DIF PE handler throws an error if the `schema.uri` only contains `https://www.w3.org/2018/credentials#VerifiableCredential`? 

Currently getting the following error in AATH:

```
aries_cloudagent.protocols.present_proof.v2_0.formats.handler.V20PresFormatHandlerError: Only expanded type extracted from CREDENTIALS_CONTEXT_V1_URL and VERIFIABLE_CREDENTIAL_TYPE included as the schema.uri
```

I think we should promote more explicit PE definitions, but it don't see the need to restrict it.

@shaangill025

**Comment by shaangill025** [comment]
My reasoning behind this is that if the proof_request's `presentation_definition` constraint checks if `$.credentialSubject.givenName`  is 'JOHN' and on the holder side, there are 2 credentials both having `credentialSubject.givenName` as `JOHN` but one is `PermanentResidentCard` and other could be `DriverLicense`.  Then if only `https://www.w3.org/2018/credentials#VerifiableCredential` is included as the `schema.uri` then both these credentials will be included in the presentation. I thought this will encourage the construction of a more structured `presentation_defintition`.

There is also another mechanism for the holder to restrict credentials by `record_id`. Do you suggest taking this restriction out.

**Comment by TimoGlastra** [comment]
In this case the verifier should either be more explicit or both values are correct.

---

>  then both these credentials will be included in the presentation  

Shouldn't we only disclose one of the two? Disclosing both seems like disclosing more information than necessary. IMO this shouldn't be the default behaviour

---

> Do you suggest taking this restriction out.


yes

**Comment by shaangill025** [comment]
> Shouldn't we only disclose one of the two? Disclosing both seem like disclosing more information than necessary. IMO this shouldn't be the default behavior

The holder can now restrict the credentials manually when sending the presentation. With --auto settings, I think it is difficult to restrict the applicable credentials [like by selecting the 1st one in the list] because maybe the `presentation_definition` was constructed in a way to get multiple credentials.

**Comment by TimoGlastra** [comment]
Ah makes sense. How are you generating the presentation submission? I think that contains enough information to determine whether the credential is used

**Comment by shaangill025** [comment]
> Ah makes sense. How are you generating the presentation submission? I think that contains enough information to determine whether the credential is used
 @TimoGlastra I have made the changes [#1247] to fix the recent DIF PE issues you opened. Yes, looking at the `presentation_submission` in `VP`, we can determine which credential [from the index] in the `verifiableCredential` list was applicable to which input_descriptor id.

This function generates the `descriptor_map` for `presentation_submission`:
https://github.com/hyperledger/aries-cloudagent-python/blob/b9d6893b270f7319a54a146107a235483ef8189d/aries_cloudagent/protocols/present_proof/dif/pres_exch_handler.py#L1196
