### ISSUE TITLE
DIF PE Presentation Submission and optional id property in W3C credentials

### ISSUE THREAD

**Issue by shaangill025** [hyperledger/aries-cloudagent-python#1253]
[W3C data model specification](https://www.w3.org/TR/vc-data-model/#identifiers)
`id` property is optional, this is stored as `given_id` in `VCRecord`.
DIF PE handler uses this `given_id` in generating the `descriptor_map` for `presentation_submission`. `given_id` is also used to check if the number of applicable credentials meets the requirement specification [`submission_requirement`]
- If `id` is not included, there will be issues in DIF PE handler as currently implemented. I think as a fix, the `given_id` of the credential could either be set to a generated `UUID4` or to the `record_id`. @TimoGlastra Any feedback?
- If `id` is included, then according to spec, `the value of the id property MUST be a single URI. It is RECOMMENDED that the URI in the id be one which, if dereferenced, results in a document containing machine-readable information about the id`. As it will be unique for each credential so there shouldn't be any issues.

**Comment by shaangill025** [comment]
- Similar situation when the `presentation_definition` has `limit_disclosure` set to `true`. 
If the `VP` includes multiple derived credentials with original credentials not having an `id`
- This can also be fixed by setting the `given_id` of derived credential to a `uuid4` for building the `presentation_submission` correctly.

This added `given_id` is just for internal processing in DIF PE Handler and we will not modify the `cred_value` dict which is added to `VP`. I think the best place to set `given_id` is within `../present_proof/dif/pres_exch_handler`:

1. First, we identify if a credential is applicable
2. Check if `given_id` is None
3. Set `given_id` to `uuid4()`
4. Proceed with building `VP`

**Comment by TimoGlastra** [comment]
I'd be cautious of setting the given_id in the pres exch handler as from then on you don't know whether the given_id is from the original cred or applied at a later stage. This can make additional processing in the future more complex.

However, I do think generating a uuid seems like a good approach. I wouldn't use the record_id for it, as that is more an internal id.

How are you handling this at the moment?

**Comment by shaangill025** [comment]
> How are you handling this at the moment?

Currently, I am only using the `given_id` of `VCRecord` as an unique identifier for credentials when adding then into `dict[input_descriptor_id][credential_given_id]`, it causes an issue [below] if it is `None` and multiple credentials have to be enclosed in `VP`. In the example below, I expect 2 credentials to be enclosed here and  `$.verifiableCredential[0]` and `$.verifiableCredential[1]` in `descriptor_map`
```
"presentation_submission": {
          "id": "83faa708-fb78-4d2f-b0d9-a890e14a1f21",
          "definition_id": "32f54163-7166-48f1-93d8-ff217bdb0654",
          "descriptor_map": [
            {
              "id": "pr_input_1",
              "format": "ldp_vp",
              "path": "$.verifiableCredential[0]"
            },
            {
              "id": "pr_input_1",
              "format": "ldp_vp",
              "path": "$.verifiableCredential[0]"
            }
          ]
        }
```


> I'd be cautious of setting the given_id in the pres exch handler as from then on you don't know whether the given_id is from the original cred or applied at a later stage. This can make additional processing in the future more complex.
> 
> However, I do think generating a uuid seems like a good approach. I wouldn't use the record_id for it, as that is more an internal id.

Sounds good, I will not modify VCRecord of original credentials, I can use `record_id` as the unique identifier in this case. For `derived_credential`, as I am converting them from `dict` to `VCRecord` within `pres_exch_handler` anyway, I think it is okay to specify/update their `given_id` with `str(uuid4())`. Based upon my testing, if the original credential had no `given_id` then derived credential has `urn:bnid:_:c14n0` as the `given_id`.
