### ISSUE TITLE
Revocation : true / Credential Definition

### ISSUE THREAD

**Issue by wildnano** [hyperledger/aries-cloudagent-python#1254]
- Firstable **when creating a credential definition** with **support_revocation: true** I get error 400

```
{
    "support_revocation": true,
    "tag": "default-030",
    "schema_id": "{{SCHEMA_ID}}"
}
```
**400: tails_server_base_url not configured**

When I send again the request, it works I get the credential_definition_id.
Is it normal to send credential definition twice in order to get the ID ? I don't think so ...

- Then,  when the **issuer sends credential** to the **wallet** and I check **all credentials** for the wallet I get an empty array

```
{
    "results": []
}
```
At this step when I go to **/revocation/registries/created**
I can see in the register multiple lines referring to the credential definition
```
{
    "rev_reg_ids": [
        "4kfmXB6jB2jB5Knt7uskb6:4:4kfmXB6jB2jB5Knt7uskb6:3:CL:8580:default-006:CL_ACCUM:35b22a3e-f7da-4d91-8532-a1688e03ac8d",
        "4kfmXB6jB2jB5Knt7uskb6:4:4kfmXB6jB2jB5Knt7uskb6:3:CL:8580:default-031:CL_ACCUM:65c5fa9d-1375-43a3-853f-b22dd31e4a62",
        "4kfmXB6jB2jB5Knt7uskb6:4:4kfmXB6jB2jB5Knt7uskb6:3:CL:8580:default-021:CL_ACCUM:e28afa30-d7c5-4d82-9048-b6413dc6690c",
        "4kfmXB6jB2jB5Knt7uskb6:4:4kfmXB6jB2jB5Knt7uskb6:3:CL:8580:default-031:CL_ACCUM:27e35013-bde4-48b9-9548-451195443796",
        "4kfmXB6jB2jB5Knt7uskb6:4:4kfmXB6jB2jB5Knt7uskb6:3:CL:8580:default-031:CL_ACCUM:718ba5e7-4655-4b6b-8600-6198a1be106e",
        "4kfmXB6jB2jB5Knt7uskb6:4:4kfmXB6jB2jB5Knt7uskb6:3:CL:8580:default-027:CL_ACCUM:38242345-490c-493d-82de-ad5c8243e1ae"
    ]
}
```
When revocation is false I don't get any problem with playing the scenario.

Could someone explain me what happens exactly in the process when revocation is true and what to do to in order to verify proof in this case.

Thanks.

**Comment by esune** [comment]
`400: tails_server_base_url not configured` means that you have not set the startup argument `--tails-server-base-url` indicating where to upload the tails file. The tails file needs to be pushed to a publicly accessible location in order for verifiers to be able to check the revocation state for a credential.

To generate a proof-request you need to add either a global (for the whole proof) or local (for a specific requested attribute/perdicate) `non_revoked` clause: see a walk through [here](https://github.com/hyperledger/aries-cloudagent-python/blob/main/docs/GettingStartedAriesDev/CredentialRevocation.md).
