### ISSUE TITLE
Integration with Register & Resolver Drivers

### ISSUE THREAD

**Issue by andre-d-gomes** [hyperledger/aries-cloudagent-python#1255]
Hi,

I've been performing tests with this component, as well as the did-sov-drivers for DID registering & resolvance. When using the same Von-Network for both services (sharing the same seed & wallet_name for the aca-py agent, and the registry driver), after registering a new DID through the driver, I'm unable to query said DID on the agent's wallet.

Are the aca-py agents currently only able to query for their created private DIDs, stored on their wallets? Thank you in advance.

**Comment by swcurran** [comment]
Sorry this didn't get answered.  I think what you are asking is whether an ACA-Py agent can control (e.g. have the private key of) an existing DID on a ledger.  If so, the answer is yes.  You need to pass in the seed for the DID using the SEED startup parameter for a public DID.  When that is done, the ACA-Py agent checks it's wallet to see if the DID is there and if not, creates it.  Then it checks the ledger on which the DID is expected to be, and if it doesn't exist, it creates it. If it does exist, it assumes that it matches the DID it created in its wallet.  These initialization scenarios are used all the time and are very reliable.
