### ISSUE TITLE
Presentation Proof not verified

### ISSUE THREAD

**Issue by afa1imb** [hyperledger/aries-cloudagent-python#1257]
This is related to [#175](https://github.com/hyperledger/aries-cloudagent-python/issues/175)

I'm trying to make a presentation proof request, and though the state of the presentation proof record is always verified, but the attribute "verified" is always false. This is my workflow :

First the verifier is making a connection invitation to the verifier: 

> POST ​/connections​/create-invitation

Then the prover receives the invitation: 

> POST /connections​/receive-invitation

and then sends a presentation proposal using the connection id and an earlier defined credential definition id:

> ```json
> {
>   "auto_present": false,
>   "connection_id": "f34cba81-bedb-45b9-b40d-2403c5d6d990",
>   "presentation_proposal": {
>     "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/present-proof/1.0/presentation-preview",
>     "attributes": [
>         {
>           "cred_def_id": "Aydxxx:3:CL:2583:default",
>           "name": "Attribute1",
>           "value": "bla"
>         },
>         {
>           "cred_def_id": "Aydxxx:3:CL:2583:default",
>           "name": "Attribute2",
>           "value": "blub"
>         }
>     ],
>     "predicates": [   ]
>   },
>   "trace": true
> }

The response is:

> ```json
> {
>     "updated_at": "2021-04-30 14:37:54.242939Z",
>     "trace": true,
>     "auto_present": false,
>     "created_at": "2021-04-30 14:37:54.242939Z",
>     "presentation_proposal_dict": {
>         "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/present-proof/1.0/propose-presentation",
>         "@id": "1cb103e7-0d6b-44a7-a2cd-9adb164785aa",
>         "~trace": {
>             "target": "log",
>             "full_thread": true,
>             "trace_reports": []
>         },
>         "presentation_proposal": {
>             "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/present-proof/1.0/presentation-preview",
>             "attributes": [
>             {
>           "cred_def_id": "Aydxxx:3:CL:2583:default",
>           "name": "Attribute1",
>           "value": "bla"
>         },
>         {
>           "cred_def_id": "Aydxxx:3:CL:2583:default",
>           "name": "Attribute2",
>           "value": "blub"
>         }        
>             ],
>             "predicates": []
>         }
>     },
>     "role": "prover",
>     "presentation_exchange_id": "47225a63-9f3d-44c4-bf88-6707584cb9ab",
>     "thread_id": "1cb103e7-0d6b-44a7-a2cd-9adb164785aa",
>     "initiator": "self",
>     "connection_id": "f34cba81-bedb-45b9-b40d-2403c5d6d990",
>     "state": "proposal_sent"
> }

 The verifier then fetches the presentation using the thread id:
 
>  GET /present-proof/records?thread_id=1cb103e7-0d6b-44a7-a2cd-9adb164785aa

and gets following response:

> ```json
> {
>     "results": [
>         {
>             "connection_id": "f34cba81-bedb-45b9-b40d-2403c5d6d990",
>             "thread_id": "1cb103e7-0d6b-44a7-a2cd-9adb164785aa",
>             "updated_at": "2021-04-30 14:37:54.399689Z",
>             "trace": true,
>             "role": "verifier",
>             "auto_present": false,
>             "initiator": "external",
>             "presentation_proposal_dict": {
>                 "@type": "did:sov:BzCbsxxx;spec/present-proof/1.0/propose-presentation",
>                 "@id": "1cb103e7-0d6b-44a7-a2cd-9adb164785aa",
>                 "~trace": {
>                     "target": "log",
>                     "full_thread": true,
>                     "trace_reports": []
>                 },
>                 "presentation_proposal": {
>                     "@type": "did:sov:BzCbsxxx;spec/present-proof/1.0/presentation-preview",
>                     "attributes": [
> {
>           "cred_def_id": "Aydxxx:3:CL:2583:default",
>           "name": "Attribute1",
>           "value": "bla"
>         },
>         {
>           "cred_def_id": "Aydxxx:3:CL:2583:default",
>           "name": "Attribute2",
>           "value": "blub"
>         }        
>                     ],
>                     "predicates": []
>                 }
>             },
>             "state": "proposal_received",
>             "presentation_exchange_id": "d3e8d41a-e8fa-467a-b9f4-e9c417e7062c",
>             "created_at": "2021-04-30 14:37:54.399689Z"
>         }
>     ]
> }

Then the verifier sends a request to present proof:
> POST /present-proof​/records​/d3e8d41a-e8fa-467a-b9f4-e9c417e7062c/send-request

and gets following response:

> ```json
> {
>     "connection_id": "3a5a833b-418e-491e-a24c-4730fc2c347f",
>     "thread_id": "1cb103e7-0d6b-44a7-a2cd-9adb164785aa",
>     "updated_at": "2021-04-30 14:44:48.831583Z",
>     "trace": true,
>     "role": "verifier",
>     "auto_present": false,
>     "initiator": "external",
>     "presentation_proposal_dict": {
>         "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/present-proof/1.0/propose-presentation",
>         "@id": "1cb103e7-0d6b-44a7-a2cd-9adb164785aa",
>         "~trace": {
>             "target": "log",
>             "full_thread": true,
>             "trace_reports": []
>         },
>         "presentation_proposal": {
>             "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/present-proof/1.0/presentation-preview",
>             "attributes": [
>           {
>           "cred_def_id": "Aydxxx:3:CL:2583:default",
>           "name": "Attribute1",
>           "value": "bla"
>         },
>         {
>           "cred_def_id": "Aydxxx:3:CL:2583:default",
>           "name": "Attribute2",
>           "value": "blub"
>         }   
>             ],
>             "predicates": []
>         }
>     },
>     "state": "request_sent",
>     "presentation_exchange_id": "d3e8d41a-e8fa-467a-b9f4-e9c417e7062c",
>     "created_at": "2021-04-30 14:37:54.399689Z",
>     "presentation_request": {
>         "name": "proof-request",
>         "version": "1.0",
>         "nonce": "981857811225108271185480",
>         "requested_attributes": {
>             "0_attribute1_uuid": {
>                 "name": "Attribute1",
>                 "restrictions": [
>                     {
>                         "cred_def_id": "Aydxxx:3:CL:2583:default"
>                     }
>                 ]
>             },
>             "1_attribute2_uuid": {
>                 "name": "Attribute2",
>                 "restrictions": [
>                     {
>                         "cred_def_id": "Aydxxx:3:CL:2583:default"
>                     }
>                 ]
>             }
>         },
>         "requested_predicates": {}
>     }
> }

The the prover sends the presentation:

> POST ​/present-proof​/records​/47225a63-9f3d-44c4-bf88-6707584cb9ab/send-presentation

using following body:

> ```json
> {
>     "name": "proof-request",
>     "version": "1.0",
>     "nonce": "981857811225108271185480",
>     "requested_attributes": {
>         "0_attribute1_uuid": {
>             "cred_id": "babddb38-0d8b-43f7-a40f-6b571f4d2483",
>             "revealed": true
>         },
>         "1_attribute2_uuid": {
>             "cred_id": "babddb38-0d8b-43f7-a40f-6b571f4d2483",
>             "revealed": true
>         }
>     },
>     "requested_predicates": {},
>     "self_attested_attributes": {
>         "self_attested_attr1": "bla",
>         "self_attested_attr2": "blub"
>     }
> }

When fetching the record of the presentation from the verifier side:

> GET /present-proof/records/d3e8d41a-e8fa-467a-b9f4-e9c417e7062c

following response comes back:

> ```json
> {
>     "presentation_request": {
>         "name": "proof-request",
>         "version": "1.0",
>         "nonce": "981857811225108271185480",
>         "requested_attributes": {
>             "0_attribute1_uuid": {
>                 "name": "Attribute1",
>                 "restrictions": [
>                     {
>                         "cred_def_id": "Aydxxx:3:CL:2583:default"
>                     }
>                 ]
>             },
>             "1_attribute2_uuid": {
>                 "name": "Attribute2",
>                 "restrictions": [
>                     {
>                         "cred_def_id": "Aydxxx:3:CL:2583:default"
>                     }
>                 ]
>             }
>         },
>         "requested_predicates": {}
>     },
>     "role": "verifier",
>     "presentation": {
>         "proof": {
>             "proofs": [
>                 {
>                     "primary_proof": {
>                         "eq_proof": {
>                             "revealed_attrs": {
>                                 "attribute1": "bla",
>                                 "attribute2": "blub"
>                             },
>                             "a_prime": "xxx",
>                             "e": "xxx",
>                             "v": "xxx",
>                             "m": {
>                                 "master_secret": "xxx"
>                             },
>                             "m2": "xxx"
>                         },
>                         "ge_proofs": []
>                     },
>                     "non_revoc_proof": null
>                 }
>             ],
>             "aggregated_proof": {
>                 "c_hash": "4343433",
>                 "c_list": [
>                     [
>                         1,
>                         186,
>                         136,
>                         59,
>                         113
>                     ]
>                 ]
>             }
>         },
>         "requested_proof": {
>             "revealed_attrs": {
>                 "0_attribute1_uuid": {
>                     "sub_proof_index": 0,
>                     "raw": "bla",
>                     "encoded": "bla"
>                 },
>                 "1_attribute2_uuid": {
>                     "sub_proof_index": 0,
>                     "raw": "blub",
>                     "encoded": "blub"
>                 }
>             },
>             "self_attested_attrs": {
>                "self_attested_attr1": "bla",
>                "self_attested_attr2": "blub"
>             },
>             "unrevealed_attrs": {},
>             "predicates": {}
>         },
>         "identifiers": [
>             {
>                 "schema_id": "Aydxxx:2:vss_permissions:1.0",
>                 "cred_def_id": "Aydxxx:3:CL:2583:default",
>                 "rev_reg_id": null,
>                 "timestamp": null
>             }
>         ]
>     },
>     "trace": true,
>     "initiator": "external",
>     "thread_id": "1cb103e7-0d6b-44a7-a2cd-9adb164785aa",
>     "presentation_exchange_id": "d3e8d41a-e8fa-467a-b9f4-e9c417e7062c",
>     "connection_id": "3a5a833b-418e-491e-a24c-4730fc2c347f",
>     "presentation_proposal_dict": {
>         "@type": "did:sov:BzCbsNYxxx;spec/present-proof/1.0/propose-presentation",
>         "@id": "1cb103e7-0d6b-44a7-a2cd-9adb164785aa",
>         "~trace": {
>             "target": "log",
>             "full_thread": true,
>             "trace_reports": []
>         },
>         "presentation_proposal": {
>             "@type": "did:sov:BzCbsxxx;spec/present-proof/1.0/presentation-preview",
>             "attributes": [
>             {
>           "cred_def_id": "Aydxxx:3:CL:2583:default",
>           "name": "Attribute1",
>           "value": "bla"
>         },
>         {
>           "cred_def_id": "Aydxxx:3:CL:2583:default",
>           "name": "Attribute2",
>           "value": "blub"
>         }  
>             ],
>             "predicates": []
>         }
>     },
>     "auto_present": false,
>     "verified": "false",
>     "created_at": "2021-04-30 14:37:54.399689Z",
>     "updated_at": "2021-04-30 14:45:24.151861Z",
>     "state": "verified"
> }

My Question is, what should I do to the verified field in the last response to be true, not false?

Thank you very much!

**Comment by swcurran** [comment]
I'm not the best on these, but the "verified" is coming back from the the call to Indy AnonCreds to verify the proof.  I suspect that the issue has to do with the use of the self-attested attributes.  I notice that there are restrictions that the claims must come from a specific Cred Def (`Aydxxx:3:CL:2583:default`), but since they are self-attested, they don't meet that restriction.  Is it possible that is the issue?

You might try removing the restriction -- although I'm not sure what "proving" self-attested claims would mean.

**Comment by naman20sharma** [comment]
Well I am facing a similar issue and I have not added any self-attested attribute. Although, it was working as expected in the older version (0.3.5). The state of the presentation proof record is always `verified`, but the `verified` flag is always `false`.

@TimoGlastra -- can you please take a look at this ?

**Comment by esune** [comment]
The `verified` flag may also be returned as `false` if the requested credentials were presented, but the revocation check failed.
@naman20sharma are you using credential definitions with revocation support enabled? Older versions of aca-py may not have supported this completely/correctly.

**Comment by afa1imb** [comment]
@swcurran Thank you very much! Not using self attested attributes resolved the issue

**Comment by naman20sharma** [comment]
> The `verified` flag may also be returned as `false` if the requested credentials were presented, but the revocation check failed.
> @naman20sharma are you using credential definitions with revocation support enabled? Older versions of aca-py may not have supported this completely/correctly.

Yes, I do have the revocation check enabled in credential definitions. Is there any other parameter required specifically ?

**Comment by esune** [comment]
> 
> 
> > The `verified` flag may also be returned as `false` if the requested credentials were presented, but the revocation check failed.
> > @naman20sharma are you using credential definitions with revocation support enabled? Older versions of aca-py may not have supported this completely/correctly.
> 
> Yes, I do have the revocation check enabled in credential definitions. Is there any other parameter required specifically ?

Not that I can think of. Make sure the `non-revoked` interval either omits the `from` boundary, or sets it to `0`. To can be whichever epoch timestamp you want (e.g.: now).

**Comment by naman20sharma** [comment]
> > > The `verified` flag may also be returned as `false` if the requested credentials were presented, but the revocation check failed.
> > > @naman20sharma are you using credential definitions with revocation support enabled? Older versions of aca-py may not have supported this completely/correctly.
> > 
> > 
> > Yes, I do have the revocation check enabled in credential definitions. Is there any other parameter required specifically ?
> 
> Not that I can think of. Make sure the `non-revoked` interval either omits the `from` boundary, or sets it to `0`. To can be whichever epoch timestamp you want (e.g.: now).

Well, I tried by setting revocation `false` and with that I am sharing my presentation-request flow [https://pastebin.com/hJTVp6fn](url). I'm still not sure what's wrong, please take a look at it. 
Thank you!

**Comment by esune** [comment]
Can you try and see what the outcome is if you don't use attribute value restrictions (e.g.: `attr::studentid::value`)?

**Comment by naman20sharma** [comment]
> Can you try and see what the outcome is if you don't use attribute value restrictions (e.g.: `attr::studentid::value`)?

It worked after removing this attribute value restriction (but when revocation was disabled). But, actually I need this restriction to segregate the credential to be verified, as same cred def is being used for multiple credentials and I don't wish to verify all of them together. If using this attribute restriction was causing the problem, what should I do ? 
Thank you! for your consistent response.

**Comment by esune** [comment]
> 
> It worked after removing this attribute value restriction (but when revocation was disabled). But, actually I need this restriction to segregate the credential to be verified, as same cred def is being used for multiple credentials and I don't wish to verify all of them together. If using this attribute restriction was causing the problem, what should I do ?
> Thank you! for your consistent response.

@swcurran I don't believe it is expected for a proof to not be "fully verifiable" when using attribute value restrictions: should this be logged as an issue to be further investigated?

**Comment by pstuermlinger** [comment]
I'm currently running into the same issue with attribute value restriction. This feature is required by the use case and should work according to the anoncred specification:  https://hyperledger.github.io/anoncreds-spec/#restrictions

Side note: The spec says `attr::<attribute-name>::<attribute-value>` (=`attr::color::red`) but the example states `"attr::color::value" : "red"`.

This one doesn't work:
```json
{
  "name": "Check-In of course 1234",
  "version": "1.1.0",
  "requested_attributes": {
    "0_Participant": {
      "names": [
        "Name",
        "Participantnumber",
        "Coursenumber"
      ],
      "restrictions": [
        {
          "cred_def_id": "Ufv...:3:CL:...:default",
          "attr::Coursenumber::value": "1234"
        }
      ]
    }
  },
  "requested_predicates": {},
  "nonce": "..."
}
```

Schema:
```json
{
  "schema_name": "Participant",
  "schema_version": "1.0",
  "attributes": [
    "Name",
    "Participantnumber",
    "Coursenumber"
  ]
}
```
It works when I remove the attribute value restriction. But then people can show any credential of this kind not only those which fulfill the requirements.

**Comment by pstuermlinger** [comment]
The solution to my problem is to write "attr::coursenumber::value": "1234" (lower-case) instead of "attr::Coursenumber::value": "1234" (upper-case). Even though the requested attribute is upper-case.
