### ISSUE TITLE
RFC 0510 - ACA-Py DIF PE is_holder support

### ISSUE THREAD

**Issue by shaangill025** [hyperledger/aries-cloudagent-python#1261]
-[ RFC 0510](https://github.com/hyperledger/aries-rfcs/tree/master/features/0510-dif-pres-exch-attach) in regards to `is_holder` states that `preferred or required as defined in the spec.Note that this feature allows the Holder to present credentials with a different subject identifier than the DID used to establish the DIDComm connection with the Verifier.`
- This means when `is_holder` is required we should only present and sign those credentials where `credentialSubject.id` is the same as the ConnRecord my_did.
- Since, current connection DID will be `did:sov:`, it will leave out all of BbsBls credentials and not support limit_disclosure. So is_holder cannot be used alongside limit_disclosure

Is this as expected and should be implemented in ACA-Py like this? To support this:
- When fetching W3C credentials, check if `is_holder`
- add `subject_ids = [ConnRecord.my_did]` as a parameter and call `search_credentials()`

**Comment by swcurran** [comment]
No -- that's sounds very wrong.  The DID used for the connection with the verifier should (almost) never be used for anything to do with verifiable credentials.  I'll take a look at that in the RFC.

**Comment by TimoGlastra** [comment]
That doesn't sound right indeed.

`is_holder` means you want the presenter of the credential to be the same as the credential holder. In most cases this translates to the signature on the VP coming from the same did as the credentialSubject.id

**Comment by swcurran** [comment]
I'm not sure why this `preferred or required as defined in the spec.
Note that this feature allows the Holder to present credentials with a different subject identifier than the DID used to establish the DIDComm connection with the Verifier.` is in the RFC at all. 

IMHO you would never want to use the DIDComm DID as the Verifier.  This wording suggests using the DID from the DIDComm connection is the normal way, but if you need to change it, you can use this other way.

Is it just my interpretation?  If you want to use your DIDComm DID for multiple purposes (such as with a VC), that's up to you, but it should never be suggested or recommended (or implied) in any RFCs.

**Comment by shaangill025** [comment]
> That doesn't sound right indeed.
> 
> `is_holder` means you want the presenter of the credential to be the same as the credential holder. In most cases this translates to the signature on the VP coming from the same did as the credentialSubject.id

This is what is happening currently in ACA-Py [ even when `is_holder` is not specified in constraint], so what is expected when there is `is_holder` specified?
### In ACA-Py as of yet
If a `presentation_request` is processed and 3 credentials are applicable to be included in the `VP`. 
- If all 3 credentials have `did:...:test` as `credentialSubject.id`, VP is signed with suite having `public_key_base58` as `did:...:test`'s `did_info.verkey`
-  If one or more of the 3 credentials have `did:...:test` as `credentialSubject.id` and the remainder has no `credentialSubject.id`, VP is signed with suite having `public_key_base58` as `did:...:test`'s `did_info.verkey`
- If one of 3 credentials have `did:...:other_test` and the other 2 have `did:...:test` as `credentialSubject.id`, an exception is raised stating `Applicable credentials have different credentialSubject.id, multiple proofs are not supported currently`

The following is from the DIF spec:
```
The constraints object MAY contain an is_holder property. If present, its value MUST be an array of objects composed as follows:

- The is-holder object MUST contain a field_id property. The value of this property MUST be an array of strings, with each string
matching the string value from a field object’s id property. This identifies the attribute whose Subject is of concern to the Verifier.
- The is-holder object MUST contain a directive property. The value of this property MUST be one of the following strings:
1. required - This indicates that the processing entity MUST include proof that the Subject of each attribute identified by a value
in the field_id array is the same as the entity submitting the response.
2. preferred - This indicates that it is RECOMMENDED that the processing entity include proof that the Subject of each attribute
identified by a value in the field_id array is the same as the entity submitting the response.

The is_holder property would be used by a Verifier to require that certain inputs be provided by a certain Subject. 
For example, an identity verification Presentation Definition might contain an Input Descriptor for a birthdate from a birth
certificate. Using is_holder, the Verifier would be able to require that the Holder of the birth certificate Claim is the same as the
Subject of the birthdate attribute. This is especially useful in cases where a Claim may have multiple Subjects.
```
The verifier must specify which `fields` in the `input_descriptors`, so only credentials filtered from these fields should be proven to be provided by a certain subject. Can signing the presentation still provide holder binding?

**Comment by TimoGlastra** [comment]
The way you have it currently implemented seems correct, if the following is also true:

- If none of the credentials have a credentialSubject.id, an exception is raised stating that it is not possible to prove the `is_holder` requirement.

I think the statement should just be removed from the RFC

**Comment by shaangill025** [comment]
> The way you have it currently implemented seems correct if the following is also true:
> 
> * If none of the credentials have a credentialSubject.id, an exception is raised stating that it is not possible to prove the `is_holder` requirement.
> 
> I think the statement should just be removed from the RFC

Sounds good. For the following will this be the right approach:
- But if `is_holder` is missing/not specified then don't sign the `VP` at all? I guess it cannot be verified by the verifier then.
- In reference to the DIF spec [snippet above], currently, the `field_ids` are not being used. Maybe we should also check that each of the filtered credentials from that `field` have the same `credentialSubject.id`, otherwise raise an exception?

**Comment by shaangill025** [comment]
> Sounds good. For the following will this be the right approach:
> 
> * But if `is_holder` is missing/not specified then don't sign the `VP` at all? I guess it cannot be verified by the verifier then.
> * In reference to the DIF spec [snippet above], currently, the `field_ids` are not being used. Maybe we should also check that each of the filtered credentials from that `field` have the same `credentialSubject.id`, otherwise raise an exception?

@TimoGlastra Any feedback will be appreciated.
