### ISSUE TITLE
Indy tails server - tails_server & tester arguments error

### ISSUE THREAD

**Issue by wildnano** [hyperledger/aries-cloudagent-python#1264]
Hi,

I cloned https://github.com/bcgov/indy-tails-server.git
and started  /indy-tails-server/docker/
I got these issues :
```
WARNING: The STORAGE_PATH variable is not set. Defaulting to a blank string.
WARNING: The LOG_LEVEL variable is not set. Defaulting to a blank string.

tails-server_1        | usage: tails-server [-h] [--host <host>] [--port <port>]
tails-server_1        |                     [--log-config <log_config_path>] [--log-level <log_level>]
tails-server_1        |                     --storage-path <storage_path>
tails-server_1        | tails-server: error: argument --storage-path: expected one argument

tester_1              | integration.py: error: the following arguments are required: --genesis-url, --tails-server-url
```
![image](https://user-images.githubusercontent.com/23073731/123274534-e5aefa00-d503-11eb-93b7-cf43ede58dfb.png)

I tried to implement the files Dockerfiletails.server and Dockerfile.test with no success
Thanks for your help

**Comment by esune** [comment]
You need to update your startup command and specify `--genesis-url` to tell the agent which ledger to connect to, and `--tails-server-base-url` to tell it where to upload the tails files when creating a credential with revocation support.

See [this](https://github.com/hyperledger/aries-cloudagent-python/blob/main/docs/GettingStartedAriesDev/CredentialRevocation.md) for additional reference.

**Comment by esune** [comment]
Closing issue as I think the above answer addresses the problem. Please feel free to reopen in https://github.com/bcgov/indy-tails-server if more help is required, as the issue seems to be related to the `tails-server` rather than aca-py.
