### ISSUE TITLE
Problems running run_docker

### ISSUE THREAD

**Issue by gilAsier** [hyperledger/aries-cloudagent-python#1277]
I've been trying to start the docker(/run_docker) for a while with the aim of having the rest API enabled and being able to start developing my own controller.
The problem is that I am not being able to access the API services.
This is what I running:

![image](https://user-images.githubusercontent.com/4936241/123796695-adcdfb00-d8e5-11eb-952c-49cbe3ef6f51.png)

What should be the procedure to follow to have the rest API available?

**Comment by ducadellaforcoletta** [comment]
Hello,

have you exposed the port you are using (8021 & 8020) in the ENV variable
$PORTS?
Take a look at the run_docker script.


Il giorno mar 29 giu 2021 alle ore 14:25 gilAsier ***@***.***>
ha scritto:

**Comment by gilAsier** [comment]
That was the problem. Thanks you for the help!
