### ISSUE TITLE
Acme Agent crashes with errors

### ISSUE THREAD

**Issue by afrancoc2000** [hyperledger/aries-cloudagent-python#1288]
Hi, 

I'm running the [Acme Controller Workshop](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AcmeDemoWorkshop.md) but I am getting an error on line 213 of acme.py:

```
AttributeError: 'Namespace' object has no attribute 'wallet_type'
```

It seems something to do with this [change](https://github.com/hyperledger/aries-cloudagent-python/commit/e1a589a694d58337c4dde1c241cf8b3c72858956#diff-8ee8a2cb1f9b0c20e9da8af048d4d2cc3d898e2a08f3a2e96c163a6bdd605c68).

Tried to force it using this code:

    args = parser.parse_args()
    args.wallet_type = ''
    check_requires(args)

But now I'm getting this new error: 

    Exception: Error registering DID, response code 400

I guess all the initialization of the acme agent should change to be like the Alice and Faber ones.

Hope it helps

**Comment by esune** [comment]
Probably something for @andrewwhitehead  to chime in.

**Comment by ianco** [comment]
There's an outstanding PR that should fix this:

https://github.com/hyperledger/aries-cloudagent-python/pull/1289

**Comment by esune** [comment]
@afrancoc2000,  @ianco can you please confirm we can close this issue, since #1289 was merged?

**Comment by ianco** [comment]
Closing this issue, please open a new issue if there are any further problems

**Comment by afrancoc2000** [comment]
Confirmed :)
