### ISSUE TITLE
Update Alice/Faber Credential and Proof Request to use Aries RFC "Date Int" format

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#1291]
A fun one for @ianco when he has some time.

Please update the Alice/Faber demo to change the "age" attribute to be "DateOfBirth" and use the "DateInt" recommended format as outlined in this recently merged [PR to Aries RFCs](https://github.com/hyperledger/aries-rfcs/pull/687).  Once done, change the proof request to use that style instead of the current ">18" check.  

It would be good to demo that in practice.

**Comment by ianco** [comment]
Fixed in PR https://github.com/hyperledger/aries-cloudagent-python/pull/1395
