### ISSUE TITLE
Getting error while issuing credentials

### ISSUE THREAD

**Issue by iaman1998** [hyperledger/aries-cloudagent-python#1292]
Hello, I am trying to issue a credential using a javascript controller made by me, but I am getting the following error on sending the data to /issue-credential/send 
{'connection_id': ['Missing data for required field.'], 'credential_proposal': ['Missing data for required field.']}
My credential object looks like this 
{
    "comment": "string",
    "credential_proposal": {
        "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/1.0/credential-preview",
        "attributes": [
            {
                "name": "Name",
                "value": "Alice Smith"
            },
            {
                "name": "Date",
                "value": "2020-01-01"
            },
            {
                "name": "Degree",
                "value": "Maths"
            },
            {
                "name": "Age",
                "value": "24"
            }
        ]
    },
    "schema_issuer_did": "GCezUGKaGXjaeuUrGgN22f",
    "connection_id": "804d0219-cd5a-4a1b-8db8-4244ad8dd641",
    "schema_version": "2.0",
    "schema_id": "GCezUGKaGXjaeuUrGgN22f:2:Vague:2.0",
    "issuer_did": "GCezUGKaGXjaeuUrGgN22f",
    "cred_def_id": "GCezUGKaGXjaeuUrGgN22f:3:CL:139026:default_vague",
    "schema_name": "Vague"
}

**Comment by esune** [comment]
The error message seems to indicate `connection_id` and `credential_proposal` are either missing or malformed, however the above JSON looks fine to me. @andrewwhitehead @ianco do you have any thoughts other than confirming the payload being sent to the agent matches the above?

**Comment by ianco** [comment]
The json looks good to me.

**Comment by iaman1998** [comment]
Another thing i'd like to add for @ianco and @esune is that the same controller works fine with the aca-py agents running on play with docker, the one given in demo. And another thing is, for the agent i am running on my own computer, when i issue credentials with same json using swagger api, it works fine. Similar issue comes with the acme controller while requesting proofs, i am using the acme controller as given in demo.

**Comment by esune** [comment]
Very odd. It sounds like the only difference in your setup is the agent you are posting requests to, so I'd start by confirming the version and startup settings are the same in both cases.

**Comment by iaman1998** [comment]
> Very odd. It sounds like the only difference in your setup is the agent you are posting requests to, so I'd start by confirming the version and startup settings are the same in both cases.
I am on the latest version of aca-py which is 0.6.0 , and i'd put the startup flags 
`aca-py start --label Faber \
-it http 0.0.0.0 8000 \
-ot http --admin 0.0.0.0 8021 \
--admin-insecure-mode \
--genesis-url "http://test.bcovrin.vonx.io/genesis" \
--seed {{seed}} \
--endpoint "http://localhost:8000/" \
--debug-connections --auto-provision \
--wallet-type indy --wallet-name FABER \
--wallet-key secret --auto-accept-requests \
--auto-accept-invites --auto-ping-connection --auto-respond-credential-proposal \
--auto-respond-credential-offer --auto-respond-credential-request \
--auto-store-credential`

**Comment by esune** [comment]
> 
> I am on the latest version of aca-py which is 0.6.0 , and i'd put the startup flags
> `aca-py start --label Faber \ -it http 0.0.0.0 8000 \ -ot http --admin 0.0.0.0 8021 \ --admin-insecure-mode \ --genesis-url "http://test.bcovrin.vonx.io/genesis" \ --seed {{seed}} \ --endpoint "http://localhost:8000/" \ --debug-connections --auto-provision \ --wallet-type indy --wallet-name FABER \ --wallet-key secret --auto-accept-requests \ --auto-accept-invites --auto-ping-connection --auto-respond-credential-proposal \ --auto-respond-credential-offer --auto-respond-credential-request \ --auto-store-credential`

I think the endpoint declaration is incorrect, as `localhost` will be resolved by other agents as their own service/host - you need to use an address that is addressable by other services s well (e.g.: `host.docker.internal` or the docker VM IP address, an example of scripts that pull it is[here](https://github.com/bcgov/issuer-kit/blob/master/docker/manage#L3)).

Once thing you can check is the state of the connection you are going to be sending the credential on: if the agents can't talk both ways it will not get to `active` (I suspect this might be the case).

**Comment by iaman1998** [comment]
> I think the endpoint declaration is incorrect, as `localhost` will be resolved by other agents as their own service/host - you need to use an address that is addressable by other services s well (e.g.: `host.docker.internal` or the docker VM IP address, an example of scripts that pull it is [here](https://github.com/bcgov/issuer-kit/blob/master/docker/manage#L3)).

This looks possible, although all agents are running on the same network, i'll still try explicitly mentioning the ip address.

**Comment by iaman1998** [comment]
@esune so I mentioned the endpoint IP explicitly, opened the ports , and even checked whether the connections are active, still I am getting the same error.

**Comment by iaman1998** [comment]
Seems the issue was about Content-Type , i didn't mention application/json and thus it wasn't working. It used to work in older versions so I thought it would work here too. But now it is all settled. Thank you. @esune and @ianco for your help.
