### ISSUE TITLE
Issuer of Credential not shown in Credential Exchange Record in Issue-credentialsV2

### ISSUE THREAD

**Issue by futureman2007** [hyperledger/aries-cloudagent-python#1299]
I noticed, that when an agent receives a credential proposal, there is no information about who has issued the credential (for example a credential definition ID). But when the record is stored in the wallet, this information is "magicly" provided.

Is this a bug or have i overseen something?
When for example a device is receiving a credential proposal i need the device to ask its owner: "Hey, i got this credential from X. Shall i trust it?"

An other use case would be, that the device stores credentials in the wallet, when they are issued from X".

At the Moment i can only achieve this, by accepting the credential, looking it up in the wallet, check the cred_def_id and then decide to delete it or to leave it in the wallet.
Or simply using issue-credentialsv1, which provides this information in the credential-exchange record

**Comment by ianco** [comment]
> I noticed, that when an agent receives a credential proposal, there is no information about who has issued the credential (for example a credential definition ID). But when the record is stored in the wallet, this information is "magicly" provided.

Do you mean a credential offer?  A credential proposal is send from the holder to the issuer, so the issuer will provide the info about themself.

**Comment by futureman2007** [comment]
Looking inside the JSON of the credential Records in aca-py during the whole flow, i could not find those entries like credential_definition id. In issue-credentials 1.0 it is provided as credential_definition_id. In issue-credentials 2.0 such a field is not provided (when i haven overseen it... searching it for 1 1/2 hours...)

**Comment by swcurran** [comment]
Pretty sure it is in the attachment, I think the base-64 encoded field.  Decode that and you should see it.
