### ISSUE TITLE
present-proof/create-request as QR code?

### ISSUE THREAD

**Issue by srbms23** [hyperledger/aries-cloudagent-python#1312]
Is there a way to show present-proof/create-request as QR code so it can be easily scanned from a Wallet on a Cellphone? The idea is same as with invitation-url when new connection is created.

If it works, I would also appreciate if someone could shortly explain how to do that. 

Thanks in advance!

**Comment by swcurran** [comment]
Yes, this is a supported feature, called a "connection-less presentation".  There are a number of examples of this used in the community.  For example, you can look at [vc-authn-oidc](https://github.com/bcgov/vc-authn-oidc) which uses this technique to create an Open ID Connection IdP based on verifiable credentials.

I'm sure there are other simpler examples, but that might be a useful place for you to look.

**Comment by swcurran** [comment]
Note that there are ways to do this with AIP 1.0 (as with the example above) and with AIP 2.0 using the Out of Band Protocol.  It can be found here: https://github.com/hyperledger/aries-rfcs/blob/master/features/0434-outofband/README.md

**Comment by srbms23** [comment]
Thank you @swcurran for a quick response!
That is a good starting point for me!

In case of further questions, I will reopen this issue.
