### ISSUE TITLE
Keyword conflict with /transactions/create-request, request body schema name Date

### ISSUE THREAD

**Issue by jcourt562** [hyperledger/aries-cloudagent-python#1319]
Running Swagger Codegen for Typescript on the 0.7.0-rc1 flags an issue with  the `Date` Model type. It causes it to rename the type to `ModelDate`.  In the past this sort of manipulation has caused issues with the packing/unpacking code Swagger generates.

**Details** 
There is a model type of `Date` that seems to have been defined for the `POST /transactions/create-request` endpoints body. 

It is the ONLY place I can see this being used and it results in a keyword clash in typescript. In general it would seem to be a good idea not to use these generic names unless they really are some generic type. The description for the `Date` type seems to be `Expiry Date` and format is `date-time`. 

**Prefered Solution**
Would it be possible to change this to a name like `ExpirationDate` that is unlikely to conflict with any Language Keywords ?

**Comment by swcurran** [comment]
@andrewwhitehead ^^^

**Comment by swcurran** [comment]
This hasn't happened. Should we give up and close this or should this still be done?

**Comment by jcourt562** [comment]
You can choose to close it if you like.  If it causes me pain in future I am sure I can do the changes and propose a PR.

**Comment by swcurran** [comment]
Appreciate the PR if it is needed.  I'll close this one.
