### ISSUE TITLE
Invalid $ref of #/definitions/IndyAttrValue for the IndyCredential>properties>values field

### ISSUE THREAD

**Issue by jcourt562** [hyperledger/aries-cloudagent-python#1320]
It looks like all $ref values in the generated openapi.json file has changed from 0.6.0 to 0.7.0-rc1.  They use to be of the format 

"$ref" : "#/definitions/V20PresExRecordList"

They now seem to be of the format 

"$ref": "#/components/schemas/V20PresExRecordList"

However this is not the case for the IndyCredential>properties>values field which seems to have retained an invalid reference to :

"$ref": "#/definitions/IndyAttrValue"

This causes swagger to generate code with a non-existent type declared for the `values` field.

**Prefered fix**

Should just be able to provide correct reference to be "#/components/schemas/IndyAttrValue"

**Comment by swcurran** [comment]
@andrewwhitehead ^^^

**Comment by jcourt562** [comment]
Sorry this one looks like I jumped the gun.  Running the `generate-open-api-spec` tool in ACA-py doesn't show this issue so it is clearly something in my swagger environment.
