### ISSUE TITLE
Error when authenticating in Multitenancy mode

### ISSUE THREAD

**Issue by santidediego** [hyperledger/aries-cloudagent-python#1321]
I create a new subwallet with **/multitenancy/wallet** and get my received token. Body in the post method is:

```
{
  "key_management_mode": "managed",
  "label": "Charly",
  "wallet_dispatch_type": "default",
  "wallet_key": "Charly",
  "wallet_name": "Charly",
  "wallet_type": "indy",
  "wallet_webhook_urls": [
    "http://localhost:8022/webhooks"
  ]
}
```

Then I authenticate using swagger by using _Bearer {token}_ following the steps in the [multitenancy docs](https://github.com/hyperledger/aries-cloudagent-python/blob/main/Multitenancy.md)

When I try to run (for example) a **/wallet/did/create** method for creating a local DID I get a _401:Unauthorized_ Error.

Am I missing something?

**Comment by ianco** [comment]
Not sure off the top of my head exactly how this works, but you can check the alice/faber demo, which supports creating sub-wallets in multitenancy mode.  The demo code for creating new wallets is here:

https://github.com/hyperledger/aries-cloudagent-python/blob/89324e24dfbc46d22e4bca5895089c08558e6943/demo/runners/support/agent.py#L402

**Comment by esune** [comment]
@santidediego you need to provide `both` headers for the `Bearer` token for the subwallet **AND** the `api-key` for the main wallet when executing requests to a tenant. This is a bit misleading in my opinion, @TimoGlastra might have additional insight on why this is required, rather than only using the bearer token for the tenant.

**Comment by santidediego** [comment]
Do you mean even if you are not using `api-key` for the API? In my case I am doing the testing with an unprotected API, so I was only using the token for the subwallets.

I was indeed able to run the demo controller with multitenancy, the issue only happens with the OpenAPIDemo

**Comment by esune** [comment]
Sorry, I missed that detail. No, if you don't have an api-key set for the agent you should not need to specify one. I will have to check the behaviour locally as all of the instances we use are generally api-key protected.

**Comment by swcurran** [comment]
Closing this age as dormant. Please reopen if we think we can make progress on these.
