### ISSUE TITLE
Cannot specify inbound transport through environment variable

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#1330]
At present, I don't think it is possible to specify `--inbound-transport` through the accompanying environment variable `ACAPY_INBOUND_TRANSPORT`. This stems from this argument being both an "append" and "nargs > 1" argument. The ConfigArgParse library does not accept a list of lists at the current version in use by ACA-Py or in the most recent release (1.5.1 at the time of writing).

I have a PR to ConfigArgParse that should address this: https://github.com/bw2/ConfigArgParse/pull/240

Until my or another fix is merged and released, I figured it made sense to call out this limitation here.

If my assessment is off, I'd be happy to hear how you did it as all permutations I attempted and time spent examining the code seems to indicate this is just broken in ConfigArgParse lol.

**Comment by dbluhm** [comment]
My PR has been merged so this is now just awaiting a release with the fix.

**Comment by ianco** [comment]
It should work, see this PR:  https://github.com/hyperledger/aries-cloudagent-python/pull/1627

**Comment by MonolithicMonk** [comment]
No that doesn't work either
