### ISSUE TITLE
Issue while sending credential to mobile wallet

### ISSUE THREAD

**Issue by Rounak210** [hyperledger/aries-cloudagent-python#1336]
![image](https://user-images.githubusercontent.com/85231262/127489555-90a527a1-be55-4ad7-a9e2-a9d79ca8e5a1.png)

Issue while executing /connections/send-offer/

**Comment by esune** [comment]
That error is a failed delivery of a webhook for a connection. Is `http://dev-proof-of-account-service:8081/webhooks/topics/connections/` able to receive POST requests (in particular from the agent service)?

**Comment by Rounak210** [comment]
@esune, it is able to receive post requests as other than sending credential to the wallet, all the webhook calls works fine

**Comment by esune** [comment]
In order to try help you we will need more details about your setup (where is the ledger how are you running the agents, which mobile wallet are you using) and details/how to reproduce the issue.

**Comment by swcurran** [comment]
Likely a setup issue. Closing - please reopen if there is more to this one.
