### ISSUE TITLE
Reconnect to mediator never receives `granted` status

### ISSUE THREAD

**Issue by phearaeun** [hyperledger/aries-cloudagent-python#1337]
I observed that the agent is always able to get `granted` status for the first invitation. If we try to reconnect with a new invitation, we never get `granted` status from the mediator.

What is the best practice for reconnecting to mediator?

**Comment by swcurran** [comment]
@burdettadam @dbluhm ^^^^  Thoughts on this?

**Comment by dbluhm** [comment]
@phearaeun could you clarify what you mean by "reconnecting" to the mediator? After you've established a connection with the mediator and requested mediation and received it, that agent does not need to "reconnect" at least in the DIDComm sense. If the mediation clients (the agents granted mediation) are cloud agents and have an endpoint accessible to at least the mediator, the mediator will immediately forward messages it receives on behalf of the client to the client's endpoint. If the mediation clients are edge agents and do not have an endpoint accessible to the mediator, the mediator will store messages it receives for the client in an "undelivered queue." To retrieve stored messages, the edge agent must connect (in the TCP/HTTP/WebSocket sense) to the mediator and send a message with `"~transport": {"return_route": "all"}`. Usually a trust ping is used as the message.

Hopefully this gives you some background to answer your question

**Comment by phearaeun** [comment]
In dev mode, after the service restarted, I have to connect the agent to the mediator again. Every new request will never receive granted status as the first request.

> that agent does not need to "reconnect" at least in the DIDComm sense.
Yes, I agree with this but if we accidentally connect to the mediator again, we can't receive the granted status from the new request. My solution now is to check first if the agent already connected to the mediator, we don't connect to it again.


And why does the mediator respond `granted` only for the first invitation, in case that the new request is made by the same agent?
