### ISSUE TITLE
Provision with existing empty database 

### ISSUE THREAD

**Issue by tomaaron** [hyperledger/aries-cloudagent-python#1338]
Hello,

is there any way to provision into an existing empty database? I've been trying to wrap my head around this for quiet some time because it isn't always the case that you're granted superuser for the DBMS. Any help would be appreciated!

**Comment by ianco** [comment]
This should work with the latest aca-py release, if you use the published docker image:

https://hub.docker.com/layers/bcgovimages/aries-cloudagent/py36-1.16-1_0.7.0/images/sha256-8bd108e69eecb3a758d02e6dca79a020f5239ebb79c0c7607c5de2c2401de1b2?context=explore

This includes updates to the indy-sdk postgres driver to allow this exact requirement.

**Comment by tomaaron** [comment]
Can confirm this worked! Thank you.

**Comment by tomaaron** [comment]
I'm sorry can't confirm that it's working. The user needs to permission for CREATE DB ;(

**Comment by ianco** [comment]
Can you provide some information about what you have done?  How did you create the database and what startup parameters are you providing to aca-py?

**Comment by tomaaron** [comment]
Yes, I've created a gist with a `docker-compose` https://gist.github.com/tomaaron/62b9af5c37992356f820c0ed0fcebd3a

**Comment by swcurran** [comment]
Closing as dormant. Please reopen if appropriate.
