### ISSUE TITLE
How to get Credential_revocation_id

### ISSUE THREAD

**Issue by Rounak210** [hyperledger/aries-cloudagent-python#1340]
I am setting up revocation_registry in my Aca-Py. Can anyone please tell me, how to fetch credential_revocation_id?? while executing credential-revocation.

POST /issue-credential/revoke?rev_reg_id=<revocation_registry_id>
     &cred_rev_id=<credential_revocation_id>&publish=<true|false>

**Comment by swcurran** [comment]
Generally, you have to collect it when you issue the credential. You should then save it in whatever database you are linking the issued credential to the entity to whom you issued the credential.

**Comment by Rounak210** [comment]
@swcurran , There are no parameter with "Cred_rev_id" while issuing credential. Are you talking about "revocation_id" ?? .Kidnly have a look once. Thanks!!

![image](https://user-images.githubusercontent.com/85231262/127858542-4fcf2ca4-9e9f-4c9b-880f-d16c270fc377.png)

**Comment by Rounak210** [comment]
![image](https://user-images.githubusercontent.com/85231262/127882395-e190d07c-8576-43b7-8f1c-d09cc99244f0.png)
Thanks for the help, I think revocation_id is the cred_rev_id.

**Comment by swcurran** [comment]
Good stuff.  You have to keep both the "cred_rev_id" and "rev_reg_id" and provide them at revocation time. Unfortunate that the name of the field varies in the usage...  :-(
