### ISSUE TITLE
Consensus is Impossible Error

### ISSUE THREAD

**Issue by Rounak210** [hyperledger/aries-cloudagent-python#1345]
![image](https://user-images.githubusercontent.com/85231262/128509439-e897c51a-d439-443f-9e61-75e0bc4bb3d2.png)
Can anyone provide any feedback regarding this error?. I am using ACA-Py version 1.16-0_0.6.0 . 
@swcurran can you please look into this issue once.??
Getting this error while issuing credential. Any help would be appreciated. Thanks!!.

**Comment by ianco** [comment]
Hi, are you still getting this error?  It looks like a connection issue between the aca-py agent and the indy ledger (or a problem with the ledger nodes getting out of sync)

**Comment by Rounak210** [comment]
@ianco, yes sometimes while sending credentials onto the mobile wallet, I get this error. However, if I try it again, then the error gets resolved.

**Comment by ianco** [comment]
Which mobile wallet and ledger are you using?

**Comment by swcurran** [comment]
Closing.
