### ISSUE TITLE
Can not create schema and cred def with multitenancy

### ISSUE THREAD

**Issue by phearaeun** [hyperledger/aries-cloudagent-python#1351]
I am trying to create schema and cred def with multitenancy but I receive only `Unauthorized`.
I also tried to create default sub wallet to get the token so that I can submit schema and create cred def for the next purpose but I received the following:

```
    Created new profile
    Profile backend: indy
    Profile name: mysubwallet
    No public DID
```
Error: cannot submit schema without public did.

Any help is appreciated!

**Comment by JovanShandro** [comment]
@phearaeun You have to first create a public DID for the sub wallet. The way to do that is:
POST /wallet/did/create which creates a local DID. Then you have to register this DID to the ledger. If you are using http://dev.greenlight.bcovrin.vonx.io/ then just go on 'Register from DID' and add the DID and the Verkey. Once this is done you just:
POST /wallet/did/public and add the DID as a parameter. After this you should be able to create a schema and cred def.
