### ISSUE TITLE
Multitenancy Scalability

### ISSUE THREAD

**Issue by JovanShandro** [hyperledger/aries-cloudagent-python#1353]
Hello!

Just some background information: We are a team of developers who want to use Aries python for our use-case. We want the solution to be able to scale at least to 100,000 users or even 1,000,000. Ideally we should be able to set up a single agent for each user, however to facilitate the transition from the old model of centralized systems the initial idea was to offer to host the agents for the users. Hosting a single agent for each user creates other problems, so the idea of a multi-tenant agent came up. 

I have tested multi-tenant agents with up to 10,000 users and it works fine, however I wanted to ask is there an 'upper limit' to how much users a multi-tenant agent can have, or is it expected that when there are many users (e.g 1 000 000), it would take a lot of seconds just to e.g create a single invitation.

Any insight on this would be appreciated! Thank you!

**Comment by TimoGlastra** [comment]
Hi @JovanShandro,

In theory you should be able to use multi-tenancy for hosting a lot of tenants at the same time. I think the main limit is the number of concurrent wallets being used at a given time. You could host multiple ACA-Py next to each other using the same underlying database to reduce the load for the agents. However, there is no optimization to efficiently handle . Meaning that messages for sub wallets can go to any of the ACA-Py agents, causing a lot of wallets being opened even though the wallet is already open in another agent.

There are however a few things that probably need to be resolved for it to work in large scale use cases. One of them is the automatically managing resources by closing wallets if there are too many opened. Currently wallets will never get closed, meaning the list of open wallets will pile up until the agent is shut-down. This is fine for 10-100 wallets, but gets problematic when talking about the numbers you're talking about. See https://github.com/hyperledger/aries-cloudagent-python/pull/928

Another related issue that could help with performance: https://github.com/hyperledger/aries-cloudagent-python/issues/1349

**Comment by swcurran** [comment]
Hopefully you have what you need. Closing this issue.
