### ISSUE TITLE
aca-py args to set AIP level 

### ISSUE THREAD

**Issue by xtrycatchx** [hyperledger/aries-cloudagent-python#1357]
My apologies is advance if my question seems silly

when running `./bin/aca-py start <...some args>` , its currently in `aip 2.0` . Is there a way to specify `aip 1.0` when starting the cloudagent locally? By the way, I'm running purely as a mediator.

I know that when running the demo we can do something like `./run_demo faber --aip 10`. May I know if there's a way to provide the same aip 1.0 settings when directly running the aca-py ?

Thanks.

**Comment by ianco** [comment]
I did a quick search and I don't think aca-py has this option available.  (aca-py supports both aip's, so I'm not sure a flag is actually necessary)

(FYI you can get a list of all available args by running something like `./bin/aca-py start --help`)

**Comment by swcurran** [comment]
Note that Alice/Faber Demo has "--aip1" and "-aip2" options. You might want to check what ACA-Py settings are triggered when those are used.

Closing this issue.
