### ISSUE TITLE
got Error!!! DID register to ledger using admin API on Multitenancy ACAPY_Agent  

### ISSUE THREAD

**Issue by bbmarley** [hyperledger/aries-cloudagent-python#1358]
Getting an error !!!

I'm using Multitenancy ACAPY_Agent to Register DID to the ledger 
(If I used http://localhost:9000 for register DID to ledger manually its working fine but I need to register using Admin API)

- I created a Sub-wallet using `/multitenancy/wallet` got token as response
- Using the Response token of subwallet API I created local DID using `/wallet/did/create` got DID and Verkey as response
- Using DID and verkey I tried to register DID to ledger using admin API `/ledger/register-nym` I got an error with 403 Undocumented 

![register nym error response](https://user-images.githubusercontent.com/43064317/129957385-6ee629db-3f98-40d5-88ff-a780bd93787f.JPG)

**Comment by jeffdem** [comment]
Hi bbmarley, in my opinion, you need a STEEWARD wallet already register on the ledger and use his BEARER to use the API /ledger/register-nym to register nym of others wallets

**Comment by ianco** [comment]
For aca-py to write to the ledger, it needs a DID in its wallet that is already registered on the ledger, with a role (like STEWARD  or ENDORSER) with privileges to write to the ledger.  The aca-py wallet's public DID is used to sign the transaction that is sent to the ledger.  The error message `wallet "mywallet" has no public DID` means that your agent doesn't have a DID that can write to the ledger.

If you:

- start up your agent with an already-registered DID (you can register the `seed` using http://localhost:9000 and then start your agent with the `--seed` parameter, this will create the DID in the aca-py wallet and then promote it as the public DID)

... then when you create a new DID, you can write to the ledger using the above endpoint.

Check out the demo code, which does all this (see https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/runners/support/agent.py#L462)

**Comment by swcurran** [comment]
Closing
