### ISSUE TITLE
How to see the reason, why a proof request is not verified

### ISSUE THREAD

**Issue by romanzoun** [hyperledger/aries-cloudagent-python#1361]
This relates to https://github.com/hyperledger/indy-sdk/issues/2419

Hey

We have installed the revocation and it works. So we issue credentials and we have a demo application to login with this credentials via a proof request.

Than we revoke the credentials and the login fails....

state: verified
verified: false --> something went wrong

But how to get a message from aries, that this is because of revoced status of the credentials?

We're using aca-py

**Comment by ianco** [comment]
There is a separate API in aca-py to check if a credential is revoked (not sure offhand exactly what the API is but it's on the aca-py swagger page).

I don't think you can get a specific reason why a proof request fails (this comes from indy-sdk, it is not an aca-py feature).

**Comment by romanzoun** [comment]
Thank you,

Currently I start the verifier cloudagent with the "--auto-verify-presentation" flag....Do you think, if I use the 
POST: proof_request/{pres_ex_id}/verify 
I get in the error_msg the message, if its revoked?

So if we verify manually, we can get the reason?

**Comment by ianco** [comment]
No. The verification of the proof involves a bunch of math, and either it verifies or not.  I don't think there is any way to get the reason

**Comment by domwoe** [comment]
Nothing that ACA-Py can fix. The underlying libraries do not provide more information than proof is valid or not

**Comment by swcurran** [comment]
So the answer is to put the question to the underlying code -- indy-sdk and/or indy-credx, and ursa.

Closing this issue as an ACA-Py question.
