### ISSUE TITLE
Create controller and docker compose mechanism to run the aries-protocol-test-suite

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#137]
It would be helpful to have an easy way to have `aries-cloudagent-python` run through the set of tests in the `aries-protocol-test-suite`. Investigate the test suite and determine what tests are currently in the test suite. Once understood, create in a folder in this repo (perhaps `aries-test-suite`) a process to execute the test suite.  I would imagine the process would include:

- an ACA-Py controller that handles the test suite test cases
- a docker compose file that starts up all of the components to run the test suite tests - likely including
  - von-network
  - aries-test-suite
  - aca-py
  - aca-py controller
  - possibly a wallet (if necessary)
- a bash script that allows the test suite to be executed from the command line - possibly with options to run either a specific release (pulling the code from PyPi) or with the current code.

**Comment by vaniisgh** [comment]
Hey ! I'm a complete newbie to the Hyperledger framework, though I have been reading up on it ... I look forward to contributing to it and learning as I go ... would it be ok if I took up this issue :)

**Comment by swcurran** [comment]
My apologizes for the delay in responding to this--my email got backed up.  Not sure if you are still interested in this, but we'd be glad to have someone work on this.

Hopefully the documentation on ACA-Py and what a controller is gives you what you need to get started. Let us know if you have questions.

If you know Python, using "Faber" in the /demo folder might be a good way to go. If you are more comfortable in another language, then the you can right what is effectively a web app as the controller (using the ACA-Py APIs). We have a node one that might be a starting point.

**Comment by vaniisgh** [comment]
Sounds good! I'm going through the demos and setting learning up ... It should take a me a few days but as soon as I get the hang of it I look forward to completing this task :) !
