### ISSUE TITLE
modules not found errors when running aca-py for the first time

### ISSUE THREAD

**Issue by dnaicker** [hyperledger/aries-cloudagent-python#1381]
after building or installing aca-py the following modules not found when running
`aca-py --version` or `aca-py --help`

```
ModuleNotFoundError: No module named 'configargparse' 
ModuleNotFoundError: No module named 'deepmerge'
ModuleNotFoundError: No module named 'yaml' 
ModuleNotFoundError: No module named 'requests' 
ModuleNotFoundError: No module named 'marshmallow'
ModuleNotFoundError: No module named 'base58'
ModuleNotFoundError: No module named 'nacl'  
ModuleNotFoundError: No module named 'pydid' 
ModuleNotFoundError: No module named 'pyld' 
ModuleNotFoundError: No module named 'markdown' 
ModuleNotFoundError: No module named 'prompt_toolkit' 
ModuleNotFoundError: No module named 'prompt_toolkit.eventloop.defaults' 
ModuleNotFoundError: No module named 'aiohttp'
ModuleNotFoundError: No module named 'aiohttp_apispec'
ModuleNotFoundError: No module named 'aiohttp_cors' 
ModuleNotFoundError: No module named 'jwt'   
```

resolved by installing each missing dependency individually:

``` 
python3 -m pip install "prompt-toolkit<3.0.0"
python3 -m pip install jwt 
python3 -m pip install aiohttp_cors  
python3 -m pip install aiohttp_apispec
python3 -m pip install aiohttp 
python3 -m pip install prompt_toolkit
python3 -m pip install markdown  
python3 -m pip install pydid
python3 -m pip install pyld 
python3 -m pip install pynacl
python3 -m pip install base58
python3 -m pip install marshmallow 
python3 -m pip install requests 
python3 -m pip install pyyaml 
```

please could this be added to the install script?

**Comment by swcurran** [comment]
Did you install with PyPi?  Or just clone the repo?

Instructions for running locally are here if you used PyPi: https://github.com/hyperledger/aries-cloudagent-python/blob/main/DevReadMe.md#locally-installed. — sounds like perhaps we are missing a step in that guidance?

We strongly encourage using Docker when testing and developing as it greatly simplifies getting past issues like this.  Guidance is here: https://github.com/hyperledger/aries-cloudagent-python/blob/main/DevReadMe.md#docker

You can also look in the docker file to see what you need to do get all of the dependencies loaded.  Namely this dockerfile command can be run (minus the “RUN”) on the command line:

```bash
RUN pip3 install --no-cache-dir \
    -r requirements.txt \
    -r requirements.askar.txt \
    -r requirements.bbs.txt \
    -r requirements.dev.txt
```

**Comment by dnaicker** [comment]
Thank you Stephen, I will take a look at the docker file. 

I was using pip3 to install and also trying to run the aca-py file from source.
