### ISSUE TITLE
proof request without specifying `requested_predicates`

### ISSUE THREAD

**Issue by blu3beri** [hyperledger/aries-cloudagent-python#1384]
Currently, when using the Swagger UI, I can send a proof request, with v1, without setting the `requested_predicates`. This results in a 200, while it should fail as [indy_prover_search_credentials_for_proof_req](https://github.com/hyperledger/indy-sdk/blob/57dcdae74164d1c7aa06f2cccecaae121cefac25/libindy/src/api/anoncreds.rs#L1231) specifies that `requested_predicates` is not optional. This would mean that I either have to pass in an empty object of acapy adds this field with an empty object when I don't add it myself.

**Comment by ianco** [comment]
I suspect that if you're able to submit a proof request without specifying `requested_predicates`, then it's getting added in automatically at some stage.

Do you feel this is a critical issue?  I'm reluctant to recommend any changes to the v1.0 API since it's already pretty widely used.

**Comment by blu3beri** [comment]
I am testing it currently with AFJ in React Native and the issue is that I do not recieve the requested_predicates at all. This is what I receive decoded from base64 `{"name": "Proof request", "nonce": "1", "requested_attributes": {"additionalProp1": {"name": "a"}}, "version": "1.0"}`.

I do not think that is a major issue, but it does seem that ACA-Py does not add the `requested_predicates` field when it is not specified.

**Comment by swcurran** [comment]
@ianco -- can you look into this, please?

**Comment by ianco** [comment]
> @ianco -- can you look into this, please?

Yep on it.

**Comment by ianco** [comment]
I was able to submit w 1.0 proof request without specifying EITHER requested attributes or predicates.

When I call `/present-proof/records/<pres_ex_id>/credentials` I get a wallet error from Indy.

I'll update the input schema for creating a presentation request to make the requested attributes and predicates required.

**Comment by ianco** [comment]
See PR:  https://github.com/hyperledger/aries-cloudagent-python/pull/1411

**Comment by blu3beri** [comment]
Thanks!

**Comment by TimoGlastra** [comment]
@solidnerd this is the issue with proof request. PR #1411 should make the `requested_predicates` required
