### ISSUE TITLE
Docker Image v0.7.1 is missing

### ISSUE THREAD

**Issue by solidnerd** [hyperledger/aries-cloudagent-python#1386]
Currently I can't find any release on Docker Hub can you help me here ?

**Comment by swcurran** [comment]
@esune -- where are the docs to build/release a new image?  Thanks

**Comment by WadeBarnes** [comment]
https://github.com/bcgov/aries-cloudagent-container, but I see you've already built and published it.

**Comment by swcurran** [comment]
Should be there now, and published.  Please re-open if there is an issue.

Thanks!
