### ISSUE TITLE
Zero Knowledge poof on non numeric data / predicates on non numeric data

### ISSUE THREAD

**Issue by romanzoun** [hyperledger/aries-cloudagent-python#1391]
Hey

I have a demo, where I issue birthday as date and not the age in the credentials.

I want to make a predicate, that checks if the age is over 18, but based on the date.

Currently the checks worked only on integer data. 

What is a good way to implement this?

I have an idea to change the schema, that day, month and year is separate attribute and then send three predicates on that.
like 

```
"requested_predicates":
  [
   "0_birthday_day": {
        "name": "birthday_day",
        "p_type": ">=",
        "p_value": 4, #current day
      },
    "0_birthday_month": {
        "name": "birthday_month",
        "p_type": ">=",
        "p_value": 4, #current month
      },
    "0_birthday_year": {
        "name": "birthday_year",
        "p_type": ">=",
        "p_value": 2021, #current year
      }
  ]

```
Do you have best practice for predicates on non numeric values? Is it possible?

**Comment by ianco** [comment]
We have an issue to add this functionality to the demo:  https://github.com/hyperledger/aries-cloudagent-python/issues/1291

**Comment by romanzoun** [comment]
ok, and how you want to solve it? I need something for now that I can use :)

I also think about to extend my schema to have birthday-date and another autogenerated field, like "numeric-birthdate", that puts puts the date as Long. 

Is it possible to hide some attrubutes from the wallet, for such autogenerated data?

**Comment by ianco** [comment]
The solution described in the ticket I linked should work (disclaimer: I haven't tried it yet).

... change the "age" attribute to be "DateOfBirth" and use the "DateInt" recommended format as outlined in this recently merged PR to Aries RFCs:  https://github.com/hyperledger/aries-rfcs/pull/687

**Comment by romanzoun** [comment]
Thank you very much, I'll try to do so :)
