### ISSUE TITLE
marshmallow.exceptions.ValidationError: {'_schema': ['Value for description.code must be issuance-abandoned']}

### ISSUE THREAD

**Issue by mwensveen-ebpi** [hyperledger/aries-cloudagent-python#1397]
Issue created based on https://chat.hyperledger.org/channel/aries-cloudagent-python?msg=xZ7RwjjJNwdxpKzsF

Our ACA-PY agent (version 0.7.0) is connected to the BCOVRIN TEST (--genesis-url http://test.bcovrin.vonx.io/genesis).
When sending a credential to a user that uses connect.me we receive an error. Which is to be expected, as connect.me does not use the bcovrin test network.
But the the problem-report is not handled smoothly.

Error received from connect.me:
aries_cloudagent.transport.pack_format DEBUG Expanded message: {'@id': '9d661ea0-2336-41fe-b3af-db12b3c2438f', '@type': 'did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/1.0/problem-report', 'comment': 'error occurred: VcxError { inner: \n\nCould not find Credential Definition on the connected Ledger networks\n\nCredential Definition not found on the Ledger }', 'description': {'code': 'invalid-credential-offer', 'en': "Couldn't create credential-request for received credential-offer."}, '~thread': {'received_orders': {'did:sov:Cst5jmVuTpyQGgs7hg3Ybt': 0}, 'sender_order': 0, 'thid': 'd8655eb0-cbf5-43fb-be86-fea8c10b23f9'}}

This results in the following stacktrace in ACA-PY:
2021-09-01 12:47:16,618 aries_cloudagent.messaging.models.base ERROR CredentialProblemReport message validation error:
Traceback (most recent call last):
File "/home/indy/aries_cloudagent/messaging/models/base.py", line 137, in deserialize
return schema.loads(obj) if isinstance(obj, str) else schema.load(obj)
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.py", line 723, in load
data, many=many, partial=partial, unknown=unknown, postprocess=True
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/marshmallow/schema.py", line 904, in doload
raise exc
marshmallow.exceptions.ValidationError: {'_schema': ['Value for description.code must be issuance-abandoned']}

**Comment by swcurran** [comment]
Taking a look at the RFC, the handling in ACA-Py is technically correct. Per the [paragraph in this section of the Issue Credential RFC](https://github.com/hyperledger/aries-rfcs/tree/main/features/0453-issue-credential-v2#states), the code should be “issuance-abandoned”.  As such, this is a bug in the connect.me implementation.

On the ACA-Py side — is ACA-Py doing the right thing, or should we be doing anything differently.

@andrewwhitehead @ianco — checking with you on that.  If not, let’s close this one.

**Comment by andrewwhitehead** [comment]
Technically that's the only supported error code, but we should probably just log a warning if something else is received.

**Comment by swcurran** [comment]
Thanks.  @shaangill025 — could you please take this one?  Low priority compared to the rest of what you are doing.  Hit this one when you have a bit of opening or want a change of pace.

Thanks!
