### ISSUE TITLE
No ledger available when not using '--wallet-type indy' for agent startup 

### ISSUE THREAD

**Issue by dnaicker** [hyperledger/aries-cloudagent-python#1398]
Was just wondering if this is a common error, when I use `--wallet-type indy` to startup agent I get ledger pool timeout error. 

- If I remove` --wallet-type indy`, the aries cloud agent starts up although when publishing to ledger it says `Error 403 ledger not found`

- This error also appears when calling: `schemas_send_schema raise web.HTTPForbidden(reason=reason) aiohttp.web_exceptions.HTTPForbidden: No ledger available. ` Would I need HTTPS? 

- I am able to register Alice as an issuer using` curl -X POST "http://localhost:9000/register" \
-d '{"seed": "Alice000000000000000000000000001", "role": "TRUST_ANCHOR", "alias": "Alice"}'
` 
- ` curl -X POST http://localhost:11000/schemas -H 'Content-Type: application/json' -d '{ "attributes": ["name", "age"], "schema_name": "my-schema", "schema_version": "1.0"}'
 `returns ledger not found, which is linked to `--wallet-type indy` not being provided as I get a `pool timeout error` if `--wallet-type indy` is provided. 

- I am connecting to localhost:9000 von-network from localhost:11000 aca-py agent

**Comment by dnaicker** [comment]
[Steps to ACA-PY.pdf](https://github.com/hyperledger/aries-cloudagent-python/files/7118736/Steps.to.ACA-PY.pdf)

I attached a file with steps to reproduce. I just left out cloning and starting the von-network with ./manage start --logs

**Comment by dnaicker** [comment]
Updated doc with von-network steps

[Steps to ACA-PY.pdf](https://github.com/hyperledger/aries-cloudagent-python/files/7118751/Steps.to.ACA-PY.pdf)

**Comment by dnaicker** [comment]
when running `curl -X GET "http://localhost:11000/schemas/created" -H "accept: application/json"`

the following error is returned: 
>  Traceback (most recent call last): File "/home/denver/.local/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 162, in ready_middleware
    return await handler(request)
  File "/home/denver/.local/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 199, in debug_middleware
    return await handler(request)
  File "/home/denver/.local/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/denver/.local/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 366, in setup_context
    return await task
  File "/home/denver/.local/lib/python3.6/site-packages/aries_cloudagent/messaging/schemas/routes.py", line 194, in schemas_send_schema
    raise web.HTTPForbidden(reason=reason)
aiohttp.web_exceptions.HTTPForbidden: No ledger available

from the source code it is looking for `--wallet-type in the args`

![image](https://user-images.githubusercontent.com/7840952/132317438-d59d4036-2d56-4005-a1c9-742611bffa77.png)

I setup my agent with:

> aca-py start \ 
--label Alice \ 
-it http 0.0.0.0 8000 \ 
-ot http \ 
--admin 0.0.0.0 11000 \ 
--admin-insecure-mode \ 
--genesis-url http://localhost:9000/genesis \ 
--seed Alice000000000000000000000000001 \ 
--endpoint http://localhost:8000/ \ 
--debug-connections \ 
--auto-provision \ 
--wallet-name Alice1 \ 
--wallet-key secret \ 
--auto-accept-invites \ 
--auto-accept-requests \ 
--wallet-type basic

**Comment by dnaicker** [comment]
I noticed a previous github issue regarding BaseLedger that impacts the same line of code: https://github.com/hyperledger/aries-cloudagent-python/issues/518 

Fix that was merged:
https://github.com/hyperledger/aries-cloudagent-python/pull/533

It is definitely the '--wallet-type indy' that is causing an issue, is there a work around?

**Comment by dnaicker** [comment]
When using '--wallet-type indy' I get connection pool errors.

I tried to resolve by installing indy-node and indy-plenum.

Version mismatches between prompt_toolkit occured and I messed up my pip and python installs.

I had to refresh my ubuntu vm and start again.

I am now using the docker demo images and trying to resolve those errors: 'wallet item not found' for accept-request api call for issuer with connection_id from logs.

The main issue here with '--wallet-type indy' was that it could not find a ledger pool. I used indy-cli and noticed that there were no ledger pools listed when VON-Network was running. 

I tried looking into the VON-Network startup scripts but did not get further.

Not sure how to continue.

**Comment by dnaicker** [comment]
when starting up agents I am now using `--genesis-url http://dev.greenlight.bcovrin.vonx.io/genesis` this resolved the issues for me although for local installations of indy node this might not assist

**Comment by ianco** [comment]
Same issue as your other issues (I think) - when you run a local von-network, if you are running the agents in docker containers (for example `./run_demo faber`) then you start von-network like `./manage start --logs`

However if you are running aca-py on your local machine (like `aca-py start ...`) then you need to start von-network with your local IP, like `./manage start <your IP> --logs`

**Comment by swcurran** [comment]
Closing as resolved.
