### ISSUE TITLE
OpenAPI demo accept-request error can't connect to host ip

### ISSUE THREAD

**Issue by dnaicker** [hyperledger/aries-cloudagent-python#1399]
Running the docker openapi demos with: https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AriesOpenAPIDemo.md

> `LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo alice --events --no-auto --bg`
> `LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo faber --events --no-auto --bg`

after using the following posts

> /connections/create-invitation (Faber)
> /connections/receive-invitation (Alice)
> /connections/{conn_id}/accept-invitation (Alice)
> /connections/{conn_id}/accept-request (Faber)

copied the `conn_id `from the logs for Faber and used separate `conn_id ` for and Alice from post response

when using Faber's `conn_id `it shows an error for accept-request

> 
> Alice      | 2021-09-07 18:29:51,465 aries_cloudagent.transport.outbound.manager ERROR >>> Outbound message failed to deliver, NOT Re-queued.
> Alice      | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.56.102:8020 ssl:default [Connect call failed ('192.168.56.102', 8020)]
> Alice      | ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.56.102', 8020)

I also get an error Fabers side:
`2021-09-07 18:30:24,697 aries_cloudagent.admin.server ERROR Handler error with exception: Connection is not in the request or response state`.

**Comment by dnaicker** [comment]
When I try play.with.docker.online and run the OpenAPI demo, at the accept-request copying the connection_id for faber from the log files to the OpenAPI REST accept-request call, it shows this error:

**Comment by dnaicker** [comment]
> When I try play.with.docker.online and run the OpenAPI demo, at the `accept-request` call, copying the `connection_id `for faber from the log then using that in the accept-request call, it shows this error: `wallet item not found`
> ![image](https://user-images.githubusercontent.com/7840952/132440090-3d744db2-f0fb-4de6-b3f3-29914977a9a0.png)
> 
> I used the start-up parameters of:
> 
> > LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo alice --events --no-auto --bg
> > LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo faber --events --no-auto --bg

**Comment by dnaicker** [comment]
I came across this error reported in the github issues that contained WalletItemNotFound, related to ACA-Py agents having multiple calls, not sure if it is related: https://github.com/hyperledger/aries-cloudagent-python/issues/557

**Comment by dnaicker** [comment]
Looking on older repository this could also be the issue: https://github.com/hyperledger/aries-acapy-controllers/issues/17

![image](https://user-images.githubusercontent.com/7840952/132450006-c6b2610c-b908-471c-a00d-30b09cafb5f7.png)

Not too sure how to configure the parameters

**Comment by ianco** [comment]
The error `Cannot connect to host 192.168.56.102:8020` means that the two agents can't connect with each other and therefore can't exchange messages.  Both agents (when you start with `./run_demo ...`) run in docker containers, so they should be able to connect using the internal docker network IP (which is `192.168.56.102` in this case).  I'm not sure why they can't but it's likely a docker issue.

The subsequent error on the faber side `Connection is not in the request or response state` is a direct result of the previous error - faber never received the connection request from alice, so faber's connection is still in invitation state.

**Comment by dnaicker** [comment]
Thank you @ianco the explanation helps a lot.
