### ISSUE TITLE
Get circleci running in bcgov environment in prep for transfer to HL

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#14]

**Comment by swcurran** [comment]
Reassigning to @WadeBarnes in hopes he can fit this in this week. 

If you can't, please at least comment out the CircleCI badges on the readme so that those don't show up, and reassign to me.

Thanks!

**Comment by WadeBarnes** [comment]
Wired up CircleCI and CodeCov with some help from @nrempel.  CircleCI as been configured to build PRs from forks.  Badges and links are working.

The `master` branch has been protected.  Merges require a review, build to succeed, and DCO sign-off.

Just need a new logo.

**Comment by nrempel** [comment]
circleci is up and running now 👍🏼
