### ISSUE TITLE
Plain-text DIDComm messages are sent to the external outbound queue 

### ISSUE THREAD

**Issue by acuderman** [hyperledger/aries-cloudagent-python#1402]
When using an external outbound queue. messages are not packed before they are pushed to the queue. That causes problems (apart from the security) when the recipient is a multitenant Aca-py agent since the relay can not figure out who is the recipient of the message.

[Messages should be packed in the similar way they are being when using the internal queue](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/transport/outbound/manager.py#L394)

**Comment by dbluhm** [comment]
Addressed by #1408
