### ISSUE TITLE
Aca-py not respecting NO_PROXY variables

### ISSUE THREAD

**Issue by paulbastian** [hyperledger/aries-cloudagent-python#1403]
Running Aca-py behind company firewalls requires proxy settings, at the same time internal services must be excluded from these proxy routes. Usually this is done by using environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY. Both HTTP_PROXY and HTTPS_PROXY are currently respected by aioHttp and since 0.6.0 imported into aca-py behavior by using the `trust_env=True`. NO_PROXY is not regarded by aiohttp in the current stable release.
However, the changes have already been merged into aiohttp and shall be released with version 3.8:
https://github.com/aio-libs/aiohttp/pull/5556
Therefore, this is a placeholder and information for people running into the same issue until aioHttp release 3.8 is included into aca-py.
Best regards,
Paul

**Comment by paulbastian** [comment]
As a quick fix, you can mount a patched client.py as a volume if working with docker containers:
https://gist.github.com/paulbastian/add8c12cc47509f3b41cb726287e05b5

**Comment by webknjaz** [comment]
FYI aiohttp v3.8 has been released this night.

**Comment by swcurran** [comment]
@shaangill025 -- can you please look at this. Andrew had been on it.

Thanks!

**Comment by pstuermlinger** [comment]
I'm also running into the same issue. The docker container is configured to use a company proxy. From within the container I can curl to other internal agents and services. However, when Aca-Py tries to send a message to another local agent via docker host ip (part of no_proxy) it just fails with a "Service Unavailable".

**Comment by paulbastian** [comment]
This issue should resolve with version 0.7.4 soon

**Comment by pstuermlinger** [comment]
Confirmed, works with the current rc. Thanks!
