### ISSUE TITLE
demo Faber agent not issuing credentials

### ISSUE THREAD

**Issue by AnasAlamin** [hyperledger/aries-cloudagent-python#1410]
i'm trying to issue a credential in Faber agent demo, but it's not issuing even though i established a connection.

**Comment by ianco** [comment]
@AnasAlamin can you please provide more details?

**Comment by AnasAlamin** [comment]
i'm following the demo provided in the link below,
https://www.youtube.com/watch?v=AomoHvw4lgc

i was able to issue credentials and it was all working great, but for the latest version it stopped issuing credentials.
i tried different mediators, different test genesis files and even different RNMA versions but it's not working.

**Comment by ianco** [comment]
Are you testing with BiFold or a different mobile agent?

I haven't tried BiFold but the demo was working recently (last week) with other mobile apps (esatus and trinsic).

**Comment by AnasAlamin** [comment]
any news...?

**Comment by swcurran** [comment]
Pretty sure the issue is on the Bifold side.  AFAIK, a change occurred there and recent releases (from late last week) were affected.

**Comment by AnasAlamin** [comment]
pretty sure something has changed from this side as well.
after your comment i got to make it work with the old version of BiFold, but now i can't even establish a connection neither from the old version of BiFold, nor the latest version

**Comment by swcurran** [comment]
Hopefully things have evolved since then. Closing this...please reopen if appropriate.
