### ISSUE TITLE
Credential not getting issued for ACA-PY version 0.6.0

### ISSUE THREAD

**Issue by Rounak210** [hyperledger/aries-cloudagent-python#1412]
Currently facing this issue while trying to issue credential onto the ledger,

requests.exceptions.HTTPError: 400 Client Error: Error when issuing credential: Error: Invalid structure. Caused b
y: UrsaCryptoError: Invalid len of bytes representation for PoingG2. CommonInvalidStructure. for url: http://dev-t
hrift-agent:5001/issue-credential/records/3e9555b6-412b-4b6a-b388-554c869dbe7b/issue

Any help will be appreciated. Thanks!!.

**Comment by Fethbita** [comment]
If you are using revocation, are you sure that the tails server is accessible?

**Comment by Rounak210** [comment]
The tail server is up and running but when i try to access it, it is showing 404 Not Found error.

**Comment by Fethbita** [comment]
So you might have created your credential definition and posted the tails file to the tails server but maybe restarted the tails server so now it is unreachable. Can you try to find out your registries using the `/revocation/registries/created` endpoint and post the files again using the `/revocation/registry/{rev_reg_id}/tails-file` endpoint.

**Comment by Rounak210** [comment]
x-special/nautilus-clipboard
copy
file:///home/rounak/Desktop/Screenshot%20from%202021-09-17%2023-07-17.png

**Comment by Rounak210** [comment]
![image](https://user-images.githubusercontent.com/85231262/133840085-4979a659-c1ef-4140-bcbf-29572bf4dba9.png)
Currently showing that my tail server is uploaded

**Comment by Fethbita** [comment]
What happens if you recreate the credential definition and try to issue from that one? Do you still get the error?

**Comment by swcurran** [comment]
Looks like this issue is dormant. Closing -- please reopen if appropriate.
