### ISSUE TITLE
Schema creation fails after upgrade to 0.7.1

### ISSUE THREAD

**Issue by seriousManual** [hyperledger/aries-cloudagent-python#1414]
We're currently in the process of upgrading from 0.5.6 to 0.7.1

One of the first issues that came up is that it now is no longer possible to create a schema using the `POST /schemas` 
I'm just using the Swagger UI to execute the request with the default example parameters:

![image](https://user-images.githubusercontent.com/1330022/133282577-ff357774-eb13-40b3-901a-a8ed83105871.png)

This is the error that is shown in the application logs:

![image](https://user-images.githubusercontent.com/1330022/133282647-68e7ad2c-5282-4bc7-9a9d-6f6fad7b94ef.png)

Something about the `schema_id` not matching a pattern which is weird, since one is not expected to supply a schema_id when creating a schema.

We're running the official image bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1

**Comment by seriousManual** [comment]
FWIW:
the setup in general is in a functioning state, establishing and setting up of connections is working, as well as the exchange of messages:

![image](https://user-images.githubusercontent.com/1330022/133283947-4f5f4d15-1b7d-4c75-bd44-4c2fbc0c05a8.png)

**Comment by swcurran** [comment]
@ianco , can you please take a quick look. Perhaps related to the Endorser?

**Comment by ianco** [comment]
@seriousManual can you provide more info about your setup?  You are correct this error should not happen when creating a schema (it may happen if creating a credential definition though).

I've tested the schema create in the version you are running and it works for me.

**Comment by seriousManual** [comment]
Thanks for the fast response, really appreciate it!
What setup details are you interested in in particular?

The container we're running is part of a docker-compose setup, its setup looks like this:

![image](https://user-images.githubusercontent.com/1330022/133340236-ce54a623-5a16-4314-afba-c3cab41bdb61.png)

**Comment by ianco** [comment]
Hi @seriousManual thanks for the info, that is helpful.

Can you provide a full log file for the create schema use case?

Specifically, can you start with a "clean" environment and:
- start up the ledger in a "new" state
- check the ledger browser (http://localhost:9000 if you are running von-network) to verify the ledger contents
- start up your faber agent with a "clean wallet" (please use the `--log-level debug` parameter to get detailed logging)
- create a public DID for faber
- create a schema
- check the ledger browser again to see if a transaction was created for the schema

Can you provide the full log for the above scenario (for faber)?

Thanks

FYI It's possible your error is getting raised *after* the schema is created on the ledger, when the aca-py agent is trying to construct the response to send back to the controller (the response contains the schema_id and I believe there is format validation on this response data structure ...)

**Comment by seriousManual** [comment]
Thank you @ianco !

> It's possible your error is getting raised after the schema is created on the ledger

It actually did not occur to me that the error may not be related to the schema *creation* but to a subsequent process that is involved.
It looked into it and your in fact right, the error does not happen when creating the schema (it is created allright). After schema creation our UI is triggered to refresh its state, when it then tries to update the created schemas, the request against the agent fails.

For the protocol and because somone might run into this as well:
We are using `openapi-typescript-codegen` (https://www.npmjs.com/package/openapi-typescript-codegen) to generate client code based on the openapi.json (https://github.com/hyperledger/aries-cloudagent-python/blob/main/open-api/openapi.json) provided with aca-py.
This library however generates this little piece of code:

```ts
function getUrl(options: ApiRequestOptions): string {
    const path = options.path.replace(/[:]/g, '_');
    const url = `${OpenAPI.BASE}${path}`;
```

Since a schemaId always contains colons this will invalidate the URL that is sent against aca-py (looks like this then: `/schemas//schemas/MhRTysEFWRAjnRVTs98G8Z_2_company_2.0`), hence the error message `"schema_id": ['String does not match expected pattern'].

I replaced it with the urlencoded version of the colon:
```ts
const path = options.path.replace(/[:]/g, '%3A');
```

Disclaimer: This might have some other implications, maybe there will come up some other issues with this fix. 

Thanks again for taking the time of looking into this!

**Comment by swcurran** [comment]
@seriousManual -- there is a document [Using Open API](https://github.com/hyperledger/aries-cloudagent-python/blob/main/UsingOpenAPI.md) about code generation.  Would it be helpful to add your comments to that document?

Glad this got resolved.

Thanks

**Comment by seriousManual** [comment]
> Would it be helpful to add your comments to that document?

Not sure, the issue only applies to users of `openapi-typescript-codegen`.
Since `@ula-aca/aries-cloudagent-interface` which you are referring to in the documentation is much more widely used it is unlikely that too many people are running into this...

If you like I can create a PR with some notes though!
