### ISSUE TITLE
Subtitute CL by BBS+ Signature

### ISSUE THREAD

**Issue by JosselinGN** [hyperledger/aries-cloudagent-python#1418]
Good Morning everybody,

Our goal is to replace the signature type, i.e. replace CL with BBS+ Signature.
After several research, we have seen that there are code implementations of the BBS+ Signature in "aries-cloudagent-python".
Could you tell me more? Is there a way to do this subtitution ? If yes, how ?

Thank you very much !

**Comment by swcurran** [comment]
Sorry for the delay in responding.

BBS+ Signatures is in ACA-Py. Today, there are no wallets that support it, but you can do it ACA-Py to ACA-Py and ACA-Py to AF-Go. Work is beginning on support for BBS+ in Aries Framework JavaScript, and from there into wallets.

To try it out in ACA-Py, take a look at the demo using this guidance:

https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AliceWantsAJsonCredential.md

**Comment by Nabil-oussa** [comment]
Hello @swcurran think you very much for your response and help. Our purposes is to have BBS+ in ACA–Py instead CL signature as in credential-definitions function as in this JSON
{
"credential_definition_id": "4kfmXB6jB2jB5Knt7uskb6:3:CL:8326:Vacc 1"
}
The question how we can configure the wallet’s ACA-Py to support the BBS+ signature. Thanks!
