### ISSUE TITLE
Issue when connecting two agents with WS protocol. 

### ISSUE THREAD

**Issue by kkamyczek** [hyperledger/aries-cloudagent-python#1440]
I have run two agents:

PORTS="8030:8030 8031:8031" ./scripts/run_docker start \
   --endpoint ws://192.168.0.104:8030 \
   --label alice.agent \
   --inbound-transport ws 0.0.0.0 8030 \
   --outbound-transport ws \
   --admin 0.0.0.0 8031 \
   --admin-insecure-mode \
   --wallet-type indy \
   --wallet-name alice.agent420695 \
   --wallet-key alice.agent420695 \
   --preserve-exchange-records \
   --wallet-local-did \
   --auto-provision \
   --genesis-url http://dev.greenlight.bcovrin.vonx.io/genesis \
   --trace-target log \
   --trace-tag acapy.events \
   --trace-label alice.agent.trace \
   --auto-ping-connection \
   --log-level DEBUG \
   --trace-target log \
   --trace-tag acapy.events \
   --trace-label alice.agent.trace \
   --recreate-wallet \
   --auto-accept-invites \
   --auto-accept-requests \
   --auto-store-credential

PORTS="8020:8020 8021:8021" ./scripts/run_docker start \
   --endpoint ws://192.168.0.104:8020 \
   --label faber.agent \
   --inbound-transport ws 0.0.0.0 8020 \
   --outbound-transport ws \
   --admin 0.0.0.0 8021 \
   --admin-insecure-mode \
   --wallet-type indy \
   --wallet-name faber.agent916333 \
   --wallet-key faber.agent916333 \
   --preserve-exchange-records \
   --wallet-local-did \
   --auto-provision \
   --genesis-url http://dev.greenlight.bcovrin.vonx.io/genesis \
   --trace-target log \
   --trace-tag faber.events \
   --trace-label faber.agent.trace \
   --auto-ping-connection \
   --log-level DEBUG \
   --trace-target log \
   --trace-tag faber.events \
   --trace-label faber.agent.trace \
   --recreate-wallet \
   --auto-accept-invites \
   --auto-accept-requests \
   --auto-store-credential

I have created an invitation (/connections/create-invitation)
in one agent and tried to receive it (/connections/receive-invitation).

I got such issue:
2021-10-13 08:25:19,871 aries_cloudagent.transport.outbound.manager ERROR Exception in outbound queue processing:
Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/transport/outbound/manager.py", line 366, in _process_loop
    self.deliver_queued_message(queued)
  File "/home/indy/aries_cloudagent/transport/outbound/manager.py", line 456, in deliver_queued_message
    queued.api_key,
TypeError: handle_message() takes from 4 to 5 positional arguments but 6 were given

It's related to this code:
  def deliver_queued_message(self, queued: QueuedOutboundMessage) -> asyncio.Task:
        """Kick off delivery of a queued message."""
        transport = self.get_transport_instance(queued.transport_id)
        queued.task = self.task_queue.run(
            transport.handle_message(
                queued.profile,
                queued.payload,
                queued.endpoint,
                queued.metadata,
                queued.api_key,
            ),

Could you please tell me if it's possible to use it with WebSockets?

**Comment by ianco** [comment]
See PR https://github.com/hyperledger/aries-cloudagent-python/pull/1442
