### ISSUE TITLE
Creating mediation request fails when using multi use invitation

### ISSUE THREAD

**Issue by acuderman** [hyperledger/aries-cloudagent-python#1443]
When using Did-Exchange multi-use invitation combined with caching, Mediation request after the connection is established fails in approximately 10% - 30% of cases with the following error: `Invalid mediation request: no active connection`

After some debugging, I found out that in some cases multi-use invitation is loaded instead of a derived one-time invitation, which causes a `no active connection` error since the multi-use invitation is always in the invitation state.

The incorrect invitation is loaded because the DIDComm message from the agent to the mediator is encrypted using recipient_verkey taken from the initial invitation and not from the connection response. I am unable to reproduce the issue if caching is turned off.

I have been logging [this line](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/protocols/connections/v1_0/manager.py#L1043). Values were the following:
- Mediator receives connection request `ENohtAAMbpLLSDeRxB5QdH6C9nGaobZb9Gv81htS3aUk::5KHUxXGpcQndkuUQJWg8o4omZnwbc58vR73TfD6JkXMe`
- Agent receive a connection response `7Uj9V41BGfwAv7ZpNWh4nxhniZisj9BkogFQ84bPp5ju::ENohtAAMbpLLSDeRxB5QdH6C9nGaobZb9Gv81htS3aUk`
- Mediator receives connection completed `ENohtAAMbpLLSDeRxB5QdH6C9nGaobZb9Gv81htS3aUk::7Uj9V41BGfwAv7ZpNWh4nxhniZisj9BkogFQ84bPp5ju`
- Mediator receives mediation request `ENohtAAMbpLLSDeRxB5QdH6C9nGaobZb9Gv81htS3aUk::5KHUxXGpcQndkuUQJWg8o4omZnwbc58vR73TfD6JkXMe`

### Reproduction steps
- Run agent and the mediator (agent with --open-mediation flag)
- Mediator: Create out of bound multi-use invitation (did-exchange)
- Agent: Receive an invitation and send the connection request
- Agent: Listen to connection established event (state = completed) and create mediation request
- Mediator: Either logs error or succedes

**Comment by swcurran** [comment]
Yes -- support for central caching is a need in ACA-Py.  We've had some progress made on it in the past (based on Redis) but the work didn't quite get completed.  We have that as a backlog item that really needs to be addressed and we're trying to see how to get it done.
