### ISSUE TITLE
Add endorser support to updating DID attributes

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#1447]
Problem description from @TimoGlastra :

We're currently testing a setup where we let an endorser submit a new DID to the ledger, but then want to use that DID as the public DID on an ACA-Py agent. When we start ACA-Py it will automatically try to update the endpoint on the ledger (which is a desired feature because we want the endpoint on the ledger), but currently rejects with the following error. Would you say this won't happen on either Sovrin staging or main net? Do you know if there are any plans to change this?

`Ledger rejected transaction request: client request invalid: UnauthorizedClientRequest('Rule for this action is: 1 TRUSTEE signature is required and needs to be owner OR 1 STEWARD signature is required and needs to be owner OR 1 ENDORSER signature is required and needs to be owner OR 1 NETWORK_MONITOR signature is required and needs to be owner OR 1 signature of any role is required and needs to be owner with additional metadata fees attrib_add OR 1 ENDORSER signature is required AND 1 signature of any role is required and needs to be owner\nFailed checks:\nConstraint: 1 TRUSTEE signature is required and needs to be owner, Error: Not enough TRUSTEE signatures\nConstraint: 1 STEWARD signature is required and needs to be owner, Error: Not enough STEWARD signatures\nConstraint: 1 ENDORSER signature is required and needs to be owner, Error: Not enough ENDORSER signatures\nConstraint: 1 NETWORK_MONITOR signature is required and needs to be owner, Error: Not enough NETWORK_MONITOR signatures\nConstraint: 1 signature of any role is required and needs to be owner with additional metadata fees attrib_add, Error: Fees are required for this txn type\nConstraint: 1 ENDORSER signature is required AND 1 signature of any role is required and needs to be owner, Error: Not enough ENDORSER signatures',)`

**Comment by frostyfrog** [comment]
I have tested the changes made by @HarshMultani-AyanWorks and they appear to resolve this issue. When making an Author DID public, the ATTRIB transaction gets signed by the Author and Endorser before being sent to the ledger. I would love to see the change make it into the project.

**Comment by ianco** [comment]
@HarshMultani-AyanWorks  do you have an estimate when your PR will be ready to review?  https://github.com/hyperledger/aries-cloudagent-python/pull/1616

Let me know if I can help with any of the outstanding work, we're planning for the next aca-py release and it would be good to have these updates included.

**Comment by HarshMultani-AyanWorks** [comment]
> @HarshMultani-AyanWorks do you have an estimate when your PR will be ready to review? #1616
> 
> Let me know if I can help with any of the outstanding work, we're planning for the next aca-py release and it would be good to have these updates included.

Hi @ianco, The PR should be ready to merge by this week

**Comment by swcurran** [comment]
Closing this as resolved.
