### ISSUE TITLE
Access profile on plugin initialization

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1452]
We're currently writing a plugin for ACA-Py that needs access to the profile and storage on startup and having a hard time finding a clean approach to this. The setup method only takes the InjectionContext, no profile, and the routes registration also doesn't get a profile.

How we currently solved is by adding a new endpoint and then calling that from the setup method. This is not ideal but gives us access to the context.

I was thinking whether we could maybe add an event that will be emitted after the agent has fully started. This would allow us to hook into that from the setup method and have access to the profile. Bonus is that we don't have to guess anymore when ACA-Py is fully initialized because the event will only trigger after the agent is initialized.

Is it already possible to do this? If not do you think something like the event I described above would work? Are there other (better) solutions?

**Comment by TimoGlastra** [comment]
cc @dbluhm. You know a lot about plugins and event busses :)

**Comment by dbluhm** [comment]
I fumbled the reopening of this issue (sorry) but while I've already triggered notifications: do we want to track the provision event addition as a feature request within this issue and keep it open until implemented?

**Comment by swcurran** [comment]
Do we think the provision event needs to handled in the same way?  If so, please add a new issue.

Closing this one as complete as originally requested.
