### ISSUE TITLE
Proof request with none_revoked restriction returns valid=true even though the credential has been revoked

### ISSUE THREAD

**Issue by etschelp** [hyperledger/aries-cloudagent-python#1455]
I tested this with the latest Lissi wallet and aca-py 0.7.2-rc0. 

Steps to reproduce.

1. aca-py is started with a configured tails server, a cred def with revocation registry is created
2. Connect aca-py with the Lissi wallet
3. Issue a credential
4. Revoke the credential
5. Send a proof request with none_revoked restriction and a timestamp that is after the revocation from step 4
6. Lissi wallet says credential has been revoked, but we send it anyway
7. aca-py says proof is valid, but the verified field should be set to false in this case

In the aca-py logs I see the following

```
2021-10-21 13:57:37,745 aries_cloudagent.indy.verifier INFO Amended presentation request (nonce=1056466064839133135704935): removed non-revocation interval at requested_attributes referent Mz2w979BSbBb8SGihvYbYy:2:Bank Account:1.0; corresponding credential in proof is irrevocable
2021-10-21 13:57:37,745 aries_cloudagent.indy.verifier WARNING Amended presentation request (nonce=1056466064839133135704935); removed global non-revocation interval; no revocable credentials in proof
```
This is most likely a version incompatibility issue between agents. When I look into the [verifier.py](https://github.com/hyperledger/aries-cloudagent-python/blob/2355b5ec8f36b4507ba091587d6095f7ad61f5f5/aries_cloudagent/indy/verifier.py#L50) I see that it checks for the existence of a _timestamp_ field in the _identifiers_ section of the presentation request that is retrieved via the _sub_proof_index_. If this field is missing from the response of the other agent the none revocation check is skipped. 

Response from Lissi that is not working

```json
    "presentation": {
        "requested_proof": {
            "revealed_attrs": {},
            "revealed_attr_groups": {
                "Mz2w979BSbBb8SGihvYbYy:2:Bank Account:1.0": {
                    "sub_proof_index": 0,
                    "values": {
                        "Name": {
                            "raw": "revocationtest01",
                            "encoded": "54732868580499211735974961366354315864941016766578192688462230293521237042341"
                        }
                    }
                }
            },
            "self_attested_attrs": {},
            "unrevealed_attrs": {},
            "predicates": {}
        },
        "identifiers": [
            {
                "schema_id": "Mz2w979BSbBb8SGihvYbYy:2:Bank Account:1.0",
                "cred_def_id": "NBUXM1kVv4yNVc6ezpaa94:3:CL:232:demo-bank-02",
                "rev_reg_id": "NBUXM1kVv4yNVc6ezpaa94:4:NBUXM1kVv4yNVc6ezpaa94:3:CL:232:demo-bank-02:CL_ACCUM:4e70d6ee-f5cd-4920-8465-b30225c64192"
            }
        ]
    }
```

Response from another aca-py that is working:

```json
    "presentation": {
        "requested_proof": {
            "revealed_attrs": {},
            "revealed_attr_groups": {
                "M6Mbe3qx7vB4wpZF4sBRjt:2:bank_account:1.0": {
                    "sub_proof_index": 0,
                    "values": {
                        "iban": {
                            "raw": "FR76300060000112345678901892222",
                            "encoded": "6148709647731321911179338611335436659224044805103852311744105627476491120195"
                        },
                        "bic": {
                            "raw": "AGRIFRPP2222",
                            "encoded": "91116420062241147916189842285176128956310697178501382826806302166580532590101"
                        }
                    }
                }
            },
            "self_attested_attrs": {},
            "unrevealed_attrs": {},
            "predicates": {}
        },
        "identifiers": [
            {
                "schema_id": "M6Mbe3qx7vB4wpZF4sBRjt:2:bank_account:1.0",
                "cred_def_id": "F6dB7dMVHUQSC64qemnBi7:3:CL:571:phil-bank-21",
                "rev_reg_id": "F6dB7dMVHUQSC64qemnBi7:4:F6dB7dMVHUQSC64qemnBi7:3:CL:571:phil-bank-21:CL_ACCUM:f78a6628-57f9-4098-a1de-ecd534a50bb6",
                "timestamp": 1632320402
            }
        ]
    },
```

**Comment by JamesKEbert** [comment]
@etschelp fairly specific question for you--are you specifying a timestamp for the credentials in the requestedCredentials property for creating the Indy Proof `"timestamp": Optional<number>`?
```
{
   "self_attested_attributes": {
      "self_attested_attribute_referent": string
    },
    "requested_attributes": {
      "requested_attribute_referent_1": {"cred_id": string, "timestamp": Optional<number>, revealed: <bool> }},
      "requested_attribute_referent_2": {"cred_id": string, "timestamp": Optional<number>, revealed: <bool> }}
    },
    "requested_predicates": {
      "requested_predicates_referent_1": {"cred_id": string, "timestamp": Optional<number> }},
    }
}
```
In my troubleshooting if this field is not provided & the credential being presented is revocable then no timestamp will be passed in the identifiers of the proof and then additionally ACA-Py will assume the credential is non revocable. Just the absence of the timestamp in the identifiers doesn't appear to be the issue here, more a symptom. I could be missing something here for sure though.

**Comment by ianco** [comment]
Aca-py is dropping revocation constraints for presented credentials that are non-revocable, because indy-sdk will fail validation in this scenario.  However the current logic is not correct ...

**Comment by esune** [comment]
@ianco is this still an open issue, or should we close it now?

**Comment by ianco** [comment]
Should be fixed with https://github.com/hyperledger/aries-cloudagent-python/pull/1465

I'll close it
