### ISSUE TITLE
Implement revocation registry support for credential issuance

### ISSUE THREAD

**Issue by andrewwhitehead** [hyperledger/aries-cloudagent-python#146]
- [x] Generate tails files when revocable credential definitions are created or additional tails files are needed [controller must trigger this]
- [x] Share tails files with a common tails server [controller must perform this]
- [ ] Submit tails metadata to the ledger and update accumulator value when credentials are revoked

**Comment by swcurran** [comment]
Work partially completed and PR #306 put in to capture the work done and listing the work to be done. Medici Ventures is planning on taking over the effort.
