### ISSUE TITLE
Add v2.0 of the Discover Features Protocol - AIP 2.0

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#1466]
Please add the [Discover Feature v2.0](https://github.com/hyperledger/aries-rfcs/tree/b3a3942ef052039e73cd23d847f42947f8287da2/features/0557-discover-features-v2) protocol.  Although AFAIK there is not a big difference between v1.0 and v2.0 versions, we normally copy the current version to create the new version and evolve the new version from there -- retaining support for the new version.

### Notes

- The Admin interface should be more or less the same as the v1.0 version.  Please review the differences in the two versions and decide if there should be a difference.
   - I've not looked into the Admin API for responding to a Discover Protocol request.  In theory, ACA-Py should allow the controller to decide what features to include in the response, so a particular instance can limit what is supported.
   - I'm not sure what is the best way to support the new "features" that can be discovered (e.g. Goal Codes), or how Goal Codes are implemented in ACA-Py.  Some discuss may be needed.
- The prefix for the new version should ALWAYS be "https://didcomm.org", so there is no need to support the old prefix "did:sov:xxxxx" -- although if it easier, there probably is no harm

I suggest that an outline of the new version of the protocol be put into this issue to allow for comments.

Assigned to @shaangill025 to get started.

Thanks

**Comment by shaangill025** [comment]
Looking at the existing `Discover feature v1.0`, there is an endpoint `/features` under `server tag` to query supported features for that agent. So, if Bob (:5002) needs to know about Alice's (:5001) supported protocols, Bob calls this endpoint (:5001) directly (not via Admin API). There are elements like `QueryHandler` and `prepare_disclosed` that are implemented but not used which I think are required for compliance with RFC0031.

**Proposed Changes**
Rename the above endpoint as `discover-features-v1.0/query` and add a `connection_id` query parameter. But now Bob calls this endpoint (Admin API) with the `Bob-Alice connection_id`. This will make use of `DiscloseHandler`, `QueryHandler`, and the response will show the `disclose` message as returned by Alice.

In the case of `Discover Features V2.0`, new endpoint `discover-features-v2.0/query` under `server tag` will be created. the above change will help in supporting proactive disclosure (configured by startup arguments, details below). So, if enabled by Alice, then whenever Bob and Alice connection gets established, Alice proactively discloses protocols and goal codes. 

_startup arguments_
--auto-disclose-protocols
--auto-disclose-goalcodes
Both of these, are used to indicate whether the agent should automatically disclose protocols with or without associated goalcodes when a connection is established.

Another argument, --disclose-protocol-list can be applied to both v1 and v2 and be used to accept a path to YAML configuration file [structure below]. Only these protocols can be shared either automatically or via queries.
```
{
	"protocol_str": ["goal_code", ....]
}
```
Only the disclose (v2) messages recieved by Bob (from Alice proactively) at time of connection establishment needs to be stored. So, `DiscloseMsgRecord(BaseExchangeRecord)` will be created and can be accessed from an endpoint `discover-features-v2.0/disclosures` under `server tag`.


In ACA-Py, I see the following goal codes (all in `endorse_transaction`):
- ENDORSE_TRANSACTION = "transaction.endorse"
- REFUSE_TRANSACTION = "transaction.refuse"
- WRITE_TRANSACTION = "transaction.ledger.write"

These can be defined inside the protocol controller class, they are already registered inside `plugin_registry.py -> load_protocol_version` and then used inside the `ProtocolRegistry` to further filter protocols by goal_code, if specified.

**Comment by shaangill025** [comment]
I will appreciate a clarification on this:
```
"queries": [
    { "feature-type": "protocol", "match": "abc.*" },
    { "feature-type": "goal-code", "match": "aries.*" }
  ]
```
Does this mean:
1. Disclosure contains all protocols matched by `abc.*` and all goal codes matched by `aries.*` found within the filtered protocols matched by `abc.*`?
2. Disclosure contains all protocols matched by `abc.*` and all goal codes matched by `aries.*` evaluated independently?

**Comment by swcurran** [comment]
Thanks for the summary.  Some followup:

- This comment `So, if Bob (:5002) needs to know about Alice's (:5001) supported protocols, Bob calls this endpoint (:5001) directly (not via Admin API).` from your assessment seems really strange.  No Admin API call?  If not -- that definitely needs to be added.  I know the Aries Toolbox uses the Feature Discovery query, so not sure how that works.  Very odd.

- Agree with your plans for V1, as it needs Admin API support.

- Perhaps we need to add a parallel task and implementation of [Goal Codes](https://github.com/hyperledger/aries-rfcs/tree/b3a3942ef052039e73cd23d847f42947f8287da2/concepts/0519-goal-codes) RFC that enables consistent use across protocols, centralized management of the Goal Codes used by the ACA-Py instance and the ability to respond to Discover Feature queries.  I'm not exactly sure what that would be like, so we likely need to discuss.  The list of Goal Codes supported seem small and missing the ones for DID Exchange and Credential Exchange (Issue/Present), so I think there is more to be added.

- Regards question about the meaning of the multiple `queries` entries -- I'm pretty certain they are to be processed independently, but will ask the author to respond -- @dhh1128 .

- Proactive disclosure would be the first message of a protocol and so would follow the `@id` and `~thread` rules -- notably that the first message of a protocol only uses the `@id`, which serves as the `thid` should there be any other messages in the protocol.  Which there won't be... 😄

**Comment by shaangill025** [comment]
> Proactive disclosure would be the first message of a protocol and so would follow the `@id` and `~thread` rules -- notably that the first message of a protocol only uses the `@id`, which serves as the `thid` should there be any other messages in the protocol.  Which there won't be...

Sounds good, maybe this can be indicated inside the `RFC 0557` document, under [disclosure message section](https://github.com/hyperledger/aries-rfcs/tree/main/features/0557-discover-features-v2#disclosures-message-type), that a proactive disclosure message should look like:
```
{
  "@type": "https://didcomm.org/discover-features/2.0/disclosures",
  "@id": "....",
  "disclosures": [
    {"feature-type": "protocol", "id": "https://didcomm.org/tictactoe/1.0"},
    ...
  ]
}
```

**Comment by shaangill025** [comment]
> Perhaps we need to add a parallel task and implementation of [Goal Codes](https://github.com/hyperledger/aries-rfcs/tree/b3a3942ef052039e73cd23d847f42947f8287da2/concepts/0519-goal-codes) RFC that enables consistent use across protocols, centralized management of the Goal Codes used by the ACA-Py instance and the ability to respond to Discover Feature queries.  I'm not exactly sure what that would be like, so we likely need to discuss.  The list of Goal Codes supported seem small and missing the ones for DID Exchange and Credential Exchange (Issue/Present), so I think there is more to be added.

Sounds good, from an implementation point of view (after a second thought), defining of `goal_code` should happen in `controller` for applicable protocols and then we implement a `GoalCodeRegistry` on the lines of `ProtocolRegistry` to support `goal_code_matching_query` and `register_goal_codes` functions. I will need a central registry or list of `goal_code` for ACA-Py to support to proceed in this aspect.
