### ISSUE TITLE
Acme Controller Workshop: Unclear instructions for issuing work credential

### ISSUE THREAD

**Issue by estrehle** [hyperledger/aries-cloudagent-python#1477]
I am working through the Acme Controller Workshop. First: A big thanks to everyone who contributed! I find it very easy to follow and I am learning a lot along the way.

One step left me scratching my head, though. In Section "Issuing Alice a Work Credential", what should I do with this piece of code?
``` python
        with log_timer("Publish schema and cred def duration:"):
            # define schema
            version = format(
                "%d.%d.%d"
                % (
                    random.randint(1, 101),
                    random.randint(1, 101),
                    random.randint(1, 101),
                )
            )
            # (schema_id, cred_def_id) = await agent.register_schema_and_creddef(
                "employee id schema",
                version,
                ["employee_id", "name", "date", "position"],
                support_revocation=False,
                revocation_registry_size=TAILS_FILE_COUNT,
            )
```
Should I copy-paste this? Where?

**Comment by ianco** [comment]
Hi @estrehle I think that is old code, I'll remove it from the instructions.

**Comment by estrehle** [comment]
@ianco Thanks for getting back! I played around a bit and found out that I actually need to copy-paste this code right after the previous code bit. Otherwise we're missing a definition for `schema_id` and `cred_def_id` which are used later. I'll suggest a fix and create a PR.
