### ISSUE TITLE
/present-proof/send-request 403 error

### ISSUE THREAD

**Issue by teyahdavis** [hyperledger/aries-cloudagent-python#1479]
Hi, I'm running agents in v.0.7.1 on an Azure VM, connected to Sovrin's BuilderNet.

Trying to call /present-proof/send-request on my verifier agent with body:
```
{
  "comment": "string",
  "connection_id": "cb679c76-467e-4580-af3b-a6299a150d7d",
  "proof_request": {
    "name": "Proof request",
    "non_revoked": {
      "to": 1636105797
    },
    "nonce": "1234567890",
    "requested_attributes": {
      "additionalProp1": {
        "name": "org"
      }
    },
    "requested_predicates": {
      "additionalProp2": {
        "name": "age",
        "p_type": ">=",
        "p_value": 10,
        "restrictions": [
          {}
        ]
      }
    },
    "version": "1.0"
  },
  "trace": false
}
```
 
But got a **403: Connection c5cd3e9b-31c6-4a12-aa5d-a387f5520c55 not ready** error in Postman, and **aries_cloudagent.core.conductor WARNING Cannot queue message for delivery, no supported transport in CLI**, could anyone support with this please?

For context, the same body was used successfully in the exact same setup except using a local VON-Network.

**Comment by ianco** [comment]
Hi @teyahdavis , this error could be caused by lots of factors.  There could be connection issues between aca-py and the ledger, could be a TAA issue (I think with buildernet you have to accept TAA but not with a local VON network), or "other".

Check the aca-py log files for any error messages, there could be an error during the startup/initialization which is affecting this operation

**Comment by teyahdavis** [comment]
Thanks @ianco !

In my verifier aca-py logs, i'm just seeing:
```
2021-11-09 11:59:21,442 aries_cloudagent.admin.server ERROR Handler error with exception: Connection 78c62e39-d922-4216-9455-00ef46d23723 not ready

=================
Traceback (most recent call last):
  File "/home/indy/aries_cloudagent/admin/server.py", line 162, in ready_middleware
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 199, in debug_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/indy/aries_cloudagent/admin/server.py", line 366, in setup_context
    return await task
  File "/home/indy/aries_cloudagent/protocols/present_proof/v1_0/routes.py", line 540, in presentation_exchange_send_free_request
    raise web.HTTPForbidden(reason=f"Connection {connection_id} not ready")
aiohttp.web_exceptions.HTTPForbidden: Connection 78c62e39-d922-4216-9455-00ef46d23723 not ready
2021-11-09 11:59:21,444 aiohttp.access INFO 82.23.255.169 [09/Nov/2021:11:59:21 +0000] "POST /present-proof/send-request HTTP/1.1" 403 274 "-" "PostmanRuntime/7.28.4"
```

and there don't seem to be any problems with the startup - it seems like the problem is with the verifier agent because my issuer and holder were able to communicate and issue/store a credential etc.

**Comment by ianco** [comment]
It looks like the connection between your verifier and holder/prover isn't in active state.  Try the `/connections` endpoint and see what state your connection is in

**Comment by teyahdavis** [comment]
when my verifier creates a connection request and my holder receives it, the state I can see is: request

generally I don't have to do anything other than receive it for it to be active?

**Comment by ianco** [comment]
On the verifier side, you are creating an invitation.  On the holder side, you have to receive and then request the connection.  And then on the verifier side you have accept the connection request.  (There is another "acknowledge connection" step but this one is optional and not properly specified in the RFC)

Depending on what "auto" flags you specify on aca-py startup, some of these steps may happen automatically.

So, check the startup parameters on each of your aca-py instances, you may have auto flags set on one but not another, and this would mean you need a different set of manual steps to get the connections setup between different agents.

**Comment by teyahdavis** [comment]
each of my agents have --auto-accept-invites \ --auto-accept-requests \ flags, is there something else it might be?

**Comment by ianco** [comment]
These should work, what do you get from the `/connections` endpoint?

**Comment by teyahdavis** [comment]
verifier:
```
{
            "invitation_key": "6fRr85NVxdufZ5XAcXyhVRGYvBDuizoYp6brFztGwUnH",
            "created_at": "2021-11-09 16:35:51.537150Z",
            "accept": "auto",
            "updated_at": "2021-11-09 16:35:51.537150Z",
            "connection_id": "867add77-1773-44cf-8c46-14fa6fa5bf77",
            "their_role": "invitee",
            "routing_state": "none",
            "invitation_mode": "once",
            "rfc23_state": "invitation-sent",
            "connection_protocol": "connections/1.0",
            "state": "invitation"
        }
```

holder:
```
{
            "invitation_key": "6fRr85NVxdufZ5XAcXyhVRGYvBDuizoYp6brFztGwUnH",
            "created_at": "2021-11-09 16:36:03.484147Z",
            "request_id": "5a8f3a02-0c5b-49a4-8c93-a560c8450a7d",
            "their_label": "Buyer",
            "state": "request",
            "connection_protocol": "connections/1.0",
            "invitation_msg_id": "1b60baaa-ae74-4d7d-b7eb-1f9b517936ce",
            "updated_at": "2021-11-09 16:36:03.540631Z",
            "their_role": "inviter",
            "accept": "auto",
            "my_did": "3W2PXB2iP3r98W7SDv6XdM",
            "routing_state": "none",
            "connection_id": "3a287f56-8346-48b1-8b2e-1605b63c6604",
            "rfc23_state": "request-sent",
            "invitation_mode": "once"
        }
```

**Comment by ianco** [comment]
Looks like the holder has sent the connection request, but the verifier hasn't received it (status is still `invitation`)

Possibly the invitation is getting sent with the wrong endpoint?  (should be the endpoint of the verifier)   In which case the holder thinks they've sent the connection request but it never made it to the verifier

**Comment by teyahdavis** [comment]
the steps I'm taking to make the connection are:
**verifier** - /connections/create-invitation
**holder** - /connections/receive-invitation

I'm copying the invitation {} body from the response from the verifier and literally just sending it in the holder receive invitation.

I've double-checked the endpoints and they seem to be correct, just confused as this is what I've done for the issuer and holder and that worked as expected?

also thank you so much, I appreciate your help!

**Comment by ianco** [comment]
If the holder isn't able to connect to the issuer I'd expect some kind of error message in the log file.

Can you past the "banner" that's displayed on startup from each agent, as well as the contents of your invitation?

**Comment by teyahdavis** [comment]
invite contents:
```
{
        "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/invitation",
        "@id": "1644b969-a897-473e-9988-fbbdbf188d21",
        "serviceEndpoint": "http://51.132.141.111:8000/",
        "label": "Buyer",
        "recipientKeys": [
            "6rzyWQudN5y9vTK46zbREN6Xay3KQPCDP5SFPjGewrdW"
        ]
    }
```

by banner do you mean 
![image](https://user-images.githubusercontent.com/74596899/140982427-5be68c56-8a63-466d-aa2d-69713bbed832.png)
or something else?

**Comment by teyahdavis** [comment]
wait I've found the problem, it was a copy/paste mistake in the verifier's startup command!

**Comment by ianco** [comment]
Aha!  Good work!
