### ISSUE TITLE
--pool-name broken in 0.3.1

### ISSUE THREAD

**Issue by SmithSamuelM** [hyperledger/aries-cloudagent-python#148]
Running the ace-py version 0.3.1 tag objects to the --pool-name option.  This worked in 0.2.1.
The docs say --pool-name but looks like the actual option is
--ledger-pool-name

Need to fix the docs  (Dev Read Me)

**Comment by swcurran** [comment]
Documentation for the command line options is now part of the executable. Docs have been updated to remove the command line parameters and replaced with instructions on how to run an executable to get them.

Check --help for the latest.
