### ISSUE TITLE
Credential definition not in wallet

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#1480]
Hello,

I'm running an ACA-Py agent (**V0.6.0** and using **SQLite** as the default wallet) in my AWS ECS cluster, which connects to the Sovrin's BuilderNet. I can create a credential schema successfully, but when I tried to create a credential definition, I've got the below error.

`400: Credential definition PK6fouNGpMe6FBzK2pfrGn:3:CL:6927:passport is on ledger default but not in wallet AuthorityWallet`

Could anyone tell me what could be the root cause here? Thanks!

**Comment by WadeBarnes** [comment]
The credential definition has been written to the ledger but it does not exist in your wallet.  This can happen if you have been testing with the same schema version and already written the data to the ledger and now you are trying to do the same with another instance of the agent using the same DID and Verkey, or you deleted the wallet at some point after creating the transactions on the ledger.  Either way your agent's wallet does not contain the credential definition, but it exists on the ledger already.  You can try incrementing the schema version and restarting your agent.  That way the agent will write the schema and cred def with the new version info.

**Comment by yunxi-zhang** [comment]
Thanks for the clarification @WadeBarnes. Postgres is the target DB I'll use, just using the SQLite for testing purpose. This issue is gone after my ACA-Py can connect to Sovrin's BuilderNet properly and accepted the TAA.
