### ISSUE TITLE
Proof requests without the "is_holder" constraint conclude in invalid proof validation

### ISSUE THREAD

**Issue by acuderman** [hyperledger/aries-cloudagent-python#1486]
When the proof request doesn't include the `is_holder` constraint, the verifier responds with `verified: false`, but It should respond with true. The same thing happens if the directive is "preferred" instead of "required".

### Reproduction steps:
- Remove [is_holder constraint](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/runners/faber.py#L331) or change the directive to `preferred`
- Run demo agents:
```
./run_demo faber --did-exchange --cred-type json-ld --wallet-type askar
./run_demo alice --wallet-type askar
```
- Issue credential and send proof request
- Observe that the Faber agent logs `Proof = False`

**Comment by shaangill025** [comment]
@acuderman Can you test the requested updates [in PR #1493]?

**Comment by acuderman** [comment]
@shaangill025 Thanks for the update. It works now if the holder sets `holder_did` when creating the credential request, but doesn't otherwise.

### Reproduction steps:
- Remove [is_holder constraint](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/runners/faber.py#L331) constraint 
- Replace [this line](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/runners/agent_container.py#L235) with `data = {}`
- Run demo agents and go through the flow
- Faber agent logs Proof = False while It should be true

**Comment by shaangill025** [comment]
> Thanks for the update. It works now if the holder sets `holder_did` when creating the credential request, but doesn't otherwise.

This is expected, if there is no `holder_did` set or `$.credentialSubject.id` for the credential, then the presentation is not signed as it will not be possible to verify this. 

If you would still like to sign such a presentation then you will have to specify the `signing DID` in the request body (example below) for `/present-proof-2.0/records/{pres_ex_id}/send-presentation` endpoint.
```
"dif": {
    "issuer_id": "string"
}
```

**Comment by acuderman** [comment]
Okay, thanks for the explanation. In this case, looks good.
