### ISSUE TITLE
ACA-Py returns 200 with "schema": null when no schema found

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1487]
When a schema is not found when calling the `/schemas/{schema_id}` endpoint, ACA-Py returns the following json with a `200` response code.

```json
{
  "schema": null
}
```

Shouldn't this return a `404` error? Or is this on purpose? Not sure how things not found on the ledger should be processed

**Comment by swcurran** [comment]
@ianco @andrewwhitehead  -- could you please weigh in on this?  Should we change ACA-Py for this case?  

Or should we just close this issue as a ¯\\\_(ツ)_/¯?

**Comment by ianco** [comment]
I think it makes sense to return a `404`
