### ISSUE TITLE
Multitenancy: Unauthorized error on restart

### ISSUE THREAD

**Issue by a1s-tech** [hyperledger/aries-cloudagent-python#1495]
When restarting the agent, all calls related to an existing wallet fail. This is the log:

```
aries_cloudagent.admin.server ERROR Handler error with exception: Unauthorized
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 341, in setup_context
    self.context, token
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/multitenant/manager.py", line 415, in get_profile_for_token
    wallet = await WalletRecord.retrieve_by_id(session, wallet_id)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/messaging/models/base_record.py", line 233, in retrieve_by_id
    cls.RECORD_TYPE, record_id, {"retrieveTags": False}
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/storage/in_memory.py", line 74, in get_record
    raise StorageNotFoundError("Record not found: {}".format(record_id))
aries_cloudagent.storage.error.StorageNotFoundError: Record not found: 80592095-a5f2-436d-b981-8e225331370a

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 162, in ready_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 199, in debug_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 290, in check_token
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 322, in check_multitenant_authorization
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 346, in setup_context
    raise web.HTTPUnauthorized()
aiohttp.web_exceptions.HTTPUnauthorized: Unauthorized
```
In the current setup I am using `bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1` with `postgres:13` and the following config:

```
admin-api-key: ...
admin: [0.0.0.0, 8031]
label: ...
webhook-url: http://...
genesis-url: http://.../genesis

inbound-transport:
  - [http, 0.0.0.0, 8030]
  - [ws, 0.0.0.0, 8040]
outbound-transport: http
endpoint: http://...:8030
auto-ping-connection: true
multitenant: true
multitenant-admin: true
jwt-secret: ...
wallet-key: someKey...
wallet-storage-type: postgres_storage
wallet-storage-config: '{"url":"postgres-host:5432","wallet_scheme":"MultiWalletSingleTable"}'
wallet-storage-creds: '{"account":"postgres","password":"...","admin_account":"postgres","admin_password":"..."}'
auto-provision: true
seed: someSeed--000000000-000000000-00
```
All operations work just fine with a running agent: creating wallets, invitations, relationships, credentials, etc.
However, once the agent is restarted, it doesn't recognize existing wallets (although they exist in the database) and all operations on these wallets fail.

**Comment by TimoGlastra** [comment]
Not sure if this has something to do with It, but you're not setting the `wallet-type` property. If not set ACA-Py will default to the `in_memory` wallet, which loses all data after a restart. However as you say the wallets exist in the database I'm not sure if this could be it

**Comment by ianco** [comment]
Not able to reproduce.  I started an aca-py agent in multitenant mode, created a sub-wallet, tested access to the sub-wallet using the swagger page (authenticate using bearer token)

Then I restarted the agent, re-authenticated and was able to access the wallet again.

I used an external postgres database to store wallets (left this running while I restarted the aca-py agent)

@a1s-tech I can share some of my config if you're interested

**Comment by a1s-tech** [comment]
@TimoGlastra I will check the `wallet-type` property; indeed, the error seems to come from `in_memory.get_record`. 
Thanks for the suggestion!

**Comment by a1s-tech** [comment]
@ianco yes, please share. Much appreciated.

**Comment by ianco** [comment]
See the following two files (renamed to `*.txt` to satisfy github):

[postgres-indy-args-local.yml.txt](https://github.com/hyperledger/aries-cloudagent-python/files/7549699/postgres-indy-args-local.yml.txt)
[faber-local-multitenant.sh.txt](https://github.com/hyperledger/aries-cloudagent-python/files/7549700/faber-local-multitenant.sh.txt)

1. run a local von-network (`./manage start 192.168.0.11 --logs`, your IP will differ)
2. run a local postgres (the command is in the yml file included above)
3. (optionally) run a tails server if you are going to be revoking credentials
4. Run the agent using the above .sh script

Once the agent is running:
1. Open the swagger page in a browser `http://localhost:8021`
2. Create a new sub-wallet - remember the token
3. authenticate the swagger page using `Bearer <your sub-wallet token>`
4. you can now call admin endpoints for your sub-wallet
5. re-start your aca-py agent (<ctrl-c> to kill it and then run the .sh script again)
6. You will need to re-authenticate with your bearer token again
7. call the admin endpoints for your subwallet

**Comment by a1s-tech** [comment]
@ianco Your example worked as expected.
In my setup I added `wallet-type: indy` and removed `seed` (this combination generated other errors). Now all is good.

Thank you @TimoGlastra  & @ianco for your assistance.
