### ISSUE TITLE
error: [Errno 36] File name too long when installing aca-py 0.7.X

### ISSUE THREAD

**Issue by santidediego** [hyperledger/aries-cloudagent-python#1497]
When installing **aca-py 0.7.X** both with _pip_ and _python setup.py install_, I got an error:

`error: [Errno 36] File name too long: 'build/bdist.linux-x86_64/egg/aries_cloudagent/vc/tests/dids/__pycache__/did_zUC72Q7XD4PE4CrMiDVXuvZng3sBvMmaGgNeTUJuzavH2BS7ThbHL9FhsZM9QYY5fqAQ4MB8M9oudz3tfuaX36Ajr97QRW7L`

Same commands work for me in **aca-py 0.6.X**

**Comment by swcurran** [comment]
@shaangill025 -- can you please take a look at this?  Anything we can do for that?

**Comment by shaangill025** [comment]
On my end, I tried with `Windows with pip 20.3.3`, `Ubuntu with pip 9.0.1` and `Mac with pip 21.3.1` and `aries-cloudagent-0.7.2` installed successfully with no errors.

**Comment by santidediego** [comment]
Solved by upgrading _pip_. Thanks
