### ISSUE TITLE
Update outbound queue docs

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#1502]
The outbound queue implementation and documentation have grown out of sync. The Documentation should be updated to reflect the current implementation.

**Comment by swcurran** [comment]
@dbluhm @shaangill025 -- reminder about this one.  Is there still a need to update the docs?

**Comment by dbluhm** [comment]
@shaangill025 added some docs in the PR  he opened up. Assuming those docs will make a comeback lol I think this issue will be resolved with those docs.
