### ISSUE TITLE
Schema/Credential Definition Error - Multi Tenancy Enabled

### ISSUE THREAD

**Issue by teyahdavis** [hyperledger/aries-cloudagent-python#1505]
Hi, I'm running 4 agents in v.0.6.0 with a Local Von-Network on an Azure VM.

I've used an Endorser agent to publish the DID of the Issuer agent's subwallet to the ledger, and when using the Bearer token, the Issuer is able to successfully establish a connection with my Holder agent, however, when I try to create a Credential Definition (from the Issuer agent) I'm getting the following errors:
```
400: Ledger default has no schema YMvx9U8XNpN3CsKVSF6FPw:2:issuerschema:0.1
```

The steps I'm taking are below:

1. **Issuer** `/multitenancy/wallet` POST with body:
```
{
  "key_management_mode": "managed",
  "label": "Authority",
  "wallet_key": "secret",
  "wallet_name": "AuthorityWallet",
  "wallet_type": "indy"
}
```
2. **Issuer** `/wallet/did/create`  POST with empty body
3. **Endorser** `/ledger/register-nym` POST with params:
```
did=<did from response body of step 2>
verkey=<verkey from response body of step 2>
```
4. **Issuer** `/wallet/did/public` POST with params:
```
did=<did from response body of step 2>
```
5. **Issuer** `/wallet/did/` GET

All of the steps after 1 on the Issuers side are authorized with the bearer token, I would appreciate some help with this, thank you!

**Comment by ianco** [comment]
@teyahdavis  Can you list the steps you use to create the credential definition?  Remember you need to create a schema first (or use a schema that is already created on the ledger)

**Comment by teyahdavis** [comment]
Sure, I created schema by:

1. **Issuer** `/schemas` POST with body:
```
{
    "attributes": ["org", "name", "age"],
    "schema_name": "issuerschema",
    "schema_version": "0.1"
}
``` 
Response was:
```
{
    "schema_id": "YMvx9U8XNpN3CsKVSF6FPw:2:issuerschema:0.1",
    "schema": {
        "ver": "1.0",
        "id": "YMvx9U8XNpN3CsKVSF6FPw:2:issuerschema:0.1",
        "name": "issuerschema",
        "version": "0.1",
        "attrNames": [
            "org",
            "age",
            "name"
        ],
        "seqNo": null
    }
}
```

**Comment by teyahdavis** [comment]
Then credential definition request was `/credential-definitions` POST with body:
```
{
    "revocation_registry_size": 1000,
    "schema_id": "YMvx9U8XNpN3CsKVSF6FPw:2:issuerschema:0.1",
    "support_revocation": true,
    "tag": "issuerschema"
}
```

**Comment by ianco** [comment]
Hi @teyahdavis , I tried creating a schema/cred def based on your templates and everything worked for me:

- started a local von network and tails server
- started an agent using the faber demo (`./run demo faber --revocation --multitenant`)
- using the swagger page `http://localhost:8021` created a sub-wallet and then authenticated using that bearer token
- created a new local DID, published to ledger (I used Endorser role) and made this the wallet's public DID
- created a schema using your template
- created a cred def using your template

Can you attach a log file from your agent (restart to start with a clean config) from the full sequence (use `--log-level debug`) so I can see what's happening in your installation?

**Comment by swcurran** [comment]
This was likely a local setup issue. Closing.
