### ISSUE TITLE
Cache module for aca-py

### ISSUE THREAD

**Issue by sukalpomitra** [hyperledger/aries-cloudagent-python#151]
Is there a cachin g module in aca-py? If yes how to activate it? So that we can cache the ledger and the presentation exchange operation can be made faster?

**Comment by nrempel** [comment]
Hi @sukalpomitra,

There is a cache module available. Currently there is only an in-memory implementation of it.

You can see an example of its use here: https://github.com/hyperledger/aries-cloudagent-python/blob/cae81410ee25a1b9b0a3276425114bb4d9dc4cef/aries_cloudagent/messaging/credentials/manager.py#L57

**Comment by swcurran** [comment]
Closing this issue.  Please reopen if there are other specific questions.
