### ISSUE TITLE
OOB invitation not deleted when using `use_existing_connection`

### ISSUE THREAD

**Issue by ffendt** [hyperledger/aries-cloudagent-python#1511]
When having an active connection between two agents and using the `use_existing_connection` flag when receiving another invitation from the inviter using the Out-Of-Band protocol, the invitation doesn't get deleted at the inviter. I would expect the invitation to be deleted in the database of the inviter.

Steps to reproduce (which will hopefully make my very long sentence above more understandable):
* Create an OOB invitation at the inviter
* Receive the invitation at invitee
* Continue to establish the connection until it's active (I had `auto_accept=true` on both agents)
* Create another OOB invitation at the inviter
* Receive the invitation at invitee with flag `use_existing_connection=true`
* invitee immediately get's back the previously created and still active connection
* The invitation remains in the database of the inviter. There are two connections when querying the `/connections` endpoint: one is the still active connection, one is the invitation pending in state `invitation`

Is it expected that the invitation will remain at the inviter? In my opinion, this will pollute the database with already used invitations.

**Comment by shaangill025** [comment]
@ffendt PR #1521 (more details), deletes stale `ConnRecords` which were last updated at least 3 hours back. The trigger for this  is creating an OOB invitation, so whenever a new OOB invitation is created then this cleanup is performed. Does this strategy sound reasonable?

**Comment by ffendt** [comment]
@shaangill025, thanks for the quick PR. I'll close this issue for now.
