### ISSUE TITLE
Corrupted input (present-proof request) breaks the output API (present proof records)

### ISSUE THREAD

**Issue by DennisVonDerBey** [hyperledger/aries-cloudagent-python#1512]
We just noticed while testing out the Askar wallet type with BBS+ activated, that corrupted input on the `/present-proof-2.0/send-request` endpoint can break the `/present-proof-2.0/records` API endpoint.

`/present-proof-2.0/send-request'
Request Payload:
```
{
  "comment": "string",
  "connection_id": "3b5b30f4-6289-4814-88ae-ac8dd1f03fc5",
  "presentation_request": {
    "dif": {
      **"_schema": [{
        "uri": "https://www.w3.org/2018/credentials/#VerifiableCredential"
      }],**
      "presentation_definition": {
        "format": {
          "ldp_vp": {
            "proof_type": "BbsBlsSignature2020"
          }
        },
        "id": "fa2c4a76-c7bd-4313-a0f8-d9f5979c1fd2",
        "input_descriptors": [{
          "schema": [{
              "uri": "https://www.w3.org/2018/credentials/#VerifiableCredential"
            }
          ],
          "constraints": {
            "fields": [{
                "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                "path": ["$.credentialSubject.id"]
              }
            ],
            "is_holder": [{
              "directive": "required",
              "field_id": [
                "3fa85f64-5717-4562-b3fc-2c963f66afa6"
              ]
            }],
            "limit_disclosure": "required"
          },
          "id": "XXXXXXX",
          "name": "XXXXXXX"
        }]
      }
    }
  }
}
```

Don't ask me how the `_schema` ended up in there, that's a fail on our side. But if you send this request and then fetch the records:

`/present-proof-2.0/records`:
Return code: `400 Error: Bad Request`
Return body:
```
400: V20PresRequest schema validation failed. {'_schema`: ['Unknown field.']}.
```

It looks like there is some validation happening that should normally be applied upon user input when fetching data from the persistence. This locks up the endpoint for the whole instance.

Image used: `bcgovimages/aries-cloudagent:py36-1.16-1_0.7.2-rc0`

**Comment by shaangill025** [comment]
@DennisVonDerBey I will appreciate it if you can give this a quick test.
