### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'notify'

### ISSUE THREAD

**Issue by edbkei** [hyperledger/aries-cloudagent-python#1522]
This happens in a VM (Ubuntu 20.04.3 LTS) in a platform provided by Google Cloud. This is a very fresh implementation after new git clone on von-network and aries-cloudagent-python. Then, running ./run_demo faber, this happens:

eduardo@eduardoito:~/aries/aries-cloudagent-python/demo$ ./run_demo faber
Preparing agent image...
sha256:739adae5f285d5e9ed031fd83efe7d97df17d08588bb2ec99bf572d069903ea3
Trying to detect ngrok service endpoint
jq not found
x.x.x.x
Starting [faber] agent with args [--port 8020]
Initializing demo agent faber with AIP 20 and credential type indy
Setting use_did_exchange: True

#1 Provision an agent and wallet, get back configuration details
Started webhook listener on port: 8022
Faber      | Registering faber.agent ...
Faber      | nym_info: {'did': 'ELoxNnY1VbJLcTcYWs3cmL', 'seed': 'd_000000000000000000000000392955', 'verkey': '8GkeTXkVFYfxZKDcX9RzFakQSksVeS8swBZd2rUcaMKG'}
Faber      | Registered DID: ELoxNnY1VbJLcTcYWs3cmL
Created public DID
Faber      | ['/home/indy/.pyenv/versions/3.6.13/bin/python', '-m', 'aries_cloudagent', 'start', '--endpoint', 'http://x.x.x.x:8020', '--label', 'faber.agent', '--auto-ping-connection', '--auto-respond-messages', '--inbound-transport', 'http', '0.0.0.0', '8020', '--outbound-transport', 'http', '--admin', '0.0.0.0', '8021', '--admin-insecure-mode', '--wallet-type', 'indy', '--wallet-name', 'faber.agent392955', '--wallet-key', 'faber.agent392955', '--preserve-exchange-records', '--auto-provision', '--emit-new-didcomm-prefix', '--genesis-transactions', '{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node1","blskey":"4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSEimFF6nsQ6M41QvhM2Z33nves5vfSn9n1UwNFJBYtWVnHYMATn76vLuL3zU88KyeAYcHfsih3He6UHcXDxcaecHVz6jhCYz1P2UZn2bDVruL5wXpehgBfBaLKm3Ba","blskey_pop":"RahHYiCvoNCtPTrVtP7nMC5eTYrsUA8WjXbdhNc8debh1agE9bGiJxWBXYNFbnJXoXhWFMvyqhqhRoq737YQemH5ik9oL7R4NTTCz2LEZhkgLJzB3QRQqJyBNyv7acbdHrAT8nQ9UkLbaVL9NBpnWXBTw4LEMePaSHEw66RzPNdAX1","client_ip":"x.x.x.x","client_port":9702,"node_ip":"10.128.0.2","node_port":9701,"services":["VALIDATOR"]},"dest":"Gw6pDLhcBcoQesN72qfotTgFa7cbuqZpkX3Xo6pLhPhv"},"metadata":{"from":"Th7MpTaRZVRYnPiabds81Y"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"fea82e10e894419fe2bea7d96296a6d46f50f93f9eeda954ec461b2ed2950b62"},"ver":"1"}\n{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node2","blskey":"37rAPpXVoxzKhz7d9gkUe52XuXryuLXoM6P6LbWDB7LSbG62Lsb33sfG7zqS8TK1MXwuCHj1FKNzVpsnafmqLG1vXN88rt38mNFs9TENzm4QHdBzsvCuoBnPH7rpYYDo9DZNJePaDvRvqJKByCabubJz3XXKbEeshzpz4Ma5QYpJqjk","blskey_pop":"Qr658mWZ2YC8JXGXwMDQTzuZCWF7NK9EwxphGmcBvCh6ybUuLxbG65nsX4JvD4SPNtkJ2w9ug1yLTj6fgmuDg41TgECXjLCij3RMsV8CwewBVgVN67wsA45DFWvqvLtu4rjNnE9JbdFTc1Z4WCPA3Xan44K1HoHAq9EVeaRYs8zoF5","client_ip":"10.128.0.2","client_port":9704,"node_ip":"10.128.0.2","node_port":9703,"services":["VALIDATOR"]},"dest":"8ECVSk179mjsjKRLWiQtssMLgp6EPhWXtaYyStWPSGAb"},"metadata":{"from":"EbP4aYNeTHL6q385GuVpRV"},"type":"0"},"txnMetadata":{"seqNo":2,"txnId":"1ac8aece2a18ced660fef8694b61aac3af08ba875ce3026a160acbc3a3af35fc"},"ver":"1"}\n{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node3","blskey":"3WFpdbg7C5cnLYZwFZevJqhubkFALBfCBBok15GdrKMUhUjGsk3jV6QKj6MZgEubF7oqCafxNdkm7eswgA4sdKTRc82tLGzZBd6vNqU8dupzup6uYUf32KTHTPQbuUM8Yk4QFXjEf2Usu2TJcNkdgpyeUSX42u5LqdDDpNSWUK5deC5","blskey_pop":"QwDeb2CkNSx6r8QC8vGQK3GRv7Yndn84TGNijX8YXHPiagXajyfTjoR87rXUu4G4QLk2cF8NNyqWiYMus1623dELWwx57rLCFqGh7N4ZRbGDRP4fnVcaKg1BcUxQ866Ven4gw8y4N56S5HzxXNBZtLYmhGHvDtk6PFkFwCvxYrNYjh","client_ip":"10.128.0.2","client_port":9706,"node_ip":"x.x.x.x","node_port":9705,"services":["VALIDATOR"]},"dest":"DKVxG2fXXTU8yT5N7hGEbXB3dfdAnYv1JczDUHpmDxya"},"metadata":{"from":"4cU41vWW82ArfxJxHkzXPG"},"type":"0"},"txnMetadata":{"seqNo":3,"txnId":"7e9f355dffa78ed24668f0e0e369fd8c224076571c51e2ea8be5f26479edebe4"},"ver":"1"}\n{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node4","blskey":"2zN3bHM1m4rLz54MJHYSwvqzPchYp8jkHswveCLAEJVcX6Mm1wHQD1SkPYMzUDTZvWvhuE6VNAkK3KxVeEmsanSmvjVkReDeBEMxeDaayjcZjFGPydyey1qxBHmTvAnBKoPydvuTAqx5f7YNNRAdeLmUi99gERUU7TD8KfAa6MpQ9bw","blskey_pop":"RPLagxaR5xdimFzwmzYnz4ZhWtYQEj8iR5ZU53T2gitPCyCHQneUn2Huc4oeLd2B2HzkGnjAff4hWTJT6C7qHYB1Mv2wU5iHHGFWkhnTX9WsEAbunJCV2qcaXScKj4tTfvdDKfLiVuU2av6hbsMztirRze7LvYBkRHV3tGwyCptsrP","client_ip":"10.128.0.2","client_port":9708,"node_ip":"10.128.0.2","node_port":9707,"services":["VALIDATOR"]},"dest":"4PS3EDQ3dW1tci1Bp6543CfuuebjFrg36kLAUcskGfaA"},"metadata":{"from":"TWwCRQRZ2ZHMJFn9TzLp7W"},"type":"0"},"txnMetadata":{"seqNo":4,"txnId":"aa5e817d7cc626170eca175822029339a444eb0ee8f0bd20d3b0b76e566fb008"},"ver":"1"}\n', '--seed', 'd_000000000000000000000000392955', '--webhook-url', 'http://x.x.x.x:8022/webhooks', '--trace-target', 'log', '--trace-tag', 'acapy.events', '--trace-label', 'faber.agent.trace', '--auto-accept-invites', '--auto-accept-requests', '--auto-store-credential']
Shutting down agent ...
Faber      |
Faber      | Shutting down
Faber      | 2021-11-26 15:45:10,366 asyncio ERROR Task exception was never retrieved
Faber      | future: <Task finished coro=<run_loop.<locals>.done() done, defined at /home/indy/aries_cloudagent/commands/start.py:77> exception=AttributeError("'NoneType' object has no attribute 'notify'",)>
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/commands/start.py", line 79, in done
Faber      |     await shutdown
Faber      |   File "/home/indy/aries_cloudagent/commands/start.py", line 35, in shutdown_app
Faber      |     await conductor.stop()
Faber      |   File "/home/indy/aries_cloudagent/core/conductor.py", line 373, in stop
Faber      | Process did not terminate in time
Faber      |     await self.root_profile.notify(SHUTDOWN_EVENT_TOPIC, {})
ERROR:runners.agent_container:Error terminating agent:
Traceback (most recent call last):
  File "/home/indy/demo/runners/faber.py", line 417, in main
    else False,
  File "/home/indy/demo/runners/agent_container.py", line 678, in initialize
    await self.agent.start_process()
  File "/home/indy/demo/runners/support/agent.py", line 657, in start_process
    await self.detect_process()
  File "/home/indy/demo/runners/support/agent.py", line 996, in detect_process
    + f"Admin URL: {status_url}"
Exception: Timed out waiting for agent process to start (status=None). Admin URL: http://10.128.0.2:8021/status

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/indy/demo/runners/agent_container.py", line 881, in terminate
    await self.agent.terminate()
  File "/home/indy/demo/runners/support/agent.py", line 681, in terminate
    result = await asyncio.wait_for(future, 10, loop=loop)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/indy/demo/runners/support/agent.py", line 668, in _terminate
    raise Exception(msg)
Exception: Process did not terminate in time
Faber      | AttributeError: 'NoneType' object has no attribute 'notify'
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/indy/demo/runners/faber.py", line 765, in <module>
    asyncio.get_event_loop().run_until_complete(main(args))
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/home/indy/demo/runners/faber.py", line 417, in main
    else False,
  File "/home/indy/demo/runners/agent_container.py", line 678, in initialize
    await self.agent.start_process()
  File "/home/indy/demo/runners/support/agent.py", line 657, in start_process
    await self.detect_process()
  File "/home/indy/demo/runners/support/agent.py", line 996, in detect_process
    + f"Admin URL: {status_url}"
Exception: Timed out waiting for agent process to start (status=None). Admin URL: http://xx.xx.x.x:8021/status
Faber      |
Faber      | ::::::::::::::::::::::::::::::::::::::::::::::
Faber      | :: faber.agent                              ::
Faber      | ::                                          ::
Faber      | ::                                          ::
Faber      | :: Inbound Transports:                      ::
Faber      | ::                                          ::
Faber      | ::   - http://0.0.0.0:8020                  ::
Faber      | ::                                          ::
Faber      | :: Outbound Transports:                     ::
Faber      | ::                                          ::
Faber      | ::   - http                                 ::
Faber      | ::   - https                                ::
Faber      | ::                                          ::
Faber      | :: Public DID Information:                  ::
Faber      | ::                                          ::
Faber      | ::   - DID: ELoxNnY1VbJLcTcYWs3cmL          ::
Faber      | ::                                          ::
Faber      | :: Administration API:                      ::
Faber      | ::                                          ::
Faber      | ::   - http://0.0.0.0:8021                  ::
Faber      | ::                                          ::
Faber      | ::                               ver: 0.7.2 ::
Faber      | ::::::::::::::::::::::::::::::::::::::::::::::
Faber      |
Faber      | Listening...
Faber      |

**Comment by ianco** [comment]
Are you using "x.x.x.x" as an IP or are you redacting your log file?

**Comment by edbkei** [comment]
yes. It was due to  security reason, just in case.

**Comment by edbkei** [comment]
This issue was found due to a fault in SSL/TLS as reported wrongly at https://github.com/bcgov/von-network/issues/187, indeed it should be reported herein, as it is related to aries-cloudagent-python. Briefly describing what happened is that I have an VM created in university cloud environment, where I installed aries-cloudagent, when executing run_demo faber results "OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443". Wade Barnes made a correct assumption, I think, "proxy setting should be set to git", as when I do wireshark on interface docker0, it displays clearly that TLS header comes empty. So, I had to request an independent VM on Google cloud, that Wade´s assumption is true. So, I have wireshark trace displaying clearly that TLS header is not empty, what shows that assumption is true. Nonetheless, appears this NoneType error.

**Comment by ianco** [comment]
The root cause is that Faber isn't detecting that the aca-py agent has started up.  Could be a timing issue, or a network-related issue (although the aca-py agent is started as a sub-process, so not sure why there would be a network issue).

When faber starts their agent they poll the `http://10.128.0.2:8021/status` endpoint to confirm that aca-py has finished its startup.

You can try extending the timeout for this step, or logging what is getting returned from this call.

**Comment by edbkei** [comment]
as it may take time to analyze, I would like to share .pcap file. As it is 79MB, I would like to request you an repository to upload.

**Comment by edbkei** [comment]
Hi,

I´ve doubled the START_TIMEOUT as below:
START_TIMEOUT = float(os.getenv("START_TIMEOUT", 60.0)) # 30.0
at ~/aries-cloudagent-python/demo/runners/support/agent.py

and the things improved a lot, now it is possible to connect faber2alice, 
send credential, and make proof. It delays a little more to bring the invitation data, so
the start_time might be in between of 30..60s.

Nevertheless, when exiting faber and alice, it comes new timeout problem. But, I think it is now manageable. 
.......
22/webhooks', '--trace-target', 'log', '--trace-tag', 'acapy.events', '--trace-label', 'faber.agent.trace', '--auto-accept-invites', '--auto-accept-requests', '--auto-store-credential']' timed out after 0.5 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/indy/demo/runners/agent_container.py", line 881, in terminate
    await self.agent.terminate()
  File "/home/indy/demo/runners/support/agent.py", line 681, in terminate
    result = await asyncio.wait_for(future, 10, loop=loop)  # 10
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/indy/demo/runners/support/agent.py", line 668, in _terminate
    raise Exception(msg)
Exception: Process did not terminate in time
eduardo@eduardoito:~/aries-cloudagent-python/demo$

**Comment by edbkei** [comment]
after some more simulations, START_TIMEOUT needs to be set to 60s.
at coroutine _terminate, timeout should be set to 2.0 instead of 0.5s.

**Comment by edbkei** [comment]
Regarding to TLS header empty in University Environment, that it could be proxy/firewall setting. Indeed, it happens because when during dockerfile.demo at docker run --rm bcgovimages/von-image36-1.15-1 /bin/bash, it may happen that MTU size may not fit VxLAN policy of local IT environment. In my case, it was limited to 1450 bytes. The procedure made was to change /etc/docker/daemon.json by introducing { "mtu": 1450}
