### ISSUE TITLE
Multiple explicit Out-Of-Band invitations with public DID

### ISSUE THREAD

**Issue by ffendt** [hyperledger/aries-cloudagent-python#1524]
Current state:
Inviter throws exceptions when receiving connection requests to explicit public Out-Of-Band invitations, when there is more than one explicit public Out-Of-Band invitation in state `invitation`. The connection isn't established and stays in state `invitation`.

Desired state:
Inviter can create multiple explicit public Out-Of-Band invitations and invitees can receive them when they want to, without exceptions in the inviter.

Details:
When creating an invitation with `public_did=true`, the inviter will create a database entry for a connection with field `invitation_key = public_did.verkey` (see [outofbound manager #L247](https://github.com/hyperledger/aries-cloudagent-python/blob/2960c51d175103e35be2865108e495ad7fb41265/aries_cloudagent/protocols/out_of_band/v1_0/manager.py#L247)). When providing multiple invitations, the inviter will have multiple invitations with the same `invitation_key` (and initially the same state `invitation`). If now an invitee receives one of the invitations, the inviter will run into an `StorageDuplicateError` in [didexchange manager #L396](https://github.com/hyperledger/aries-cloudagent-python/blob/2960c51d175103e35be2865108e495ad7fb41265/aries_cloudagent/protocols/didexchange/v1_0/manager.py#L396).

If I understand the code correctly, fixing this would need some adjustments on how the didexchange manager correlates a received request to a previously created invitation.

**Comment by shaangill025** [comment]
@ffendt The fix is ready if you want to give it a quick test.

**Comment by ffendt** [comment]
@shaangill025 Looks good, I can't reproduce the problem with the fixes from your PR. Thank you very much.

I'll close this issue and subscribe to the PR to retest if there are any major code changes.
