### ISSUE TITLE
Issue while sending response of proof request (Alice-Faber demo)

### ISSUE THREAD

**Issue by rsbhardwaj** [hyperledger/aries-cloudagent-python#153]
Hi,
(In Alice-Faber Demo)
I have modified the controller file in Aries python cloud agent demo with different attributes, till the issuance it works fine but while sending the response of proof request it fails at the proof holder agent with error as below - 

#26 Send the proof to X
Farmer | 2019-08-21 12:14:06,857 aiohttp.server ERROR Error handling request
Farmer | Traceback (most recent call last):
Farmer | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
Farmer | resp = await task
Farmer | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
Farmer | resp = await handler(request)
Farmer | File "/home/indy/aries_cloudagent/messaging/presentations/routes.py", line 310, in presentation_exchange_send_credential_presentation
Farmer | presentation_exchange_record, body
Farmer | File "/home/indy/aries_cloudagent/messaging/presentations/manager.py", line 197, in create_presentation
Farmer | credential_definitions,
Farmer | File "/home/indy/aries_cloudagent/holder/indy.py", line 252, in create_presentation
Farmer | json.dumps({}), # We don't support revocation currently.
Farmer | File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/anoncreds.py", line 1412, in prover_create_proof
Farmer | prover_create_proof.cb)
Farmer | indy.error.CommonInvalidStructure

**Comment by swcurran** [comment]
@rsbhardwaj - it looks like the error you are getting is from the Indy SDK, which suggests to me that the format of the data you are passing is incorrect.  Suggest comparing the flow and data between the proof done by Alice and the one you have done with Farmer.  If we can look at the fork you are using for this, we might be able to find the issue, but that's likely the area you should be looking.

**Comment by swcurran** [comment]
Closing this issue. Let us know if you are still having an issue.
