### ISSUE TITLE
Allow to accept TAA using startup parameters

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1532]
Currently it is not possible to automatically accept the TAA using startup parameters. It is possible if you have an interactive tty, but this is not always the case in server environments. If you know which ledger you're going to interact with, it would be possible to set the aml mechanism in the acapy startup parameters to be able to automate the complete startup process. 

With the new multi-ledger functionality we could even allow to set this per ledger, so you can handle it for all configured ledgers.

Maybe there are good reasons not to do this, so interested to hear you input

**Comment by swcurran** [comment]
The TAA is only needed for writing to a ledger.  My assumption has been that a single instance of ACA-Py for issuing will only be writing to a single ledger, and so the current mechanism for handling the TAA were sufficient (e.g. not really impacted for multi-ledger).

That said, having a start-up parameter to say "accept-indy-taa" seems like a good idea.  I think I sort of assumed it was already there :-).
