### ISSUE TITLE
Predicate range checks break due to over aggressive fraud detection

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#1536]
If you are doing a range check using predicates (e.g. "age >= 19 AND age <= 65") aca-py rejects this due to over aggressive fraud detection in the indy verifier class.

**Comment by ianco** [comment]
@swcurran I'm working on a fix for this, I'd like to get it into the `0.7.3` release ...

**Comment by swcurran** [comment]
Sounds good -- I'll hold off on the release.

**Comment by ianco** [comment]
Fixed in PR https://github.com/hyperledger/aries-cloudagent-python/pull/1538

**Comment by swcurran** [comment]
#fix
