### ISSUE TITLE
Credential record state not updated after revocation

### ISSUE THREAD

**Issue by DaevMithran** [hyperledger/aries-cloudagent-python#1539]
There should be a credential_revoked state for credential records, currently we have to use a seperate api to know the revocation status and the state of credential records remain in credential_issued even after revocation. The update should also reflect in the credential records.

**Comment by DaevMithran** [comment]
Agreed. That's a valid point. As we are supporting revocation in two ways either using cred_ex_id or rev_reg_id. The first approach will work only if the credential record is in the ACA-Py secure storage, So we can change the state of credential record to credential_revoked only when the credential record is in the ACA-Py secure storage. 
I'll create a PR for this. Thank you for the response.

**Comment by swcurran** [comment]
Addressed by #1545
