### ISSUE TITLE
Support for connecting to a Static Agent

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#154]
I would like to be able to connect a static agent to the Aries cloud agent. A static agent could have a partial implementation of the connection protocol (rather than creating a new keypair and DID, just pass it's statically configured key and DID) but I don't think this is the best option for all static agents. I would like to add support for somehow passing in a DID, key, and endpoint to ACA and receiving ACApy's reciprocating DID and key for the static connection.

I think we could probably do this a number of ways. It seems feasible to add a command line argument to specify the DID, key, and endpoint of the static agent and on startup have ACA create and print its DID and key. An admin api for adding a static connection could be another option, perhaps in addition to the CLI arg. I imagine a static connection would be listed as part of the normal api for listing connections, with a status indicating that it is a static connection.

I intend to work on this myself but I am interested to hear feedback from the maintainers on my (vague) plan of attack.
cc @andrewwhitehead

**Comment by andrewwhitehead** [comment]
Added via `--test-suite-endpoint` flag.
