### ISSUE TITLE
didexchange fetches all connection records to determine whether a connection can be reused

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1542]
As I understand the didexchange implementation at the moment, it fetches all connection records to be able to determine if a connection can be reused. It needs `their_public_did` which is not a tag, thus requiring a `post_filter`.

When dealing with a lot of connections this will probably making reusing connections quite slow.

Same happens with `invitation_msg_id`

**Comment by swcurran** [comment]
@shaangill025 / @andrewwhitehead -- can you please take a look at this? Can we add the "their_public_did" as a tag so that we can do an efficient query of the connection set?

**Comment by andrewwhitehead** [comment]
Is the `their_did` tag not sufficient?

**Comment by TimoGlastra** [comment]
`their_did` contains the peer did, the connection is only bootstrapped using the public did
