### ISSUE TITLE
Support ARM based docker images

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1546]
I've recently bought an ARM mac and the experience hasn't been great. Opening this issue to keep track of the status of supporting ARM based images for ACA-Py.

There has been some work done by other Hyperledger maintainers, and also the work in [von-network](https://github.com/bcgov/von-network/issues/182) which looks very promising. I'm currently developing on an ubuntu droplet because it was causing me too much headache, but would definitely want to get this resolved in the near future.

--- 
(below is copied from maintainers mailing list and may be helpful)

Now that mac arm hardware is pretty common, it is useful to have your
docker images built for arm64 and amd64 architectures. This means that
when mac m1 users run your docker containers, no emulation is needed and
performance is much better.

With lots of help from Ry, I've set up the Hyperledger mac arm runner to
build multiarch docker images. The amd64 image is built on the intel mac
via ssh, using docker buildx, and the arm64 image is built on the arm mac
itself.

To make this work via github actions, simply set your runs-on: to
macos-arm and run:

    docker buildx build . \
            --push \
            -t ghcr.io/hyperledger-labs/solang:latest \
            --platform linux/arm64,linux/amd64
This results in a single docker image, which contains both the arm64 and
the amd64 layers. You can see the resulting docker images here:

https://github.com/hyperledger-labs/solang/pkgs/container/solang

**Comment by swcurran** [comment]
I think this issue belongs in here: https://github.com/bcgov/aries-cloudagent-container, which is the source of the images.  Looks like we should be able to do that in the script used to produce the tagged releases.  I'll take a look at that when we create the 0.7.3 release tag.  Does that sound right?

I'm going to open a separate issue on how/where ACA-Py images should be published.  I suspect it is time to (a) put the script/process to create the images into ACA-Py itself, and (b) to publish the images to Hyperledger.  But as noted -- separate issue.

**Comment by swcurran** [comment]
Closing this in favour of #1548 .
