### ISSUE TITLE
How and to where should ACA-Py Container Images be published?

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#1548]
Currently, container images for ACA-Py are produced from this repo: https://github.com/bcgov/aries-cloudagent-container, and published to Docker Hub here: https://hub.docker.com/r/bcgovimages/aries-cloudagent. 

Is it time to:

1. Put the script/process to create the images into the ACA-Py repo vs. a separate one
2. Publish the images to a Hyperledger repo vs. a BCGov one?

Opinions welcome on this and any other suggestions on changes to the container image publishing process.

Thanks!

**Comment by WadeBarnes** [comment]
I think the image(s) should be published as part of the ACA-Py release process, and I'm leaning toward the images living in the [Hyperledger Docker Hub](https://hub.docker.com/u/hyperledger/).  The other option would be publish the images in the `ghcr.io` repository linked to the project.

@ryjones, Do you have any strong preferences to [Hyperledger Docker Hub](https://hub.docker.com/u/hyperledger/) or `ghcr.io`?

I also think the image build/publish could be refactored and simplified as a GHA workflow that is triggered on a release.

**Comment by ryjones** [comment]
@WadeBarnes please us github packages. It's free and it works. [here is an example of how it works in another Hyperledger project](https://github.com/hyperledger/firefly/blob/main/.github/workflows/docker_release.yml)

**Comment by swcurran** [comment]
When this gets done, please update the guidance in PUBLISHING.md (currently describes the aries-cloudagent-container approach). 

How do we get people currently using the docker/bcgovimages transitioned over to using the new Hyperledger images?

**Comment by swcurran** [comment]
Also -- this issue should also address #1546 when the update is made.

**Comment by WadeBarnes** [comment]
Images are published here; https://github.com/hyperledger/aries-cloudagent-python/pkgs/container/aries-cloudagent-python

Images are built and published automatically when a GutHub release is created.
