### ISSUE TITLE
Tracing both sides of a conversation with aca-py api

### ISSUE THREAD

**Issue by SmithSamuelM** [hyperledger/aries-cloudagent-python#156]
I mentioned this in another issue but decided it would be better to have its own issue.

In working through the swagger api the id on both sides of a connection or exchange are different for each side. While its possible to figure from the order of events what responses belong to a given connection/exchange it seems like it would be much easier if the API included the ids from the other side. Indeed its somewhat tedious if there are multiple exchanges etc. I fear that this manual matchup would be error prone and could get really complicated and problematic if there were more than one agent talking at the same time. I assume (maybe this is a big assumption) that under the hood each agent is keeping track of the ids from the other side of any connection or exchange but only exposing in the API their side. It would be helpful to understand why only one side shows up in the API. After the incepting event both sides should have both sets of ids or am I missing something fundamental here?

The thread id might be one way that these are tracked but I don't see thread ids consistently showing up in the API responses.

**Comment by swcurran** [comment]
I'm closing this issue as we have an issue open already on adjusting the data delivered via the webhook. Threading information is an obvious choice as @andrewwhitehead noted above.  We are using ACA-Py in a high volume use case where we are scaling both sides of the connection and I don't think we're having any issues with tracking in the controller what's happening.
