### ISSUE TITLE
OpenAPIDemo LEDGER_URL environment variable not available to run_demo script

### ISSUE THREAD

**Issue by watkinspd** [hyperledger/aries-cloudagent-python#1578]
Running MacOS Monterey 12.1 

When using the [demo instructions for docker for the OpenAPIDemo](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AriesOpenAPIDemo.md#running-in-docker) I found that the `$LEDGER_URL` environment variable was NULL within the `./run_demo` script. 

This was causing the demo to fail. The docker container would try to start but would fail to obtain the genesis file and quickly terminate.

Modifying the command to use `export LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io` fixed it for me. 

[This link helped me figure this out.](https://blog.doppler.com/how-to-set-environment-variables-in-linux-and-mac)

**Comment by swcurran** [comment]
By default the `run_demo` script assumes that a local instance of an Indy network is being used, and that the user has started an instance of `von_network`.  For the OpenAPIDemo, the Greenlight Dev Indy network is used, as outlined in the Getting Started. To use that, you prefix the commands with setting the LEDGER_URL as noted in the instructions you reference -- `LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo faber --events --no-auto --bg` -- that first part sets the environment variable used in the rest of the script.
