### ISSUE TITLE
CORS issue when calling a specific POST API from my frontend app

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#1584]
I run ACA-Py agents as docker containers by using the official ACA-Py docker images: bcgovimages/aries-cloudagent and run my frontend apps to connect to each agent. My frontend app can call the majority of the APIs of ACA-Py agents successfully, but when calling this specific POST api: `/present-proof-2.0/records/{pres_ex_id}/send-presentation`, I've got an CORS issue as shown below.
`Access to XMLHttpRequest at 'http://localhost:8001/present-proof/send-request/bce53e72-6f4e-45e1-8826-5b7f8551884c/send-presentation' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Below shows my local dev environment information.
- ACA-Py version of the docker image: py36-1.16-0_0.6.0, py36-1.16-1_0.7.0 and py36-1.16-1_0.7.2
- ACA-Py port: 8001
- Frontend port: 4200
- HTTP response doesn't have: `Access-Control-Allow-Origin `for this api as shown below, which causes this issue.
![image](https://user-images.githubusercontent.com/16185797/148091828-f6a6f897-0a56-4985-a945-55b0568b78e4.png)

Can anyone help?

**Comment by swcurran** [comment]
@shaangill025 -- is this one that you can look at?  I don't think anything we've done on 0.7.3 would have dealt with this.

**Comment by shaangill025** [comment]
@yunxi-zhang I can't replicate the CORS issue, I tested `/present-proof/records/{pres_ex_id}/send-presentation` (`v6.0`, `v7.0`, `v7.1`, `v7.2`, `v7.3rc0`) and `/present-proof-2.0/records/{pres_ex_id}/send-presentation` (`v7.0`, `v7.1`, `v7.2`, `v7.3rc0`). 

From the screenshot above, there is no endpoint `present-proof/send-request/..../send-presentation`, the correct endpoint is `/present-proof/records/..../send-presentation`, maybe this is the issue.

**Comment by yunxi-zhang** [comment]
thanks @shaangill025 , my mistake. I thought I used the right api in my frontend, but I put the wrong one there. Thanks for helping here.
