### ISSUE TITLE
Inconsistent behavior when issuing multiple credentials in sequential. Some of the requests/issuances are failing with error "400 Revocation registry metadata not found".

### ISSUE THREAD

**Issue by konda-kalyan** [hyperledger/aries-cloudagent-python#1586]
Inconsistent behavior when issuing multiple credentials in sequential. Some of the issuances are failing with error "400 Revocation registry metadata not found".

Agent version: 0.7.2
Wallet-type: askar
Agent API invoking from Controller: /issue-credential/records/{credential_exchange_id}/issue

Note that issue is not consistent and happening only when we use wallet type as askar (when we tested with indy as wallet type then no errors). Let’s say when we issue 10 credentials, sometimes all 10 are getting succeeded and sometimes few requests are failing with above error. The error rate is proportional when we go for bulk runs. Recently, we have upgraded agent to 0.7.2 version and wanted to understand if we are missing anything.

Below are the command line parameters (values are masked for security reasons).

[ "/bin/bash", "-c", " aca-py start -it http 0.0.0.0 10000 -ot http --admin 0.0.0.0 5000 -e http://abcagent:10000 --wallet-type askar --auto-provision --log-level debug --seed <some 32 chars> --genesis-url http://test.bcovrin.vonx.io/genesis --label 'Example label' --admin-insecure-mode --auto-respond-messages --wallet-storage-type postgres_storage --wallet-storage-config '{"url":"abcpostgresserver:5432","wallet_scheme":"DatabasePerWallet"}' --wallet-storage-creds '{"account":"abcuser","password":"abcpassword","admin_account":"abcuser","admin_password":"abcpassword"}' --wallet-name wallet-askar --wallet-key dicept_key --tails-server-base-url http://abctailserver:6543" ]

Let me know if I can provide more info. Any pointers are highly appreciated. Thank you

**Comment by swcurran** [comment]
@andrewwhitehead -- can you please take a look at this one?  Thanks,

**Comment by andrewwhitehead** [comment]
I can't see why this error would be raised rather than the `Revocation registry definition not found` or `Revocation registry not found` prior to it. Are there any database errors being logged? In any case it might well be impacted by the recent fixes in #1591.

**Comment by andrewwhitehead** [comment]
I believe this is resolved with aries-askar 0.2.5.

**Comment by PaulWen** [comment]
I can confirm this. I run some tests with AcaPy 0.7.4rc0 and Askar 0.2.5 using the Aries Load Generator. Based on those the issue has been solved.
