### ISSUE TITLE
Does ACA-Py encrypt in authcrypt or anoncrypt mode?

### ISSUE THREAD

**Issue by estrehle** [hyperledger/aries-cloudagent-python#1600]
[Aries RFC0019](https://github.com/hyperledger/aries-rfcs/blob/main/features/0019-encryption-envelope/README.md) specifies two modes for packing DIDComm messages into encrypted envelopes:

- _Authcrypt_ encrypts the message with the sender's private key, thus revealing the sender's identity to the message receiver.
- _Anoncrypt_ is anonymous and reveals nothing about the sender.

Which mode does ACA-Py use for establishing connections and sending basic messages?

**Comment by andrewwhitehead** [comment]
As far as I recall, anoncrypt is used only when sending a connection request, as no peer DID relationship has been established at this point, and when sending forwarded messages to mediators. Otherwise authcrypt is used exclusively.
