### ISSUE TITLE
Unable to install libindy in ubuntu 18.04

### ISSUE THREAD

**Issue by ShubhankerB** [hyperledger/aries-cloudagent-python#1612]
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 68DB5E88
sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb xenial stable"
sudo apt-get update
sudo apt-get install -y libindy -> Raising error that package not found
sudo apt-get install -y indy-cli  -> Raising error that package not found

**Comment by swcurran** [comment]
This was discussed recently on rocketchat and I believe resolves the issue you are raising here. Please reopen if not:

Conversation:

Hello All, I am trying to install Indy SDK packages. For windows, i just downloaded and imported the libindy dll files inside of my java project and i can call the indy methods. They are working fine. Now i am trying to move the java application to ubuntu and needed linux installation of libindy files . so i followed Ubuntu based distributions (Ubuntu 16.04 and 18.04) section from https://github.com/hyperledger/indy-sdk . I am getting an error when installing libvcx

The following packages have unmet dependencies:
libvcx : Depends: libindy (= 1.15.0~1628)
E: Unable to correct problems, you have held broken packages.

My ubuntu version : bionic for 18.04 Ubuntu .
Please help me.


WadeBarnes
6:20 AM
Example (using Docker):

```
FROM ubuntu:18.04
RUN apt-get update -y && apt-get install -y \
    gnupg \ 
    ca-certificates

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88
RUN echo "deb https://repo.sovrin.org/sdk/deb bionic stable" >> /etc/apt/sources.list
RUN apt-get update -y && apt-get install -y \
    libindy
```
Created a Gist here; https://gist.github.com/WadeBarnes/c0ec30be1040ade584489ba4f7b91e23
PR for doc update here; https://github.com/hyperledger/indy-sdk/pull/2478

Prasad8 2
Thanks. The Linux packages works for Ubuntu 20 also or is it strictly allowed to use only with Ubuntu 16 and 18 ?

WadeBarnes
I believe it works for 20.04 as well.

**Comment by WadeBarnes** [comment]
Yes, that works for 20.04 as well.
