### ISSUE TITLE
Transforming Faber/Alice/Acme use-case into a web-based use-case

### ISSUE THREAD

**Issue by ripulbd** [hyperledger/aries-cloudagent-python#1618]
Hi, 

I would like to transform the Faber/Alice/Acme use-case into a web-based use-case. I would like to know what would be the best approach for doing this. If someone knows of any pointer regarding this, I would be grateful if you could share those pointers. 

Thanks in advance.

**Comment by swcurran** [comment]
You should take a look at aries-acapy-controllers repo.  It has some instances of exactly that in .NET, Express and Node/JS -- https://github.com/hyperledger/aries-acapy-controllers .

**Comment by ripulbd** [comment]
Thanks a lot. this will just serve my purpose. Excellent.

**Comment by ripulbd** [comment]
Hi,

As per the above suggestion, I deployed two instances to the controller: Alice and Acme while for Faber I used the aca-py Faber instance. 

Using this setup, I can create connections betwee Faber-Alice and Alice-Acme. I can issue credentials to Alice.

But when I request for a proof from Acme, I am receiving this error:"marshmallow.exceptions.ValidationError: {'proof_request': ['Missing data for required field.'], 'connection_id': ['Missing data for required field.']}"

Please see the attached screenshot.
![New Screenshot](https://user-images.githubusercontent.com/1178467/152554323-0a4aeaa4-18d9-42a3-b270-1d4e7941aec8.png)

Just to check, if I copy the JSON proof request from the Acme interface and use it via the Admin API, then it is okay. 

I am struggling to understand if I am missing any trick here. 

Thanks a lot.

**Comment by swcurran** [comment]
@amanji -- can you please help out here a bit?  Thanks!

**Comment by ripulbd** [comment]
Hi,

Just to add to my previous post, I also deployed the Faber dotnet controller. When I try to issue credentials from this interface, it is also having the same issue. 

Also to add, all these controllers are sharing the same aca-py instance and the same wallets. 

Thanks a lot.

**Comment by ripulbd** [comment]
Hi,

Just to let you know, I have found a solution. The demo NodeJS controller seems to have some issues in the way the requests are submitted. I had to modify the code to submit the requests via axios to the API and it seemed to work. 

Thank you.
