### ISSUE TITLE
Swagger API example ValueModel ambiguous in places

### ISSUE THREAD

**Issue by SmithSamuelM** [hyperledger/aries-cloudagent-python#162]
The POST /credential_exchange/{Id}/store  example is

```son

Example ValueModel{   "credential_id": "string" }

```

But there are two different credential_id  used in the credential exchange and in the credential exchange record , that are,  credential_def_id and credential_exchange_id and nothing that is exactly credential_id. . Given the proximity of these two real fields the example field name is ambiguous and needs to reflect that actual field name. This happens in other places in the swagger example ValueModels.

**Comment by swcurran** [comment]
As noted in another issue, `referent` is the same as `credential_id` and the API demo doc (at least) have been updated.  We're not going to add a ticket yet to change this as it is tied to the handling of the indy-sdk wallet implementation that will change over time.

Closing this issue.
