### ISSUE TITLE
Appropriate Wallet image format, size and URL

### ISSUE THREAD

**Issue by srbms23** [hyperledger/aries-cloudagent-python#1622]
I tried to upload Wallet image using `PUT` method: `multitenancy/wallet/wallet_id`. However I am struggling to fing appropriate image size, format and URL. I tried with .svg and .png images but both of them seem not to work. I tried with, for example: https://i.ibb.co/NNdzyM9/digwallet.png but image is not shown even though I am able to download image with curl from terminal. With some .svg images, from Wikipedia for example, sometimes image is shown and sometimes it is not which is strange, in Swagger example is says png: `"image_url": "https://aries.ca/images/sample.png"`. 

Are there any rules regarding image format, size and URL link?

Thanks :)

EDIT: It only works with .svg.png images that can be found in Wikipedia ([Example](https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Coca-Cola_logo.svg/512px-Coca-Cola_logo.svg.png)). However sometimes some of these images are only shown only with first connection invitation. After that every other connection invitation that is sent from that wallet comes without image... Is there a known reason for that?

**Comment by ianco** [comment]
I believe that aca-py just stores the url, so whether the image is displayed depends on the client.  For example if you're displaying a connection in a mobile wallet, it should display the image next to the connection in your connection list - it will just fetch the image from the url, and may or may not understand different image formats.

Where are you trying to display the image?

**Comment by srbms23** [comment]
Hi @ianco,

I tried to display wallet image in a mobile wallet, currently it is [lissi](https://lissi.id/) app. Just because sometimes it works with some urls and sometimes it does not even though it is the same image source and link type (I tested several images from Wikipedia) I thought maybe there are some rules regarding URLs, image format and size. With both images used for testing I am able to download them using curl, so both links should be fine.
If you have any other idea why this happens please let me know. :)

I will try to reach someone from lissi and ask them if they can help me. Thanks! :)
