### ISSUE TITLE
Why does a Mobile Agent Require a Mediator

### ISSUE THREAD

**Issue by bsivacharan** [hyperledger/aries-cloudagent-python#1629]
Hi,

I know this forum is for issues, but so far I am able to resolve them by myself, however I have a general question to ask

 I am building a demo porotype based on aca-py and aries mobile agent. I am unclear with the holder to Issuer flow in case of (Mobile agent to cloud agent) appreciate if some one can clarify the following  

1) Can mobile agents directly communicate with the "issuer" cloud agent like aca-py? 
2) in Most of the Example's, by far I have seen mentioning the need for "mediator" for mobile agents. When Mobile agents can communicate with mediation server endpoint, my question is why do they cannot directly connect and communicate with the issuer cloud agent (end point)

Thanks
siva
1

**Comment by swcurran** [comment]
Quick answer to this:

An arbitrary agent cannot send a message directly to a mobile wallet app of another user.  A mobile wallet app has no endpoint, and in fact only can communicate to others by sending requests from the mobile wallet (not receiving requests). As such, for an arbitrary agent to send a message to a mobile wallet, the wallet uses a mediator and the other agents send to the mediator. Then, the mediator can interact with the mobile wallet to get the message.  This works even when the mobile wallet is offline (turned off, not connected to the Internet) -- the mediator queues up the messages.  The mediator may be able to send push notifications to the mobile wallet, but an arbitrary other agent could not.

**Comment by swcurran** [comment]
"Push Notifications" are a feature provided by a mobile OS (e.g. Android and iOS) that have very strict authorization rules. Apps register what push notifications they accept, from whom they accept them, and the mobile OS gives the user control over what notifications they want to see. It is a very constrained process to ensure that the user is not spammed with notifications from arbitrary senders.  As such, a mobile app cannot be set up to receive push notifications from arbitrary sources, but they can be set up to receive them from specific sources, such as the mediator they use.

Hope that helps.
