### ISSUE TITLE
Improving UX

### ISSUE THREAD

**Issue by ripulbd** [hyperledger/aries-cloudagent-python#1630]
Hi,

Based on the awesome suggestions provided in my previous issues, I have been able to transform the Faber-Alice part of the demo into web services where Alice uses the Aries Mobile Agent React Native. So the whole flow works perfectly. 

In my case, the flow I have implemented is like this: Alice uses two channels two interact with the Faber web service.  Firstly, Alice uses the web UI to create a new connection which is displayed using a QR code. Alice uses her mobile wallet to establish the connection. When the connection is established, a session is created for Alice in the browser and now Alice has the option to request Faber to issue the credential which is then stored in the mobile wallet. Then, Faber requests to submit a proof request and Alice can do that by accepting the request in the wallet and then releasing the credential. As long as the session is maintained, the flow works fine. 

Now I would like to take it to the next level, mainly to improve the UX. Let's imagine a scenario, when the session is destroyed. Now, even though both Faber and Alice have the required connection parameters they do not have an established connection per se. One option for Faber is to show the list of active connection IDs and allow Alice to choose the correction one from it.  However, this is where I am struggling a bit, Because, Faber might have many active connections and it would be difficult for Alice to know what the correct connection ID for her is. I think one solution could be to store a persistent cookie at Alice's browser which will contain her connection ID. But what might happen when Alice might use a different browser in a different device?

I would be grateful if there is any suggestion to improve this UX. Thanks a lot as always.

**Comment by swcurran** [comment]
I don't think this repo is the place to talk about UX issues as they are so use case specific, as such, I'm closing this issue.

Regards your use case.  I'm not sure what you mean by the session being destroyed -- do you mean their web session?  If that is the case, the "OOB reuse" feature of [0434-outofband](https://github.com/hyperledger/aries-rfcs/tree/main/features/0434-outofband) takes care of that use case.  Faber presents an invitation, Alice processes it, realizes it is from the a connection she already has and sends the "reuse" message to not create a new connection.

As well, using a cookie would work for enabling skipping the QR code altogether when using the same browser. Faber sets a cookie, Alice navigates back to the Faber page, Faber gets the cookie, finds the association with the Alice connection, and uses that to send a message to Alice via DIDComm -- perhaps a Proof Request.
