### ISSUE TITLE
RecipientKey is not a raw Ed25519VerificationKey2018 key

### ISSUE THREAD

**Issue by PaulWen** [hyperledger/aries-cloudagent-python#1634]
Running tests using the [Aries Cloud Agent Load Generator](https://github.com/My-DIGI-ID/aries-cloudagent-loadgenerator) I came across the unexpected error message `recipientKeys [...] is not a raw Ed25519VerificationKey2018 key` twice so far:

- https://github.com/lissi-id/acapy-load-test-results/blob/main/Full%20Flow%20Constant%20Load/08%20AcaPy%200_7_3%20askar_wallet/report-test-results.pdf (page 3)
- https://github.com/lissi-id/acapy-load-test-results/blob/main/Full%20Flow%20Increasing%20Load/10%20AcaPy%200_7_3%20askar_wallet/report-test-results.pdf (page 3)

In my test setup, I am using an Issuer/Verifier AcaPy as well as a separate Holder AcaPy. The Issuer/Verifier AcaPy generates a connection invitation. The Holder tries to receive the connection invitation using `POST /connections/receive-invitation` but returns `HTTP 422` and `recipientKeys [...] is not a raw Ed25519VerificationKey2018 key`.

Unfortunately, I am not able to reproduce the error reliably and as you can also see in the test reports many other connections that have been established the same way did not result in the error.

Issuer/Verifier AcaPy: 0.7.3; Askar; Postgres
Holder AcaPy: 0.7.3; Askar; sqlite

**Comment by swcurran** [comment]
@PaulWen  -- Is this still an issue after the recent updates and additional load generator tests?

**Comment by PaulWen** [comment]
I have not seen the issue anymore for a while now. Though, I cannot provide a final answer as I never figured out how to reproduce it. This being said, it would be fine with me if we close this issue.
