### ISSUE TITLE
Running Docker Scripts on Windows

### ISSUE THREAD

**Issue by dFohlen** [hyperledger/aries-cloudagent-python#1644]
# Current Behavior

Running the [run_docker](https://github.com/hyperledger/aries-cloudagent-python/blob/main/scripts/run_docker) script on Windows 10 results in an `docker: invalid reference format` error.  The script is executed within the Git Bash and MINGW64.

# Expected Behavior

Running on all operating systems (Windows, Linux and Mac) without errors.

# Failure Information (for bugs)

After some research and testing, I came up with the clue about the `pwd` environment variable and the different brackets. So in [run_docker#L37](https://github.com/hyperledger/aries-cloudagent-python/blob/e29e6ef1e79622e608ecb1b632ccfc3b3536e7b3/scripts/run_docker#L37) (and the other scripts) rounded brackets were used instead of curly brackets as expected by Windows. 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open Git Bash on Windows
2. Execute ` ./scripts/run_docker start --help`
3. Fails with: 
   ``` 
   docker: invalid reference format.
   See 'docker run --help'.
   ``` 

## Context

* Operating System: Windows 10 Pro 21H1
* Shell: Git Bash
* Docker Version: 4.5.1 (74721)
* ACA-Py: [main](https://github.com/hyperledger/aries-cloudagent-python/tree/main)

## Failure Logs

```
$ ./scripts/run_docker start --help
#1 [internal] load build definition from Dockerfile.run
#1 sha256:31fc6ff0b4e368a268c16d2d1ff87914a5d2190266620ddb6255d4b4078e6ce5
#1 transferring dockerfile: 36B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:1630b7b8adb2b67f630b04940297979b16b07db2b8337da4663a8373bb814834
#2 transferring context: 34B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/bcgovimages/von-image:py36-1.15-1
#3 sha256:7a39a9bb062d089aad0c4df08d652b3b30681a27b26cc8a8047ca40555d8d699
#3 DONE 7.5s

#4 [ 1/11] FROM docker.io/bcgovimages/von-image:py36-1.15-1@sha256:7ba9452bbda1b5d03f117451ba6504f30cfe5598e74ff78f3e6e4ce29a206c65
#4 sha256:05e243cb66d49964d3fbfc7aac3f3d6081061d4aa71fc74b018019b8a281a01c
#4 DONE 0.0s

#5 [internal] load build context
#5 sha256:1203afb22987453e93a16ba62aebd2afcf05c139ea54653d2ad699dafd790b59
#5 transferring context: 62.27kB 0.1s
#5 transferring context: 114.26kB 0.2s done
#5 DONE 0.2s

#9 [ 5/11] ADD aries_cloudagent/version.py aries_cloudagent/version.py
#9 sha256:fb4e2f6e46503b907d2ad90319276d0a539ea5c29d81cb1472ec3f02d94fcd4f
#9 CACHED

#10 [ 6/11] ADD bin ./bin
#10 sha256:d6d51b589350ced15214d43d43e44e337a39e3d74052dece6d54f230ed3b2baf
#10 CACHED

#11 [ 7/11] ADD README.md ./
#11 sha256:87035e365a923763215c5f7db6fbb26051f91924df218eb90c095cf69590277e
#11 CACHED

#6 [ 2/11] ADD requirements*.txt ./
#6 sha256:9a4badfeedfdc9b7e10cacda2a3ffb52feee19bba854e75166f3afbd18f1a5d0
#6 CACHED

#12 [ 8/11] ADD setup.py ./
#12 sha256:3a526acbce4123c3de869e6b2d95eec371fa8d886192bb40dd7bf018572e8612
#12 CACHED

#14 [10/11] RUN mkdir logs && chown -R indy:indy logs && chmod -R ug+rw logs
#14 sha256:cee4c1797e0dd614f97c988622d83f578ed2a7c38abb06be917b8252aee9dcc8
#14 CACHED

#7 [ 3/11] RUN pip3 install --no-cache-dir     -r requirements.txt     -r requirements.askar.txt     -r requirements.bbs.txt     -r requirements.dev.txt
#7 sha256:5436ecfe7cd7d0fed901021eae363894a5b1da0888d7e395b2296b94b36fc26f
#7 CACHED

#13 [ 9/11] RUN pip3 install --no-cache-dir -e .
#13 sha256:fd03c630f8a87880f95b872c1f731123f182fdfec52a2f1c9a08e959c3e87c0a
#13 CACHED

#8 [ 4/11] RUN mkdir aries_cloudagent && touch aries_cloudagent/__init__.py
#8 sha256:07a598ef1e2e93f2cf65f249f0f854865dc01fc812b529c86785452dbed56731
#8 CACHED

#15 [11/11] ADD aries_cloudagent ./aries_cloudagent
#15 sha256:1b7c96cf971b2b384f8b81566d615d001fac98947d36cf109603fe04d439ad4a
#15 CACHED

#16 exporting to image
#16 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#16 exporting layers done
#16 writing image sha256:78047bf3490e3bf5953983db265b14044c696b1ecf4702f32f228da77cb21a81
#16 writing image sha256:78047bf3490e3bf5953983db265b14044c696b1ecf4702f32f228da77cb21a81 done
#16 naming to docker.io/library/aries-cloudagent-run done
#16 DONE 0.0s
docker: invalid reference format.
See 'docker run --help'.
``` 

## Possible Suggestion

[run_docker#L37](https://github.com/hyperledger/aries-cloudagent-python/blob/e29e6ef1e79622e608ecb1b632ccfc3b3536e7b3/scripts/run_docker#L37) 
```
diff --git a/scripts/run_docker b/scripts/run_docker
index e1c99a0b..f8207395 100755
--- a/scripts/run_docker
+++ b/scripts/run_docker
@@ -34,7 +34,7 @@ if [ -n "${ENABLE_PTVSD}" ]; then
   ARGS="${ARGS} -e ENABLE_PTVSD=\"${ENABLE_PTVSD}\" -p $PTVSD_PORT:$PTVSD_PORT"
 fi
 
-ARGS="${ARGS} -v $(pwd)/../logs:/home/indy/logs"
+ARGS="${ARGS} -v ${pwd}/../logs:/home/indy/logs"
 
 if [ -n "${WEBHOOK_URL}" ]; then
   ARGS="${ARGS} -e WEBHOOK_URL=\"${WEBHOOK_URL}\""
```

\* Don't know what effect this change will have on the other systems.

**Comment by WadeBarnes** [comment]
I just tried `./scripts/run_docker start --help` without the update and I got the expected `aca-py` help output without error:
- Windows 11 Pro 21H2
- git version 2.34.1.windows.1
- Docker Desktop 4.5.1 (74721)

**Comment by WadeBarnes** [comment]
Changing from `$(pwd)` to `${pwd}` would end up treating `pwd` as a variable to be expanded, rather than a command to be executed inline for it's output.  Therefore it would resolve as a blank string, rather than the path for the current directory.

The issue appears to be the fact that the resulting volume mount spec is missing the leading `/` expected by Windows:
```
winpty docker run --rm -ti --name aries-cloudagent-runner_ktMvNPtBQzQk4DvF -v /c/Users/wade/git-repos/aries-cloudagent-python/scripts/../logs:/home/indy/logs aries-cloudagent-run start --help
```

should be:
```
winpty docker run --rm -ti --name aries-cloudagent-runner_ktMvNPtBQzQk4DvF -v //c/Users/wade/git-repos/aries-cloudagent-python/scripts/../logs:/home/indy/logs aries-cloudagent-run start --help
```

**Comment by WadeBarnes** [comment]
@dFohlen, Good find BTW.  It's working on my machine because instead of an error it's creating a garbage folder, `C:\Users\wade\git-repos\aries-cloudagent-python\logs;C`, in my `aries-cloudagent-python` project folder, not mounting the folder, and then continuing on as though nothing happened.

**Comment by dFohlen** [comment]
Hi @WadeBarnes,

first of all - thanks for your help. Your right, without changing the brackets the path looks like:
`winpty docker run --rm -ti --name aries-cloudagent-runner_0uhqL2NgobULtHcz -v /c/Users/d_fohlen/Documents/SSI Demo/aries-cloudagent-python.git/scripts/../logs:/home/indy/logs aries-cloudagent-run start --help`

with the curly brackets:
`inpty docker run --rm -ti --name aries-cloudagent-runner_h3zdv6qDOJzmQ0Xr -v /../logs:/home/indy/logs aries-cloudagent-run start --help`

Maybe because of the whitespaces in `SSI Demo`?

**Comment by WadeBarnes** [comment]
@dFohlen, Yes, the whitespace is also an issue.  That would mean line 37 would need to be something like `ARGS="${ARGS} -v '/$(pwd)/../logs':/home/indy/logs"` to work.

**Comment by WadeBarnes** [comment]
@dFohlen, You might also then need to add `eval` to the beginning of `$CONTAINER_RUNTIME run --rm -ti --name "aries-cloudagent-runner_${RAND_NAME}"`, to make it `eval $CONTAINER_RUNTIME run --rm -ti --name "aries-cloudagent-runner_${RAND_NAME}"`, to get it to work with the quotes and whitespace.

**Comment by dFohlen** [comment]
Good morning @WadeBarnes,

your solution is working. The command now contains the following path and the logs folder is correctly created in the root directory of the repository.
`eval winpty docker run --rm -ti --name aries-cloudagent-runner_gvihwp7D7LmotY2q -v '//c/Users/d_fohlen/Documents/SSI Demo/aries-cloudagent-python.git/scripts/../logs':/home/indy/logs aries-cloudagent-run start --help`

But the folder is still empty after running/stopping the ACA-Py. Which logs should be stored there? Especially because there is an other empty `log` folder on the container 🤔 

```
$ls -l /home/indy
total 56
-rwxr-xr-x 1 root root 9835 Feb 17 15:19 README.md
drwxr-xr-x 1 indy indy 4096 Feb 25 08:43 aries_cloudagent
drwxr-xr-x 2 indy indy 4096 Feb 21 22:48 aries_cloudagent.egg-info
drwxr-xr-x 2 root root 4096 Feb 21 22:48 bin
drwxrwxr-x 1 root root 4096 Feb 24  2021 ledger
drwxrwxr-x 1 root root 4096 Feb 24  2021 log
drwxr-xr-x 1 root root 4096 Feb 25 08:34 logs
-rwxr-xr-x 1 root root   54 Feb 17 15:19 requirements.askar.txt
-rwxr-xr-x 1 root root   26 Feb 17 15:19 requirements.bbs.txt
-rwxr-xr-x 1 root root  315 Feb 17 15:19 requirements.dev.txt
-rwxr-xr-x 1 root root   24 Feb 17 15:19 requirements.indy.txt
-rwxr-xr-x 1 root root  471 Feb 17 15:19 requirements.txt
-rwxr-xr-x 1 root root 1735 Feb 17 15:19 setup.py
$ ls -l /home/indy/logs
total 0
$ ls -l /home/indy/log
total 0
```

**Comment by WadeBarnes** [comment]
More info on logging configuration can be found here; https://github.com/hyperledger/aries-cloudagent-python/blob/main/Logging.md

**Comment by swcurran** [comment]
Closing this issue.  I'm assuming that anything useful from this has been put in the right places.  Please reopen if there is more to be done.
