### ISSUE TITLE
Askar-profile wallet creation error causes wallet to be only registered in the relay database

### ISSUE THREAD

**Issue by acuderman** [hyperledger/aries-cloudagent-python#1649]
When using Aca-py in askar-profile multitenancy mode with Postgres database, the following error is thrown in very rare scenarios:

```
aiohttp.web_exceptions.HTTPBadRequest: Error when adding storage record. Backend error. Caused by: error returned from database: insert or update on table "items" violates foreign key constraint "items_profile_id_fkey".
Traceback (most recent call last):
  File "/cloudagent/aries_cloudagent/storage/askar.py", line 52, in add_record
    await self._session.handle.insert(
  File "/usr/local/lib/python3.10/site-packages/aries_askar/store.py", line 441, in insert
    await bindings.session_update(
  File "/usr/local/lib/python3.10/site-packages/aries_askar/bindings.py", line 837, in session_update
    return await do_call_async(
aries_askar.error.AskarError: Backend error
Caused by: error returned from database: insert or update on table "items" violates foreign key constraint "items_profile_id_fkey"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cloudagent/aries_cloudagent/multitenant/admin/routes.py", line 314, in wallet_create
    wallet_record = await multitenant_mgr.create_wallet(
  File "/cloudagent/aries_cloudagent/multitenant/base.py", line 200, in create_wallet
    public_did_info = await wallet.get_public_did()
  File "/cloudagent/aries_cloudagent/wallet/askar.py", line 366, in get_public_did
    await storage.add_record(
  File "/cloudagent/aries_cloudagent/storage/askar.py", line 60, in add_record
    raise StorageError("Error when adding storage record") from err
aries_cloudagent.storage.error.StorageError: Error when adding storage record

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ddtrace/contrib/aiohttp/middlewares.py", line 61, in attach_context
    response = await handler(request)
  File "/cloudagent/aries_cloudagent/admin/server.py", line 163, in ready_middleware
    return await handler(request)
  File "/cloudagent/aries_cloudagent/admin/server.py", line 200, in debug_middleware
    return await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
  File "/cloudagent/aries_cloudagent/admin/server.py", line 347, in check_multitenant_authorization
    return await handler(request)
  File "/cloudagent/aries_cloudagent/admin/server.py", line 391, in setup_context
    return await task
  File "/cloudagent/aries_cloudagent/multitenant/admin/routes.py", line 320, in wallet_create
    raise web.HTTPBadRequest(reason=err.roll_up) from err
aiohttp.web_exceptions.HTTPBadRequest: Error when adding storage record. Backend error. Caused by: error returned from database: insert or update on table "items" violates foreign key constraint "items_profile_id_fkey".
```

The error happens very rarely and can not be regularly reproduced. No errors seem to happen before this one.

When searching for the wallet using `/multitenancy​/wallet​/{wallet_id}` whole wallet info is returned, so I believe that the wallet is registered on the relay side but not the actual profile as other endpoints return error:
```
aries_askar.error.AskarError: Profile not found
```

Are there any ideas about what could cause the problems? 

I think that the operations to create the wallet should be wrapped in a transaction and rollbacked if something unexpected happens.

**Comment by andrewwhitehead** [comment]
I see, thanks for investigating. It looks like there is an issue in that code where it's not properly detecting an existing profile, but I don't think it explains the error above. Are you removing any profiles?

**Comment by acuderman** [comment]
No, we are not removing any profiles.

**Comment by acuderman** [comment]
Looking at the profiles table, some numbers in the id column are skipped (auto increment column) . I expect this happens when there is a conflict.

**Comment by acuderman** [comment]
> Looking at the profiles table, some numbers in the id column are skipped (auto increment column) . I expect this happens when there is a conflict.

After testing, the profile id isn't returned when the conflict happens, so the "Duplicate profile name" error is thrown, which disproves the theory above.

To sum up when the error above happens in the single call to create a multitenant wallet::
 - create_profile Askar function creates the SQL query which returns id (Otherwise It would throw "Duplicate profile name" error)
 - profile name and id is added to the cache
 - database reads do not throw any errors
 - on the first insert database query returns  `insert or update on table "items" violates foreign key constraint "items_profile_id_fkey"`

**Comment by andrewwhitehead** [comment]
I've tried load testing this locally against a Postgres database and can't reproduce it that way. What platform are you running the application and DB on? Is there any load balancing or replication on the DB?

**Comment by acuderman** [comment]
Hey, thanks for looking into It. I was also load testing It without the success.

Aca-py is running on `python:3.10-slim` docker image with Postgres v13.4 running on AWS RDS - Aurora.

We have a separate writable instance and readable instance (1 each) under the same cluster. I have tried running SELECT queries on both, and they return the same results.

**Comment by swcurran** [comment]
Any suggestions on what to do with this issue?  Is it still happening after the recent Askar updates?

**Comment by acuderman** [comment]
We did not observe any issues lately using the custom askar fix @reflectivedevelopment prepared. Although, I am unsure if the fix was also merged to the aries-askar repository.

@reflectivedevelopment can you please confirm?

**Comment by reflectivedevelopment** [comment]
I believe this was related to https://github.com/hyperledger/aries-askar/pull/45

Since when a transaction failed, it would leave the transaction open, causing random sql statements to fail, leading to foreign key violations.
