### ISSUE TITLE
transaction endorsement uses %VER instead of the actual protocol version

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1650]
https://cs.github.com/?scopeName=All+repos&scope=&q=repo%3Ahyperledger%2Faries-cloudagent-python+%22%25VER%22

@ianco

**Comment by TimoGlastra** [comment]
Same with `<requested signature type>`. Seems like a placeholder to me?

**Comment by ianco** [comment]
On it

**Comment by swcurran** [comment]
@ianco -- did this get fixed?

**Comment by ianco** [comment]
No this is still outstanding, sorry forgot about this one

**Comment by swcurran** [comment]
@amanji — this is a trivial ACA-Py one for you to get started with.
