### ISSUE TITLE
Missing goal codes in DID exchange protocol implementation

### ISSUE THREAD

**Issue by jleach** [hyperledger/aries-cloudagent-python#1652]
The [DID Exchange](https://github.com/hyperledger/aries-rfcs/tree/main/features/0023-did-exchange) RFC notes the implication of a goal/code to better reason about why a connection is being established:

```JSON
  "goal_code": "aries.rel.build",
  "goal": "To create a relationship",
  ```

Its also mentioned in the [Out-Of-Band](https://github.com/hyperledger/aries-rfcs/tree/main/features/0434-outofband) protocol in `Invitation: https://didcomm.org/out-of-band/%VER/invitation`:

```JSON
  "goal_code": "issue-vc",
  "goal": "To issue a Faber College Graduate credential",
```

But, in the ACA-py agent Swagger docs its absent `/out-of-band/create-invitation/`

```JSON
{
  "alias": "Barry",
  "attachments": [
    {
      "id": "attachment-0",
      "type": "present-proof"
    }
  ],
  "handshake_protocols": [
    "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/didexchange/1.0"
  ],
  "mediation_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "metadata": {},
  "my_label": "Invitation to Barry",
  "use_public_did": false
}
```

**Comment by andrej-zirko** [comment]
We are considering the utilization of goal codes with implicit invitation.

The inviter will receive a request from invitee using create request and Public DID. However, the webhook received by the inviter does not provide specific details about the invitee.

At present, we haven't come across any particular information that can be displayed to the inviter, except for the goal and goal code.

Are there any alternative methods available currently to convey information about the invitee to the inviter?

Thank you

**Comment by swcurran** [comment]
@usingtechnology — please take this one. Hopefully it should be a quick and dirty addition to the API for OOB.

For @andrej-zirko ’s use case, the `request` Admin API call also needs goal and goal code to be added, so please include that if the Admin API does not currently support it.

Of course, if the underlying protocols do not also support goal codes, that will also need to be supported…

**Comment by usingtechnology** [comment]
Ok, on it.
