### ISSUE TITLE
Could not store issued credential in mobile wallet

### ISSUE THREAD

**Issue by andionita** [hyperledger/aries-cloudagent-python#1664]
Connecting acapy to a mobile wallet works up to the point where the mobile wallet (lissi in this case) attempts to store the issued credential, which eventually fails with the error message "Credential X could not be stored". 

I am following this guide and I am aware it may be outdated.
https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AliceGetsAPhone.md

I am using the lissi wallet app on android. I have tried using the other recommended wallet apps, trinsic and esatus both fail on scanning the invitation QR code generated by acapy.

I am guessing there is an incompatibility with the ledger/genesis file (have tried with both test and dev.greenlight.bcovrin.vonx.io)? Any hints to get the application working are appreciated!

**Comment by swcurran** [comment]
BCovrin Test should work ([http://test.bcovrin.vonx.io/](http://test.bcovrin.vonx.io/)). Dev Greenlight definitely will not work as the lissi wallet does not support it.

**Comment by andionita** [comment]
Indeed, after pulling the latest changes it works like a charm. My last git pull was a while back. Thanks!

**Comment by andionita** [comment]
I am reopening since the issue has reoccurred. Since yesterday the storing of credentials in lissi fails. I pulled the most recent changes in the main branch, the issued credential remains in state "offer_sent" and hence not finishing. I am running `POST http://acapy:8021/issue-credential/send-offer` to issue the credential. Any ideas what is happening?

**Comment by swcurran** [comment]
Any updates on this?  My feeling is that we're getting an inconsistency between ACA-Py and the LISSI Wallet but I'm not certain.  Have you tried other wallets -- esatus and/or Trinsic?

I'm going to close this now, but no problem if you want to reopen it.  We definitely want to have ACA-Py working with all wallets -- or to know why things aren't working.
