### ISSUE TITLE
Credential Revocations: Unrecoverable state after failed credential revocation due to ledger connection issues

### ISSUE THREAD

**Issue by PaulWen** [hyperledger/aries-cloudagent-python#1669]
A colleague of mine just showed me the following behavior:
1. issue revocable credentials (two credentials using revocation registry A and a third credential using revocation registry B)
1. stop VON ledger or cut the network connection between AcaPy and ledger
1. revoke credential from revocation registry A --> "Internal Server Error: Read Timeout"; AcaPy still writes down in its DB that the credential has been revoked
1. start VON ledger or ensure network connection between AcaPy and ledger
1. revoke another credential from the revocation registry A --> "Internal Server Error: Ledger rejected transaction request: client request invalid ..."; AcaPy still writes down in its DB that the credential has been revoked
1. revoke credential from revocation registry B --> works as expected

**The behavior results in two problems**:
1. AcaPy marks credentials as revoked in the DB even though they are not yet revoked
2. once the AcaPy DB and Ledger are out of sync it is not possible to revoke any further credentials using the same revocation registry

**Comment by swcurran** [comment]
@PaulWen -- could you try this with Askar (which picks up CredX).  We're wondering if it is still an issue there.

Thanks

**Comment by PaulWen** [comment]
Good point! The observations above were made using the Indy SDK. Running the same test using the Askar wallet seems to resolve most of the problems. Will we play around a little bit more with credential revocations in the context of the Askar wallet and open another ticket in case we find any issues with that.

In case we do not want to fix the revocation problems in the context of the Indy SDK, this issue can be closed.

**Comment by swcurran** [comment]
Good to know -- Andrew thought that would be the case.  That said, we should look to see if there is something easy we can do in ACA-Py to resolve this.  If it is a big deal, then we might not address it.

We really want to push on getting moved to the shared components/Askar.

**Comment by ianco** [comment]
I've added an integration test that demonstrates this issue, see PR #https://github.com/hyperledger/aries-cloudagent-python/pull/1672

I'll take a look at what aca-py is doing ...  the error message the aca-py logs is:

`2022-03-17 17:14:45,831 aries_cloudagent.indy.sdk.verifier ERROR Presentation on nonce=838013515937407266142254 cannot be validated: Timestamp on sub-proof #1 is missing vs. requested attribute health_attrs`

(`health_attrs` is from a non-revocable credential)

**Comment by swcurran** [comment]
This is being fixed with #1783 .  Closing this issue.

@PaulWen -- it would be great if you could test #1783 and see if your use case above is indeed fixed.
