### ISSUE TITLE
POST issue/credential2.0 not executing in the Swagger UI

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#1677]
From an email: I was running through an Aries Acy-Py demo this weekend to share with my students during my class next week - one using Swagger UI - and noticed that POST issue/credential2.0 wasn’t executing. Just mentioning this in case you were not aware and are still using the Swagger UI in your own teaching demos. I managed to set up a little exercise for them without the Swagger UI, but it’s not as good at helping them understand the interactions.

**Comment by ianco** [comment]
Sent a note to the reporter to confirm what endpoint(s) are being used.  All tests are running ok.  Noted that the `POST /issue-credential-2.0/send` endpoint doesn't work with alice/faber because the controllers are trying to respond to events that aca-py is *also* responding to, which does a "double-tap" error.

**Comment by ianco** [comment]
```
This is the demo I was following: https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AriesOpenAPIDemo.md

I successfully completed all steps up to POST /issue-credential-2.0/send.  

At that point, I altered the JSON as instructed and tried to execute. Nothing happened when I clicked on Execute. I initially thought it was because my JSON wasn’t formatted properly so I double checked this against the sample screen shot. It looked okay. I tried to execute a few times without success. Then I tested out a few other APIs to see if they would execute and they did. So, I concluded that there might be something wrong in the back end of this particular API. I tried to look at the code on the side, but I just wasn’t familiar enough with it to identity if that was the problem. I’m still not sure it’s an issue with the API call, though, because I don’t know how Swagger behaves if the JSON isn’t correct i.e., does it throw an error or just not respond?
```

**Comment by ianco** [comment]
Closing since everything seems to work.  Will open a new issue if we can get more detailed info about what error is (potentially) happening
