### ISSUE TITLE
Allow use of SEED when creating local wallet DID

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#1682]
Update the `/wallet/did/create` endpoint to allow the use of an optional `SEED` when creating a new local DID

Add a new startup parameter `--allow-insecure-seed-local-did` to enable the use of this new `SEED` parameter (if the option is not provided on startup then the `SEED` parameter will not be available when creating a local DID.

Consider as well providing a way to import an explicit public/private key pair (vs. indirectly via a seed) so that an existing key pair can be imported into an Aries Wallet.

See Issue #1657  for the background discussion

**Comment by tdiesler** [comment]
#606 may also be related

**Comment by DaevMithran** [comment]
@ianco this has been resolved

**Comment by tdiesler** [comment]
@DaevMithran please show how this can now be done

**Comment by DaevMithran** [comment]
@tdiesler 
I added wallet startup parameter: --wallet-allow-insecure-seed which will support for seed in wallet/did/create route

The seed is not added in schema of wallet/did/create route as it can create confusion.

**Comment by tdiesler** [comment]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/244946/161918253-9f2084b1-ab5c-4542-b475-d7c507345968.png">

... "seed" as top level attribute or as an option?

**Comment by matgnt** [comment]
Just as a reference for others, it seems the change has been merged in PR #1705

**Comment by DaevMithran** [comment]
@tdiesler seed is a top level attribute
