### ISSUE TITLE
Error: connection_id is null on the public invitation.

### ISSUE THREAD

**Issue by kfigaj** [hyperledger/aries-cloudagent-python#1685]
When an agent is asked about the invitation with the public set to true it creates the data where connection_id is set to null.

![connection_id_null](https://user-images.githubusercontent.com/1562375/159930703-8d18be24-22ec-411f-9fae-c274564b92b7.png)

Interestingly, when another agent uses this public invitation, in response the connection id will be set correctly. 

I assume it is a bug, as there are protocols that require the connection_id like the basic message.

**Comment by kfigaj** [comment]
@TimoGlastra Can you possibly give me a hint is this response without a connection_id a bug as I think in the agent/maybe configuration or is this by design?

**Comment by dbluhm** [comment]
This is by design. At this stage, there is no connection record within ACA-Py. The invitation simply indicates the ability to connect and any agents forming connections through that invitation will cause a new connection record to be created.

**Comment by kfigaj** [comment]
@dbluhm Thank you for the answer. So the connection_id will be assigned later on, when someone actually makes this connection. I understand that the inviter will get the connection_id only then.
