### ISSUE TITLE
ImageUrl is absend for OOB invitation

### ISSUE THREAD

**Issue by bandirom** [hyperledger/aries-cloudagent-python#1686]
Init data:
env ACAPY_IMAGE_URL: http://localhost/alice-image.jpg (only for example)
image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1

### Connection invitation

Request URL:
`http://192.168.1.106:10000/connections/create-invitation`

```json
{
    "handshake_protocols": [
        "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/didexchange/1.0"
    ],
    "use_public_did": false
}
```

Response:

![image](https://user-images.githubusercontent.com/46032838/159936686-5a1389ae-5a13-43d5-9dde-52b1de4ead7e.png)

You can see that the `imageUrl` key present in the response

### OOB invitation:

Request URL:
`http://192.168.1.106:10000/out-of-band/create-invitation`

```json
{
"handshake_protocols": [
    "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/didexchange/1.0"
  ],
  "use_public_did": false
}
```

Response:

![image](https://user-images.githubusercontent.com/46032838/159936144-daa6088f-7b16-49a0-8c9c-8b90893ee7c1.png)

`imageUrl` is absend in the response

**Comment by bandirom** [comment]
Also tested with `py36-1.16-1_0.7.4-rc0` and the issue was not solved

**Comment by andrewwhitehead** [comment]
The [outofband RFC](https://github.com/hyperledger/aries-rfcs/tree/main/features/0434-outofband) does not specify an image URL property. It's possible that other agents are adding one as a non-standard extension.
