### ISSUE TITLE
Custom agent

### ISSUE THREAD

**Issue by ShubhankerB** [hyperledger/aries-cloudagent-python#1693]
Hi,

I am new to SSI and Aries. I have already used Aries Javascript Agent in node js. There I could create a custom agent through my codes. I am trying to port from JS agent to python agent. Here also I need the functionality to create a new custom Agent and offer credentials using that agent. I could see thay you had provided 4 demo agents. 

Do I need to create a new agent by refactoring the existing source code or it can be done via external calls?
I could not find any corresponding API in swagger. 

I request yours guidance to create a new custom agent. 

Thank you a lot

**Comment by ianco** [comment]
Aca-py is a bit different from AFJ in that the agent runs as a separate process.  There are some examples in the `demo` directory.  The aca-py API is available via swagger.  The alice/faber demo code shows how to start up an aca-py agent instance and then interact with it through its API.

**Comment by ShubhankerB** [comment]
Thank you a lot for your kind attention and such a nice reply. I have been able to run ACApy agents like Alice Faber etc as provided in hyperledger training material for Aries in Linux academy. All I now need Create a new custom agent and use its API's via another application.

**Comment by ianco** [comment]
There are also some examples here:  https://github.com/hyperledger/aries-acapy-controllers

... and the BC Government has a lot of demo's and examples.  Search for "aries" under https://github.com/bcgov?q=aries&type=all&language=&sort=
