### ISSUE TITLE
Adding 'auto_verify' flag to '/present-proof/send-request' API

### ISSUE THREAD

**Issue by konda-kalyan** [hyperledger/aries-cloudagent-python#1698]
As per the discussion on Discord - ACA-PY channel, here, I am raising this issue to add 'auto_verify' flag to '/present-proof/send-request' API.

Additional info:
There is 'auto_issue' flag in /issue-credential/send-offer API which helps avoids one agent call from controller and inform agent that once holder is accepted the offer then issue the credential.

In the same way, we good to have, 'auto_verify' flag to /present-proof/send-request API request_payload. So that, after webhook call (when state is 'presentation_received'), we no need to call one more agent API (/present-proof/records/{presentation_exchange_id}/verify-presentation) for actual verification.

This improves the performance.

**Comment by DaevMithran** [comment]
@konda-kalyan this issue has been resolved.

**Comment by swcurran** [comment]
Closing based on comment above.  It would be good to get an extra comment or two on how this was resolved.
