### ISSUE TITLE
Set Public DID error with Multitenancy and Author/Endorser

### ISSUE THREAD

**Issue by frostyfrog** [hyperledger/aries-cloudagent-python#1703]
This came up while fixing test errors in PR #1696. When running `LEDGER_URL=http://test.bcovrin.vonx.io PUBLIC_TAILS_URL=https://tails-test.vonx.io BDD_EXTRA_AGENT_ARGS="{\"wallet-type\":\"askar\"}" ./run_bdd -t @T003-RFC0586` (for both askar and indy), the tests are failing while attempting to promote a did to a public did. The error that is specifically returned is `aiohttp.web_exceptions.HTTPBadRequest: No endorser connection found` which can be found in `aries_cloudagent/wallet/routes.py` on line 510. 

The code suggests that the call to `get_endorser_connection_id(profile: Profile)` is not returning a connection ID like it should.

**Comment by MajdT51** [comment]
I'm trying to use this new feature and getting this errors in the logs

curl -X 'POST' \
  'http://localhost:11000/wallet/did/public?did=42gXHkTTzGBDb28EopJLRU&conn_id=785cd5b6-c915-4576-9213-9d9bef01771d&create_transaction_for_endorser=true

> 2022-04-02 11:45:20,894 aiohttp.server ERROR Error handling request
> Traceback (most recent call last):
>   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
>     resp = await request_handler(request)
>   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_app.py", line 504, in _handle
>     resp = await handler(request)
>   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 117, in impl
>     return await handler(request)
>   File "/home/indy/aries_cloudagent/admin/server.py", line 159, in ready_middleware
>     return await handler(request)
>   File "/home/indy/aries_cloudagent/admin/server.py", line 196, in debug_middleware
>     return await handler(request)
>   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
>     return await handler(request)
>   File "/home/indy/aries_cloudagent/admin/server.py", line 339, in check_multitenant_authorization
>     return await handler(request)
>   File "/home/indy/aries_cloudagent/admin/server.py", line 383, in setup_context
>     return await task
>   File "/home/indy/aries_cloudagent/wallet/routes.py", line 437, in wallet_set_public_did
>     context.profile, context, context.session, did, write_ledger=write_ledger
>   File "/home/indy/aries_cloudagent/wallet/routes.py", line 516, in promote_wallet_public_did
>     session, connection_id
> UnboundLocalError: local variable 'connection_id' referenced before assignment

<img width="565" alt="image" src="https://user-images.githubusercontent.com/50261972/161381805-f701341f-7e8f-482f-9c3c-0c8e0d54a448.png">

For the Author Agent:
* Not setting any flags
* Those are the metadata of my author connections 785cd5b6-c915-4576-9213-9d9bef01771d
```json
{
  "results": {
    "endorser_info": {
      "endorser_did": "7rB93fLvW5kgujZ4E57ZxL",
      "endorser_name": "end-endorser"
    },
    "transaction_jobs": {
      "transaction_my_job": "TRANSACTION_AUTHOR",
      "transaction_their_job": "TRANSACTION_ENDORSER"
    }
  }
}
```
For the endorser agent 
* I have the following flags     
         --endorser-protocol-role endorser \
        --endorser-endorse-with-did 7rB93fLvW5kgujZ4E57ZxL \
        --auto-endorse-transactions
* connection 89bee7f3-9bfd-4af8-aeaf-c8d0b0668e5c metadata    
```json    
 {
  "results": {
    "transaction_jobs": {
      "transaction_their_job": "TRANSACTION_AUTHOR",
      "transaction_my_job": "TRANSACTION_ENDORSER"
    }
```

**Comment by ianco** [comment]
I'll take a look at this one

**Comment by MajdT51** [comment]
@ianco 
I'm still not able to do it. it does not find an endorser connection

Agent-Author (--endorser-protocol-role author)
Agent-Endorser (--endorser-protocol-role endorser)

Both have connection in state **completed**
**Agent-Author:** 
  ```
  curl -X 'GET' \
  'http://localhost:11000/connections/f3eaee3f-0503-4ae0-a9c2-55a049a21f9d/metadata' \
  -H 'accept: application/json'
```
```
{
  "results": {
    "transaction_jobs": {
      "transaction_my_job": "TRANSACTION_AUTHOR",
      "transaction_their_job": "TRANSACTION_ENDORSER"
    },
    "endorser_info": {
      "endorser_did": "7rB93fLvW5kgujZ4E57ZxL",
      "endorser_name": "EndorserX1"
    }
  }
} 
```

**Agent-Endorser:**
 ```
 curl -X 'GET' \
  'http://localhost:11001/connections/0c36238e-f9ce-49f6-a717-a069386938da/metadata' \
  -H 'accept: application/json'
```
```
{   "results": {     "transaction_jobs": {       "transaction_their_job": "TRANSACTION_AUTHOR",       "transaction_my_job": "TRANSACTION_ENDORSER"     }   } }
```
**Problem:**

 **Agent-Author:** 
When im trying to set this did `FfkjDhgvq1dc673H8beEqJ` as public (already registered https://indy-test.bosch-digital.de/browse/domain?page=1&query=FfkjDhgvq1dc673H8beEqJ&txn_type=)
```
curl -X 'POST' \
  'http://localhost:11000/wallet/did/public?did=FfkjDhgvq1dc673H8beEqJ&conn_id=f3eaee3f-0503-4ae0-a9c2-55a049a21f9d&create_transaction_for_endorser=true' \
  -H 'accept: application/json' \
  -d ''
```
I get `400: No endorser connection found`

**Comment by ianco** [comment]
@MajdT51 I'll take a look

**Comment by ianco** [comment]
@MajdT51 please see PR https://github.com/hyperledger/aries-cloudagent-python/pull/1726

This fixes your use case, where you're provided an endorser connection_id explicitly.

Note that you can also set the `--endorser-alias` parameter on the author and then aca-py will automatically retrieve the appropriate endorser connection (based on a connection with a matching `alias`).

**Comment by MajdT51** [comment]
> @MajdT51 please see PR #1726
> 
> This fixes your use case, where you're provided an endorser connection_id explicitly.
> 
> Note that you can also set the `--endorser-alias` parameter on the author and then aca-py will automatically retrieve the appropriate endorser connection (based on a connection with a matching `alias`).

I can confirm that PR solved this error https://github.com/hyperledger/aries-cloudagent-python/issues/1703#issuecomment-1095121742

Thanks
