### ISSUE TITLE
GET /schemas/created returns duplicates

### ISSUE THREAD

**Issue by marcos-carretero** [hyperledger/aries-cloudagent-python#1707]
This issue is similar to #678, but manifests without sending multiple POST /schemas.

This issue was observed in the IDIM (Dev) ACA-Py instance: 
`"serviceEndpoint": "https://idim-agent-dev.apps.silver.devops.gov.bc.ca"`

### Steps to reproduce:
1. Create a new schema using the `POST /schemas` endpoint
2. Invoke the `GET /schemas/created` method

#### Expected results:

- A single schema is returned for each schema created
```
{
  "schema_ids": [
    "XpgeQa93eZvGSZBZef3PHn:2:BC Person Credential (Dev):0.0.1"
  ]
}
```

#### Actual results:

- Two schema_id records are returned for the same value

```
{
  "schema_ids": [
    "XpgeQa93eZvGSZBZef3PHn:2:BC Person Credential (Dev):0.0.1",
    "XpgeQa93eZvGSZBZef3PHn:2:BC Person Credential (Dev):0.0.1"
  ]
}
```

**Comment by marcos-carretero** [comment]
I have also observed that `GET /credential-definitions/created` also returns duplicates.

**Comment by swcurran** [comment]
Closing this issue as completed based on #1721
