### ISSUE TITLE
Make connection id optional if revoking with notification and cred_ex_id is present

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#1712]
Currently when you want to revoke a credential and send a revocation notification you need to pass in the connection id. This makes sense if revoking using the `cred_rev_id` and `rev_reg_id` properties. However if revoking using the cred_ex_id we can take the connection id from the credential exchange record (if not using connectionless).

Thoughts on this (@dbluhm?)?

**Comment by dbluhm** [comment]
Thinking back to some of the exchanges @ianco and I had on the original PR for revocation notification, I'm led to believe that, in practice, it will be uncommon for us to retain the credential exchange record. I don't see any problem letting the connection id be optional if we do have the cred ex record though. :slightly_smiling_face:

**Comment by swcurran** [comment]
For cleanliness of the repo, I'm going to close this one. It's a nice to have and I don't expect anyone to implement it. For production use cases, I think we should discourage using the ACA-Py wallet for business purposes (such as long term tracking of issuances).

Feel free to reopen if you think this is more important than I do.
