### ISSUE TITLE
Asynctest replacement

### ISSUE THREAD

**Issue by andrewwhitehead** [hyperledger/aries-cloudagent-python#1717]
The `asynctest` library which we use extensively in unit tests is no longer being maintained, and does not function properly under Python 3.8+.

Coincidentally, Python 3.8 with mock 4.0 introduces some tools ([IsolatedAsyncioTestCase](https://docs.python.org/3/library/unittest.html#unittest.IsolatedAsyncioTestCase) and [AsyncMock](https://docs.python.org/3/library/unittest.mock.html?highlight=asyncmock#unittest.mock.AsyncMock)) which might be sufficient to replace it. It looks like there is a [backwards-compatible stub](https://pypi.org/project/mock/) which could be required for testing in Python 3.6 and 3.7.

There would be some changes required to all async test cases (using `asyncSetUp` instead of `async def setUp` for example), and we will probably want to try porting some more advanced test cases first in order to check if any other features of `asynctest` are required.

**Comment by swcurran** [comment]
For anyone wanting to contributing and to get a good view on the scope of ACA-Py, this would be a good task.
