### ISSUE TITLE
ledger read operations with multiledger enabled causes timeouts and failure

### ISSUE THREAD

**Issue by DhiaSlm** [hyperledger/aries-cloudagent-python#1728]
Acapy version: 0.7.3
Wallet: Indy SDK
multi-ledger mode enabled, same behavior for multi-tenancy enabled or disabled.
An example of read operation using Acapy endpoint: GET /ledger/did-endpoint causes timeouts and long latency, the following message (extract) seems to be logged repeatedly until saturation of the log file:
`...
aries-cloud-agent-institutional         | 2022-04-04 13:33:06,898 indy.libindy.native.indy.services.pool.pool WARNING 	src/services/pool/pool.rs:360 | Unexpected timeout: req_id 4pHhuT5Lu48Y7Zsk3mRTK4buPtvEK26zjuaQ3s4mbn1f, node_alias Bundesdruckerei
aries-cloud-agent-institutional         | Error grabbing logs: unexpected EOF`

Even thought the request is successful, after the first request the above mentioned issue seems to increase the response latency every time the same endpoint is fired again. 

With Aries Askar wallet, the same endpoint fails completely with the following message (extract):

`...
aries-cloud-agent-institutional         | 2022-04-04 11:19:18,400 aries_cloudagent.admin.server ERROR Handler error with exception: Validation error: Consistency proof verification failed
aries-cloud-agent-institutional         | Traceback (most recent call last):
aries-cloud-agent-institutional         |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 163, in ready_middleware
aries-cloud-agent-institutional         |     return await handler(request)
...
`

**Comment by swcurran** [comment]
This is likely caused by the specific ledgers that you are using.  Beyond increasing the timeouts, there is little that can be done in ACA-Py for this AFAIK.  Adding support for `did:indy`, where we don't need to send the requests against all of the ledgers -- only the correct one -- would be a huge a help.

I'm going to close. Please reopen if you have specific ideas on what could be done to make this work better.
