### ISSUE TITLE
Complete GettingStarted ToDo Documentation

### ISSUE THREAD

**Issue by SmithSamuelM** [hyperledger/aries-cloudagent-python#173]
The Getting Started Document 

https://github.com/hyperledger/aries-cloudagent-python/tree/master/docs/GettingStartedAriesDev

Lists several documents that are To Do items:
Request filling in. Especially the credential attributes to better understand how to use Sovrin ZCP credentials.

To Do: Establishing a connection between Aries Agents
To Do: Issuing an Indy credential: From Issuer to Holder/Prover
To Do: Presenting an Indy credential: From Holder/Prover to Verifier
To Do: Next steps: Creating your own Aries Agent

**Comment by swcurran** [comment]
Revamping the documentation.  This will not be relevant — closing.
