### ISSUE TITLE
Case sensitive role parameter with /ledger/register-nym 

### ISSUE THREAD

**Issue by tdiesler** [hyperledger/aries-cloudagent-python#1731]
This works ...

```
POST /ledger/register-nym?did=CQ6rwbmiRBBPQZm7K2nyif&verkey=7DKi3...k2a26&role=ENDORSER
```

This doesn't

```
POST /ledger/register-nym?did=CQ6rwbmiRBBPQZm7K2nyif&verkey=7DKi3...k2a26&role=endorser
```

CrossRef: https://github.com/hyperledger-labs/acapy-java-client/issues/33

**Comment by swcurran** [comment]
That is an Indy constraint that I don't think we should mess with in ACA-Py.

Closing this issue. Please reopen if you think it appropriate.
