### ISSUE TITLE
Swagger no load

### ISSUE THREAD

**Issue by jmerino12** [hyperledger/aries-cloudagent-python#1762]
When I run faber or alice, on my localhost, or in play docker, and go to the swagger url it doesn't load.

on page  [Play Docker](https://labs.play-with-docker.com/). I deploy the [Python agent](https://github.com/hyperledger/aries-cloudagent-python/tree/main/demo#the-alicefaber-python-demo) 
using the following command:
```sh
git clone https://github.com/hyperledger/aries-cloudagent-python
cd aries-cloudagent-python/demo
LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo faber --aip 10
```

when it is up, I go to the url with port `8021`, and the swagger does not load, in turn I make requests through the insomnia tool and there is a time request.
same thing happens on my localhost.
![Captura de Pantalla 2022-05-06 a la(s) 8 18 51 a m](https://user-images.githubusercontent.com/39765924/167139411-51f7d354-0c2a-476f-8bff-796bde96c77c.png)

![Captura de Pantalla 2022-05-06 a la(s) 8 18 59 a m](https://user-images.githubusercontent.com/39765924/167139418-cf1c92fa-3ab1-4952-b2b7-85ac92ea5bb6.png)

**Comment by ianco** [comment]
@jmerino12 can you provide some more details?  What platform are you on, what command(s) are you using to run the alice/faber demo (plus indy ledger, etc), what url are you trying to connect to, and are there any error messages showing up in the alice/faber consoles?

**Comment by jmerino12** [comment]
@ianco update

**Comment by ianco** [comment]
Hmmmm I'm not sure, I just tested this just now and I'm able to load the swagger page.

<img width="1350" alt="Screen Shot 2022-05-06 at 7 13 30 AM" src="https://user-images.githubusercontent.com/1852309/167150682-6bdd4b33-4ff9-4424-86c3-3f5f7a4ef9e4.png">

**Comment by ianco** [comment]
When you load `http://<host>:8021` it does a redirect to `http://<host>:8021/api/docs`, it's possible that the redirect isn't redirecting ...

Try loading directly `http://<host>:8021/api/docs` in your browser and see if that works

**Comment by jmerino12** [comment]
@ianco  yes, now i charge.
