### ISSUE TITLE
Bug in OOB invitation? "their_role" is "inviter" on both sides

### ISSUE THREAD

**Issue by docmanni** [hyperledger/aries-cloudagent-python#1763]
Using aca-py 0.7.4-rc1, I'm facing the issue that after an OOB invitation (with attached presentation request, if that plays any role) and a successful establishment of the connections on both agents, both connection records show "their_role" as "inviter". Is this intended behaviour? How can I find out who actually assembled the invitation and who received it?

This is the connection record on the inviter's (Alice) agent:
<pre>
{
      "rfc23_state": "completed",
      "connection_protocol": "connections/1.0",
      "invitation_key": "8PPDCpDvLn4WJXftHrAjF69KBnEf8ZiAhcTUBCZHXJwR",
      "routing_state": "none",
      "updated_at": "2022-05-06T16:49:25.438834Z",
      "invitation_msg_id": "08ee8523-5105-44fe-9cb8-acd028820d19",
      "state": "active",
      "their_label": "Bob",
      "created_at": "2022-05-06T16:46:45.991546Z",
      "accept": "auto",
      "connection_id": "458653c3-d8f0-4401-8e66-fdf76fd53c7a",
      "invitation_mode": "once",
      "my_did": "Fr92wHBfGfbDsb84vwLUb1",
      "their_role": "inviter",
      "their_did": "HTjP7zrUj6qpnA8DQ2LA8R",
      "alias": "Alice Company"
}
</pre>
This is the connection record on the agent where a user receives the invitation (Bob):
<pre>
{
      "their_public_did": "EYyXxsd5sMbVm8Rz2yQuSH",
      "created_at": "2022-05-06T16:49:22.153565Z",
      "updated_at": "2022-05-06T16:49:25.644872Z",
      "their_label": "Alice",
      "request_id": "0bbff8df-307e-4ae1-836a-2ddf89b166ac",
      "their_did": "Fr92wHBfGfbDsb84vwLUb1",
      "invitation_msg_id": "08ee8523-5105-44fe-9cb8-acd028820d19",
      "connection_protocol": "didexchange/1.0",
      "connection_id": "a2f3646d-8b32-4c5d-b87c-134b8b0dc6e4",
      "invitation_mode": "once",
      "routing_state": "none",
      "state": "active",
      "my_did": "HTjP7zrUj6qpnA8DQ2LA8R",
      "rfc23_state": "completed",
      "their_role": "inviter",
      "accept": "manual"
}
</pre>

Notable differences: 
    1. on the first agent, the connection request is automatically accepted, the second one is set to "manual".
    2. the connection protocols are different (I haven't set them explicitly, though)
    
Both agents are started without the "--auto-accept-invites" flag, but that does not seem to have an influence on Alice's agent as this connection is accepted automatically nevertheless. Bob's connection has to be accepted manually, that works as intended.

Alice's agent is started with the "--public-invites" flag, Bob's agent is not.

Setting the "auto_accept" parameter when creating the OOB invitation to false or true has no effect, i.e. I'm facing the same outcome.

Further, in the OOB create-invitation result it says:
`"handshake_protocols": ["did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/didexchange/1.0"]`

So, I don't know where the connection_protocol is actually changed to "connections/1.0".

The "use_existing_connections" and "auto_accept" are both set to false when calling "/out-of-band/receive-invitation", no mediator involved.

Are those different connection protocols the reason why the roles cannot be figured out correctly? How can I solve this problem?

Thanks in advance for your kind help!

**Comment by shaangill025** [comment]
I had tested this using `0.7.4-rc1` and also tested extensively recently using `ACA-Py main`,  their roles are consistent/correct. For me, Alice has `"their_role": "invitee"` and  Bob has `"their_role": "inviter"`. I am not sure what happened regarding the protocol mismatch, I was unable to replicate this in my testing.
