### ISSUE TITLE
ACA-Py demo bug Play With Docker: waiting for connection (faber) persists even after starting Alice

### ISSUE THREAD

**Issue by kentbull** [hyperledger/aries-cloudagent-python#1765]
The Faber agent hangs on "Waiting for connection..." after following the [instructions](https://github.com/hyperledger/aries-cloudagent-python/tree/main/demo#the-alicefaber-python-demo) for the Play With Docker variant.

Faber:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/65027257/167274047-53e8e5f1-73bb-42ca-9b4a-5d87b2e17100.png">

Alice:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/65027257/167274053-0be9e0fd-18b3-4491-a4dd-93f2db1025d4.png">

**Comment by swcurran** [comment]
That is the expected behaviour. It is waiting for the user to copy the invitation and paste it into the Alice window.  When done, the connection will be established and the Faber agent will move forward.

**Comment by kentbull** [comment]
Ok, I must be missing something or the instructions are unclear, at least to me. I supposed that the Faber instance would output an invitation. Did I just misinterpret the output?

**Comment by swcurran** [comment]
If you scroll back in terminal, you will see the invitation -- immediately above the QR code.  It is copied and then pasted into the Alice terminal.  At the start Faber and Alice know nothing about each other, and the invitation must get (in this case) from Faber to Alice somehow.  The techniques used here are copy/paste and QR code.

![demo-faber-invite](https://user-images.githubusercontent.com/1018050/168310668-3cc5b1b4-c226-4daf-a0c5-0f5aed45b084.jpg)

**Comment by kentbull** [comment]
Right, I just got this to work yesterday. Closing this issue.
