### ISSUE TITLE
ACA-Py demo bug on ./run_demo faber: Exception: Timed out waiting for agent process to start (status=None). Admin URL: http://host.docker.internal:8021/status

### ISSUE THREAD

**Issue by kentbull** [hyperledger/aries-cloudagent-python#1766]
A timeout exception on the Admin URL: http://host.docker.internal:8021/status occurs upon starting the Faber demo at the [The Alice/Faber Python demo](https://github.com/hyperledger/aries-cloudagent-python/tree/main/demo#the-alicefaber-python-demo) step.

Repro steps:
1. Use an M1 Mac
2. Start up the VON network with `./manage start --logs`
3. Start up Faber with `./run_demo faber`

And you will receive the following error:
```
$ ./run_demo faber
Preparing agent image...
sha256:7467603d6daa15555d1e3e44546e9e4f5f357afe06f490b95e04201450c739dd
Trying to detect ngrok service endpoint
ngrok not detected for agent endpoint
DOCKERHOST=host.docker.internal
DOCKER_ENV=-e LOG_LEVEL= -e RUNMODE=docker -e DOCKERHOST=host.docker.internal -e AGENT_PORT=8020 -e TRACE_TARGET=log -e TRACE_TAG=acapy.events -e TRACE_ENABLED=
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Starting [faber] agent with args [--port 8020]
Initializing demo agent faber with AIP 20 and credential type indy

#1 Provision an agent and wallet, get back configuration details
Started webhook listener on port: 8022
Faber      | Registering faber.agent ...
Faber      | nym_info: {'did': '93Syvm8PJHmLU6GmWbQeTU', 'seed': 'd_000000000000000000000000446834', 'verkey': '5PELgxsYqq8bma9aRyGqtVWjN3NmhxxGpSD8tDRENpnU'}
Faber      | Registered DID: 93Syvm8PJHmLU6GmWbQeTU
Created public DID
Faber      | ['/home/indy/.pyenv/versions/3.6.13/bin/python', '-m', 'aries_cloudagent', 'start', '--endpoint', 'http://host.docker.internal:8020', '--label', 'faber.agent', '--auto-ping-connection', '--auto-respond-messages', '--inbound-transport', 'http', '0.0.0.0', '8020', '--outbound-transport', 'http', '--admin', '0.0.0.0', '8021', '--admin-insecure-mode', '--wallet-type', 'indy', '--wallet-name', 'faber.agent446834', '--wallet-key', 'faber.agent446834', '--preserve-exchange-records', '--auto-provision', '--public-invites', '--emit-new-didcomm-prefix', '--genesis-transactions', '{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node1","blskey":"4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSEimFF6nsQ6M41QvhM2Z33nves5vfSn9n1UwNFJBYtWVnHYMATn76vLuL3zU88KyeAYcHfsih3He6UHcXDxcaecHVz6jhCYz1P2UZn2bDVruL5wXpehgBfBaLKm3Ba","blskey_pop":"RahHYiCvoNCtPTrVtP7nMC5eTYrsUA8WjXbdhNc8debh1agE9bGiJxWBXYNFbnJXoXhWFMvyqhqhRoq737YQemH5ik9oL7R4NTTCz2LEZhkgLJzB3QRQqJyBNyv7acbdHrAT8nQ9UkLbaVL9NBpnWXBTw4LEMePaSHEw66RzPNdAX1","client_ip":"host.docker.internal","client_port":9702,"node_ip":"host.docker.internal","node_port":9701,"services":["VALIDATOR"]},"dest":"Gw6pDLhcBcoQesN72qfotTgFa7cbuqZpkX3Xo6pLhPhv"},"metadata":{"from":"Th7MpTaRZVRYnPiabds81Y"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"fea82e10e894419fe2bea7d96296a6d46f50f93f9eeda954ec461b2ed2950b62"},"ver":"1"}\n{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node2","blskey":"37rAPpXVoxzKhz7d9gkUe52XuXryuLXoM6P6LbWDB7LSbG62Lsb33sfG7zqS8TK1MXwuCHj1FKNzVpsnafmqLG1vXN88rt38mNFs9TENzm4QHdBzsvCuoBnPH7rpYYDo9DZNJePaDvRvqJKByCabubJz3XXKbEeshzpz4Ma5QYpJqjk","blskey_pop":"Qr658mWZ2YC8JXGXwMDQTzuZCWF7NK9EwxphGmcBvCh6ybUuLxbG65nsX4JvD4SPNtkJ2w9ug1yLTj6fgmuDg41TgECXjLCij3RMsV8CwewBVgVN67wsA45DFWvqvLtu4rjNnE9JbdFTc1Z4WCPA3Xan44K1HoHAq9EVeaRYs8zoF5","client_ip":"host.docker.internal","client_port":9704,"node_ip":"host.docker.internal","node_port":9703,"services":["VALIDATOR"]},"dest":"8ECVSk179mjsjKRLWiQtssMLgp6EPhWXtaYyStWPSGAb"},"metadata":{"from":"EbP4aYNeTHL6q385GuVpRV"},"type":"0"},"txnMetadata":{"seqNo":2,"txnId":"1ac8aece2a18ced660fef8694b61aac3af08ba875ce3026a160acbc3a3af35fc"},"ver":"1"}\n{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node3","blskey":"3WFpdbg7C5cnLYZwFZevJqhubkFALBfCBBok15GdrKMUhUjGsk3jV6QKj6MZgEubF7oqCafxNdkm7eswgA4sdKTRc82tLGzZBd6vNqU8dupzup6uYUf32KTHTPQbuUM8Yk4QFXjEf2Usu2TJcNkdgpyeUSX42u5LqdDDpNSWUK5deC5","blskey_pop":"QwDeb2CkNSx6r8QC8vGQK3GRv7Yndn84TGNijX8YXHPiagXajyfTjoR87rXUu4G4QLk2cF8NNyqWiYMus1623dELWwx57rLCFqGh7N4ZRbGDRP4fnVcaKg1BcUxQ866Ven4gw8y4N56S5HzxXNBZtLYmhGHvDtk6PFkFwCvxYrNYjh","client_ip":"host.docker.internal","client_port":9706,"node_ip":"host.docker.internal","node_port":9705,"services":["VALIDATOR"]},"dest":"DKVxG2fXXTU8yT5N7hGEbXB3dfdAnYv1JczDUHpmDxya"},"metadata":{"from":"4cU41vWW82ArfxJxHkzXPG"},"type":"0"},"txnMetadata":{"seqNo":3,"txnId":"7e9f355dffa78ed24668f0e0e369fd8c224076571c51e2ea8be5f26479edebe4"},"ver":"1"}\n{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node4","blskey":"2zN3bHM1m4rLz54MJHYSwvqzPchYp8jkHswveCLAEJVcX6Mm1wHQD1SkPYMzUDTZvWvhuE6VNAkK3KxVeEmsanSmvjVkReDeBEMxeDaayjcZjFGPydyey1qxBHmTvAnBKoPydvuTAqx5f7YNNRAdeLmUi99gERUU7TD8KfAa6MpQ9bw","blskey_pop":"RPLagxaR5xdimFzwmzYnz4ZhWtYQEj8iR5ZU53T2gitPCyCHQneUn2Huc4oeLd2B2HzkGnjAff4hWTJT6C7qHYB1Mv2wU5iHHGFWkhnTX9WsEAbunJCV2qcaXScKj4tTfvdDKfLiVuU2av6hbsMztirRze7LvYBkRHV3tGwyCptsrP","client_ip":"host.docker.internal","client_port":9708,"node_ip":"host.docker.internal","node_port":9707,"services":["VALIDATOR"]},"dest":"4PS3EDQ3dW1tci1Bp6543CfuuebjFrg36kLAUcskGfaA"},"metadata":{"from":"TWwCRQRZ2ZHMJFn9TzLp7W"},"type":"0"},"txnMetadata":{"seqNo":4,"txnId":"aa5e817d7cc626170eca175822029339a444eb0ee8f0bd20d3b0b76e566fb008"},"ver":"1"}\n', '--seed', 'd_000000000000000000000000446834', '--webhook-url', 'http://host.docker.internal:8022/webhooks', '--monitor-revocation-notification', '--trace-target', 'log', '--trace-tag', 'acapy.events', '--trace-label', 'faber.agent.trace', '--auto-accept-invites', '--auto-accept-requests', '--auto-store-credential']
Shutting down agent ...
Faber      |
Faber      | ::::::::::::::::::::::::::::::::::::::::::::::
Faber      | :: faber.agent                              ::
Faber      | ::                                          ::
Faber      | ::                                          ::
Faber      | :: Inbound Transports:                      ::
Faber      | ::                                          ::
Faber      | ::   - http://0.0.0.0:8020                  ::
Faber      | ::                                          ::
Faber      | :: Outbound Transports:                     ::
Faber      | ::                                          ::
Faber      | ::   - http                                 ::
Faber      | ::   - https                                ::
Faber      | ::                                          ::
Faber      | :: Public DID Information:                  ::
Faber      | ::                                          ::
Faber      | ::   - DID: 93Syvm8PJHmLU6GmWbQeTU          ::
Faber      | ::                                          ::
Faber      | :: Administration API:                      ::
Faber      | ::                                          ::
Faber      | ::   - http://0.0.0.0:8021                  ::
Faber      | ::                                          ::
Faber      | ::                           ver: 0.7.4-rc1 ::
Faber      | ::::::::::::::::::::::::::::::::::::::::::::::
Faber      |
Faber      | Listening...
Faber      |
Faber      |
Faber      | Shutting down
Faber      | 2022-05-08 13:01:13,800 aries_cloudagent.commands.start ERROR Exception during startup:
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/commands/start.py", line 72, in init
Faber      |     await startup
Faber      |   File "/home/indy/aries_cloudagent/commands/start.py", line 29, in start_app
Faber      |     await conductor.start()
Faber      |   File "/home/indy/aries_cloudagent/core/conductor.py", line 318, in start
Faber      |     tag_query={},
Faber      |   File "/home/indy/aries_cloudagent/storage/base.py", line 89, in find_record
Faber      |     results = await scan.fetch(2)
Faber      |   File "/home/indy/aries_cloudagent/storage/indy.py", line 291, in fetch
Faber      |     await self.close()
Faber      |   File "/home/indy/aries_cloudagent/storage/indy.py", line 321, in close
Faber      |     await non_secrets.close_wallet_search(self._handle)
Faber      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/non_secrets.py", line 449, in close_wallet_search
Faber      |     close_wallet_search.cb)
Faber      | concurrent.futures._base.CancelledError
Faber      | 2022-05-08 13:01:13,809 asyncio ERROR Task exception was never retrieved
Faber      | future: <Task finished coro=<run_loop.<locals>.done() done, defined at /home/indy/aries_cloudagent/commands/start.py:77> exception=RuntimeError('cannot reuse already awaited coroutine',)>
Faber      | Process did not terminate in time
Faber      | RuntimeError: cannot reuse already awaited coroutine
Faber      | 2022-05-08 13:01:13,966 asyncio ERROR Task was destroyed but it is pending!
ERROR:runners.agent_container:Error terminating agent:
Traceback (most recent call last):
  File "/home/indy/demo/runners/faber.py", line 421, in main
    else False,
  File "/home/indy/demo/runners/agent_container.py", line 726, in initialize
    await self.agent.start_process()
  File "/home/indy/demo/runners/support/agent.py", line 692, in start_process
    await self.detect_process()
  File "/home/indy/demo/runners/support/agent.py", line 1033, in detect_process
    + f"Admin URL: {status_url}"
Exception: Timed out waiting for agent process to start (status=None). Admin URL: http://host.docker.internal:8021/status

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/indy/demo/runners/agent_container.py", line 959, in terminate
    await self.agent.terminate()
  File "/home/indy/demo/runners/support/agent.py", line 716, in terminate
    result = await asyncio.wait_for(future, 10, loop=loop)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/indy/demo/runners/support/agent.py", line 703, in _terminate
    raise Exception(msg)
Exception: Process did not terminate in time
Faber      | task: <Task pending coro=<IndySdkStorageSearch.__del__.<locals>.cleanup() running at /home/indy/aries_cloudagent/storage/indy.py:335> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x4011d1eee8>()]>>
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/indy/demo/runners/faber.py", line 780, in <module>
    asyncio.get_event_loop().run_until_complete(main(args))
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/home/indy/demo/runners/faber.py", line 421, in main
    else False,
  File "/home/indy/demo/runners/agent_container.py", line 726, in initialize
    await self.agent.start_process()
  File "/home/indy/demo/runners/support/agent.py", line 692, in start_process
    await self.detect_process()
  File "/home/indy/demo/runners/support/agent.py", line 1033, in detect_process
    + f"Admin URL: {status_url}"
Exception: Timed out waiting for agent process to start (status=None). Admin URL: http://host.docker.internal:8021/status
```

The agent begins to start, starts the webhook, and creates a DID, and then begins shutting down the agent.

**Comment by shaangill025** [comment]
@kentbull I tested this on my end [Mac m1 (arm)] and it is working. What version of `Docker Desktop` is installed on your system? Was this working for you before?

**Comment by kentbull** [comment]
Docker version:
```
docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 10 14:08:43 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.6.1 (76265)
 Engine:
  Version:          20.10.13
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       906f57f
  Built:            Thu Mar 10 14:05:37 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.5.10
  GitCommit:        2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ```

**Comment by kentbull** [comment]
And no, this was not working for me before. It always failed. I tried again today with the same result.

I am seeing 11 instances of the following error in the logs on von-network startup:
```
von-webserver-1  | 2022-05-13 02:05:57,189|ERROR|libindy.py|	src/services/pool/state_proof/mod.rs:86 | Given signature is not for current root hash, aborting
```

**Comment by kentbull** [comment]
I was able to move on beyond this issue by using the Play With Docker approach though I'd like to assist in resolving this Run Locally With Docker issue. Let's figure this out.

**Comment by kentbull** [comment]
Yes, I can confirm a downgrade to Docker Desktop 4.0.1 solves the issue. Thanks @shaangill025

**Comment by b0ilerup** [comment]
Thanks @shaangill025 .. This resolved my issue as well.  What do you think the latest version of Docker Desktop we can go up to?

**Comment by khalithartmann** [comment]
I had the same problem with my mac m1. I upgraded to version 4.9.0  now it works :)

**Comment by jihen28** [comment]
starting the Alice demo at the [The Alice/Faber Python demo](https://github.com/hyperledger/aries-cloudagent-python/tree/main/demo#the-alicefaber-python-demo) step.

Repro steps:

Use Windows
Start up the VON network with ./manage start --logs
Start up Alice with ./run_demo alice
when I paste the invitation data i receive the following error: 


Invite details: {"@type": "https://didcomm.org/out-of-band/1.1/invitation", "@id
": "f6a82e70-592 f-4f7e-9d87-29c60d1602dd", "handshake_protocols": ["https://did
comm.org/didexcha nge/1.0"], "label": "faber.agent", "services": [{"id": "#inlin
e", "type": "did-c ommunication", "recipientKeys": ["did:key:z6MkiFgbKBcDTsCuje7
XqwrZRTfASj1dHNEZvu WD9bMwSSu6"], "serviceEndpoint": "http://host.docker.interna
l:8020"}]}

Alice      | 2023-04-04 02:27:24,183 aries_cloudagent.messaging.models.base ERRO
R Service message validation error:
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/messaging/models/base.py", line
 201, in deserialize
Alice      |
Alice      |     schema.loads(obj) if isinstance(obj, str) else schema.load(obj)
,
Shutting down agent ...
Alice      | =================
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/schema.py", line 723, in load
Alice      |     data, many=many, partial=partial, unknown=unknown, postprocess=
True
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/schema.py", line 904, in _do_load
Alice      |     raise exc
Alice      | marshmallow.exceptions.ValidationError: {'recipientKeys': {0: ['Val
ue did:key:z6MkiFgbKBcDTsCuje7XqwrZRTfASj1dHNEZvu WD9bMwSSu6 is not in W3C did:k
ey format']}}
Alice      | 2023-04-04 02:27:24,186 aries_cloudagent.admin.server ERROR Handler
 error with exception: Service schema validation failed
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/messaging/models/base.py", line
 201, in deserialize
Alice      |     schema.loads(obj) if isinstance(obj, str) else schema.load(obj)
,
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/schema.py", line 723, in load
Alice      |     data, many=many, partial=partial, unknown=unknown, postprocess=
True
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/schema.py", line 904, in _do_load
Alice      |     raise exc
Alice      | marshmallow.exceptions.ValidationError: {'recipientKeys': {0: ['Val
ue did:key:z6MkiFgbKBcDTsCuje7XqwrZRTfASj1dHNEZvu WD9bMwSSu6 is not in W3C did:k
ey format']}}
Alice      |
Alice      | The above exception was the direct cause of the following exception
:
Alice      |
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/admin/server.py", line 173, in
ready_middleware
Alice      |     return await handler(request)
Alice      |   File "/home/indy/aries_cloudagent/admin/server.py", line 210, in
debug_middleware
Alice      |     return await handler(request)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/aiohttp_apispec/middlewares.py", line 34, in validation_middleware
Alice      |     schema["schema"], request, locations=schema["locations"]
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/webargs/asyncparser.py", line 90, in parse
Alice      |     result = schema.load(parsed)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/schema.py", line 723, in load
Alice      |     data, many=many, partial=partial, unknown=unknown, postprocess=
True
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/schema.py", line 861, in _do_load
Alice      |     unknown=unknown,
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/schema.py", line 669, in _deserialize
Alice      |     index=index,
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/schema.py", line 493, in _call_and_store
Alice      |     value = getter_func(data)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/schema.py", line 662, in <lambda>
Alice      |     val, field_name, data, **d_kwargs
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/fields.py", line 342, in deserialize
Alice      |     output = self._deserialize(value, attr, data, **kwargs)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/fields.py", line 713, in _deserialize
Alice      |     result.append(self.inner.deserialize(each, **kwargs))
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/fields.py", line 342, in deserialize
Alice      |     output = self._deserialize(value, attr, data, **kwargs)
Alice      |   File "/home/indy/aries_cloudagent/protocols/out_of_band/v1_0/mess
ages/invitation.py", line 98, in _deserialize
Alice      |     return Service.deserialize(value)
Alice      |   File "/home/indy/aries_cloudagent/messaging/models/base.py", line
 205, in deserialize
Alice      |     raise BaseModelError(f"{cls.__name__} schema validation failed"
) from err
Alice      | aries_cloudagent.messaging.models.base.BaseModelError: Service sche
ma validation failed
Alice      | 2023-04-04 02:27:24,199 aiohttp.server ERROR Error handling request
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/messaging/models/base.py", line
 201, in deserialize
Alice      |     schema.loads(obj) if isinstance(obj, str) else schema.load(obj)
,
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/schema.py", line 723, in load
Alice      |     data, many=many, partial=partial, unknown=unknown, postprocess=
True
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/schema.py", line 904, in _do_load
Alice      |     raise exc
Alice      | marshmallow.exceptions.ValidationError: {'recipientKeys': {0: ['Val
ue did:key:z6MkiFgbKBcDTsCuje7XqwrZRTfASj1dHNEZvu WD9bMwSSu6 is not in W3C did:k
ey format']}}
Alice      |
Alice      | The above exception was the direct cause of the following exception
:
Alice      |
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/aiohttp/web_protocol.py", line 433, in _handle_request
Alice      |     resp = await request_handler(request)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/aiohttp/web_app.py", line 504, in _handle
Alice      |     resp = await handler(request)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/aiohttp/web_middlewares.py", line 117, in impl
Alice      |     return await handler(request)
Alice      |   File "/home/indy/aries_cloudagent/admin/server.py", line 173, in
ready_middleware
Alice      |     return await handler(request)
Alice      |   File "/home/indy/aries_cloudagent/admin/server.py", line 210, in
debug_middleware
Alice      |     return await handler(request)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/aiohttp_apispec/middlewares.py", line 34, in validation_middleware
Alice      |     schema["schema"], request, locations=schema["locations"]
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/webargs/asyncparser.py", line 90, in parse
Alice      |     result = schema.load(parsed)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/schema.py", line 723, in load
Alice      |     data, many=many, partial=partial, unknown=unknown, postprocess=
True
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/schema.py", line 861, in _do_load
Alice      |     unknown=unknown,
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/schema.py", line 669, in _deserialize
Alice      |     index=index,
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/schema.py", line 493, in _call_and_store
Alice      |     value = getter_func(data)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/schema.py", line 662, in <lambda>
Alice      |     val, field_name, data, **d_kwargs
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/fields.py", line 342, in deserialize
Alice      |     output = self._deserialize(value, attr, data, **kwargs)
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/fields.py", line 713, in _deserialize
Alice      |     result.append(self.inner.deserialize(each, **kwargs))
Alice      |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packag
es/marshmallow/fields.py", line 342, in deserialize
Alice      |     output = self._deserialize(value, attr, data, **kwargs)
Alice      |   File "/home/indy/aries_cloudagent/protocols/out_of_band/v1_0/mess
ages/invitation.py", line 98, in _deserialize
Alice      |     return Service.deserialize(value)
Alice      |   File "/home/indy/aries_cloudagent/messaging/models/base.py", line
 205, in deserialize
Alice      |     raise BaseModelError(f"{cls.__name__} schema validation failed"
) from err
Alice      | aries_cloudagent.messaging.models.base.BaseModelError: Service sche
ma validation failed
Alice      |
Alice      | Shutting down
Alice      | Exited with return code 0
Traceback (most recent call last):
  File "/home/indy/demo/runners/support/agent.py", line 870, in admin_request
    resp.raise_for_status()
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/cl
ient_reqrep.py", line 1010, in raise_for_status
    headers=self.headers,
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Err
or', url=URL('http://host.docker.internal:8031/out-of-band/receive-invitation?us
e_existing_connection=true')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 193, in
_run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 85, in _
run_code
    exec(code, run_globals)
  File "/home/indy/demo/runners/alice.py", line 244, in <module>
    asyncio.get_event_loop().run_until_complete(main(args))
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py",
 line 488, in run_until_complete
    return future.result()
  File "/home/indy/demo/runners/alice.py", line 138, in main
    await input_invitation(alice_agent)
  File "/home/indy/demo/runners/alice.py", line 103, in input_invitation
    connection = await agent_container.input_invitation(details, wait=True)
  File "/home/indy/demo/runners/agent_container.py", line 1067, in input_invitat
ion
    return await self.agent.input_invitation(invite_details, wait)
  File "/home/indy/demo/runners/agent_container.py", line 604, in input_invitati
on
    connection = await self.receive_invite(invite_details)
  File "/home/indy/demo/runners/support/agent.py", line 1249, in receive_invite
    params=params,
  File "/home/indy/demo/runners/support/agent.py", line 971, in admin_POST
    "POST", path, data, text, params, headers=headers
  File "/home/indy/demo/runners/support/agent.py", line 873, in admin_request
    raise Exception(f"Error: {resp_text}") from e
Exception: Error: 500 Internal Server Error

Server got itself in trouble
