### ISSUE TITLE
The type of QR code

### ISSUE THREAD

**Issue by h-kiri04** [hyperledger/aries-cloudagent-python#1768]
Is there any way to output faber QR code with Aries Connection (C_I) instead of Aries Out of band (OOB) in ver. 0.7.3?
The application I use cannot decode OOB.

**Comment by h-kiri04** [comment]
The above was caused by a QR code type that could not be resolved by the message decoder.
Currently the message decoder can resolve c_i, d_m, m, but is there any way to resolve OOB?

**Comment by ianco** [comment]
If you run `./run_demo faber --aip 10` then it will generate the `c_i` version of the invitation and QR code

(AIP = Aires Interop Profile.  `10` uses the version 1.0 version of the connection, credential and proof endpoints, and `20` uses the version 2.0 endpoints)

**Comment by h-kiri04** [comment]
I was able to generate the c_i version.
Thank you very much.
