### ISSUE TITLE
More flexible support for endpoints

### ISSUE THREAD

**Issue by andrewwhitehead** [hyperledger/aries-cloudagent-python#177]
- [x] Support multiple `--endpoint` arguments and add them all to generated DIDDocs
- [ ] Support a `--hostname` parameter and automatically derive endpoint(s) based on the inbound transports supported, when endpoints are not provided manually

**Comment by swcurran** [comment]
@andrewwhitehead - is this still needed or can we close this?

**Comment by andrewwhitehead** [comment]
It's not essential, I think we can close it.
