### ISSUE TITLE
ACA-Py demo Running Locally halted on indy-sdk#2412

### ISSUE THREAD

**Issue by kentbull** [hyperledger/aries-cloudagent-python#1772]
The Running Locally for the ACA-Py demo fails due to indy-sdk https://github.com/hyperledger/indy-sdk/issues/2412 which is caused by apt-get not finding packages.

**Comment by swcurran** [comment]
Did you have any luck resolving this?  If not -- perhaps add a PR to put a note in the docs?  Did you find anything else helpful in running locally that deserves a doc (or code) update?

Issues with running locally are difficult for us to deal with as we tend to stick with docker-type environments to avoid all of this messiness.  Even if I can get it running locally in my world, that may not translate into something that will help you. 

Sorry this is a pain.

**Comment by kentbull** [comment]
I will try it again. I had to downgrade Docker Desktop to 4.0.0 in order to get a different demo to work. Maybe that is what needs to be done here.
