### ISSUE TITLE
Is selective disclosure implemented yet?

### ISSUE THREAD

**Issue by tanjan-sj** [hyperledger/aries-cloudagent-python#1779]
Hi, my team wants to implement selective disclosure with encryption in a system that we're building. I found out in the [aries-rfcs ](https://github.com/hyperledger/aries-rfcs/blob/main/features/0646-bbs-credentials/README.md) that this is probably underway? Is it by any chance already implemented?
If not, what is a good point to start working on it?
Thanks.

**Comment by swcurran** [comment]
Selective disclosure has been working for a years with AnonCreds credentials (based on Hyperledger Indy) and with BBS+ Signatures with W3C JSON-LD Credentials.  Look in the /demo folder of the repo to get started -- default demos use AnonCreds.  There is also an instruction file on using the demo with JSON-LD credentials -- although the functionality is not as rich as with AnonCreds.

HTH.

**Comment by tanjan-sj** [comment]
Is [this](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AliceWantsAJsonCredential.md) what you meant? I cannot seem to find a way to implement selective disclosure - where an entity should be able to granularly decide which information to share. It seems in the above example, the full presentation is required to present in order to verify/validate.

**Comment by swcurran** [comment]
Sorry for the delay in responding -- I've been out of the office for a while.

The JSON-LD capability in ACA-Py does support selective disclosure capabilities for most JSON-LD structures (there are some limitations) if you use the BBS+ Signatures.  I'm not very familiar with the demo, as we are using AnonCreds for the work we do. However, in looking at the example, in this [presentation](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AliceWantsAJsonCredential.md#request-presentation-example), there is selective disclosure being used.  Note that:

- The issued credential has attributes: givenName", familyName, gender, birthCountry, birthDate
- The presentation request specifies  constraint `"limit_disclosure": "required",` -- e.g. "send only the requested attributes"
- The presentation request is requesting only fields familyName and givenName.

That's an example of selective disclosure using JSON-LD credentials.
