### ISSUE TITLE
Pool timeout Error when running aca-py

### ISSUE THREAD

**Issue by TrevorBushnell** [hyperledger/aries-cloudagent-python#1780]
I've cloned this git repo and I've created a virtual environment to install aca-py. I've then ran aca.py in the virtual environment with the following commandline args but get the following error:

![image](https://user-images.githubusercontent.com/75416642/169913635-2e7051db-dc02-471f-bc58-2c52f88676b5.png)
![image](https://user-images.githubusercontent.com/75416642/169913646-5d96222f-3c7d-4ca6-a09b-6798f582e790.png)

I've done some research and see that the reason I get this error is because of IPs/ports not matching between the nodes on the VON network, but everything that I have seen online points to fixing things in docker images of the indy-sdk, which I'm not using at all. There's nothing on how to fix this with just aries. Can someone please point me in the right direction for how to fix this?

**Comment by ianco** [comment]
The error means that your agent can't connect to your ledger.  I notice you've redacted the url of your ledger (in the `--genesis-url` parameter).  Try fetching this endpoint manually and see what IP's are in the endpoints it advertises - this is the IP your agent is trying to connect to.  Then see if you can connect to this IP from the machine where you're running your agent.
