### ISSUE TITLE
The QR code type of Acme

### ISSUE THREAD

**Issue by h-kiri04** [hyperledger/aries-cloudagent-python#1788]
Hello,
Is there any way to make acme QR code type "did:sov:" instead of "https://didcomm.org"?

I tried the following methods, but that did not change.
1) demo/runner/acme.py
	CRED_PREVIEW_TYPE = "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/1.0/credential-preview"
2) ./run_demo acme --aip 10

Thank you for your response in advance.

**Comment by ianco** [comment]
You mean the QR code for the connection invitation?  The only options implemented in the demo that affect the invite are `--aip 20` (the default) or `--aip 10`

**Comment by swcurran** [comment]
Is it possible that you have this config parameter (or environment variable) set:

```
 --emit-new-didcomm-prefix
                        Emit protocol messages with new DIDComm prefix; i.e.,
                        'https://didcomm.org/' instead of (default) prefix
                        'did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/'. [env var:
                        ACAPY_EMIT_NEW_DIDCOMM_PREFIX]
```

We are trying to get EVERYONE over to use the new `'https://didcomm.org/'`, so I would be happier to see whatever it is that is not supporting the new style fixed vs. getting ACA-Py to use the old way.

**Comment by swcurran** [comment]
Closing this -- please reopen if you have more questions.  Let us know if the ideas helped get you past your blocker.

**Comment by h-kiri04** [comment]
I'm sorry for the delay in replying.
This question has been resolved.
Also, I will make every effort to use the newer version as much as possible.
Thank you very much.
