### ISSUE TITLE
Inbound Transport now has an undocumented, required attribute is_external

### ISSUE THREAD

**Issue by frostyfrog** [hyperledger/aries-cloudagent-python#1791]
As mentioned in #1790, PR #1659 has introduced a new required attribute `is_external`. While going through the history, I noticed that in the PR, a default was set and then removed later on in this commit: https://github.com/hyperledger/aries-cloudagent-python/commit/577f34a48daea5b3c87705ab84f4f7e722afeedf#r74716748

This change caused the `HttpWsTransport` in https://github.com/hyperledger/aries-acapy-plugin-toolbox to break on startup (indicating a breaking change) due to the use of `is_external` in other parts of the code.

**Comment by shaangill025** [comment]
@frostyfrog I will appreciate if you can check if PR #1792 fixes this issue and #1790.

**Comment by swcurran** [comment]
Closing this as fixed in #1792 -- please reopen if not addressed.

**Comment by frostyfrog** [comment]
I do believe that #1792 will resolve this issue. Sorry for the late response, got bogged down with work last week.
