### ISSUE TITLE
How to turn off auto-accept-requests and auto-accept-invites?

### ISSUE THREAD

**Issue by skradha26** [hyperledger/aries-cloudagent-python#1796]
I am trying to tweak the demo in aries-cloudagent-python to test my example. I am not sure if my question is already answered. But, I was wondering how to turn off the auto-accept-requests and auto-accept-invites.

Thanks in advance.

**Comment by swcurran** [comment]
There is a `--no-auto`  argument that the demo agents use to turn off some of the auto flags. This is used in the ACA-Py OpenAPI demo documented [here](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AriesOpenAPIDemo.md).

See the code in the agent runner [here](https://github.com/hyperledger/aries-cloudagent-python/blob/00d97b3e0e6f713dfab383eb2e5e14e58472a47d/demo/runners/agent_container.py#L72) for what is not automated when using `--no-auto` flag.  That's also an area of the code where many of the startup parameters are set.
