### ISSUE TITLE
Connectionless Verification of revoked credential (as well as valid credential) not working as expected when specifying non_revoked interval in present proof request.

### ISSUE THREAD

**Issue by itsdheerajbudhiraja** [hyperledger/aries-cloudagent-python#1806]
After specifying `non_revoked` in present proof request: 

Till `aca-py release 0.7.3` - getting verified: true in response irrespective of credential is revoked or not.

With `aca-py 0.7.4-rc*` - getting verified: false irrespective of credential is revoked or not. 

Sample present proof request: 
```
{
	"name": "access",
	"names": null,
	"version": "1.0",
	"nonce": "674647785166691834257572",
	"requested_attributes": {
	  "e642366f-21c9-4163-aae8-3c37b5afd273": {
		"name": "Employee_Name",
		"restrictions": [
		  {
			"issuer_did": "Y9wFFsnqyVV4pvCyaFmASp"
		  }
		]
	  },
	  "c56954b6-3227-441d-a236-49dec8627583": {
		"name": "Employee_ID",
		"restrictions": [
		  {
			"issuer_did": "Y9wFFsnqyVV4pvCyaFmASp"
		  }
		]
	  }
	},
	"requested_predicates": {},
	"non_revoked": {
	  "from": 0,
	  "to": 1655204958
	}
  }
  ```

**Comment by itsdheerajbudhiraja** [comment]
while trying with 0.7.4-rc2,  I was getting following error on agent while generating proof request: 
```
UnboundLocalError: local variable 'transport_id' referenced before assignment
2022-06-14 10:23:27,536 aries_cloudagent.admin.server ERROR Handler error with exception: local variable 'transport_id' referenced before assignment
=================
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 159, in ready_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 196, in debug_middleware
    return await handler(request)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
```

**Comment by shaangill025** [comment]
@itsdheerajbudhiraja Proof verification is working, I tested [ACA-Py main - latest] for `non_revoked` in proof_request [present-proof v1 and v2, both revoked and non-revoked credential] using connectionless OOB exchange with Askar and Indy wallets. With `0.7.4-rc2` image there was a bug fixed with #1776 which might be causing the issue.

**Comment by itsdheerajbudhiraja** [comment]
@shaangill025  Request you to confirm non_revoked interval was specified as global level oy , not at individual attribute level. Please share request body of proof request you had used.

I am using above posted proof request, I have valid credentials from issuer in my wallet.
But in 0.7.4-rc1, that verification result is coming as verified:false.

FYI,
I am using vc-authn-oidc controller for connection less verifications and in logs I inspected agent webhook call response which itself contained verified: false. 

If you have any clue what might gone wrong. Please let me know

**Comment by itsdheerajbudhiraja** [comment]
Below is webhook from agent: 

 {"state": "verified", "thread_id": "21d99530-0e11-49e1-a82c-e25b0f8cf7f9", "initiator": "self", "verified": "false", "auto_present": false, "presentation": {"proof": {"proofs": [{"primary_proof": {"eq_proof": {"revealed_attrs": {"base_location_id": "17", "business_unit": "17", "employee_id": "17", "employee_name": "17", "local_contact_email_id": "107806195626052438802752593992200339722248894776284956324424714157186691434738", "manager_email_id": "107806195626052438802752593992200339722248894776284956324424714157186691434738"}, "a_prime": "102795493859453915735829294408344979800496700850443584902962764006934725267050672908732377965239687030367098317328956981327623154618471742773121562930736390181653121085162441148106174973124598285555500611603281741567798527238907146921416532170044718053303672934607963079977346083324922256918723765779470393148442477354183904747106688840823908244474234672156662472487125772256960871547986936637959940231463494278585038748913348108382442696328549341889869710555442729843729167722419484846731782371176683033392283826800654623485878401180801288662727898920274240258123266196884136659884405127678178736404159501714873139263", "e": "173530067650929352526226182031653513602364356706734711426857242668378905162680994609134718491894769965766321188102008734721474003072139928", "v": "807527028333876004509369786243237210777392500196123821989343714608727526601672184558935437022640892629963320135233769977052417219624337203857889557013740069208275315769701756424171369091144862655099323327551536765608206589954946992299001866470351792374309632832941494447523419874766243586745411129685547126053845142933222628860652635503162245534912193911431156440644704118812901965085823561850168561834639540897873841027527765329925070447827373274833713833836323434226375724986051754108909745567313782597934123325175778566283696886482292888248750244800109699581276677610809896145310947978788095511107592608469141272284442831593080379610329387785577009784939716979871129953607921196047241468702924272994994747277424052964381374122870426412441521998677961735004203243427728928555052511928315680339906154864538697438417302174492553127012884464171809892211175473768506790598565219504331445370800664851678801721816690295180376", "m": {"master_secret": "9175758317724173130491809817637046288695278574724226477722768106166620131112976085711855415807863331438540729797496792257189750051247157307913092908786873037631041084288541305701"}, "m2": "11293886272610603702070616725409651554315051463156302485033355802034964332832268726413571765749490124268644926861334494593237360803077965752347864997954464864523084969257033548166"}, "ge_proofs": []}}], "aggregated_proof": {"c_hash": "28930898509691847280750486890376926016220818474330712556559742513849812871477", "c_list": [[3, 46, 76, 19, 2, 225, 32, 85, 202, 40, 73, 83, 37, 208, 203, 83, 108, 207, 150, 22, 191, 95, 56, 125, 42, 107, 245, 245, 103, 91, 109, 125, 165, 23, 200, 141, 16, 255, 105, 76, 94, 123, 5, 238, 200, 75, 37, 166, 67, 44, 40, 60, 219, 143, 169, 12, 33, 98, 142, 164, 152, 32, 138, 75, 13, 97, 90, 134, 199, 78, 131, 249, 175, 18, 108, 218, 159, 65, 76, 244, 16, 133, 255, 96, 141, 76, 125, 247, 162, 185, 169, 146, 7, 31, 184, 240, 220, 7, 106, 104, 110, 87, 81, 26, 163, 201, 92, 118, 229, 30, 29, 235, 52, 77, 129, 11, 73, 236, 194, 98, 92, 235, 95, 88, 96, 23, 41, 74, 20, 16, 149, 19, 217, 43, 3, 111, 58, 228, 141, 252, 205, 148, 91, 255, 251, 48, 255, 195, 96, 178, 41, 37, 246, 160, 110, 223, 95, 77, 201, 136, 246, 9, 96, 255, 106, 252, 151, 32, 166, 134, 197, 38, 223, 46, 160, 14, 40, 192, 216, 203, 80, 216, 129, 182, 22, 72, 32, 64, 28, 5, 148, 38, 22, 240, 104, 59, 55, 0, 153, 47, 12, 228, 126, 30, 47, 22, 133, 15, 156, 42, 25, 46, 27, 178, 80, 36, 114, 189, 27, 58, 109, 38, 38, 100, 181, 13, 163, 71, 121, 88, 121, 190, 155, 173, 20, 34, 166, 215, 33, 42, 64, 225, 180, 201, 204, 19, 104, 54, 185, 30, 116, 81, 171, 71, 228, 64, 63]]}}, "requested_proof": {"revealed_attrs": {}, "revealed_attr_groups": {"3c78eb4f-c2c7-482c-9557-947b758eb318": {"sub_proof_index": 0, "values": {"Local_Contact_Email_Id": {"raw": "17@w.com", "encoded": "107806195626052438802752593992200339722248894776284956324424714157186691434738"}, "Manager_Email_Id": {"raw": "17@w.com", "encoded": "107806195626052438802752593992200339722248894776284956324424714157186691434738"}, "Employee_Name": {"raw": "17", "encoded": "17"}, "Employee_ID": {"raw": "17", "encoded": "17"}, "Base_Location_Id": {"raw": "17", "encoded": "17"}, "Business_Unit": {"raw": "17", "encoded": "17"}}}}, "self_attested_attrs": {}, "unrevealed_attrs": {}, "predicates": {}}, "identifiers": [{"schema_id": "Y9wFFsnqyVV4pvCyaFmASp:2:Employee3:1.0", "cred_def_id": "Y9wFFsnqyVV4pvCyaFmASp:3:CL:41:default", "rev_reg_id": "Y9wFFsnqyVV4pvCyaFmASp:4:Y9wFFsnqyVV4pvCyaFmASp:3:CL:41:default:CL_ACCUM:87f6db7f-a8b0-4acb-b30e-e414e85768c2"}]}, "presentation_exchange_id": "bcd3a68a-bc24-4afa-916c-7131e8dadb21", "updated_at": "2022-06-17T05:54:45.458087Z", "role": "verifier", "auto_verify": true, "presentation_request": {"nonce": "331551437322774273490016", "name": "topcoder_access", "version": "1.0", "requested_attributes": {"3c78eb4f-c2c7-482c-9557-947b758eb318": {"names": ["Employee_Name", "Employee_ID", "Base_Location_Id", "Manager_Email_Id", "Local_Contact_Email_Id", "Business_Unit"], "restrictions": [{"issuer_did": "Y9wFFsnqyVV4pvCyaFmASp"}]}}, "requested_predicates": {}, "non_revoked": {"to": 1655445249, "from": 0}}, "presentation_request_dict": {"@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/present-proof/1.0/request-presentation", "@id": "21d99530-0e11-49e1-a82c-e25b0f8cf7f9", "request_presentations~attach": [{"@id": "libindy-request-presentation-0", "mime-type": "application/json", "data": {"base64": "eyJuYW1lIjogInRvcGNvZGVyX2FjY2VzcyIsICJ2ZXJzaW9uIjogIjEuMCIsICJub25fcmV2b2tlZCI6IHsiZnJvbSI6IDAsICJ0byI6IDE2NTU0NDUyNDl9LCAicmVxdWVzdGVkX2F0dHJpYnV0ZXMiOiB7IjNjNzhlYjRmLWMyYzctNDgyYy05NTU3LTk0N2I3NThlYjMxOCI6IHsibmFtZXMiOiBbIkVtcGxveWVlX05hbWUiLCAiRW1wbG95ZWVfSUQiLCAiQmFzZV9Mb2NhdGlvbl9JZCIsICJNYW5hZ2VyX0VtYWlsX0lkIiwgIkxvY2FsX0NvbnRhY3RfRW1haWxfSWQiLCAiQnVzaW5lc3NfVW5pdCJdLCAicmVzdHJpY3Rpb25zIjogW3siaXNzdWVyX2RpZCI6ICJZOXdGRnNucXlWVjRwdkN5YUZtQVNwIn1dfX0sICJyZXF1ZXN0ZWRfcHJlZGljYXRlcyI6IHt9LCAibm9uY2UiOiAiMzMxNTUxNDM3MzIyNzc0MjczNDkwMDE2In0="}}]}, "trace": false, "created_at": "2022-06-17T05:54:09.148746Z"}

**Comment by itsdheerajbudhiraja** [comment]
Problem came out to be in aries js framework - Mobile wallet was sending incorrect proof. 

On degugging I figured out this error: 
```
2022-06-17 05:54:45,457 aries_cloudagent.indy.sdk.verifier ERROR Presentation on nonce=331551437322774273490016 cannot be validated: Timestamp on sub-proof #0 is missing vs. requested attribute group 3c78eb4f-c2c7-482c-9557-947b758eb318
```
Seems holder wallet is sending incorrect proof - Some timestamp is missing.  

Aca-py code is working fine. 

@swcurran @shaangill025

**Comment by swcurran** [comment]
Good stuff!  Thanks for digging in and confirming.

**Comment by TimoGlastra** [comment]
ACA-Py 0.7.3 (and before? Not sure what the affected versions are) contained a bug where it would mark a proof as verified if it didn't include a proof of non revocation even though the proof request requested a proof of non-revocation.

This has been fixed since and is therefore now breaking.

AFJ 0.1.0 doesn't have support for revocation yet, and that's why it is now failing with ACA-Py 0.7.4-RC. AFJ 0.2.0 will support revocation.

**Comment by swcurran** [comment]
Thanks for the explanation @TimoGlastra --- makes sense.
