### ISSUE TITLE
Endpoint in imported postgres subwallets not updated

### ISSUE THREAD

**Issue by milos-sol** [hyperledger/aries-cloudagent-python#1825]
I had acapy running in aws ec2 together with postgres DB for couple of months. 
Few days ago I got new ec2 instance where acapy currently runs so I imported all subwallets from an old ec2 inst. 
However all subwallets still use old Endpoint since they are "hard-coded" in DB so I am unable to, for example, create new connections (Error: "Connection ... not ready.")

What I did and tried so far to update Endpoint:
1. Acapy start command uses new endpoint so that should be ok.
2. I also updated Endpoint with POST wallet/set-did-endpoint with
`{
  "did": "XZcf2eM9FsfZHFFD6JYaBC",
  "endpoint": "http://newIP/8020",
  "endpoint_type": "Endpoint"
}` 
and when I execute GET wallet/get-did-endpoint, new IP is actually in Response,
`{
  "did": "XZcf2eM9FsfZHFFD6JYaBC",
  "endpoint": "http://newIP/8020"
}`
but Create Connection still uses old one in invitation_url.

3. The only way it works is when I force to overwrite service_endpoint with new IP in Create connection JSON Body like:
POST /connections/create-invitation
`{
"service_endpoint" : "http://newIP/8020"
}`

Did I forget to do something? Or is there a way maybe I can overwrite Endpoint IP in my Postgres DB? Thanks :)

**Comment by andrewwhitehead** [comment]
Is this using the connection protocol or did-exchange protocol?

**Comment by andrewwhitehead** [comment]
It looks like the endpoint is generally inherited from the mediator, which may be the base wallet in the case of multitenancy. Are there any details returned from the `/mediation/default-mediator` endpoint?

**Comment by milos-sol** [comment]
1. It is [connection protocol](https://github.com/hyperledger/aries-rfcs/blob/main/features/0160-connection-protocol/README.md).
And invitation url in our usecases is almost always presented as QR code so we can scan it with mobile wallets. 
2. I get empty Body response from `/mediation/default-mediator` Endpoint.

**Comment by andrewwhitehead** [comment]
Hmm. Has the agent been restarted at all? Maybe it's a cache issue.

**Comment by milos-sol** [comment]
I had to restart Agent couple of times, have no idea why but now all endpoints are updated. 

Thanks a lot @andrewwhitehead

**Comment by andrewwhitehead** [comment]
I think it's worth investigating to see if the cache problem can be resolved without restarting the agent.

**Comment by icc-garciaju** [comment]
The endpoint in your comment is not defining a port, is that right?
