### ISSUE TITLE
Update the performance demo to report wallet size and storage usage; test tweaks to credentials

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#183]
Once storage tracking is enabled, test:

1. Using unencrypted tags. Report back time and storage usage.
2. Purging credX records after use.
3. Using the registration credential during the test and using an tag policy that aggressively removes tags.

**Comment by andrewwhitehead** [comment]
Wallet size reports added to performance demo. Tagging policy was unworkable due to credential lookup restrictions.
