### ISSUE TITLE
 How to get the verifier's DID?

### ISSUE THREAD

**Issue by skradha26** [hyperledger/aries-cloudagent-python#1841]
how can I get the verifier's DID in the aries demo? This is in case a holder gets a proof request and holder wants to know the DID of the verifier to resolve DIDDoc to check before sending proof. I am not sure which API endpoint to use to get the DID of verifier.

**Comment by kukgini** [comment]
I'm not sure I understand correctly what you are asking.

When you received a proof request, you already connected with counter party (in this case, a verifier).
From the connection, you already get counter party's identifier of peer DID form. However, there is no way to verify that it is a reliable opponent. It only guarantees that all messages forwarded thereafter are from the original party.

So, If you want to verify a verifier, there is a way to connect with Implicit Invitation of verifier's public DID in the first place. And that public DID has to be obtained from trusted governance.

**Comment by skradha26** [comment]
Oh ok. Is there any example somewhere or some pointers?
