### ISSUE TITLE
API 'POST /credential-definitions' - revocation_registry_size should be optional when support_revocation is false

### ISSUE THREAD

**Issue by konda-kalyan** [hyperledger/aries-cloudagent-python#1843]
This API is expecting revocation_registry_size info even thouh support_revocation is false. Rev reg size should be optional when revocation is not enabled.

Additional info: This is in reference to the discussion currently going on on Discord channel. Please let me know if I can provide more info.

**Comment by swcurran** [comment]
Closing as stale -- reopen if needed.
