### ISSUE TITLE
Error accepting mediation invitation

### ISSUE THREAD

**Issue by DucDA177** [hyperledger/aries-cloudagent-python#1879]
I tried to start an agent with argument 
--mediator-invitation ws://10.35.45.136:16/?oob= ....
When agent started running, the log show errors: 
![image](https://user-images.githubusercontent.com/48557721/181463343-f10e6b0b-3309-4e2b-95b2-f7b78b3c896d.png)
Therefore, the agent not automatically set the default mediation.
Here is the scripts that I run the agent:
`PORTS="54 56 58" \
scripts/run_docker start \
--label DUCDA_MULTITENNANT \
--wallet-key DUCDA_MULTITENNANTWalletKey \
--wallet-name DUCDA_MULTITENNANTWalletName \
--genesis-url https://raw.githubusercontent.com/sovrin-foundation/sovrin/stable/sovrin/pool_transactions_builder_genesis \
--endpoint http://10.35.45.136:54/ \
--endpoint ws://10.35.45.136:56/ \
--inbound-transport http 10.35.45.136 54 \
--inbound-transport http 0.0.0.0 54 \
--inbound-transport ws 0.0.0.0 56 \
--outbound-transport http \
--outbound-transport ws \
--admin 0.0.0.0 58 \
--admin-insecure-mode \
--auto-provision \
--wallet-type indy \
--auto-accept-requests \
--auto-accept-invites \
--auto-respond-messages \
--auto-respond-credential-proposal \
--auto-respond-credential-offer \
--auto-respond-credential-request \
--auto-respond-presentation-proposal \
--auto-respond-presentation-request \
--auto-store-credential \
--auto-verify-presentation \
--debug-connections \
--connections-invite \
--webhook-url http://10.35.45.136:14444/api/Webhooks \
--emit-new-didcomm-prefix \
--replace-public-did \
--tails-server-base-url https://a174-104-28-254-75.ngrok.io \
--notify-revocation \
--monitor-revocation-notification \
--multitenant \
--multitenant-admin \
--jwt-secret blab@1234 \
--wallet-storage-type postgres_storage \
--wallet-storage-config "{\"url\":\"10.35.45.136:5432\",\"wallet_scheme\":\"MultiWalletSingleTable\"}" \
--wallet-storage-creds "{\"account\":\"postgres\",\"password\":\"duc177\",\"admin_account\":\"postgres\",\"admin_password\":\"duc177\"}" \
--mediator-invitation ws://10.35.45.136:16/?oob=eyJAdHlwZSI6ICJodHRwczovL2RpZGNvbW0ub3JnL291dC1vZi1iYW5kLzEuMC9pbnZpdGF0aW9uIiwgIkBpZCI6ICIwNTg5MmI1NC1hYmU4LTQ5OTUtYWY2MC04ZTQzNDcyMGNjZjUiLCAiaGFuZHNoYWtlX3Byb3RvY29scyI6IFsiaHR0cHM6Ly9kaWRjb21tLm9yZy9kaWRleGNoYW5nZS8xLjAiXSwgInNlcnZpY2VzIjogW3siaWQiOiAiI2lubGluZSIsICJ0eXBlIjogImRpZC1jb21tdW5pY2F0aW9uIiwgInJlY2lwaWVudEtleXMiOiBbImRpZDprZXk6ejZNa2pMaXRiRlFKanlLVGNvNjZkODhldlVkYUxmUDVXdXI5N1c4TEtCdkVkOVd5Il0sICJzZXJ2aWNlRW5kcG9pbnQiOiAid3M6Ly8xMC4zNS40NS4xMzY6MTYvIn1dLCAibGFiZWwiOiAiRFVDREEiLCJtZXRhZGF0YV9zZXQiOnt9fQ== \
`

**Comment by DucDA177** [comment]
@swcurran please kindly take a look on this issue

**Comment by shaangill025** [comment]
PR #1970 should fix this.
