### ISSUE TITLE
Retrieving cred_def_id and schema_id from the verifier side

### ISSUE THREAD

**Issue by santidediego** [hyperledger/aries-cloudagent-python#1882]
I am trying to implement a web controller that calls the aca-py API. When trying to call `/present-proof/send-request`, I wish to specify the` cred_def_id` or `schema_id` under the `restrictions` label in the proof request.

However, I am not able to find any way to get this information from the verifier´s side. As the verifier has not created the schema and definition, the endpoints `/credential-definitions​/created` and `/schemas/created` do not provide me the information I need from the ledger.

Am I missing something? Is there any way to get this information?

**Comment by swcurran** [comment]
A verifier will get this information from some other means -- e.g. from the issuer themselves, or from place that the issuer has published the information.  For example, our plan is to create a repository of Schemas and Issuers where those that publish Schemas or are Issuers can publish information about their credential types and credentials. Included in that information will be the DIDs, Schema IDs and CredDef IDs needed by the verifier.  In turn, the verifier will configure their presentation requests to use the attribute names or IDs that they need.

Hope that helps.  I'm going to close this, but feel free to ask more questions or reopen.

Hope
