### ISSUE TITLE
did:orb not accepted when creating json-ld credentials

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#1898]
In AATH, try running:  `./manage run -d acapy-main -t @DidMethod_orb`

All the tests fail with the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/webargs/asyncparser.py", line 90, in parse
    result = schema.load(parsed)
  File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 723, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 904, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'method': ['Must be one of: key, sov.']}
```

@dbluhm ?

**Comment by swcurran** [comment]
Marshmallow shouldn't be rejecting other than did:key and did:sov.  This may be related to the W3C VC work, I suspect. I think this had worked previously, but seems to have been changed at some point.  AFAIK, the did:orb tests were working when last worked on.

**Comment by swcurran** [comment]
Perhaps [here](https://github.com/hyperledger/aries-cloudagent-python/blob/d407c48cc9f041c5b27ee8f589fc0e2eaef2220d/open-api/openapi.json#L4848)?

**Comment by swcurran** [comment]
Is this test trying to register or resolve a `did:orb` DID?  If it is trying to resolve it, this should work.  If it is trying to register it, this should not work.  Given that the test is ALL ACA-Py, my guess is that this one trying to register a DID, and therefore, we can safely make the change that @ianco has proposed in AATH of disabling the did:orb tests for ACA-Py only runs.
