### ISSUE TITLE
 Unable to get all data from the API end point: present-proof-2.0/records/

### ISSUE THREAD

**Issue by skradha26** [hyperledger/aries-cloudagent-python#1905]

**Comment by skradha26** [comment]
I have been trying to get the data from the present-proof-2.0/records/ endpoint especially the value of "verified" in the json returned by the API endpoint. I just tried using the end point with the presentation exchange id I have and I don't get the entire json. When I use the endpoint directly from the browser, I get the whole JSON. I am not able to understand the reason behind the difference.

**Comment by swcurran** [comment]
Closing as stale -- reopen if needed.
