### ISSUE TITLE
invite-base-url argument for aca-py start

### ISSUE THREAD

**Issue by bandirom** [hyperledger/aries-cloudagent-python#1909]
Hello!

I defined this var in the command line as:

`      --invite-base-url http://192.168.1.104/invitation`

POST: ` /connections/create-invitation`
Payload: 
```json
{
  "my_label": "Bob",
  "recipient_keys": [
    "H3C2AVvLMv6gmMNam3uVAjZpfkcJCwDwnZn6z3wXmqPV"
  ]
}
```
In the response we see that '/invitation' added as well: 

![image](https://user-images.githubusercontent.com/46032838/186151359-bea4f6b1-e406-4733-a5ec-c76c8551d0e1.png)

I tried to receive the same result for OOB invitation

POST: ` /out-of-band/create-invitation`
Payload: 
```json
{
  "alias": "Barry",
  "handshake_protocols": [
    "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/didexchange/1.0"
  ],
  "my_label": "Invitation to Barry",
  "use_public_did": false
}
```

Response invitation url without `/invitation`

![image](https://user-images.githubusercontent.com/46032838/186152010-9f80c681-1589-47dc-9942-cc83103053c0.png)

**Comment by swcurran** [comment]
Closing as stale -- reopen if needed.
