### ISSUE TITLE
Credentials visual distinguishment

### ISSUE THREAD

**Issue by JonasNiestroj** [hyperledger/aries-cloudagent-python#1918]
## Use Case

We are experimenting, with how credentials could be visually distinguished from eachother. As an Idea we would like to transmit a small icon and potentially a hexcode with the credential. While the hexcode can easily be encoded as part of the credential, the performance of the cryptographic signing depends strongly on the credential format. To be a bit more agnostic we are therefore looking for ways to transmit this file from issuer to holder.

## Possible solutions

The icon can be added in the credential offer attachments and be mapped to the credential at the end. It seems that the offer attachments are "hardcoded" at the moment. So its not possible to give other attachments then the default `libindy-cred-0` attachment.

## Question

Is the possible solution the right one to handle this use case? Are there other solutions to solve it?

**Comment by swcurran** [comment]
We're looking to use "[Overlays Capture Architecture](https://oca.colossi.network/)" (OCA) for this.  Work has begun on implementing it in Aries.  The concept is that a Schema Publisher or Issuer publishes to a known location an "OCA Bundle" that has information useful for displaying a credential -- multilingual labels, attribute descriptions, credential name and certificate, an icon for the issuer, the name of the issuer (again, multilingual), format and encoding of the attributes, etc.

Here is a [video of Credential Branding](https://drive.google.com/drive/u/0/search?q=Credential%20Branding) in Aries Bifold that will (soon!) be driven by OCA data from the Issuer.

Here is a [presentation on OCA](https://wiki.hyperledger.org/download/attachments/71697612/video1096400111.mp4?api=v2) -- jump to 25 minutes into the presentation.  Here are the [slides](https://docs.google.com/presentation/d/1-CgRzMn10kYLnLOZVVQX4tAmG6f0E9b0O4Ybkcf-o70/edit?usp=sharing).  In the presentation are links to various works in progress on this.  

An Aries RFC ("OCA for Aries") for this is in the works.  There is an [Aries RFC on OCA](https://github.com/hyperledger/aries-rfcs/tree/main/concepts/0013-overlays), but it's really a description of OCA vs. how to use it with Aries.

We have more work to do on this, so not yet completed.

**Comment by JonasNiestroj** [comment]
@swcurran Thank you very much for all the information! That looks really promising. 
Three questions:
- I guess the slides you sent me are for another topic. Its about corporate firewalls instead of OCA. Can you send me the one about OCA? Im really interested in the various works that you already did
- Did i got it right that this will likely be the standard in the future for everything regarding extra information about a credential/schema?
- Is there already a approximate timeline about when this topic will be useable for all?

Sorry for all the questions but this feature is really needed for our whole SSI Case we are currently investigating/building. Maybe we can also help bringing this topic forward.

**Comment by swcurran** [comment]
Fixed the slides link in the comment above.   Yes -- that's the goal, to use the OCA as the standard.

We are working through the areas that need to be updated.  A number of groups are trying to coordinate on this, starting at either end -- the creation of an OCA Bundle and the consuming of the bundle in the wallet.  We've not started on being able to publish a bundle and where bundles are stored as yet, although we can get by with minimal effort there.

What is your use case and how many credentials are you dealing with?

**Comment by JonasNiestroj** [comment]
Im currently working as a developer for the swiss governement to find out if the whole indy/aries stack is usable for our future use case. In the future the swiss governement want's to issue electronic identities and other credentials for the swiss citizens. 
The count of that credentials is not defined because theoretically it's infinite. There will be a lot of different credential schemas so the visual distinguishment is needed.

**Comment by swcurran** [comment]
That's pretty much the same as we (Government of British Columbia) are working on as well. Happy to discuss what we are doing and perhaps see if we can collaborate.  We've got a mobile wallet coming to app stores Real Soon Now, plus a number of issuers and verifiers.  As we start, there are only few verifiable credentials, but we anticipate more being added quickly.

**Comment by JonasNiestroj** [comment]
I would also be happy to discuss about what we are doing. Can i contact you anywhere?

**Comment by swcurran** [comment]
Sorry for the slow response. Would be glad to connect on this -- swcurran at cloudcompass dot ca.  Please send a note and we can try to find some time to meet about this.
