### ISSUE TITLE
Storage Find_all/Query with limit and offset

### ISSUE THREAD

**Issue by berendsliedrecht** [hyperledger/aries-cloudagent-python#1919]
Hi,

I was wondering whether it would be possible, or easy to add, to find all records with a limit and offset. This is mainly needed for pagination as we want to request the records in small batches without filtering it after ACA-Py responds with all the records. I know that in an `Askar Scan` you can supply a `limit` + `offset`, but not with a `Session`, here we can only supply a `limit` which is already omitted in ACA-Py. 

@andrewwhitehead do you have any idea how we could do this? If it is technically possible I wouldn't mind taking a look and creating a PR.

-- Askar ACA-Py find_all_records
https://github.com/hyperledger/aries-cloudagent-python/blob/cbd5ceedf54659d61ac4f817d0d454345c0a72c0/aries_cloudagent/storage/askar.py#L178

-- Askar fetch_all (being called by find_all_records)
https://github.com/hyperledger/aries-askar/blob/27f062b243b91309596c1625f28f367ada9a9974/wrappers/python/aries_askar/store.py#L425

**Comment by swcurran** [comment]
Closing in favour of #3001.
