### ISSUE TITLE
IIWBOOK how to run demo link inaccessible

### ISSUE THREAD

**Issue by demos2022** [hyperledger/aries-cloudagent-python#1927]
Hi, 
I am trying to run the  IIWBOOK demo app. However, the link provided - https://vonx.io/how_to/iiwbook in the documentation is inaccessible. As per documentation, this link has details on how to run the demo. Please assist.

**Comment by WadeBarnes** [comment]
New link; https://digital.gov.bc.ca/digital-trust/projects-and-initiatives/conference-book-demo/
