### ISSUE TITLE
Slow performance with lots of connections

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#1932]
From a discord chat:

We see the delay occurring during connection creation which I believe does not use the author/endorser transaction flow. We see the delay in the inviter agent side

we noticed that for the org that is 75 days old, it has 4832 connections in its ACAPY records. And it takes 20 seconds for it new invitations to become active. 

and for an org that is newer and has only 450 connections, it takes a few seconds for the invites to become active.

is it possible that the many many connection records could be weighing down ACAPY performance when requests come in?

**Comment by PaulWen** [comment]
I have seen such kind decreases in performance with older AcaPy versions (I believe prior 0.7.0) and when using the Indy SDK instead of the Askar wallet.

Which AcaPy version has been used and is it running with the Indy SDK or Askar wallet?

**Comment by ianco** [comment]
From cchiu on Discord:  "We are using an ACAPY image based off of v0.7.3. And we are hitting Sovrin Buildernet and Sovrin Mainnet as the ledgers (not sure if that is important or not)"

Not sure if it's indy or askar wallet.

**Comment by cchiu3** [comment]
we are using indy wallet

**Comment by PaulWen** [comment]
My load tests for AcaPy version 0.7.3 + Indy wallet also show that the performance drops drastically over time: https://github.com/lissi-id/acapy-load-test-results/blob/main/AcaPy_0-7-4/Endurance_Test/04-0_7_3_indy-200rpm/report-test-results-0-END.pdf

If this is an option for you I can highly recommend switching to the Askar wallet as this has not this behavior yet: https://github.com/lissi-id/acapy-load-test-results/blob/main/AcaPy_0-7-4/Endurance_Test/02-0_7_4_askar_0_2_5-200rpm/report-test-results-0-6.pdf

**Comment by swcurran** [comment]
Lots of updates have been done in this area, including one specifically targetting lots of connections, and the use of Askar.  Closing this issue -- please reopen with more details or open a new issue.

Thanks
