### ISSUE TITLE
DID Exchange in ACA-Py 0.7.4 with explicit invitations and without auto-accept broken

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#1936]
While working with @mepeltier on testing out a few different scenarios on ACA-Py 0.7.4, we (re)discovered that the connection state after receiving a did exchange request was not being saved, making it impossible to accept the request. This was fixed in main (and included in 1.0.0-rc0) by #1881. At the time I reviewed that PR, I did not realize how big of an issue the PR was fixing. Looking at it again now, I think it warrants a patch release.

Main has seen some changes lately that likely wouldn't fit in a patch release. With that in mind, I think cherry-picking and producing a release on a separate branch is appropriate. I'd be happy to put in the effort to prepare a branch with this state.

Should we do this? Are there other fixes that should be included in a 0.7.5 patch release?
@swcurran @ianco @andrewwhitehead

**Comment by dbluhm** [comment]
Also probably worth making sure we hit this scenario in the integration tests.

**Comment by dbluhm** [comment]
I'll review PRs merged since 0.7.4 and report back whether there are any I think should also be included in a 0.7.5 patch release.

**Comment by ianco** [comment]
> Also probably worth making sure we hit this scenario in the integration tests.

The integration tests run with most of the "auto" flags on, whereas AATH runs with most of the "auto" flags off

**Comment by dbluhm** [comment]
The mobile team at Indicio is interested in seeing #1940 included in a patch.

**Comment by swcurran** [comment]
@ianco -- I tend to call #1913 a breaking change, so would prefer to leave it for 1.0.0. What is the rationale for putting it into 0.7.5?

**Comment by ianco** [comment]
> @ianco -- I tend to call #1913 a breaking change, so would prefer to leave it for 1.0.0. What is the rationale for putting it into 0.7.5?

Northern Block has specifically asked for a release with this fix

**Comment by swcurran** [comment]
Could we do that as a 1.0.0-rc1 for that?  I'm happy to do that.

**Comment by ianco** [comment]
> Could we do that as a 1.0.0-rc1 for that? I'm happy to do that.

For sure I think that would be fine.

**Comment by Durai46** [comment]
@swcurran Are you going to publish the docker image for the same?

**Comment by swcurran** [comment]
Yes.  Completing the 0.7.5 release is still a in progress -- there is at least one more PR to go.  Would it help you for me to produce a 1.0.0-rc1, or do you need the 0.7.5-rc0/0.7.5 image?

Sorry for the delay.

**Comment by Durai46** [comment]
Thank you @swcurran I would go for 0.7.5 image.

**Comment by swcurran** [comment]
Tag and image 0.7.5-rc0 exists and seems to be fine. @Durai46 and @dbluhm -- can you confirm we are good to go with "0.7.5" final?  I think it is an easy one, but just wanted to get this finished.

We've run AATH tests and things are working with one odd, but likely unrelated bit of weirdness.  If you want the details I can provide, but it's convoluted! :-(

Once I get a thumbs up I'll do a final PR for the 0.7.5 release and we'll count it done.

**Comment by dbluhm** [comment]
I haven't had a chance to give it the full battery of tests we like to run (basically just plugging into our plugins/projects and running integration tests) but I have run a few and it's looking good so far. Critically, the original problem I opened this issue for I have tested and found working in 0.7.5-rc0.

**Comment by swcurran** [comment]
OK -- Glad to hear the main issue is addressed. I'm doing a bit more and we'll make a call that it is done Real Soon Now. Please let me know if you do more and the results are good/bad.

Thanks!

**Comment by swcurran** [comment]
FYI -- the "weirdness" with AATH has been solved.  Weird answer, but now working... :-)

**Comment by dbluhm** [comment]
With 0.7.5 released, closing this issue :slightly_smiling_face:
