### ISSUE TITLE
Webhook requests include a trailing slash

### ISSUE THREAD

**Issue by karimStekelenburg** [hyperledger/aries-cloudagent-python#1939]
When providing a `--webhook-url` on startup, a trailing `/` seems to be added to the web hook requests. So if I provide `https://example.example` as the `--webhook-url` value, connection state changes are posted to `https//example.example/topic/connections/` instead of `https//example.example/topic/connections`.

This deviates from what is documented here: https://github.com/hyperledger/aries-cloudagent-python/blob/main/AdminAPI.md#administration-api-webhooks.

Although this isn't a major issue, I know it caused some confusion here and there ;)

**Comment by swcurran** [comment]
Hey @ianco -- can you figure out what to do with this?  I'm wondering if this started with an OpenShift issue?  We definitely had a "trailing /" issue come up in OpenShift deployments at some point in the past -- John raised it years ago.

I don't really care about the answer (with or without "/"), but do want to have the code and docs consistent.
