### ISSUE TITLE
Support of Ephemeral Protocol

### ISSUE THREAD

**Issue by Alexis-Falquier** [hyperledger/aries-cloudagent-python#195]
plans for aca-py to implement the ephemeral protocol? Its possible to implement through the controller as an additional functionality which is what I have done, but I think people would find it useful to have as part of it's native functionality.

**Comment by swcurran** [comment]
Thanks, Alexis.  We're going to look into it - take a look at what is in
`aries-framework-dotnet` and talk with the folks at MattrGlobal on the
state of the protocol.  Last I checked it was not in an RFC form, but I've
not checked in awhile (and am offline as I type this.).  We'll be meeting
with @tplooker at IIW and will talk to him about adding support for the
protocol.

Do have an immediate need to use it, and if so, what are you doing?  That
is always helpful as we prioritize our efforts.

**Comment by Alexis-Falquier** [comment]
Sounds good, I'll be at IIW as well would love to be there when for that discussion. we are big fans of the ephemeral protocol. 

And we are working on an api solution which would allow the use of SSI as a log in flow, for this we found ephemeral challenges to be extremely useful. I've actually integrated it through our aca controller as an additional functionality to the agent, and tested with Streetcreds wallet who have the protocol integrated in their app.

**Comment by swcurran** [comment]
A ping of @andrewwhitehead and @esune to meet with @tplooker and @Alexis-Falquier to talk over adding the ephemeral challenge to ACA-Py. Tobias mentioned in a side conversation that it was changing, so we definitely want the latest info before we add the implementation.

**Comment by Alexis-Falquier** [comment]
Related to this, has aca-py implemented the service decorator protocol? https://github.com/hyperledger/aries-rfcs/tree/master/features/0056-service-decorator

**Comment by swcurran** [comment]
We are using the ephemoral challenge with ACA-Py, where ACA-Py is in the role of the verifier.  We have an example of this you can try out with the Streetcred agent by getting a verified email credential from here, https://email-verification.vonx.io/ and using it here: https://law-society-demo.pathfinder.gov.bc.ca/.

Caveats:

- you can get an IOS Streetcred Identity Agent from the App Store
- After installing and opening the app, follow the instructions to create your wallet and enable notifications, and you will be taken to the main app screen. It's on that screen you must do some additional setup, as follows:
  - Click the link "Sovrin Network" at the top right of the screen.
     - You should be taken to the app settings for the Streetcred app.
     - Some users have reported that after clicking the link, they are only take to the main iOS settings screen. If that occurs, scroll down on that screen to find and click "Streetcred" to get to the settings specific to Streetcred.
  - Click on the "Preferred Network" setting at the bottom.
  - From the list of networks, please select the "BCovrin Test" network.
  - Click back and then return to the Streetcred app screen.
  - Verify that where it used to say "Sovrin Network", it now says "BCovrin Test Network".

**Comment by swcurran** [comment]
@Alexis-Faquier - is the support we currently have in ACA-Py sufficient for your needs?  That is, the ability to use ACA-Py as a verifier using the ephemeral challenge, based on the service decorator?  We have a live demonstration of this [here](https://github.com/bcgov/vc-authn-oidc/blob/master/docs/DemoInstructions.md).

ACA-Py still does not respond to ephemeral challenges, and does not respond to requests that include a service decorator.  Is that OK for your use cases?

**Comment by Alexis-Falquier** [comment]
In our use case we also respond to ephemeral challenges, so currently the controller handles it when one comes in instead of sending it over to the acapy instance

**Comment by tmarkovski** [comment]
Ephemeral challenge is superseded (though not officially) by Presentation Protocol with support for Service Decorator. This is currently implemented and interoperable in acapy and .net framework.

**Comment by swcurran** [comment]
Closing this for now.  We'd like to raise this in the Aries Working Group based on the idea of merging the invitation process with a prove challenge and any other potential request arriving with no pre-established connection. Changes to ACA-Py will follow once that is in place.
