### ISSUE TITLE
Create a documentation site for the ACA-Py that incorporates and organizes the current Markdown documentation

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#1951]
Create a documentation website for ACA-Py that provides both a useful structure for the documentation, adds introductory material to organize the information for different audiences and incorporates the many existing markdown documents we have in the repo.

**Comment by TimoGlastra** [comment]
For AFJ we use https://docusaurus.io/, source code can be found here: https://github.com/hyperledger/aries-javascript-docs/

**Comment by swcurran** [comment]
@amanji has been experimenting with [Material for Mkdocs](https://squidfunk.github.io/mkdocs-material/) since Hyperledger has the "insider" edition, and [Docusaurus](https://docusaurus.io/), because of the AFJ success with it.  Leaning is Docusaurus, perhaps built into ACA-Py repository, or perhaps as a separate site.  One of the features we'd like to keep is the generated internal ACA-Py code documentation that we get from [Sphinx and ReadTheDocs](https://aries-cloud-agent-python.readthedocs.io/en/latest/), but the main focus of the site will be developers getting started with ACA-Py, vs. contributors/maintainers.

**Comment by esune** [comment]
I think this is resolved by #2079

**Comment by amanji** [comment]
Soon🤞. Need to create a workflow for a multi branch build before that can be merged.

**Comment by swcurran** [comment]
First cut of site launched currently at: https://hyperledger.github.io/aries-acapy-docs

I’ll be changing the URL to a custom domain later today, and adding the 0.8.0 docs, then the 0.7.5, and likely the last of the 0.6.X line of docs as well.

I’ll probably do some more maintenance on the docs in main.

Feedback welcome!
