### ISSUE TITLE
Large amount of connections can cause performance degradation

### ISSUE THREAD

**Issue by kukgini** [hyperledger/aries-cloudagent-python#1959]
In aca-py 0.7.4, If agent disclose a multi-use invitation for all invitee, When the number of connections increases, the return records of Askar's SCAN_QUERY grow proportionally. As a result, In proportion, the total execution time of connection 1.0 process increases.

**Comment by swcurran** [comment]
@ianco and @andrewwhitehead -- could you please take a look at this.  Is there something we can do about this?

Thanks

**Comment by reflectivedevelopment** [comment]
See https://github.com/hyperledger/aries-cloudagent-python/pull/2116
