### ISSUE TITLE
Modify crypto envelope packing so header algorithm is accurate

### ISSUE THREAD

**Issue by Moopli** [hyperledger/aries-cloudagent-python#196]
The envelope header states it uses XChacha20 while the internals use Chacha20.

It's unclear which of these needs to change, but agreement is necessary so communication with other agents (using different implementations) will work.

**Comment by Moopli** [comment]
For context, I'm running into this issue while implementing a compatible pack/unpack in aries-framework-go.

**Comment by andrewwhitehead** [comment]
The crypto envelope format is currently consistent with indy-sdk. An updated envelope format is under development in the Aries community and we will sync up with that once it's finalized.

**Comment by andrewwhitehead** [comment]
Closed pending updated envelope format.
