### ISSUE TITLE
Is the "Alice Gets a Job" demo still working?

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#1987]
We've had a report ([here](https://github.com/cloudcompass/ToIPLabs/issues/95)) that the "Alice Gets A Job" demo may have an issue. From the report:

I have completed the steps in the [lab Alice get a job](https://github.com/cloudcompass/ToIPLabs/blob/main/docs/LFS173xV2/HelpAliceGetAJob.md), which in turn uses the [ACA-Py lab](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AcmeDemoWorkshop.md).

* Degree credential is issued from faber to alice
* Work credential can be issued from acme to alice
* Degree proof can be requested from acme to alice
* But in the third case, even I'm getting a Acme | Proof = True message, I also get an unhandled exception from the asyncio loop, as it is shown in the following image:

![image](https://user-images.githubusercontent.com/1018050/197880446-0852dfe6-7913-4bf2-9f14-ebeeb6ce2901.png)

Any clue? Is it something related to how the keys of attributes are being built in faber.py#225?

I have copied the snippets of code as is from the lab.

**Comment by swcurran** [comment]
@ianco -- can you please do an Acme run to see if it is still working?

**Comment by ianco** [comment]
I'll check.  I suspect there were changes to the demo that were never applied to the Acme instructions

**Comment by ianco** [comment]
Code was fixed
