### ISSUE TITLE
Update the RTD docs-from-code process to produce more useful information for developers

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#20]
We have functioning ReadTheDocs (RTD) from source code generating at https://aries-cloud-agent-python.readthedocs.io/en/latest/ (See the "Modules" link).  It's working (yay!) but the generated result is not useful. Everything appears to be in the "aries_cloudagent" module, so you can't traverse the modules.

The current method for generating is here: https://github.com/swcurran/aries-cloudagent-python/blob/master/docs/README.md. Specifically, from the docs dir, run this: `sphinx-apidoc -f -o  . ..`

The ideal would be that each folder below aries_cloudagent, and below aries_cloudagent/messages be a separate module that we could still auto-generate.

I'm not sure if the problem is that the items are not properly defined as "modules" in python (e.g. that it's a code problem) or if the script calling the generator needs to be setup to call each thing we want as module explcitly. And if the latter, how to we include the code files in the root folder (e.g. aries_cloudagent itself).  For bonus points, how to structure the RST so that we can have the messages code (which are the message family protocols that are optionally added to an instance of Aries Agent) called out separtely from the rest of the code.  I would think all but that bonus point should "just work", so I find the challenge quite weird.

von_anchor is an example of it working much better...https://von-anchor.readthedocs.io/en/latest/modules.html
generated from https://github.com/PSPC-SPAC-buyandsell/von_anchor/tree/master/docs/source

It may be that the rst files (e.g. https://github.com/PSPC-SPAC-buyandsell/von_anchor/blob/master/docs/source/von_anchor_utils.rst) are hand rolled, which is kind of OK - we'd have to figure out how to prevent people from adding new code and not docs.

Good luck - @WadeBarnes with help from myself and @nrempel 

Really good to have this working in time for the transfer.

**Comment by WadeBarnes** [comment]
Switched to using `sphinx_rtd_theme`:
`pip install -U sphinx-rtd-theme`
Update `./docs/conf.py`; `html_theme = 'alabaster'` => `html_theme = 'sphinx_rtd_theme'`
