### ISSUE TITLE
Holder ACA-Py unable to handle credential offer after connection switched to RESPONSE state

### ISSUE THREAD

**Issue by markuskreusch** [hyperledger/aries-cloudagent-python#2001]
**What we do**
We have connected two ACA-Py instances to [issue a credential](https://github.com/hyperledger/aries-rfcs/tree/main/features/0036-issue-credential). We have a controlling application that issues requests to both instances to create and transfer an invitation, establish the connection and perform the credential exchange. We start the issuance process as soon as the connection switches to RESPONSE status (webhook /connections).

**What we observe**
Around 70% of the issuances fail in a scenario with negligible network latency because everything happens on one machine. With network latency the error rate is considerably lower but not zero. The credential exchange does not proceed further. The error message we see in the holder ACA-Py is:
```
2022-11-02 17:06:35,041 aries_cloudagent.core.conductor ERROR Exception in message handler:
Traceback (most recent call last):
   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 180, in _step
     result = coro.send(None)
   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/dispatcher.py", line 209, in handle_message
    await handler(context, responder)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/issue_credential/v1_0/handlers/credential_offer_handler.py", line 53, in handle
    "No connection or associated connectionless exchange found for credential"
aries_cloudagent.messaging.base_handler.HandlerException: No connection or associated connectionless exchange found for credential offer
```

**What we expect**
The holder ACA-Py should know the connection because it already processed the invitation and sent a connection request to the issuer ACA-Py. The issuer already sent the connection response to the holder ACA-Py before sending the credential offer. The credential exchange should proceed normally.

**Workaround**
The problem is gone when we wait on the issuer ACA-Py till the connection switched to ACTIVE state.

**Why can't we just do that and why do we think it should work with RESPONSE as well?**
The [RFC](https://github.com/hyperledger/aries-rfcs/blob/main/features/0160-connection-protocol/README.md#3-connection-acknowledgement) states: "After the response is received, the connection is technically complete.". Thus from the viewpoint of the issuer the connection is technically complete after the response has been sent. As well it is stated that "The invitee SHOULD send a message to the inviter.". The invitee is thus not forced to send a message to the inviter. It just should do so but can as well not do it. A system must work even when the message is not sent. In practice several wallet implementations - like the lissi wallet for example - do not send such a message. Thus we believe reacting to the connection status RESPONSE should work as well.

**Comment by swcurran** [comment]
Connections protocol is deprecated because of issues like this. Closing this as implementations should move to DID Exchange.
