### ISSUE TITLE
Endorser: Invalid request JSON: protocolVersion not found

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#2007]
On `POST /transactions/{transaction_id}/endorse` for a NYM transaction from an author, we get a 400 error when using the `askar` wallet type:
```
400: Cannot endorse invalid request. Invalid request JSON: protocolVersion not found.
```
It would seem that the indy-sdk defaults to `protocolVersion` of `2` when absent but indy-vdr requires that it be explicitly set.

@ianco @swcurran

**Comment by dbluhm** [comment]
This was tested on ACA-Py 0.7.5

**Comment by dbluhm** [comment]
This seems to be related to these recently changed lines:

https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/ledger/routes.py#L305-L321

The transaction data passed to the endorser does not include the protocolVersion. It also does not include a reqId which caused additional failures, even after switching to the `indy` wallet:

```
400: Exception raised by ledger transaction: Error: Invalid structure. Caused by: Request is invalid json: Error("missing field `reqId`", line: 1, column: 244). CommonInvalidStructure.. Exception raised by ledger transaction: Error: Invalid structure. Caused by: Request is invalid json: Error("missing field `reqId`", line: 1, column: 244). CommonInvalidStructure.
```

**Comment by ianco** [comment]
@dbluhm  can you provide your full configuration?

I tested with the endorser service (https://github.com/hyperledger/aries-endorser-service) and it worked with both aca-py releases `07.5` and `1.0.0-rc1`

**Comment by hangindev** [comment]
I encountered the same error message when I tried to have an Author creates a DID and promote to public with the help with a Endorser.

I ran two agents using image "bcgovimages/aries-cloudagent:py36-1.16-1_0.7.5". Steps to reproduce:

0. Establish connection and set up endorser role/info
1. Author creates a local DID and `POST /ledger/register-nym`, specifying `conn_id` and `create_transaction_for_endorser`. 
2. Author `POST /transactions/create-request`. 
3. Endorser `POST /transactions/{tran_id}/endorse`
4. Got response "400: Cannot endorse invalid request. Invalid request JSON: protocolVersion not found."

Any pointers would be appreciate. Thank you!

The docker compose file I used to set up two agents:

```yaml
version: "3.9"
services:

  author:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.5
    ports:
      - "8020:8020"
      - "8021:8021"
    command: "start \
      --label my-aries-agent \
      --genesis-url http://172.17.0.1:9000/genesis \
      --endpoint http://172.17.0.1:8020 \
      --inbound-transport http 0.0.0.0 8020 \
      --outbound-transport http \
      --webhook-url http://172.17.0.1:8022/acapy-webhook \
      --admin 0.0.0.0 8021 \
      --admin-insecure-mode \
      --wallet-type askar \
      --wallet-name my-wallet \
      --wallet-key my-wallet-password \ 
      --auto-provision \
      --auto-ping-connection"

  endorser:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.5
    ports:
      - "8030:8030"
      - "8031:8031"
    command: "start \
      --label my-aries-agent \
      --genesis-url http://172.17.0.1:9000/genesis \
      --endpoint http://172.17.0.1:8030 \
      --inbound-transport http 0.0.0.0 8030 \
      --outbound-transport http \
      --webhook-url http://172.17.0.1:8022/acapy-webhook \
      --admin 0.0.0.0 8031 \
      --admin-insecure-mode \
      --wallet-type askar \
      --wallet-name my-wallet \
      --wallet-key my-wallet-password \
      --auto-provision \
      --auto-ping-connection"
```

**Comment by dbluhm** [comment]
I'm going to close this as stale. Endorser is being reworked for use with anoncreds-rs.
