### ISSUE TITLE
Code alerts from github

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#201]
github has an analysis tool for code and this project currently (as of opening this request) has 43 alerts.  Please review the alerts and clean them up as appropriate:

https://lgtm.com/projects/g/hyperledger/aries-cloudagent-python/?mode=list

Determine if the analysis is useful and what we should do with it from a CI pipeline perspective.  Do we want to post them badges in our readme?

Assigning to @nrempel, but not sure if it should go to you or other devs - reassign if appropriate.

**Comment by andrewwhitehead** [comment]
Many of these are fixed now and the rest are spurious errors.

**Comment by swcurran** [comment]
Thanks.
