### ISSUE TITLE
Tables and How to use wallet key and derivation method

### ISSUE THREAD

**Issue by abhimin** [hyperledger/aries-cloudagent-python#2016]
I'm able to integrate postgres and four tables are created I.e items,item_tags ,profiles, config.

I have few queries
1.are these only four tables used for wallet setup to store credentials, connections,secret keys and other information. 

2.how wallet key and derivation method configured. 

Please clarify above queries .

**Comment by abhimin** [comment]
@ianco can you help me for above queries

**Comment by ianco** [comment]
Hi @abhimin these are the 4 tables for an `indy` wallet (the structure is a bit different for `askar`)
I don't know the details about how all the underlying crypto and encryption work, I suggest asking in the #aries or #indy channel on discord

**Comment by swcurran** [comment]
Closing this as not part of ACA-Py.
