### ISSUE TITLE
Example code for /issue-credential-2.0/send-proposal endpoint

### ISSUE THREAD

**Issue by santidediego** [hyperledger/aries-cloudagent-python#2017]
Is there any example body that I can follow for _/issue-credential-2.0/send-proposal_? 

I ´ve followed the [OpenApiDemo](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AriesOpenAPIDemo.md) but I cannot find any example for this method.

**Comment by swcurran** [comment]
Closing as stale -- reopen if needed.  Sorry there was no response on this one.
