### ISSUE TITLE
Present Proof v2 + JSON-LD Creds: Internal error leaked to verifier through problem report

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#2020]
While tinkering with JSON-LD credential issuance and presentation, I found that if I had multiple credentials that could fulfill a presentation definition from a presentation request but I didn't provide enough information to the holder agent to know which one to use when creating a presentation, the following problem report is sent to the verifier:

```
{
  "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/notification/1.0/problem-report",
  "@id": "263e6806-9358-4a6a-a817-a0e042345848",
  "~thread": {
    "thid": "b03e564b-5db6-40d2-99fb-deb42f6cfae9"
  },
  "description": {
    "en": "Multiple credentials are applicable for presentation_definition 2d2781bc-6973-4b26-af35-00375d07ef10 and --auto-respond-presentation-request setting is not enabled. Please specify which credentials should be applied to which input_descriptors using record_ids filter.",
    "code": "abandoned"
  }
}
```

I think this is pretty clearly an internal error and not something that needs to be reported to the other party.

**Comment by swcurran** [comment]
Closing as stale -- reopen if needed.
