### ISSUE TITLE
A single presentation request for different credentials

### ISSUE THREAD

**Issue by guillesanz21** [hyperledger/aries-cloudagent-python#2021]
Version: 0.7.2
AIP: 1.0

I want to request a presentation of two attributes, one from an identity credential (id_number) an one from a COVID vaccination test credential (tg), all of that with a single request. I am using the endpoint `POST /present-proof/send-request` and sending the following body:

```
{
  "comment": "Identity and test proof presentations",
  "connection_id": "474fc553-3e45-47ff-a93f-e20e29b26779",
  "proof_request": {
    "name": "Proof request",
    "non_revoked": {
      "from": 1669052023,
      "to": 1669052100
    },
    "nonce": "1",
    "requested_attributes": {
      "0_id_number_uuid": {
        "names": ["id_number"],
        "non_revoked": {
          "from": 1669052023,
          "to": 1669052100
        },
        "restrictions": [
          {
            "cred_def_id": "8JudXt1xWHFE1xV4s2iUDb:3:CL:12:covID_MVP_Identity"
          }
        ]
      },
      "0_tg_uuid": {
        "name": "tg",
        "non_revoked": {
          "from": 1669052023,
          "to": 1669052100
        },
        "restrictions": [
          {
            "cred_def_id": "6iP8RfdJSmyihNYpryVya5:3:CL:16:covID_MVP_Test"
          }
        ]
      }
    },
    "requested_predicates": {},
    "version": "1.0"
  },
  "trace": true
}
```
When I try to send the presentation from the holder with the endpoint `POST /present-proof/records/{pres_ex_id}/send-presentation`, it returns the following error:
```
Error when constructing proof: Error: Invalid structure. Caused by: UrsaCryptoError: Credential doesn't contain requested attribute. CommonInvalidStructure.
```
Now I am not sure if I can request atributes from multiple credentials in a single request, but I understood that I could do so if I place the respective credential definition within the restrictions field of each requested attribute.

**Comment by swcurran** [comment]
You definitely should be able to do that.  I'm afraid I'm not up on how to turn on debugging to see where the problem might lie.  Have you compared your proof request to those in the Alice / Faber demo to see if there is some structural difference.

Some ideas to verify.  This type of thing has is done regularly, so it is very likely something specific to your setup.

Does your holder have the credentials in question in their secure storage?

Do the source credentials use revocation?  

I notice you have revocation at the top level (all credentials) and at the credential level. I'm not sure if that might be a problem, but perhaps removing it from one or the other might make a difference.

Sorry I can't help much more.

**Comment by guillesanz21** [comment]
I found the problem. 
I had a bug in my backend. I forgot to update the extraction of the names of the attributes from the request, before sending the presentation. It was still trying to get the names from the "name" key, instead of getting it from the "names" key. 
Thank you for your time!
