### ISSUE TITLE
Question: how do I implement a new credential format? 

### ISSUE THREAD

**Issue by arpentnoir** [hyperledger/aries-cloudagent-python#2023]
Posting as issue because discord link here https://www.hyperledger.org/use/aries not working... I'd be keen to join the discord channel too if it's still going? 

>By design Hyperledger Aries is credential format agnostic. This means you can use it for any credential format, as long as an RFC is defined for the specific credential format.

is someone able to point me to documentation / examples of approach to implementing a new credential format?

**Comment by swcurran** [comment]
What credential format are you interested in adding?

In general, the flow is this:

- In creating a new credential format, you will be using the [Issue Credential](https://github.com/hyperledger/aries-rfcs/tree/main/features/0453-issue-credential-v2) and [Present Proof](https://github.com/hyperledger/aries-rfcs/tree/main/features/0454-present-proof-v2) Aries Protocols, and adding a new type of attachment format that will be used for processing credentials of that type.
- Create an RFC that describes the attachments for processing the type of credential for each message in the Issue and Present protocols. Existing RFCs define the attachments for [AnonCreds](https://github.com/hyperledger/aries-rfcs/tree/main/features/0592-indy-attachments) (incorrectly called "Indy Credentials" in the RFC) and [W3C Verifiable Credentials Standard](https://github.com/hyperledger/aries-rfcs/tree/main/features/0593-json-ld-cred-attach).
- With some agreement/review in the community, you would implement the attachment handlers for the new credential type in the Frameworks of interest -- e.g. in ACA-Py in this repo.

The RFC specification process is needed to ensure that other frameworks implementing the handlers are interoperable, and they will help you in getting feedback from the community.

Hope that helps.
