### ISSUE TITLE
Using docker results in "/usr/bin/python3: No module named aries_cloudagent"

### ISSUE THREAD

**Issue by shearichard** [hyperledger/aries-cloudagent-python#2027]
Having read https://github.com/hyperledger/aries-cloudagent-python , I then read the instructions for running through Docker https://github.com/hyperledger/aries-cloudagent-python/blob/main/DevReadMe.md#docker .

The test actions shown here https://github.com/hyperledger/aries-cloudagent-python/blob/main/DevReadMe.md#docker all seemed to work.

I then made 'bin' the current directory and executed ...
```
aca-py start    --inbound-transport http 0.0.0.0 8000 \
                --inbound-transport ws 0.0.0.0 8001 \
                --outbound-transport ws \
                --outbound-transport http
```
... as per https://github.com/hyperledger/aries-cloudagent-python/blob/main/DevReadMe.md#about-aca-py-command-line-parameters .

In response I got
```
/usr/bin/python3: No module named aries_cloudagent
```
Which makes me think that the instructions at https://github.com/hyperledger/aries-cloudagent-python/blob/main/DevReadMe.md#about-aca-py-command-line-parameters are perhaps not applicable to running a-c-p in Docker ? Or have others succeeded ?

Would be interested in

**Comment by dbluhm** [comment]
When using docker, whether that's using the `run_docker` script or using a published image, the default entry point for the container will be `aca-py`. For example, to start an instance of ACA-Py using the `run_docker` script, you might run this command:

```
PORTS=“8080:8080 3000:3000” ./scripts/run_docker start -e “http://localhost:3000/” -it http 0.0.0.0 3000 -ot http --admin 0.0.0.0 8080 --admin-insecure-mode --no-ledger --wallet-type askar --wallet-name test --wallet-key test --jwt-secret random --multitenant-admin --auto-provision --log-level info
```

This will start an ACA-Py instance without an Indy Ledger using the askar wallet type and setting it up to be a multi-tenant ACA-Py instance.

If you have further questions, feel free to re-open this issue or ask on the Hyperledger Discord #aries-cloudagent channel :slightly_smiling_face:

https://discord.gg/hyperledger
