### ISSUE TITLE
JsonLd validation of nested Objects is not working correctly and it excludes the values from the signature

### ISSUE THREAD

**Issue by MajdT51** [hyperledger/aries-cloudagent-python#2028]
Hello, I think the json-ld validation is not working correctly for nested Objects.

Tested with bcgovimages/aries-cloudagent:py36-1.16-1_0.7.4 And bcgovimages/aries-cloudagent:py36-1.16-1_0.7.5

Steps to reproduce :

1. Start Acapy without AdminKey at port 11000
2. Create a DID of type SOV
3. Run the following curl command after replacing the `issuer` and `verkey`
NOTICE the nested object `vaccine` has an extra wrong property `**testMeWrong**`. This property is not part of the schema in  "https://w3id.org/vaccination/v1"

```bash
curl -X 'POST' \
  'http://localhost:11000/jsonld/sign' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "doc": {
    "credential": {
      "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/vaccination/v1"
      ],
      "type": [
        "VerifiableCredential",
        "VaccinationCertificate"
      ],
      "id": "urn:uvci:af5vshde843jf831j128fj",
      "name": "COVID-19 Vaccination Certificate",
      "description": "COVID-19 Vaccination Certificate",
      "issuanceDate": "2019-12-03T12:19:52Z",
      "expirationDate": "2029-12-03T12:19:52Z",
      "issuer": "<replace-issuer-sov-did>",
      "credentialSubject": {
        "type": "VaccinationEvent",
        "batchNumber": "1183738569",
        "administeringCentre": "MoH",
        "healthProfessional": "MoH",
        "countryOfVaccination": "NZ",
        "recipient": {
          "type": "VaccineRecipient",
          "givenName": "JOHN",
          "familyName": "SMITH",
          "gender": "Male",
          "birthDate": "1958-07-17"
        },
        "vaccine": {
          "type": "Vaccine",
          "testMeWrong": "WRONG",
          "disease": "COVID-19",
          "atcCode": "J07BX03",
          "medicinalProductName": "COVID-19 Vaccine Moderna",
          "marketingAuthorizationHolder": "Moderna Biotech"
        }
      }
    },
    "options": {
      "proofPurpose": "assertionMethod",
      "type": "Ed25519Signature2018",
      "verificationMethod": "did:sov:7rB93fLvW5kgujZ4E57ZxL#key-1"
    }
  },
  "verkey": "<replace-verkey>"
}'
```
**The expected result** is an Error

**The actual result** is a signed doc (I think it is also the case for issue json-ld credentials flows)

**Comment by MajdT51** [comment]
Update:

"testMeWrong": "WRONG" is included in the returned signed_doc from `/jsonld/sign` but I think it is not a part of the signature 😱 Because calling `/jsonld/verify` returns valid even if I change its value from "WRONG" to "WRONGXOX"

**Comment by TimoGlastra** [comment]
I think this is working correclty for using the JSON-LD exchange protocols, but not for the JSON-LD sign / verify endpoints. There is a `get_properties_without_context` in ACA-Py but it's not used for the jsonl-ld sign/verify endpoints. 

The best route would probably be to update the jsonld sing/verify to use the new jsonld signeatures support in ACa-Py, but this method could be quick fix

**Comment by MajdT51** [comment]
> I think this is working correclty for using the JSON-LD exchange protocols, but not for the JSON-LD sign / verify endpoints. There is a `get_properties_without_context` in ACA-Py but it's not used for the jsonl-ld sign/verify endpoints.
> 
> The best route would probably be to update the jsonld sing/verify to use the new jsonld signeatures support in ACa-Py, but this method could be quick fix

Thank you. Could you please add it to a todo list or at least add a warning until this is fixed :) I have been using this method for a while and probably others doing it too without knowing about this critical issue :)
