### ISSUE TITLE
"How to Issue JSON-LD Credentials using Aca-py" has invalid Admin API endpoint documentation

### ISSUE THREAD

**Issue by jfblier-amplitude** [hyperledger/aries-cloudagent-python#2041]
The documented endpoint `/request-presentation-2.0/request-proof` from `https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AliceWantsAJsonCredential.md#request-presentation-example` doesn't exists.

`/present-proof-2.0/send-request` should be used with the automated flow.

Also there's an other mention to `/request-presentation-2.0/{pres_ex_id}/send-presentation` that should be updated.

**Comment by swcurran** [comment]
Happy to get a PR :-). 

@ianco -- FYI.

**Comment by jfblier-amplitude** [comment]
Sure. Will work on it this weekend :-)

@swcurran , @ianco

**Comment by jfblier-amplitude** [comment]
@swcurran @ianco 
I submitted a PR `https://github.com/hyperledger/aries-cloudagent-python/pull/2045`
Thanks.
