### ISSUE TITLE
Does it required to store the issued credentials at holder end or issuer end

### ISSUE THREAD

**Issue by abhimin** [hyperledger/aries-cloudagent-python#2047]
Hi Team,
After issuing the credentials do we need to store the credentials explicitly using store api from acapy agent at holder end.

Please share some info on this.

**Comment by abhimin** [comment]
@adamsc64  Stephen can you share some info

**Comment by TimoGlastra** [comment]
Yes, you need to call store on the holder end

**Comment by abhimin** [comment]
@TimoGlastra I'm trying to store the credential with revocation support in holder wallet but getting tails file has doesn't match error at holder end.

Can you please share which configuration and steps  we need to use at holder end for storing credential with revocation

**Comment by ianco** [comment]
@abhimin you can check out the demo in the aca-py repo - https://github.com/hyperledger/aries-cloudagent-python/tree/main/demo#revocation

**Comment by swcurran** [comment]
The demo should provide the needed help. Closing this issue.
