### ISSUE TITLE
Help Wanted: Update CI/CD Pipeline to eliminate Circle/CI

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2048]
Circle/CI is becoming problematic and we need to move off of it for this repo and over to (I assume) a pure GHActions approach.

Looking for someone in the community that has some experience in this area to grab this issue.  Suggested approach:

- Offer to take this task
- Evaluate what is done with Circle/CI now and design a replacement
- Post an approach for a quick review from others that have expertise in this area
- Assuming a thumbs up -- move forward with the switch.

Thanks!

**Comment by dbluhm** [comment]
@swcurran #1888 The actions in this PR were intended to replace Circle CI

**Comment by WadeBarnes** [comment]
That being the case, I'll jump on the final review first thing in the morning tomorrow.

**Comment by swcurran** [comment]
AWESOME!  Is it ready to go?  Looks like it.  @WadeBarnes -- can you please do a (hopefully) final pass through the PR?

Thanks!

**Comment by WadeBarnes** [comment]
Related to CircleCI issues here; https://github.com/hyperledger/aries-cloudagent-python/pull/2024#issuecomment-1349054858
