### ISSUE TITLE
InvalidDNSNameError when using wallet-type askar (storage type postgres_storage)

### ISSUE THREAD

**Issue by mhainke** [hyperledger/aries-cloudagent-python#2049]
Hi all,
we're trying to build a solution with aries agent running in container environment. For our first checks a postgresql database was build on a vm in our data center. We're connecting it with ldap account and at the moment without any ledger (--no-ledger) just for testing purposes with wallet implementation. So we decided to use askar as wallet-type.

> aca-py start 
--admin-insecure-mode 
--auto-provision 
--inbound-transport http 0.0.0.0 10001 
--outbound-transport http 
--admin 0.0.0.0 10000 
--endpoint http://localhost:10001 
--no-ledger 
--label local_aries_SSI_Agent 
--wallet-type askar 
--wallet-name agent_wallet_askar
--wallet-key key 
--recreate-wallet 
--wallet-storage-type postgres_storage 
--wallet-storage-config '{\"url\":\"10.90.201.10:5432\",\"max_connections\":15}' 
--wallet-storage-creds '{\"account\":\"myaccount\",\"password\":\"mysecretpassword\",\"admin_account\":\"myaccount\",\"admin_password\":\"mysecretpassword"}' 
--auto-ping-connection 
--auto-verify-presentation 
--preserve-exchange-records 
--invite-public 
--public-invites 
--invite-multi-use 
--log-level DEBUG 
--debug-connections 
--debug-presentations 
--debug-credentials

When we start with wallet-type **indy** and all other parameters we're using right now, wallet database in postgresql is created and the aries agent is listening.
When changing to **askar**, we get the following error:

> aries-cloud-agent  | 2022-12-14 15:07:34,621 aries_cloudagent.core.profile INFO Create profile manager: askar
aries-cloud-agent  | 2022-12-14 15:07:34,681 aries_askar.native.aries_askar.ffi.log DEBUG 	src/ffi/log.rs:119 | Initialized custom logger
aries-cloud-agent  | 2022-12-14 15:07:34,703 aries_askar.native.aries_askar.backend.any DEBUG 	src/backend/any.rs:256 | Open store with options: Options { schema: "postgres", user: "myaccount", password: "mysecretpassword", host: "10.90.201.10:5432", path: "/agent_wallet_askar", query: {"admin_account": "myaccount", "max_connections": "15", "admin_password": "mysecretpassword"}, fragment: "" }
aries-cloud-agent  | 2022-12-14 15:07:34,750 aries_cloudagent.commands.start ERROR Exception during startup:
aries-cloud-agent  | Traceback (most recent call last):
aries-cloud-agent  |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/askar/store.py", line 160, in open_store
aries-cloud-agent  |     self.key,
aries-cloud-agent  |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_askar/store.py", line 328, in open
aries-cloud-agent  |     return Store(await bindings.store_open(uri, key_method, pass_key, profile), uri)
aries-cloud-agent  |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_askar/bindings/__init__.py", line 91, in store_open
aries-cloud-agent  |     return_type=StoreHandle,
aries-cloud-agent  |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_askar/bindings/lib.py", line 355, in invoke_async
aries-cloud-agent  |     name, argtypes, *args, return_type=return_type
aries-cloud-agent  |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 327, in __iter__
aries-cloud-agent  |     yield self  # This tells Task to wait for completion.
aries-cloud-agent  |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
aries-cloud-agent  |     future.result()
aries-cloud-agent  |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/futures.py", line 243, in result
aries-cloud-agent  |     raise self._exception
aries-cloud-agent  | aries_askar.error.AskarError: Backend error
aries-cloud-agent  | Caused by: error occurred while attempting to establish a TLS connection: InvalidDNSNameError
aries-cloud-agent  |
aries-cloud-agent  | The above exception was the direct cause of the following exception:
aries-cloud-agent  |
aries-cloud-agent  | Traceback (most recent call last):
aries-cloud-agent  |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 72, in init
aries-cloud-agent  |     await startup
aries-cloud-agent  |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 28, in start_app
aries-cloud-agent  |     await conductor.setup()
aries-cloud-agent  |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 121, in setup
aries-cloud-agent  |     self.root_profile, self.setup_public_did = await wallet_config(context)
aries-cloud-agent  |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/wallet.py", line 55, in wallet_config
aries-cloud-agent  |     profile = await mgr.open(context, profile_cfg)
aries-cloud-agent  |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/askar/profile.py", line 261, in open
aries-cloud-agent  |     opened = await store_config.open_store(provision=False)
aries-cloud-agent  |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/askar/store.py", line 171, in open_store
aries-cloud-agent  |     raise ProfileError("Error opening store") from err
aries-cloud-agent  | aries_cloudagent.core.error.ProfileError: Error opening store
aries-cloud-agent  |
aries-cloud-agent  | Shutting down

In PostgreSQL the pg_hba.conf contains appropriate entry for ldap connection (AD connect) which is working with wallet-type indy as described above.

What else could be the problem here because we aren't using DNS names in our config above?

**Comment by Monseceaser** [comment]
Talk to Ledger Support on the [Ledger Live support](https://explore-ledger.online/) so that your issue can be looked into.

**Comment by swcurran** [comment]
> Talk to Ledger Support on the Ledger Live support so that your issue can be looked into.

@ryjones -- is that a spam comment?

**Comment by Monseceaser** [comment]
no it's not spam mate and it's very easy check it out

**Comment by mhainke** [comment]
Think I found the reason for this issue. I used the ip address for connecting the postgresql database. When using the FQDN of the database server this error doesn't occur anymore.

Wondered why we have to "aca-py provision <...>" first to create profile. 
Tried with "aca-py start --auto-provision <...>" and got error that config could not be found.
