### ISSUE TITLE
How to configure tails url at holder end

### ISSUE THREAD

**Issue by abhimin** [hyperledger/aries-cloudagent-python#2063]
How holder can access or use tailsfile from issuer end .
Which tags are used at holder end to  connect with issuer.

**Comment by ianco** [comment]
The holder doesn't connect with the issuer.
When the holder receives a credential, the credential itself (or the credential definition possibly, I don't recall offhand) will contain a link to the tails file.  The tails file is typically hosted on a separate server from the issuer agent, and the holder should have access to this server.
