### ISSUE TITLE
Investigate errors in daily Python 3.7 and Python 3.10 errors

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2072]
We are running the integration tests for Python 3.6 - 3.10 and currently we are getting errors for Python 3.7 and Python 3.10.

Investigate the errors and solve at least the 3.10 issue, and ideally both.

Example error run [here](https://github.com/hyperledger/aries-cloudagent-python/actions/runs/3878901102)

**Comment by swcurran** [comment]
@Jsyro — here is the task for you to look at.  I’ll see if I can make you an assignee, and will be adding you to the Hyperledger organization so that for sure you can be added to future tickets.

**Comment by Jsyro** [comment]
Inital investigation: 

3.10 (INDY), `assertion` library `TypeError: required field "lineno" missing from alias`. possible breaking change or library dependency issue. 

3.7 (INDY), Flake 8 is checking and thinks it's finding attribute errors, maybe it's legit, but probably there is a type checking issue with this error.

**Comment by Jsyro** [comment]
`TypeError: required field "lineno" missing from alias` was fixed with an update to the pytest library. 

https://github.com/pytest-dev/pytest/discussions/9195.

**Comment by Jsyro** [comment]
Tests rely on this library, https://github.com/nvllsvm/async_case.... which is incompatible with newer versions of asyncio that do not accept the `loop` parameter in the `gather()` method. 

https://docs.python.org/3.10/whatsnew/3.10.html#changes-in-the-python-api

Unsure how to proceed, could update the lib, but unclear if that would break older versions, could refactor and remove dependency on the library, but the related tests are quite dense. 

https://github.com/hyperledger/aries-cloudagent-python/blob/67da623e65587929fbbba04ed052864dbf8c7c32/aries_cloudagent/admin/tests/test_admin_server.py
