### ISSUE TITLE
RFC-0019 Encryption Envelope - unpack fails without further error details

### ISSUE THREAD

**Issue by tdiesler** [hyperledger/aries-cloudagent-python#2083]
AcaPy is having trouble unpacking a jwe envelope without giving details on what did go wrong

```
acapy01  | 2023-01-19 13:43:52,162 indy.libindy DEBUG do_call: >>> name: indy_unpack_message, args: (c_int(13), '{"protected":"eyJlbmMiOi...9fV19","iv":"xUuD-HaC2Og6qqNS","ciphertext":"V8KpaLS...53B1Mkh","tag":"shZzB5tOhdZTfbL7esLvpA\\u003d\\u003d"}', c_uint(2843), <CFunctionType object at 0x40194c31d8>)
acapy01  | 2023-01-19 13:43:52,163 indy.libindy DEBUG do_call: Function indy_unpack_message returned err: 102
acapy01  | 2023-01-19 13:43:52,164 indy.libindy WARNING _do_call: Function indy_unpack_message returned error 102
acapy01  | 2023-01-19 13:43:52,164 indy.libindy DEBUG _get_error_details: >>>
acapy01  | 2023-01-19 13:43:52,164 indy.libindy DEBUG _get_error_details: <<< error_details: None
acapy01  | 2023-01-19 13:43:52,165 indy.libindy DEBUG do_call: <<< <Future finished exception=CommonInvalidParam3()>
acapy01  | 2023-01-19 13:43:52,165 aries_cloudagent.core.dispatcher ERROR Handler error: PackWireFormat.unpack
acapy01  | Traceback (most recent call last):
acapy01  |   File "/home/indy/aries_cloudagent/wallet/indy.py", line 911, in unpack_message
acapy01  |     self.opened.handle, enc_message
acapy01  |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/crypto.py", line 498, in unpack_message
acapy01  |     unpack_message.cb)
```

I can successfully unpack such messages sent from AcaPy and do the round trip on my end. The above is a DidExchange Response message - so no connection just yet. The packed didex response uses Alice's did:sov, which isn't known to AcaPy nor the Ledger. Would that be a problem?

More context ...

- Faber has a public DID on AcaPy
- Alice has no public DID and no AcaPy wallet
- Inviter (Alice) creates an Out-of-Band Invitation
- Invitee (Faber) receives the Invitation
- Inviter (Alice) receives an encrypted DidEx Request and extracts Fabers's DID Document
- so far so good
- Inviter (Alice) sends an encrypted DidEx Response (fails with the above)

How could I try to debug this?
Is there perhaps some (online) tool that can verify `didcomm-envelope-enc` message format/integrity?

**Comment by andrewwhitehead** [comment]
Are you able to test with `--wallet-type askar`? Unfortunately indy-sdk isn't reporting any details, except that it doesn't think the envelope format is valid.

**Comment by andrewwhitehead** [comment]
Also you might try stripping the padding (trailing '='s) off of base64-URL-encoded values.

**Comment by tdiesler** [comment]
I verified that the [Kotlin pack algorithm is ok](https://github.com/tdiesler/nessus-didcomm/blob/main/agent/src/test/kotlin/org/nessus/didcomm/test/crypto/LibIndyTest.kt#L149). I also double checked, by using libindy pack for the didex request - I get the same error in AcaPy.

The error seems to be [coming from here](https://github.com/hyperledger/indy-sdk/blob/main/libindy/src/api/crypto.rs#L731)

```
    check_useful_c_byte_array!(jwe_data, jwe_len, ErrorCode::CommonInvalidParam2, ErrorCode::CommonInvalidParam3);
```

**Comment by tdiesler** [comment]
OMG, it had to do with the Http `Content-Type`

Ok with: `application/didcomm-envelope-enc; charset=utf-8`
Bad with: `application/json; charset=utf-8`

I leave this open for others to decide whether this is intended behaviour. Perhaps a warning would be good when a (json) payload looks like an encrypted envelope, but the Content-Type indicates otherwise
