### ISSUE TITLE
How to perform aca-py issuer and holder agents in a different networks?

### ISSUE THREAD

**Issue by elazzarin** [hyperledger/aries-cloudagent-python#2084]
Hi,
How to run the demo below on different networks and/or computers?

[the-alicefaber-python-demo](https://github.com/hyperledger/aries-cloudagent-python/tree/main/demo#the-alicefaber-python-demo)

I would like to run the agent Faber and Alice on different networks according to the steps of the demo above (correctly accept the invitation, create an Issue Credential, Send Proof Request and Send Message).

Thank you

**Comment by ianco** [comment]
Hi @elazzarin 

The demo should work if you are running the alice and faber agents on different computers, you just need to make sure that (a) both agents are configured to use the same Indy ledger, and (b) the agents are exposing public endpoints (so the agents can connect to each other)

(a) you can start each agent using the `LEDGER_URL` parameter to connect to the same (external) ledger, for example `LEDGER_URL=http://test.bcovrin.vonx.io/ ./run_demo faber` (same with alice on the other computer)

(b) the `run_demo` script will automatically detect if ngrok is running, and will then use the ngrok endpoint as the agent's endpoint.  This is described here (but should work for both the alice and faber agents):  https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AliceGetsAPhone.md#expose-services-publicly-using-ngrok

(note that with alice you run ngrok as `ngrok http 8030`)

 This "should work" but hasn't been rigorously tested.  Let me know how it goes!

**Comment by elazzarin** [comment]
Hi @ianco 

Followed your instructions and everything went well.

Thanks
