### ISSUE TITLE
Add container vulnerability scanning for the built/published ACA-Py images.

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/aries-cloudagent-python#2087]
PR https://github.com/hyperledger/aries-cloudagent-python/pull/2076 added support for building and publishing ACA-Py images.  The initial implementation just builds and publishes the images.

It would be a great enhancement to have these containers scanned on a regular basis (and possible during the builds) for vulnerabilities.

**Comment by WadeBarnes** [comment]
@ryjones, Does Hyperledger have any existing tools and processes for this?

**Comment by ryjones** [comment]
@WadeBarnes [I think you can choose from a lot of free ones](https://github.com/hyperledger/aries-cloudagent-python/actions/new?category=security&query=), we don't have a policy

**Comment by swcurran** [comment]
Narrowing to container images seems to give [this list](https://github.com/hyperledger/aries-cloudagent-python/actions/new?category=security&query=Container). Sysdig and Snyk are the names I recognize, but not sure about which to use.  Opinions?

Need to verify their use/pricing for open source projects.

**Comment by pradeepp88** [comment]
I created an acapy image with the new Dockerfile from the docker folder, uploaded it to Dockerhub and scanned it with Snyk tool. It was showing to have lot of vulnerabilities arising from Debian-buster base image. The number of vulnerabilities went down drastically, when changing the base image from `python:{python_version}-slim-buster` to `python:{python_version}-slim`. Used Python version 3.8. The same is the case for all the slim-buster images.

**Comment by WadeBarnes** [comment]
@pradeepp88, it would also be interesting to compare the results when using `3.9-slim-bullseye`.  Thanks for trying this out.

**Comment by pradeepp88** [comment]
@WadeBarnes I have tested the images with `python:3.9-slim-bullseye` and found 0 critical vulnerabilities. I tested in both Qualys and Synk and got the same results. So created a PR #2105 to update the base images from slim-buster to slim-bullseye version. Please review.
Looking for feedback from the community on the vulnerability scanning tool to be used. I checked Snyk, it is good and matches the report generated by enterprise scanning tools. Thanks.

**Comment by swcurran** [comment]
Thanks @pradeepp88 — great stuff.  Much appreciation for the work and conclusions.

**Comment by WadeBarnes** [comment]
thanks @pradeepp88, the related PR updating the base images has been merged.

**Comment by WadeBarnes** [comment]
Addressed with https://github.com/hyperledger/aries-cloudagent-python/pull/2418
