### ISSUE TITLE
Export Wallet from ACA-Py Agent

### ISSUE THREAD

**Issue by darapich92** [hyperledger/aries-cloudagent-python#2096]
Hello everyone, I want to export the wallet of user so that he can use it for accessing again to the aca-py agent. Currently, I am running ACA-Py agent using docker. I want to mount the volume of the wallet in the Docker Container but I do not know the wallet directory in the Docker Container. Could you let me know the directory of Wallet in the Docker Container? or you have any solutions to export the wallet from ACA-Py agent without mounting the Volume, I would also prefer it. Thank you very much!

**Comment by kukgini** [comment]
normally it would be in `/home/indy/.indy_client/wallet` directory.

**Comment by darapich92** [comment]
@kukgini thank you very much. I think that directory is correct.
