### ISSUE TITLE
How to view Binary Data in the wallet database storage of agent?

### ISSUE THREAD

**Issue by darapich92** [hyperledger/aries-cloudagent-python#2100]
Hello everyone, i run the postgresql as the wallet storage of the agent. But when I query it in the database, i saw that all data are `[binary data]`. Do you know how to view it via database admin browser (currently, I use pgadmin4 to view postgres database).

![image](https://user-images.githubusercontent.com/5119512/215589424-07280d2b-0b4e-49ca-8e19-a4c09218147b.png)

Thank you very much!

**Comment by ianco** [comment]
With an "indy" wallet there's no way to inspect the database contents, they are encrypted.

With an "askar" wallet I'm not sure if there's a setting to run in "unencrypted mode", @andrewwhitehead ?

**Comment by ianco** [comment]
> I think it makes sense to encrypt the data. But in some case, we want to query it.

I agree, I think it's an oversight that there is no option in an indy wallet to query the data.

However I thought we had an option with "askar" but I'm not sure offhand.

**Comment by swcurran** [comment]
There are two ways to search, AFAIK.  First, if you are doing an exact match, you can search for the encyrpted value in the tags. That is how, for example, the credential searching is done for credentials with given claim names, or for given claim name/value pairs.  In Indy-SDK at least, there is a way to create unecrypted tags, so you can search with expressions.  Not sure if that is available for Aries Askar — it’s a pretty tricky feature to use in a general purpose tool.

**Comment by darapich92** [comment]
@swcurran thank you very much for the information. So, I should dive to query for data by using provided code from Indy-SDK.

**Comment by ianco** [comment]
I forgot about the unencrypted tags feature.  If you start acapy with `--exch-use-unencrypted-tags` then aca-py will use unencrypted tags for more (but not all) records

**Comment by darapich92** [comment]
@ianco ahh!! thank you for the information.
