### ISSUE TITLE
Multitenancy wallet creation 

### ISSUE THREAD

**Issue by sheraliinamdar** [hyperledger/aries-cloudagent-python#2102]
I have created one multitenancy environment and by default it created the database by name "wallets" in aws RDS  and Wallet Scheme is set to "MultiWalletSingleTableSharedPool" and it is working as expected.

Now i am creating another multitenancy environment by using same aws RDS with same wallet scheme, as database "wallets" already created from previous environment. Now aries is throwing exception saying wallet name already exist. 

is there any way to configure db name "wallets" to something else by using any config variable ? and 
can two different aries instances point to same db "wallets" ?

**Comment by ianco** [comment]
For an "indy" wallet the database name is hardcoded unfortunately, you will need to use 2 separate postgres instances.

For an "askar" wallet I'm not sure if the database name is configurable, @andrewwhitehead ?

**Comment by swcurran** [comment]
Closing as stale -- reopen if needed.
