### ISSUE TITLE
Multitenancy: use a different db (connection) per tenant

### ISSUE THREAD

**Issue by esune** [hyperledger/aries-cloudagent-python#2104]
When running an agency, there may be a need to run physically separate database instances for all/some of the tenants. Currently it is possible to target separate schemas in the same RDBMS, but not using different connections altogether.

Thoughts on feasibility/usefulness of this feature?

It may relate to #1349 and #2102.

**Comment by swcurran** [comment]
Closing as stale -- reopen if needed.
