### ISSUE TITLE
How to set criteria to revoke a credentials .also what are the from and to values in proof presentation

### ISSUE THREAD

**Issue by abhimin** [hyperledger/aries-cloudagent-python#2106]
How issuer set criteria to revoke in acapy api and how holder know what values in from and to can be shared to verifier.
Can you please specify what are the apis flow from issuer to holder and verifier for the revocation of credentials.

**Comment by abhimin** [comment]
@swcurran please help in revocation criteria  or condition  to a credentials

**Comment by abhimin** [comment]
@ianco @andrewwhitehead  please share some insights.

**Comment by ianco** [comment]
Hi @abhimin 
To start, take a look at the docs in https://github.com/hyperledger/aries-cloudagent-python/tree/main/docs/GettingStartedAriesDev, there is a document covering revocation.
When you issue a credential (with revocation enabled) you get a revocation id and index, and you then use these values to revoke the credential.  If you have revocation notification enabled, the holder will get a notification when their credential is revoked (with the same id's).
There are also some demo's here - https://github.com/hyperledger/aries-cloudagent-python/tree/main/demo.  If you run faber with revocation enabled (for example `./run_demo faber --revocation --events` will also show the detailed message flow) you can see the full flow.

**Comment by abhimin** [comment]
@ianco  can I give from and to values in present proof request as per ledger transaction time in seconds  or 
Can I give current time in seconds when sending proof.

**Comment by ianco** [comment]
You use the current time in seconds, I believe

https://github.com/hyperledger/aries-cloudagent-python/blob/main/docs/GettingStartedAriesDev/CredentialRevocation.md

**Comment by swcurran** [comment]
Also documented in the [AnonCreds specification](https://hyperledger.github.io/anoncreds-spec/#request-non-revocation-proofs).

Closing this issue.
