### ISSUE TITLE
Issuer updates tailsfile after revoke credentials

### ISSUE THREAD

**Issue by abhimin** [hyperledger/aries-cloudagent-python#2119]
Currently I have created credential definition with support revocation true and I can see tails file created.
Then issued credential but I don't see any log in tailsserver. 
Also I don't see any log or any request transaction to tailsserver after revoke.

Can I get few details when and what values of tails files would update either from issuer or holder after tailsfile created.

**Comment by swcurran** [comment]
The tails file is static — it doesn’t change after creation. The only operation is the holder retrieving it for the creation of a presentation.

The best overview of the revocation process is here:

https://github.com/hyperledger/indy-hipe/blob/main/text/0011-cred-revocation/README.md
