### ISSUE TITLE
Add an "auto delete" capability for presentation exchange records

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#2126]
Presentation exchange records don't automatically get deleted.

There is currently a `--preserve-exchange-records` parameter but that seems to apply only to credential exchange records.

Add the ability to "auto-delete" presentation exchange records, either through a startup param (like the cred exch flag), or through an extra param on the "verify" function (e.g. auto-delete after verify).

**Comment by swcurran** [comment]
@usingtechnology — assigning this one to you.  Not sure of exactly the state of this, but this same feature that applies to `issue-credential` protocol state objects should apply to `present-proof`.

Suggested approach is to do a small waterfall project — plan what you are going to do, with a HackMD.io or equivalent document to review with a maintainer, and then make the changes.

**Comment by usingtechnology** [comment]
Added a [hackmd](https://hackmd.io/u8s3eGsLQFGY164iKLbhag?view) proposing a game plan.

**Comment by ianco** [comment]
Added comments to the hackmd, only consideration is adding "auto delete" capability on both the verifier and holder sides of the pres exch protocol.

**Comment by usingtechnology** [comment]
Thanks @ianco . Update the hack md to break up the configuration into verifier/holder specific settings. Allowing the holder to preserve records independently of the verifier configuration. Proposing we add similar functionality for credential exchange.

Not sure if this would be the PR to support tenant-level overrides too? At least start sketching in a framework that would support it.

**Comment by ianco** [comment]
> Not sure if this would be the PR to support tenant-level overrides too?

I'd do this in a separate PR ...
