### ISSUE TITLE
How does Acapy handle TLS and Certificate for postgres database transactions

### ISSUE THREAD

**Issue by MonolithicMonk** [hyperledger/aries-cloudagent-python#2131]
Environment:
Acapy: 
- Helm chart kubernetes deployment borrowed from bpa chart
- Ubuntu 20.04 host
- Version 0.74
- Askar wallet

Database:
- Yugabyte distributed postgres db deployed using yugabyte helm chart
- Ubuntu 20.04

Other info:
- DB is secured with password authentication, TLS end to end encryption, and server-client certificates

QUESTION:
Given an acapy client that wants to conduct a secure relationship with a database,
And the database requires a valid certificate for communication encryption,
How does one configure acapy to use a certificate to communicate with the database?

In [this link](https://cs.github.com/hyperledger/aries-cloudagent-python/blob/a033cd0442cca1b04edc2c943175a3f060e97345/demo/runners/support/agent.py#L1127)  to an agent demo I can see that the postgres configuration has a ```tls: false``` configuration option.  However I don't see this option anywhere in the aca-py provision / start command.

This is the error that is returned by acapy due to no certificate configued:
```
Client auth requested but no cert selected
2023-02-17 13:28:49,103 aries_askar.native.rustls.client.tls13 DEBUG     /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/rustls-0.19.1/src/client/tls13.rs:869 | Skipping certverify message (no client scheme/key)
```

Can anyone with insight into this please assist.  I included yugabyte for accuracy however my concern is applicable to any postgres db.

**Comment by swcurran** [comment]
Closing as stale -- reopen if needed.
