### ISSUE TITLE
Plugin Repository

### ISSUE THREAD

**Issue by usingtechnology** [hyperledger/aries-cloudagent-python#2132]
I believe there is a need for a Hyperledger Aca-Py Plugins master repository.

Currently, there is no real documentation about how to (I believe work in this area is underway): 

- create a plugin
- best practices for loading/using a plugin
- build out a custom image with a set of plugins
- how to distribute your plugin

BC Gov is working on a series of plugins for multi-tenant enhancements [traction](https://github.com/bcgov/traction) and need to make those more accessible for public use.

Ontario Gov is working on a webhook security enhancement and they are restricted from creating an open source repository for their plugin, but can contribute to existing open source projects/repos.

We (BC Gov) created a list of [plugins](https://hackmd.io/m2AZebwJRkm6sWgO64-5xQ) we could find as we were investigating how to make plugins and what we could do the architecture. It is unknown what is active, what is working (if it ever did).

Having a hyper ledger repository should make it easier for the community to find and leverage plugins and would be a good place for how-to and other guides for leveraging the plugin architecture.

**Comment by dbluhm** [comment]
@swcurran I think having a central repo for the documentation @usingtechnology described and at least links to plugin repository makes sense. I would not recommend moving the entirety of the plugin to such a repo, though. We should have consistency as much as possible across the plugins but I don't think it would be beneficial to change the processes and workflows already established on the toolbox plugin.

Perhaps it would make sense to have a "centralized" repo that pulled in common groupings of plugins via submodule and built images from them. This could be a good way to get the benefits of having the plugin "in-repo" without moving it.

**Comment by ianco** [comment]
I think a centralized list of plug-ins is a good idea (could just be maintained in a doc in the aca-py repo) but I don't think we should have a centralized repo for the plug-ins themselves.

**Comment by usingtechnology** [comment]
See https://github.com/hyperledger/aries-acapy-plugins

**Comment by usingtechnology** [comment]
Repository is created... [aries-acapy-plugins](https://github.com/hyperledger/aries-acapy-plugins)
