### ISSUE TITLE
Design new aca-py plug-in model

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#2141]
See discussion and linked docs from aca-pug:  https://wiki.hyperledger.org/display/ARIES/2023-02-21+Aries+Cloud+Agent+-+Python+Users+Group+Community+Meeting

**Comment by ianco** [comment]
From discord:

Here are my thoughts from my recent experience working on a plugin.

1. There is no documentation on how a plugin should behave, each plugin developer has their own approach with some commonality.  A set of rules, calls, and reference examples that we could agree on would be helpful.
2. We wanted to override the existing behaviour of a class.  In our case, it was to add a header variable in web_hook calls.  We ran into two major setbacks.
   a. While Python lets you override a class and replace a function, not all functions are suitable.  For example in send_webhook the function is fully contained.  It builds the call and sends it to the queue.  There is no way to intercept before the call is made.  A good way I have seen this addressed is by having Hooks.  For example in WordPress, plugins register hooks that are called at various critical points in a function.  This allows you to change behaviour without having to copy the function to a new class and hope that no one changes the base class function in the future.
   b. The dependency manager with the code injection allows for overriding classes, by allowing you to bind a new class to the class name.  However, not all classes are accessed using the injection method.  For example, in our case we needed to override behaviour in the AdminServer.  No where in the code base is the AdminServer or BaseAdminServer retrieved using the dependency manager.   This meant that even if we wanted to override the function, then it would never get used.  Our only option at this point is to put the code into the main body of code and not in a plugin.

A lot of what I am talking about here involves major rewriting of the code base that only provides architectural improvements and not new features.  Do you feel that changes like this to move to a friendlier environment for plugins will pay off in the long term?

**Comment by swcurran** [comment]
Covered in new aries-acapy-plugins repo.
