### ISSUE TITLE
Nightly tests on main fork only?

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#2152]
The nightly test github actions we recently merged run on every fork of ACA-Py (unless the owner disables actions on their fork, I suppose). Perhaps it's a good idea to have a check that has them run only if on the main hyperledger fork of ACA-Py (or if some config value is set in the environment on the repo? Opting in to have them run on your fork seems valuable, even if only for testing the action).

cc @WadeBarnes @swcurran

**Comment by WadeBarnes** [comment]
@dbluhm, 100% agree.

**Comment by swcurran** [comment]
Definitely!

**Comment by dbluhm** [comment]
@anwalker293 will take a stab at this :slightly_smiling_face:
