### ISSUE TITLE
API demo accept connection invitation using the URL

### ISSUE THREAD

**Issue by alberttrigo** [hyperledger/aries-cloudagent-python#2153]
I was wondering to be able to accept the invitation generated by Faber on Alice Swagger using its API (running docker) not using the invitation struct, just using the URL that contains the invitation encoded. 

Is it possible?

**Comment by swcurran** [comment]
This is done in the Alice/Faber demo controller code, but I don’t think it is supported in ACA-Py. E.g. the controller accepts the URL, extracts the invitation, and then passes it to ACA-Py. ACA-Py can’t (and probably shouldn’t?) process the URL itself.  On the other hand, that would definitely lock in the format of the URL.
