### ISSUE TITLE
Hyperledger AnonCreds implementation in ACA-Py: design document

### ISSUE THREAD

**Issue by cjhowland** [hyperledger/aries-cloudagent-python#2158]
@swcurran 

Here is the design document for the BCGov Code with Us opportunity to update ACA-Py to use the new anoncreds-rs implementation: https://hackmd.io/WKld-wswSemi_dZzvCbYvw?view

Let us know what comments, suggestions, or feedback you have.  Thanks!

cc @dbluhm @burdettadam

**Comment by swcurran** [comment]
Awesome — we’ll review.  @andrewwhitehead @ianco @shaangill025 — FYI.

**Comment by ianco** [comment]
Overall looks good to me

**Comment by andrewwhitehead** [comment]
I think I would separate the `AnonCredsRegistry` interface into readable (resolver) and writable (publisher) variants, as certain methods might only support reading depending on the configuration. These changes would likely also impact the `BaseLedger` interface, which has always been mis-named, it's actually more of an `IndyLedger` (or maybe specifically `did:sov`).

**Comment by swcurran** [comment]
Closing as used.
