### ISSUE TITLE
ACA-Py 0.7.4: Multitenancy wallet error ProfileSessionInactiveError

### ISSUE THREAD

**Issue by abramis** [hyperledger/aries-cloudagent-python#2159]
Hello, im not having a problem when creating an indy wallet on postgresql via ACA-Py (part of the flow on signup process on my controller). Problem starts when test it 100 times parallel to run. Aca-py service that run is POST multitenancy/wallet and request body:
`{"key_management_mode":"managed","wallet_dispatch_type":"default","wallet_key":"MySecretKey123","wallet_name":"jwbnqaicun3y","wallet_type":"indy","wallet_webhook_urls":["http://myIP:3005/webhookStu"]}' }`
Response:
```
status: 400, 
statusText: 'ProfileSessionInactiveError.'
```
Aca-py cant handle so many parallel requests? Is there a solution to my problem? Cause my controller cant pass stress tests with this kind of errors. Do you know if other aca-py services have this problem? Thank you

**Comment by AishwaryaJain68102** [comment]
@abramis I also encountered the same error, did you fix it ?

**Comment by abramis** [comment]
> 

No i didn't. I tried with GET ACA-Py request for credentials, and 100 times parallel test ran successfully. The problem is on POST requests. Maybe askar wallet has better results? Because on another 100 times test, i tried to delete wallets from postgres, and failed, cause said "too many transactions" something like that. Maybe indy postgresql based wallets are too slow to handle this kind of "traffic"?

**Comment by swcurran** [comment]
Can you share any details of the tests you are running?  Do you have a controller that triggers the error?

I would definitely recommend trying to run it with Askar, as it is much faster, and provides stable performance. But I would still be interested in seeing if we can find the source of this error.

**Comment by abramis** [comment]
For 1st test run 100 times parallel a http request (that said above) with Apache JMeter and bzm Parallel Controller. Not all requests failed. 70% returned status 200. Controller based on Node.JS. 
Error as axios catch it for initial post: 
`{ Error: Request failed with status code 400
    at createError (/home/avraam/blockademic/backend/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/avraam/blockademic/backend/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/avraam/blockademic/backend/node_modules/axios/lib/adapters/http.js:312:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  config:
   { transitional:
      { silentJSONParsing: true,
        forcedJSONParsing: true,
        clarifyTimeoutError: false },
     adapter: [Function: httpAdapter],
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     maxBodyLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json',
        'Content-Type': 'application/json',
        'X-API-Key': 'nFg33#rtUIkf3',
        'User-Agent': 'axios/0.25.0',
        'Content-Length': 212 },
     method: 'post',
     url: 'http://localhost:5050/multitenancy/wallet',
     data:
      '{"key_management_mode":"managed","wallet_dispatch_type":"default","wallet_key":"MySecretKey123","wallet_name":"zzzhtlczauniex2","wallet_type":"indy","wallet_webhook_urls":["http://MY_IP:3005/webhookStu"]}' },
  request:
   ClientRequest {
     _events:
      [Object: null prototype] {
        socket: [Function],
        abort: [Function],
        aborted: [Function],
        connect: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 7,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: null,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'localhost',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(asyncId)]: 1022,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'localhost',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(asyncId)]: 1022,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     _header:
      'POST /multitenancy/wallet HTTP/1.1\r\nAccept: application/json\r\nContent-Type: application/json\r\nX-API-Key: nFg33#rtUIkf3\r\nUser-Agent: axios/0.25.0\r\nContent-Length: 212\r\nHost: localhost:5050\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256 },
     socketPath: undefined,
     timeout: undefined,
     method: 'POST',
     insecureHTTPParser: undefined,
     path: '/multitenancy/wallet',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [Socket],
        connection: [Socket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 400,
        statusMessage: 'ProfileSessionInactiveError.',
        client: [Socket],
        _consuming: false,
        _dumped: false,
        req: [Circular],
        responseUrl: 'http://localhost:5050/multitenancy/wallet',
        redirects: [] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _options: [Object],
        _ended: true,
        _ending: true,
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 212,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'http://localhost:5050/multitenancy/wallet' },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] {
        accept: [Array],
        'content-type': [Array],
        'x-api-key': [Array],
        'user-agent': [Array],
        'content-length': [Array],
        host: [Array] } },
  response:
   { status: 400,
     statusText: 'ProfileSessionInactiveError.',
     headers:
      { 'content-type': 'text/plain; charset=utf-8',
        'content-length': '33',
        date: 'Fri, 17 Mar 2023 09:26:19 GMT',
        server: 'Python/3.6 aiohttp/3.8.4',
        connection: 'close' },
     config:
      { transitional: [Object],
        adapter: [Function: httpAdapter],
        transformRequest: [Array],
        transformResponse: [Array],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        maxBodyLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'post',
        url: 'http://localhost:5050/multitenancy/wallet',
        data:
         '{"key_management_mode":"managed","wallet_dispatch_type":"default","wallet_key":"MySecretKey123","wallet_name":"zzzhtlczauniex2","wallet_type":"indy","wallet_webhook_urls":["http://MY_IP:3005/webhookStu"]}' },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header:
         'POST /multitenancy/wallet HTTP/1.1\r\nAccept: application/json\r\nContent-Type: application/json\r\nX-API-Key: nFg33#rtUIkf3\r\nUser-Agent: axios/0.25.0\r\nContent-Length: 212\r\nHost: localhost:5050\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        insecureHTTPParser: undefined,
        path: '/multitenancy/wallet',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     data: '400: ProfileSessionInactiveError.' },
  isAxiosError: true,
  toJSON: [Function: toJSON] }`

For postgres is here (2nd test):
`{ error: sorry, too many clients already
    at Parser.parseErrorMessage (/home/avraam/blockademic/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/avraam/blockademic/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/avraam/blockademic/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.stream.on (/home/avraam/blockademic/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  length: 85,
  name: 'error',
  severity: 'FATAL',
  code: '53300',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'proc.c',
  line: '344',
  routine: 'InitProcess' }`

**Comment by usingtechnology** [comment]
Can you try something like this...
Create a `max_conns.sql` file.
```
ALTER SYSTEM SET max_connections = 500;
```
Then in your docker compose for your postgres/wallet db, something like:
```
  wallet-db:
    image: postgres:15
    hostname: ${POSTGRESQL_HOST}
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    networks:
      - app-network
    volumes:
      - wallet-db-data:/var/lib/pgsql/data
      - ./max_conns.sql:/docker-entrypoint-initdb.d/max_conns.sql    
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 3s
      retries: 5
```
I had issues during load testing that default postgres couldn't keep up with the connections.  That at least got me past that error. `ProfileSessionInactiveError` is a bit of a catch all when you can't do anything with the base/wallet or sub-wallet.

**Comment by GautamR24** [comment]
> Can you try something like this... Create a `max_conns.sql` file.
> 
> ```
> ALTER SYSTEM SET max_connections = 500;
> ```
> 
> Then in your docker compose for your postgres/wallet db, something like:
> 
> ```
>   wallet-db:
>     image: postgres:15
>     hostname: ${POSTGRESQL_HOST}
>     environment:
>       POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
>     networks:
>       - app-network
>     volumes:
>       - wallet-db-data:/var/lib/pgsql/data
>       - ./max_conns.sql:/docker-entrypoint-initdb.d/max_conns.sql    
>     healthcheck:
>       test: pg_isready -U postgres
>       interval: 3s
>       timeout: 3s
>       retries: 5
> ```
> 
> I had issues during load testing that default postgres couldn't keep up with the connections. That at least got me past that error. `ProfileSessionInactiveError` is a bit of a catch all when you can't do anything with the base/wallet or sub-wallet.

@usingtechnology I have changed the docker file as per your input. 
This is how I have added the required file in docker 
![image](https://github.com/hyperledger/aries-cloudagent-python/assets/48410350/a503f72d-633d-488f-8fcf-93680a0516b7)

Till creation of **49th wallet,** everything is working fine.
**But when 50th wallet is being created I am still getting this error "400: ProfileInactiveSessionError".**

**This is the screenshot of DB logs:**
[
![Screenshot from 2023-05-30 17-27-52](https://github.com/hyperledger/aries-cloudagent-python/assets/48410350/e1048470-a76f-4348-bff9-0beb1f16b68e)
](url)

On creation of 49th wallet, controller is getting logs showing the response from swagger, which shows it is successful.
After this when 50th wallet is being created, I am getting that same **"profileError"**
![image](https://github.com/hyperledger/aries-cloudagent-python/assets/48410350/9f26ec97-717e-4685-a2bb-9cfee45d8d4b)

**Comment by dinbtechit** [comment]
@GautamR24  - Did you manage to fix this error?

**Comment by GautamR24** [comment]
Hey,

Just wanted to know, anyone still facing the mentioned issue. If not, great.
If yes, then I could share something that I tried and worked out for me.

Thanks.

**Comment by dinbtechit** [comment]
In my situation, we encountered this error while trying to establish a connection with a database encrypted using a different wallet key.
