### ISSUE TITLE
Deeper solution for stuck messages in mediator - race condition w.r.t connection state

### ISSUE THREAD

**Issue by shaangill025** [hyperledger/aries-cloudagent-python#2160]
Follow up to issue #2111 and PR #2147, which should fix it but @dbluhm suggested that a deeper [more elegant] solution for the issue should be explored/discussed in future.

**Comment by swcurran** [comment]
As I understand it — this issue references this @dbluhm [comment on issue #2147](https://github.com/hyperledger/aries-cloudagent-python/pull/2147#discussion_r1123415171).

@shaangill025 please confirm.

**Comment by shaangill025** [comment]
Yes, to be specific the comment linked [above](https://github.com/hyperledger/aries-cloudagent-python/pull/2147#discussion_r1123415171) and [this](https://github.com/hyperledger/aries-cloudagent-python/pull/2147#discussion_r1129989478).
