### ISSUE TITLE
The DID resolver and DID Admin Endpoint should also resolve local only DIDs

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2161]
The ACA-Py DID resolver and the Admin API endpoint `GET /resolver/resolve/{did}` evidently does not resolver local only DIDs -- e.g. peer DIDs used for DIDComm connections.  This issue is to extend the resolver to include checking for and resolving such DIDs.  For example, I should be able to grab `theirdid` from a Connection object and resolve it to see the DIDDoc related to that DID. The resolution process should only check locally for properly qualified `peer:did` DIDs. For unqualified DIDs, it's a little trickier since there are both unqualified local (peer) and ledger-based (`did:sov`) DIDs. If there is not a way to tell if the type (local or ledger-based) of such a DID, the approach should probably be to try to resolve it as a local DID, and if it is not, to try to resolve it on a ledger.

Comments from @shaangill025 @dbluhm and others welcome.

**Comment by shaangill025** [comment]
Something to consider
- I think Peer method 1 DIDDoc is always resolved from storage and not ledger
- Peer DIDs will be linked to use of Askar wallet

Currently the correct resolve function is called based upon the applicable DIDMethod, any unqualified DID will trigger an `InvalidDIDError exception` when calling `PyDID's validate DID function`. I think for unqualified DID, we update the resolve function which should first try to resolve as Peer DID with `f"did:peer:1{unqualified_did}"` and if nothing found then proceed as `did:sov`

**Comment by swcurran** [comment]
That definitely won’t work, as the `{identifier}` part of `did:peer:1{identifier}` is not the same as the `{unqualified_did}`. It must be possible to search by `{unqualified_did}` in local storage to find it.  At some point, we may convert `{unqualified_did}` into a derivable format (leaning towards `did:peer:2` right now), but even then we will likely still have to be able to search for and find it in storage — e.g. keep a tag for the item.

**Comment by shaangill025** [comment]
- `create_local_did` will store the DID in wallet, so when we have an unqualified DID, are we are only trying to convert did:sov:{unqualified_did} and not did:key:{unqualified_did} (masked indy dids when storing in Indy wallet) or when derived from fingerprint (askar)] into Peer DID?
- When old DIDDoc are being converted for Peer method 1, we store Peer DID in wallet and put the corresponding unqualified DID as a tag in the StorageRecord. I think this can be managed within method 1, as we can resolve old DIDDoc from unqualified DID from storage.
- For new DIDDoc, we create a new DIDKEY keypair, store to wallet, use that DIDDoc to compute method 1 Peer DID and put the [DIDKey.did](https://didkey.did/) as unqualified_did StorageRecord tag.

**Comment by swcurran** [comment]
@shaangill025 — we aren’t at this time converting any DIDs.  This tasks is just to extend the current resolver so that when  an unqualified DID is passed via the endpoint, we want to look at the difference places it may have been defined.  Currently we have two flavours of unqualified DIDs:

- Local unqualified DIDs exist in the wallet and are created when we are creating a DIDComm communication. The DID might be `theirdid` or `mydid` in the connection record, and there should be a did record with the associated DIDDoc to be found and returned.  They have no standardized qualifier, and there is a current discussion in the Aries community about what to do with them. Strongest contender right now is to make them `did:peer:2` DIDs, but the decision hasn’t been made.
- Public unqualified DIDs exist on an Indy ledger. They are the equivalent to `did:sov` DIDs. AFAIK they may be in the wallet and so we might want to check there, or they need to be resolved by going to the ledger(s).

This ticket is to extend the DID Resolver (if needed) and the Admin API to accept an unqualified DID and resolve it.

### Resolving Public Unqualified DIDs

> An additional note to be considered in the future. We can ignore this for this ticket, but perhaps something for the future — if the behaviour I describe is actually happening.  When investigating the code, please add a note to this ticket of how the resolver works with public unqualified DIDs.

> Note: If we resolve a public DID only from the wallet, we are essentially getting a cached copy, and the on ledger DID may have changed. In a future PR we may want to extend the API to add an optional “getFromVDRyn” parameter to force going to the ledger for public DIDs.
