### ISSUE TITLE
Missing credential_preview in Credential Offer for AIP2 JSONLD credentials

### ISSUE THREAD

**Issue by NB-MikeRichardson** [hyperledger/aries-cloudagent-python#2171]
This error appears to be caused by a mismatch in the implementation of the protocol for API2.0 credential offer between aca-py and AFJ (for JSONLD credentials)

This is the format we expect in AFJ…

![image](https://user-images.githubusercontent.com/93971245/225627266-f9c5334c-8afd-46c4-a20b-27a274f9ab3e.png)

But it looks (from the error message we see in AFJ validation of the incoming offer message) as if aca-py is not including the credential_preview object. It appears to be optional for credential proposals but mandatory for credential offers:

See protocol specification here:[aries-rfcs/README.md at main · hyperledger/aries-rfcs](https://github.com/hyperledger/aries-rfcs/blob/main/features/0453-issue-credential-v2/README.md) Search for credential_preview. You will see it is optional for propose credential, but mandatory for offer credential. 

For AFJ we add this field but it is empty as although mandatory according to the above protocol, it is not used in JSON-LD credentials. Note the attribute array is empty in the above image of an AFJ credential.

**Comment by swcurran** [comment]
Closing as stale -- reopen if needed.
