### ISSUE TITLE
Mobile Wallet Not Created

### ISSUE THREAD

**Issue by PenguinTaro** [hyperledger/aries-cloudagent-python#2176]
I have configured the Aries bifold App with afj mediator.Able to establish a connection between Mobile agent and Mediator.As Mediator's wallet is being created but dont understand why Mobile agent's wallet is not been created in Mediator.
I have also Connected my Mobile agent with another ACA-py Agent (issuer)and able to establish connection between these agents using mediator.after scanning QR code the app just keeps spinning until i send the credential offer from issuer .The cred-offer is being accepted by Mobile Agent and credentials are being issued and visible on Mobile App.but in ACA-py(swagger UI) it is throwing error in issue-credential/records/cred_ex_id "Wallet Item not found".I dont understand where this credential is being stored since Mobile Agent's wallet is not been created.
I am attaching the screenshot of Error from Swagger UI.

![image](https://user-images.githubusercontent.com/99000637/227177937-b07a472e-4f3a-43b6-840b-d6bd0d4294f6.png)

**Comment by swcurran** [comment]
Closing this as old. Sorry for the lack of feedback. This works for most people, some likely something local.
