### ISSUE TITLE
Incompatibility with Javascript Framework

### ISSUE THREAD

**Issue by biagioboi** [hyperledger/aries-cloudagent-python#2177]
I'm trying to develop a web application wich use Python on server side and Javascrpt on client side.

This is possible thanks to the architecture but problems with this approach are related to one field on the invitation, which is different between javascript and python.

Here is the aca-py invitation:
![IMAGE 2023-03-23 14:17:32](https://user-images.githubusercontent.com/49649951/227216055-ec92d251-25f2-4e31-9963-33dfbf0e38b0.jpg)

Here is the javascript invitation:
 
![IMAGE 2023-03-23 14:18:17](https://user-images.githubusercontent.com/49649951/227216234-4b7bda5c-807b-4dfb-9537-64103a8e54ea.jpg)

The difference is on the field "service" which is "services" in javascript.
Since it is describing a list of service, should be converted into services also in python.

**Comment by swcurran** [comment]
@shaangill025 — is this addressed as part of the work you are doing on Peer DIDs?  Or should this be a separate issue?

**Comment by biagioboi** [comment]
the issue has been solved in newer version
