### ISSUE TITLE
=> ERROR [internal] load metadata for docker.io/bcgovimages/von-image:py36-1.15-1  

### ISSUE THREAD

**Issue by GundamDyname** [hyperledger/aries-cloudagent-python#2208]
when i try Start Agent by used The following command :
PORTS="8080:8080 8000:8000" \
scripts/run_docker start --wallet-type indy \
--seed 000000000000000000000000000Agent \
--wallet-key welldone \
--wallet-name myWallet \
--genesis-url http://von_ip_address/genesis \
--inbound-transport http 0.0.0.0 8000 \
--outbound-transport http \
--admin 0.0.0.0 8080 \
--admin-insecure-mode

will return an error 
[+] Building 3.4s (16/16) FINISHED                                              
 => [internal] load build definition from Dockerfile.run                   0.1s
 => => transferring dockerfile: 651B                                       0.0s
 => [internal] load .dockerignore                                          0.1s
 => => transferring context: 138B                                          0.0s
 => [internal] load metadata for docker.io/bcgovimages/von-image:py36-1.1  2.4s
 => [ 1/11] FROM docker.io/bcgovimages/von-image:py36-1.15-1@sha256:7ba94  0.0s
 => [internal] load build context                                          0.8s
 => => transferring context: 7.78MB                                        0.8s
 => CACHED [ 2/11] ADD requirements*.txt ./                                0.0s
 => CACHED [ 3/11] RUN pip3 install --no-cache-dir     -r requirements.tx  0.0s
 => CACHED [ 4/11] RUN mkdir aries_cloudagent && touch aries_cloudagent/_  0.0s
 => CACHED [ 5/11] ADD aries_cloudagent/version.py aries_cloudagent/versi  0.0s
 => CACHED [ 6/11] ADD bin ./bin                                           0.0s
 => CACHED [ 7/11] ADD README.md ./                                        0.0s
 => CACHED [ 8/11] ADD setup.py ./                                         0.0s
 => CACHED [ 9/11] RUN pip3 install --no-cache-dir -e .                    0.0s
 => CACHED [10/11] RUN mkdir logs && chown -R indy:indy logs && chmod -R   0.0s
 => CACHED [11/11] ADD aries_cloudagent ./aries_cloudagent                 0.0s
 => exporting to image                                                     0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:a5c8cf8066cac0ad71f2023333ec8b35d2c4dbba65e36  0.0s
 => => naming to docker.io/library/aries-cloudagent-run                    0.0s

Container name: aries-cloudagent-runner_mqry6cAJDE3WvsGJ
No Docker network specified.

please give me some help

**Comment by swcurran** [comment]
Sorry for the lack of response. Likely a local issue, but not sure what. Closing as this works for the vast majority.
