### ISSUE TITLE
Test out, update documentation and enable the use of Redis with ACA-Py deployments

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2212]
Please review and apply the documentation for the use of Redis for both a Presistent Queue and Cache for us in ACA-Py deployments. In doing so, update the documentation and add additional examples as you think would help others in deploying ACA-Py.

As this work is being done for BC Gov, and we use OpenShift, please make sure the information is available for use in that environment.

Some ideas:

* Perhaps it would be useful to have an alternate way to run the demo with a Redis deployment, and settings.  Perhaps that could be done by having the use start a dockerized Redis and passing in the right parameters via an option to `./run_demo`, or perhaps have a separate docker-compose file with Redis included.
* The first thing we need to have available is Redis deployed with the BC Gov Mediator.  As such, that should be considered the first target. In that — we don’t need multiple instances of the mediator running, just one. But we do want the queue to survive the Mediator instance being moved within OpenShift — stopped on one node and started on another.  Running multiple ACA-Py mediator instances is complicated by the use of Web Sockets, and we will have a separate issue/effort to solve that from this one.
* Once we can run with Redis, we want to be able to do load testing on environments with and without Redis to understand the impact of using it.  Collaborate with @usingtechnology on techniques to load test a Redis deployment (or at least, a Redis Mediator deployment) and a comparable non-Reds-based deployment.

**NOTES:**

* Others in the community use Kafka instead of Redis for the persistent queues. AFAIK, that does not cover the shared cache needs. Repository is [here](https://github.com/sicpa-dlab/aries-acapy-plugin-kafka-events).
* I think the [ACA-Py Redis documentation](https://aca-py.org/main/deploying/RedisPlugins/) references the [Indicio-developed Redis caching configuration](https://github.com/Indicio-tech/aries-acapy-cache-redis).

Questions?  Let’s use this issue for now.

**Comment by swcurran** [comment]
Some notes from our discussion about immediate needs:

Most immediate goal is to get Redis PQ and cache running with an ACA-Py instance deployed for use an Aries Mediator Service (https://github.com/hyperledger/aries-mediator-service). We don’t (yet) need an ACA-Py mediator running as HA (e.g. with multiple instances of ACA-Py collaborating), but we do need to prevent the loss of messages when the single ACA-Py instance is moved by the OpenShift/K8S scheduler. Hence the use of Redis for even the single instance setup.

So:

- understand the general Redis setup with ACA-Py. How to configure, example config., is the documentation accurate.
- add Redis to the Aries Mediator Service setup so that it runs exactly the same with/without Redis
- merge with Sherman’s work on load testing/tracing ACA-Py so we can see the impact of running Aries Mediator Service with/without Redis.

In doing that — collecting lessons learned, improve docs, adding scripts that help others are a benefit, etc.

**Comment by Jsyro** [comment]
Updates (I think dropping updates in the gh issues is a good suggestion):

- [redis plugin](https://github.com/bcgov/aries-acapy-plugin-redis-events/) documentation is good, but the simple examples are missing.
- Was recommended to investigate AATH as a way to test aca-py with redis vs aca-py without redis. 
- Setup build configuration on openshift to build acapy/redis in dev namespace

**Comment by Jsyro** [comment]
https://github.com/hyperledger/aries-agent-test-harness/issues/677

**Comment by Jsyro** [comment]
Running the redis events queue plugin and redis cluster provided similar results to existing aca-py configurations!

Adding a configuration to the mediator-service repo that included redis. https://github.com/hyperledger/aries-mediator-service/pull/78

Working with Wade to deploy into BCGov openshift.
