### ISSUE TITLE
Can't access admin aca-py swagger page

### ISSUE THREAD

**Issue by DimKasimatis** [hyperledger/aries-cloudagent-python#2213]
Hi, I have started an aries agent with the following commands:

`PORTS="8000 8001"
./run_docker start \
-l Ndia \
-it http 0.0.0.0 8000 \
-ot http \
--admin 0.0.0.0 8001 \
--admin-insecure-mode \
-e http://192.168.152.116:8000 \
--genesis-url http://192.168.152.116:9000/genesis \
--wallet-type indy \
--wallet-name issuerwallet \
--wallet-key issuerkey \
--log-level info \
--auto-provision \
--auto-accept-invites \
--auto-accept-requests \
--auto-ping-connection \
--tails-server-base-url https://9a38-37-60-109-30.ngrok.io \
--seed Ndia0000000000000000000000000010`

The agent appears to startup as it should but when I try to access the admin page to see the API docs I get nothing. 
These are the docker logs for the agent:
![image](https://user-images.githubusercontent.com/52934158/233808798-9d2d7b06-d98f-4964-9899-d95a9766eef0.png) 
Appreciate any help that can get me to the aca-py swagger page.

**Comment by WadeBarnes** [comment]
Based on your startup parameters the admin API page should be available at http://localhost:8001/api/doc

**Comment by terilenard** [comment]
Hello,

Similar issue here. From what I saw so far the port of the swagger API is not accessible.

Tried to run the following code to start acapy:

```
PORTS="8000 8001" \ 
sudo ./run_docker start -l Issuer -it http 0.0.0.0 8000 -ot http --admin 0.0.0.0 8001 --admin-insecure-mode -e http://192.168.134.140:8000/ --genesis-url http://172.17.0.1:9000/genesis --wallet-type indy --wallet-name issuerwallet --wallet-key issuerkey --log-level "INFO" --auto-provision --auto-accept-invites --auto-accept-requests --auto-ping-connection --seed issuer00000000000000000000000000
```

Output is the same as above, and von-network is up and running. Additionally, curl-ing port 8000 and 8001 fails:

```
curl http://192.168.134.140:8000/

curl: (7) Failed to connect to 192.168.134.140 port 8000: Connection refused
```

Moreover, I tried to run the `generate-open-api-spec` script. Gave the following output:

```
##########################################################################################
#
#  Starting ACA-py docker image with command: 
 	 docker run -d --rm --name aries-cloudagent-run_9xqSHBEmNqvQ0HRi -p 8307:8307 -p 8305:8305 -v //home/teri/workdir/TestBed-Network/aries-cloudagent-python/scripts/../logs:/home/indy/logs aries-cloudagent-run start -e http --inbound-transport http 0.0.0.0 8307 --outbound-transport http --admin 0.0.0.0 8305 --admin-insecure-mode --log-level info --wallet-type indy --wallet-name gen-openapi --wallet-key gen-openapi-key --no-ledger
#
##########################################################################################

Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
Waiting for web interface to activate
**** FAIL - Web interface failed to activate in 20 seconds. ****
0906aad4d7a0d7930f5a983dbe7473cc16efab17c8d20fd04caf3ee6906c26d4

```

**Comment by swcurran** [comment]
Closing this as likely a local issue. Works for the vast majority -- not sure the issue here.
