### ISSUE TITLE
LEDGER_URL missing in JSON-LD Lab

### ISSUE THREAD

**Issue by janesp** [hyperledger/aries-cloudagent-python#2215]
`ERROR:runners.support.agent:Error loading genesis transactions` while executing lab example

Amendments required for JSON-LD lab

`./run_demo faber --did-exchange --aip 20 --cred-type json-ld`

should be
`LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo faber --did-exchange --aip 20 --cred-type json-ld`

Same for Alice agent `LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo alice`

**Comment by swcurran** [comment]
Thanks.  It really shouldn’t be needed if we aren’t using Indy-based credentials, but I agree it is right now.
