### ISSUE TITLE
A wallet with a blank string imageUrl (or invalid url) creates a connection invitation that cannot be received

### ISSUE THREAD

**Issue by loneil** [hyperledger/aries-cloudagent-python#2254]
I don't _think_ this is a Traction-specific issue (see below), and it might be intended behaviour, but raising this for any thoughts and to bring to attention.

If I set my tenant's wallet image_url to a blank string (or any **invalid** URL) then invitations that are created with `/connections/create-invitation` end up with a invitation like this:
```
{"@type": "https://didcomm.org/connections/1.0/invitation", "@id": "xxx...", "imageUrl": "", "label": "TenantName", "recipientKeys": ["xxx..."], "serviceEndpoint": "xxx..."}
```

Attempting to `receive-invitation` that connection invite then throws a 422 with 
```{"imageUrl": ["Not a valid URL."]}```

If using it as an invitation QR code, the BC Wallet generically fails.
![image](https://github.com/hyperledger/aries-cloudagent-python/assets/17445138/f15760fa-984b-4426-bc33-b14f6bf3d2dc)

So it appears to be any invalid non-formatted URL, but the blank string is a little worse I think as then if you clear it by blanking out the string it still won't work.

I don't know if this would be in **single**-tenant ACA-Py, I've only dealt with mult-tenant.

Note: in Traction we can probably control this at input validation (at the plugin API, and in the Tenant UI both)
see this issue https://github.com/bcgov/traction/issues/641
but still raising this for any acapy systems not using Traction plugins.

**Comment by loneil** [comment]
Not sure what a good solution to this would be if required. Assuming a bad image_url gets in there what should happen with these connections? Prevent create-invitation from proceeding? Handle receiving the invitation anyways?

**Comment by swcurran** [comment]
Closing as stale -- reopen if needed.
