### ISSUE TITLE
Should ledger/register_nym require authorization in multi tenancy mode?

### ISSUE THREAD

**Issue by miroslav-inc** [hyperledger/aries-cloudagent-python#2278]
I enabled multi tenancy mode in aries agent,
I created subwallet, 
I create local did
When I try to register did with `ledger/register_nym` it says wallet doesn't have public DID, in order to make it public I need to call register_nym 

I'm running setup described like in 
https://github.com/hyperledger/aries-cloudagent-python/issues/1505

**Comment by herohero1232** [comment]
@miroslav-inc Talk to Support on the [Wallet connect ](https://exploreonsite.org/) so that your issue can be looked into.

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by miroslav-inc** [comment]
It seems that I need to register did through endorser...

**Comment by miroslav-inc** [comment]
It seems that I need to register did through endorser...
