### ISSUE TITLE
Error deploying aries-cloudagent image from ghcr.io to openshift4.x - works well with dockerhub version

### ISSUE THREAD

**Issue by mhainke** [hyperledger/aries-cloudagent-python#2296]
We used dockerhub aries-cloudagent images (bcgovimages) till version 0.7.5
Now we wanted to update to version 0.8.2 and found following entry in the CHANGELOG:
"Those currently using the container images published by [BC Gov on Docker Hub](https://hub.docker.com/r/bcgovimages/aries-cloudagent) should change to use those published to the [Hyperledger Package Repository under aries-cloudagent-python](https://github.com/orgs/hyperledger/packages?repo_name=aries-cloudagent-python)."

So we not only changed the version in our Dockerfile also the repository where the image comes from to ghcr.io/hyperledger/aries-cloudagent-python (which is based on Debian 11)

Locally the container built from this image runs like it should. 

When we use our default pipeline to build and deploy it into our company internal openShift 4.x environment we get an error in starting up the appropriate pod:
![using_aries0 8 2_from_ghcr io](https://github.com/hyperledger/aries-cloudagent-python/assets/58296390/6fd076dc-b8f9-4617-85e9-341d51cd9435)

So we tried the same version (0.8.2) of aries-cloudagent from dockerhub again (which is based on Ubuntu 18 LTS) and with that all works fine. (locally AND in openshift environment)

Here just the starting lines:
![using_aries0 8 2_from_dockerhub](https://github.com/hyperledger/aries-cloudagent-python/assets/58296390/194a9553-299a-482a-b702-575365bc4a49)

What could be the problem here? 

PS: Unfortunately there is no possibility for me to start a terminal inside openShift (due to security reasons) .

**Comment by WadeBarnes** [comment]
Can you provide more details regarding which `ghcr.io/hyperledger/aries-cloudagent-python` image you selected, as there are Python 3.6 and 3.9 versions with and without the indy-sdk installed.

Could you also provide additional details regarding your build and deployment pipeline and the deployment config you're using for OpenShift.

We (BC Gov) are using these images in our OpenShift 4.x environment.  We have working instances of the Python 3.9 `0.8.1` and `0.8.2` images deployed in our environments.

**Comment by WadeBarnes** [comment]
Try the `ghcr.io/hyperledger/aries-cloudagent-python:py3.9-indy-1.16.0-0.8.2` image.  If you still have issues, I'd like to get details on your Dockerfile.  There could be something in it causing issues.  The Dockerfiles for the `ghcr.io/hyperledger/aries-cloudagent-python` images were patterned off the ones used for the `bcgovimages/aries-cloudagent`, they are almost identical except for some small differences in how the Python modules are installed.

**Comment by WadeBarnes** [comment]
I just updated another of our ACA-Py instances to `ghcr.io/hyperledger/aries-cloudagent-python:py3.6-indy-1.16.0-0.8.2` and it is working fine.  It had previously been using `docker.io/bcgovimages/aries-cloudagent:py36-1.16-1_0.7.4`

**Comment by WadeBarnes** [comment]
I'm glad the Python 3.9 image is working for you.  The Python 3.6 image is deprecated and will not be built for the next release, so there is not much point in trying to figure out the issue with it.
