### ISSUE TITLE
indy-base pull access denied in run_demo faber

### ISSUE THREAD

**Issue by tko85** [hyperledger/aries-cloudagent-python#2298]
When trying to run the demo I get this error message:
git clone https://github.com/hyperledger/aries-cloudagent-python
cd aries-cloudagent-python/demo
LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo faber
Preparing agent image...
Dockerfile.demo:1
--------------------
   1 | >>> FROM indy-base
   2 |     
   3 |     ENV ENABLE_PTVSD 0
--------------------
ERROR: failed to solve: indy-base: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

**Comment by swcurran** [comment]
@usingtechnology — sorry to yank you on this, but can you look at this, immediately?

What has changed that has broken this?  Need to get this fixed ASAP.  I was able to replicate with the latest main.

**Comment by usingtechnology** [comment]
ok, starting in on it.

**Comment by WadeBarnes** [comment]
The changes here https://github.com/hyperledger/aries-cloudagent-python/pull/2247 made the switch to using `indy-base` in teh docker file(s).

**Comment by usingtechnology** [comment]
what is `indy-base` then? i immediately went to see what was published on docker and then here... nothing.

**Comment by usingtechnology** [comment]
ok, i see that it is a prelim step in run_demo... looking into why it isn't working

**Comment by WadeBarnes** [comment]
https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/run_bdd#L129

**Comment by WadeBarnes** [comment]
The same build needs to be added here; https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/run_demo#L151-L152

**Comment by usingtechnology** [comment]
thanks @WadeBarnes.

**Comment by WadeBarnes** [comment]
and have a look to see if there are any other locations using `../docker/Dockerfile.demo` without building the `indy-base` image first.

**Comment by usingtechnology** [comment]
that seems to be the only place (other than bdd) using `Dockerfile.demo`
