### ISSUE TITLE
Present Proof Ack

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#230]
Right at the beginning of the RFC, it mentions that `ack` is adopted into the protocol for confirmation:
https://github.com/hyperledger/aries-rfcs/blob/master/features/0037-present-proof/README.md#tutorial

This adoption of `ack` is not explored in detail but it would be useful to have this implemented in ACA-Py so the holder knows more than just a final state of `presentation_sent` at the end of an exchange with a verifier and can know that the presentation was at least received.

**Comment by swcurran** [comment]
So after receiving the proof, the verifier would send an ack back to the prover.

@sklump - does this make sense as an addition to the protocol?  Do you want to do this?

**Comment by sklump** [comment]
I can take this.

**Comment by andrewwhitehead** [comment]
Closed via #232
