### ISSUE TITLE
Alice demo image fails to build

### ISSUE THREAD

**Issue by tko85** [hyperledger/aries-cloudagent-python#2301]
The Alice demo agent never gets past 'Preparing agent image...'.  See below.

git clone https://github.com/hyperledger/aries-cloudagent-python
Cloning into 'aries-cloudagent-python'...
remote: Enumerating objects: 63199, done.
remote: Counting objects: 100% (1702/1702), done.
remote: Compressing objects: 100% (789/789), done.
remote: Total 63199 (delta 987), reused 1471 (delta 899), pack-reused 61497
Receiving objects: 100% (63199/63199), 43.21 MiB | 12.25 MiB/s, done.
Resolving deltas: 100% (47273/47273), done.
[node2] (local) root@192.168.0.17 ~
$ cd aries-cloudagent-python/demo
[node2] (local) root@192.168.0.17 ~/aries-cloudagent-python/demo
$ LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo alice --events --no-auto --bg

Running in alice in the background. Note that you cannot use the command line console in this mode.
To see the logs use: "docker logs alice".
While viewing logs, hit CTRL-C to return to the command line.
To stop the agent, use: "docker stop alice". The docker environment will
be removed on stop.

Preparing agent image...

**Comment by swcurran** [comment]
Hmmm…working fine for me.  I assume since you got faber working you have an up to date repo, with the latest change. 

I deleted the image and still had no problem.

It can take a little but build the image…

Not sure what it might be.

**Comment by swcurran** [comment]
Closing this as tested. If you can provide more details about what might be different about the run, please re-open.

Thanks
