### ISSUE TITLE
Need to preset indy_client folder with Askar before creating Revocation Registry

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2307]
Something (TBD) has changed in 0.8.2 such that when used with Askar, the folder to hold the Tails Files is not being created and thus, Revocation Registry creation is stopped in the "init" state. As a result, issuance fails as the holder can't get the Tails File.

Need to further investigate this issue and figure out what is happening, what changed that caused this behaviour, and what is the correct change to make to fix the behaviour.

Also, an environment variable `EXTERNAL_STORAGE` was found that was not previously documented. This should at minimum be turned into a configuration parameter and documented. If the name needs to be changed, that can happen -- announced as a breaking change.

We need a fix in the next couple of days to get this into a 0.8.3 patch release we have pending.

@esune @loneil

**Comment by swcurran** [comment]
@loneil -- what version were you running when this last worked?  Recall that Traction previously ran on 1.0.0-rc0 (I think) so this might have been broken before 0.8.2.  I scanned the 0.8.2 PRs and I don't see any that (at least on the surface) could have triggered this change.

**Comment by loneil** [comment]
This appears to works with 0.8.2 using this image ` bcgovimages/aries-cloudagent:py36-1.16-1_0.8.2`
when a revocable cred is created in that instance the tails file folder `.indy_client` is created and appears to be owned by the INDY user.

On the image with no Indy being used now `ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.8.2` the error occurs when that folder (which I'm not sure would be named `indy`) cannot be created by the ARIES user it appears.

**Comment by swcurran** [comment]
Ah -- OK, that would explain it.  @WadeBarnes -- are you familiar with the differences in the two Dockerfiles?  I'm guessing in removing the indy-sdk from the latter, the .indy_client folder was removed as well, even though it is used by Askar as well as the Indy SDK.

If that is the issue, please look to see if we can recreate the same container image with the correction.  Is that the right approach?

**Comment by swcurran** [comment]
That looks to me like the issue. Where as in Dockerfile.Indy, a number of folders are created [here](https://github.com/hyperledger/aries-cloudagent-python/blob/7f223e558ec07dc4e048d14bb79025f042d89a9f/docker/Dockerfile.indy#L161), a number of those folders are not created in the Dockerfile that uses Askar [here](https://github.com/hyperledger/aries-cloudagent-python/blob/7f223e558ec07dc4e048d14bb79025f042d89a9f/docker/Dockerfile#L78).

**Comment by WadeBarnes** [comment]
That is correct.  The Askar only image (the one without the indy-sdk) does not contain or use the `indy_client` folders.  Those were only used with the indy-sdk.  Askar uses the `aries_cloudagent` folder.

**Comment by swcurran** [comment]
That is what we have discovered is **not** correct.  In ACA-Py, the .indy_client folder is used, as Emiliano found.  We need to update the Dockerfile to add back in the indy_client folder for Askar.

**Comment by WadeBarnes** [comment]
I'm not sure it makes sense to include the `.indy_client` folder on an image that does not contain the indy-sdk.  What is writing the tails file and why is it trying trying to write it to an indy-sdk specific folder?

**Comment by swcurran** [comment]
The directory is being used is defined in ACA-Py ([here](https://github.com/hyperledger/aries-cloudagent-python/blob/7f223e558ec07dc4e048d14bb79025f042d89a9f/aries_cloudagent/indy/util.py#L15)) and does not care of the Indy SDK or Askar is being used.  It is just creating the folder that will be used for the temp location of tails files. It is old code and could be improved based on what we know know.

In theory we could use the `EXTERNAL_STORAGE` undocumented env. variable (not start up parameter, unfortunately) to change the name, and maybe we'll do that later. But I think right now we just need to revert the change of not creating the `.indy_client` folder since it is having unexpected side effects -- like breaking revocation.

**Comment by WadeBarnes** [comment]
The Askar only docker file has never had the `.indy_client` folder in it.  Strange that we're finding this problem now.  The image must not be in wide use.  I'll add the `.indy_client` folder to the image.

**Comment by WadeBarnes** [comment]
A pre-release image was created [ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.8.3-pre](https://github.com/hyperledger/aries-cloudagent-python/pkgs/container/aries-cloudagent-python/110532436?tag=py3.9-0.8.3-pre).  @loneil tested the new image and indicated it fixed the reported issues.

**Comment by loneil** [comment]
Still agree `.indy_client` is a strange name for this folder to hold tails on an askar-only deployment (I think, unless I'm misunderstanding the naming). So could be good to change that up in the future.
If that happens would there be any migration issues for a system that uses the `.indy_client` folder now, and later it gets set to something else?

**Comment by WadeBarnes** [comment]
If a user needs to persist the files they would mount a persistent volume to the folder.  Later if the folder name was changed the volume could just be mounted to the new location.  Otherwise the tails files are ephemeral and would be downloaded as needed.

**Comment by swcurran** [comment]
We talked about it in the Aries Maintainer’s call. There is agreement on the naming given that the `.aries_cloudagent` folder is there.  Even more troublesome is the undocument environment variable (not config parameter) and hard-coded value.  We’ll add an issue in to address at some point. Painful, but not that painful.
