### ISSUE TITLE
Dependency bugs when starting ACA-py agents using Docker

### ISSUE THREAD

**Issue by finnformica** [hyperledger/aries-cloudagent-python#2311]
Hi all, I am new to the Hyperledger space and trying to get my first Aries agents up and running using docker. I have been running into several issues while starting and I was hoping to get some help from everyone. Firstly, I am running all of this on an M1 MacBook Pro with macos Ventura 13.2.1.

Following the documentation [here](https://github.com/hyperledger/aries-cloudagent-python/blob/main/DevReadMe.md#docker) I have been attempting to run ACA-py agents using the `scripts/run_docker start` command as detailed in the README above. A von-network server is already running with an 'Alice' DID written to the ledger. The exact command used is:

```
scripts/run_docker start \
--inbound-transport http 0.0.0.0 8000 \
--outbound-transport http \
--admin 0.0.0.0 11000 \
--admin-insecure-mode \
--genesis-url http://host.docker.internal:9000/genesis \
--seed Alice000000000000000000000000001 \
--endpoint http://localhost:8000/ \
--debug-connections \
--auto-provision \
--wallet-type indy \
--wallet-name Alice1 \
--wallet-key secret
```

Bugs:

1. No matching distributions can be found for the `indy-vdr~=0.3.3` and `ursa-bbs-signatures~=1.0.1` modules when installing the requirements. Commenting out these dependencies fix these issues but would this have further downstream affects and is there a better solution?

2. Using the 'fix' above the agent fails to start due to `aries_cloudagent.utils.classloader.ModuleLoadError: Unable to import module aries_cloudagent.indy.sdk.profile: No module named 'indy'`, however, I checked the requirements and `python3-indy` is already installed.

Any and all help is much appreciated thank you very much!

**Comment by WadeBarnes** [comment]
See if the workaround described here fixes your issues; https://github.com/hyperledger/aries-cloudagent-python/issues/2312

**Comment by finnformica** [comment]
Thank you, that has helped solved the first problem but the second bug still stands with the same error.

For anyone who may have the same issue I added this bit of code to the top of the `scripts/run_docker.sh` file:

```bash
# Set default platform to linux/amd64 when running on Arm based MAC since there are no arm based images available currently.
if [[ $OSTYPE == 'darwin'* ]]; then
  architecture=$(uname -m)
  if [[ "${architecture}" == 'arm'* ]] || [[ "${architecture}" == 'aarch'* ]]; then
    export DOCKER_DEFAULT_PLATFORM=linux/amd64
  fi
fi
```

**Comment by WadeBarnes** [comment]
The persistent errors may have to do with cached images.

You could try temporarily updating this line 
https://github.com/hyperledger/aries-cloudagent-python/blob/d1341f56c6867c23ccd7e17e0390af0b9d4cb66e/scripts/run_docker#L6
to
```
$CONTAINER_RUNTIME build --no-cache -t aries-cloudagent-run -f ../docker/Dockerfile.run .. || exit 1
```

To see if that helps.

**Comment by finnformica** [comment]
That still produces the same error unfortunately 😢

**Comment by WadeBarnes** [comment]
> That still produces the same error unfortunately 😢

The first or second error you were getting?  If the second ... Even after uncomment the dependencies you commented out?

**Comment by finnformica** [comment]
The first error was completely fixed by your patch in the von-network repo even after uncommenting the indy-vdr and ursa-bbs-signatures in requirements, the second error still persists with the indy module not being found.

**Comment by WadeBarnes** [comment]
I see the issue.  `python3-indy` is installed, but that's only a wrapper for the `indy-sdk` which does not look like it's installed by that particular image.  Switching to `--wallet-type askar` should fix that issue.  Askar storage is superior to Indy storage, and the indy-sdk is being deprecated in favor of Askar and other newer shared libraries.

**Comment by finnformica** [comment]
Thats fixed it thank you! Should I submit a PR to ACA-py with the ARM workaround you added to the von-network repo?

**Comment by WadeBarnes** [comment]
> Should I submit a PR to ACA-py with the ARM workaround you added to the von-network repo?

Please do.

**Comment by swcurran** [comment]
Thanks for the notes.  We need to remove any references to the `—wallet-type indy` from the repo and always use Askar.  I’ll create a task that we check through and update where ever needed.

I’ll close this one based on the PR and the new issue — which we will work on very soon.
