### ISSUE TITLE
Apply workaround to fix issues using the ACA-Py scripts on ARM based MACs

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/aries-cloudagent-python#2312]
Developers using ARM based MACs commonly run into issues running the ACA-Py demos (and other scripts).  The underlying reason is ACA-Py does not fully support the ARM architecture due to some of it's dependencies not supporting the ARM architecture.  This issue is being addresses here; https://github.com/hyperledger/aries-cloudagent-python/issues/2124.

The workaround is to tell docker to use amd64 emulation when running on an ARM based MAC.  This is done by setting `DOCKER_DEFAULT_PLATFORM=linux/amd64`.

A script to auto-detect ARM based MACs and set `DOCKER_DEFAULT_PLATFORM=linux/amd64` has been added to von-network, apply this workaround to the affected ACA-Py scripts.  https://github.com/bcgov/von-network/pull/272

**Comment by swcurran** [comment]
@amanji -- assigning this to you to close or apply a change as appropriate as related to #2124
