### ISSUE TITLE
Implement AnonCredsRevocation.handle_full_registry

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#2377]
See: https://github.com/hyperledger/aries-cloudagent-python/blob/anoncreds-rs/aries_cloudagent/anoncreds/revocation.py#L654-L656

The `handle_full_registry` method is currently stubbed out. This method should trigger rotating out the full registry, in similar fashion to what is now being done over here: https://github.com/hyperledger/aries-cloudagent-python/blob/2b0e27abb598cadc6453202aec593512c29abf3f/aries_cloudagent/revocation/indy.py#L111-L113

**Comment by usingtechnology** [comment]
See PR #2523 .

There is an off by 1 issue (think there always was?) - it works but feels bad. We leave an empty slot per registry.
