### ISSUE TITLE
Create new registry in AnonCredsRevocation.get_or_create_active_registry if necessary

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#2378]
See: https://github.com/hyperledger/aries-cloudagent-python/blob/anoncreds-rs/aries_cloudagent/anoncreds/revocation.py#L670-L672

This method should trigger the creation of a new registry if one is not available.

Reference: https://github.com/hyperledger/aries-cloudagent-python/blob/2b0e27abb598cadc6453202aec593512c29abf3f/aries_cloudagent/revocation/indy.py#L224-L251

As an aside, I'm not sure this will ever actually trigger the creation of a new registry when using automated setup. The registry creation should be triggered by the `handle_full_registry` method.

**Comment by swcurran** [comment]
If this is part of the controller-handled revocation, this can be left off, as that will not be supported.
