### ISSUE TITLE
Update/adapt Present Proof v1 to use anoncreds interface

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#2382]
So far, only the PPv2 implementation has been updated to use the new anoncreds interface. We should update the PPv1 implementation as well.

**Comment by dbluhm** [comment]
The Present Proof protocol implementations do a better job of sharing code than the Issue Credential protocol implementations do. Still, this diff may be helpful: https://github.com/hyperledger/aries-cloudagent-python/pull/2276/files#diff-53165217f650ab8ddebd7bf96b175abc73bed5f8189ec1655aeae241ffc0b33a

(Jump to `aries_cloudagent/protocols/present_proof/v2_0/formats/indy/handler.py` if the link didn't do it automatically for you)

**Comment by ianco** [comment]
I don't think we should update the v10 protocols, and we may want to disable these protocols when running with askar-anoncreds.

**Comment by ianco** [comment]
I don't think we should update the v10 protocols, and we may want to disable these protocols when running with askar-anoncreds.
