### ISSUE TITLE
Upgrade step for migrating from IssuerRevRegRecord

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#2385]
Related to #2384; we need an upgrade step to convert old `IssuerRevRegRecords` into the new records managed by `AnonCredsRevocation`.

**Comment by dbluhm** [comment]
Can we skip registries marked as decommissioned?

**Comment by jamshale** [comment]
This was completed via anoncreds upgrade endpoint. Decommissioned registries were copied over.
