### ISSUE TITLE
Upgrade step for migrating from old created schema and cred def records

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#2386]
Records for created schemas and cred defs were previously being created in the `routes.py` for the respective objects. These records are now managed by `AnonCredsIssuer` directly to enable it to manage artifacts pending publication. The structure is very similar to the initial records but the old still need to be migrated to the new.

**Comment by jamshale** [comment]
This was completed via the anoncreds upgrade endpoint.
