### ISSUE TITLE
Upgrade step for indy-credx wallet entries

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#2389]
Records like private keys for cred defs and revocation registries are currently managed directly by the Indy CredX module in a very similar manner to how `AnonCredsIssuer` and `AnonCredsRevocation` manages their private values. The Indy CredX models can/should be migrated to the generic AnonCreds equivalent records.

**Comment by jamshale** [comment]
This was completed via the anoncreds upgrade endpoint.
