### ISSUE TITLE
Endorser support in Indy registries

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#2390]
Extend the implementation in ACA-Py to support AnonCreds RS by adding Endorser support.

@dbluhm created the following [design document](https://hackmd.io/@dbluhm/acapy-endorser-registry) about this.

A meeting was held about the design and the recording is available for anyone that is interested.

**Comment by swcurran** [comment]
By registries -- are you meaning revocation registries, or Indy transactions in general?

**Comment by dbluhm** [comment]
An "AnonCreds Registry" is what I mean; the thing that registers and resolves schemas, cred defs, revocation registries, revocation lists.
