### ISSUE TITLE
Can't solve requirements*.txt for demo with 0.9.0

### ISSUE THREAD

**Issue by jkrupicka** [hyperledger/aries-cloudagent-python#2396]
Running `LEDGER_URL=http://test.bcovrin.vonx.io ./run_demo faber` in demo/ works perfectly fine with 0.8.2, but results in `ERROR: failed to solve: process "/bin/sh -c pip3 install --no-cache-dir \t-r requirements.txt \t-r requirements.askar.txt \t-r requirements.bbs.txt \t-r requirements.dev.txt" did not complete successfully: exit code: 1` with 0.9.0. This is in Dockerfile.demo:15. Is anyone else able to reproduce this error?

**Comment by swcurran** [comment]
I ran it on my system (Ubuntu) and worked fine. What are you running on?  Can you share the log from running the command so we can see what the error is?

**Comment by jkrupicka** [comment]
I apologize. I'm not sure what changed, but it's now working for me. I'm also on Ubuntu. Closing now.
