### ISSUE TITLE
Replace `flake8` / `pytest-flake8` with `ruff` / `pytest-ruff`

### ISSUE THREAD

**Issue by ff137** [hyperledger/aries-cloudagent-python#2400]
Flake8 is being surpassed by an extremely fast linter: https://github.com/astral-sh/ruff. 
See the readme for speed comparison and testimonials.

This is primarily suggested because `pytest-flake8` is no longer maintained, binding aca-py to flake v4 instead of the latest v6.
To shed technical debt, I propose replacing the `pytest-flake8` dependency (used in PR tests) with [`pytest-ruff`](https://github.com/businho/pytest-ruff)

**Comment by dbluhm** [comment]
I am generally in favor of a change. I've heard of `ruff` before but this is the first time I've looked closer; I notice that the version is 0.0.282. That's the only thing that gives me pause; however, it seems to be widely used and well supported. I think I'm in favor :slightly_smiling_face:
