### ISSUE TITLE
Build failed: Could not find a version that satisfies the requirement marshmallow~=3.19.0

### ISSUE THREAD

**Issue by dolly1997** [hyperledger/aries-cloudagent-python#2405]
Hi @swcurran @reflectivedevelopment @dbluhm 
I was trying to build my dockerfile of ACA-py agent with 0.9.0 version .I provided the Label wallet-type askar in my script file as well.when i tried to build the image it is throwing me an error of marshmallow.please do let me know if I am missing something.

I am attaching screenshot of the error log.

<img width="797" alt="error1" src="https://github.com/hyperledger/aries-cloudagent-python/assets/40203065/b91dc0ab-2a1a-4cd2-86d3-0b479f70e819">

**Comment by dbluhm** [comment]
I see this kind of error from my colleagues who have M1 macs or when there's a python version mismatch I think.

If you're on M1, you'll have to explicitly set the platform to be amd64 since ARM builds aren't supported yet.

With 0.9.0, the minimum required python version was updated to Python 3.9. If your image is still using a version less than 3.9, I think this can result in errors like this.

**Comment by WadeBarnes** [comment]
A follow-tp to @dbluhm's comment.  If you are on an Arm base Mac try setting `export DOCKER_DEFAULT_PLATFORM=linux/amd64` before you run the build.

**Comment by dolly1997** [comment]
@dbluhm @WadeBarnes thankyou for the feedback. I would like to inform you i am not using Mac machine .As we are moving to askar in 0.9.0 version. i dont know exactly what configuration need to be configured befor that.
this is my dockerfile :
<img width="553" alt="image" src="https://github.com/hyperledger/aries-cloudagent-python/assets/40203065/5020bfcf-fbd6-4ccb-9502-6949f8cd225d">

**Comment by dbluhm** [comment]
I would recommend using the official images built by the project: https://github.com/hyperledger/aries-cloudagent-python/pkgs/container/aries-cloudagent-python/112246792?tag=py3.9-0.9.0

**Comment by WadeBarnes** [comment]
I recommend the same.

**Comment by dolly1997** [comment]
Thanks a lot @WadeBarnes @dbluhm 
It works for me. able to build the image and my ACA-py agent is up and running with latest version(0.9.0)
