### ISSUE TITLE
Apply CL-Signature changes that were applied in the main branch to the anoncreds-rs branch

### ISSUE THREAD

**Issue by usingtechnology** [hyperledger/aries-cloudagent-python#2411]
Change in scope for this task. It is now just to apply the changes from #2302 into the anoncreds-rs branch. The changes include new features/improvements in CL Signatures, such as not needed the tails file for issuing and revoking credentials. That will reduce the need for keeping local copies of tails files after creation/publishing.

We'll add plan/set of tasks for merging the anoncreds-rs branch into main vs. the other way round.  Or we will do it the other way round. TBD.

Old scope:

Sub-task for #2297.
`anoncreds-rs` branch is very out of date with `main`. We need to get this synced before taking on more new code.

Will need to coordinate work between @dbluhm and @usingtechnology  - the work that @andrewwhitehead did around credx impacts changes to the Base ledger and will be the trickiest logic to merge in.

**Comment by usingtechnology** [comment]
Just did a simple merge `main` onto `anoncreds-rs` to look at impact. Most merge conflicts are straightforward (ex. library version updates, text in readmes). There are a few areas that will require some deep knowledge about why code as changed...

- askar/profile
- core/conductor
- ledger/base
- revocation/manager
- revocation/models/issuer_cred_rev_record

All in all I don't think it's a significant amount of work, but certainly not an automatic effort.

**Comment by swcurran** [comment]
This has been done in the work @ianco has been doing.
