### ISSUE TITLE
Version upgrade required for aiohttp

### ISSUE THREAD

**Issue by kukgini** [hyperledger/aries-cloudagent-python#2424]
My security team suggested version upgrade on aiohttp over then 3.8.5
see details: https://security.snyk.io/vuln/SNYK-PYTHON-AIOHTTP-5798483

**Comment by swcurran** [comment]
Seems that ACA-Py is not impacted by the issue:

`This vulnerability only affects users of aiohttp as an HTTP server (i.e. aiohttp.Application). Users are not affected by this vulnerability if they use aiohttp as an HTTP client library (i.e. aiohttp.ClientSession).`

I searched the codebase and ACA-Py only uses the ClientSession.

That said, we’re pretty good at staying on top of dependecy updates, so this will be updated relatively soon, I’m sure.

Happy to take a PR!  :-)

**Comment by kukgini** [comment]
@swcurran I think Inbound Transport and Admin API are made using aiohttp server. Although aca-py don't use aiohttp.Application directly, I can see that server.py and routes.py use web.Application . The report says a server program that use the llhttp parser to parse http headers will be exposed on HTTP Request Smuggling issues.

**Comment by swcurran** [comment]
Yup — I saw that. I thought the report was very strange as it mentioned that the parser uses Node — not something expected in a Python dependency.  Caught me by surprise.

Also looked up what Request Smuggling is (https://portswigger.net/web-security/request-smuggling) and likewise it seems very unlikely to be an issue in ACA-Py, as the Admin API is not end user accessible.

That said - we will upgrade the version dependency. Just not sure of the priority.  We have not received a dependabot flag or PR about this.

**Comment by kukgini** [comment]
There is no need to rush, it is natural that it is fully reviewed and processed by priority. However, it is curious that aiohttp has not been updated even for the micro version for quite some time.

However, from the point of view of the recent security trend, Zero Trust Architecture, it is necessary to be somewhat guarded against about boundary-based security awareness. Therefore, it is better to consider that the Admin API is safe because it is verified every time by the auth token rather than safe because it is an internal communication. At this point, HTTP Request Smuggling can be a problem.

**Comment by swcurran** [comment]
Agree on the zero trust architecture comment. I was thinking of that as I wrote the previous comment :-).

**Comment by swcurran** [comment]
We're at 3.9.2 now, so closing this.
