### ISSUE TITLE
Remove old route protocol

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#2430]
The route protocol was a precursor to the coordinate mediation protocol. The `routing/1.0` protocol itself will retain the `forward` message and its handler. However, the old `route-query-request` and response and `route-update-request` and response have been out of use for at least a couple of years. Before that, I don't think it had ever achieved common use to begin with. I think it's time to remove the handlers and any other references from the codebase.

**Comment by swcurran** [comment]
Sounds right to me.
