### ISSUE TITLE
Update ACA-Py AATH Test Agent to Askar

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2460]
The AATH tests are still using Indy SDK. Update the AATH Test Agent to use Askar and the shared components.

**Comment by anajembaedwin** [comment]
I am happy to work on this issue.

**Comment by swcurran** [comment]
Hi @anajembaedwin — feel free. It should be a straight forward one.  However, the ACA-Py tests are generally not running these days because of a change in ACA-Py, and that is going to make it difficult for you — most tests are going to fail.  We still have to figure out how to deal with that problem.

**Comment by usingtechnology** [comment]
Including this in [AATH PR 727](https://github.com/hyperledger/aries-agent-test-harness/pull/727) with the test fixes.
