### ISSUE TITLE
Ledger writes not happening when an Endorser connection exists and issuer upgraded to 0.10.1

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/aries-cloudagent-python#2474]
When calling `/revocation/active-registry/{cred_def_id}/rotate` on existing, active RegRegistries, the existing registries are decommissioned but the new RevRegistries are not getting created.

Scenario and details can be found here; https://github.com/bcgov/DITP-DevOps/issues/109

**Comment by swcurran** [comment]
In the instance where this was discovered, we are finding that all attempts to create a RevReg are silently failing — the ledger transaction is not being written. As such, this may not be an issue with /rotate at all, and may just be an issue with this deployment.  It had previously been able to create RevRegDefs before as needed...

**Comment by WadeBarnes** [comment]
Based on the latest findings in the linked ticket, and the fact that everything was working fine before the upgrade, I'm skeptical this is just and issue with the deployment.

**Comment by WadeBarnes** [comment]
Manually creating the RevRegDefs through the admin interface fails as well.

**Comment by swcurran** [comment]
Issue is specifically #2475 , and should be resolved by #2476 .

**Comment by WadeBarnes** [comment]
The updates contained in the [0.10.2-rc0](https://github.com/hyperledger/aries-cloudagent-python/releases/tag/0.10.2-rc0) release fixed the reported issue and I was able to repair the agent's RevReg state.  See the linked issue for details.
