### ISSUE TITLE
If a connection is created without any recipient_keys messages will be sent in plaintext 

### ISSUE THREAD

**Issue by Jsyro** [hyperledger/aries-cloudagent-python#2478]
A connection can be created without recipient_keys, and when it is, messages are sent to that service_endpoint in plain text. 

acapy should probably log an error or raise an exception when messages are being sent in plain text, or possibly on connection creation if no recipient_keys are provided.

**Comment by swcurran** [comment]
Closing as stale -- reopen if needed.
