### ISSUE TITLE
chore: Prepare ACA-Py Patch Release 0.10.2

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2479]
We need to get a couple of fixes into a release - PR #2476 and Issue #2477.  We'll do an rc2 as soon as the PRs are ready to go.  The patch release will be branched off of 0.10.1 and will only have these fixes and release PRs.  The PRs will of course also go onto the main branch for subsequent releases.

**Comment by dbluhm** [comment]
Branch: https://github.com/hyperledger/aries-cloudagent-python/tree/0.10.2

It's got the changes from #2476 already so just waiting on #2477.

**Comment by WadeBarnes** [comment]
Testing of the [0.10.2-rc0](https://github.com/hyperledger/aries-cloudagent-python/releases/tag/0.10.2-rc0) has been successful.  The changes address the two issues I reported; https://github.com/hyperledger/aries-cloudagent-python/issues/2477, https://github.com/hyperledger/aries-cloudagent-python/issues/2474

**Comment by WadeBarnes** [comment]
An issue related to the [0.10.2-rc0](https://github.com/hyperledger/aries-cloudagent-python/releases/tag/0.10.2-rc0) has popped up.  Details start here; https://github.com/bcgov/DITP-DevOps/issues/109#issuecomment-1712033422.  If this does turn out to be another ACA-Py issue we'll created a ticket, while we do investigation we'll track the issue outside ACA-Py.

**Comment by WadeBarnes** [comment]
> An issue related to the [0.10.2-rc0](https://github.com/hyperledger/aries-cloudagent-python/releases/tag/0.10.2-rc0) has popped up. Details start here; [bcgov/DITP-DevOps#109 (comment)](https://github.com/bcgov/DITP-DevOps/issues/109#issuecomment-1712033422). If this does turn out to be another ACA-Py issue we'll create a ticket, while we do investigation we'll track the issue outside ACA-Py.

The reported issue has been resolved.  Technically it's not an issue with ACA-Py, but it is an issue with the documented process for manually creating and **fully** initializing a new RevReg.  PR for the update to the docs is incoming.

**Comment by WadeBarnes** [comment]
Testing of the RC image is going well.  IDIM has some final tests to perform using the repaired `sit` instance.  Once testing is complete there, I'm confident we can complete the release process for `0.10.2`.

**Comment by WadeBarnes** [comment]
@swcurran, IDIM has confirmed their testing has been successful.  Please proceed with the official `0.10.2` release.

**Comment by WadeBarnes** [comment]
Or would the issues discovered here, https://github.com/hyperledger/aries-cloudagent-python/issues/2497, delay this release?

cc @swcurran, @dbluhm

**Comment by swcurran** [comment]
Yes…we’re waiting on an assessment of that one.
