### ISSUE TITLE
Bump Shared Components versions in ACA-Py

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2505]
We've had recent releases made to the shared components that are used in ACA-Py main branch, and we should update the dependencies for those libraries in ACA-Py as appropriate.

@andrewwhitehead -- what of these libraries can be simply updated in the requirements, and which need corresponding code changes in ACA-Py as part of the update?

* CredX / indy-shared-rs [v1.0.3](https://github.com/hyperledger/indy-shared-rs/releases/tag/v1.0.3).
* Indy VDR [v0.4.0](https://github.com/hyperledger/indy-vdr/releases/tag/v0.4.0)
* Aries Askar 0.3.0 pending -- [PR to update version for tagging](https://github.com/hyperledger/aries-askar/pull/179)

I'll put in a separate issue for updating the anoncreds-rs branch with the latest version of that.

**Comment by TimoGlastra** [comment]
Also tagged Askar 0.3.0-dev.1 release: https://github.com/hyperledger/aries-askar/releases/tag/v0.3.0-dev.1

**Comment by andrewwhitehead** [comment]
Indy-credx updates are already being picked up by ACA-Py. Indy-vdr 0.4 and Askar 0.3 will require an update to the requirements, but I've already run the unit tests against them and didn't see any issues. We could create a draft PR to run the integration tests against the dev release of Askar.

**Comment by swcurran** [comment]
Great.  Do we have an ETA (and “definition of done”) for the Indy VDR and/or the Askar final releases?  Is it good practice to update to the Dev releases now or should we hold off?

**Comment by swcurran** [comment]
Completed. #2520
