### ISSUE TITLE
Problem Report Being Sent Before Thread Established

### ISSUE THREAD

**Issue by Ennovate-com** [hyperledger/aries-cloudagent-python#2512]
In `aries_cloudagent/protocols/issue_credential/v2_0/routes.py`
in the methods which initiate a credential exchange, namely:
   `credential_exchange_send_proposal` -- line 838
   `credential_exchange_send_free_offer` -- line 1045
   `credential_exchange_send_free_request` -- line 1255

There is a call to `report_problem` at the line numbers mentioned above. However, while there will be an existing thread on both sides of the connection for "bound" requests, allowing the problem report to be delivered successfully, for these requests above, which initiate a new credential exchange, the credential exchange records have not yet been established on the partner side. Therefore, the `report_problem` call results in the partner raising a `StorageNotFound` error when it attempts to locate the nonexistent credential exchange thread. For example:

```aries_cloudagent.storage.error.StorageNotFoundError: V20CredExRecord record not found for {'thread_id': 'b7c261f7-7a36-4413-bdb9-7cd93af3f50c'}, {'connection_id': 'ba0d694c-738d-4850-97cb-785a2a597562'}```

If there's no case where the partner thread would already exist for these methods which begin the credential exchange, then the attempt to deliver the problem report to a non-existent thread should be avoided. If that makes sense, simply deleting the `report_problem` calls in those three methods would resolve this issue.

One fairly simple way to test this is to try and create a credential exchange with an empty credential subject.

**Comment by swcurran** [comment]
Thanks for the report.  I agree with your analysis and solution.  Great if you could raise a PR for this.

**Comment by swcurran** [comment]
This was reported in #1730 as well.

**Comment by Ennovate-com** [comment]
@swcurran PR #2519 created. Thanks for pointing out the earlier report.

**Comment by Ennovate-com** [comment]
Fixed with Merge of PR #2519. Thanks!
