### ISSUE TITLE
Seeking Assistance regarding integrate custom DID method

### ISSUE THREAD

**Issue by Sshovon** [hyperledger/aries-cloudagent-python#2513]
I'm looking for help with how to successfully integrate custom DID method into aca-py project. Currently, I'm using a trial-and-error approach to incorporate our implemented DID method into the existing project. Can someone provide a structured approach to accomplish this task effectively? 

**What I've Accomplished So Far:**
- Integrated the resolver for resolving our custom DID.
- Started the demo agent with our custom DID instead of did:sov.
- Stored this custom DID in our ledger.
- Created a VC schema and credential definition using the custom DID and stored it in our ledger.

**What I Aim to Achieve:**
- To fully implement the SSI flow using our custom DID, including VC issuance, proof requests, and more.

Is there a more structured and efficient approach to achieving this?

**Comment by swcurran** [comment]
Are you trying to just integrate the DID Method (for getting/resolving DIDs) or are you also trying to use AnonCreds?  Sounds like you are trying to use AnonCreds as well.

Assuming that, we are in the midst of merging AnonCreds RS (implementation) into ACA-Py to make it easier to use any ledger/storage method. That will be a big help to you, but not sure we're far enough along.

**Comment by Sshovon** [comment]
Thank you @swcurran, for the response. I am trying to integrate DID method and AnonCred. 
To work with anoncred-rs in aca-py is there any specific documentation to streamline the process?

**Comment by Sshovon** [comment]
Also please let me know if there is any structured way to integrate a new DID method.

**Comment by dixadholakiya** [comment]
hey I am just working on same,integrate customised DID method to ACA Py agent.Did you just replace code file or any other processes required?

**Comment by Sshovon** [comment]
Hello @dixadholakiya , I couldn't achieve the objective in aca-py. But I have achieved the same using credo-ts agents.
