### ISSUE TITLE
Create a "v0.10.3" branch, cherry pick 2486 into it and prepare release 0.10.3

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2518]
Please cherry pick the #2486 PR into a new branch "v0.10.3" (note the "v" -- it is necessary), and then lets get it released.

@WadeBarnes -- could you do the cherry picking?  I think you have the most GitHub foo...

**Comment by swcurran** [comment]
@WadeBarnes -- please reassign (perhaps @shaangill025 or @dbluhm ) if you aren't the right person.

Once the branch is ready, please assign to me to complete the release.

**Comment by WadeBarnes** [comment]
Done, back to you @swcurran

**Comment by WadeBarnes** [comment]
Prerelease image created; [ghcr.io/hyperledger/aries-cloudagent-python:py3.9-indy-1.16.0-0.10.3-pre0](https://github.com/hyperledger/aries-cloudagent-python/pkgs/container/aries-cloudagent-python/132134787?tag=py3.9-indy-1.16.0-0.10.3-pre0)

**Comment by WadeBarnes** [comment]
I've identified some RegRegs in the LSBC `test` environment I can use for testing the pre-release.

**Comment by WadeBarnes** [comment]
Testing with the `py3.9-indy-1.16.0-0.10.3-pre0` image was successful.  Details here; https://github.com/bcgov/DITP-DevOps/issues/83#issuecomment-1739520879

@swcurran, you may proceed with the official `0.10.3` release.
