### ISSUE TITLE
Error connecting Issuer with Endorser service

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/aries-cloudagent-python#2528]
Issuer is ACA-Py `v0.10.3` and Endorser is ACA-Py `v1.0.0-rc0`.  Issuer and endorser are setup the same as others that are working (granted connection was made a while ago).  Both Issuer and Endorser and are rooted on the same ledger (Sovrin TestNet).

Connections are using public DIDs.  The connection request is sent from the Issuer.  Endorser encounters the following error and no connection request is registered.
```
2023-10-03 22:37:58,444 aries_cloudagent.connections.base_manager WARNING No corresponding DID found for sender verkey: FyPgD34crHTb24ec65x2bcQCaNzFra1tM5wtN2oYJCoo
2023-10-03 22:37:58,465 aries_cloudagent.messaging.base_handler ERROR Error receiving RFC 23 connection request
Traceback (most recent call last):
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/didexchange/v1_0/handlers/request_handler.py", line 44, in handle
else context.message_receipt.recipient_verkey
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/protocols/didexchange/v1_0/manager.py", line 453, in receive_request
"DID Doc attachment missing or has no data: "
aries_cloudagent.protocols.didexchange.v1_0.manager.DIDXManagerError: DID Doc attachment missing or has no data: cannot connect to public DID
```

Issuer connection is left in the following state:
```
{
  "results": [
    {
      "state": "request",
      "created_at": "2023-10-03T22:37:58.312491Z",
      "updated_at": "2023-10-03T22:37:58.385715Z",
      "connection_id": "3fc05cfb-df83-479e-8417-06398caec6ae",
      "my_did": "UUHA3oknprvKrpa7a6sncK",
      "their_did": "EZpKx6nT56Hv83JmNz7ik8",
      "their_role": "inviter",
      "connection_protocol": "didexchange/1.0",
      "rfc23_state": "request-sent",
      "request_id": "82d9202f-1b3b-45b6-ac3a-9213c05d8079",
      "routing_state": "none",
      "accept": "manual",
      "invitation_mode": "once",
      "alias": "Endorser",
      "their_public_did": "EZpKx6nT56Hv83JmNz7ik8"
    }
  ]
}
```

Hoping this is something recognizable and I'm just missing something.

**Comment by swcurran** [comment]
Is endorser set to auto-accept?  Looks like the response is not coming back from the Issuer.

**Comment by WadeBarnes** [comment]
No, it's expected to be manually accepted.  But it's not even showing up in the list of connections to be accepted.

**Comment by WadeBarnes** [comment]
Debug logs of the Issuer sending a connection request to the endorser:
[endorser.log](https://github.com/hyperledger/aries-cloudagent-python/files/12797691/endorser.log)
[Issuer.log](https://github.com/hyperledger/aries-cloudagent-python/files/12797692/Issuer.log)

**Comment by WadeBarnes** [comment]
@dbluhm, Is this an issue with the format of the DID being sent by the Issuer in the connection request?

**Comment by WadeBarnes** [comment]
I upgraded the endorser service to `0.10.3` and I'm still running into the same errors on the endorser sidde.
```
2023-10-04 13:10:31,328 aries_cloudagent.connections.base_manager WARNING No corresponding DID found for sender verkey: FyPgD34crHTb24ec65x2bcQCaNzFra1tM5wtN2oYJCoo
2023-10-04 13:10:32,795 aries_cloudagent.messaging.base_handler ERROR Error receiving RFC 23 connection request
Traceback (most recent call last):
File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/protocols/didexchange/v1_0/handlers/request_handler.py", line 40, in handle
conn_rec = await mgr.receive_request(
File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/protocols/didexchange/v1_0/manager.py", line 541, in receive_request
raise DIDXManagerError(
aries_cloudagent.protocols.didexchange.v1_0.manager.DIDXManagerError: Unsolicited connection requests to public DID is not enabled
```

**Comment by WadeBarnes** [comment]
I've upgraded the endorser to `0.10.3` and now getting this message, which is pointing in the right direction at least:
```
2023-10-04 13:10:31,328 aries_cloudagent.connections.base_manager WARNING No corresponding DID found for sender verkey: FyPgD34crHTb24ec65x2bcQCaNzFra1tM5wtN2oYJCoo
2023-10-04 13:10:32,795 aries_cloudagent.messaging.base_handler ERROR Error receiving RFC 23 connection request
Traceback (most recent call last):
File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/protocols/didexchange/v1_0/handlers/request_handler.py", line 40, in handle
conn_rec = await mgr.receive_request(
File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/protocols/didexchange/v1_0/manager.py", line 541, in receive_request
raise DIDXManagerError(
aries_cloudagent.protocols.didexchange.v1_0.manager.DIDXManagerError: Unsolicited connection requests to public DID is not enabled
```

**Comment by dbluhm** [comment]
With 0.10.1, the public DID connection behavior changed. The newer version of ACA-Py is not including the DID Doc attachment in the request/response while the older version is strictly expecting it to be present. I think this is the cause of the first error you posted.

I think this raises a question which I probably should have considered with the changes: how backwards compatible do we want to be with changes like those introduced in 0.10.1? 0.10.1 was perhaps our most forward-looking release in recent memory (code for "I broke a lot of stuff"). There will be more changes like this as we continue to push forward to OOB/DID Exchange updates to align with the RFCs and to DIDComm v2 and beyond. I think reasonable effort should be taken, of course, but we will have to draw the line somewhere. Would also be great to introduce automated testing against the most recent release and all releases up until that line.

> Unsolicited connection requests to public DID is not enabled

For this one, `--requests-through-public-did` is required. Though, if the inviter explicitly created an invitation and the request was received through that, I don't believe we should hit this path.

**Comment by WadeBarnes** [comment]
I enabled `ACAPY_REQUESTS_THROUGH_PUBLIC_DID` on the endorser, and I'm now able to make the connection between the issuer and endorser.

**Comment by swcurran** [comment]
Happy to add more to the changelog if that would be helpful.  Perhaps we need a document “upgrading.md” that tracks things we discover post-promotion.

Don’t know what to say about 1.0.0-rc0. It is now so old that, not sure we should worry.  It is a mess that we ever created a 1.0.0 line of releases…

**Comment by WadeBarnes** [comment]
Summary:
- Issuer was using latest version of ACA-Py, 0.10.3.  Endorser was using an older version of ACA-Py, 1.0.0-rc0; the first release with the Endorser protocols.
- The two versions are not compatible.
- After upgrading the Endorser it's settings needed to be adjusted, as expected, to accept unsolicited connection requests.

**Comment by WadeBarnes** [comment]
@swcurran, @dbluhm, One observation on the behavior of the the connection request when it was failing (being rejected).  The fact that the connection request was rejected didn't seem to make its way back to the Issuer (in this case), so the issuer had a pending connection that was essentially orphaned.  I would expect request failure would be communicated so the connection record could be updated/deleted to indicate it was rejected.  Thoughts?  Worth a ticket?

**Comment by swcurran** [comment]
Agreed — there should have been a Problem Report sent.

**Comment by WadeBarnes** [comment]
Resolved with upgrade and configuration update.

**Comment by rahulbatham767** [comment]
i'm having issue in manually accepting invitation, i don't want auto accept how to fix it.

**Comment by dbluhm** [comment]
@rahulbatham767 please open a new issue and include details about what is failing as well as logs (log level debug would be ideal)
