### ISSUE TITLE
Performance testing for acapy

### ISSUE THREAD

**Issue by nahid-g** [hyperledger/aries-cloudagent-python#2532]
What is the most effective way for conducting performance testing on an acapy instance or an application built on acapy? Is there any framework? We are trying to calculate latency and throughput of transactions.

**Comment by swcurran** [comment]
Ther is work currently happening in ACA-Py for implementing a load test generator. This is a Code With Us opportunity funded by BC Gov (details [here](https://marketplace.digital.gov.bc.ca/opportunities/code-with-us/51d7c289-51a8-4307-939c-5a4271c7b2b6)) and awarded to Indicio.  We’ll be talking about the design tomorrow (Tuesday) on the [ACA-Pug Meeting]() at 8:00 Pacific / 17:00 Central Europe.  With that capability, you will be able to run the load test generator as a set of holders (configurable how many, how many activities), hitting various “systems under test” Issuers and Verifiers, possibly with a mediator in front of the holders.

Another data point.  BC recently reloaded the “dev” version of [OrgBook BC](https://orgbook.gov.bc.ca) that holds about 2.5M credentials on start up.  The implementation is an ACA-PY issuer issuing all of the credentials to a single ACA_Py holder (a so-called “community wallet”). During the loading, without much tuning, the systems had a sustained rate of about 30 issuances/second.

**Comment by swcurran** [comment]
For guidance on performance testing ACA-Py, please look at [Aries Akrida](https://github.com/hyperledger/aries-akrida), which provides capabilities for such testing.  BC Gov will be using Aries Adrida in the next short while to understand the performance characteristics of ACA-Py.
