### ISSUE TITLE
Per Tenant setting: requests-through-public-did

### ISSUE THREAD

**Issue by thiagoromanos** [hyperledger/aries-cloudagent-python#2572]
Since I can define per tenant the setting `public_invites`, it would be great that I could also set per tenant the `requests-through-public-did` (in a case where I have a tenant that wants to receive those public did requests, but all other tenants don't).

**Comment by swcurran** [comment]
Thanks — this is correct. @esune — is there a pattern/approach for making configuration parameters tenant-specific vs. global?

**Comment by esune** [comment]
We have implemented an endpoint in a Traction plugin to facilitate setting these at runtime: see [this](https://github.com/bcgov/traction/blob/e0648f1c6210f5d29688e0427a5f8208c0a4d4bc/plugins/traction_innkeeper/traction_innkeeper/v1_0/tenant/routes.py#L363). I believe that anything listed in [this map](https://github.com/shaangill025/aries-cloudagent-python/blob/d705ca2fe9132fc5bdc07e427e10f74201bbfac2/aries_cloudagent/multitenant/admin/routes.py#L45-L62) is supported: we started with a subset of all the options that were available as there are several and we were not sure whether this would be useful for us only or others. I think if there are other flags that would be good to have set at a tenant level they just need to be added to that list.

c.c.: @shaangill025 for more insight.

**Comment by thiagoromanos** [comment]
> We have implemented an endpoint in a Traction plugin to facilitate setting these at runtime: see [this](https://github.com/bcgov/traction/blob/e0648f1c6210f5d29688e0427a5f8208c0a4d4bc/plugins/traction_innkeeper/traction_innkeeper/v1_0/tenant/routes.py#L363). I believe that anything listed in [this map](https://github.com/shaangill025/aries-cloudagent-python/blob/d705ca2fe9132fc5bdc07e427e10f74201bbfac2/aries_cloudagent/multitenant/admin/routes.py#L45-L62) is supported: we started with a subset of all the options that were available as there are several and we were not sure whether this would be useful for us only or others. I think if there are other flags that would be good to have set at a tenant level they just need to be added to that list.
> 
> c.c.: @shaangill025 for more insight.

@esune , is there a plan to add this `requests-through-public-did` flag to that per-tenant list? Don't think that would be a breaking change to aca-py, since the global flag is there since 0.9.0.

**Comment by esune** [comment]
> 
> @esune , is there a plan to add this `requests-through-public-did` flag to that per-tenant list? Don't think that would be a breaking change to aca-py, since the global flag is there since 0.9.0.

Looping-in @swcurran and @dbluhm for additional opinions. I don't think it is planned, but I don;t see an issue in having that setting be part of the per-tenant customizations.
@thiagoromanos if you have bandwith a PR is always welcome 😉

**Comment by swcurran** [comment]
Agree.  I’m hoping it is well documented how to make a setting a per tenant setting so that we can easily add new ones that make sense.  Agree that this is one.
