### ISSUE TITLE
ACA-Py Version has changed format from the last RC

### ISSUE THREAD

**Issue by nodlesh** [hyperledger/aries-cloudagent-python#2579]
I believe we've changed the format of the acapy version in the latest rc. I'm building agents from ACA-Py main every night in Aries Agent Test Harness and the version from `./bin/aca-py --version` is combing back as `0.11.0rc1` instead of the historical and expected `0.11.0-rc1`. There is some processing of the version in the AATH acapy backchannel that is used for version comparison that is failing because of this.
This issue started in the BC Wallet Test Pipeline on the evening of Oct 30. 

It is also likely that the `admin_url/status` api returns the illformed version format.

**Comment by swcurran** [comment]
@esune — getting someone looking at this sooner than later would be a good thing.

**Comment by esune** [comment]
It is looking like we are going to keep the current behaviour, as it follows the official PEP 440 rules.

@nodlesh I think the best course of action would be to update the handling in AATH to recognize the updated versioning scheme.

**Comment by swcurran** [comment]
There is an AATH issue created to deal with this, and @nodlesh is updating AATH accordingly.

From now on, in the tags, releases, etc. we’ll leave off the “-“ entirely.
