### ISSUE TITLE
List of commercial products based on ACA-Py?

### ISSUE THREAD

**Issue by adrian-idc** [hyperledger/aries-cloudagent-python#2586]
Hello, first and foremost I want to say thank you to the community for doing such an amazing job with the ACA-Py agent. 

At [ID Crypt](https://www.idcrypt.global/) we are building a decentralized digital identity platform and ACA-Py is a fundamental part of it. We have recently released a community edition agent which is available at the Azure marketplace and allows users get an ACA-Py agent up and running, in Azure, in just a few minutes. The product is available [here](https://azuremarketplace.microsoft.com/es-es/marketplace/apps/idcryptgloballimited1599811331642.idcrypt-global-cloud-agent?tab=PlansAndPrice) if people want to poke around.

We were interested to know if there's a space in the ACA-Py docs, or somewhere else, where commercial products based on ACA-Py are listed. And If such space doesn't exist now, we were wondering if this is something the community would be interested on.

Thank you!

**Comment by swcurran** [comment]
Love to have that.  I suggest that you look at https://aca-py.org and decide where would the best place to put that.  Once you decide that, I can let you know where to do a documentation PR to this repo and trigger it appearing on that website.  Then it will be in both the ACA-Py repo, and on that website.  Make sense?

**Comment by swcurran** [comment]
As noted -- PRs are welcome and any provided documentation will be pushed. Closing this issue.
