### ISSUE TITLE
Add support for connection-less problem reports for presentations

### ISSUE THREAD

**Issue by esune** [hyperledger/aries-cloudagent-python#2597]
When receiving a problem report on a connection-less proof request, ACA-Py considers it unsupported and raises an exception (see [here](https://github.com/hyperledger/aries-cloudagent-python/blob/e13339650932f7b31f036366fdaa6e179dd760d1/aries_cloudagent/protocols/present_proof/v1_0/handlers/presentation_problem_report_handler.py#L33-L36).
This seems incorrect, and prevents the correct handling of rejected proof-requests (the verifier would not be able to know that a proof was rejected, and why).

Handling of the problem report should likely update the exchange record to "abort" it, and emit an event/webhook with relevant data for a controller to be able to reconcile it with the outgoing request.

**Comment by andrewwhitehead** [comment]
Comparing `receive_presentation` to `receive_problem_report`, it looks like the handler just needs to be updated to pass None as the connection_id when there's no connection record.

**Comment by popkinj** [comment]
Hey @esune 
I'm no python expert... But...

Could it be as simple as changing [this](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/protocols/present_proof/v1_0/manager.py#L327-L333) to something like this:

```python
        connection_id = (
            None
            if oob_record
            else getattr(connection_record,'connection_id',None)
            if connection_record
            else None
        )
```

**Comment by esune** [comment]
> Hey @esune I'm no python expert... But...
> 
> Could it be as simple as changing [this](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/protocols/present_proof/v1_0/manager.py#L327-L333) to something like this:
> 
> ```python
>         connection_id = (
>             None
>             if oob_record
>             else getattr(connection_record,'connection_id',None)
>             if connection_record
>             else None
>         )
> ```

I think something like this should work 👍🏻
