### ISSUE TITLE
Consider using pytest-bdd

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#2620]
https://pypi.org/project/pytest-bdd/

Being honest with myself, the bdd tests are a black box to me. I am not confident in how the tests are setup, how to add more, etc. And I think that's probably a fair signal that others may feel the same way. Part of this is a lack of familiarity with Gherkin itself but the other part is the lack of familiarity with behave and its testing structure. I see pytest-bdd as a way to help one of those problems by removing behave as another test framework to learn and get familiar with.

The plugin itself is active with the most recent release dated last month.

To keep ACA-Py stable and resilient, we should probably be adding more and more integration tests. I think it's worth an investigation whether this library can make it easier to do that.

**Comment by WadeBarnes** [comment]
cc @nodlesh

**Comment by nodlesh** [comment]
Behave is considered a little easier to use than pytest-bdd, and I believe supports more Gherkin structure than pytest-bdd. I also read that it is easier to share steps between features in Behave, which we do a lot of. However, pytest has parallel execution which could come in handy in the future. Though, we can solve the parallel restriction in Behave by paralleling it in the test/build pipeline in GitHub actions/workflows. 

For myself, I have always felt that with vanilla pytest it was easy to write tests that no one could read, or understand what they were doing. However, inserting Gherkin/BDD into it may solve that problem.

I guess it comes down to the perspective of the one writing the tests, if they have pytest experience then pytest-bdd might be easier to pick up. If pytest isn't in the person's repertoire, then I would assume Behave would be the easier framework. The behave structure is really simple; Feature files, and a steps py file that bridges the gherkin to python code. If someone is familiar with pytest-bdd then I don't think that behave is going to be very difficult.   

I see no issues though with moving to pytest-bdd, and could possibly help with that if you want. I don't see a ton of value in moving existing behave tests to pytest-bdd, but if the community wants to do future integration testing in pytest-bdd then I see no reason not to do that. 

The only drawback I would see is that other test harnesses, like AATH and AMTH, are using Behave and will continue to, so there would some loss of continuity there. 

One thing I really agree with is that we should be adding more and more integration tests. To be honest, I think tests should be written first, before the new features in ACA-Py, to test those new features  (TDD style which is what BDD is really meant for). This way we have expressed plain english specification in gherkin of what the feature is expected to do before the feature is developed.

**Comment by WadeBarnes** [comment]
> One thing I really agree with is that we should be adding more and more integration tests. To be honest, I think tests should be written first, before the new features in ACA-Py, to test those new features (TDD style which is what BDD is really meant for). This way we have expressed plain english specification in gherkin of what the feature is expected to do before the feature is developed.

👍

**Comment by dbluhm** [comment]
Thanks for your thoughts on this! I will try to spend more time getting over the learning curve before forming opinions on where we should go. I will push back a bit on the sentiment of pytest being unreadable and attribute it to being just a matter of preference. My team makes extensive use of pytest and we are happy with it. I'll agree that you certainly can write unreadable tests -- to be frank, some of ACA-Py's unit tests are ridiculous but I think that's more an issue with how deeply interconnected some pieces are and how mocking is almost an outright necessity to isolate units. A different problem.

**Comment by dbluhm** [comment]
I'm going to close this as not enough benefit for the trouble it could potentially cause. Thanks again for your input on this question!
