### ISSUE TITLE
Add support for DID Peer 4 to ACA-Py

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2640]
Add support for [DID Peer 4](https://identity.foundation/peer-did-method-spec/#method-4-short-form-and-long-form) to ACA-Py.

At minimum, we need to be able to accept DID Peer 4 DIDs from other parties.

In addition, we need a way to trigger the creation of DIDComm connections for which our side uses a DID Peer 4. Likely, that means:

- A configuration setting to create new connections using DID Peer 4.
  - The setting should be available at the tenant level
- An optional parameter on the creation of the connection to use a DID Peer 4. Not sure if that is in creating the invitation.

**Comment by Jsyro** [comment]
did:peer:4 resolution added in https://github.com/hyperledger/aries-cloudagent-python/pull/2692.

emitting did:peer:4 is future work. @swcurran Should i do that now, or switch to [did rotate](https://github.com/hyperledger/aries-cloudagent-python/pull/2494)

**Comment by Jsyro** [comment]
merged https://github.com/hyperledger/aries-cloudagent-python/pull/2696 .

closing this ticket
