### ISSUE TITLE
Make sure —preserve-exchange-records applies to issuers, holders, and verifiers

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2656]
From this [comment on issue 535](https://github.com/hyperledger/aries-cloudagent-python/issues/535#issuecomment-1840089139):

> Hi regarding the --preserve-exchange-records, it retains for the holder side but not on the issuer's side. Is there a way to retain the exchange records for the issuer's side as well?

This task is to look at what is being done for all parts of the exchanges (issuers, holders and verifiers) and to make sure that the settings are applied correctly for each.

**Comment by usingtechnology** [comment]
see #2352. I did some work to extend that flag to include presentation exchanges and `auto_remove` to override. maybe there are still gaps?

**Comment by usingtechnology** [comment]
quikc update, haven't checked out all of it.
using issue credential v1 API (haven't checked v2)... issuer and holder can retain/preserve the exchanges. there is a bug on the holder side to override `--preserve-exchange-records` behaviour (by setting `auto_remove=True` on send-request), so exchanges currently are ALWAYS preserved. easy fix though.

more investigation on presentation exchanges (v1 and v2) tomorrow.
