### ISSUE TITLE
[BUG] VC LDP credential issuance requires the credential.type array to have more than 1 item

### ISSUE THREAD

**Issue by PatStLouis** [hyperledger/aries-cloudagent-python#2669]
The VC data model 1.1 spec states that the credential.type array can **optionally** have a second type:

`VerifiableCredential and, optionally, a more specific verifiable credential type.`
https://www.w3.org/TR/vc-data-model/#types

I would recommend to remove the validation on the `length == 1` for the credential.type as indicated in the specification.

Happy to provide a PR if this is approved.

**Comment by swcurran** [comment]
PR welcome :-)!
