### ISSUE TITLE
[BUG] Improper Use of TimeZone-Naive datetime.utcnow()

### ISSUE THREAD

**Issue by Ennovate-com** [hyperledger/aries-cloudagent-python#2678]
When `datetime.timestamp()` is called on a timezone-naive instance of `datetime`, it assumes the value is a local datetime. Therefore, the code `datetime.utcnow().timestamp()` should never be used, since the non-local timezone-naive `datetime.utcnow()` violates that assumption.

The "old" correct way to get the UTC timestamp is:
`datetime.now().timestamp()`

A better way of doing it is to avoid the naive datetime, using the timezone-aware version, formerly using:
`datetime.utcnow().replace(tzinfo=timezone.utc).timestamp()`
or now, because `datetime.utcnow()` has been deprecated since Python version 3.12, using:
`datetime.now(tz=timezone.utc).timestamp()`

A fairly easy way to see the effect is with the following code in an environment where the timezone offset is non-zero:

```
from datetime import datetime, timezone
now1 = datetime.now()
now2 = datetime.utcnow()
now3 = datetime.now(tz=timezone.utc)
now1
now1.timestamp()
now2
now2.timestamp() # WRONG!
now3
now3.timestamp()
```

This produces output like this:

```
>>> from datetime import datetime, timezone
>>> now1 = datetime.now()
>>> now2 = datetime.utcnow()
>>> now3 = datetime.now(tz=timezone.utc)
>>> now1
datetime.datetime(2023, 12, 16, 11, 50, 0, 979519)
>>> now1.timestamp()
1702749000.979519
>>> now2
datetime.datetime(2023, 12, 16, 17, 50, 0, 982995)
>>> now2.timestamp() # WRONG!
1702770600.982995
>>> now3
datetime.datetime(2023, 12, 16, 17, 50, 0, 983405, tzinfo=datetime.timezone.utc)
>>> now3.timestamp()
1702749000.983405
```

As can be seen above, when using the "old" way with the timezone-naive local datetime `now1`, `timestamp()` applies the timezone offset, resulting in the UTC timestamp value. Likewise, the "better" way with the timezone-aware `now3` datetime, `timestamp()` produces the same result. Note that without the timezone info, the value of `now2` does not appear much different than the value of `now1` except that it is 6 hours ahead. Since `now2` has already applied the timezone offset once when `utcnow()` was called, calling `timestamp()` on the timezone-naive value applies the timezone offset a second time, resulting in a timestamp value where the timezone offset has been applied twice! In the example above, the time zone was 6 hours west of UTC, resulting in a timestamp that was actually 12 hours ahead of local time and therefore, incorrectly, 6 hours (21,600 seconds) _ahead_ of UTC.

One consequence of this error results from the code `iat = int(round(datetime.utcnow().timestamp()))` in `aries_cloudagent/multitenant/base.py`. When the time zone is west of UTC, the JWT "Issued At Time" (IAT) values will be _ahead_ of UTC by the value of the timezone offset. Because that time has not yet been reached, the call to `jwt.decode` raises the exception `jwt.exceptions.ImmatureSignatureError: The token is not yet valid (iat)`:

```
2023-12-15 23:39:24,144 aries_cloudagent.admin.server ERROR Handler error with exception: Unauthorized
=================
Traceback (most recent call last):
  File "/app/aries_cloudagent/admin/server.py", line 402, in setup_context
    profile = await self.multitenant_manager.get_profile_for_token(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/aries_cloudagent/multitenant/base.py", line 362, in get_profile_for_token
    token_body = jwt.decode(token, jwt_secret, algorithms=["HS256"], leeway=1)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jwt/api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jwt/api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "/usr/local/lib/python3.11/dist-packages/jwt/api_jwt.py", line 242, in _validate_claims
    self._validate_iat(payload, now, leeway)
  File "/usr/local/lib/python3.11/dist-packages/jwt/api_jwt.py", line 278, in _validate_iat
    raise ImmatureSignatureError("The token is not yet valid (iat)")
jwt.exceptions.ImmatureSignatureError: The token is not yet valid (iat)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/aries_cloudagent/admin/server.py", line 179, in ready_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/aries_cloudagent/admin/server.py", line 216, in debug_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/aries_cloudagent/admin/server.py", line 384, in check_multitenant_authorization
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/aries_cloudagent/admin/server.py", line 420, in setup_context
    raise web.HTTPUnauthorized()
aiohttp.web_exceptions.HTTPUnauthorized: Unauthorized
2023-12-15 23:39:24,146 aiohttp.access INFO 68.207.66.210 [16/Dec/2023:05:39:24 +0000] "GET /connections HTTP/1.1" 401 179 "http://35.208.46.235:8004/api/doc" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
```

The documentation for [utcnow()](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow) has a Warning saying:
_Warning Because naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. As such, the recommended way to create an object representing the current time in UTC is by calling datetime.now(timezone.utc)._
and mentions that `datetime.utcnow()` has been deprecated since Python version 3.12. Therefore, it recommends replacing any use of the timezone-naive `datetime.utcnow()` with the timezone-aware version `datetime.now(timezone.utc)`.

The tests do not catch this issue because the tests themselves have the same issue. The values that the tests compare the IAT value to have the same double offset as the IAT values themselves. One option to remedy this is to compare one of the IAT values to the expected value, in addition to comparing to the value added to `wallet_record` by `self.manager.create_auth_token`:

```
      assert iat = 1577836800
      assert wallet_record.jwt_iat == iat
```

However, for this to detect the error, besides running the tests in UTC with a zero timezone offset, the tests would need to be run (again?) in another timezone with a negative offset and maybe even a third time with a timezone with an offset greater than zero. (Not being addressed by the PR.) In any case, the fix to replace usage of `utcnow()` needs to be applied to the tests concurrently with updating the agent code in order to avoid an `AssertionError` in `test_base.py`.

**Comment by swcurran** [comment]
Fixed by #2679
