### ISSUE TITLE
Reduce the container image content to reduce security scan reports

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2697]
We have a lot of security warnings in ACA-Py, many of which stem from unused executables in our base image (162 for "vim" alone!!).  We're going to try some things to remove them, and failing that, we'll dismiss the warnings as not relevant. We might also switch from slim-bullseye to slim-bookworm or to Alpine Linux (to shrink the image size and attack surface).

We'll see...

**Comment by swcurran** [comment]
After playing with the dockerfiles for a bit, I think the scanning security reports are false, based on the use of "slim-bullseye" as the Build image.

- adding in a command in the Dockerfile to remove "vim" from the image resulted in an error 100 exit code -- indicating the package is not installed.
- `exec`-ing into the running demo container find `vim` is not installed.

As such, we're going to dismiss the reports. That will clear up 162 of the security scan reports, and we can then look at what is left.

**Comment by swcurran** [comment]
Also looked at naively switching to Alpine.  It will not be as easy as thought. Immediately ran into two issues:

- `useradd` in Debian is `adduser` in Alpine -- but even with the manpage, I couldn't get the command to successfully execute the creation of the "aries" user.
- The package manager is (of course) different in Alpine (`apk`) so it would likely take some time to switch it. Decided (based on the checks above) that it wasn't worth the effort.

**Comment by swcurran** [comment]
Closing this issue for now. May open it again, add more comments as we go. But for now, just planning on dismissing the reports and seeing what other reports are there.

**Comment by swcurran** [comment]
Turns out we are explicitly installing the `tiny-vim` package into the image, which is likely causing the issue. If we remove that, we have no editor, but that is likely not the end of the world. @WadeBarnes @dbluhm @ianco -- what do you think about not having an editor in a running ACA-Py container?  Is there guidance we can provide about how to deal with that?  I can think of a fairly ugly copy/paste/edit/copy/paste process for getting a file edited in a pinch. Not pretty, but not impossible.

Thoughts?  

We then have to repeat the process for other security scan reports, some of which we could not remove -- e.g. OpenSSL.

I don't think we need to spend too much time on this, but looking for fast wins.

**Comment by dbluhm** [comment]
My recommendation if you need to edit in a pinch is to just apt install one after exec'ing into the container. Or derive a new image. Or use a volume. I think removing vim is an easy win.

**Comment by dbluhm** [comment]
Alpine also uses `musl` instead of the "standard" glibc which would mean that we'd have to build our binary dependencies ourselves. I'm aware of at least one group that ended up ditching Alpine because they kept on running into issues with this. So probably wouldn't recommend that. They moved to a slim Debian image, too.

**Comment by ianco** [comment]
You can also copy files to/from the image (so you could copy a file to your local, edit it, and then copy it back).  But per @dbluhm 's suggestion as long as we can "apt install" we can add an editor if necessary

**Comment by WadeBarnes** [comment]
No need for an editor to be distributed in the released image.  If someone needs it they can install it, as @dbluhm has already stated.

**Comment by swcurran** [comment]
AFAIK — there is not a way to install it if needed, as you are running as non-root (aries), and don’t have sudo access, nor the root password.  I still think we should remove it, but just wanted to check if I’m missing something about that.

**Comment by swcurran** [comment]
Thanks for the insight on alpine, @dbluhm.  Should we aim for slim-bookworm?  I did a quick test and it is not a simple switch — the docker build failed on the apt-get, so that would have to be figured out. My concern there is might build and pass on tests, but we might miss an obscure dependency.

From a brief bit of research, I also gather that the python envrionment is a little different, requiring the use of a virtual environment. Presumably that would be pretty easy to enable in docker.

**Comment by WadeBarnes** [comment]
> AFAIK — there is not a way to install it if needed, as you are running as non-root (aries), and don’t have sudo access, nor the root password. I still think we should remove it, but just wanted to check if I’m missing something about that.

Yes, I believe you are correct.  Don't see it being an issue though.  It might be convenient to have an editor for debugging, but that should be done locally where you have more control over the image and the user context.

In OpenShift, when I need control over files on the image I'll mount the file from a configmap.  That way I can edit the file in the configmap and have it mounted in the running container.

**Comment by WadeBarnes** [comment]
> Thanks for the insight on alpine, @dbluhm. Should we aim for slim-bookworm? I did a quick test and it is not a simple switch — the docker build failed on the apt-get, so that would have to be figured out. My concern there is might build and pass on tests, but we might miss an obscure dependency.
> 
> From a brief bit of research, I also gather that the python envrionment is a little different, requiring the use of a virtual environment. Presumably that would be pretty easy to enable in docker.

I seem to recall that's why we pinned it at `slim-bullseye`.

**Comment by swcurran** [comment]
Sounds good.  That’s what I was thinking as well. And as @ianco said, there are games you can play to update a file. I’ll go ahead and do a PR to remove tiny-vim.  In doing that, I’ll post a list of the other executables that have vulnerabilities to see what we can remove.

**Comment by dbluhm** [comment]
> AFAIK — there is not a way to install it if needed, as you are running as non-root (aries), and don’t have sudo access, nor the root password.  I still think we should remove it, but just wanted to check if I’m missing something about that.

In at least local environments, you can set yourself to the root user as you exec into the container without sudo or a password.

**Comment by swcurran** [comment]
VIM issue addressed with #2699 .

Here is a list of the remaining causes of the remaining alerts.  3 are in code, the rest in the items listed here:

I'm not sure there are many more we can deal with. If anyone has thoughts, please let me know -- especially if we should just dismiss the alerts, or if we should try to remove the offending item in the container image.

| Item            | Count |
|-----------------|-------|
| glibc           | 9     |
| curl            | 5     |
| openldap        | 5     |
| pcre3           | 5     |
| systemd         | 6     |
| libsepol        | 4     |
| sqlite3         | 4     |
| patch           | 4     |
| perl            | 4     |
| git             | 4     |
| libgcrypt20     | 2     |
| gnutls28        | 2     |
| openssl         | 2     |
| coreutils       | 2     |
| tar             | 2     |
| expat           | 1     |
| e2fsprogs       | 1     |
| db5.3           | 1     |
| bash            | 1     |
| apt             | 1     |
| net-tools       | 1     |
| libzstd         | 1     |
| libssh2         | 1     |
| krb5            | 1     |
| gnupg2          | 1     |
| pcre2           | 1     |
| util-linux      | 1     |
| zlib            | 1     |
| gcc-9           | 1     |
| gcc-10          | 1     |

**Comment by WadeBarnes** [comment]
We don't need the following packages in the release image:
- curl
- systemd - Not used by the container
- git

I doubt we need:
- openldap
- perl

Might be able to get away without the following for runtime environments:
- gcc-9
- gcc-10

**Comment by WadeBarnes** [comment]
I had a look at the `nightly` image to see if any of the packages were upgradable.  Results (no upgradable packages):
```
root@Morpheus:~# apt-get update -y
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8062 kB]
Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [264 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [18.8 kB]
Fetched 8554 kB in 2s (5702 kB/s)
Reading package lists... Done
root@Morpheus:~# apt list --upgradeable
Listing... Done
```

**Comment by swcurran** [comment]
Closing this issue as for now we are not going to do anything further. We can revisit this issue in the future if we think there is any serious issues.  For now, there is little here that is an actual risk. The action that was taken (removing vim) did remove a lot of noise from the reports — even if it didn’t significantly improve security
