### ISSUE TITLE
Reorganize the documentation files in ACA-Py to reduce the adjustments needed when deploy the aca-py.org docs site

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#2702]
The Aries Cloud Agent Python documentation site at [https://aca-py.org](https://aca-py.org) is currently assembled by copying the various markdown files from parts of the ACA-Py repo into the “right place” in the source repository ([https://github.com/hyperledger/aries-acapy-docs](https://github.com/hyperledger/aries-acapy-docs)) for the documentation site.

The script that generates the mkdocs site can be used as the model for where the documents should go.

**Comment by dbluhm** [comment]
Is this ready to be closed?

**Comment by swcurran** [comment]
Yup — alll done, including updates to the https://aca-py.org site, which has been significantly simplified.
