### ISSUE TITLE
AnonCreds - Confirm AnonCreds endpoints

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#2718]
There were some new endpoints added within the new anoncreds package (for example in the holder.py class).  Confirm that these are required (and weren't merge in just by accident).

**Comment by tra371** [comment]
hey @ianco , i mentioned these endpoints [here](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/holder/routes.py#L487-L493). i meant to ask if they were added to help our case like for fetching anoncreds w3c credentials.

**Comment by ianco** [comment]
> hey @ianco , i mentioned these endpoints [here](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/holder/routes.py#L487-L493). i meant to ask if they were added to help our case like for fetching anoncreds w3c credentials.

Ah ok I was looking in the `anoncreds` package.

My interpretation of the `GET /credentials` vs the `GET /credentials/w3c` endpoints is that the first is for anoncreds credentials and the second is for w3c (i.e. json-ld) credentials.

The anoncreds/w3c updates are wrapping anoncreds credentials in a w3c "package", but they are still ultimately anoncreds credentials.  So, my assumption is they would be returned by the `GET /credentials` (and related) endpoints and *not* the `GET /credentials/w3c` (and related) endpoints.

There may be some changes required to these endpoints to return any additional meta-data (i.e. info that is included in the w3c "package" but not necessarily in the credential), or maybe to allow some different search options.  However I think the main issue is the trype of credential, not how it's packaged.

**Comment by tra371** [comment]
ah so we're still gonna use the `GET /credentials` for w3c pakage.

the issue is also deciding the format a w3c credential is going to be stored in.

**Comment by ianco** [comment]
Closing, I think we've confirmed the affected endpoints
