### ISSUE TITLE
Move secondary markdown documents into a folder

### ISSUE THREAD

**Issue by jamshale** [hyperledger/aries-cloudagent-python#2725]
I don't know how others feel about this, but there is a lot of markdown files that kind of pollute the root of the repo. There are some that are required for hyperledger that should stay in the root but if the secondary documentation were moved into a dedicated directory it would make the repo cleaner.

Instead of:
![Screenshot from 2024-01-18 08-21-51](https://github.com/hyperledger/aries-cloudagent-python/assets/31809382/b9b096fb-5a84-4926-8366-1575781fe675)

Something like:
![Screenshot from 2024-01-18 08-25-03](https://github.com/hyperledger/aries-cloudagent-python/assets/31809382/5c40c0bd-00f8-4355-b9c2-ba9e8d1af1ad)

**Comment by swcurran** [comment]
There is already an issue for that #2702 .  And (hopefully) people are using https://aca-py.org.

I’ll close this as a duplicate — but totally agree with the sentiment.
