### ISSUE TITLE
Log message processing time for better performance observability

### ISSUE THREAD

**Issue by jleach** [hyperledger/aries-cloudagent-python#2736]
The BC Wallet often gets comments the wallet is "slow". It can be a daunting task to track down where the perceived slowness comes from: bc wallet, ledgers, mediator, issue agent, etc. We would like to introduce some basic logging to help track information flowing through the ecosystem during a debug session. In this case, our proposal is to add a log message when a message is received from a mediator client and when it is relayed to its destination. A sample is shown below:

```console
17:50:42.634.  Message (some id or counter for the message) received from DID 12355abc.
... other stuff
... more stuff
17:50:43.121.  Message (some id or counter for the message) relayed to DID 1325d3d332.
```

The hope is we can correlate this with a message being sent to a connecitonId / threadId / DID on the wallet and better determine how long the message took to exit our infrastructure.

**Comment by esune** [comment]
This *might* possibly be covered under [tracing](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AgentTracing.md)

**Comment by swcurran** [comment]
Where did we get on per tenant logging?  Is that complete?  I think so... #2550 .

**Comment by esune** [comment]
> Where did we get on per tenant logging? Is that complete? I think so... #2550 .

I need to pick up where we left and re-review what we have and what is missing. What @jleach is suggesting would likely require an audit of the code to include log statements in key points - if not already supported by tracing - to record entry/exit time in specific methods (with toggles to disable the statements during "normal" operation).

**Comment by ianco** [comment]
> This _might_ possibly be covered under [tracing](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AgentTracing.md)

Does AFJ/Bifold support message tracing?

**Comment by jamshale** [comment]
I'm going to close this as stale. If anyone wants to re-open it leave a comment.
