### ISSUE TITLE
light client

### ISSUE THREAD

**Issue by nickz-t3** [hyperledger/aries-cloudagent-python#2751]
Hi. Not a bug but more of a feature request.

As I understand the way ACAPy works is that every agent who wants to control his own keys (and VCs) should spin up an ACAPy instance. 

Is there a way to have a light client for the Issuer. It only issues VCs and signs them. It does not store them, those VCs are being send by some other means not included in ACAPy functionality. 

The ideal way is to be able to use it as part of some other code as an SDK. Ideally in typescript/javascript.

**Comment by PatStLouis** [comment]
@nickz-t3 is there a reason why you would want to use aca-py instead of credo to do so? Does #2990 address your requirement?
