### ISSUE TITLE
 WireFormatParseError("Message unpack failed")

### ISSUE THREAD

**Issue by jainavinash845** [hyperledger/aries-cloudagent-python#2768]
Hi @jleach @JamesKEbert @WadeBarnes @wadeking98 ,

while connecting to mediator to app getting error in acapy mediator, Earlier is was working but after rebuild the images and container getting "Message unpacked failed".  
![image](https://github.com/hyperledger/aries-cloudagent-python/assets/44163302/ad2743e9-91ee-47cc-8c6f-c9d6638a5732)

Here is start.sh

![image](https://github.com/hyperledger/aries-cloudagent-python/assets/44163302/b2fa815f-f231-4fd8-8a70-2e976141ccdb)
 kindly look into that issue

**Comment by blockchainMeng** [comment]
same error recently
