### ISSUE TITLE
Integration tests creating existing DID's

### ISSUE THREAD

**Issue by jamshale** [hyperledger/aries-cloudagent-python#2855]
The integration tests are recreating the same did's they previously created causing fails because the schema/cred_def's they are trying to create already exist on the ledger. Should be able to make the seed/did creation more random to prevent this from happening.

**Comment by PatStLouis** [comment]
have we found in the code where the seed is generated? I was thinking in [here](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/run_bdd) but I couldn't see it

**Comment by ianco** [comment]
The aca-py seed is created here:  https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/runners/support/agent.py#L211

It's kind of hokey and not really robust enough for running integration tests, where we may create hundreds of DID's in a single run of the tests.  (It was initially implemented for a simple demo but should be updated ...)

**Comment by PatStLouis** [comment]
I can suggest to switch to python [secrets.token_urlsafe](https://docs.python.org/3/library/secrets.html#secrets.token_urlsafe) to create a random seed with large entropy instead of randint.

**Comment by ianco** [comment]
> I can suggest to switch to python [secrets.token_urlsafe](https://docs.python.org/3/library/secrets.html#secrets.token_urlsafe) to create a random seed with large entropy instead of randint.

I'll take a look, thanks for the suggestion.

**Comment by PatStLouis** [comment]
@ianco looks like @dbluhm is addressing this in another pr with a similar approach, using `token_hex` instead. Less entropy but good enough!
