### ISSUE TITLE
OOB Multiuse invitations not emitting expected done webhook

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#2859]
Sometime between main and 0.11.0, we've lost a webhook of topic `out_of_band`, state `done` being emitted from ACA-Py when a connection has been completed through multiuse OOB invitations.

This is a breaking change that makes it difficult for controllers to determine when a connection was formed through an invitation intended to trigger a flow (e.g. with goal codes).

**Comment by ianco** [comment]
> @ianco — do you have some time to investigate this?

I will take a look!

**Comment by ianco** [comment]
Would be nice if the integration tests also tested for receipt of webhooks ...  I added a ticket for that awhile back (https://github.com/hyperledger/aries-cloudagent-python/issues/2675)

**Comment by swcurran** [comment]
Needed for 0.12.0

**Comment by ianco** [comment]
@dbluhm  can you confirm everything was working properly in `0.11.0`?

I can only find 2 commits that may have impacted this, one of yours (to oob_manager) (I don't think this is causing an issue):

https://github.com/hyperledger/aries-cloudagent-python/compare/0.11.0...main#diff-58bd2e10dd54af5ef794d6c6aca4e7bb29e049df0724f4d00fb77a3f2e2513ca

And (the more likely one) of mine, dealing with a different webhook issue:

https://github.com/hyperledger/aries-cloudagent-python/commit/62ec2c05827ec0f691735b3b2b92a9196429721b

... although I can't see where a webhook that had been previously emitted has been removed ...

I'll pull the `0.11.0` version and try it out ...

**Comment by dbluhm** [comment]
I can do a quick test run and should be able to provide a link to an easy to run example

**Comment by dbluhm** [comment]
Minimal reproducible example of it working on 0.11.0 found here:

https://github.com/Indicio-tech/acapy-minimal-example/tree/test/oob-0.11.0/examples/simple

```sh
git clone https://github.com/Indicio-tech/acapy-minimal-example.git
cd examples/simple
git checkout test/oob-0.11.0
docker-compose run example
# cleaning up
docker-compose down -v
```

**Comment by ianco** [comment]
@dbluhm  thanks looking at this now ...

**Comment by dbluhm** [comment]
Might be relevant, I recently realized that in order for the queued events to be emitted from a transaction, the transaction must be explicitly committed; e.g.:

```python
async with profile.transaction() as txn:
    # do some stuff...
    await rec.save(txn)
    await txn.commit()
```

Discovered this while doing the multi-use respond in kind fix

**Comment by ianco** [comment]
With the aca-py `0.11.0` version, Alice receives a `request` webhook, and then `done`.

With the latest aca-pym Alice receives an `init` webhook, and then a `request` (and then no `done`).

So there's a new `init` webhook as well as the missing `done`.

**Comment by ianco** [comment]
> Might be relevant, I recently realized that in order for the queued events to be emitted from a transaction, the transaction must be explicitly committed; e.g.:

Yes this is my commit that I referenced above.

**Comment by dbluhm** [comment]
Yes, the `init` webhook is one that I added here: https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/protocols/didexchange/v1_0/manager.py#L715-L719

With the open question of whether we should suppress the new webhook. Originally, the logic was resulting in a race condition that we worked around by adding a transaction for saving the conn rec and attaching the request.

**Comment by ianco** [comment]
Aha this commit is what caused this issue:  https://github.com/hyperledger/aries-cloudagent-python/commit/76a1d2614c592328b401f5470a510244bdd3e0c0

In `oob_processor.py` we check if the OOB record is multi-use, and if not then we emit the `done` event.  Since the `multi_use` flag wasn't getting saved we always emitted the event.

I'll update the oob_processor to always emit the `done` event even for mult_use.

**Comment by ianco** [comment]
PS @dbluhm  that simple example of yours was super useful.  @swcurran  we should link to this from aca-py somewhere, and I'm going to steal your method of checking for webhooks for the aca-py integration tests.
