### ISSUE TITLE
Problems on Checking Credential Revoke status on Holder side in multi-ledger settings

### ISSUE THREAD

**Issue by Xuanye-Zhang** [hyperledger/aries-cloudagent-python#2863]
I am working on issuing credential on multi-ledger setting. I create two ledger and both ledger integrate with the same tails-server. The scenarios is issuer (on ledger1) issue a credential to holder(on ledger2). 
The result is holder can successfully receive the credential with an valid credential id.
But while on holder side checking the revocation status of credential by calling the /credential/revoked/{cred_id} it gives the following error:
```
500 Internal Server Error

Server got itself in trouble
```
And from the ACA-PY logs it shows the error
```
2024-04-02 05:42:51,683 aries_cloudagent.core.dispatcher ERROR Handler error: credentials_revoked
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/src/app/aries_cloudagent/holder/routes.py", line 249, in credentials_revoked
    revoked = await holder.credential_revoked(
  File "/usr/src/app/aries_cloudagent/indy/credx/holder.py", line 392, in credential_revoked
    (rev_reg_delta, _) = await ledger.get_revoc_reg_delta(
  File "/usr/src/app/aries_cloudagent/ledger/indy_vdr.py", line 1052, in get_revoc_reg_delta
    response_value = response["data"]["value"]
TypeError: 'NoneType' object is not subscriptable
```
However, I can find the tails-file put on the tails-server as the following
```
"PUT /Vzh3fpkZ2ngZPquG5biAK5:4:Vzh3fpkZ2ngZPquG5biAK5:3:CL:8:source-signature-role:CL_ACCUM:34be17a8-3d15-46bf-a107-43985d5d1b42 HTTP/1.1" 200 195 "-" "Python/3.9 aiohttp/3.9.1"
```

I try the same process in settings where both receiver and sender on the same ledger, it does not have the problem.

This issue hinder the revocation on multi-ledger.

**Comment by swcurran** [comment]
Sorry you didn't get a response.  I think this sounds like a setup issue, but can't tell. Closing as stale, but feel free to reopen and add info if this is still a roadblock.
