### ISSUE TITLE
Endorser will auto endorse a txn but then complain on ack

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#2873]
When configured as an Endorser, ACA-Py will auto-endorse received txns but then fail on transaction acknowledgement:

```python
demo-alice-1          | 2024-04-04 18:10:44,970 aries_cloudagent.messaging.base_handler ERROR Error receiving transaction acknowledgement
demo-alice-1          | Traceback (most recent call last):
demo-alice-1          |   File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/protocols/endorse_transaction/v1_0/handlers/transaction_acknowledgement_handler.py", line 35, in handle
demo-alice-1          |     await mgr.receive_transaction_acknowledgement(
demo-alice-1          |   File "/home/aries/.local/lib/python3.9/site-packages/aries_cloudagent/protocols/endorse_transaction/v1_0/manager.py", line 532, in receive_transaction_acknowledgement
demo-alice-1          |     raise TransactionManagerError(
demo-alice-1          | aries_cloudagent.protocols.endorse_transaction.v1_0.manager.TransactionManagerError: The "transaction_my_job" is not set in "transaction_jobs" in connection metadata for this connection record
```

**Comment by jamshale** [comment]
For transaction acknowledgement the endorser needs to set it's role via `/transactions/{conn_id}/set-endorser-role` for the connection to prevent this from happening.

I've had some brief conversations with @ianco about this before about if this should be required or could be prevented. I'm not sure of the reason why this was done this way in the first place. 

The endorser agent in demo does this, so no errors are seen.

**Comment by dbluhm** [comment]
Indeed; I should have added a little more detail to my opening comment. Usually the `set-endorser-role` step is required but not when using the "auto-endorse" flag -- at least for the endorsement step itself. The author is still receiving the endorsed transaction and is able to publish it. So it really is only the ack step on the endorser that is failing.

I get the impression there's room for simplifying things in this protocol. We'll be spending some time adjacent to this functionality in the near future. I'll see if we have any recommendations after we've spent that time.
