### ISSUE TITLE
`PublishRevocations` model replaced with `PublishRevocationsSchemaAnoncreds`

### ISSUE THREAD

**Issue by ff137** [hyperledger/aries-cloudagent-python#2901]
Good day

I notice from working with the openapi spec, in 0.12.0 there is a new model: `PublishRevocationsSchemaAnoncreds`.
It looks like this (from running openapi-generator):
```py
class PublishRevocationsSchemaAnoncreds(BaseModel):
    rrid2crid: Optional[Dict[str, List[Annotated[str, Field(strict=True)]]]] = Field(
        default=None, description="Credential revocation ids by revocation registry id"
    )
```

This new model is now used to replace the previous `PublishRevocations` models in the Revocation API:
- The following methods: `clear_pending_revocations` and `publish_revocations` 
- they now return `PublishRevocationsSchemaAnoncreds` instead of the old `PublishRevocations`
- Additionally, the `TxnOrPublishRevocationsResult` model, which was previously using `PublishRevocations`, is now also using `PublishRevocationsSchemaAnoncreds`, which seems to be an unnecessary change.

Now, the confusion set in when I noticed the Anoncreds Revocation API is using the old `PublishRevocations`, instead of the new `PublishRevocationsSchemaAnoncreds`. The naming suggests that this is an oversight.

The old model was modified to now take extra `options`, which the `PublishRevocationsSchemaAnoncreds` does not.
```py
class PublishRevocations(BaseModel):
    options: Optional[PublishRevocationsOptions] = None
    rrid2crid: Optional[Dict[str, List[Annotated[str, Field(strict=True)]]]] = Field(
        default=None, description="Credential revocation ids by revocation registry id"
    )
```

So, my guess is that `PublishRevocationsSchemaAnoncreds` is the model that should be used in the new AnoncredsRevocationApi, and that this is the model that should have the extra `options` field, not the old one. 

All in all, this isn't problematic for the internals of ACA-Py, because the models are identical, it's just a difference in names, with the extra options field. But, the model names propagate to the openapi spec, which is causing some confusion!

If my observations are correct that this is an oversight, then do let me know and I can contribute a quick renaming fix.

**Comment by ff137** [comment]
Additionally, I notice that the old Revocation API also replaces `CredRevRecordResult` with `CredRevRecordResultSchemaAnoncreds`, in `get_revocation_status`. I assume this is also an oversight and that the Revocation API should use the same models as previous; that only the AnoncredsRevocationApi should be using these new models instead.

And the old `CredRevRecordResult` uses the new result type: `IssuerCredRevRecordSchemaAnoncreds` ...
```py
class CredRevRecordResult(BaseModel):
    result: Optional[IssuerCredRevRecordSchemaAnoncreds] = None
```

with the new `CredRevRecordResultSchemaAnoncreds` using the old result ...
```py
class CredRevRecordResultSchemaAnoncreds(BaseModel):
    """
    CredRevRecordResultSchemaAnoncreds
    """  # noqa: E501

    result: Optional[IssuerCredRevRecord] = None
```

Looks like someone used find-replace-all a bit too liberally!

**Comment by jamshale** [comment]
I likely made a mistake here. I'll have a look. Thanks for spotting it.
