### ISSUE TITLE
Broken Link in Hyperledger Participate Documentation

### ISSUE THREAD

**Issue by Mohiit70** [hyperledger/aries-cloudagent-python#2904]
The Hyperledger Aries participation page link is broken.

https://www.hyperledger.org/participate/coding

**Comment by swcurran** [comment]
Thanks. The target page moved to: https://github.com/hyperledger/aries-cloudagent-python/blob/main/docs/gettingStarted/README.md

I’ll figure out how to get that fixed with the Hyperledger folks.

@ryjones — do you know who can make the update to the page/link above?

**Comment by Mohiit70** [comment]
> Thanks. The target page moved to: https://github.com/hyperledger/aries-cloudagent-python/blob/main/docs/gettingStarted/README.md
> 
> I’ll figure out how to get that fixed with the Hyperledger folks.
> 
> @ryjones — do you know who can make the update to the page/link above?

@swcurran I think the links for Hyperledger Sawtooth and Iroha are also broken.

**Comment by ryjones** [comment]
I've raised this internally with Ben

**Comment by ryjones** [comment]
@Mohiit70 @swcurran the links are updated, I found a few more dead links and made Ben aware of it

**Comment by swcurran** [comment]
Nice! Thanks for the updates, and the report.
