### ISSUE TITLE
Broken Download Link: Video Slides

### ISSUE THREAD

**Issue by Mohiit70** [hyperledger/aries-cloudagent-python#2905]
The '**Download Video Slides**' link on the Hyperledger participation page is broken, hindering users from downloading educational resources.

Website link: https://www.hyperledger.org/participate/coding

**Comment by swcurran** [comment]
And another one for Ben — @ryjones .

Obviously ACA-Py is not the right place to report these, but what is the right place for these?

**Comment by ryjones** [comment]
@swcurran @Mohiit70 please send email to marketing@hyperledger.org

**Comment by swcurran** [comment]
Reported.
