### ISSUE TITLE
Missing Image in About Section

### ISSUE THREAD

**Issue by Mohiit70** [hyperledger/aries-cloudagent-python#2906]
Image below text in the 'About' section on the Hyperledger homepage is missing or distorted.

link: https://www.hyperledger.org/ 

![Screenshot 2024-04-22 232055](https://github.com/hyperledger/aries-cloudagent-python/assets/120316966/821c5f8d-b48a-432a-b74e-63e5078b9ceb)

**Comment by swcurran** [comment]
@ryjones — this is another for Ben.  Does he have a GitHub ID so I can assign it to him directly?

**Comment by ryjones** [comment]
@swcurran @Mohiit70 please send email to marketing@hyperledger.org

**Comment by swcurran** [comment]
Reported
