### ISSUE TITLE
Anoncreds library still referencing dev11 pre-release

### ISSUE THREAD

**Issue by loneil** [hyperledger/aries-cloudagent-python#2913]
ACA-Py 0.12.0 is still using `anoncreds= { version = "0.2.0.dev11", optional = true, allow-prereleases = true }` as a dependency but anoncreds back in Feb looks to have a real release that ACA-Py could be referencing instead that came out shortly after that one.
https://pypi.org/project/anoncreds/#history

Doesn't look like much difference between 0.2.0dev11 and 0.2.0 proper.

**Comment by dbluhm** [comment]
Fixed in #2917
