### ISSUE TITLE
Regression(0.12.X): Revocation Notifications not getting emitted

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#2915]
It looks like #2558 introduced a bug where revocation notifications are no longer getting emitted when using the `/revocation/publish-revocations` endpoint. It seems to be fine when revocation is immediately published on revoke but if the issuer desires to batch them together and publish all pending revocations at once, no notifications are emitted to the holder connection.

This seems to be an issue in both 0.12.0 and 0.12.1rc0. Not sure why we didn't catch this one sooner :thinking:

**Comment by dbluhm** [comment]
Actually no, it wasn't #2558; it looks like it was #2812. @jamshale it looks like we might have deleted some notification emissions for so they could be handled in Askar-AnonCreds but maybe didn't account for the plain old Askar wallet case?

**Comment by dbluhm** [comment]
In particular, these lines: https://github.com/hyperledger/aries-cloudagent-python/pull/2812/files#diff-21df84291ab9a8290fcb3f396c10df170eb5c891236ad3a9dcbdec9df885749fL299-L302

**Comment by jamshale** [comment]
I thought I removed this on purpose because I changed the flow to only notify after the revocation id's were written to the ledger instead of right when the endpoint was called. If this isn't happening, I must have messed something up. I can look. I thought I had covered this case.

**Comment by dbluhm** [comment]
@jamshale I think conditions of the deleted lines were such that it would only send that notification only if not using an endorser. It makes sense to only notify after the transactions are actually published in the endorser case but these lines were preventing the self-endorsed revocations to ever trigger a notification, I think.

See #2916; the changes in that PR get things working for me again

**Comment by dbluhm** [comment]
In case it's useful, I used this minimal example to reproduce and diagnose the issue: https://github.com/Indicio-tech/acapy-minimal-example/tree/main/examples/presenting_revoked_credential

With the image of `alice` pointing to `0.12.1rc0`. `docker-compose run example` to actually run it.

**Comment by jamshale** [comment]
Ughh. I think that must have been the issue. I was trying to fix the problem where using an endorser didn't send revocation notifications. This was introduced and then fixed for 0.11.0. I must have overlooked the self-endorsed case and got trigger happy here.
