### ISSUE TITLE
Snyk container scanning not running on PR

### ISSUE THREAD

**Issue by pradeepp88** [hyperledger/aries-cloudagent-python#2928]
https://github.com/hyperledger/aries-cloudagent-python/blob/f9d9baded73e49bb796ded1ed9f327dd98ce1c14/.github/workflows/snyk.yml#L1C1-L7C15

Opening this issue to review the Snyk container scan not being run on every PR as configured.

**Comment by pradeepp88** [comment]
@swcurran / @WadeBarnes - can you please check the Snyk account to see if the scans are running there? The Github action shows the last container ran 5 months ago. 
![image](https://github.com/hyperledger/aries-cloudagent-python/assets/45354395/5372b32c-7d63-45e9-81a4-2e8c7f178036)

**Comment by WadeBarnes** [comment]
It does appear to be running:
![image](https://github.com/hyperledger/aries-cloudagent-python/assets/10504350/19e64343-702f-4355-873e-2e56d2e9f700)

**Comment by pradeepp88** [comment]
@WadeBarnes thanks for checking. So it is an integration issue with Github to view the results. 

Is there a public link to view the Snyk scanning results directly from there?

**Comment by WadeBarnes** [comment]
@pradeepp88, Submitted a PR here that should fix the Sync Container scanning issues; https://github.com/hyperledger/aries-cloudagent-python/pull/2951

**Comment by pradeepp88** [comment]
Thanks @WadeBarnes but still the sarif file is having some config errors and the workflow fails 
<img width="1113" alt="image" src="https://github.com/hyperledger/aries-cloudagent-python/assets/45354395/bba1b32b-9225-4876-aea6-e7008184d1f8">

**Comment by pradeepp88** [comment]
@WadeBarnes submitted a PR #2961 to fix this issue.

**Comment by jamshale** [comment]
This fix was merged so I believe this issue can be closed.
