### ISSUE TITLE
`Anoncreds` Revoking one credential of many of the same type fails proof

### ISSUE THREAD

**Issue by jamshale** [hyperledger/aries-cloudagent-python#2934]
With anoncreds specifically. If `faber` issues multiple credentials to `alice` of the same type and then revokes any of the credentials, the next proof request will fail verification.

Steps (using demo):
- start faber `./run_demo run faber --wallet-type askar-anoncreds --revocation`
- start alice `./run_demo run alice --wallet-type askar-anoncreds`
- connect
- issue 3 credentials to alice
- revoke credential 2
- request proof
- result will be `verified = false`

[Screencast from 2024-05-07 09:39:59 AM.webm](https://github.com/hyperledger/aries-cloudagent-python/assets/31809382/29afa09f-16f4-4903-902c-1ac5860c2eb1)

**Comment by swcurran** [comment]
Sounds like this is either a bug in ACA-Py’s selection of a default credential to use when there are multiple — should choose the most recent non-revoked one, or in Alice picking the wrong one to use from a set.

**Comment by swcurran** [comment]
That said, I don’t know how “default” is defined by ACA-Py.  Presumably it is the first in the array of candidate VCs that could be used to satisfy the request.
