### ISSUE TITLE
List of supported/stable images for use

### ISSUE THREAD

**Issue by pradeepp88** [hyperledger/aries-cloudagent-python#2993]
Currently there are many images available in GHCR repo and there is no documentation where we can find stable images/versions for use. The previous major version images still has vulnerabilities, ex: 0.11.0 which has been fixed in 0.11.1. 

Creating this issue to create a documentation where the community can find a list of supported or stable docker images for use.

Once we have the list of supported images, we can setup a workflow to regularly scan for vulnerabilities as the vulnerability list is being constantly updated.

**Comment by pradeepp88** [comment]
cc: @WadeBarnes @swcurran

**Comment by swcurran** [comment]
Resolved with this PR #3143 that enccompasses and extends #3051
