### ISSUE TITLE
Investigate and test `fix_ledger_entry` implementation (Anoncreds)

### ISSUE THREAD

**Issue by jamshale** [hyperledger/aries-cloudagent-python#3016]
After studying some of the sonarcloud reports there was a high severity issue with `aries_cloudagent/anoncreds/default/legacy_indy/registry.py` not calling the `generate_ledger_rrrecovery_txn` method with the correct values. This occurs in `fix_ledger_entry`. I think this happened with an anoncreds upgrade and isn't unit tested correctly. After studying it a bit more I don't have much confidence it was implemented correctly or that it's working.

It's challenging to manually test because it requires the ledger getting out of sync with the wallet. 

Should go over this function and ensure it's working and tested properly.

**Comment by swcurran** [comment]
@ianco — I know you were involved in the `fix_ledger_entry` work. Can you/have you checked in to see what @jamshale has found? Thanks.

**Comment by jamshale** [comment]
https://sonarcloud.io/code?id=hyperledger_aries-cloudagent-python&selected=hyperledger_aries-cloudagent-python%3Aaries_cloudagent%2Fanoncreds%2Fdefault%2Flegacy_indy%2Fregistry.py&line=1040. For reference.

I don't know a lot about this feature. I'm assuming there is a similar function for the indycredx implementation. Just doesn't look like I unit tested it properly, or that it was really ever working, at least since anoncreds got upgraded to version 2.
