### ISSUE TITLE
[BBS] optional docker build and images

### ISSUE THREAD

**Issue by amanji** [hyperledger/aries-cloudagent-python#3104]
The currently included BBS (`ursa-bbs-signatures`) library relies on an outdated and archived rust library and does not support Apple ARM architecture. It is also an optional dependency at the moment but is installed by default. It was previously proposed to move the BBS implementation from the core of ACA-Py to a plugin, however this would be a significant undertaking for a deprecated library and given the fact that there is an updated spec for BBS signatures whose implementation is imminent.

Instead, it is currently proposed that 2 separate ACA-Py images be built going forward. The default image would not have BBS installed. An extended image would be available (tagged with a `-bbs` suffix) that includes BBS (for those that need it) with the understanding that it would not support Apple ARM architecture.

This ticket encompasses the following deliverables:
1. Remove BBS dependency from the current Docker config.
2. Create a Docker.bbs config file that creates an augmented ACA-Py image which includes BBS (to be tagged with a `-bbs` suffix)
3. README documentation explaining the different images and the trade-offs of both
4. Release both images for consumption

**Comment by swcurran** [comment]
Looks good!

**Comment by jamshale** [comment]
Closing as completed
