### ISSUE TITLE
Presentation Ack missing?

### ISSUE THREAD

**Issue by domwoe** [hyperledger/aries-cloudagent-python#311]
According to the present-proof protocol, the verifier should send an ACK message to the prover.

I'm using the /present-proof/send-proposal with all the auto flags enabled at the agent which leads to the following final states:
verifier: verified
prover: presentation_sent

I would expect, that the prover ends up in a different state and I can't see anything about the ack message in the logs.

**Comment by sklump** [comment]
I'll take a look at this.

**Comment by sklump** [comment]
PR#314 fixes.
