### ISSUE TITLE
Cherry Pick PR 3095 To The 0.11.x and 0.12.x branches

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#3119]
Please take the changes in PR 3095 and apply them to 0.11.x and 0.12.x branches so that we can release them.

**Comment by dbluhm** [comment]
I have a couple of other changes that I have parties interested in getting in a 0.12.x release:

- #3112
- #2835
- #2943

Any chance we could cherry-pick these over as well?

**Comment by dbluhm** [comment]
Happy to do some leg-work to make it happen, too

**Comment by swcurran** [comment]
Happy to see those in the release — go for it.  Hopefully the tests cover these.  I’m not good enough at git to do the cherry picking :-).

**Comment by jamshale** [comment]
I'll give it a shot and see how many issues I encounter.

**Comment by jamshale** [comment]
I remember now. I looked at this before. I think `0.11.x` is straightforward but I'm not sure about `0.12.x`? There's no branch for this. Should we create one first? Or am I going to be using tags instead?

**Comment by swcurran** [comment]
Please create a branch for 0.12.0 at the 0.12.1 tag.

BTW — @dbluhm — are any of those PRs you listed security patches such that they should be 0.11.x as well, or are they just nice to haves for 0.12.x?

Thanks!

**Comment by dbluhm** [comment]
Nice to haves; bug fixes, interop, and extensibility

**Comment by dbluhm** [comment]
Oh, thought of one more (sorry): #3050

**Comment by loneil** [comment]
Thanks for including that one @dbluhm ! I tested out the 0.12.2 RC in a Traction deployment and it indeed now successfully completes OOB connections from Traction to the version of Credo in the BC Wallet.
