### ISSUE TITLE
Backport #3081 to LTS releases

### ISSUE THREAD

**Issue by esune** [hyperledger/aries-cloudagent-python#3139]
#3081 tweaks terse webhooks to expose enough data to allow controllers to receive the information they need without relying on storing and fetching the exchange records.

This change should be cherry-picked and backported to current LTS releases to avoid issues for users using 2.0 protocols.

**Comment by swcurran** [comment]
@jamshale — can you make the necessary PRs for this?  Thanks.  Let’s get this into 0.12.2, since we haven’t released it yet.

@dbluhm, others — any updates on the testing of 0.12.2rc1?

**Comment by swcurran** [comment]
Does this really need to go to 0.11.x?  I'm not sure it is relevant -- I think the related features were in 0.12.x only.

**Comment by esune** [comment]
> Does this really need to go to 0.11.x? I'm not sure it is relevant -- I think the related features were in 0.12.x only.

I would be okay backporting it only to `0.12.x`, however since present-proof 2.0 was introduced in [https://github.com/hyperledger/aries-cloudagent-python/releases/tag/0.7.4](0.7.4) and the terse webhooks this addresses were added in [0.8.0](https://github.com/hyperledger/aries-cloudagent-python/releases/tag/0.8.0) I think this issue would be in any release after 0.8.0 so it would be good to address this in all (currently) designated LTS releases.

**Comment by swcurran** [comment]
It was the handling of the deleting of Presentation records after the protocol completes that I was thinking about. It turns out, that went in to ACA-Py in 0.10.0, so before the 0.11.0 LTS.  It’s kind of a stretch to be needed for an LTS, as it isn’t a security issue, and anyone seeing it would have long addressed it somehow.

**Comment by esune** [comment]
Ah, right - it's in combination with that as well. If we can get `0.12.x` it might be good enough - I agree it is not a security issue, but seems like an important enough bug to get it fixed in at lest the latest official release (to me).
