### ISSUE TITLE
Update CI with explicit permissions for publishing images

### ISSUE THREAD

**Issue by gmulhearn** [hyperledger/aries-cloudagent-python#3165]
Hi, after encountering a recent issue in VCX's CI with image publishing permissions, i checked acapy as well.. 

I believe something changed in the hyperledger organisation settings last week where the GITHUB_TOKEN default permissions dropped to read-only. As a result, our image-publishing jobs started getting denied..

e.g. it looks like nightly publishes of acapy have failed or skipped for the past week or so: https://github.com/hyperledger/aries-cloudagent-python/actions/workflows/nigthly.yml

last successful run: https://github.com/hyperledger/aries-cloudagent-python/actions/runs/10275685048
![image](https://github.com/user-attachments/assets/9e96fcce-5218-42f0-bec8-205b97d47f1b)

runs now: https://github.com/hyperledger/aries-cloudagent-python/actions/runs/10396422027/job/28790543901
![image](https://github.com/user-attachments/assets/fe8d15f3-5a90-4657-b3e3-27ff7b348118)

(compare the github_token permissions)

For VCX, the fix appeared to be adding explicit permissions to the affected jobs:
```
    permissions:
      contents: read
      packages: write
```

Related fix in VCX: https://github.com/hyperledger/aries-vcx/pull/1283

**Comment by swcurran** [comment]
Thanks — this was top of the agenda today.  @jamshale could you take a look?

I had a similar (but perhaps unrelated) experience with another repo that required adding this.

**Comment by jamshale** [comment]
That sounds like the same issue. I had thought the token might have expired, but this would make sense.
