### ISSUE TITLE
Documentation on Outstanding work for AnonCreds Wallet (askar-anoncreds) out-of-date?

### ISSUE THREAD

**Issue by rngadam** [hyperledger/aries-cloudagent-python#3192]
https://aca-py.org/latest/deploying/AnonCredsWalletType/#outstanding-work

https://github.com/rngadam/aries-cloudagent-python/blob/3447dc89fbe9b498139705a2b1ac7c69616b0154/docs/deploying/AnonCredsWalletType.md#L79-L90

![image](https://github.com/user-attachments/assets/00265428-b420-4efc-957b-fbb6345b5113)

This seems to be a list from 6 months ago. I see that many of these issues seemed to be addressed:

https://github.com/hyperledger/aries-cloudagent-python/issues?q=is%3Aissue+label%3AAnonCreds+is%3Aclosed

Would like to know what the current outstanding work is.

**Comment by jamshale** [comment]
I do think most of this has been accomplished. I can update it.

**Comment by rngadam** [comment]
Thank you!
