### ISSUE TITLE
Is it possible to migrate wallet strategy DatabasePerWallet -> MultiWalletSingleTable?

### ISSUE THREAD

**Issue by alterkim** [hyperledger/aries-cloudagent-python#3219]
Hi all,

I was using acapy version 0.7.5 and wallet type `indy` with `multitenancy` mode. 
Now, I want to upgrade the acapy version, but I have to change wallet type to `askar`. Even I was using `multitenancy` mode, my wallet storage is using `DatabasePerWallet` strategy. Before I migrate to `askar`, I want to change `DatabasePerWallet` strategy to `MultiWalletSingleTable`. I would like to ask if this is possible.

Thank you for reading!

**Comment by swcurran** [comment]
Comments, @jamshale ?  :-).

**Comment by jamshale** [comment]
Yes, If you haven't upgraded already this should be straightforward using the [aries-acapy-tools](https://github.com/hyperledger/aries-acapy-tools/blob/main/acapy_wallet_upgrade/README.md) acapy_wallet_upgrade script. Particularly the `mwst-as-profiles` option.

If you have more questions, then @dbluhm might have better answers as he was on the team that produced the script.

**Comment by alterkim** [comment]
Thank you for your answers.
I also want to use `mwst-as-profiles` option, but now my system is working as `dbpw` with `multi-tenancy`.
So that's why I want to migrate `dbpw` as `mwst` in indy wallets then migrate with `mwst-as-profiles` option.

But if this is not possible, I think migrating as `dbpw` askar can be best.

**Comment by jamshale** [comment]
Oh. I didn't realize the option didn't work for indy multi-tenant multi-wallets. I actually didn't realize that was an option for indy wallets at all. I joined the project after askar wallets were the common wallet types.

I'd say this isn't possible currently. I have been working on tools to convert multi-tenant wallet types for askar, but the only option available currently in multi-tenant single wallet to multi-tenant multi-wallet. The opposite of what you were looking for. I think there is going to be more complexity for your case and haven't put effort into this as it's not what our use case needed.

If this is something you really need... You could possibly work on updating the `acapy_wallet_upgrade` tool for your case,  or migrating to the askar wallet type multi-wallet for now and then working on a new tool for askar multi-tenant multi-wallet to multi-tenant single wallet. I did want to do this but there's no timeline for completing it.

**Comment by jamshale** [comment]
I'm going to close this as the only option is to create a tool in `aries-acapy-tools` repo. Now that I have more understanding of mutiltenant wallets, I do think it's possible to create the from multi-wallet to single-wallet but I don't have plans to work on anytime soon.
