### ISSUE TITLE
Add new maintainers -- Mourits, Thiago and Patrick

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#3239]
The work on the (successful!) application to move ACA-Py to the [OpenWallet Foundation](https://openwallet.foundation/) triggered some thinking on adding some new maintainers to the project. I'd like to propose adding @ff137 and @thiagoromanos to the list of maintainers. Both have deep expertise in deploying ACA-Py and decentralized solutions and both have made substantial contributions to the project.

Please add a thumbs up/down and/or approve/disapprove comment to this issue, and if/when enough Maintainers have approved the proposal, we can put in the PR to the [Hyperledger Governance YAML](https://github.com/hyperledger/governance/blob/main/access-control.yaml) file to make the change effective.

The current maintainers of the project will transfer with the repo to the OpenWallet Foundation project when that move is carried out.

Thanks!

**Comment by jamshale** [comment]
👍 Yes, I think both would be great to have as maintainers.

**Comment by PatStLouis** [comment]
I would like to submit my application to become a maintainer as well.

**Comment by swcurran** [comment]
Awesome — I was thinking the same thing as I wrote that.  I’ll do a PR for all three.

Last call for objections/alternatives.

**Comment by swcurran** [comment]
Done!!!   Except I forgot about the comment to add @PatStLouis 😮‍💨  .  I'll do that now.  Sorry about that -- and I've fixed the name of the issue.

**Comment by swcurran** [comment]
w00t!!! We have new maintainers.

Congratulations and thank you to @ff137, @thiagoromanos and @PatStLouis !  Guidance for what the responsibilities are can be found in this section of the  [Maintainers.md](https://github.com/hyperledger/aries-cloudagent-python/blob/main/MAINTAINERS.md#the-duties-of-a-maintainer) file -- let me know if you see anything that is not right.  I will be removing the top section that lists the maintainers as that is no longer the "source of truth" (if it ever was) for the list - to be included in my current PR.  Great as well, if you can make the project meeting -- ACA-Pug on Tuesday's at 8:00 Pacific / 17:00 Central Europe every second week, the Aries Maintainer Meetings on opposite weeks on Tuesday's at 9:00 Pacific / 18:00 Central Europe.  Totally understand if those times are not convenient for you.  Biggest thing we need you to do is weigh in on the direction of the project -- make sure we are doing the right things!!

Thanks!
