### ISSUE TITLE
attr_names in SchemaSchema class should be attrNames

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#324]
I don't know much about the internals of this project or python in general, but the [`attr_names`](https://github.com/hyperledger/aries-cloudagent-python/blob/caf0b39f8c3762a3cdc578b2343913af662a490b/aries_cloudagent/messaging/schemas/routes.py#L68) property in the `SchemaSchema` class is written in snake_case (`attr_names`) but in reality is returned in camelCase (`attrNames`).

As the property `seqNo` is also declared in camelCase I think this is a typo? If so I would be happy to open a PR.

**Comment by sklump** [comment]
Schema is as defined in indy-sdk. Touch nothing.

**Comment by TimoGlastra** [comment]
I get that the schema is returned as it is defined in the indy-sdk.

The indy-sdk returns the `attrNames` in camelCase, and not as `attr_names` in snake_case. See the [Rust code](https://github.com/hyperledger/indy-sdk/blob/b418cca7c8fe6e1c5fbfc281f4b72d19a0ddc67e/libindy/src/domain/anoncreds/schema.rs#L19) and for example the [NodeJS wrapper docs](https://github.com/hyperledger/indy-sdk/blob/b418cca7c8fe6e1c5fbfc281f4b72d19a0ddc67e/libindy/src/domain/anoncreds/schema.rs#L19). 

However aca-py, this repo, defined it as `attr_names` and not `attrNames` in the [`SchemaSchema` class](https://github.com/hyperledger/aries-cloudagent-python/blob/caf0b39f8c3762a3cdc578b2343913af662a490b/aries_cloudagent/messaging/schemas/routes.py#L68).

So the OpenAPI scheme that is generated contains inconsistent casing type definitions that is not representing what is really returned.

**Comment by sklump** [comment]
I will make it match indy.

**Comment by TimoGlastra** [comment]
Yeah it seems like the casing is not very consistent and can be confusing (for me at least).

I see it is already fixed and merged. Thank you!
