### ISSUE TITLE
BDD Integration tests running on forks

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#3275]
![image](https://github.com/user-attachments/assets/6b34fa4b-ee03-457f-bf99-4516b036f9a3)
Heads up that the BDD nightly tests (I think) are running on forks. Should we limit this to just running on the main repo?
@jamshale

**Comment by jamshale** [comment]
I'll fix this. I hadn't really thought about it at the time. I just updated the sonarcloud workflow that had the same issue.
