### ISSUE TITLE
Checking encoded value vs. raw when verifying a presentation

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#340]
Per https://github.com/hyperledger/aries-rfcs/issues/391, please add support for verifying that the raw and encoded values match.

~~Because of the intricacies of the Aries Interop Profile versioning, I'd like to know what the impact would be of adding support for version 1.1 of [credential proposal in 0036](https://github.com/hyperledger/aries-rfcs/tree/master/features/0036-issue-credential#propose-credential).  The change is outlined [here](https://github.com/hyperledger/aries-rfcs/tree/master/features/0036-issue-credential#11propose-credential).  I would assume we would have to make the receipt of that message support the optional parameters, and handle them appropriately.  Please confirm or correct my understanding, and the effort and impact of making that change.~~

Thanks

**Comment by sklump** [comment]
The changes in v1.1 of the credential proposal are nothing to do with encoding. The v1.1 changes allow for a proposal of a credential without the holder needing to know the cred def id. I believe v1.1 is still missing `schema_issuer_did` as a criterion. I've raised it here https://github.com/hyperledger/aries-rfcs/issues/370.

Closing up the raw/encoded bait-and-switch is a totally separate issue. It shouldn't take long and I don't believe there are other encoding mechanisms out there at present, so it should be all to the positive.

**Comment by swcurran** [comment]
I understand that the 1.1 issues have nothing to do with encoding. It's how we handle the AIP versioing that I'm trying to get a handle on with the second part of this.  As such, I'm trying to understand the impact of implementing 1.1 so we can make another decision on that as a community. 

I'll make it a separate issue and remove it from here.

**Comment by sklump** [comment]
PR#344 has the verifier check for tamper evidence before submitting to indy-sdk for verification.
https://github.com/hyperledger/aries-cloudagent-python/pull/344

**Comment by swcurran** [comment]
Resolved. The existing ACA-Py encoding algorithm is the same.
