### ISSUE TITLE
Prepare and release ACA-Py 0.4.1

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#342]
Please include work up until now, plus:

- required: PR #240 (please merge it)
- required: PR #338
- required: PR #336
- optional: PR #333
- optional: PR #339

As well, we need the issues raised in [Aries RFCs 391](https://github.com/hyperledger/aries-rfcs/issues/391) resolved and included.  Needed for ACA-Py are updates to the presentation verification (checking raw vs. encoded) and possibly the encoding algorithm which is being questioned.

Please monitor if anything else is needed, but the sooner the better and NLT Wednesday with at least the three required PRs.

**Comment by sklump** [comment]
The encoding algorithm has been present from day 1: https://github.com/hyperledger/aries-cloudagent-python/blob/401a82b10a33accd391b465f902dddc98da81803/aries_cloudagent/issuer/util.py#L9

Any change to it will break every aca-py and every indy-cat-agent credential in history. No pressure.
