### ISSUE TITLE
Running test and production instances of ACA-Py on AWS or other cloud platforms

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#351]
We'd welcome documentation contributions in this repo about running ACA-Py instances on cloud platforms.  Ideally the document would include simple test instances and more robust production instances.  For the former, a simple tutorial would be a good start.  For the latter, we would like to get sample configurations, shell scripts, architectural drawings and guidance to make deployments robust.

For example, it might be on top of the Kubernetes cloud solutions so that an instance would get "free" auto-restart when the process(es) fail, rollover, and auto-scaling when loads increase/decrease.

**Comment by santacruzm** [comment]
Hello! My team and I would like to get more information on this issue and are interested in looking into it! Can we pick it up?

**Comment by swcurran** [comment]
You bet! We know a lot about running ACA-Py on OpenShift (Red Hat's Kubernetes distro) and may be able to help if you want to discuss.  We don't know AWS that well, so that's where we (and others could use help).  I'm thinking of a folder in the repo as a start.

Thanks!!

**Comment by swcurran** [comment]
Note from Hyperledger Rocketchat from sebastillar (eSatus, I think):

> In our case we are working on Ubuntu 16.04. To initialize the agents we use crontab and @reboot rules. When the host computer reboot, crontab executes the rules (run scripts or commands).
