### ISSUE TITLE
Push notification outbound-transport with message pickup protocol

### ISSUE THREAD

**Issue by dgunseli** [hyperledger/aries-cloudagent-python#365]
Currently we are working on a native mobile edge agent solution. For informing mobile applications about any messages from agent, we are planning to use push notifications. For that reason we implemented a basic outbound-transport. It is working.

But the problem is, agent messages reach push notification data limit easily. Than we decided implement a message store&pickup protocol according to  [RFC 0212](https://github.com/hyperledger/aries-rfcs/tree/master/features/0212-pickup). 

Main idea is this:

- Mobile users will create an artificial endpoint like 'push:XXXX'
- Mobile users will create connection request with this artificial endpoint
- Push notification outbound-transport will be assigned for this schema
- Any outbound messages will be handled with this push notification outbound-transport
- Any messages will be sent via push notification to the edge-agent if the message size doesn't exceed data size limit of push notification, otherwise message will be stored and only an information about stored message will be sent to the edge-agent through push-notification
- Mobile user will query stored messages with pickup protocol when it is informed about the message (batch or with a single message id which be delivered with push notification)

Main requirements for this implementation are:

- Outbound transports don't have context to inject. So we can't use protocols inside the transports or do any wallet interactions to store messages. Is there any comments or solutions about it?
- Push notification service requires a key. It would be better if we add this key to the parameters rather than add this parameter as hard-coded.

**Comment by swcurran** [comment]
Closing this as alternatives to this are being worked. Push notifications will probably go into the aries-mediator-service repo.
