### ISSUE TITLE
Websocket "Webhook" not working

### ISSUE THREAD

**Issue by matgnt** [hyperledger/aries-cloudagent-python#366]
Hi all,

from the code in `server.py` I found that websockets are a way to receive push notifications. I very much like this idea! After playing around with it a little, I could only receive the very first message after I connected to the `/ws` endpoint. 1 message on the "settings" topic. Right after this message, the connection got closed.

After debugging `aca-py` a bit, I can locate the issue now.
I used version 0.4.1, but no change in server.py since then.

`send = loop.create_task(queue.dequeue(timeout=5.0))`
https://github.com/hyperledger/aries-cloudagent-python/blob/master/aries_cloudagent/admin/server.py#L364

The timeout can cause an `asyncio.TimeoutError` exception.
(raised in `basic.py`)

If that happens, it's not detected until this call:
`msg = send.result()`
https://github.com/hyperledger/aries-cloudagent-python/blob/master/aries_cloudagent/admin/server.py#L380

This call re-raises the exception from inside the task and causes the whole loop to stop and jump to the `finally` block and cleans up the websocket queue.
Websocket closed now and it can't be used in `send_webhook` any more.
https://github.com/hyperledger/aries-cloudagent-python/blob/master/aries_cloudagent/admin/server.py#L427

I see a few options:
- catch the `asyncio.TimeoutError` near the `send.result()` call (or somewhere later, still inside the loop) or
- test for `send.exception()` before the `result()` call

Any thoughts on this?

Thanks and have a nice evening,
Matthias

**Comment by swcurran** [comment]
@andrewwhitehead - can you please take a look at this?  Thanks!
