### ISSUE TITLE
Create a "NOTICES" file for ACA-Py that references all dependencies and their licenses

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#367]
Generate a list of all dependencies used in the ACA-Py code base, determine the licence for each, and then construct a NOTICES file to be added to the route of the directory. This file is a requirement for Open Source projects.

Here is an example of a NOTICES file from another Hyperledger project:

- https://github.com/hyperledger/sawtooth-core/blob/master/NOTICES

Guidance from Apache on how to assemble a NOTICES file:

- https://www.apache.org/dev/licensing-howto.html

This python script appears to be able to process (some kind of) source code to produce a notices file. Perhaps it might be useful?

- https://github.com/aosp-mirror/platform_build/blob/master/tools/generate-notice-files.py

**Comment by sklump** [comment]
I can take this.
