### ISSUE TITLE
Shepard aries-acapy-controllers repo into Hyperledger

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#386]
@WadeBarnes, please work with @amanji to shepard the movement of this repo directly into Hyperledger.  This is not a BC Gov repo, so no need to have it stop there.

There is a PR to be reviewed/revised/merged which should be done first, and it would be great if you could verify DCO and activate the DCO bot. Once that and anything else you think is needed, please help @amanji and Ry (from Hyperledger) make the transfer.  We've connected with the Aries community and people are happy with the contribution.

The repo is: https://github.com/petridishdev/aries-acapy-controllers/ and Akiff (@amanji) is the owner.  He is based in Vancouver and on Hyperledger Rocketchat.

It would be great to have this done so we could include a reference to this in our talk at Hyperledger Global Forum next week.

**Comment by WadeBarnes** [comment]
Preparations complete.  Coordinating transfer.

**Comment by WadeBarnes** [comment]
Transfer complete; https://github.com/hyperledger/aries-acapy-controllers
