### ISSUE TITLE
Review and define tasks to implement the did:peer method in aries-cloudagent-python

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#39]
Please review the most recent updates to the did:peer method spec - https://openssi.github.io/peer-did-method-spec/

As you review it, please identify tasks we can add to this product now. For example:

- naming DIDs with the "did:peer:" prefix. Likely that would continue to be interoperable with any other agent.
- Generate the DID itself using the algorithm defined in the spec. Again - likely to be interoperable with any other agent.
- Add the new protocols to add the Update and Delete operations for did:peer DIDs, including making it optional to notify the other party of a delete, or to just silently delete the connection.  Likely to be eventually interoperable with other agents - once they support the protocols.

Likely there are additional impacts for which we need to account for in the agent.

**Comment by swcurran** [comment]
@nrempel not sure if this is best for you or Andrew or both. If Andrew or both, please add him next week when he is back from va-cay. Thanks

**Comment by swcurran** [comment]
@nrempel - ping for you to take a look.

**Comment by nrempel** [comment]
Sorry I missed this, I'll look into it

**Comment by swcurran** [comment]
A fascinating find...we're still having issues with this, I think.  Closing this issue in favour of remaining, more focused issues.
