### ISSUE TITLE
Add support for separating revoking a credential and posting an update to the ledger rev-reg (aka bulk revocation)

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#410]
The current implementation of revocation in ACA-Py triggers an update to the ledger (the Revocation Registry) each time a credential is revoked.  A common use case we expect to see used is the batching of revocations into a single ledger update on a periodic basis - e.g. hourly, daily, etc.

This issue is a request to enhance ACA-Py so that a controller can have separate mechanisms to revoke credentials and post an update to the Revocation Registry update.  Ideally, the controller could still do both in one step.

Suggest that in taking this task, a design be sketched out and reviewed before implementation.

Note that the Alice Faber demo might be updated to support the new capability once implemented.

**Comment by sklump** [comment]
I can take this on once I complete unit test coverage for what we already have.

**Comment by sklump** [comment]
Here's a meagre design sketch. I think where I go from here is a prototype.

I may have misunderstood the exercise: Andrew was talking about doing it at the indy level. Regardless, I'll get something together to show what's possible with the current state of the art.

https://drive.google.com/open?id=1U6oRQgTF98Avu8OnGNnvjvMe-eBtYnsW

**Comment by sklump** [comment]
Can we close this one? It's in master now.
