### ISSUE TITLE
Websocket webhook not working with --admin-api-key enabled

### ISSUE THREAD

**Issue by matgnt** [hyperledger/aries-cloudagent-python#427]
Hi all,

I'm using the websocket webhook to receive changes from aca-py, e.g. new connection invitations and I pretty much like this feature :-)

Unfortunately after activating ```--admin-api-key```, websocket can't connect any more. Reason: the ```server.py``` middleware code correctly checks for the http header ```x-api-key```
Problem is, that with (builtin) Javascript ```WebSocket()``` there is no way to set custom http-headers. Only way (I found) is when switching to "polling" protocol, which is the fallback and probably not the reason why to use websockets in the beginning.

I think we somehow should enable the admin-api-key also for websockets and I see 2 options at the moment:

1. Allow query params as an additional method to transfer ```x-api-key``` to aca-py.
One-liner change on the server in [server.py](https://github.com/hyperledger/aries-cloudagent-python/blob/master/aries_cloudagent/admin/server.py#L169)
```
header_admin_api_key = request.headers.get("x-api-key") or request.query.get("x-api-key")
```
Client:
```
new WebSocket('wss://localhost:10000/ws?x-api-key=12345
```
pro: Rather simple fix on both sides
con: URL with the key in the browser cache and server logs? (Still, client can decide not to use this feature...)

2. Send a message with the api-key to the server after websocket connection is established.
Pro: Security?
Con:
Need to define message.
Keep state of connection and only publish messages when allowed to do so.
Maybe more likely to accidentally publish data on websocket connections with wrong state (before api-key message) when implementing new features?

3. any other ideas?

Thanks for your help,
Matthias

**Comment by swcurran** [comment]
@andrewwhitehead @nrempel -- please take a look and help out with this one.

Thanks!

**Comment by matgnt** [comment]
@swcurran I now created a pull request for option 1. Anything I can help with to get this merged?

**Comment by nrempel** [comment]
Hi @matgnt, sorry about the delay.

Your implementation looks good as far as I can tell. However, I agree about the security concern with passing the api key in the url which is generally bad practice.

I think the best solution will be to open the connection and for the server to wait for an api key message. This isn't as easy as adding a query parameter though.

That being said, if you are using the builtin Javascript `WebSocket` class, does that mean you are connecting from a browser? If that's the case, then the API key will always be insecure. Most non-browser implementations of a websocket client _do_ support sending headers with a websocket connection request.

For example:

https://godoc.org/golang.org/x/net/websocket#Config
https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession.ws_connect

**Comment by matgnt** [comment]
Hi @nrempel 

thanks for the feedback! Yes, I'm using `WebSocket` from the browser.

I now created a [commit](https://github.com/boschresearch/aries-cloudagent-python/commit/d2dca06248362f15755e8d0145f76d3500eceb58) with a basic option 2 implementation - still with rough edges ;-)

It basically does the following things:
1. Exception for the /ws path from middleware logic that closes the connection if no api key is given in header
2. Add a property api_key_authenticated to the websocket / BasicMessageQueue
3. Only send messages to websocket if it is authenticated

I also added a simple html page to check the console output.

Todos:
- Still allow http headers (non-browser websocket implementations)
- message structure for passing the apiKey
- ...

@nrempel What do you think? Is this going to the right direction? Thanks for your feedback,
Matthias

**Comment by nrempel** [comment]
@matgnt so I think we should not support connections from a web browser by design. In any scenario, if a controller connects to the agent from the browser, the API key will be exposed to the end-user. Whether by a network call to retrieve the key or having the key hard-coded in the HTML or Javascript, it will always be exposed.

Can you share a bit more about what you are trying to accomplish?

**Comment by matgnt** [comment]
@nrempel Good that you ask, yes, the api key is exposed to the user.

It started as a system like a "developer playground" where developers can easily spawn new agents and connect to them to e.g. issue credentials and "play" with SSI. Only thing missing is notifications when, e.g. new invitations are in the queue.

I see different options to solve this problem:
1. poll the agent (from the frontend)
2. create a controller that does the notification through websockets to the frontend
3. run the agent in insecure mode (which allows everyone to connect).
4. using websockets with api key to get notifications from the agent directly. Only the user who created the agent is able to connect with its "private" / individual api key - of course, the system that started the agent also knows the api key.

I thought number 4 would be a good idea. I thought the user who knows the api key is the "owner" of the agent. It's like a hosting service for agents and you authenticate by knowing the api key.

**Comment by matgnt** [comment]
I've created a new pull request #528 with a message structure to send the api key and test cases for both cases: authentication via header and via websocket message content.

Let me know if I can help with anything.
