### ISSUE TITLE
Support revocation for small volume (>100,000) credential scenarios

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#433]

**Comment by sklump** [comment]
>100000 seems like large volume to me, no? Relative to what?

There is no reason in principle why aca-py as it stands won't scale to 100000 credentials, say 100 revocation registries of 1000 credentials each. What does this item entail?

**Comment by swcurran** [comment]
This is an epic (in ZenHub) term that captures the various issues and PRs needed to support revocation.  Small volume is indeed relative - I was thinking as opposed to 4.5M citizens receiving a credential from the government (or way more for larger jurisdictions).  I thing if we keep tails-files to the 2-4MB range that would be good. Just ran a couple of tests and a 5k credentials tail file is 1.6M, while a 10k one is 2.56M. So 10 to 20 revocation registries would be a reasonable way to handle 100k credentials.

But we do need to get to revocation registries with a million credentials...   Not with tails files though.
