### ISSUE TITLE
Some Minor Issues with the Acme Demo Workshop

### ISSUE THREAD

**Issue by euroledger** [hyperledger/aries-cloudagent-python#446]
I have been working through the "Acme Controller Workshop"

To get the pasted code to work I had to do a number of things that are not documented in the workshop:

Add import statements:
`import random`
`from uuid import uuid4`
`from datetime import date`

Also it looks like the CredentialPreview class is not available to demo code. So I had to comment out the use of this class for the option 1 (Issue credential). 

In the "request_received" block I used the code from faber to create a credential_preview field in the credential to be issued, which appears to be a mandatory field, thus:

```
CRED_PREVIEW_TYPE = (
    "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/1.0/credential-preview"
)
```
       cred_attrs = self.cred_attrs[message["credential_definition_id"]]
            cred_preview = {
               "@type": CRED_PREVIEW_TYPE,
                "attributes": [
                   {"name": n, "value": v} for (n, v) in cred_attrs.items()
               ],
           }
            await self.admin_POST(
                f"/issue-credential/records/{credential_exchange_id}/issue",
                {
                    "comment": f"Issuing credential, exchange {credential_exchange_id}",
                    "credential_preview": cred_preview
                    # "credential_preview": CredentialPreview(
                    #     attributes=CredAttrSpec.list_plain(cred_attrs)
                    # ).serialize()
                }
            )

With these changes I was able to run all the example use cases and they worked fine. 

It also looks like the "solution" acme.py is different from the example code snippets to be cut and pasted.

**Comment by swcurran** [comment]
Thanks for the note.  As we've evolved the ACA-Py library, we've been keeping Alice and Faber up to date, but not focusing on poor old Acme.  A PR to fix this would be great (nudge, nudge).  We should move the "complete answer" into this repo vs. having it in the @ianco repo.

Glad to hear you got through it!

**Comment by euroledger** [comment]
Sure I can do that. :-)

**Comment by euroledger** [comment]
Created a pull request, pending review for the above changes. I hope I followed the procedure correctly for forking, creating branches etc. I did remember to use the DCO signoff flag. Please let me know if there's anything fishy.

**Comment by swcurran** [comment]
@ianco - can you please review this and the PR that was provided related to this?

Thanks!

**Comment by swcurran** [comment]
Merged
