### ISSUE TITLE
Incorrect endpoint to store credential in Aries OpenAPI Demo 

### ISSUE THREAD

**Issue by sadeghd** [hyperledger/aries-cloudagent-python#448]
In "Aries OpenAPI Demo", section "Alice Stores Credential in her Wallet", we are requested to call endpoint POST /credential-exchange/records/{id}/store but it does not exist. It should be POST /issue-credntial/records/{cred_ex_id}/store as is shown in the figure below the instructions.

**Comment by swcurran** [comment]
This has been addressed in a recent update to the demo - PR #450 .  Hopefully it will be merged soon after you get this.

Thanks for the note.
