### ISSUE TITLE
Demo bug discovered

### ISSUE THREAD

**Issue by kdenhartog** [hyperledger/aries-cloudagent-python#45]
When I was running through the demo using the `./run_demo` scripts I encountered a bug.

Steps to reproduce it: 
1. start the VON network.
2. start Faber agent using `./run_demo faber`
3. start Alice agent using `./run_demo alice`
4. Send invitation details from Alice agent to Faber Agent
5. close Alice agent
6. start Alice agent again using `./run_demo alice`
7. Resend same invitation details from Alice agent to Faber Agent

On Faber agent the following stack trace is outputted:
```
Faber      | Connected
Faber      | 2019-07-08 20:07:09,766 aries_cloudagent.messaging.base_handler ERROR Error receiving connection request
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/messaging/connections/manager.py", line 301, in receive_request
Faber      |     self.context, connection_key, ConnectionRecord.INITIATOR_SELF
Faber      |   File "/home/indy/aries_cloudagent/messaging/connections/models/connection_record.py", line 247, in retrieve_by_invitation_key
Faber      |     return await cls.retrieve_by_tag_filter(context, tag_filter)
Faber      |   File "/home/indy/aries_cloudagent/messaging/connections/models/connection_record.py", line 202, in retrieve_by_tag_filter
Faber      |     cls.RECORD_TYPE, tag_filter
Faber      |   File "/home/indy/aries_cloudagent/storage/base.py", line 217, in fetch_single
Faber      |     raise StorageNotFoundError("Record not found")
Faber      | aries_cloudagent.storage.error.StorageNotFoundError: Record not found
Faber      | 
Faber      | During handling of the above exception, another exception occurred:
Faber      | 
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/messaging/connections/handlers/connection_request_handler.py", line 28, in handle
Faber      |     context.message, context.message_delivery
Faber      |   File "/home/indy/aries_cloudagent/messaging/connections/manager.py", line 305, in receive_request
Faber      |     "No invitation found for pairwise connection"
Faber      | aries_cloudagent.messaging.connections.manager.ConnectionManagerError: No invitation found for pairwise connection
```

On Alice agent the following data is provided: 
  {
    "connection_id": "f88e976e-83a9-49fa-af9a-9c2c9116ca11",
    "my_did": "HB7TcMFbS4iq3AEEykqe3a",
    "their_label": "Faber Agent",
    "initiator": "external",
    "invitation_key": "CBMhDiuBDPnbEs7LPFwpbvbSasS894cgj2KYCUVSLqUT",
    "request_id": "3903c194-4f17-46f8-b961-239f95843cab",
    "state": "request",
    "routing_state": "none",
    "created_at": "2019-07-08 20:07:09.648451Z",
    "updated_at": "2019-07-08 20:07:09.705012Z"
  }

Then when trying to send a message (3) from Faber agent, the following message is presented: 
```
Alice      | 2019-07-08 20:11:29,752 aries_cloudagent.dispatcher ERROR Message parsing failed: Message does not contain '@type' parameter, sending problem report
```

**Comment by andrewwhitehead** [comment]
Hi Kyle, that's actually expected behaviour, apart from the 'Message parsing failed' message which should be fixed shortly (it's in a PR). The agent doesn't currently allow invitations to be reused.

**Comment by kdenhartog** [comment]
Ahh gotcha, that makes sense that it shouldn't be possible to replay an invitation. I'll take a look and see if I can add a few lines in the guide as well to highlight that invitations cannot be reused as well.

**Comment by swcurran** [comment]
The guide is getting updated right now, so probably best to hang on for that a bit :-)
