### ISSUE TITLE
Identify inter-protocol dependencies that require refactor/abstraction

### ISSUE THREAD

**Issue by nrempel** [hyperledger/aries-cloudagent-python#473]

**Comment by nrempel** [comment]
This search shows all the instances where specific protocol versions are being imported directly: https://github.com/hyperledger/aries-cloudagent-python/search?q=%23+FIXME%3A+We+shouldn%27t+rely&unscoped_q=%23+FIXME%3A+We+shouldn%27t+rely

**Comment by swcurran** [comment]
@nrempel -- could you outline what is the fix for these instances?  Can we dynamically import the correct version of the protocol?  Or is there some other way to maintain these?

@sklump -- any thoughts on this?  This is a byproduct of the "proper handling of major/minor" versions of protocols.  We now declare what version of a protocol we support via the plugin registry.  Can we use that to handle these imports?

**Comment by sklump** [comment]
I am taking few hours here to look into this and come up with a document.

**Comment by nrempel** [comment]
There are a couple approaches I can think of:

Perhaps a particular protocol simply depends on another protocol of a certain version. In this case, we could keep the direct imports, or maybe go through some sort of protocol resolution abstraction, and add some validation around the protocol dependencies.

Or maybe every direct import could be bubbled up into its own abstraction. For example any reference to the connection protocol could be pulled into its own "connection" abstraction. Then the imports would reference higher-level notions of things instead of protocols directly. This is just an example, I think we already do this everywhere for connections but we would need to create more high-level notions of things that represent what the imported protocols represent.

**Comment by sklump** [comment]
https://drive.google.com/open?id=1_eA6FtMv-gqh0o8c8h6wskWR_DOE7PwB

Use symbolic links: per protocol for current version, per major version for current minor version. Link to current version from unversioned protocols, link to most recent minor version for major version matching versioned importer's reckoning (typically, v1->v1, but v0->v1 for introductions). Anyway, that's my thought.

**Comment by sklump** [comment]
https://github.com/hyperledger/aries-cloudagent-python/pull/514 provides a working implementation.

**Comment by swcurran** [comment]
@sklump -- I believe this is done and am closing. Please reopen if I'm wrong on that.
