### ISSUE TITLE
Make the credential preview a required part of the issue credential/credential offer message

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#477]
ACA-Py's `issue-credential` implementation was written according to Aries RFC [0036](https://github.com/hyperledger/aries-rfcs/tree/master/features/0036-issue-credential). When we wrote it, we made the assumption that the `credential-preview` item in the `credential-offer` message was optional. In reading the RFC, there is no indication that the item is optional. We need to fix that.

Task: To ensure that ACA-Py controllers are properly implemented, make a change to the admin endpoint for sending a `credential-offer` so that `credential-preview` is a required field.

Aside: A related issue is whether the preview **should** be a required field. We'll debate that in the issue-credential v2.0 specification. Feel free to weigh in on that topic.

**Comment by andrewwhitehead** [comment]
On a related note, the /offer endpoint currently requires a credential_preview parameter, but the preview should already be specified on the credential exchange at that point.

**Comment by swcurran** [comment]
@andrewwhitehead - not sure I understand that:

- since `/offer` is often the first message in a credential exchange, how would it be specified at that point?
- Even if the `credential-proposal` has a `credential-preview`, it is the issuer that is the authority on what will be issued.  The 'offer' should never take what is in the `proposal`.  The controller might do that, but ACA-Py should never automagically copy data from the `proposal` to the `offer`.
- What was happening in the email verification controller that allowed that?  Was it that the `/send` endpoint is not requiring the `credential-preview`?

**Comment by andrewwhitehead** [comment]
I meant /issue not /offer. The email verification controller was using /send-offer with no preview (and no auto-issue), then following up with /issue once the request was received.

**Comment by sklump** [comment]
I can look into this first thing Monday.

**Comment by sklump** [comment]
I hate to be that guy, but I'm looking at the code in issue-credential/v1_0/routes.py and I don't see anything that goes against the spec. The preview is mandatory or optional where the RFC says so.

Where is the email verification controller? What should I be fixing please?

**Comment by swcurran** [comment]
The email-verification server has been fixed.  We're trying to prevent controllers from making errors in the future.

The concern is with the "offer-credential" message, where the preview should be required but evidently is not (since the email-verification-service wasn't sending it).  Is there a verification check that the preview data is being included in the message?

I'm also concerned that the "offer-credential" is defaulting to picking up the preview data from the "cred-exchg-record". That should not be allowed - the issuer must ALWAYS supply that data.  They can get it from the "cred-exchg-record" if they want, but must explicitly supply the data for the offer and issue.

**Comment by sklump** [comment]
https://github.com/hyperledger/aries-cloudagent-python/blob/4290bda59fa255efb61a7d419c2d9c14013fb16c/aries_cloudagent/protocols/issue_credential/v1_0/routes.py#L147

https://github.com/hyperledger/aries-cloudagent-python/blob/4290bda59fa255efb61a7d419c2d9c14013fb16c/aries_cloudagent/protocols/issue_credential/v1_0/routes.py#L432

It's mandatory. My advice is to try again with the middleware patch, see if it engages. Failing that, I need instructions on how to reproduce the issue.

**Comment by sklump** [comment]
(Obviously the preview from the proposal should not be authoritative - it's effectively self-asserted)

**Comment by sklump** [comment]
... there is some logic in the manager that could use a going-over. If the controller bypasses the routes and engages the manager directly, it could skip the preview. I think that logic is extant from days long gone by. I will take a look first thing in the morning.

**Comment by swcurran** [comment]
I assume this is not much help, but here is the [PR 45](https://github.com/bcgov/indy-email-verification/pull/45) that fixed the issue in the indy-email-verification app.

My concern about the proposal -> offer flow is if a dev accidentally/lazily gets the cred preview from the proposal via the "cred_ex_object" rather than it having to come from the controller.  I don't want ACA-Py enabling that bad behaviour. But as long as the admin API is requiring the cred_preview from the admin API, all should be good.

**Comment by sklump** [comment]
Thanks - I will still go over the logic in the manager, it may be the case that it allows for optionality where the routes don't (anymore).

**Comment by sklump** [comment]
https://github.com/hyperledger/aries-cloudagent-python/pull/484
addresses residual dead code that could have allowed bypassing the preview.

**Comment by swcurran** [comment]
Closing issue.

**Comment by Sarangc1203** [comment]
> I'm also concerned that the "offer-credential" is defaulting to picking up the preview data from the "cred-exchg-record". That should not be allowed - the issuer must ALWAYS supply that data. They can get it from the "cred-exchg-record" if they want, but must explicitly supply the data for the offer and issue.

@swcurran Did anyone follow-up on this issue? Right now, the send-offer is basically issuing the requested attributes in the proposal, but it would be better if, at this stage, the issuer gets to decide what values he/she is willing to provide. Some sort of negotiation maybe? This can simply be dealt with by giving the issuer the authority to finalize the values.

**Comment by sklump** [comment]
The issuer does get to decide credential attribute values. Only on configuration setting `--auto-respond-credential-proposal` does aca-py feed proposal values into the offer without a manual step requiring controller intervention.

**Comment by Sarangc1203** [comment]
After the holder sends a proposal, the next step is issuer sending an offer. As far as I understand from the SwaggerUI, the issuer directly sends an offer to the holder using /issue-credential/records/{cred_ex_id}/send-offer which just responds to the received proposal without giving an option to tell the holder at this stage what values the issuer is ready to provide in the credential. There is an option to provide the credential_preview at the issuing stage (I still don't understand it's purpose) but it is very late in the whole issue-credential protocol cycle.
PS: I didn't configure my agent with `--auto-respond-credential-proposal`.

**Comment by sklump** [comment]
Yes: the operator should find the cred ex record by its ID and determine whether the preview values are OK.

If they are OK, the operator can send the bound offer via /issue-credential/records/{cred_ex_id}/send-offer. Otherwise, the operator can make a free offer (i.e., one not bound to a proposal) with new values and then it is up the holder how to respond to that offer.
