### ISSUE TITLE
Connection invitation handling improvements

### ISSUE THREAD

**Issue by andrewwhitehead** [hyperledger/aries-cloudagent-python#48]
Some updates to improve the granularity of the 'auto-accept' feature for invitations and reduce the number of configuration options.

- [ ] Remove the `--accept-invites` and `--accept-requests` command line parameters

- [ ] Add an `auto_accept` property to connection records. When the flag is set on a given connection record and corresponding connection request is later received, automatically send a connection response.

- [ ] Add an `auto_accept` parameter to the `connections_create_invitation` route. This simply sets the flag on the new connection record.

- [ ] Add an `auto_accept` parameter to the `connections_receive_invitation` route. If the parameter is set, automatically send a new connection request based on the invitation.

- [ ] Update demos (including IIWBook and email verification) to pass these parameters instead of setting the command line flags.

- [ ] Update documentation if necessary.

@swcurran @nrempel  Does that sound reasonable?

**Comment by swcurran** [comment]
@andrewwhitehead - what is the planned timing on this?  I have this documented in the OpenAPI demo that I'm planning to use on Wednesday.  Are you talking before or after?

Documentation is here:  https://github.com/hyperledger/aries-cloudagent-python/blob/master/demo/AriesOpenAPIDemo.md#running-the-demo-steps

Main thing to look at is the invocation.

**Comment by andrewwhitehead** [comment]
@swcurran  I'm not planning to implement this right away, nothing is currently depending on it.

**Comment by swcurran** [comment]
OK good.  I think it looks good.

**Comment by andrewwhitehead** [comment]
Resolved via #82
