### ISSUE TITLE
No permission message on aca-py architectural deep dive video

### ISSUE THREAD

**Issue by osancus** [hyperledger/aries-cloudagent-python#480]
How can i access this video?

https://zoom.us/recording/play/Pr-gdxAUVciy7MtPE9tkNAuSLT_Pl_NEYMeW2XxQRitjXtQajl3X5y7L_A1CCRee?autoplay=true&startTime=1563894122000

**Comment by swcurran** [comment]
Please try it again and let me know.  Zoom reverted all recordings to private unless explicitly shared, so I've reshared that one to be public.

Thanks!

**Comment by osancus** [comment]
I just tried it again, Still not working.

> Please try it again and let me know. Zoom reverted all recordings to private unless explicitly shared, so I've reshared that one to be public.
> 
> Thanks!

**Comment by swcurran** [comment]
I've published it on YouTube here: https://youtu.be/FXTQEtB4fto  The link works but the video is still being processed as I write this - stuck at 95%. Hopefully it will complete soon.  I'll check back in a bit.

I'll update the links soon.

**Comment by osancus** [comment]
Thanks, Stephen. Cheers!

> I've published it on YouTube here: https://youtu.be/FXTQEtB4fto The link works but the video is still being processed as I write this - stuck at 95%. Hopefully it will complete soon. I'll check back in a bit.
> 
> I'll update the links soon.
