### ISSUE TITLE
ConnectionRequest message validation error while connecting from mobile app

### ISSUE THREAD

**Issue by naman20sharma** [hyperledger/aries-cloudagent-python#488]
### Trying to establish a connection using the instructions given in AliceGetsAPhone.md  
Using https://github.com/hyperledger/aries-mobileagent-xamarin Application and **Play with Docker** for running web Agent(Faber).

After scanning the QR code from the mobile app, following error is thrown in docker-playground terminal and leaves the connection in 'Negotiating' state in the mobile application.

`Faber      | 2020-04-30 13:35:31,003 aries_cloudagent.messaging.models.base ERROR ConnectionRequest message validation error:
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/messaging/models/base.py", line 127, in deserialize
Faber      |     return schema.loads(obj) if isinstance(obj, str) else schema.load(obj)
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/marshmallow/schema.py", line 723, in load
Faber      |     data, many=many, partial=partial, unknown=unknown, postprocess=True
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/marshmallow/schema.py", line 904, in _do_load
Faber      |     raise exc
Faber      | marshmallow.exceptions.ValidationError: {'label': ['Field may not be null.']}
Faber      | 2020-04-30 13:35:31,355 aries_cloudagent.core.dispatcher ERROR Message parsing failed: Error deserializing message: ConnectionRequest schema validation failed, sending problem report
Faber      | 2020-04-30 13:35:31,360 aries_cloudagent.core.dispatcher ERROR Handler error: ConnectionManager.get_connection_targets
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/protocols/connections/v1_0/manager.py", line 976, in get_connection_targets
Faber      |     await entry.set_result([row.serialize() for row in targets], 3600)
Faber      | TypeError: 'NoneType' object is not iterable
Faber      | 2020-04-30 13:35:31,364 aries_cloudagent.core.conductor ERROR Exception in message handler:
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/core/dispatcher.py", line 171, in handle_message
Faber      |     await responder.send_reply(error_result)
Faber      |   File "/home/indy/aries_cloudagent/messaging/responder.py", line 103, in send_reply
Faber      |     await self.send_outbound(outbound)
Faber      |   File "/home/indy/aries_cloudagent/core/dispatcher.py", line 292, in send_outbound
Faber      |     await self._send(self._context, message, self._inbound_message)
Faber      |   File "/home/indy/aries_cloudagent/core/conductor.py", line 309, in outbound_message_router
Faber      |     await self.queue_outbound(context, outbound, inbound)
Faber      |   File "/home/indy/aries_cloudagent/core/conductor.py", line 335, in queue_outbound
Faber      |     mgr.get_connection_targets(connection_id=outbound.connection_id)
Faber      |   File "/home/indy/aries_cloudagent/protocols/connections/v1_0/manager.py", line 976, in get_connection_targets
Faber      |     await entry.set_result([row.serialize() for row in targets], 3600)
Faber      | TypeError: 'NoneType' object is not iterable
Faber      | 2020-04-30 13:35:31,365 aries_cloudagent.core.dispatcher ERROR Handler error: Dispatcher.handle_message
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/core/dispatcher.py", line 171, in handle_message
Faber      |     await responder.send_reply(error_result)
Faber      |   File "/home/indy/aries_cloudagent/messaging/responder.py", line 103, in send_reply
Faber      |     await self.send_outbound(outbound)
Faber      |   File "/home/indy/aries_cloudagent/core/dispatcher.py", line 292, in send_outbound
Faber      |     await self._send(self._context, message, self._inbound_message)
Faber      |   File "/home/indy/aries_cloudagent/core/conductor.py", line 309, in outbound_message_router
Faber      |     await self.queue_outbound(context, outbound, inbound)
Faber      |   File "/home/indy/aries_cloudagent/core/conductor.py", line 335, in queue_outbound
Faber      |     mgr.get_connection_targets(connection_id=outbound.connection_id)
Faber      |   File "/home/indy/aries_cloudagent/protocols/connections/v1_0/manager.py", line 976, in get_connection_targets
Faber      |     await entry.set_result([row.serialize() for row in targets], 3600)
Faber      | TypeError: 'NoneType' object is not iterable`

**Comment by ianco** [comment]
Can you provide the connection request message that is sent from the mobile agent?  (Hint: if you run faber with the `--events` flag it will print all events)

The error seems to relate to a missing attribute (`label`) somewhere.

Here is the reference in the rfc:  https://github.com/hyperledger/aries-rfcs/tree/master/features/0160-connection-protocol#1-connection-request

**Comment by naman20sharma** [comment]
> Can you provide the connection request message that is sent from the mobile agent? (Hint: if you run faber with the `--events` flag it will print all events)
> 
> The error seems to relate to a missing attribute (`label`) somewhere.
 After using `--events` flag I'm getting following event (wrt reference of connection request)

`EVENT: Response from POST /connections/create-invitation received: 
{
    "connection_id": "64a83f07-bd95-410c-a99f-7d710f3741c7",
    "invitation": {
        "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/invitation",
        "@id": "ef27df42-1664-492f-add8-83554cb1d313",
        "serviceEndpoint": "http://ip172-18-0-59-bqnsqhiosm4g008t1o9g-8020.direct.labs.play-with-docker.com",
        "recipientKeys": [
            "EDGywbAZcvN3pyxj6BjtqAoNydGghGjTYr3XDfEUkWnd"
        ],
        "label": "Faber.Agent"
    },
    "invitation_url": "http://ip172-18-0-59-bqnsqhiosm4g008t1o9g-8020.direct.labs.play-with-docker.com?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiZWYyN2RmNDItMTY2NC00OTJmLWFkZDgtODM1NTRjYjFkMzEzIiwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwOi8vaXAxNzItMTgtMC01OS1icW5zcWhpb3NtNGcwMDh0MW85Zy04MDIwLmRpcmVjdC5sYWJzLnBsYXktd2l0aC1kb2NrZXIuY29tIiwgInJlY2lwaWVudEtleXMiOiBbIkVER3l3YkFaY3ZOM3B5eGo2Qmp0cUFvTnlkR2doR2pUWXIzWERmRVVrV25kIl0sICJsYWJlbCI6ICJGYWJlci5BZ2VudCJ9"
}`

**Comment by naman20sharma** [comment]
@ianco The issue was resolved, the mobile-agent wasn't registering the "agent name", and the "their-label" property of the python-agent was null. After I added the agent-name in mobile-agent, the issue was resolved and the connection was established.

**Comment by DineshRajj** [comment]
> @ianco The issue was resolved, the mobile-agent wasn't registering the "agent name", and the "their-label" property of the python-agent was null. After I added the agent-name in mobile-agent, the issue was resolved and the connection was established.

Hi @naman20sharma I am also facing the same issue where exactly I have to add the agent name in the code? Any hints?

Thanks in Advance
