### ISSUE TITLE
Can't Access Administration API Route aca-py swagger

### ISSUE THREAD

**Issue by lucasmori** [hyperledger/aries-cloudagent-python#492]
Hi guys!

I tried to start an aries agent using aca-py command, with a very basic params like this:
```
aca-py start \
--inbound-transport http 0.0.0.0 10000 \
--outbound-transport http \
--admin 0.0.0.0 11000 \
--admin-insecure-mode

```
I get the follow errors:
 
![image](https://user-images.githubusercontent.com/31638574/81091189-3ebd6800-8ed5-11ea-8fd8-e44756032377.png)

And when I try to access that `http://0.0.0.0:11000/api/docs/swagger.json` in browser i got connection reset.

I don't know how to solve that.

**Comment by swcurran** [comment]
You are missing at least the `--wallet-type indy` to get an indy wallet (storage) in place.

**Comment by lucasmori** [comment]
I included this param, and now this error:
![image](https://user-images.githubusercontent.com/31638574/81100330-be056880-8ee2-11ea-8105-de003f8cb696.png)

**Comment by ianco** [comment]
If you're running local you need to `pip install libindy` plus whatever else is installed in the base docker image, there are lots of dependencies.

**Comment by swcurran** [comment]
There are some "running locally" instructions, with this on getting the requirements - https://github.com/hyperledger/aries-cloudagent-python/tree/master/demo#installing-prerequisites

**Comment by lucasmori** [comment]
Cool, I tried to run in docker running this command 
```
scripts/run_docker start \ 
--inbound-transport http 0.0.0.0 5000 \
--outbound-transport http \
--admin 0.0.0.0 5100 \
--admin-insecure-mode \
--wallet-type indy
```
And that was the result:
![image](https://user-images.githubusercontent.com/31638574/81103620-ae3c5300-8ee7-11ea-9547-25274f2d7d35.png)

But I can't access `http://0.0.0.0:5100`

**Comment by guilherme-funchal** [comment]
Hello Lucas!


1)Initially you must start the von-network with the commands : 

cd von-network
./manage build
./manage start

To see the von-network, you can access in the browser http://127.0.0.1:9000/

2)After that, you can execute the following command in the script directory of aca-py:

cd aries-cloudagent-python/scripts/

PORTS="8080:8080 7000:7000" ./run_docker start --wallet-type indy --seed 000000000000000000000000000Agent --wallet-key welldone --wallet-name myWallet --genesis-url http://172.17.0.1:9000/genesis --inbound-transport http 0.0.0.0 8000 --outbound-transport http --admin 0.0.0.0 8080 --admin-insecure-mode

3)Access Swagger in the browser http://127.0.0.1:8080 to use ACA-Py

**Comment by lucasmori** [comment]
Hey Guilherme!

Thank you very much, I follow your steps and I was successful. My agent is now running!

**Comment by guilherme-funchal** [comment]
Oi Lucas, trabalho no SERPRO, tenho participado de algumas reuniões com o pessoal do CPqD. Se  precisar ajuda estou a disposição.

**Comment by lucasmori** [comment]
Oi Guilherme, trabalho com soluções blockchain no CPQD. Obrigado pela ajuda!
