### ISSUE TITLE
./run_demo faber Invalid library state

### ISSUE THREAD

**Issue by martinporopat** [hyperledger/aries-cloudagent-python#496]
Hi,
When I run "./run_demo faber", I got the error:

Faber      |   File "/home/indy/aries_cloudagent/wallet/indy.py", line 188, in create
Faber      |     ) from x_indy
Faber      | aries_cloudagent.wallet.error.WalletError: Exception while performing indy operation: Error: Invalid library state
Faber      |   Caused by: Can't derive key
Faber      |   Caused by: Sodium pwhash failed

"./run_demo alice" is working OK

(Ubuntu 18.04 in Vagrant Windows)

![image](https://user-images.githubusercontent.com/3036063/81359390-649e6480-90af-11ea-8ecb-84637f2a3c3c.png)

**Comment by swcurran** [comment]
Very strange since the demo is running on docker.  Is your docker version up to date?  Space?  I just run it on the latest code in the repo (master branch) and all good.

**Comment by swcurran** [comment]
Have you tried this again?  Any other information?  Googling doesn't give much on the error.  Perhaps providing how you started up the session - what you did to create the repo, build and deploy.

**Comment by martinporopat** [comment]
Hi,
Now its working after I added asyncio.sleep(3) in some places:

https://github.com/hyperledger/aries-cloudagent-python/blob/116ea5dc5ba750537ae74303d3b9322b97378f86/demo/runners/faber.py#L162

https://github.com/hyperledger/aries-cloudagent-python/blob/116ea5dc5ba750537ae74303d3b9322b97378f86/demo/runners/support/agent.py#L574

https://github.com/hyperledger/aries-cloudagent-python/blob/116ea5dc5ba750537ae74303d3b9322b97378f86/demo/runners/faber.py#L389
