### ISSUE TITLE
 aries-cloudagent-python - how revocation works?

### ISSUE THREAD

**Issue by Shweta-hlf** [hyperledger/aries-cloudagent-python#505]
Using open rest api demo,Bank agent has created cred_def_id using "support revocation=true" and then created new revocation-registry and update it into tails file and publish this to ledger.Now bank agent  issues credential to customer.Credetial is saved into customer wallet with cred_Rev_id.Now  Bank wants to revoke issued credential from Customer.but cred_rev_id is with customer credential.
How bank will get cred_Rev_id ?
AS /issue-credential/revoke api require rev_reg_id  and cred_rev_id ?
Pls help out.
![cred_rev_id](https://user-images.githubusercontent.com/60926287/81813011-8e8ad780-9544-11ea-9d6f-2328e3075cf3.jpg)

**Comment by swcurran** [comment]
The Bank must save the ID somewhere that it decides.  This is data that the Controller would save in a database -- it shouldn't be kept in the Bank's agent storage. Typically, it would be stored in the bank's account tracking system.

**Comment by Shweta-hlf** [comment]
Thanks a lot Stephen for your quick reply....!!!
Here Cred_rev_id is auto incremented when credential issue.I am not able to customize with new value by using "cred_rev_id" or "revocation_id" while sending credential.

**Comment by sklump** [comment]
Cred rev id is not customizable. It is an index into a tails file.

**Comment by sklump** [comment]
The issuer agent generates the Revocation registry identifier with the revocation registry. It is not customizable either.

**Comment by swcurran** [comment]
Not sure about this, but should the algorithm for selection of a credential be more complex than incrementing from one?  E.g. are we potentially leaking metadata if we give out the indices in order.

I'm asking -- not sure.  Obviously tracking gets much more difficult if we don't just increment through the registry.

**Comment by andrewwhitehead** [comment]
We don't have a choice given the interface in the current indy-sdk. It could be something to look at in future revocation designs.

**Comment by sklump** [comment]
It is just an identifier. There is no reason why it should be anything other than an index. There is nothing wrong with an increment. Tails files are public, there is no sensitive data leaking here.

**Comment by swcurran** [comment]
Closing this as answered.

**Comment by Shweta-hlf** [comment]
Thanks a lot for your answer.Cred_Rev_Id is stored into holder wallet while issuer has revocation id (same as cred_rev_id) will get from /issue-credential/records.
