### ISSUE TITLE
Error: Credential definition is on ledger default but not in wallet default

### ISSUE THREAD

**Issue by Alexis-Falquier** [hyperledger/aries-cloudagent-python#506]
I got this error which I have not seen before. The cred def in question has been created before but I am not able to get it from the ledger. When calling schemas/created I get the schema id. But when I call the same on credential definitions it returns empty. If I try to create the credential definition again I get this error:

aries_cloudagent.ledger.error.LedgerError: Credential definition <cred_def_id> is on ledger default but not in wallet default

Possible relevant info:

The credential was originally created on an agent running elsewhere but with the same public DID. 

I am able to create new credential definitions but not retrieve the ones that were previously created and written to the ledger.

Network is Sovrin Staging Net

**Comment by swcurran** [comment]
That's normal behaviour on Indy, I'm afraid.  You must keep the cred def in the wallet and in sync with the ledger entry to be able to use it.  As I understand it, there are private keys associated with the public keys on the cred def, and you can't recreate a cred def.

**Comment by Alexis-Falquier** [comment]
Got it, so these keys that associate the wallet with the cred def are separate than the keys associated with the public DID? For some reason I thought that as long as the wallet held the public DID it could use the cred-def

**Comment by swcurran** [comment]
Yes - they are separate and created at Cred Def creation time. It's often a source of frustration - you can recreate a DID from a seed, but no such luck with a Cred Def.  Once you create a Cred Def, the ledger and wallet must persist for it to continue to be useful.

**Comment by Alexis-Falquier** [comment]
Got it, thanks for the info Stephen!

**Comment by miroslav-inc** [comment]
Agent needs to enable persistent storage to be in sync with ledger data (postgres for example)

**Comment by aritroCoder** [comment]
> That's normal behaviour on Indy, I'm afraid. You must keep the cred def in the wallet and in sync with the ledger entry to be able to use it. As I understand it, there are private keys associated with the public keys on the cred def, and so you can't recreate a cred def.

I had previously created a cred-def in the bcovrin ledger, but now when I deleted wallet and restarted the agent I am getting the error message above. Is there any way to fix it without using my own von network instance? I am not using any seed in the arg file of acapy

**Comment by swcurran** [comment]
There is no way to recover a CredDef deleted from a wallet. With a DID, a seed is used so that the DID can be recreated in the wallet, but that cannot be done for a CredDef.  This is the same for all networks — BCovrin Test or a local von-network.

**Comment by aritroCoder** [comment]
> There is no way to recover a CredDef deleted from a wallet. With a DID, a seed is used so that the DID can be recreated in the wallet, but that cannot be done for a CredDef. This is the same for all networks — BCovrin Test or a local von-network.

I don't want to recover the cred-def, I just want to create a new cred def, can I do it without changing the parameters in the request body?

**Comment by swcurran** [comment]
No. You have to at least change the tag. If not, it is the same identifier and will be rejected.

In theory, Indy supports "edits" but no clients support that.
