### ISSUE TITLE
Connection Invitation parameter wrong handling

### ISSUE THREAD

**Issue by ducadellaforcoletta** [hyperledger/aries-cloudagent-python#517]
A server error: "ConnectionManagerError: Cannot use public and multi_use at the same time" during the invocation of the admin api /connection/create-invitation with public=true and multi=false. 

The invitation is correctly created if the multi parameter is not provided.

Looking to the code, seems that the input parameter is managed as string, when provided, and the checks always pass as true even when false is contained. 

The url generated from my istance of aca-py is the following:  curl -X POST "http://localhost:4000/connections/create-invitation?alias=Test&accept=false&public=true&multi_use=false" -H "accept: application/json".

**Comment by sklump** [comment]
OK, I can take a look at this

**Comment by sklump** [comment]
Current master fixes, since commit 0c154494924adda2a3dd41eb7c98068009884f13
