### ISSUE TITLE
 demo/runners/performance.py fails with --routing flag

### ISSUE THREAD

**Issue by Howlla** [hyperledger/aries-cloudagent-python#522]
the error can be found in line 299
 ```
 File "/home/indy/demo/runners/performance.py", line 299, in main
    invite, auto_accept=json_dumps(False)
NameError: name 'json_dumps' is not defined
```
It can reproduced by running

$ LEDGER_URL=http://greenlight.bcovrin.vonx.io ./run_demo performance --routing

I think it should be replaced with json.dumps

**Comment by sklump** [comment]
Sorry, my mistake. I'm on it.
