### ISSUE TITLE
ACA-Py Admin API throwing 500 internal server error when issue-credential send-offer is sent with an incorrect cred_ex_id

### ISSUE THREAD

**Issue by nodlesh** [hyperledger/aries-cloudagent-python#524]
### Issue

When using the Issue Credential Protocol, the Admin API calls that take a cred_ex_id return a 400 internal server error when the id is not proper, that is either ill formed, or properly formed but invalid. 

### Steps to Reproduce
Just simply run the issue-credential send-offer though the Admin API in code or even in the Swagger web interface

### Outcome

500 Internal Server Error\n\nServer got itself in trouble

### Expected Outcome

A problem report more closely aligned to the actual problem of the id.

### Workaround

Use the correct cred_ex_id

### Test Cases Affected

None

### Severity

Medium

### Business Priority

Medium

**Comment by swcurran** [comment]
@sklump - could you take a look at this when you get a chance?  Given the work you did on the API, I'm thinking that you would be best to understand the scope of this issue.  Is this a one-off or at least a relatively rare issue, or is there a need for a systemic handling of these types of issues?  What's the best approach?

**Comment by sklump** [comment]
I'll get to it later this week. It fits more generally into Nick's omnibus error audit.
