### ISSUE TITLE
acapy kills itself if it's not run in a shell where the TAA acceptance response can be typed via keyboard

### ISSUE THREAD

**Issue by Alexis-Falquier** [hyperledger/aries-cloudagent-python#529]
As the title says, when trying to run aca-py if the TAA cannot be accepted on startup via keyboard input it shuts down. Considering there is a way to accept the TAA via the admin API is there a way to make aca-py start without the TAA command line acceptance mechanism?

```
Transaction Endorser Data Processing Agreement
LINK
AS OF THE EFFECTIVE DATE OF THIS TRANSACTION AUTHOR AGREEMENT
(c) 2019 by Sovrin Foundation. This work is licensed under the Creative Commons
Attribution-ShareAlike 4.0 International License
(http://creativecommons.org/licenses/by-sa/4.0/).
Warning: Input is not to a terminal (fd=0).
Shutting down
```

**Comment by swcurran** [comment]
@andrewwhitehead - thoughts on this?

**Comment by swcurran** [comment]
AFAIK - ACA-Py is working fine with TAA. Closing this issue.
