### ISSUE TITLE
Error when constructing revocation state -Invalid len of bytes representation for PoingG2

### ISSUE THREAD

**Issue by RimAbdallah** [hyperledger/aries-cloudagent-python#532]
I am trying to present proof of a revoked credential, here is my proof presentation: 
```{
  "requested_attributes": {
    "additionalProp1": {
      "revealed": true,
      "cred_id": "d3d34e11-dc0c-4e0f-89c9-725d5fcbf13c"
    }
  },
  "trace": true,
  "requested_predicates": {
    "additionalProp1": {
      "cred_id": "d3d34e11-dc0c-4e0f-89c9-725d5fcbf13c"
    }}
  },
  "self_attested_attributes": {
    "additionalProp1": "self_attested_value"
  }
}```

My server response is the following : 
500 Internal Server Error

and the terminal indicates the following error : 
Error when constructing revocation state -Invalid len of bytes representation for PoingG2

**Comment by swcurran** [comment]
This issue was resolved with PR #531 --- please confirm or reopen if still an issue.

**Comment by msjeong482** [comment]
Maybe you may enter the wrong input.
Check a format 'additionalProp1' in attribute 'requested_predicates'.
See your proof presentation:
  "requested_attributes": {
    "additionalProp1": {
      "revealed": true,
      "cred_id": "d3d34e11-dc0c-4e0f-89c9-725d5fcbf13c"
    }
  },
  "trace": true,
  "requested_predicates": {
    "additionalProp1": {
      "cred_id": "d3d34e11-dc0c-4e0f-89c9-725d5fcbf13c"
    }} // **-- > Is this correct? not '}'?**
  },
  "self_attested_attributes": {
    "additionalProp1": "self_attested_value"
  }
}

**Comment by sklump** [comment]
For posterity:
Send GET /revocation/registry/{rev_reg_id}/tails-file to the issuer to download the tails file. Also, your proof request needs a non_revoked non-revocation interval as per https://github.com/hyperledger/indy-sdk/blob/6ecf3dded79fde74206ec0939d2dda179784768c/wrappers/python/indy/anoncreds.py#L1127.

**Comment by RimAbdallah** [comment]
thank you for your help

**Comment by hoannguyen26196** [comment]
i got same proplem. Could you show the solution more clearly ? Thank you for your help.

**Comment by RimAbdallah** [comment]
> i got same proplem. Could you show the solution more clearly ? Thank you for your help.

the reply of Mr sklump helped solve my problem. make sure you have created the revocation registry and updated the tails file via the issuer and your proof request have a non_revoked non-revocation interval. 

for more info -->  https://github.com/hyperledger/indy-sdk/blob/6ecf3dded79fde74206ec0939d2dda179784768c/wrappers/python/indy/anoncreds.py#L1127.

**Comment by hoannguyen26196** [comment]
i have created the revocation registry and updated the tails file via the issuer.  but i can not change non_revok.from and non_revoke.to. Their value are always is 1595499372.

**Comment by RimAbdallah** [comment]
the "1595499372" is a UNIX epoch you can use an online epoch converter to get the equivalent of the date you want.

> i have created the revocation registry and updated the tails file via the issuer. but i can not change non_revok.from and non_revoke.to. Their value are always is 1595499372.

**Comment by hoannguyen26196** [comment]
Thank you so much. You save my day.
