### ISSUE TITLE
Evolve the handling of revocation registries into ACA-Py and away from the controller

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#545]
The current ACA-Py implementation leaves a lot for the controller to do in managing the details of Indy revocation registries.  Define what can be done to reduce the effort on the controller and move more of that management into ACA-Py.

An initial very naive proposal is [here](https://hackmd.io/_BYKvL71T3W4ECele9BZuQ) that we can start from.  Feel free to add comments and update that document and/or add comments below.  We'll likely have a discussion on this -- no later than the ACA-Pug meeting this week (2020.06.10).

**Comment by swcurran** [comment]
@sklump -- would you be able to take this one?  I've updated the [HackMD document](https://hackmd.io/_BYKvL71T3W4ECele9BZuQ) based on recent conversations such as on the ACA-Pug call two weeks ago.  It would be really nice to get this done.

What do you think?

**Comment by sklump** [comment]
I can take this, probably starting in earnest the 2nd week of July.
