### ISSUE TITLE
No Signatures in credentials

### ISSUE THREAD

**Issue by MoSoltani** [hyperledger/aries-cloudagent-python#546]
Hello everybody,

when I send credentials to an endpoint and the status is stored in wallet i miss the signatures.

There is only listed fields are:

- referent
- schema_id
- cred_def_id
- rev_reg_id
- cred_rev_id

Thanks and regards,
Mohammad

**Comment by sklump** [comment]
The signatures are in the credential, not the metadata.

**Comment by sklump** [comment]
Once a credential is in the wallet, it does not leave the wallet. What you are seeing is a synopsis of the credential. The signatures are in the credential, in the wallet.

**Comment by MoSoltani** [comment]
Hi Stephan, 
Is there any possibility to read out the signatures?

**Comment by sklump** [comment]
No: Indy doesn't do that. You can present a proof.
