### ISSUE TITLE
Max. 10 stored credentials

### ISSUE THREAD

**Issue by MoSoltani** [hyperledger/aries-cloudagent-python#552]
Hi all,

when I issue credentials to someone up to the state "saved in Wallet" everything works fine till 10 credentials are saved. From the 10th one the new credentials get stored, but another one from the get automatically deleted. So the max credentials at the moment I can save are 10.

Anyone an idea? 
Regards,
Mohammad

**Comment by MoSoltani** [comment]
Update: 
When I then delete existing credentials, then it shows me again credentials which has been saved. So the credentials are not getting deleted. It would mean that the GET /credentials only fetch 10 records.

**Comment by MoSoltani** [comment]
I have found the problem. The standard seems to be 10 credentials. The API can get the "count" argument. But where can I change the standard?

**Comment by sklump** [comment]
Specify `count` URL parameter to deviate from the default.
