### ISSUE TITLE
ACA-PY support Readiness, Liveliness and Shutdown for OpenShift pod management

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#556]
Add endpoints for Readiness and Liveliness tests.

- Liveliness check should always return True and should be able to be handled at any time.
- Readiness check should return false until a (TBD) internal state where the instance is ready to accept requests from other agents or from the admin interface about things other than readiness and liveliness. 

Support shutdown signal from openshift or other source.  On receipt:

- update state so that the readiness endpoint return false.
- don't accept new work,
- ensure task queue is completed,
- Shut down

In considering this, assume the scenario where the ACA-Py instance is just 1 of n instances (possibly only 1) making up a service, and load balancer may be in front of the instances to distribute incoming requests from the controller to the set of instances.  This is the OpenShift/k8s scenario, but don't assume any k8s functionality - just respond to the requests using the internal state of the instance.

A controller could use the readiness endpoint to check if the instance is available for processing. In the k8s scenario, if any of the ACA-Py instances in the  service are available, then the service is available for processing requests.

**Comment by swcurran** [comment]
@sklump -- can you look at this one?  There are two unknowns with this related to the readiness endpoint.

1. At what point is an ACA-Py instance sufficiently operational that it can accept requests to be processed?
2. How to handle shutting down gracefully, as noted above.

Let me know if you need background on the OpenShift requirements for the two endpoints.

Let me know.
