### ISSUE TITLE
Can't make connection between faber demo and digital wallet

### ISSUE THREAD

**Issue by anhem115** [hyperledger/aries-cloudagent-python#566]
I'm trying to create the connection between the faber demo and my digital wallet Streetcred but there is some error when I tried to do that. 

I'm using the `http://test.bcovrin.vonx.io/` for the ledger

# First: I started my ngrok for the faber agent at port 8021:
```ngrok http http://localhost:8021```
# Then I run the faber demo with the agent endpoint
```AGENT_ENDPOINT=http://b72cd1316825.ngrok.io LEDGER_URL=http://test.bcovrin.vonx.io ./run_demo faber --no-auto --events```
# The following invitation object is generated:
```{"@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/invitation", "@id": "a70bd033-7c04-4fe9-9810-33c3078be769", "serviceEndpoint": "http://b72cd1316825.ngrok.io", "recipientKeys": ["8Rzm91BsoHbnxCDeUiGiDTZpq94nVbFydqzyiRPi6W6u"], "label": "Faber.Agent"}```
# I scanned the code with my Streetcred, it displays the invitation to connect. However, when I selected "Connect", I got the following error:
![image](https://user-images.githubusercontent.com/11781639/85161421-55b9de80-b225-11ea-96b3-71678c893584.png)

# I could be able to access swagger api doc from the ngrok link though.
![image](https://user-images.githubusercontent.com/11781639/85161473-6b2f0880-b225-11ea-971a-420752cbca69.png)

Any help is appreciated.

**Comment by WadeBarnes** [comment]
Make sure the mobile app is connected to the *Bcovrin Test Network* in the settings.

**Comment by anhem115** [comment]
Yeah, I'm sure that it connects to the Bcovrin Test Network, otherwise I will message like Network mismatch

**Comment by anhem115** [comment]
Sorry, it's my bad, I use the ngrok for the wrong endpoint, I should create ngrok for the Inbound  port not the Administrative port.
