### ISSUE TITLE
Check for storage_config and storage_credentials are in proper escaped JSON format

### ISSUE THREAD

**Issue by msembinelli** [hyperledger/aries-cloudagent-python#569]
This is in reference to #568 

I think it would be a huge timesaver to people working with k8 yaml files to deploy acapy if the postgres plugin intialization code did some check to see that the `storage_config` and `storage_credentials` passed in are in the proper format (escaped JSON string) before calling out to the static library. The error returned on bad parameters is error `210` and that doesn't give a good indication of what is going wrong.

```
E 2020-06-19T22:22:14.452583499Z 2020-06-19 22:22:14,452 aries_cloudagent.wallet.provider INFO Opening wallet type: indy
 
E 2020-06-19T22:22:14.461212446Z 2020-06-19 22:22:14,461 aries_cloudagent.wallet.plugin INFO Initializing postgres wallet
 
E 2020-06-19T22:22:14.478151798Z 2020-06-19 22:22:14,476 aries_cloudagent.wallet.plugin ERROR **Error unable to configure postgres stg: 210**
```

The proper format needs to end up resolving to the following on command line for `aca-py start`
```
--wallet-storage-config "{\"url\":\"localhost:5432\",\"wallet_scheme\":\"MultiWalletSingleTable\"}"
```
This also applies to `--wallet-storage-creds`

A fix can be added right in this code `aries_cloudagent/wallet/plugin.py`
```
def load_postgres_plugin(storage_config, storage_creds, raise_exc=False):
    """Load postgres dll and configure postgres wallet."""
    global LOADED, LOGGER

    if not LOADED:
        LOGGER.info("Initializing postgres wallet")
        stg_lib = cdll.LoadLibrary("libindystrgpostgres" + file_ext())
        result = stg_lib.postgresstorage_init()
        if result != 0:
            LOGGER.error("Error unable to load postgres wallet storage: %s", result)
            if raise_exc:
                raise OSError(f"Error unable to load postgres wallet storage: {result}")
            else:
                raise SystemExit(1)
        if "wallet_scheme" in storage_config:
            c_config = c_char_p(storage_config.encode("utf-8"))
            c_credentials = c_char_p(storage_creds.encode("utf-8"))
            result = stg_lib.init_storagetype(c_config, c_credentials)
            if result != 0:
                LOGGER.error("Error unable to configure postgres stg: %s", result)
                if raise_exc:
                    raise OSError(f"Error unable to configure postgres stg: {result}")
                else:
                    raise SystemExit(1)
        LOADED = True

        LOGGER.info("Success, loaded postgres wallet storage")
```

In addition, the argparse documentation should be updated to note fields such as `wallet_scheme` and discuss `admin_account` user requiring CREATEDB permissions.

**Comment by msembinelli** [comment]
Will try and submit a PR for this soon.

**Comment by darapich92** [comment]
Hi @msembinelli , I created the wallet via ACA-Py but it got an error message. I think it is related to the JSON format. After I fixed it based on your recommendation, I still got an error message. 
Here is my command of issuing the wallet: 
`sudo PORTS="8000:8000 8001:8001" ./run_docker start \
  --outbound-transport http \
  --inbound-transport http 0.0.0.0 8000 \
  --endpoint http://localhost:8000/ \
  --genesis-url https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_sandbox_genesis \
  --wallet-type indy \
  --wallet-name Issuer \
  --wallet-key secret \
  --wallet-storage-type postgres_storage \
  --wallet-storage-config "{\"url\":\"localhost:5432\",\"wallet_scheme\":\"MultiWalletSingleTable\"}" \
  --wallet-storage-creds "{\"account\":\"postgres\",\"password\":\"mysecretpassword\",\"admin_account\":\"postgres\",\"admin_password\":\"mysecretpassword\"}" \
  --log-level info`

this is the result message:

`2023-01-02 13:13:05,439 aries_cloudagent.core.profile INFO Create profile manager: indy
2023-01-02 13:13:05,465 aries_cloudagent.indy.sdk.wallet_plugin INFO Checking input postgres storage_config and storage_creds arguments
2023-01-02 13:13:05,465 aries_cloudagent.indy.sdk.wallet_plugin INFO Initializing postgres wallet
2023-01-02 13:13:05,491 aries_cloudagent.indy.sdk.wallet_plugin ERROR Error unable to configure postgres stg: 210
2023-01-02 13:13:05,528 asyncio ERROR Task exception was never retrieved
future: <Task finished coro=<run_loop.<locals>.init() done, defined at /home/indy/aries_cloudagent/commands/start.py:69> exception=SystemExit(1,)>
Traceback (most recent call last):
`
Can you give an idea to solve it? thank you very much!
