### ISSUE TITLE
Aries OpenAPI Demo Issue

### ISSUE THREAD

**Issue by muhammadusman93** [hyperledger/aries-cloudagent-python#57]
In Issuing a Credential section, the demo instructions asks to following

**_Next, scroll down to the POST /credential-definitions section that was executed in the previous step._**

However, the document never asked to execute the POST/ credential-definitions. Kindly check . 

Thanks.

**Comment by ianco** [comment]
Thanks for the feedback!

This is fixed in https://github.com/hyperledger/aries-cloudagent-python/pull/58

**Comment by muhammadusman93** [comment]
Thanks for the quick reply. 

I also changed the "p_value":  18 to "p_value":  180 in requesting a proof. 
I cannot see a difference as both of these show "state": "presentation_received".

Thanks.

**Comment by ianco** [comment]
Try to validate the proof and see what happens!
