### ISSUE TITLE
Store/Backup wallet after stopping Container

### ISSUE THREAD

**Issue by MoSoltani** [hyperledger/aries-cloudagent-python#575]
Hi all,

after stopping the container for Alice or other users and restart the container a new wallet is created, so all the received credentials and created connections are not more available.

Is there any possibility to backup the wallet and restore it in the container?

Thanks and regards,
Mohammad

**Comment by markwormgoor** [comment]
It is possible. I'm not using the demo, but have built my own docker container. An example from my docker YAML file is below. Notice the "wallet-storage-config" option on the command line and the volumes at the bottom. The first tells Indy where to store its wallets. The second tells Docker to mount the ./data/wallets folder under /data in Docker.

Of course, most people would use Postgres as their database engine, but for my development setup, the below is sufficient. It should be doable to also do this for the demo's (but haven't looked at those specifically).

```
    command: |
      start --endpoint http://127.0.0.1:8060
      --inbound-transport http 0.0.0.0 8060
      --outbound-transport http
      --admin 0.0.0.0 8061
      --admin-insecure-mode
      --label cloudwallet.dev
      --genesis-url http://localhost/genesis
      --wallet-type indy
      --wallet-storage-type default
      --wallet-storage-config '{ "path":"/data" }'
      --wallet-name cloudwallet.dev761055
      --wallet-key cloudwallet.dev761055
      --preserve-exchange-records
      --auto-provision
      --log-level info
    volumes:
      - ./data/wallets:/data
```

**Comment by swcurran** [comment]
Closing issue - please reopen if necessary.
