### ISSUE TITLE
Add option to protect webhook endpoint with api-key

### ISSUE THREAD

**Issue by esune** [hyperledger/aries-cloudagent-python#578]
The `WEBHOOK_URL` used by aca-py to talk back to the controller doesn't have many options to add security.

The only way to secure the webhook endpoint currently is to add path-based security to the url (adding the api-key to the URL).
A more common and secure way would be to support adding an api-key to the request headers targeting the `WEBHOOK_URL`.

**Comment by swcurran** [comment]
@esune -- is this still relevant?  Priority?

**Comment by esune** [comment]
@shaangill025 fixed this a couple of months back, we can close it!
