### ISSUE TITLE
About the tag in credential definition

### ISSUE THREAD

**Issue by anhem115** [hyperledger/aries-cloudagent-python#591]
Scenario:
  I successfully created a credential definition A (in both ledger and wallet). I lost my agent wallet (accidentally deleted), so I recreated my agent DID from my seed. And because the credential definition can't be recovered, so I have to add a different tag (not the `default` tag) to create another credential definition? Otherwise I will get the error: 

```
                        raise LedgerError(
                            f"Credential definition {credential_definition_id} is on "
                            f"ledger {self.pool_name} but not in wallet "
                            f"{self.wallet.name}"
                        )
```

because the the credential definition id is generated by the following structure:
```
        "{origin_did}:3:{signature_type}:{str(schema['seqNo'])}:{tag}"
```
So I guess I need to use a different `tag` value here to recreate a credential definition from my old wallet DID?

**Comment by sklump** [comment]
The old cred def is garbage once the private key controlling it is lost. A new cred def needs a new identifier - since everything else is the same, you must use a new tag.

**Comment by anhem115** [comment]
Thank you for clarifying!
