### ISSUE TITLE
ACA-Py Admin API requiring JSON data for credential preview on issue and store when cred_ex_id is already given.

### ISSUE THREAD

**Issue by nodlesh** [hyperledger/aries-cloudagent-python#594]
### Issue

Using the ```issue``` and ```store``` operations on the ACA-Py admin API, one would expect that the credential preview or any other credential data is not needed to pass to the operation. This is because the protocol has already been established by the send-offer, and the credential can then be referenced with the credential exchange id (cred_ex_id).  The ```issue``` operation requires a full credential_preview including attributes. This is unnecessary. The ```store``` operation requires the cred_exl_id in the JSON body, even though that id is already sent as part of the URL.

### Steps to Reproduce

Scenario: Issue a credential with the Holder beginning with a proposal
```
    Given "2" agents
      | name  | role   |
      | Acme  | issuer |
      | Bob   | holder |
    And "Acme" and "Bob" have an existing connection
    When "Bob" proposes a credential to "Acme"
    And "Acme" offers a credential
    And "Bob" requests the credential
    And "Acme" issues the credential <- uses "issue" operation
    And "Bob" acknowledges the credential issue <- uses "store" operation
    Then "Bob" has the credential issued
```

### Outcome

Operation is successful but data not needed. 
When debugging a test because of a problem, having that JSON data as part of the call just adds one more variable to the possible issues for debugging. Removing the JSON would make debugging easier. 
Implementation would also be easier not having to construct that JSON body.

### Expected Outcome

Operations successful without any JSON body, and just the cred_ex_id on the URL.

### Workaround

Pass in the JSON data as the API expects. 

### Test Cases Affected

T001-API10-RFC0036, T002-API10-RFC0036, T003-API10-RFC0036, T004-API10-RFC0036

### Severity

Low

### Business Priority

Medium

**Comment by nodlesh** [comment]
@swcurran Added this issue, but I don't have the privileges to add a ```bug``` or ```enhancement``` tags.

**Comment by sklump** [comment]
I can take this.

**Comment by swcurran** [comment]
Thanks @sklump. I think the it should be possible to pass the data on this, just not required.  Is that how you see it?

**Comment by sklump** [comment]
No: the credential values are necessarily what was on offer or else a bait-and-switch is possible from a shady issuer.

**Comment by sklump** [comment]
Since we now (correctly) insist on putting them in the offer, we should have removed them at that time from the issue. Clear?

**Comment by swcurran** [comment]
I'm going to post to the community about.  The scenario I worry about is if/when we support other than Indy credentials that we'll need the data back.

**Comment by sklump** [comment]
Sure, at that time we can add it in as an option.

**Comment by sklump** [comment]
I expect that will be in about half a world war, and by then we will not be on v1.0 of the protocol.

**Comment by sklump** [comment]
https://github.com/hyperledger/aries-cloudagent-python/pull/596
