### ISSUE TITLE
Update/Revoke for a credential

### ISSUE THREAD

**Issue by anhem115** [hyperledger/aries-cloudagent-python#603]
Scenario:
I have issued a credential to user. Then users want to update a field in their data (e.g. home address), so I will issue a new credential with their new home address, but I also have to revoke their old credential. 

Currently, I need both `rev_reg_id` and `revocation_id` to revoke a credential. I could get the `rev_reg_id` from the response of the proof request, but I don't know where could I check for their `revocation_id`? I could get the `revocation_id` only when I issue a credential but not from the presentation response.

**Comment by sklump** [comment]
The old credential has a cred_rev_id field. Also, the issuer in aca-py returns it when it creates the credential; the controller is supposed to store the rev reg id and cred rev id on issue.

**Comment by swcurran** [comment]
FYI - the team is currently working on making the handling of this much easier for the controller -- should be ready on the main branch in the next few days.  @sklump has nailed it though that it is the responsibility of the controller to keep the data from the issue event so that the the controller can trigger the revocation via the admin API.

**Comment by anhtranEH** [comment]
If the controller has to manage the revocation id, I"m not sure whether I could retrieve a revocation_id from the presentation_exchange_id which I received from my wallet? Or anything from the response of my wallet?

**Comment by sklump** [comment]
1) it's  credential exchange you're after, not a presentation exchange
2) by default the credential exchange gets purged as soon as the holder accepts and acks the credential
3) the issuer revokes in any case, not the holder: if the issuer retained credential exchange records (which include credentials) then it would violate the W3C credential role design: holders hold, issuers issue, verifiers verify.
4) the holder cannot be relied upon to volunteer credential metadata for revocation: the holder could be reluctant, or incommunicado

**Comment by anhtranEH** [comment]
Thank for the clarification, so the issuers should not hold any credential exchange record, but they will store the revocation id for each issued credential? Im still a bit unclear about my scenario, after my users prove themselves with the credential, they wants to update their information (update their credential). I could easily issue a new credential, but I cant determine which revocation id will be used for the revocation for the old credential (given that I did store all the revocation id when issued). Do you have any suggestions for that?

**Comment by swcurran** [comment]
When your controller issues the first credential, it will need to store the necessary information to revoke the credential with the data you keep about the entity to whom you issued the credential. When you need to reissue the credential to that entity, you revoke the existing credential and issue a new one.

**Comment by anhem115** [comment]
Thank you for the clarification. This is actually what I will implement to
determine the correct revocation id. But I wonder whether it could create
any correlation since I will store it as a tuple of (revocation_id,
[user_info]), so next time the user send the presentation, I could match
these data with the [user_info].

**Comment by swcurran** [comment]
This does not create correlation across verifiers.  The revID is only known to the issuer and the holder.  The holder proves to the verifier that their credential is not revoked without sharing the revID (a unique identifier) to the verifier.  The issuer and the holder know, but that's a given - by definition they have to know that information for revocation to work at all.

**Comment by anhtranEH** [comment]
Thank @sklump and @swcurran a lot for your answer. There is no risk of correlation between issuer and holder as that's a given for the revocation to work. The risk of correlation is a term for verifiers only.

**Comment by swcurran** [comment]
Good stuff.  BTW - to be a little more precise the "proof of non-revocation" is a zero knowledge proof, hence the no sharing of the revocation ID.
