### ISSUE TITLE
Enhancement - Add optional seed parameter to /wallet/did/create

### ISSUE THREAD

**Issue by Sarangc1203** [hyperledger/aries-cloudagent-python#606]
#50 asked about having an API to generate a DID - from a random seed. #178 added a ledger endpoint for nym registration. So when trying to implement an onboarding system for most of the use cases, it would be logical to give an option to generate DID by using a seed. 

Use case:
An organization that did not choose to register its DID when it started the agent, in future, may want to register its DID. Now since we have an option to generate the DID from seed (at the time of firing up the agent), I would expect that I get a similar option through `/wallet/did/create` afterward too.  That organization will generate its public DID by using a specific seed. And then ask the TRUSTEE or STEWARD to register its DID using `/ledger/register-nym`.

Possible solution:
For the `/wallet/did/create`, take an optional input for seed (which when not provide will generate random DID). The fix seems simple enough. In [routes.py](https://github.com/hyperledger/aries-cloudagent-python/blob/1b7d209cc70f01593c5c78be512af00c2cc1c9a8/aries_cloudagent/wallet/routes.py#L170), create_local_did() is called without any parameters. But [basic.py](https://github.com/hyperledger/aries-cloudagent-python/blob/1b7d209cc70f01593c5c78be512af00c2cc1c9a8/aries_cloudagent/wallet/basic.py#L192) supports a 'seed' parameter.

**Comment by swcurran** [comment]
The devs will likely chime in, but this shouldn't be done because this is the equivalent of sending a private key over an HTTP connection.  Reasonable to do on a sandbox test network, but a very bad idea in production.

**Comment by sklump** [comment]
The admin API purposefully leaves seeds off the wire, exactly as @swcurran writes.
