### ISSUE TITLE
Network mismatch error

### ISSUE THREAD

**Issue by anhem115** [hyperledger/aries-cloudagent-python#607]
Scenario:
1) I have issued a credential with revocation support to my Identity wallet:
  create credential definition, create revocation registry, get the tail file, update the tail file url, publish it to `test.bcovrin.vonx.io`, also update that tail file url at the indy-tail-ledger successfully, and issued the credential to my wallet. 
2) Then I make a simple proof request to my wallet, when I presented the proof, I keep getting the error Network Mismatch on the Streetcred (Trinsic wallet) and I can't do anything further. I'm sure that the network is correct (Bcovrin test) because:
    - I could check every Credential definition, Credention revocation registry, tail file url in step 1 at `http://test.bcovrin.vonx.io/` by the time I tried that. 
    - I could issued the credential successfully which means the network is correct
    - I could upload the tail file at indy-tail-server successfully which mean it retrieved the hash from the Bcovrin ledger

Do you have any idea what would cause this error because it doesn't look like network mismatch here.

**Comment by WadeBarnes** [comment]
@esune, This is a known issue; correct?  Do you have some details you could provide?

**Comment by anhem115** [comment]
I have just found the reason, I used the wrong timestamp in the proof
request! I used an old timestamp instead of getting the current timestamp.
For example:

{
  requested_attributes: ...
  non_revoked: {
    to: 12345, --> should be current timestamp
  }
}

**Comment by swcurran** [comment]
Good stuff - closing.
