### ISSUE TITLE
Open API Aries Faber Alice Demo

### ISSUE THREAD

**Issue by SmithSamuelM** [hyperledger/aries-cloudagent-python#61]
I am able to run the demo using docker playground up until the send credential step
On the Faber tab
The connection id is from the get_connection on the faber tab
The cred_definition is the CRED_DEF Transaction ID
The credential body

```son
{
  "connection_id": "6c3e48e6-1d9a-4803-a20e-2117dd6ad842",
  "credential_definition_id": "6qnvgJtqwK44D8LFYnV5Yf:3:CL:9:tag",
  "credential_values": {"name": "Alice Smith", "date": "2018-05-28", "degree": "Maths", "age": "24"}
}
```

request url
http://ip10-0-55-4-bkjn6p15do8g14edjijg-8021.direct.play-with-von.vonx.io/credential_exchange/send

The response returns an error

500 Internal Server Error

Server got itself in trouble

I tried the steps a couple of times with the same results.
Any suggestions of what is wrong?

**Comment by SmithSamuelM** [comment]
I was able to get the demo to work using docker not docker playground. So there might be a bug in the docker playground setup or something.

**Comment by pshannigan** [comment]
Hi

I've been having trouble geting the demo to work on a Ubuntu virtual box, I've installed Docker CE successfully and followed the instructions but the scripts fail to compile.  Could you give me some details on how you accomplished it within docker as I am struggling.

**Comment by swcurran** [comment]
I'm on Ubuntu and just ran through it and all worked.  Can you please post where you ran into trouble.  I was following the instructions here:

https://github.com/hyperledger/aries-cloudagent-python/blob/master/demo/AriesOpenAPIDemo.md
