### ISSUE TITLE
"state" of credential should be updated once revoked

### ISSUE THREAD

**Issue by Howlla** [hyperledger/aries-cloudagent-python#617]
The "state" of credential after GET `issue-credentials/records/` remains `credential_acked`even after revocation.
This should be updated to "revoked" to help improve useability.

**Comment by sklump** [comment]
Typical operation is to purge cred ex records after issue. You should not keep these around unless you are debugging: they contain raw credentials that are meant to be the property of the holder, in the holder wallet. Therefore by revocation time, they ought not exist to have any state.

**Comment by swcurran** [comment]
Further - the holder need not be notified of the revocation.  There is not a good way defined in Aries to inform the Holder that their credential has been revoked.  There is a proposed protocol for that, but little conversation about it in the community.  That will come as we start to use revocation more and more.

**Comment by swcurran** [comment]
Good discussion, but closing this to keep the volume of issues down.

**Comment by naman20sharma** [comment]
> Further - the holder need not be notified of the revocation. There is not a good way defined in Aries to inform the Holder that their credential has been revoked. There is a proposed protocol for that, but little conversation about it in the community. That will come as we start to use revocation more and more.

Hi, was there any updates pertaining to this ? 
I was wondering, if Holder's state doesn't change to `credential_revoked`, then the Proof requested presented by the Holder would be successfully verified. At least that's what happened, when I tried post revocation of a credential.
