### ISSUE TITLE
Non-indy tests fail

### ISSUE THREAD

**Issue by nrempel** [hyperledger/aries-cloudagent-python#626]
Several non-indy tests are failing

**Comment by sklump** [comment]
Oh! I had thought the indy tests were a superset, all this time.

**Comment by nrempel** [comment]
I thought so too. The failing tests are run in both suites but were only failing in the non-indy tests. I'm not sure why exactly but I had to make some large-ish modifications to the way imported modules were being mocked to get them to run.
