### ISSUE TITLE
Update tails server documentation and test on PWD

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#642]
Update docs here:

https://github.com/hyperledger/aries-cloudagent-python/blob/master/demo/AliceGetsAPhone.md

Also update run_demo script to remove any env vars that are no longer used

Also test with tails server on PWD and issuing to mobile with revocation

**Comment by ianco** [comment]
Also review demo code to remove any unused env vars, for example in:

https://github.com/hyperledger/aries-cloudagent-python/blob/master/demo/runners/support/agent.py#L213

**Comment by ianco** [comment]
This code in the `run_demo` script auto-detects the ngrok name of the tails server, and doesn't work with the latest changes:

https://github.com/hyperledger/aries-cloudagent-python/blob/master/demo/run_demo#L212

**Comment by swcurran** [comment]
@ianco - status of this?
