### ISSUE TITLE
Revoked credential

### ISSUE THREAD

**Issue by guilherme-funchal** [hyperledger/aries-cloudagent-python#650]
What changes in credentials after being revoked? How can I test if it is revoked?

**Comment by sklump** [comment]
The issuer updates an accumulator on the ledger to include the credentials revocation identifier.

Proof of non-revocation as of a timestamp is part of the proof of credential ownership. To prove ownership and non-revocation, the verifier sends a proof request with a non-revocation interval and the holder creates a proof on a timestamp within that interval. The proof verifies only if the credential is not revoked at that timestamp.

**Comment by swcurran** [comment]
Closing this as additional capabilities are available for dealing with revocation. And it really should be the controller that is tracking issued credentials that are revoked.
