### ISSUE TITLE
API to query the current role of our agent

### ISSUE THREAD

**Issue by Sarangc1203** [hyperledger/aries-cloudagent-python#652]
It would be beneficial from the controller's point of view to know what the my role (corresponding the current set public DID) is so that we can separate out application specific functionalities according to them.

**Comment by swcurran** [comment]
What set of roles are you talking about?

**Comment by Howlla** [comment]
I think roles refer to "Steward", "Endorser", "Trustee" etc.

**Comment by swcurran** [comment]
That would mean there would be a need to include the public DID being referenced, as there is not the concept of the agent having "a DID'.  Is there an existing admin API point related to DIDs that could be used?

I would add that if a peer DID is submitted the result could be "Peer".

**Comment by sklump** [comment]
There's a `register-nym()` but we have no corresponding `get-nym()` taking a public DID. I could put it on the list.

**Comment by sklump** [comment]
https://github.com/hyperledger/aries-cloudagent-python/pull/671
