### ISSUE TITLE
ERR:Tails file failed to upload: Payment Required

### ISSUE THREAD

**Issue by zbbgit** [hyperledger/aries-cloudagent-python#655]
when test the demo(https://github.com/hyperledger/aries-cloudagent-python/blob/master/demo/AliceGetsAPhone.md#run-an-instance-of-indy-tails-server)，run the cmd (TAILS_NETWORK=docker_tails-server LEDGER_URL=http://test.bcovrin.vonx.io ./run_demo faber --revocation --events),  there is a Exception: Error: 500: Tails file failed to upload: Payment Required,

why and how to solve ，thanks ！

Faber      | Revocation registry: f9b7280c-4e4b-4c41-911b-3b1633ce001b state: active
Faber      | 2020-08-07 01:53:16,407 aries_cloudagent.admin.server ERROR Handler error with exception: Tails file failed to upload: Payment Required
Faber      |
Faber      | Shutting down
Faber      | Exited with return code 0
Traceback (most recent call last):
  File "/home/indy/demo/runners/support/agent.py", line 437, in admin_request
    resp.raise_for_status()
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 500, message='Tails file failed to upload: Payment Required', url=URL('http://172.24.205.86:8021/credential-definitions')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/indy/demo/runners/faber.py", line 462, in <module>
    args.timing,
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/indy/demo/runners/faber.py", line 195, in main
    revocation_registry_size=TAILS_FILE_COUNT,
  File "/home/indy/demo/runners/support/agent.py", line 196, in register_schema_and_creddef
    "/credential-definitions", credential_definition_body
  File "/home/indy/demo/runners/support/agent.py", line 471, in admin_POST
    response = await self.admin_request("POST", path, data, text, params)
  File "/home/indy/demo/runners/support/agent.py", line 440, in admin_request
    raise Exception(f"Error: {resp_text}") from e
Exception: Error: 500: Tails file failed to upload: Payment Required

**Comment by swcurran** [comment]
OK - I'm dying to know about this one -- "payment required"???  @nrempel ?

**Comment by nrempel** [comment]
@zbbgit Can you share the logs from the running instance of `indy-tails-server`?

**Comment by zbbgit** [comment]
root@iZ2vcekg07cyl1x0potmotZ:~/rev-reg-demo/indy-tails-server/docker# ./manage start
Starting docker_ngrok-tails-server_1 ...
Starting docker_tails-server_1 ... done
Attaching to docker_ngrok-tails-server_1, docker_tails-server_1
ngrok-tails-server_1  | t=2020-08-10T01:02:01+0000 lvl=info msg="no configuration paths supplied"
ngrok-tails-server_1  | t=2020-08-10T01:02:01+0000 lvl=info msg="using configuration at default config path" path=/home/ngrok/.ngrok2/ngrok.yml
ngrok-tails-server_1  | t=2020-08-10T01:02:01+0000 lvl=info msg="open config file" path=/home/ngrok/.ngrok2/ngrok.yml err=nil
ngrok-tails-server_1  | t=2020-08-10T01:02:01+0000 lvl=info msg="starting web service" obj=web addr=0.0.0.0:4040
tails-server_1        | ======== Running on http://0.0.0.0:6543 ========
tails-server_1        | (Press CTRL+C to quit)
ngrok-tails-server_1  | t=2020-08-10T01:02:03+0000 lvl=info msg="tunnel session started" obj=tunnels.session
ngrok-tails-server_1  | t=2020-08-10T01:02:03+0000 lvl=info msg="client session established" obj=csess id=1bf2a44ab644
ngrok-tails-server_1  | t=2020-08-10T01:02:03+0000 lvl=info msg="started tunnel" obj=tunnels name="command_line (http)" addr=http://tails-server:6543 url=http://3a3438219804.ngrok.io
ngrok-tails-server_1  | t=2020-08-10T01:02:03+0000 lvl=info msg="started tunnel" obj=tunnels name=command_line addr=http://tails-server:6543 url=https://3a3438219804.ngrok.io

**Comment by nrempel** [comment]
Can you post logs from the tails server that include a reproduction of the error? I haven't been able to reproduce this error.

I'm thinking there might be some wires crossed when you run the demo. The error shows the agent's port as 8021 (`'http://172.24.205.86:8021/credential-definitions`) but the demo instructions have the agent running on port 8020. 

Can you try and restart docker or use `docker kill` to kill all running docker containers and start again?

**Comment by zbbgit** [comment]
> Can you post logs from the tails server that include a reproduction of the error? I haven't been able to reproduce this error.
> 
> I'm thinking there might be some wires crossed when you run the demo. The error shows the agent's port as 8021 (`'http://172.24.205.86:8021/credential-definitions`) but the demo instructions have the agent running on port 8020.
> 
> Can you try and restart docker or use `docker kill` to kill all running docker containers and start again?


Thanks，solve the problem by restart docker。

**Comment by swcurran** [comment]
One more thought.  Are we returning a 402 HTTP status anywhere?  I found that can mean payment requirement.  I couldn't see anything in the code, but wondered if that was used somewhere.

**Comment by nrempel** [comment]
No, we don't use that code anywhere.
