### ISSUE TITLE
Update the "About" for this repo

### ISSUE THREAD

**Issue by lynnbendixsen** [hyperledger/aries-cloudagent-python#665]
The 'About' comment for this repo is confusing. 
"Hyperledger Aries Cloud Agent Python (ACA-Py) is a foundation for building decentralized identity applications and services running in non-mobile environments."

The 'non-mobile' part is confusing, or inaccurate. please rewrite.

**Comment by swcurran** [comment]
I'm not sure what is confusing about it.  ACA-Py is not appropriate (AFAWK) for use as a mobile agent.  Thus, it is appropriate for any non-mobile use.

**Comment by lynnbendixsen** [comment]
I see your perspective and understand it better now, thanks. My perspective was that of recently reviewing a document describing how ACA-Py can be used as a Mediator Agent. Looking at the bigger picture, in a mobile app "environment" a Mediator agent "service" is required for communication between the mobile agent and other edge agents.
