### ISSUE TITLE
GET /schemas/created returns duplicates even though they aren't on ledger after multiple POST /schemas

### ISSUE THREAD

**Issue by jcourt562** [hyperledger/aries-cloudagent-python#678]
Version: 0.5.3
Expected Results:  The GET /schemas/created should NOT return duplicates if they don't exist on the ledger.

Description: I am able to use POST /schemas with the same schema_name and schema_version attributes and using the same DID.  The second attempt does NOT get put on the ledger and I believe that ACA-py is receiving an error on the second attempt but it returns 200.  This is defensible and the same result as creating a duplicate credential definition.  However a subsequent GET /schemas/created returns multiple instances of the schema even though only one exists on the ledger. Doing this "N" times results in "N" schema_ids returned from GET /schemas/created.  Below is an example of the incorrect GET response.

{
  "schema_ids": [
    "FfTM7q3uZLipmQnXjghcbZ:2:University_Transcript:0.1",
    "FfTM7q3uZLipmQnXjghcbZ:2:University_Transcript:0.1"
  ]
}

**Comment by esune** [comment]
This seems to still be occurring on the `0.5.4` release.

**Comment by sklump** [comment]
If the wallet predates PR#682, the extra records will be there for keeps
