### ISSUE TITLE
incompatible shell 

### ISSUE THREAD

**Issue by dongwangdw** [hyperledger/aries-cloudagent-python#69]
I try to run through the docs. when to run `run_tests`, I got the error:

```./scripts/run_tests: [[: not found```

As I found the in the script that this shell script just uses `sh` not `bash`. And `[[ ... ]]` is not good. I would advise to the syntax consistent.

My os is: ubuntu 18.04, bash and amd64. Is this anything which should be fixed?

**Comment by swcurran** [comment]
Definitely should be bash. Will need to address this.

**Comment by dongwangdw** [comment]
Yes, I think so. Let me make a pr for this.

**Comment by swcurran** [comment]
FYI - here is the low down on single vs. double square braces in bash:

https://stackoverflow.com/questions/13542832/difference-between-single-and-double-square-brackets-in-bash

We should be using just a single `[` in the scripts and definitely all should be running bash only.  If it works with other shells, that's good, but bash is the target.

I'm going to update the demo script (./run_demo in the demo folder), but the rest should be addressed as well.

**Comment by dongwangdw** [comment]
@swcurran 
I have composed a patch for this. If you did not do it, let me do this.

**Comment by swcurran** [comment]
Sure - go for it.  Thanks!  @dongwangdw

**Comment by dongwangdw** [comment]
https://github.com/hyperledger/aries-cloudagent-python/pull/72

**Comment by nrempel** [comment]
Thank you @dongwangdw! The patch has been merged and is available in the latest release.
