### ISSUE TITLE
Issue with --auto flags when sending proof proposal and having multiple credentials of the same type in the wallet

### ISSUE THREAD

**Issue by etschelp** [hyperledger/aries-cloudagent-python#704]
I do not know if this is a bug or simply something where aca-py's api behaves a bit unclear.

Given i have the following two credentials in my wallet, and both are based on the same schema and credential definition.

**GET /credentials**
```
{
  "results": [
    {
      "referent": "4ebbc6be-8cb2-4c1c-bd3e-77fc45d89647",
      "attrs": {
        "bic": "xxx",
        "iban": "yyy"
      },
      "schema_id": "M6Mbe3qx7vB4wpZF4sBRjt:2:bank_account:1.0",
      "cred_def_id": "M6Mbe3qx7vB4wpZF4sBRjt:3:CL:571:bank_account_no_revoc",
      "rev_reg_id": null,
      "cred_rev_id": null
    },
    {
      "referent": "72301763-D077-4A8F-9BC6-4613A612D4E8",
      "attrs": {
        "bic": "vvv",
        "iban": "zzz"
      },
      "schema_id": "M6Mbe3qx7vB4wpZF4sBRjt:2:bank_account:1.0",
      "cred_def_id": "M6Mbe3qx7vB4wpZF4sBRjt:3:CL:571:bank_account_no_revoc",
      "rev_reg_id": null,
      "cred_rev_id": null
    }
  ]
}
```
And my agent is configured with all the --auto flags enabled, and I want to send a proof presentation proposal like:

**POST /present-proof/send-proposal**
```
{
  "connection_id": "91992d99-c12d-426f-9b9d-de42b6c56b86",
  "presentation_proposal": {
    "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/present-proof/1.0/presentation-preview",
    "attributes": [
      {
        "name": "bic",
        "value": "xxx",
        "cred_def_id": "M6Mbe3qx7vB4wpZF4sBRjt:3:CL:571:bank_account_no_revoc",
        "referent": "4ebbc6be-8cb2-4c1c-bd3e-77fc45d89647"
      },
      {
        "name": "iban",
        "value": "yyy",
        "cred_def_id": "M6Mbe3qx7vB4wpZF4sBRjt:3:CL:571:bank_account_no_revoc",
        "referent": "4ebbc6be-8cb2-4c1c-bd3e-77fc45d89647"
      }
    ],
    "predicates": []
  }
}
```
The exchange fails and I see the following in the logs:

```
2020-09-02 09:22:34,613 aries_cloudagent.core.conductor ERROR Exception in message handler:
Traceback (most recent call last):
File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/core/dispatcher.py", line 178, in handle_message
await handler(context, responder)
File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/present_proof/v1_0/handlers/presentation_request_handler.py", line 97, in handle
holder=await context.inject(BaseHolder),
File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/protocols/present_proof/v1_0/util/indy.py", line 54, in indy_proof_req_preview2indy_requested_creds
name = indy_proof_request["requested_attributes"][referent]["name"]
KeyError: 'name'
```

If either credential is removed the call succeeds. The problem seems to be that the _referent_ information is lost in the exchange between the agents and aca-py does not know which credential to pick and hence fails (as this happens in the _request_received_ state).

**Comment by sklump** [comment]
I'll get deeper into this late in the week. It should be fixable.

**Comment by sklump** [comment]
In this context, the referent in the proposal does not mean the cred id in the wallet: https://github.com/sklump/aries-rfcs/tree/master/features/0037-present-proof#referent

The two referents here, if both the same, would specify to use the same single credential to provide both attributes. In this case, since both are the same, it looks like it should have found the matching credential. I'll keep looking into it.

**Comment by sklump** [comment]
Yep, it's a bug, to do with what the proof req looks like when it specifies "names" on a single credential rather rather than "name". I should be able to fix it in the next day or so.
