### ISSUE TITLE
Failure to publish revocation registry "breaks" credential definition revocation functionality

### ISSUE THREAD

**Issue by esune** [hyperledger/aries-cloudagent-python#707]
### Context
When creating a new credential definition supporting revocation, the agent takes care of:
- publishing a new credential definition
- generating a revocation registry and publishing it to the ledger
- generating a tails file for the revocation registry to use immediately, and one to roll over to once the first file becomes full
- publish the first "active" tails file to a tails server, so that it will be publicly available

### Problem
During this process, if uploading the tails file to the tails server fails, the credential definition ends up in a state where:
- it is possible to issue new credentials, **however**
- it will **NOT** be possible to revoke credentials, as there will likely be no active registry for the _relevant_ credential definition
- the whole tails file management will likely be broken, as there will not be a file ready to roll-over (assuming it was possible to revoke credentials)

### Desired behaviour
- Uploading the tails file to the server should retry (possibly with an increasing back-off interval) until uploading the file is successful.
- It should not be possible to issue credentials using that revocation registry if the tails file was not uploaded and it is not available for verifiers to use
- It should not be possible to issue credentials using that revocation registry if no revocation registry is active
- The above steps should be taken into account for any step involving the creation and publishing of a revocation registry and/or tails file (e.g.: generating the new "next" tails file when rolling over to a new one)

### Mitigation
Provide steps and API endpoints on the agent admin interface to correct this scenario for issuers that have already encountered it (it is currently not possible to "fix" things using the admin API)

**Comment by esune** [comment]
@andrewwhitehead @sklump @swcurran

**Comment by esune** [comment]
I poked more at the agent with the "borked" revocation registry (thanks @sklump for all the support - see [here](https://github.com/hyperledger/aries-cloudagent-python/pull/708)):
- the API endpoint at `/revocation/registry/{rev_reg_id}/set-state` allows to set the state of the registry and issue/revoke credentials until it gets full
- the agent will however **NOT** rotate tails file as expected: external (manual) intervention to create/register/publish/activate a tails file will therefore be required. Credential offers sent before the new tails file is created/registered will be delivered, however the mobile agent will not be able to receive them and they will need to be re-issued once the tails file is rotated.
- during my tests aca-py got in a weird state where the credex would get to the `credential_issued` state, however the mobile wallet would never receive the "final" credential after the initial offer was accepted (I see notifications in the app, but no actual message/credential)

**Comment by swcurran** [comment]
What does "rotate tails file" mean?

**Comment by esune** [comment]
> 
> 
> What does "rotate tails file" mean?

When the tails file capacity has been depleted, it needs to be replaced with a new one. It is a concept somewhat "similar" to log rotation from how I see it.

**Comment by sklump** [comment]
I think there are likely a few problems with the state machine here.

**Comment by sklump** [comment]
https://github.com/hyperledger/aries-cloudagent-python/pull/717 addresses
