### ISSUE TITLE
Faber-Alice-Acme Workshop Exception

### ISSUE THREAD

**Issue by QuesoViejo** [hyperledger/aries-cloudagent-python#724]
Running[ Faber-Alice-Acme lab workshop](https://github.com/hyperledger/aries-cloudagent-python/blob/master/demo/AcmeDemoWorkshop.md) I had the exception:
**Exception: Error: {"revocation_registry_size": ["Field may not be null."]}** 
which I solved calling from acme.py as:

await agent.register_schema_and_creddef(
                "employee id schema",
                version,
                ["employee_id", "name", "date", "position"],
                False,
                0
            )

But I believe the change should be made here at [agent.py](https://github.com/hyperledger/aries-cloudagent-python/blob/master/demo/runners/support/agent.py#L176), since I believe it's the default value for **revocation_registry_size: int = None**, the one causing the problem.

If I'm mistaken, I would be glad if someone could explain a bit more about it.
Thanks.

**Comment by sklump** [comment]
Not all cred defs support revocation; a revocation registry size of null is a common use case. There is a problem here and I am on it.

**Comment by sklump** [comment]
https://github.com/hyperledger/aries-cloudagent-python/pull/727 addresses

**Comment by QuesoViejo** [comment]
Great!
