### ISSUE TITLE
Add support for DID Exchange

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#730]
Add support for the DID Exchange protocol ([RFC 0023](https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange)), ideally in parallel with supporting the existing Connections protocol.

Because of how embedded the connection object is within the rest of ACA-Py, this is likely to be pretty complex. 

Naive question (sorry): Since the end result of Connections and DID Exchange are the same, is it possible to make the synonyms (not redirections) that act on the same data structures?  E.g. that the two protocols do (more or less the same things) could the share the same data structures, so we don't have to replace everything to switch from one to the other. There must be common data elements in the long-lived "connection" structure regardless of how the connection was created.

Some analysis was done to start on this in PR #693 by Nick before he left the project.

Note that DID Exchange requires OOB to be fully functional, so a companion tasks to this will be to complete the OOB protocol to fully support DID Exchange, so that we support (in sequence) step 1 and 2 of the OOB Community Upgrade (documented in this [Aries RFC PR](https://github.com/hyperledger/aries-rfcs/pull/498)).

**Comment by sklump** [comment]
Realistically, this is going to take weeks and weeks.
