### ISSUE TITLE
Remove extra forward slash from the command.

### ISSUE THREAD

**Issue by shivammutrejarug** [hyperledger/aries-cloudagent-python#737]
`$DOCKER run --name $AGENT --rm -it ${DOCKER_OPTS} \
  --network=${DOCKER_NET} \
  -p 0.0.0.0:$AGENT_PORT_RANGE:$AGENT_PORT_RANGE \
  -v "/$(pwd)/../logs:/home/indy/logs" \
  $DOCKER_ENV \
  faber-alice-demo $AGENT_MODULE --port $AGENT_PORT $ARGS`

Issue/Error - 

> Trying to detect ngrok service endpoint
> jq not found
> 192.168.65.3
> docker: Error response from daemon: Mounts denied:
> The path //Users/shivammutreja/advance_security/aries-cloudagent-python/demo/../logs
> is not shared from OS X and is not known to Docker.
> You can configure shared paths from Docker -> Preferences... -> File Sharing.
> See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.

Probable solution - In the aforementioned command `$(pwd)` will already return the path with a forward slash in the front. This means there is no need for an extra forward slash in the front.

**Comment by sklump** [comment]
https://github.com/hyperledger/aries-cloudagent-python/pull/740
