### ISSUE TITLE
Linking connection record to the public DID of the other agent, especially when the other agent is an Issuer

### ISSUE THREAD

**Issue by doganomer** [hyperledger/aries-cloudagent-python#743]
1- Issuer creates a new invitiation (with or without the public DID option) and passes it to the Holder out of band.
2- Holder creates connection using this invitation. 
Now, Holder can query the connection using _/connections_ and _/connections/{conn_id}_ endpoints. However, none of these endpoints provide a way to link the connection record to the actual Issuer (i.e. public DID of the Issuer) since a pairwise DID is always created and public DID of the Issuer does not exist in the connection info.

When Holder wants to get the schemas provided by that specific Issuer (actually for that holder's connection record) from the ledger, there is no way to filter the schemas on the ledger using any piece of information from the connection record (at least not to my knowledge)

Would that be possible to link connection record to the public DID of the Issuer; at least when the invitation is created by using public DID  by the Issuer?

**Comment by domwoe** [comment]
Related issue #358 

Although if I understand your use case correctly you'd need to make that link in your holder's controller application.

You **can** do that because the controller has the invitation with the public DID of the issuer and gets the connection id, when posting it to the `/receive-invitation` endpoint.

**Comment by swcurran** [comment]
A feature has recently been added to ACA-Py to enable this ("their-public-did" tag), so we can support the OOB "reuse" capability. Closing.
