### ISSUE TITLE
Concurrency issues with scaled agent deployments.

### ISSUE THREAD

**Issue by esune** [hyperledger/aries-cloudagent-python#745]
When thee are multiple agent instances accessing the same wallet (e.g.: kubernetes deployment of multiple aca-py agents using the same postgresql wallet), concurrency issues appear as 2 or more instances try to update the same non-secret record.

This happens, as an example, when issuing credential that support revocation: multiple agents would read the current state of the revocation registry, find that it is full and try to update the non-secret records to "rotate" the registry to a new one.

This appears to be an issue with the underlying indy-sdk, as reported [here](https://github.com/hyperledger/indy-sdk/issues/2236) and therefore depends on a fix at the sdk layer.

c.c.: @swcurran

**Comment by swcurran** [comment]
Closing this. We'll deal with new issues in the Askar context.
