### ISSUE TITLE
Include ImageURL in invitation

### ISSUE THREAD

**Issue by ankitkr1606** [hyperledger/aries-cloudagent-python#751]
I was trying to include ImageURL in the invitation while using create_invitation REST API but was not able to. Can you help me in this?

**Comment by ankitkr1606** [comment]
Let me be more clear on what i want to do. As of now when I create invitation using Swagger agents the response I get is something like this.
![invi](https://user-images.githubusercontent.com/25309320/96110902-23cc3680-0efe-11eb-93c2-5e5772d65939.png)

But as shown in the example of create invitation we can even include an attribute called ImageURL as can be seen here
![ex_invi](https://user-images.githubusercontent.com/25309320/96111491-e0be9300-0efe-11eb-919a-6d0e3e18f7db.png)

I want to include this into the invitation. I looked at the code base but was not able to find that image_url variable has been assigned any value.

**Comment by swcurran** [comment]
The use of icons in invitations has some interesting tension to it -- we want it to improve the user experience, but we want to be careful to make sure a "self-asserted" image (no verification of the sender) can't be used to fool a user into thinking a connection is with one party when it isn't.  People pretending to be the Bank when they aren't and they are trying to scam people.  An invitation rightly has no trust between the parties, and that trust should be built up using the connection process.

All that said, a PR could be created, if you are interested.

**Comment by kfigaj** [comment]
@ankitkr1606 did you try to set  this parameter at the agent start?

 --image-url IMAGE_URL
                        Specifies the image url for this agent. This image url
                        is publicized (self-attested) to other agents as part
                        of forming a connection. [env var: ACAPY_IMAGE_URL]

**Comment by swcurran** [comment]
Related to #1686 which is the same issue but for the OOB/DID Exchange protocols.  This one is for connections.

**Comment by swcurran** [comment]
This was added for OOB in PR #1966 . Closing this and will close #1686 as well.
