### ISSUE TITLE
What is the tails-server-base-url? and how should it be configured?

### ISSUE THREAD

**Issue by HarshMultani** [hyperledger/aries-cloudagent-python#752]
I have installed the indy-sdk in my system and started the ledger network (It is running).
After that I setup the aries-cloudagent and ran the agent (as a steward) using the aca-py command.

Now, with the help of this agent, I have published the schema on the ledger, but when I am trying to send a credential definition on the ledger.. It is giving me the error :- 400: tails_server_base_url not configured..

Can anyone explain what is it and how can it be resolved?

**Comment by sklump** [comment]
The tails server hosts tails files for revocable credentials. To post a cred def id that supports revocation, the issuer needs the tails server to which to post the tails files for revocation registries. 
https://github.com/bcgov/indy-tails-server
https://github.com/hyperledger/aries-cloudagent-python/blob/278c8ce0e85b403f8dd4cd83fb0bdc81f7e5dd54/aries_cloudagent/config/argparse.py#L458

**Comment by HarshMultani** [comment]
Hi, Thanks for the answer. But now, I don't want to post a cred def that supports revocation. Therefore I have set "support_revocation" to false while generating the credential definition. And, so the error is not coming.
