### ISSUE TITLE
the role filter when set to issuer while issuing credentials is showing no results.

### ISSUE THREAD

**Issue by ankitkr1606** [hyperledger/aries-cloudagent-python#771]
While issuning credentials, when I'm using  **GET /issue-credential​/records** with the value of role as issuer I'm getting empty results even though the issuer is issuing credentials, While exploring more I found that when using **POST /issue-credential/records/{cred_ex_id}/send-offer** the response body is not having any field as role inside it which is the reason why the role filter when set to issuer is not working.

**Comment by sklump** [comment]
I'll take a look, thanks
