### ISSUE TITLE
Problem in setting up a routing agent

### ISSUE THREAD

**Issue by ankitkr1606** [hyperledger/aries-cloudagent-python#773]
While using **/connections/create-invitation**, I want to include routing keys in the invitation object but not able to figure out the way to do it, and when using **/connections/{conn_id}/establish-inbound/{ref_id}**, the routing_state of the connection becomes request and I want to make it active. Can you please tell a way to do these?

**Comment by sklump** [comment]
At present aca-py doesn't support this. It's on the to-do list.

**Comment by sklump** [comment]
If you'd like to take this and submit a PR, that would be a huge help.

**Comment by denizgunseli** [comment]
@ankitkr1606 which RFC is you mention about? We are currently implementing [RFC - 0211](https://github.com/hyperledger/aries-rfcs/tree/master/features/0211-route-coordination). Does it cover your needs?

**Comment by darkchylde** [comment]
@ankitkr1606 To answer your second question, it should be active if the router responded with a `route-update-response` message. Check your router agent for any errors. 

Note: Both the agents must support the routing protocol.

**Comment by swcurran** [comment]
Closing this as I think we have adequate support. Please reopen or add a new issue if there is more to cover.
