### ISSUE TITLE
Count parameter in /credentials endpoint causes error 

### ISSUE THREAD

**Issue by doganomer** [hyperledger/aries-cloudagent-python#780]
When I send a request to **_/credentials_** endpoint with no parameters, it returns max 10 records. Therefore, I added the **count** parameter; such as **_/credentials?count=100_**. This used to work fine; however it seems that this has been broken.

When I send a request to http://localhost:4001/credentials?count=100; I get the following error:

Error: Unprocessable Entity
```
{
  "count": [
    "Not a valid integer."
  ]
}
```

**Comment by swcurran** [comment]
@sklump -- can you please take a look at this?  Looks like a big deal -- perhaps related to the recent marshmallow work?  If this is in 0.5.6 this would be a big deal.

FYI - Stephen is off today @doganomer , so the answer will not be forthcoming until tomorrow morning at the earliest -- eastern Canada time.

**Comment by sklump** [comment]
This is going to be a bigger fix than first appears. It will need a few hours probably.

**Comment by sklump** [comment]
https://github.com/hyperledger/aries-cloudagent-python/pull/782
