### ISSUE TITLE
Should ACA-Py return issuer/cred-def information to the controller after a verification?

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#783]
In the aca-py webhook payload sent back to the controller once the credential is verified contains the list of requested_attributes in the proof and the proof itself. However that does not include information about the schema, cred def and issuer of the credential.  The controller likely needs to know that information in order to decide the key verification governance question -- does the controller trust the issuer? Where the proof request is explicit about the cred-def or cred-def issuer, there is no need for the data, but otherwise, there is a need to know.

``` json
"requested_attributes": {
            "ef05d809-767f-4e1b-9c10-1617e428dd30": {
                "names": [
                    "Given Name",
                    "Surname"
                ],
                "restrictions": [
                    {
                        "schema_name": "Schema 1",
                        "schema_version": "1.0.0",
                        "issuer_did": "abcdefghilmno"
                    },
                    {
                        "schema_name": "Schema 2",
                        "schema_version": "1.0.0",
                        "issuer_did": "qwertyuioljdf"
                    }
                ]
            },
            "requested_predicates": {},
            "nonce": "761764877744881075508395"
        }

"requested_proof": {
                    "revealed_attrs": {},
                    "revealed_attr_groups": {
                        "ef05d809-767f-4e1b-9c10-1617e428dd30": {
                            "sub_proof_index": 0,
                            "values": {
                                "Surname": {
                                    "raw": "John",
                                    "encoded": ...                                },
                                "Given Name": {
                                    "raw": "Doe",
                                    "encoded": ...
                                }
                            }
                        },
                        "self_attested_attrs": {},
                        "unrevealed_attrs": {},
                        "predicates": {}
                    }
```

Note: the above is an example of proof using the names array. If non-grouped claims are present, there would be a similar data structure to the one displayed above in both sections, but for each one of the claims.

As you can see, the most I can assert from the above is that:

all claims come from the same credential
the credential respects the restrictions, and is matches one of the two schemas
I cannot determine whether the credential used was for Schema 1 or Schema 2.
When working with individual claim restrictions (not using names array) this complexity explodes: as stated above, each individual claim would have a data section in both requested_attributes and requested_proof.revealed_attrs that allows the controller to assert the value is indeed respecting the restrictions being imposed, but it will not allow further "processing".

The service from your example would come before we even get to the proof, as the proof-request itself should be generated with restrictions to allow only credentials from specific issuers. Once the proof-request is processed, there is - as of now - no way to reassemble that information.

I am not sure what the implications of adding that data to a proof in aca-py/Indy are, but I think - for this use-case - it should be handled at that level before/while processing the proof.

**Comment by sklump** [comment]
See `proof["identifiers"][i]["schema_id"]`, `proof["identifiers"][i]["cred_def_id"]` for `i` in `range(len(proof["identifiers"]))`
