### ISSUE TITLE
Exception: Error: 500 Internal Server Error

### ISSUE THREAD

**Issue by jeonjonghyeok** [hyperledger/aries-cloudagent-python#788]
EVENT: Controller POST /connections/create-invitation request to Agent
Faber      | 2020-11-17 02:49:18,939 aries_cloudagent.core.dispatcher ERROR Handler error: connections_create_invitation
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/aries_cloudagent/protocols/connections/v1_0/routes.py", line 342, in connections_create_invitation
Faber      |     body = await request.json()
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_request.py", line 584, in json
Faber      |     return loads(body)
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/json/__init__.py", line 354, in loads
Faber      |     return _default_decoder.decode(s)
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/json/decoder.py", line 339, in decode
Faber      |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/json/decoder.py", line 357, in raw_decode
Faber      |     raise JSONDecodeError("Expecting value", s, err.value) from None
Faber      | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Faber      |
Faber      | Shutting down
Faber      | 2020-11-17 02:49:18,947 aries_cloudagent.admin.server ERROR Handler error with exception: Expecting value: line 1 column 1 (char 0)
Faber      | 2020-11-17 02:49:18,947 aiohttp.server ERROR Error handling request
Faber      | Traceback (most recent call last):
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
Faber      |     resp = await task
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
Faber      |     resp = await handler(request)
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
Faber      |     return await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 144, in ready_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 177, in debug_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
Faber      |     return await handler(request)
Faber      |   File "/home/indy/aries_cloudagent/admin/server.py", line 275, in apply_limiter
Faber      |     return await task
Faber      |   File "/home/indy/aries_cloudagent/protocols/connections/v1_0/routes.py", line 342, in connections_create_invitation
Faber      |     body = await request.json()
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_request.py", line 584, in json
Faber      |     return loads(body)
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/json/__init__.py", line 354, in loads
Faber      |     return _default_decoder.decode(s)
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/json/decoder.py", line 339, in decode
Faber      |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Faber      |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/json/decoder.py", line 357, in raw_decode
Faber      |     raise JSONDecodeError("Expecting value", s, err.value) from None
Faber      | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Faber      | Exited with return code 0
Traceback (most recent call last):
  File "/home/indy/demo/runners/support/agent.py", line 446, in admin_request
    resp.raise_for_status()
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://192.168.65.3:8021/connections/create-invitation')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/indy/demo/runners/faber.py", line 462, in <module>
    args.timing,
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/indy/demo/runners/faber.py", line 204, in main
    connection = await agent.admin_POST("/connections/create-invitation")
  File "/home/indy/demo/runners/support/agent.py", line 482, in admin_POST
    response = await self.admin_request("POST", path, data, text, params)
  File "/home/indy/demo/runners/support/agent.py", line 449, in admin_request
    raise Exception(f"Error: {resp_text}") from e

**Comment by jeonjonghyeok** [comment]
in demo
LEDGER_URL=http://dev.greenlight/bcovrin.vonx.io ./run_demo faber --events --no-auto --bg

and 

docker logs -f faber

**Comment by sklump** [comment]
PR 786 fixes
