### ISSUE TITLE
Automate creation of releases

### ISSUE THREAD

**Issue by nrempel** [hyperledger/aries-cloudagent-python#79]
We should create a way to automate new releases.

Ideally, the process is triggered from the creation of a github release. This would build and push a new release to PyPI.

It would also be nice if we could automate the updating of the [changelog](https://github.com/hyperledger/aries-cloudagent-python/blob/master/CHANGELOG.md)

**Comment by swcurran** [comment]
Process is not too bad and documented in PUBLISHING.md
