### ISSUE TITLE
Error with /ledger/register-nym endpoint

### ISSUE THREAD

**Issue by bsantosALB** [hyperledger/aries-cloudagent-python#813]
Hello, I've currently found an issue regarding the did ledger registration:

![image](https://user-images.githubusercontent.com/54797210/101058213-d165d880-3584-11eb-8327-f0c6791deffa.png)

Do you know what this error could be?

**Comment by shaangill025** [comment]
@bsantosALB Which LEDGER_URL did you specify? Is the did and verkey specified above same as shown in /wallet/did/public?

**Comment by bsantosALB** [comment]
Hello @shaangill025, I'm running the Faber-Alice-Acme demo in a local server with docker. The von-network is also running in the same server. As for the DID and Verkey, yes, they were created in the /wallet/did/public endpoint

**Comment by swcurran** [comment]
Closing this -- it's worked elsewhere, so perhaps something local?
