### ISSUE TITLE
Issues starting agent after invalid POST to ledger/taa/accept

### ISSUE THREAD

**Issue by harpreetnanda** [hyperledger/aries-cloudagent-python#817]
### Env - StagingNet

I erroneously made a POST to my agent (ledger/taa/accept) with an invalid mechanism. After rescaling the POD on my openshift environment, the agent would throw  the error posted in the bottom and shut down

Based on a recommendation on the von-general chat group, I  was able to start the agent in read-only mode. This allowed me to do another POST to rectify the  error. Subsequent GET displayed the correct /taa. 

Restarting the agent ( after removing read only) now seemed to revert back to the "incorrect" mechanism that was originally posted and the agent shut down again.

<pre>
File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 88, in ledger_config
await wallet.set_did_endpoint(public_did, endpoint, ledger)
File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/wallet/indy.py", line 591, in set_did_endpoint
await ledger.update_endpoint_for_did(did, endpoint, endpoint_type)
File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 851, in update_endpoint_for_did
await self._submit(request_json, True, True)
File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 325, in _submit
f"Ledger rejected transaction request: {request_result['reason']}"
aries_cloudagent.ledger.error.LedgerTransactionError: Ledger rejected transaction request: client request invalid: InvalidClientTaaAcceptanceError("Txn Author Agreement acceptance mechanism is inappropriate: provided on_submission, expected one of ['at_submission', 'click_agreement', 'for_session', 'on_file', 'product_eula', 'service_agreement', 'wallet_agreement']",)

</pre>

**Comment by esune** [comment]
I have also seen this before: in my case I wanted to change the TAA acceptance method (used `for_session`, which I think expired when I restarted my agent), but executing a new `POST` with a new method would not update the record and on agent restart (which is required as far as I know after accepting a TAA for it to be effective) the old acceptance method would still be the active/effective one.

**Comment by swcurran** [comment]
Not sure what to do with this. Closing -- please reopen if appropriate.
