### ISSUE TITLE
Sends a proof presentation - Wallet credential identifier

### ISSUE THREAD

**Issue by kapilkathuria** [hyperledger/aries-cloudagent-python#819]
POST: /present-proof/records/{pres_ex_id}/send-presentation

above api request requires: "Wallet credential identifier"

but doesn't look like there is  "Wallet credential identifier" anywhere. 

here is the response from http://localhost:9001/present-proof/records/aa7f4604-7f27-442f-b36b-8d3db3ef459c/credentials:

```
[
  {
    "cred_info": {
      "referent": "string",
      "attrs": {
        "firstName": "Alice",
        "score": "9/10",
        "lastName": "Jones"
      },
      "schema_id": "3avoBCqDMFHFaKUHug9s8W:2:issue_schema_test1:1.0",
      "cred_def_id": "3avoBCqDMFHFaKUHug9s8W:3:CL:56740:default",
      "rev_reg_id": null,
      "cred_rev_id": null
    },
    "interval": null,
    "presentation_referents": [
      "additionalProp1"
    ]
  }
]
```

**Comment by TimoGlastra** [comment]
I think you need to use the `referent` attribute as the "Wallet credential identifier". Not sure why those have different names

See https://github.com/hyperledger/aries-rfcs/blob/master/features/0037-present-proof/README.md#referent for more information on referent

**Comment by kapilkathuria** [comment]
gotcha. it works. thank you!

do you want me to keep issue open so that naming can be corrected to avoid confusion?

**Comment by swcurran** [comment]
Better yet -- put in a PR.  :-)

**Comment by sklump** [comment]
You are likely to find these terms used interchangeably throughout the indy-sphere for historical reasons.
I don't remember exactly but I think they introduced 'credential identifier' to disambiguate from 'referent' in a proof request, after they changed 'uuid' to 'referent' in the proof request.

The referent in an RFC-37 proof proposal can tie multiple items together into one credential for presentation, or allow for their presentation via distinct credentials. Hence the RFC-37 referent acts as an index of the wallet referent within the proof proposal.
