### ISSUE TITLE
Mobile Cloud Wallet using aries-cloudagent-python

### ISSUE THREAD

**Issue by proteche** [hyperledger/aries-cloudagent-python#828]
Is it possible to create mobile cloud agent by using aries-cloudagent-python api's & storing verifiable credential in mobile storage, any information will be helpful.
Thanks in advance

**Comment by swcurran** [comment]
We've not thought about that model before.  We have considered creating a cloud wallet service and having a mobile agent (perhaps a progressive web app).  There are two important features being worked now for that -- multi-tenancy support and mediator support.  What we have nailed down is how access to the cloud wallet would be managed to keep the user in control.
