### ISSUE TITLE
How to store issued credentials

### ISSUE THREAD

**Issue by jabbawocky0815** [hyperledger/aries-cloudagent-python#832]
Hi! I am new to learn hyperledger.
I have played around with the demo agents (faber and alice) and get it running. I changed the code to create my own credential definition. I am also running a local von-network.
I can issue a credential by using the swagger API and alice gets the credential.
But when i restart the agents, the credentials are lost.
What i have to do, to get the agents to store the credentials?
I think i have to start the agents in provision mode?
But i have not figured out to do it right.
Is there any tutorial out there with detailed steps?

**Comment by swcurran** [comment]
Hopefully you found out about this.
