### ISSUE TITLE
Missing TAA Accepting Mechanism in Faber Agent for Demo Repos

### ISSUE THREAD

**Issue by sauveergoel** [hyperledger/aries-cloudagent-python#855]
While trying out to connect [StagingNet](https://forum.sovrin.org/t/how-to-access-the-public-sovrin-network/1035) with [Open API Demo Code's](https://github.com/hyperledger/aries-cloudagent-python/blob/master/demo/AriesOpenAPIDemo.md) Faber Agent, a `InvalidClientTaaAcceptanceError` was encountered.

There is a `/ledger/taa/accept` endpoint to accept the TAA Agreement, but before that can be executed, the code progresses for a schema txn with the StagingNet ledger. Hence the error and the agent fails.

Proposed Solution: Update the Faber Agent code to check and execute TAA Acceptance before proceeding for any kind of ledger txns.

**Comment by swcurran** [comment]
@ianco -- any thoughts on this?  Seems like a good idea.

**Comment by ianco** [comment]
@swcurran agree this looks like a good idea, I suggest adding a `--accept-taa` parameter to the app (so it is explicit).  Just need to prioritize this task and put into the backlog.

**Comment by TimoGlastra** [comment]
Somewhat related to this issue: https://github.com/hyperledger/aries-cloudagent-python/issues/1532

May be worth fixing it in ACA-Py for most benefits

**Comment by swcurran** [comment]
Assuming that the merge #1532 addresses this issue.  Closing.  Please reopen if more is needed.
