### ISSUE TITLE
oob invitations create invitations with "service" but receive expects "service_blocks" or "service_dids"

### ISSUE THREAD

**Issue by brianorwhatever** [hyperledger/aries-cloudagent-python#879]
It seems the recent DID exchange work has broken the ability to receive an invitation. An invitation is created with a "service" array however the receive side expects either a "service_blockd" or "service_dids" array. Unless I am missing something I believe there needs to be a change made to either the create side or the receive side.

Here is a failing test which is passing in the plan service array containing a DID. https://github.com/hyperledger/aries-cloudagent-python/compare/master...brianorwhatever:invitiation-test#diff-02df1960dddcd47f09ad51465e89f23523255e385d69e35ba427996e2bd14e7bR330

I found this which is supposed to be sorting the service array into it's respective array https://github.com/hyperledger/aries-cloudagent-python/blob/b2ab799fe0054f860f024f9dfafc742ab721ccd3/aries_cloudagent/protocols/out_of_band/v1_0/messages/invitation.py#L73
however evidently it is not working. I'm not familiar enough with how python types work but I believe this init isn't being called.

Thoughts?

**Comment by brianorwhatever** [comment]
Sorry above method of showing the test doesn't work so i've opened a PR https://github.com/hyperledger/aries-cloudagent-python/pull/880

**Comment by andrewwhitehead** [comment]
I need to revisit the OOBManager's receive method, but I think `didexchange/receive-invitation` is working properly.

**Comment by brianorwhatever** [comment]
ah ok I will take a look at the didexchange protocol. Thanks Andrew

**Comment by brianorwhatever** [comment]
Yeah, the didexchange protocol seems to be working. I'll close this issue, thanks for the help
