### ISSUE TITLE
DIDExchange: problems with implicit invitation

### ISSUE THREAD

**Issue by marc0olo** [hyperledger/aries-cloudagent-python#881]
**Context**
In the recent days we tried to establish a DIDExchange between a Go agent and ACA-Py. The goal was to provide a public DID document for ACA-Py which is conform to RFC 0067 to make use of an implicit invitation. We faced a limitation in the current Indy format and therefore used `did:web` to provide a service endpoint and the recipientKey of ACA-Py.

The Go agent was able to resolve the DID document of the public `did:web` and created a DIDExchange request when calling its endpoint `/connections/create-implicit-invitation`. The DIDExchange request was successfully sent to and picked up by ACA-Py.

**Issues & problems in ACA-Py**
When receiving the DIDExchange request from the Go agent we faced following problems:
- ACA-Py expects the attribute `label` to be present in the DIDComm message
   - this label isn't provided by the Go agent and probably shouldn't be required
- After setting `label` as optional field I faced the next problem => ACA-Py expects an `InvitationRecord` for the provided `pthid` to be present and throws an error.
   - Since this is a DIDexchange request based on an implicit invitation, the included `pthid` includes the public DID of ACA-Py (in this case our `did:web` which we manually created)
   - I think ACA-Py needs to be able to distinguish an explicit and implicit invitation by interpreting the `pthid` in order to allow implicit invitations in the DIDexchange protocol

**Additional notes & open questions**
- For the public `did:web` I created a local DID in ACA-Py using the endpoint `/wallet/did/create` and included the `verkey` of the local DID in the public DID document.
  - Probably this is not the way to go for this scenario. But I had no idea how to achieve what I want to test.
  - I am not sure how public DIDs are being handled in ACA-Py right now => maybe the admin should be able to configure a public DID that ACA-Py uses?

**Comment by swcurran** [comment]
We have DID Exchange working in Aries Agent Test Harness with AF-Go, so closing this issue.
