### ISSUE TITLE
How Aries agent will be created

### ISSUE THREAD

**Issue by Shweta-hlf** [hyperledger/aries-cloudagent-python#887]
I am trying to implement example of faber (college),Acme(employer) and Alice (student) agents.In my use case,If college have 1000 students.so how 1000 agent will be created. Because 1000 credential will be issued to corresponding student's wallet.
Let me correct if anything wrong.

Thanks!!

**Comment by swcurran** [comment]
I think this was answered on Rocketchat -- here was the answer:

If you have 1000 (or a billion) Alice agents that are mobile agents, you don't have a problem -- each is on their own device. You would need a mediator to serve those, but a single mediator can serve many mobile agents.

If you do want to have 1000 Faber (or Alice) agents running in the cloud, the concept of a multi-tenant wallet was just implemented in ACA-Py. With that, you have one scalable instance of ACA-Py and as many wallets, one per agent in a single data store.


albertobr
11:04 AM
Thank you newdev42 and swcurran . What I can understand from your comments and from what I read in the course it's the following, you can use Go and .NET frameworks to have the agent in the mobile device (as you both say), but it's not the case, so I'm focusing in the Cloud Agent Model (HTTP API using ACA-Py). If we extend the AliceFaberAcme demo to have 1000 Alices and I develop the application (controller in IP:port) for 1000 Alices, does the following make sense?

- Faber: 1 agent / 1 controller (as in the demo)
- 1000 Alices: How many ACA-Py instances? (agents) / 1 controller (I'm not sure)?
- Acme: 1 agent / 1 controller (as in the demo)

As swcurran comments in the second paragraph, and probably is what I'm looking for, I guess the multi-tenant wallet needs Alice's signature and mine, right? Could be the best solution to my approximation?

Thank you very much and sorry if I'm asking naive questions.

swcurran
7:15 AM
Yes --multi-tenant wallets are what you want. That feature has recently (this month) been added to ACA-Py -- without a lot of docs. The Alice-Faber demo does support the multi-tenant option, so you can look at that code to see examples. More docs to come...
