### ISSUE TITLE
[multitenancy] wallet_id  is not passed correctly in send_webhook

### ISSUE THREAD

**Issue by baegjae** [hyperledger/aries-cloudagent-python#898]
https://github.com/hyperledger/aries-cloudagent-python/blob/5687d287040c2abb4d37999d64fd873ea494a9b8/aries_cloudagent/admin/server.py#L733

In this code, `wallet_id` identifies what this webhook message belongs to.

I checked that `wallet_id` is passed correctly (for newly created wallet) in cases of topic: `connections`, `revocation_registry`.

But, in the case of topic `issue_credential`, `wallet_id` was None.
Although the webhook message belongs to the newly created wallet, I checked that the `profile` passed is for the base wallet (configured when aca-py runs).

Thanks!

@TimoGlastra

**Comment by TimoGlastra** [comment]
I was able to reproduce the issue. I'll look into it

**Comment by TimoGlastra** [comment]
@baegjae #905 should resolve the issue

**Comment by baegjae** [comment]
@TimoGlastra Thank you. It works well!
