### ISSUE TITLE
Not able to create connection between Organization agent and end User agent using mediator.

### ISSUE THREAD

**Issue by Shweta-hlf** [hyperledger/aries-cloudagent-python#904]
Hi Team,

I have taken latest aries-cloudagent-python code and created 3 aries cloudagent Organization,Mediator and User.I am trying to use mediator in following way. 
1. Created connection between Organization and Mediator.
2. Using above connection id, create mediator Id by organization agent.
3. Grant mediator request by Mediator agent.
4. Trying to make connection in between Organization agent and end User agent using mediation id but getting error "No route found with recipent key " at mediator log.

Pls let me correct if anything wrong.

**Comment by dbluhm** [comment]
What parameters are you using to start each of the agents?

**Comment by dbluhm** [comment]
@Shweta-hlf, the example configurations in #910 may be of interest

**Comment by Shweta-hlf** [comment]
Thanks dbluhm!!
I tried  #910  configuration and start agent in following way.

./bin/aca-py start --arg-file ./demo/demo-args-faber.yaml
./bin/aca-py start --arg-file ./demo/demo-args-mediator.yaml
./bin/aca-py start --arg-file ./demo/demo-args-alice.yaml

First i tried to make connection between faber and Mediator using swagger api (create-invitation and receive-invitation) but "state" attribute is "request" not "active". so connection is not established.

Kindly suggest.

**Comment by dbluhm** [comment]
This appears to be a problem with your configuration or the invitation being generated rather than mediation. When you create an invitation in the Admin API, example values are inserted that likely do not reflect the actual scenario you are testing from. Please verify that when you create an invitation, the body is empty (the defaults used when not specified are probably sufficient) or that the values are correct.

**Comment by dbluhm** [comment]
@Shweta-hlf I'm going to go ahead and close this issue. If you're continuing to experience challenges while working with mediation, please feel free to contact me on chat.hyperledger.org
