### ISSUE TITLE
Broken links to demo/alice.py and demo/faber.py

### ISSUE THREAD

**Issue by gcsfred** [hyperledger/aries-cloudagent-python#91]
https://github.com/hyperledger/aries-cloudagent-python/blob/master/demo/README.md
has broken links to 

https://github.com/hyperledger/aries-cloudagent-python/blob/master/demo/alice.py
and
https://github.com/hyperledger/aries-cloudagent-python/blob/master/demo/faber.py

**Comment by swcurran** [comment]
Thanks!  PR submitted.  We moved the scripts from the demo folder into a sub-folder (runners) but didn't update the links.

**Comment by nrempel** [comment]
Looks like this has been resolved. Thanks!
