### ISSUE TITLE
Evaluate new Sovrin TAA feature and how to handle that in ACA-Py

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#92]
The new Transaction Author Agreement (TAA) will soon be added to the Sovrin ledger (MainNet, BuilderNet and StagingNet) and support will need to be added to ACA-Py to support it for Aries instances accessing and writing to those networks.

Please review this new feature and evaluate how we can add support for the TAA in ACA-Py.  This is a good starting article, and there links at the bottom of the article to further technical details.

https://sovrin.org/preparing-for-the-sovrin-transaction-author-agreement/

**Comment by vinomaster** [comment]
@swcurran You may want to review this draft diagram that has been submitted as part of an update to Sovrin Glossary Appendix E. It has been used for discussions with respect to contractual instruments for GDPR/CCPA/other-regulation compliance. 

The right side of the diagram is pertinent to this issue. It implies that the SF will require an Agent that can present a click-through license for a Transaction Author. 
<img width="789" alt="figure_E-2" src="https://user-images.githubusercontent.com/505186/62000849-c73deb00-b0af-11e9-89ee-8b5d865a4e52.png">

Should the Transaction Author's Agent store a copy of the TAA and proof of signature? The SF's Agent should keep such a record. 

How will Steward's know that the TAA has been signed by the TA(DID) before it allows a Trx Write request?

**Comment by andrewwhitehead** [comment]
I would suggest adding this to the `aca-py provision` command, probably as an automatic part of `aca-py provision ledger` (which doesn't exist yet). It could automatically download the AML and TAA if they exist, and assuming `session_agreement` is an option then it could present the terms and ask for user acceptance. Each acceptance record would be stored in non-secrets and the latest one would be submitted with each request. Some formatting could probably also be applied by a markdown-to-terminal formatter (pygments seems to support that).

**Comment by andrewwhitehead** [comment]
Resolved via #127
