### ISSUE TITLE
JSON-LD route tests can fail without an internet connection

### ISSUE THREAD

**Issue by andrewwhitehead** [hyperledger/aries-cloudagent-python#920]
The solution is probably to use local copies of any JSON-LD contexts and a custom document loader in the tests.

**Comment by TimoGlastra** [comment]
If this is not urgent, we can pick this up when extending the JSON-LD processing. Should be a few weeks

**Comment by swcurran** [comment]
Closing this. Re-add if / when this becomes crucial.
