### ISSUE TITLE
Error with /connections/create-invitation

### ISSUE THREAD

**Issue by dusela** [hyperledger/aries-cloudagent-python#929]
Hi everyone!

I am currently trying to upgrade my 0.5.3 Version to 0.6.0-pre. Therefore, I configured the Dockerfile as well as the run docker script to provide wallet provisioning. After starting the Agent 0.6.0-pre successfully, I was facing the following error when i tried to use the Swagger UI to execute the /connections/create-invitation request.

400: mediation_requests record not found: 3fa85f64-5717-4562-b3fc-2c963f66afa6. WalletItemNotFound.

What do i have to pay attention to in order not to cause this error? What exactly do I use the WalletItem for?

Thanks a lot!

**Comment by TimoGlastra** [comment]
Are you using a mediator? If not, I've often made the mistake of leaving the example `mediation_id` in the request body. You should remove that if you're not using a mediator. See the image below. 

![image](https://user-images.githubusercontent.com/23165168/106147393-161e8200-6178-11eb-95f1-d2284962627b.png)

**Comment by dusela** [comment]
> Are you using a mediator? If not, I've often made the mistake of leaving the example `mediation_id` in the request body. You should remove that if you're not using a mediator. See the image below.
> 
> ![image](https://user-images.githubusercontent.com/23165168/106147393-161e8200-6178-11eb-95f1-d2284962627b.png)

Indeed, also made that mistake! Thank you very much, everything works fine now :)

**Comment by jantuitman** [comment]
I had the same error. the documentation here claims that you can submit the request without altering. https://github.com/hyperledger/aries-cloudagent-python/blob/master/demo/AriesOpenAPIDemo.md#use-the-faber-agent-to-create-an-invitation . this is not true. so it is a bug in the demos.

**Comment by sklump** [comment]
I'll fix this today

**Comment by sklump** [comment]
https://github.com/hyperledger/aries-cloudagent-python/pull/969
