### ISSUE TITLE
Add web-based Alice/Faber demo to ACA-Py

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#93]
In the Blockchain for Business edX course, we used the work done by the BYU team to create a web-based, [node.js Alice/Faber workshop](https://github.com/hyperledger/education/blob/master/LFS171x/indy-material/nodejs/README.md) that has been very well received.  It gives a good, visual way for those new to the Indy/Verifiable Credentials world to see how credentials can work.  The problem with the workshop is that it is based on really old code and old concepts. At best the workshop is misleading (particularly about public DIDs) and and worst, those using the workshop start to dig into and in some cases try to extend the code.  It would be much better to add a new workshop based on ACA-Py.

The following are a suggestion of the features of the new demo:

- audience: primarily for business or as a first time run through for developers
  - secondary audience: developers trying to dig into the controller code to build their own
- ensure that the demo be run in Play with Docker, with docker-compose to execute
- implement separate controller and agents for each of the participants
- improve the user interface, but it's OK to show some ugliness (e.g. JSON data) if it helps developers running the demo understand the flow
- implement Alice as a web service that looks human useful
- consider implementing Faber and Acme as backend services - no user interface (at least initially)
   - Cutting and pasting invitations may be used since QR codes are not as feasible
- use node-js for the controllers to demonstrate that a controller can be written in any language
  - perhaps even do one of the controllers in another tech, such as dotnet
- If possible, use the [email verification service](https://email-verification.vonx.io), [repo](https://github.com/bcgov/indy-email-verification)
  - This is just an idea - not sure it is feasible.
  - We can could the service if that's appropriate - eg separate page for entering email address and separate page when clicking from the email to that shows an invitation.
 - Alternatively, consider having a non-UI Government issuing services that issues "Registered Organization" credentials to Faber and Acme and a "Citizen" credential to Alice
 - Add to the story an automatic proof request from Alice requesting proof of registration for Faber and Acme.

Proposed flow:

- Use email verification service to get a verifiable credential for the users email address.
  - Alternative: Gov Agent issues Alice, Faber and Acme appropriate baseline credentials
- Connect to Faber and Faber requests email address/gov proof
  - Nice to have: Alice requests Gov proof (or could be exercise for the user to implement)
- Faber generates a transcript that includes data received in the prtoof
- Connect to Acme - requests ID and transcripts proof

**Comment by dongwangdw** [comment]
@swcurran This looks interesting. I will be on this.

**Comment by swcurran** [comment]
Hi @dongwangdw - any luck finding time to make progress on this?  Let me know how it is going.

**Comment by dongwangdw** [comment]
@swcurran 
I got some urgent things recently. Have to deal with it with first priority.
I have some initial investigation and plan for this issue. I will keep updating it.

**Comment by swcurran** [comment]
Great - thanks.  Others may work on this well, so keeping this issue up to date would be great.

**Comment by dongwangdw** [comment]
OK. that's cool.

**Comment by swcurran** [comment]
@seanadipose - this is the issue we were discussing.

**Comment by wip-abramson** [comment]
I would be interested to hack on this with someone. Has anyone made any progress?

**Comment by swcurran** [comment]
This is now done. Work is currently in https://github.com/petridishdev/aries-acapy-controllers and will be moving to Hyperledger soon.  Great work done by @amanji!

The structure created is such that more controllers can be added - either tied to the demo agents or not.

Closing this issue.
