### ISSUE TITLE
Turning agents "off and on"

### ISSUE THREAD

**Issue by james-cohen** [hyperledger/aries-cloudagent-python#932]
This is less of an issue and more of a request for advice, so if there is a more appropriate place to ask it please let me know.

I'm trying to design an implementation where multiple people can use pre-existing agents on an as needed basis via use of persistent Postgres wallets. In this case, there would be one or several dormant agents in docker containers on a network that are activated when needed, associating them with the relevant users DID and wallet. When the user has finished with their desired transactions, the agent is deactivated again and can be re-used by someone else.

The aim of this is to get around the issue of agent persistence and a requirement of one agent per person. My question is, is it even feasible? The run_docker script currently used creates the entire container from scratch and before being destroyed on exit. Would a dormant agent that can be reinitialised with different wallets and DIDs be possible with a custom script?

**Comment by swcurran** [comment]
@james-cohen -- what you want is to use the newly added multi-tenancy feature in ACA-Py.  With that you will be able to have many tenants, each with their own encrypted storage, and a single, scalable ACA-Py service (e.g. stateless containers on, for example, a Kubernetes installation).

There is some documentation in the main branch of the code that describes the feature with more coming soon, and there is a way to run the demo in multi-tenancy mode.

**Comment by james-cohen** [comment]
Ah amazing, I'll take a look, thanks
