### ISSUE TITLE
Switch the primary branch from "master" to "main"

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-cloudagent-python#933]
Per the Hyperledger TSC, we need to do this in all Hyperledger repos, and we should get this done across all repos.  Let's do this one first and then figure out how to do the rest.

How do we do this in a non-disruptive manner to the community?

**Comment by andrewwhitehead** [comment]
This is quite straightforward, we just need to close outstanding PRs first.

**Comment by swcurran** [comment]
Right, but when was the last time we had no open PRs?  What if we can't close the PRs?

**Comment by andrewwhitehead** [comment]
Existing PRs can also be edited to target `main`, or just reopened. `main` will be branched off of `master` so there's little reconciliation to do.

**Comment by WadeBarnes** [comment]
Branches can be renamed; https://github.com/github/renaming

**Comment by WadeBarnes** [comment]
PR to address some documentation references; https://github.com/hyperledger/aries-cloudagent-python/pull/934

**Comment by WadeBarnes** [comment]
Developers notified via `chat.hyperledger.org` `#aries-cloudagent-python`  channel; https://chat.hyperledger.org/channel/aries-cloudagent-python?msg=7o3QSXrvn2upbeoyr

**Comment by WadeBarnes** [comment]
Branch renamed.
Developers notified via `chat.hyperledger.org` `#aries-cloudagent-python` channel; https://chat.hyperledger.org/channel/aries-cloudagent-python?msg=tXiPYBurvKN9jek39
Related PR Merged.
