### ISSUE TITLE
ActionMenu returns 200 when connection with active menu can't be reached but errors appear in terminal.

### ISSUE THREAD

**Issue by daidoji** [hyperledger/aries-cloudagent-python#940]
When an agent (**agent A**) goes down who has previously presented an actionmenu to another agent **(agent B)** acapy returns 200 OK with an empty result while connection errors show up in the terminal.

We can attempt to produce a more detailed example but a simple way to replicate:
1. Spin up alice and faber from alice-faber-demo
2. Present default openapi action menu from faber to alice (warning from alice that she doesn't have webhooks to deal with actionmenu)
3. Perform action from alice to faber using openapi: _gets 200 and `{}` but maybe that's expected_
4. Terminate faber agent container
5. Perform same action from step 3) :  _gets 200 and `{}` while the following error (attached) appeared (which we'd expect)_

[alice.err.txt](https://github.com/hyperledger/aries-cloudagent-python/files/5926691/alice.err.txt)

It would be nice to have an error webhook for these type of situations but presenting an HTTP error code from the 400 class or even just something to parse out in the response body would be helpful when developing controllers.

This actually seems to be a more general issue with acapy and might not be confined to just the ActionMenu workflow, other actions seem to have the same issue when underlying errors in Indy or the network don't necessarily get passed up to the acapy REST interface (and hence can't get to the controller to be dealt with).

The above steps were tested with the latest checkout from main.

**Comment by swcurran** [comment]
@andrewwhitehead -- thoughts on this?  Is this specific to Action Menu?

**Comment by daidoji** [comment]
Just confirmed this behavior also occurs on `/issue-credential/send` for an agent whose endpoint can't be reached.  Replication is the similar.

1. Establish a connection as we normally would (I typically use alice-faber demo workflow to test)
2. Take one of the agents down
3. `/issue-credential/send` to the downed agent via the admin api
4. Get back a 200 OK and the response body we'd expect, but acapy throws a bunch of `aiohttp.client_exceptions.ClientConnectionError`s in the background.

**Comment by swcurran** [comment]
I'm going to close this issue.  However, in doing that, I'll flag @shaangill025 about this issue as he works on the persistent queue implementation, as he is probably working in the same area.  Does this play into what you are doing?

Please reopen if appropriate.  I can see that this might still be an issue.
