### ISSUE TITLE
Credential Issuance ~250000

### ISSUE THREAD

**Issue by prachiadhikari-git** [hyperledger/aries-cloudagent-python#947]
Hi,
I am using ACA-PY version 5.6 for credential issuances along with controller which is written in Spring boot. I am trying to issue ~250000 credentials 
with only one credential definition. The time taken to issue ~100000 credentials is 26 hours. I need to optimizing this time further. Any suggestions in this 
regard will be really helpful.

Thanks and regards
Prachi

**Comment by swcurran** [comment]
Interesting problem.  We've worked on this a fair amount and we've achieved a lot more performance than that - about 20x that in our use case (1200/minute vs. the 64/minute you are getting currently), and we think we can do significantly better with some new capabilities in ACA-Py, but haven't had a chance to work on that lately. Perhaps we can help with your work.

Some questions to get started:

- Not that it matters too much, but at a high level, what is the use case?
- What are you issuing to?  What is the end to end component flow?
- What is the technical stack of the components?  For example, where is the issuer running and in what environment?  What database are you using?  Same for the holder(s) if you control that.

Thanks

**Comment by prachiadhikari-git** [comment]
Hi, 
I don't have any specifc usecase in mind at present, but I was thinking of offering credentials to the students as is the case of Alice. For most of the usecases, number of users will be huge. Thus decided to check on credential issuance performance. Currently I am trying to issue "First Name" and "Last Name" as a credential. I am using Alice from demo setup (https://github.com/hyperledger/aries-cloudagent-python/tree/main/demo) as a Holder.
Alice has sqlite and Issuer has postgres as wallet. We also have separate tail server for issuer.   Both, holder and issuer are using version 5.6.
Here is the flow:
1. Alice is set in auto accept connection and auto accept offer mode
2. Connection is established between Alice and Issuer
3. Schema and Credential definition is created with revocation registry set to true
4. Issuer sends 0.1 million credential offers to Alice, which Alice Auto Accepts
5. Issuer send 0.1 million credentials to Alice

Both Issuer and Alice are running on Ubuntu machine.  

Also tried performance testing with 2 instances of agents, both agents point to the same wallet and same tail server with same seed. But got only about ~12% performance improvement in issuance. 

Regards,
Prachi

**Comment by sklump** [comment]
You must compile indy-sdk in release mode, not debug, to generate tails files in any reasonable time frame. That's a one-time thing though.

**Comment by Knightmare25** [comment]
Isn't tail file in 5.6 version 1000 by default and it automatically create new tail file after the current one is full.

**Comment by swcurran** [comment]
With separate connections per holder and all running on one system, you are likely to hit constraints on the system.  What is the CPU. disk and network activity as the test is running?  Are you constrained on those resources?  What about when you you have two instances of the agents?

Do you have information on whether the process is slowing over time?  In other words is the database size impacting the performance over time?

As @Knightmare25 noted, the size of the tails files might impact things a little, as you are frequently creating and publishing tails files.  Perhaps making it 10x the size (10k) might be better.  But I don't expect that to be significant.

Is the issuer waiting for the completion of each issuance before moving on to the next?  Would parallel connecting and issuing help with this?

A couple of other things to look at. 

- There is a way to collect timing stats as you run the agents.  It might be good to do a smaller run while collecting timing logs and see where the bottlenecks are occurring.
- The team here is close to having a non-Indy-SDK version of ACA-Py ready.  When that is available, you can try it as it is (a) generally faster, and (b) has fewer central queues (blocking requests) vs. the Indy SDK.  That should mean more parallelism is possible.

**Comment by paliwalg** [comment]
> Interesting problem. We've worked on this a fair amount and we've achieved a lot more performance than that - about 20x that in our use case (1200/minute vs. the 64/minute you are getting currently), and we think we can do significantly better with some new capabilities in ACA-Py, but haven't had a chance to work on that lately. Perhaps we can help with your work.
> 
> Some questions to get started:
> 
> * Not that it matters too much, but at a high level, what is the use case?
> * What are you issuing to?  What is the end to end component flow?
> * What is the technical stack of the components?  For example, where is the issuer running and in what environment?  What database are you using?  Same for the holder(s) if you control that.
> 
> Than

> Interesting problem. We've worked on this a fair amount and we've achieved a lot more performance than that - about 20x that in our use case (1200/minute vs. the 64/minute you are getting currently), and we think we can do significantly better with some new capabilities in ACA-Py, but haven't had a chance to work on that lately. Perhaps we can help with your work.
> 
> Some questions to get started:
> 
> * Not that it matters too much, but at a high level, what is the use case?
> * What are you issuing to?  What is the end to end component flow?
> * What is the technical stack of the components?  For example, where is the issuer running and in what environment?  What database are you using?  Same for the holder(s) if you control that.
> 
> Thanks

Hi Sam,

Facing similar issue.  Trying to find out the ways of scaling the Aries Agent.  I have a very basic setup 
1. Trying horizontally scaling of aries agent by running two docker containers with the exact same start up parameters
2. Using Postgres database for wallet, so both the aries agent containers using the same postgres database
3. Volume mount the ./indyclient folder for both the containers. This persists the revocation registry related files.

With this type of setup expect performance to improve approx 2 fold as compared to running single agent.
I get 40% performance improvement for CredentialOffer functionality, but for CredentialIssuance it stays same.

I suspect, the reason for this to be read/write operations for revocation registry related files are synchronous.

Can you please advice, what could be issue here ? How to troubleshoot and fix it.

**Comment by paliwalg** [comment]
> Interesting problem. We've worked on this a fair amount and we've achieved a lot more performance than that - about 20x that in our use case (1200/minute vs. the 64/minute you are getting currently), and we think we can do significantly better with some new capabilities in ACA-Py, but haven't had a chance to work on that lately. Perhaps we can help with your work.
> 
> Some questions to get started:
> 
> * Not that it matters too much, but at a high level, what is the use case?
> * What are you issuing to?  What is the end to end component flow?
> * What is the technical stack of the components?  For example, where is the issuer running and in what environment?  What database are you using?  Same for the holder(s) if you control that.
> 
> Thanks

Hi Stephen,

Facing similar issue.  Trying to find out the ways of scaling the Aries Agent.  I have a very basic setup 
1. Trying horizontally scaling of aries agent by running two docker containers with the exact same start up parameters
2. Using Postgres database for wallet, so both the aries agent containers using the same postgres database
3. Volume mount the ./indyclient folder for both the containers. This persists the revocation registry related files.

With this type of setup expect performance to improve approx 2 fold as compared to running single agent.
I get 40% performance improvement for CredentialOffer functionality, but for CredentialIssuance it stays same.

I suspect, the reason for this to be read/write operations for revocation registry related files are synchronous.

Can you please advice, what could be issue here ? How to troubleshoot and fix it.

**Comment by prachiadhikari-git** [comment]
Hi,

I have observed that the issuance process is slowing over time, but with aries agent 5.6, CPU and memory usage is less than 50% of the available capacity. 
Need to check on Network activity. I am using postgres database which gets filled less than 50% of the size available. Tried Issuance with 10k tail file size, the performance is much worse than the default size, 1000. I am running issuer with 10 parallel threads, but not sure how much parallelism is possible as issue_credential has many await functions, especially issuer.create_credential. 

I am expecting some bottleneck due to tail file as suggested by @paliwalg,  but doesn't have any concrete data. 
Have you got 1200/min with revocation or without revocation? I observe that performance is much better without revocation.

Thanks and Regards,
Prachi

**Comment by swcurran** [comment]
Lots has happened since this. Closing this. When adding performance issues, it would be super helpful if the core devs could get more access to the scenario -- e.g. a minimal sample of the use case or pair programming to look at what's going on in real-time.
