### ISSUE TITLE
v2 protocols MUST expect any of the attachment formats

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-cloudagent-python#972]
Currently the issue credential v2 protocol expects the attachments to always use base64 encoding although the RFCs mention it can be any of the formats (json, base64, links + sha).

From the issue credential v2 RFC:

> Any of the 0017-attachments RFC embedded inline attachments can be used. In the examples below, base64 is used in most cases, but implementations MUST expect any of the formats.

And the present proof v2 RFC:

> The messages that include `~attach` attachments may use any form of the embedded attachment. In the examples below, the forms of the attachment are arbitrary.

@sklump maybe something to take into account for present proof v2? Otherwise we'll make sure to adjust this when adding the new format.

**Comment by sklump** [comment]
I'll take it on this week
