### ISSUE TITLE
AriesOpenAPIDemo Docs need to be updated

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#988]
The doc on this link: https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AriesOpenAPIDemo.md is outdated. It still shows faber and alice as two agents will set up 1st connection step by step whereas the latest code shows this process can be automated when attributes "--auto-accept-invites" is enabled. Please update this doc.

**Comment by sklump** [comment]
I suspect that you might have omitted the `--no-auto` parameter as the doc prescribes.

Regardless, as of https://github.com/hyperledger/aries-cloudagent-python/pull/992, the error message notes that the connection record is not available in the invitation state, when the (RFC160) responder double-taps the accept-invitation step for a received invitation.
