### ISSUE TITLE
Lack of a method to reject a present-proof request 

### ISSUE THREAD

**Issue by maddocche** [hyperledger/aries-cloudagent-python#994]
Hi,
it seems that there's no way to cancel\reject a present-proof request if there's no credentials that satisfies it.

Example:
 - verifier call _/present-proof/send-request_ endpoint with a proof request
 - prover call _/present-proof/records/{pres-ex-id}/credentials_ endpoint to look for a credentials that satisfies the request
 - this last call return an empty list

Now both prover and verifier are stuck with a present-proof request that they cannot cancel. 
From the [present proof choreography diagram](https://github.com/hyperledger/aries-rfcs/tree/4fae574c03f9f1013db30bf2c0c676b1122f7149/features/0037-present-proof#choreography-diagram) it seems that there should be a way to reject a presentation, from both sides. But there's no endpoint to do that, and sending an empty presentation gives back an error. 

Maybe there should be a problem-report endpoint for the proof-request protocol, like there's one for the issue-credential protocol.

**Comment by swcurran** [comment]
I agree there should be a "problem-report".  @sklump -- can you include this in your V2 work for now?  After we can consider for the V1 implementation.

@nodlesh -- eventually, we will want to get a test case for this into the Aries Agent Test Harness.  Send a proof request from Faber to Bob for credentials that Bob does not hold.

**Comment by sklump** [comment]
`POST /present-proof/records/{pres_ex_id}/problem-report`
`POST /present-proof-2.0/records/{pres_ex_id}/problem-report`
