### ISSUE TITLE
Creating a credential definition always causes an error for the 1st time, but will be successful for the 2nd time

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#996]
When running agent in v0.6.0-rc0, whenever creating a credential definition for the 1st time, it always causes an error as shown below. When creating the same credential definition again for the 2nd time, it will be successful.

> 2021-02-25 10:44:41,144 aries_cloudagent.admin.server ERROR Handler error with exception: tails_server_base_url not configured
> 
> =================
> Traceback (most recent call last):
>   File "/home/indy/aries_cloudagent/admin/server.py", line 164, in ready_middleware
>     return await handler(request)
>   File "/home/indy/aries_cloudagent/admin/server.py", line 201, in debug_middleware
>     return await handler(request)
>   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
>     return await handler(request)
>   File "/home/indy/aries_cloudagent/admin/server.py", line 362, in setup_context
>     return await task
>   File "/home/indy/aries_cloudagent/messaging/credential_definitions/routes.py", line 167, in credential_definitions_send_credential_definition
>     raise web.HTTPBadRequest(reason="tails_server_base_url not configured")
> aiohttp.web_exceptions.HTTPBadRequest: tails_server_base_url not configured 

Expected behaviour:
It should work for the first time.

**Comment by swcurran** [comment]
@sklump @andrewwhitehead  @ianco -- please check this out.  Is this is a general problem that we need to fix before 0.6.0?

**Comment by ianco** [comment]
I haven't seen this issue, @yunxi-zhang can we get more details about your aca-py setup and how you are creating your schema/credential definition?

**Comment by yunxi-zhang** [comment]
sure @ianco. I have two Azure VMs - Linux (ubuntu 18.04) running on the cloud. **VM1** runs a **von dev network** + **Issuer agent**, and **VM2** runs the **Holder agent**. I run the von network first, and register DIDs for the two agents as "Endorsor". Then run the **Issuer agent** by using the below attributes:

> PORTS="8000:8000 8001:8001" \
> ./run_docker start \
> -l Issuer \
> -it http 0.0.0.0 8000 \
> -ot http \
> --admin 0.0.0.0 8001 \
> --admin-insecure-mode \
> -e http://{vm1 ip}:8000 \
> --genesis-url http://{vm1 ip}:9000/genesis \
> --wallet-type indy \
> --wallet-name issuerwallet \
> --seed issuer000(omit other 0 here) \
> --log-level 'info' \
> --auto-provision \
> --auto-accept-invites \
> --auto-accept-requests \
> --auto-respond-messages \
> --auto-ping-connection 

Credential Schema is shown below (calling api: vm1 ip:8001/schemas), **Note** the schema name is a bit sensitive, so i rename it to "myschema" here:

> {
>   "attributes": [
>     "score",
>     "badge",
>     "date"
>   ],
>   "schema_name": "myschema",
>   "schema_version": "0.1"
> }

credential definition (calling api: vm1 ip:8001/credential-definitions):

> {
>   "revocation_registry_size": 1000,
>   "schema_id": "VV9pK5ZrLPRwYmotgACPkC:2:myschema:0.1",
>   "support_revocation": true,
>   "tag": "default"
> }

Let me know if you need more information from me.

**Comment by ianco** [comment]
The issue is that revocation isn't configured when you start aca-py.  For example when I started aca-py with your configuration and then tried to create the credential definition I got this error:

`400: tails_server_base_url not configured`

I think what happens is that the cred def is written to the ledger *before* this error occurs, and then the second time you execute this query, aca-py determines that the cred def is already on the ledger and therefore returns success.

To use revocation you need to run a tails server and then pass the `--tails-server-base-url` parameter to aca-py on startup

**Comment by ianco** [comment]
@swcurran @andrewwhitehead  should prob re-factor the revocation check when creating a cred def to do the check *before* the cred def is written to the ledger (if this is what is going on)

**Comment by yunxi-zhang** [comment]
Thanks for the response @ianco , actually don't know what "tails_server_base_url" mean when I see the error. Are there any docs available to this tails server concept I can have a look?

**Comment by ianco** [comment]
Revocation is described in one of the demo tutorials:  https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/AliceGetsAPhone.md#run-an-instance-of-indy-tails-server

I'm not sure where else it's described, @swcurran ?

**Comment by yunxi-zhang** [comment]
Just found this link: https://github.com/bcgov/indy-tails-server. Is this the tails server you normally use?

**Comment by ianco** [comment]
Yes it's described in the link I referenced above

**Comment by yunxi-zhang** [comment]
Thanks @ianco , the link you gave is only showing how to run a tails server. My question is more about to understand what a tails server is. I see this wiki page: https://en.wikipedia.org/wiki/Tails_(operating_system)#:~:text=Tails%2C%20or%20The%20Amnesic%20Incognito,non%2Danonymous%20connections%20are%20blocked.&text=Tails%20comes%20with%20UEFI%20Secure%20Boot. Could you let me know if this wiki page the right one that explains the tails server used for Indy?

**Comment by ianco** [comment]
Hi @yunxi-zhang sorry misunderstood your question!

No that wiki page is not correct.  Indy credential revocation is described here:  https://github.com/hyperledger/indy-sdk/blob/master/docs/concepts/revocation/cred-revocation.md

A "tails file" (or an accumulator file) is required for each credential definition that requires revocation.  The tails file itself is not written to the ledger, but the location of the tails file is.  The tails file can be located anywhere that is accessible via url.

The tails server was written by the BC Government as a convenient utility for creating and managing tails files for indy revocation.

**Comment by yunxi-zhang** [comment]
Thanks for your valuable answer @ianco , will look at the link you gave :-)

**Comment by yunxi-zhang** [comment]
Hello @ianco , once i run the tails file server and got the ngrok https url, for running my agent, should I only need to add one more config: PUBLIC_TAILS_URL="{the ngrok https url in the container}" at the beginning of my current command as shown before or any other attributes I need to add as well to make the revocation work?

**Comment by ianco** [comment]
Can this issue be closed?

**Comment by yunxi-zhang** [comment]
Yes, this issue is gone after running the tails file server locally.
